### ISSUE TITLE
Production - LDRS 300 Unit 8

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#100]
### Course
LDRS 300
### URL
https://learn.twu.ca/course/view.php?id=10828&section=8
### Instructions
Please put the attached lesson online.
[LDRS300_U8_Oct22_KM.docx](https://github.com/TWUOnline/bug-tracking/files/3790567/LDRS300_U8_Oct22_KM.docx)

**Comment by rezakh66** [comment]
@cmadland can you please check if its updated in the right place?

**Comment by kmarjanovic** [comment]
I reorganized, so all good.  If time, please make activity checklist into alert.
Thank you!
