### ISSUE TITLE
uploading new syllabus

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#1002]
**Which course contains the bug?**  
PSYC 339 OL SU 2024
 
 
**Describe the error and/or your suggestion**  
Can you please replace the syllabus file with the updated version in this section: The syllabus includes key information about the course schedule, assignments, and policies. Please read the full course syllabus [here](https://far.twu.ca/arts/psyc339/home/Syllabus_Summer_2023.pdf)

Replace with this file: 
 
[PSYC339 OL SU24 Verseveldt.pdf](https://github.com/TWUOnline/bug-tracking/files/15398903/PSYC339.OL.SU24.Verseveldt.pdf)

 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=32869&section=0
2. Unit #  Course Overview       Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by chloecwh** [comment]
I'm on it

**Comment by chloecwh** [comment]
@emilyverse It's updated!

**Comment by emilyverse** [comment]
Thank you!
________________________________
