### ISSUE TITLE
FNDN 201 Word docs from Moodle

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#1003]
### Course
[FNDN 201 OL Master](https://docs.google.com/document/d/1Lj02hG1ZIQyVTyhefPlGFEwzcDduqHeo1iMt-bSSewQ/edit)

### Instructions
- [x] Please add FNDN 201 content from Moodle to word docs

@chloecwh could you let me know if these things would speed up the Production process:
- [x] Skip images (SMEs can refer to Moodle).  just add [insert image]
- [x] Skip H5Ps - add [insert H5P]
- [x] Skip video screenshot add [insert video]
- [x] Don't worry about formatting (editor will fix later)

What other items would help Production?

**Comment by kmarjanovic** [comment]
btw I tried adding Sandy ([SandyFranco33](https://github.com/SandyFranco33)) but she's not in this repo.

Do we need to add her as a member?  https://github.com/TWUOnline/bug-tracking/settings/access

**Comment by chloecwh** [comment]
> btw I tried adding Sandy ([SandyFranco33](https://github.com/SandyFranco33)) but she's not in this repo.
> 
> Do we need to add her as a member? https://github.com/TWUOnline/bug-tracking/settings/access

Hi @kmarjanovic, I looked at bug-tracking repo and added learning-design team to it. Most of us are under far-center, and that's why we have access to it.

**Comment by chloecwh** [comment]
@kmarjanovic @SandyFranco33 Is this the correct [master](https://learn.twu.ca/course/view.php?id=20628&section=7#tabs-tree-start)?

**Comment by kmarjanovic** [comment]
@chloecwh do you have an estimate for when this can be ready?

**Comment by chloecwh** [comment]
Hi @kmarjanovic I'm starting today and hoping to get it done on Monday.

**Comment by kmarjanovic** [comment]
okay thank you!

**Comment by chloecwh** [comment]
I had added the first three units to Shairpoint. Since it's postponed to mid June, let me know if you have any feedbacks for editing H5P contents... @kmarjanovic @SandyFranco33

**Comment by SandyFranco33** [comment]
[heart]         Sandra Franco reacted to your message:
________________________________

**Comment by chloecwh** [comment]
You can find the link [here](https://mytwu.sharepoint.com/:f:/s/LearningDesign/EpSjzccBtUVEvnoZp99qvdIBA3G3ckTQ5CDkNT0MO97YPw?e=FSwANA)
[U3-FNDN201.docx](https://github.com/user-attachments/files/15540695/U3-FNDN201.docx)
[U2-LDRS420.docx](https://github.com/user-attachments/files/15540696/U2-LDRS420.docx)
[U1-FNDN201.docx](https://github.com/user-attachments/files/15540697/U1-FNDN201.docx)

**Comment by SandyFranco33** [comment]
[like]  Sandra Franco reacted to your message:
________________________________

**Comment by chloecwh** [comment]
Hi @SandyFranco33 here are units 2-4. 
[U4-FNDN201.docx](https://github.com/user-attachments/files/15841585/U4-FNDN201.docx)
[U3-FNDN201.docx](https://github.com/user-attachments/files/15841586/U3-FNDN201.docx)
[U2-FNDN201.docx](https://github.com/user-attachments/files/15841588/U2-FNDN201.docx)

On [Sharepoint](https://mytwu.sharepoint.com/:f:/s/LearningDesign/EpSjzccBtUVEvnoZp99qvdIBA3G3ckTQ5CDkNT0MO97YPw?e=pQbJzV) I have add extra material for u2 and u4. I will continue to work on the units until Wednesday and Jeff will then take over while I'm on vacation.

**Comment by chloecwh** [comment]
PRODUCTION NOTE: videos are in [Dwight's folder ](https://mytwu-my.sharepoint.com/personal/dwight_friesen_twu_ca/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fdwight%5Ffriesen%5Ftwu%5Fca%2FDocuments%2FStream%20Migrated%20Videos%2FFNDN%20201&FolderCTID=0x0120004D86A45537375E459C861D231B263BD5&view=0)

He is responsive but I haven't request whole folder transfer

**Comment by chloecwh** [comment]
Added docs to FNDN 201 repo, IDs please communicate on this [issue](https://github.com/learning-commons/fndn201/issues/1)
