### ISSUE TITLE
Overview page update request

### ISSUE THREAD

**Issue by MaraChequer** [TWUOnline/bug-tracking#1006]
**Which course contains the bug?**  
- Course Code: Psyc 340
 
 
**Describe the error and/or your suggestion**  
Hello, I would like to request a slight change in the course Evaluation section in the Course Overview page of this course:

From SME: Can you ensure that the overview section with the grading chart matches what is noted in the assessment section (under Grading Assignments) where it has the assignment noted as "Exploration Written Essay...."?  The overview presently does not match the assessment section with this assignment.
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. Error shown in- URL:  https://learn.twu.ca/course/view.php?id=15808&section=0#tabs-tree-start
2. should be matching: https://learn.twu.ca/course/view.php?id=15808&section=7#tabs-tree-start
 
**Optional: Screenshots**  
Course Evaluation in Overview Tab should show this:

![image](https://github.com/TWUOnline/bug-tracking/assets/84353161/ceeff3cb-e6a6-4228-baf3-09ef146fc18d)

**Comment by Jeff-TWU** [comment]
@MaraChequer [Updated](https://learn.twu.ca/course/view.php?id=15808&section=0#tabs-tree-start).
