### ISSUE TITLE
LDRS 500 U2 edits

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#1007]
### Course
https://learn.twu.ca/mod/book/view.php?id=967448&chapterid=14404

### Instructions
- [x] [2.2 Functions of Servant Leadership](https://learn.twu.ca/mod/book/view.php?id=967448&chapterid=14403) - add new Learning Activities page with the info from the bottom of the page (Read: Coetzer,...)
- [x] Please fix formatting https://learn.twu.ca/mod/book/view.php?id=967448&chapterid=30409 
- [x] fix formatting  https://learn.twu.ca/mod/book/view.php?id=967448&chapterid=30424

@chloecwh For TOP - Units 1 and 2 are now ready to import from Notion.

Another question - I was trying to check the old bookdown of LDRS 500 for reference, but it appears the units are deleted? https://ma-lead.github.io/ldrs500/  It's difficult to navigate the old links ([LDRS 500 - FAR MASTER](https://learn.twu.ca/course/view.php?id=10719)  [LDRS 500 (Flexible)](https://learn.twu.ca/course/view.php?id=20751&section=0#tabs-tree-start)). 
How can we access LDRS 500 bookdown from 2023 (with all 10 units)? 2024 LDRS 500 has changed significantly so it would be helpful to see both versions.

**Comment by chloecwh** [comment]
Working on it

**Comment by chloecwh** [comment]
Added 2.2 [Learning Activity](https://learn.twu.ca/mod/book/view.php?id=967448&chapterid=34473) page, removed duplicated content from unit 2

**Comment by chloecwh** [comment]
@Jeff-TWU You were testing Notion export to Quarto, would you mind importing the first 2 units? Thank you!

**Comment by kmarjanovic** [comment]
> Added 2.2 [Learning Activity](https://learn.twu.ca/mod/book/view.php?id=967448&chapterid=34473) page, removed duplicated content from unit 2

Thanks @chloecwh !  On that [book](https://learn.twu.ca/mod/book/view.php?id=967448&chapterid=30408), could you please change the title of "Learning Activity" to "Learning Activities"?  I realize some of those sections will only have 1 activity, but that way it's less for SMEs to edit when they add/delete activities.  (& it follows the [MA Lead template](https://learn.twu.ca/course/view.php?id=30164&section=4))

**Comment by chloecwh** [comment]
@kmarjanovic Updated all unit books with "Learning Activities"

**Comment by chloecwh** [comment]
Hi @kmarjanovic 
Since there were updates on MB, is Notion or MB the most up to date? 

_How can we access LDRS 500 bookdown from 2023 (with all 10 units)? 2024 LDRS 500 has changed significantly so it would be helpful to see both versions._

2023: https://ma-lead.github.io/ldrs500/
2024: Which Moodle shell consist of it? The FAR master appears broken on my end as well. 


![Screenshot 2024-06-27 at 3 09 32 PM](https://github.com/TWUOnline/bug-tracking/assets/150065592/b0016e21-f94a-43a0-bb58-3c35131342a4)

**Comment by chloecwh** [comment]
Reply from @kmarjanovic : Notion is most up to date, but an Editor will step into work this week and continue edit Notion page. 

Production work on pause @Jeff-TWU

**Comment by kmarjanovic** [comment]
@chloecwh 
All the edits made in Notion (that are confirmed by SMEs) are now in Moodle Books as well.  
There are a couple items I'm still waiting for SME feedback on, so the notes remain in Notion.
Jeff & Sandy are also working on graphics which can be added to Notion for now, and MB when confirmed.

At our mtg yesterday I believe we confirmed editor for MA Lead will work in Moodle (week tabs, assessment tabs, and Moodle Books need editing).  When complete, I'll send a Production request to copy the MB content to Quarto.

All other courses (electives, BA Lead, PSYC) will be edited in Quarto.

Does that work for Production?

**Comment by chloecwh** [comment]
That works for production! @kmarjanovic
