### ISSUE TITLE
Instructor Guide in PSYC 340 OL pointing to outdated content

### ISSUE THREAD

**Issue by barishgolland** [TWUOnline/bug-tracking#1009]
**Which course contains the bug?**  
(https://far.twu.ca/arts/psyc340adc/instructor-guide/chromeless:true/hidepagetitle:true#instructor-guide-for-psyc-340)
 
**Describe the error and/or your suggestion**  
Instructor Guide links all point to outdated content in create.twu.ca/help

 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://create.twu.ca/help/moodle/faculty/activity-or-resource/creating-an-assignment-dropbox
https://create.twu.ca/help/moodle/faculty/show-hide
https://create.twu.ca/help/online-learning-on-ramp/running-a-session/conferencing/managing-videos

 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
Hi Barish,
I thought this guide was discontinued years ago.  @cmadland wasn't there a note on the main page directing faculty to the knowledge base?
PS - Barish you may want to update your Bug Report link, as it lists the assignees (e.g. meher).  It's best to go to the main bug page and then select from there.

https://github.com/TWUOnline/bug-tracking/issues/new/choose

**Comment by chloecwh** [comment]
Updated bug-tracking assignees name! 

Would you like me to delete the "instructor guide" tab on [Moodle](https://learn.twu.ca/course/view.php?id=15808&section=14#tabs-tree-start)? @kmarjanovic @cmadland

**Comment by kmarjanovic** [comment]
Hi Chloe,
We don't want to delete the instructor's guide.  It's just the one section that's outdated.  Please replace the section "Instructor To-Do List For New Course Sections" with this info:

There are a few things you should do before the semester starts to ensure that your students have a smooth transition to studying with you.

✔️ Receive confirmation of course code and Moodle access info.

✔️ Import content from your previous cohort: If yours is a new course, the Online team can add you to the Master course shell so you can import from there to your new section. If importing from a previous course, delete items that you no longer need.

✔️ Add a syllabus: You will need to change the dates in the syllabus, make sure it is a pdf version, get approval from the department chair, and upload it to Moodle on the Course Introduction tab.

✔️ Add a welcome message: Add an Announcement forum at the bottom of the Course Introduction page. To welcome your new students, tell them about yourself and how to reach you (e.g. TWU email), and perhaps share an encouraging Bible verse or what interests you about this course. If you feel up to it, add a video welcome message!

✔️ Check the course materials: You may notice that this fully developed online course has a lot of material, including videos, unit writing, and external links. If possible, please check for broken links and send a message to our online team (elearning@twu.ca) so we can help you fix any errors.

✔️ Check the Assignment details and due dates: Due dates should be found in your course syllabus, but they may also be in your Discussion Forums and/or Assignment dropboxes. Please check that those dates are correct. Also add or edit the Assignment dropboxes (if they are missing). Confirm assessment details, such as due dates (can be added to the title of dropboxes if desired).

✔️ Check the Gradebook: Please double check that all assessment material is correct, including the percentages in the course Gradebook.

✔️ Prepare for Synchronous sessions: If you have synchronous Zoom Meetings in your course, you will need to become familiar with the following:

- Scheduling class meetings
- Recording Zoom Meetings
- Adding the recorded session to Microsoft Stream
- Embedding videos into Moodle 

✔️ Use Announcements for Weekly encouragement and review.

✔️ Course Visibility: Your course is visible to you as the instructor, but it is hidden from students. When you are ready, make your course visible to students. Your course will move from the 'Future' tab on your dashboard to the 'In progress' tab on the date indicated in the 'Start date' field of the course settings.

For instructions on how to set up your course in Moodle, please see the [Moodle Knowledge Base articles](https://trinitywestern.teamdynamix.com/TDClient/1904/Portal/KB/?CategoryID=4747). (Be sure to sign into the Knowledge Base so you have access to all instructor materials.

**Comment by kmarjanovic** [comment]
And one more change: in the last section:
Editing content in Github:
Our TWU Online team can help you with any changes you want to make to the course materials. Please email elearning@twu.ca or click on the following link to [Send a Bug report](https://github.com/TWUOnline/bug-tracking/issues/new/choose) to our team.

**Comment by chloecwh** [comment]
Updated as you request! @kmarjanovic

**Comment by kmarjanovic** [comment]
Thanks so much, @chloecwh !
