### ISSUE TITLE
Grad Student Orientation: Moodle Book Production

### ISSUE THREAD

**Issue by inoklim-twu** [TWUOnline/bug-tracking#1011]
### URL
https://learn.twu.ca/course/view.php?id=33082&section=1

### Instructions
- [X] Module 1 – [Life at TWU ](https://mytwu.sharepoint.com/:w:/r/sites/GraduateStudentOrientationTaskForce/_layouts/15/Doc2.aspx?action=edit&sourcedoc=%7B5e473ec8-e934-4445-af4c-4da25e89029e%7D&wdOrigin=TEAMS-MAGLEV.teamsSdk_ns.rwc&wdExp=TEAMS-TREATMENT&wdhostclicktime=1720725138742&web=1) (Inok)
- [x] Module 2 – [Life in Canada](https://mytwu.sharepoint.com/:w:/r/sites/GraduateStudentOrientationTaskForce/_layouts/15/Doc2.aspx?action=edit&sourcedoc=%7B5e473ec8-e934-4445-af4c-4da25e89029e%7D&wdOrigin=TEAMS-MAGLEV.teamsSdk_ns.rwc&wdExp=TEAMS-TREATMENT&wdhostclicktime=1720725138742&web=1) (Chloe)
- [x] Module 3 – [Spiritual Development](https://mytwu.sharepoint.com/:w:/r/sites/GraduateStudentOrientationTaskForce/_layouts/15/Doc2.aspx?action=edit&sourcedoc=%7Bc9f9bfe9-c2d3-4e0e-8489-fcb25d5e9db4%7D&wdOrigin=TEAMS-MAGLEV.teamsSdk_ns.rwc&wdExp=TEAMS-TREATMENT&wdhostclicktime=1720725343758&web=1) (Inok)
- [x] Module 4 – [Your Academic Journey](https://mytwu.sharepoint.com/:w:/r/sites/GraduateStudentOrientationTaskForce/_layouts/15/Doc2.aspx?action=edit&sourcedoc=%7Be0969dae-bbca-479d-8b9e-c3ad4b69bda9%7D&wdOrigin=TEAMS-MAGLEV.teamsSdk_ns.rwc&wdExp=TEAMS-TREATMENT&wdhostclicktime=1720725348160&web=1) 
- [x] Module 5 – [Health and Wellness](https://mytwu.sharepoint.com/:w:/r/sites/GraduateStudentOrientationTaskForce/_layouts/15/Doc2.aspx?action=edit&sourcedoc=%7Bdf63cc76-5445-44d3-8e9e-4162c03f1415%7D&wdOrigin=TEAMS-MAGLEV.teamsSdk_ns.rwc&wdExp=TEAMS-TREATMENT&wdhostclicktime=1720725352351&web=1)
- [x] Module 6 – [Finances](https://mytwu.sharepoint.com/:w:/r/sites/GraduateStudentOrientationTaskForce/_layouts/15/Doc2.aspx?action=edit&sourcedoc=%7B3fc25961-30a1-45d8-80a0-3e6e451cc5e0%7D&wdOrigin=TEAMS-MAGLEV.teamsSdk_ns.rwc&wdExp=TEAMS-TREATMENT&wdhostclicktime=1720725355826&web=1)
- [x] Module 7 – [Housing & Campus Services](https://mytwu.sharepoint.com/:w:/r/sites/GraduateStudentOrientationTaskForce/_layouts/15/Doc2.aspx?action=edit&sourcedoc=%7Ba74edae4-a1f0-4967-86a6-2fded9a2dbce%7D&wdOrigin=TEAMS-MAGLEV.teamsSdk_ns.rwc&wdExp=TEAMS-TREATMENT&wdhostclicktime=1720725358676&web=1)

**Comment by inoklim-twu** [comment]
@chloecwh 
Can you help create Module 2?

**Comment by chloecwh** [comment]
Back up purposes
[Module 7 – Housing & Campus Services.docx](https://github.com/user-attachments/files/16184215/Module.7.Housing.Campus.Services.docx)
[Module 6 – Finances.docx](https://github.com/user-attachments/files/16184217/Module.6.Finances.docx)
[Module 5 - Health and Wellness.docx](https://github.com/user-attachments/files/16184218/Module.5.-.Health.and.Wellness.docx)
[Module 4 – Academic Success.docx](https://github.com/user-attachments/files/16184219/Module.4.Academic.Success.docx)
[Module 3 – Spiritual Development.docx](https://github.com/user-attachments/files/16184220/Module.3.Spiritual.Development.docx)
[Module 2 – Life in Canada.docx](https://github.com/user-attachments/files/16184221/Module.2.Life.in.Canada.docx)
[Module 1 - Life at TWU.docx](https://github.com/user-attachments/files/16184222/Module.1.-.Life.at.TWU.docx)

**Comment by chloecwh** [comment]
PRODUCTION NOTES: quizzes in the bottom of the assessments will be combined into a final quiz in Moodle, see [comment](https://mytwu.sharepoint.com/:w:/r/sites/GraduateStudentOrientationTaskForce/Shared%20Documents/Content%20Development%20and%20Sequencing/Module%20Content%20Documents/Module%202%20%E2%80%93%20Life%20in%20Canada.docx?d=w5e473ec8e9344445af4c4da25e89029e&csf=1&web=1&e=Gifirg&nav=eyJjIjo1ODQ4NDg2OTl9)

**Comment by chloecwh** [comment]
Need to have it by the end of month, with inline CSS styling

**Comment by kmarjanovic** [comment]
@chloecwh @inoklim-twu 
I'm adding the units to the folder - Learning Design > [Grad student orientation](https://mytwu.sharepoint.com/:f:/r/sites/LearningDesign/Shared%20Documents/Graduate%20Student%20Orientation?csf=1&web=1&e=CHKUXU)

I resolved the comments in the doc.  Chloe please let me know if I should delete them for a clean copy.

**Comment by chloecwh** [comment]
Sounds good! I can see the first 3 units, do we plan to have a separate doc with all the quizes? @kmarjanovic @inoklim-twu

**Comment by kmarjanovic** [comment]
Hi Chloe - I've started one [here](https://mytwu-my.sharepoint.com/:w:/r/personal/kelly_marjanovic_twu_ca/Documents/Documents/TWU/Grad%20Orientation/Assessment%20for%20Grad%20Orientation.docx?d=w7d49dae5dac44154a519f4b71d7f39bc&csf=1&web=1&e=9l0bIL) but it's not ready for Production

**Comment by kmarjanovic** [comment]
Update: Waiting for SME content for one section in Unit 6 (we can add later if production wants to go ahead).  I'll confirm quiz/test questions with SMEs on Monday.  
[Assessment doc for Final Moodle Test](https://mytwu-my.sharepoint.com/:w:/r/personal/kelly_marjanovic_twu_ca/Documents/Documents/TWU/Grad%20Orientation/Assessment%20for%20Grad%20Orientation.docx?d=w7d49dae5dac44154a519f4b71d7f39bc&csf=1&web=1&e=4zoqPV)

Thanks all!

**Comment by chloecwh** [comment]
Hi @kmarjanovic @inoklim-twu, I've downloaded the docx folder, but because they are uploaded as url, I can't open them locally. 

- I renamed them, but still can't open them with Word. 
- I copied the web version to a new doc but the headings were not copied over. 

Would you mind re-uploading the files?

**Comment by kmarjanovic** [comment]
updated files (copy).  Please let me know if that works.

**Comment by chloecwh** [comment]
Thanks!
