### ISSUE TITLE
LDRS 500 Assignment to word doc

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#1014]
### Course
LDRS 500
### URL
[Assessment info in notion
](https://www.notion.so/twuid/Assessment-983afdb3c90a422bb0b310f4f2bbf025)

### Instructions
- [x] Please convert the assignment info to word so Deb can edit it.
- [x] Note it doesn't need Quarto, as all assignment info is in Moodle (or do you keep a backup file in quarto of assessment?)

Thank you!

**Comment by chloecwh** [comment]
[LDRS 500-assessment.docx](https://github.com/user-attachments/files/16435018/LDRS.500-assessment.docx)

@kmarjanovic here you go!

**Comment by kmarjanovic** [comment]
Thanks Chloe!
