### ISSUE TITLE
Class recording videos are not posting well 

### ISSUE THREAD

**Issue by SonyaCameron** [TWUOnline/bug-tracking#1015]
**Which course contains the bug?**   
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 
[](https://learn.twu.ca/course/view.php?id=32864 )
Psyc 215 OL SU 2024 

**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 
I record class on Zoom and save it to my computer.  Then when class is over, I process the video and upload it to Microsoft Stream. 
When I try to upload a link of the Class recordings page in the moodle, it is not working.  I have to fiddle around and try a few ways and eventually something works.  But it's taking way too long and it's only sometimes a hyperlink.  
I've tried sharing access with a group, the group of students in the class by clicking on "share" and selecting the course group.  Usually this works, but this week the students still didn't have access.  I re-sent the invitation to view link and maybe they all have access now.  
**When I try to copy the link to the class video onto the Class Recordings page in the course moodle, and make it an active link, it won't work.**  
An image of a video box shows on the page, but when you go to click "play" on the video, it won't play.  You'll see one of these currently on the page.  I've deleted the other broken links and video boxes that don't work.  
Will you kindly tell me what I need to do, step by step?!  
Thanks for any help!! 

**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:

1. URL:    https://learn.twu.ca/course/view.php?id=32864&section=13#tabs-tree-start  Class Meetings and Recordings page.  Weekly class video recordings are not linking and posting correctly.             2 . . Unit #         Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by SonyaCameron** [comment]
Course location:  https://learn.twu.ca/course/view.php?id=32864

**Comment by kmarjanovic** [comment]
Thank you Sonya for bringing up this issue!  @barishgolland could you or Man help Sonya?

**Comment by SonyaCameron** [comment]
Kelly, thanks for following up on this!   I have an appointment schedule with Man for Friday @11:30am PST to get tech support for this course and moodle.  Yay!

**Comment by kmarjanovic** [comment]
Great to hear! :)
