### ISSUE TITLE
Learning Online tab for TOP template

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#1021]
Please add [LO tab from TOP template](https://learn.twu.ca/course/view.php?id=33023&section=4) to 5 TOP courses

- [x] [LDRS 330: Leadership in Organizations & Small Groups](https://learn.twu.ca/course/view.php?id=34886)
- [x] [LDRS 400: Interpersonal Leadership: Negotiation & Conflict Resolution](https://learn.twu.ca/course/view.php?id=34888&section=0)
- [x] [LDRS 471: Global Analysis & Political Leadership](https://learn.twu.ca/course/view.php?id=34895&section=0)
- [x] [LDRS 500: Leadership Foundations](https://learn.twu.ca/course/view.php?id=34894)
- [x] [LDRS 502: Team Leadership & Conflict Resolution](https://learn.twu.ca/course/view.php?id=34893)

**Comment by chloecwh** [comment]
Hi @Jeff-TWU , would you mind helping 500 and 502?

**Comment by chloecwh** [comment]
Workflow 
1. backup of selected course
2. reorder tabs
3. delete community tab 
4. import TWU-OL community and learning online tabs
5. check all the elements (especially assessment info) 

Note: course evolution was mentioned twice 
ordered list was not in bullet format
learning outcome glossary is not done

**Comment by chloecwh** [comment]
Note: embedded links needs to be updated manually 

course introduction tab - assessment section
assessment - Assignment Feedback & Grading

**Comment by chloecwh** [comment]
@kmarjanovic updated accordingly!

**Comment by chloecwh** [comment]
Note: 
1. CORRECTED font and html issues https://learn.twu.ca/course/view.php?id=33023&section=3#module-1106696
2. Suggested due dates in Course Evaluation (Course Intro) are centered or aligned to the left? Same table Assesses Course Learning Outcome(s) with an s? @Nataliadsanchez @kmarjanovic

**Comment by chloecwh** [comment]
Note:

Learning online tab update order 

1. Course Introduction
2. Course Units
3. Community Engagement
4. Assessment

**Comment by chloecwh** [comment]
Note from [smoke test](https://mytwu.sharepoint.com/:x:/r/sites/TWUOnline/_layouts/15/Doc.aspx?sourcedoc=%7B011ED502-5327-4C64-BA47-1E06B9EEE54A%7D&file=TOP%20PoC%20Smoke%20Test%20-%20Courses.xlsx&wdLOR=cC487DDC6-97FA-0E47-9682-9CAE237B2BAF&fromShare=true&action=default&mobileredirect=true): 

Course Evaluation table shows incorrect hard-coded fonts (Times New Roman) - https://learn.twu.ca/course/modedit.php?update=1107585&return=0&sr=0

**Comment by chloecwh** [comment]
completed requests above
