### ISSUE TITLE
Production - LDRS 410 U4 & 7

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#103]
### Course
LDRS 410
### URL
https://learn.twu.ca/course/view.php?id=10720&section=4
### Instructions

Please format Units 4 & 7 (files in GitHub)

**Comment by faitht1023** [comment]
@kmarjanovic I've added and formatted U4, missing a couple links in the assessment tab and learning activity 4.6

**Comment by rezakh66** [comment]
@kmarjanovic Unit 7 topic 5 is missing in the file. I continue for rest of the topics for now

**Comment by rezakh66** [comment]
@kmarjanovic Unit 7 activity 7.6 is under topic 7 but activity 7.7 is under topic 6. can you please advise on this?

**Comment by kmarjanovic** [comment]
all fixed. Thank you!
