### ISSUE TITLE
Production - LDRS 663 - Comply TOP template and Create Word Doc

### ISSUE THREAD

**Issue by inoklim-twu** [TWUOnline/bug-tracking#1031]
### Instructions
- [ ] Comply TOP template
- [ ] Create Word Doc

Please upload required files as attachments.

**Comment by chloecwh** [comment]
LDRS 663 [Moodle master](https://learn.twu.ca/mod/book/view.php?id=1076016)
Github repos: 
![Screenshot 2024-08-23 at 11 19 38 AM](https://github.com/user-attachments/assets/bd0c032f-8b9d-4143-89e9-3df83545ef77)
![Screenshot 2024-08-23 at 11 19 35 AM](https://github.com/user-attachments/assets/dc506076-b99a-48c9-8481-4cfb7ea222c4)

@inoklim-twu @cmadland which one is the latest version to convert to Word?

**Comment by inoklim-twu** [comment]
@chloecwh 
[Latest Repo]([https://github.com/ma-lead/ldrs663](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fma-lead%2Fldrs663&data=05%7C02%7CInok.Lim%40twu.ca%7C855bec85183647b9478808dcc39fab33%7C2b4ef155167343efa480230c3d483f16%7C0%7C0%7C638600337744665281%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=d1%2FM7RVr03kmUVV5yRPv6G87TFr80Ib6QZ9l2aBS97E%3D&reserved=0))

**Comment by cmadland** [comment]
There's no need to convert to Werd on this repo, and it seems like it's already quarto'd, so nothing for @chloecwh or @Jeff-TWU to do.
