### ISSUE TITLE
GX course import FA 2024

### ISSUE THREAD

**Issue by chloecwh** [TWUOnline/bug-tracking#1032]
Course start date: Sept 16

Instructions: Import from GX master to FA 2024 shells

- [x] ANTH 101  X2 | Introduction Cultural Anthropology
- [x] ENGL 102  X2 | Introduction to World Literature
- [ ] FNDN 101  X1 | The Liberal Arts Journey
- [ ] LDRS 101  X1 | Learning with Technology
- [ ] MCOM 221  X2 | Digital Filmmaking
- [ ] MCOM 281  X1 | Public Speaking 
- [ ] PHIL 100  X1 | Philosophy for Life
- [ ] PHIL 210  X1 | Contemporary Ethical Issues
- [ ] PSYC 105  X2 | Introduction to Psychology
- [ ] PSYC 106  X1 | Introduction to Psychology
- [ ] SOCI 101  X1 | Introduction to Sociology
- [ ] WRTG 101  X1 | Writing and Culture

Update GX Master
- [x] ANTH 101 
- [x] ENGL 102 
- [x] FNDN 101 
- [x] LDRS 101  
- [x] MCOM 221  
- [ ] MCOM 281  (Can't find)
- [x] PHIL 100  
- [x] PHIL 210 
- [x] PSYC 105  
- [x] PSYC 106  
- [x] SOCI 101 
- [x] WRTG 101

**Comment by chloecwh** [comment]
@cmadland @kmarjanovic Any further instructions on importing FAR courses? The course list is from Colin's email thread

**Comment by cmadland** [comment]
still waiting to hear back from DeAnn

**Comment by chloecwh** [comment]
I noticed on [ENGL 102 GX master](https://learn.twu.ca/course/view.php?id=32162)  [STUDENT GUIDE TO ONLINE LEARNING ](https://www.twu.ca/online-learning) link is not working

Online Learning Orientation
For information on how to navigate through this course on Moodle, see the [MOODLE GUIDE ](http://create.twu.ca/help/moodle). Also see the [STUDENT GUIDE TO ONLINE LEARNING ](https://www.twu.ca/online-learning)for some tips on how to be successful in the online learning environment.

**Comment by kmarjanovic** [comment]
@chloecwh - this sentence should be updated (from our top template: )

For information on how to navigate through this course on Moodle, see the [TWU Support Pages](https://trinitywestern.teamdynamix.com/TDClient/1904/Portal/KB/?CategoryID=4747).

**Comment by kmarjanovic** [comment]
Also...
- [ ] please hide the Guides page.  
- [ ] the glossary tab can be deleted (I think we were just playing around with that. 

Tomorrow let's discuss Discourse & GX.

**Comment by chloecwh** [comment]
PRODUCTION: flagging PSYC 105 intro video need access https://learn.twu.ca/course/view.php?id=32192

**Comment by kmarjanovic** [comment]
No - WRTG 101 is not in bookdown (please check [Course Units section](https://learn.twu.ca/course/view.php?id=30221&section=2#tabs-tree-start))

It looks like this is the [master](https://learn.twu.ca/course/view.php?id=30205&section=0#tabs-tree-start)

I would double check the latest GX - e.g. https://learn.twu.ca/course/view.php?id=27293

Not sure the process here...Does Production let @emmanuelD-AFK or the Instructor know when the import is complete so they can check it's correct?

**Comment by kmarjanovic** [comment]
@chloecwh let's update our [GX master links](https://www.notion.so/twuid/FAR-GXP-Courses-9efebda59ba34d54aa46803a98fe0373) so it's clear what production should import

**Comment by chloecwh** [comment]
> https://learn.twu.ca/course/view.php?id=30221&section=0

Hi @kmarjanovic I'm not sure what I can update on the Notion page. Which column can I update?

**Comment by chloecwh** [comment]
Morning @cmadland and @kmarjanovic , I'm unsure what I can help with on importing FA GX courses. I've updated the masters with new information, but haven't heard back on which course needs to be imported.

**Comment by cmadland** [comment]
@chloecwh did you email the GX instructors? IIRC there are only a few courses that have any learners registered. Joel can confirm numbers and courses.

**Comment by chloecwh** [comment]
@cmadland No, I haven't email the instructors. Can you clarify the workflow of it? Do I check if the list of your last email of FA24 GX Courses (Aug 26, 2024), example FNDN 101  X1, and then go to the fall shall and see if it's empty, if the shell is empty then email instructor to see if they need assistance and CC'ed you and Joel on it? 

The first two courses I had imported before realizing I need to email the instructor...

**Comment by kmarjanovic** [comment]
Just figuring out the quality check process here...Should Chloe send email to Emmanuel (& Colin & Kelly) to let us know the courses are ready for a final Quality review?
Or contact instructors first to let them know their shells are ready?

**Comment by emmanuelD-AFK** [comment]
@ Kelly,
I thought production will do the import! You asked me to send a request on GitHub. As soon as it is available the instructor and facilitator will be notified!
Has the flow changed?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kmarjanovic** [comment]
@emmanuelD-AFK - Yes - Production is doing the import.  Just wondering the steps for Quality Review & communicating with instructors. (Who contacts instructors? Who is notified for review?)

**Comment by emmanuelD-AFK** [comment]
I can notify the instructors and ask them to contact production for review if needed! Therefore, production should inform me when the courses are already in their respective shell!
Blessings!

Emmanuel Denguessi, MA, GCA.ed, BA, Dip, CLC

Part- Time Faculty - Academic Facilitation Specialist Coordinator & Instructor Liaison

 Far Center Overhead | TWU Global

Trinity Western University | e. ***@***.***

twu.ca<http://www.twu.ca/>/ 778-552-4861


[cid:0c0fae29-dbf6-4698-9a86-c53e5b2c89a7]

________________________________

**Comment by kmarjanovic** [comment]
Perfect!  Thanks for the clarity, @emmanuelD-AFK  :)

**Comment by kmarjanovic** [comment]
@chloecwh I've added a "To import" note in the [GX Moodle links page](https://www.notion.so/twuid/FAR-GXP-Courses-9efebda59ba34d54aa46803a98fe0373).

**Comment by chloecwh** [comment]
closing this issue and continuing discussion on https://github.com/twu-fhss/phil210/issues/7
