### ISSUE TITLE
Word files for LDRS 471

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#1033]
[LDRS 471](https://learn.twu.ca/course/view.php?id=34895&section=0)

@chloecwh @MaraChequer - I'd like to send LDRS 471 to editing, but need clarification on some things.

Are the [Original Word Files from Grav](https://mytwu.sharepoint.com/:f:/r/sites/LearningDesign/Shared%20Documents/Innovation%20Certificates/LDRS%20471/Original%20word%20files%20from%20Grav?csf=1&web=1&e=ER1tZm) the most recent?

Have there been other edits to the course?  I couldn't find any issue in [bug-tracking](https://github.com/orgs/TWUOnline/projects/29), and there doesn't seem to be a place in the [LDRS 471 repo](https://github.com/twu-innovation/ldrs471) to create an issue.  

Could you help me locate those course edits?  I'm wondering whether to share those with our Editor as well so she can see what has changed in the course.

**Comment by chloecwh** [comment]
Hi @kmarjanovic This is the [correct repo](https://github.com/BA-Leadership/ldrs471/issues/17)! Will create the docs now!

**Comment by kmarjanovic** [comment]
Thanks Chloe!
