### ISSUE TITLE
Production import for FAR Centre in India

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#1034]
Course start date: Oct. 7

Instructions: Import from GX master (LDRS 101 - TOP Master) to FA 2024 shells (not sure if these are created yet, or what the course code is)

- [ ] FNDN 101  | The Liberal Arts Journey
- [ ] LDRS 101  | Learning with Technology (I'd like to use Deb's edited version, so will send to Production this week)
- [ ] SOCI 101   | Introduction to Sociology
- [ ] WRTG 101   | Writing and Culture

@cmadland & @emmanuelD-AFK - just wanted to clarify process (Production > Delivery).  Once we get info of a new offering, does Emmanuel send a Production request like this?

**Comment by chloecwh** [comment]
@cmadland @emmanuelD-AFK Following up on this issue, can I start the import?
