### ISSUE TITLE
[UNIV 301] e-Portfolio related bugs

### ISSUE THREAD

**Issue by inoklim-twu** [TWUOnline/bug-tracking#1035]
https://github.com/psyc-adc/univ301

### Bug Description
[Unit 1: Topic 2](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.twu.ca%2Fcourse%2Fview.php%3Fid%3D17766%26section%3D4%23tabs-tree-start&data=05%7C02%7CInok.Lim%40twu.ca%7Ce2776a737275411e229c08dccd3c4166%7C2b4ef155167343efa480230c3d483f16%7C0%7C0%7C638610905876479159%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=9WtS4aChegA96rXfaB2i4ec%2BhPMyP%2B2Ol7fybM2OIZw%3D&reserved=0) > Lesson 2:
 

- [How to create a website using WordPress video](https://mytwu-my.sharepoint.com/personal/melanie_laurie_twu_ca/_layouts/15/stream.aspx?id=%2fpersonal%2fmelanie_laurie_twu_ca%2fDocuments%2fStream+Migrated+Videos%2fPSYC+ADC+WordPress+Tutorial-20210529_080913.mp4&nav=eyJwbGF5YmFja09wdGlvbnMiOnsic3RhcnRUaW1lSW5TZWNvbmRzIjoyMy4yNjE2Mzh9fQ%3d%3d&referrer=StreamWebApp.Web&referrerScenario=AddressBarCopied.view.79dad573-d28b-4aae-95e9-ec553f1e25a9&xsdata=MDV8MDJ8SW5vay5MaW1AdHd1LmNhfGUyNzc2YTczNzI3NTQxMWUyMjljMDhkY2NkM2M0MTY2fDJiNGVmMTU1MTY3MzQzZWZhNDgwMjMwYzNkNDgzZjE2fDB8MHw2Mzg2MTA5MDU4NzY0OTQyNTZ8VW5rbm93bnxUV0ZwYkdac2IzZDhleUpXSWpvaU1DNHdMakF3TURBaUxDSlFJam9pVjJsdU16SWlMQ0pCVGlJNklrMWhhV3dpTENKWFZDSTZNbjA9fDB8fHw%3d&sdata=dWJhMnhLRFZ6dWZCVTQwZHNhS1BWRURseFFYcVYrdlpzTlBNLzErOXJFST0%3d) shows the old landing page (We will remove the video.) (Chloe to remove the link from Grav) - done
- Activity 2.2: Sign Up and Set Up. All the steps need to be updated as it’s using the older landing page and the theme (Twenty Seventeen) which is unavailable. (Inok)

 
[Unit 2: Topic 2](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.twu.ca%2Fcourse%2Fview.php%3Fid%3D17766%26section%3D7%23tabs-tree-start&data=05%7C02%7CInok.Lim%40twu.ca%7Ce2776a737275411e229c08dccd3c4166%7C2b4ef155167343efa480230c3d483f16%7C0%7C0%7C638610905876510416%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=YwTODdagn3gwMzrokTk8zMMS8hpoVmNR0KFVh7lkw1M%3D&reserved=0) > Lesson 1:
 

- The 'WordPress Tutorials' banner link doesn’t work (it shows Stream (Classic) has been deprecated. - done
- Activity 4.2: Create your first blog post. The Themes link goes to the [TWU E-Portfolios](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcreate.twu.ca%2Feportfolios%2Fwordpress%2Fthemes%2F&data=05%7C02%7CInok.Lim%40twu.ca%7Ce2776a737275411e229c08dccd3c4166%7C2b4ef155167343efa480230c3d483f16%7C0%7C0%7C638610905876517824%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=EJdegSqYwXYFhY91LKkswp%2FJQWKjD8bNuvwd9hHo8AU%3D&reserved=0) website, and some templates are unavailable. (Chloe to remove the link from Grav) -done

 
[Unit 4: Topic 2](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.twu.ca%2Fcourse%2Fview.php%3Fid%3D17766%26section%3D12%23tabs-tree-start&data=05%7C02%7CInok.Lim%40twu.ca%7Ce2776a737275411e229c08dccd3c4166%7C2b4ef155167343efa480230c3d483f16%7C0%7C0%7C638610905876524535%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=ox%2FMrDJC5eTUOb1fhr8%2FW2RQljZmJ0QAm6o9U4QyLaA%3D&reserved=0) > Lesson 3:
 
- Activity 7.3: Read and Reflect: [https://create.twu.ca/eportfolios/foundations/reflection/](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcreate.twu.ca%2Feportfolios%2Ffoundations%2Freflection%2F&data=05%7C02%7CInok.Lim%40twu.ca%7Ce2776a737275411e229c08dccd3c4166%7C2b4ef155167343efa480230c3d483f16%7C0%7C0%7C638610905876531397%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=s4eR%2FtEBWXVp5Q5A0Y3GsbRFGliPUIz1luzl%2BPNPpX4%3D&reserved=0). This page has a broken image under the Reflection Prompts section. (Fixed)

@chloecwh, can you please address the above issues?

**Comment by Jeff-TWU** [comment]
> https://github.com/psyc-adc/univ301
> ### Bug Description
> 
> [Unit 1: Topic 2](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.twu.ca%2Fcourse%2Fview.php%3Fid%3D17766%26section%3D4%23tabs-tree-start&data=05%7C02%7CInok.Lim%40twu.ca%7Ce2776a737275411e229c08dccd3c4166%7C2b4ef155167343efa480230c3d483f16%7C0%7C0%7C638610905876479159%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=9WtS4aChegA96rXfaB2i4ec%2BhPMyP%2B2Ol7fybM2OIZw%3D&reserved=0) > Lesson 2:
> 
>     * [How to create a website using WordPress video](https://mytwu-my.sharepoint.com/personal/melanie_laurie_twu_ca/_layouts/15/stream.aspx?id=%2fpersonal%2fmelanie_laurie_twu_ca%2fDocuments%2fStream+Migrated+Videos%2fPSYC+ADC+WordPress+Tutorial-20210529_080913.mp4&nav=eyJwbGF5YmFja09wdGlvbnMiOnsic3RhcnRUaW1lSW5TZWNvbmRzIjoyMy4yNjE2Mzh9fQ%3d%3d&referrer=StreamWebApp.Web&referrerScenario=AddressBarCopied.view.79dad573-d28b-4aae-95e9-ec553f1e25a9&xsdata=MDV8MDJ8SW5vay5MaW1AdHd1LmNhfGUyNzc2YTczNzI3NTQxMWUyMjljMDhkY2NkM2M0MTY2fDJiNGVmMTU1MTY3MzQzZWZhNDgwMjMwYzNkNDgzZjE2fDB8MHw2Mzg2MTA5MDU4NzY0OTQyNTZ8VW5rbm93bnxUV0ZwYkdac2IzZDhleUpXSWpvaU1DNHdMakF3TURBaUxDSlFJam9pVjJsdU16SWlMQ0pCVGlJNklrMWhhV3dpTENKWFZDSTZNbjA9fDB8fHw%3d&sdata=dWJhMnhLRFZ6dWZCVTQwZHNhS1BWRURseFFYcVYrdlpzTlBNLzErOXJFST0%3d) shows the old landing page
> 
>     * Activity 2.2: Sign Up and Set Up. All the steps need to be updated as it’s using the older landing page and the theme (Twenty Seventeen) which is unavailable.
> 
> 
> [Unit 2: Topic 2](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.twu.ca%2Fcourse%2Fview.php%3Fid%3D17766%26section%3D7%23tabs-tree-start&data=05%7C02%7CInok.Lim%40twu.ca%7Ce2776a737275411e229c08dccd3c4166%7C2b4ef155167343efa480230c3d483f16%7C0%7C0%7C638610905876510416%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=YwTODdagn3gwMzrokTk8zMMS8hpoVmNR0KFVh7lkw1M%3D&reserved=0) > Lesson 1:
> 
>     * The 'WordPress Tutorials' banner link doesn’t work (it shows Stream (Classic) has been deprecated.
> 
>     * Activity 4.2: Create your first blog post. The Themes link goes to the [TWU E-Portfolios](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcreate.twu.ca%2Feportfolios%2Fwordpress%2Fthemes%2F&data=05%7C02%7CInok.Lim%40twu.ca%7Ce2776a737275411e229c08dccd3c4166%7C2b4ef155167343efa480230c3d483f16%7C0%7C0%7C638610905876517824%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=EJdegSqYwXYFhY91LKkswp%2FJQWKjD8bNuvwd9hHo8AU%3D&reserved=0) website, and some templates are unavailable.
> 
> 
> [Unit 4: Topic 2](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.twu.ca%2Fcourse%2Fview.php%3Fid%3D17766%26section%3D12%23tabs-tree-start&data=05%7C02%7CInok.Lim%40twu.ca%7Ce2776a737275411e229c08dccd3c4166%7C2b4ef155167343efa480230c3d483f16%7C0%7C0%7C638610905876524535%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=ox%2FMrDJC5eTUOb1fhr8%2FW2RQljZmJ0QAm6o9U4QyLaA%3D&reserved=0) > Lesson 3:
> 
>     * Activity 7.3: Read and Reflect: [https://create.twu.ca/eportfolios/foundations/reflection/](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcreate.twu.ca%2Feportfolios%2Ffoundations%2Freflection%2F&data=05%7C02%7CInok.Lim%40twu.ca%7Ce2776a737275411e229c08dccd3c4166%7C2b4ef155167343efa480230c3d483f16%7C0%7C0%7C638610905876531397%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=s4eR%2FtEBWXVp5Q5A0Y3GsbRFGliPUIz1luzl%2BPNPpX4%3D&reserved=0). This page has a broken image under the Reflection Prompts section.
> 
> 
> @chloecwh, can you please address the above issues?

Here is [the context](https://2017-template-help.trubox.ca/portfolio-prompts/reflection/) for the misssing content from Unit 4: Topic 2, Lesson 3

**Comment by chloecwh** [comment]
Hi @inoklim-twu thanks for listing out the bugs. Can we all meet to talk about dividing workload? From updating the copy, capturing screenshots, updating GRAV and wordpress, and informing the SME there's a lot of elements to this issue.

**Comment by chloecwh** [comment]
I've updated https://create.twu.ca/eportfolios/foundations/reflection/ with the H5P from the [original site](https://2017-template-help.trubox.ca/portfolio-prompts/reflection/). @kmarjanovic is there a SME to this course? If not, how do we update instructions, specifically the copy?

**Comment by kmarjanovic** [comment]
Debra Hanenburg is the SME / instructor.  Feel free to email to let her know you're updating the portfolio content (or I could do this).  Could you explain "specifically the copy?"

**Comment by inoklim-twu** [comment]
Inok - WP Setup page - CSS 
Jeff - KB updates after the WP Setup page is updated
Chloe - Remove videos from Grav, e-Portfolio page updates: https://create.twu.ca/eportfolios/wordpress/posts-and-pages/

Current WP Setup page:
![image](https://github.com/user-attachments/assets/ec824f24-a805-44bc-be45-90f37ada2aca)

**Comment by chloecwh** [comment]
> Debra Hanenburg is the SME / instructor. Feel free to email to let her know you're updating the portfolio content (or I could do this). Could you explain "specifically the copy?"

Hi @kmarjanovic It would be helpful to send her an email letting her know we're updating the Grav content. First step we are doing are to remove videos and screenshots that are not up to date as Inok mentioned above. Just wondering when is [UNIV 301 OL FA 2024](https://learn.twu.ca/course/view.php?id=34745) starting? It's an empty shell with 30 participants.

**Comment by kmarjanovic** [comment]
@chloecwh UNIV 301 starts Oct.15th.  Debra may have other edits coming in so will let you know.

**Comment by chloecwh** [comment]
1. Removed videos on Unit 1 Topic 2 lesson 2 , Unit 2 Topic 2 lesson 1
2. Remove empty summary at Unit 3 Topic 1 Summary, (content was archived 4 yrs ago) 
`I hope you enjoyed the session with Mark Warren on Career Development and that the information will inform and help shape a deeper understanding of who you are and how you will live out your calling in this world. As you begin to think about your final paper for this course, often students include key learning and insights from this session as their main “Aha moment”. Be thinking about what that might be for you and feel free to share in this week's Class Interaction Forum.`

3. Unit 4 Topic 1 Lesson 1 - private video
`## **Lesson 1: Research Strategies**
We begin this section by learning some basic strategies related to finding and evaluating research needed for academic writing (particularly in the Social Sciences). To begin, we want to be sure we are clear about what the difference is between primary and secondary sources of information. This video does a great job explaining the differences.
[plugin:youtube](https://youtu.be/gStyna348M0)`

**Comment by chloecwh** [comment]
Removed technical related pages on E-portfolio wp, see screenshots
<img width="1512" alt="Screenshot 2024-10-15 at 10 33 55 AM" src="https://github.com/user-attachments/assets/d4125167-3609-4e4c-b8d8-97df250de621">
<img width="1512" alt="Screenshot 2024-10-15 at 10 33 52 AM" src="https://github.com/user-attachments/assets/8cd55e61-44ae-46d0-95fe-61eb23c27c3e">

**Comment by chloecwh** [comment]
Update: 

@Jeff-TWU has created the articles below and have contacted Mari to get the published
[Creating a Site](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fservicehub.twu.ca%2FTDClient%2F1904%2FPortal%2FKB%2FArticleDet%3FID%3D161499&data=05%7C02%7CChloe.Chang%40twu.ca%7C657d01551509420d39ac08dcf771a111%7C2b4ef155167343efa480230c3d483f16%7C0%7C0%7C638657314626496414%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=JT1c9hdxFWVj0mxVYICG8enyM%2FRScxgdZuaAX2CdBFQ%3D&reserved=0)
[General Settings](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fservicehub.twu.ca%2FTDClient%2F1904%2FPortal%2FKB%2FArticleDet%3FID%3D162091&data=05%7C02%7CChloe.Chang%40twu.ca%7C657d01551509420d39ac08dcf771a111%7C2b4ef155167343efa480230c3d483f16%7C0%7C0%7C638657314626525629%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=uQwpAElZlyKjjxqDLiHcqn90ebBFqrH4el8gI7DzmMk%3D&reserved=0)
[Pages and Posts](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fservicehub.twu.ca%2FTDClient%2F1904%2FPortal%2FKB%2FArticleDet%3FID%3D162092&data=05%7C02%7CChloe.Chang%40twu.ca%7C657d01551509420d39ac08dcf771a111%7C2b4ef155167343efa480230c3d483f16%7C0%7C0%7C638657314626543322%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=yhj%2Fc%2F9uKRY5kylB5Y9mrG8HYuvBdODvtKS%2BG3oD93I%3D&reserved=0)
[Editing Content](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fservicehub.twu.ca%2FTDClient%2F1904%2FPortal%2FKB%2FArticleDet%3FID%3D162093&data=05%7C02%7CChloe.Chang%40twu.ca%7C657d01551509420d39ac08dcf771a111%7C2b4ef155167343efa480230c3d483f16%7C0%7C0%7C638657314626560608%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=CB%2BE4gp6klTIkaftAdJsDkjGSI4AAL%2FmnXqf1aJ3eJo%3D&reserved=0)
[Media](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fservicehub.twu.ca%2FTDClient%2F1904%2FPortal%2FKB%2FArticleDet%3FID%3D162094&data=05%7C02%7CChloe.Chang%40twu.ca%7C657d01551509420d39ac08dcf771a111%7C2b4ef155167343efa480230c3d483f16%7C0%7C0%7C638657314626579698%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=HQ9wJc5h6WPdR3LjXw0n59I0AYTaEDhmUFxAMDAauKY%3D&reserved=0)
[Menus](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fservicehub.twu.ca%2FTDClient%2F1904%2FPortal%2FKB%2FArticleDet%3FID%3D162095&data=05%7C02%7CChloe.Chang%40twu.ca%7C657d01551509420d39ac08dcf771a111%7C2b4ef155167343efa480230c3d483f16%7C0%7C0%7C638657314626596540%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=KZgZXif5UQPzaALEiF%2FXSzjDAzrDMYRzsad7WarC0P0%3D&reserved=0)

I have reached out to Professor Hanenburg to see how we can proceed to update GRAV while there's a live course

**Comment by chloecwh** [comment]
Articles above are live
Professor Hanenburg has informed us she made the E-Portfolio optional for FA. She is ok with us making the changes to the FA24 and Master UNIV 301 course.
