### ISSUE TITLE
FCR cards request

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#1039]
### Course
all
[FCR board](https://github.com/orgs/TWUOnline/projects/21/views/1)
[FCR template](https://github.com/TWUOnline/course-logistics/issues/273)

### Instructions
- [ ] Please create cards following the FCR template for all courses

@cmadland let's discuss whether to add TOP-specific criteria to our [quality checklist](https://docs.google.com/document/d/15CWFTXFsPaP17v6afU98dLN5Cxcek3boux-epli2rmk/edit) (e.g. outcomes-based)

**Comment by chloecwh** [comment]
Will migrate the courses to TWU Online org and then create issue with the template.

**Comment by kmarjanovic** [comment]
Closing issue.
IDs can create when we start a Course Quality Review.
