### ISSUE TITLE
LDRS 101 X1 import 

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#1040]
### Course
[LDRS 101 X1](https://learn.twu.ca/course/view.php?id=33696)
### Instructions
- [x] please import the TOP version of the course into the fall X1 shell
- [x] note this course is starting tomorrow! (possibly)

Please upload required files as attachments.

**Comment by chloecwh** [comment]
@kmarjanovic @cmadland Imported!

**Comment by kmarjanovic** [comment]
thanks Chloe!!

Could you fix the following:
- [ ] on community tab - delete button for Discourse without a TWU account
- [ ] in Learning online section - course schedule.  please delete 3 month & 6 month.  See the updated syllabus for wording changes to the 6 weeks schedule.

Notes for changes to TOP template:
- [ ] Learning Online section - intro
In this section, we'll guide you through navigating your online course, what to expect from an asynchronous, self-paced format, recommended schedules to help you achieve your learning goals, and how to access student support.
to
In this section, we'll guide you through navigating your course on Moodle, what to expect from an online course, setting up a schedule to help you achieve your learning goals, and how to access student support.

- [ ] What to Expect Section (add GX description- hidden so instructors can choose What to Expect for TOP & What to expect  for GX

**Comment by chloecwh** [comment]
Updated @kmarjanovic

**Comment by kmarjanovic** [comment]
Thanks Chloe!
