### ISSUE TITLE
MCOM 281 & 221 assignment mix-up

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#1041]
### Course
[MCOM 281 X1 (FA24)](https://learn.twu.ca/course/view.php?id=34043&section=0)

### Instructions
It seems the journal assignment in 281 is the 221 journal assignment.  Note this course is live.
- [x] please replace the [Reflective Course Journal for 221 ](https://learn.twu.ca/mod/assign/view.php?id=1146149) with the Journal for 281.  @Nataliadsanchez please confirm where we can find this assignment info
- [x] Please replace the info in the [Master ](https://learn.twu.ca/mod/assign/view.php?id=976696) as well

Thank you!

**Comment by chloecwh** [comment]
I've hide the assignment of 281 FA 2024 from student. @Nataliadsanchez please let me know the correct info, thanks!

**Comment by Nataliadsanchez** [comment]
I'll update it after I finish reviewing LDRS 400

**Comment by Nataliadsanchez** [comment]
[Reflective Course Journal.docx](https://github.com/user-attachments/files/17382908/Reflective.Course.Journal.docx)
Hi @chloecwh. Thanks for waiting. Here you have the Course Journal for MCOM 281

**Comment by chloecwh** [comment]
On it

**Comment by chloecwh** [comment]
Updated GX R[eflective Course Journal](https://learn.twu.ca/mod/assign/view.php?id=976696)
[MCOM 281 X1 (FA24)](https://learn.twu.ca/course/view.php?id=34043&section=0) 

While double checking the gradebook, I notice that the Graded Assignments exceed 100%. Please advise next steps @Nataliadsanchez 
![Screenshot 2024-10-15 at 11 36 12 AM](https://github.com/user-attachments/assets/b34c599b-97bb-451e-802f-75f897dfe897)

**Comment by Nataliadsanchez** [comment]
Persuasive speech is 30% as presented in the course introduction. I'll fix the assessment table

**Comment by Nataliadsanchez** [comment]
Fixed!
