### ISSUE TITLE
Minor edit

### ISSUE THREAD

**Issue by dhanenburg** [TWUOnline/bug-tracking#1042]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 UNIV 301 OL FA2024
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 On the "Assessments" tab/Overview - please change where it says "Students will watch 3 other student presentations and offer feedback on MS stream" to "Students will watch 3 other student presentations and offer feedback on the Moodle Discussion Forum"
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=34745&section=18#tabs-tree-start
2. Unit #  Assessments tab       Topic #  Overview        Activity#  In the chart, first column, 4 lines down
 
**Optional: Screenshots**

**Comment by chloecwh** [comment]
Updated @dhanenburg
