### ISSUE TITLE
UNIV 301 Edits

### ISSUE THREAD

**Issue by dhanenburg** [TWUOnline/bug-tracking#1043]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 UNIV 301 OL FA24 
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.

4 edits are needed:

Unit 1/Lesson 2/ first paragraph - please remove "(Discovery Wheel)"

Unit 1/Lesson 2/Activity 1.3 - please delete all the text in the box and replace with "Read College Success Text and complete at least 4 activities listed in Appendix C"

Unit 1/Lesson 3/second paragraph - replace the whole second paragraph with the following - In this class, we start out with a book that is foundational for the whole program and starts some conversations about topics relevant to psychology and the helping profession. The book, The Soul of Shame, by Curt Thompson provides competent knowledge and application from psychology, interpersonal-neurobiology, theology and real life stories about the topic of shame. The topic of shame is core to a lot of the issues a client presents with in counseling. Shame has often been at the root of struggles academically - so this topic has personal and professional applications. Although the book addresses shame from a Christian/Biblical perspective the author says on p. 12 that "You may not agree, but even so I believe this book will still be helpful for you." As a Christian university we provide opportunities to discuss and learn about the historical Christian faith in the context of the topic at hand. If this is not your own worldview, it will help you learn about what Christians believe and how central to healing it may be to a client you are working with. It will increase your cultural and spiritual competency in the helping professions. 

Unit 5/Topic 1/Title says Unit 8 and it should say Unit 5
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=34745
2. Unit #         Topic #         Activity#  (See Above)
 
**Optional: Screenshots**

**Comment by chloecwh** [comment]
Updated @dhanenburg
