### ISSUE TITLE
UNIV 301 edit

### ISSUE THREAD

**Issue by dhanenburg** [TWUOnline/bug-tracking#1044]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 UNIV 301 OL FA24
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.

 Unit 1/Topic 1/Overview/ - Learning Activity 1.3 - replace all the content with "Follow the syllabus weekly reading schedule for the College Success Text and The Thompson Text. 

Delete the first reading in Activity 1.4 but leave the APA reading. 

 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=34745&section=3#tabs-tree-start
2. Unit #         Topic #         Activity#  (See above)
 
**Optional: Screenshots**

**Comment by chloecwh** [comment]
Updated @dhanenburg
