### ISSUE TITLE
Production for X2 courses

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#1046]
### Course
LDRS 101 X2 https://learn.twu.ca/course/view.php?id=34993
### Instructions
- [x] please import the TOP version of LDRS 101 for the ***Nov. start.***  I'll add the syllabus

@chloecwh Could you please check that the other X2 courses are imported as well?

tagging @emmanuelD-AFK as well.

**Comment by chloecwh** [comment]
@emmanuelD-AFK @kmarjanovic this is [the list](https://github.com/twu-fhss/phil210/issues/7#issuecomment-2341574479) I had in September, which didn't include LDRS 101 X2. Can I have the latest list for FA X2? 

[MCOM 281 X1 - Public Speaking (FA 2024)](https://learn.twu.ca/course/view.php?id=34043)
 [PSYC 106 X1 - Introduction to Psychology (FA 2024)](https://learn.twu.ca/course/view.php?id=34580)
 [PSYC 105 X2 - Introduction to Psychology (FA 2024)](https://learn.twu.ca/course/view.php?id=34577)
 [SOCI 101 X1 - Introduction to Sociology (FA 2024)](https://learn.twu.ca/course/view.php?id=34698)
 [ANTH 101 X2 - Introduction Cultural Anthropology (FA 2024)](https://learn.twu.ca/course/view.php?id=33120) 
 [PHIL 100 X1 - Philosophy for Life (FA 2024)](https://learn.twu.ca/course/view.php?id=34513)
 [PHIL 210 X1 - Contemporary Ethical Issues (FA 2024)](https://learn.twu.ca/course/view.php?id=34524)

**Comment by chloecwh** [comment]
@cmadland Do I import Quarto version to GX courses in the exact format (same course unit page) as TOP? Anything to tweak? Since LDRS 101 is in ID review, do I wait until it is send back to me from you and Kelly?

**Comment by kmarjanovic** [comment]
I just remembered I had tweaked the TOP / GX version for the X1 course -https://learn.twu.ca/course/view.php?id=33696
I changed the schedule, due dates, discussion page - so that would be the version to use and I can edit from there.

**Comment by kmarjanovic** [comment]
I'm still editing U6 - but would like to use the revised content.  Is that possible?

**Comment by chloecwh** [comment]
> I'm still editing U6 - but would like to use the revised content. Is that possible?

Of course possible! @kmarjanovic

**Comment by emmanuelD-AFK** [comment]
Hi @chloecwh,  these are the  X2 FA 24 courses: 

  | Psyc 105 | X2 |   | 7-Nov-24 | 12-Dec-24 | r | 8:15 AM | 10:15 AM | online/Virtual Labs |   |   |   | Todd Dutka
 
  | MCOM 221 | X2 |   | 8-Nov-24 | 13-Dec-24 | Fri | 5:00 PM | 7:00 PM | online/Virtual Labs |   |   |   | NED JOHN VANKEVICH
  
  | ANTH101 | X2 |   | 5-Nov-24 | 10-Dec-24 | T | 6:00 AM | 8:00 AM | online/Virtual Labs |   |   |   | Eileen Mc Willliams
 
  | LDRS 101 | X2 |   | 8-Nov-24 | 12/13/2024 | Fri | 8:15 AM | 10:15 AM | online/Virtual Labs |   |   |   | Madland/Marjanovic

**Comment by chloecwh** [comment]
Thanks @emmanuelD-AFK 

I'm awaiting: 

1. GX template sign off - all
2. Direction for [ANTH 101 request](https://github.com/twu-fhss/anth101/issues/31)  - @kmarjanovic @cmadland 
3. LDRS 101 units ID review - @cmadland @kmarjanovic 

I would need these items confirm by Oct 30 for me to import them and let instructor review on Nov 1. Note that I will be away from Nov 4-6. Thank you!

**Comment by kmarjanovic** [comment]
@emmanuelD-AFK could you please confirm the X2 courses with Chloe?
This LDRS 101 X2 was added later...we should confirm this communication process with Production.

**Comment by emmanuelD-AFK** [comment]
@kmarjanovic 

> @emmanuelD-AFK could you please confirm the X2 courses with Chloe? This LDRS 101 X2 was added later...we should confirm this communication process with Production.

Done!

**Comment by chloecwh** [comment]
Note to self: 

[ANTH 101 X2](https://learn.twu.ca/course/view.php?id=33120) - course design hasn't start, Eileen is editing the course
[MCOM 221 X2](https://learn.twu.ca/course/view.php?id=34035) - hasn't undergone template change on both X2 and Master
[PSYC 105 X2](https://learn.twu.ca/course/view.php?id=34577) - hasn't undergone template change on both X2 and Master
[LDRS 101 X2](https://learn.twu.ca/course/view.php?id=36689) - imported from TOP master, still need to tweak X2 to the GX template

**Comment by kmarjanovic** [comment]
@chloecwh @cmadland let's discuss this process at today's design meeting. Should we have a separate Live & Prime shell?  If not, does this make sense?
1. Production imports GX template & remove info not related to delivery (GX Prime Assessment tab, Community tab).
2. Confirm with @emmanuelD-AFK and/or instructor and/or facilitator to check the shell.
3. Final quality check from Emmanuel. (mainly to check syllabus is there & course is open 2 weeks prior to course start).

Thoughts?

**Comment by kmarjanovic** [comment]
In ANTH, MCOM, PSYC - please hide prime assessment & community tabs.

In ANTH 101 - I assume Eileen wants to move the weeks subtabs from Assessment main tab to course units main tab.  Could you check with her if she needs help with those edits?

**Comment by emmanuelD-AFK** [comment]
Hi Kelly,
I want to discuss the quality check only because of the Job descriptions (JD).  Per the JD (Director of Instructional Design & Quality Assurance), quality falls under your preview regardless of the stage. I can provide as much support as possible from my team (with the instructors and facilitator working on it). Still, the accountability level should be on the design and quality side.
Let's discuss it.



Emmanuel Denguessi, MA, GCA.ed, BA, Dip, CLC

Director of Program Delivery - Part-Time Faculty

TWU Online, Trinity Western University

e. ***@***.***

twu.ca<http://www.twu.ca/>/ 778-552-4861

Harvest Building / Door:120

________________________________

**Comment by chloecwh** [comment]
> ANTH 101 X2

Reached out to Eileen and CC'ed you @kmarjanovic

**Comment by chloecwh** [comment]
Got the GX template sign off from Kelly and Colin
Currently importing GX template to [MCOM 221 X2](https://learn.twu.ca/course/view.php?id=34035) and
[PSYC 105 X2](https://learn.twu.ca/course/view.php?id=34577)

**Comment by chloecwh** [comment]
Note: 

[MCOM 221 GX Master](https://learn.twu.ca/course/view.php?id=30192&section=0#tabs-tree-start)
[MCOM 221 X2 (FA 2024)](https://learn.twu.ca/course/view.php?id=34035&section=0#tabs-tree-start) - course unit site was revamped 
[PSYC 105 GX Master](https://learn.twu.ca/course/view.php?id=32192&section=0#tabs-tree-start) - schedule is empty
[PSYC 105 X2 (FA 2024) ](https://learn.twu.ca/course/view.php?id=34577&section=0) - course unit site was revamped, updated syllabus - course is set to visible to students as the last setting was set that way

1. Do I remove "Throughout the course we encourage you to actively participate in the discussions happening on [Discourse](https://twu.discourse.group/auth/microsoft_office365)." from Course Unit intro paragraph? 
2. Please double check Unit Summaries, most are copied from the content, some are generated by AI
3. PSYC 105 U7 Pavlov.ppt needs to be reuploaded, U8 Check your learning doesn't seem to be the right content 

Would you mind reviewing the courses listed above? @cmadland @kmarjanovic

**Comment by kmarjanovic** [comment]
@dgaudet48 could you please check on PSYC 105 content? "U8 Check your learning doesn't seem to be the right content"

**Comment by chloecwh** [comment]
> @dgaudet48 could you please check on PSYC 105 content? "U8 Check your learning doesn't seem to be the right content"

Here's more [details ](https://github.com/TWUOnline/bug-tracking/issues/962#issuecomment-2450487675) @dgaudet48 @kmarjanovic

**Comment by chloecwh** [comment]
Note: Imported to the correct [LDRS 101](https://learn.twu.ca/course/view.php?id=34993), archived [old content](https://learn.twu.ca/course/view.php?id=36689)

**Comment by chloecwh** [comment]
Eileen has confirmed ANTH 101 is ready to go

Unit summaries doc: 
[mcom221X2_unitTeaser.docx](https://github.com/user-attachments/files/17594060/mcom221X2_unitTeaser.docx)
[psyc105_unitTeaser.docx](https://github.com/user-attachments/files/17594062/psyc105_unitTeaser.docx)

**Comment by chloecwh** [comment]
Can we meet to talk about logistics of GXP for SP2025 courses? With Todd's feedback, I think it's important that we communicate through Zoom more. @kmarjanovic @cmadland @emmanuelD-AFK
