### ISSUE TITLE
Changing information to overview page 

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#1047]
**Which course contains the bug?**  
- SOCI 400 OL FA2024
 
 
**Describe the error and/or your suggestion**  
We have a new edition for the required text so under Required text section, please replace this Corey, G. Corey, M.S; Corey, C. (2019). Issues and Ethics in the Helping Professions (10th ed.). Cengage Publishers with this NEW reference: Corey, G. Corey, M.S; Corey, C. (2024). Issues and Ethics in the Helping Professions (11th ed.). Cengage Publishers

Can you also update the percentage graph with the following: 
Term Paper is now worth 30%
Open Book Ethics Quiz is now worth 10%
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=34715&section=0
2. Unit #  Course Overview       Topic # Required Course and Materials and Course Evaluation        Activity#  
 
**Optional: Screenshots**

**Comment by chloecwh** [comment]
@emilyverse the request has been completed, textbook edition is change each unit overview as well.
