### ISSUE TITLE
LDRS 101 missing file

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#1048]
### Course
[LDRS 101 X2](https://learn.twu.ca/course/view.php?id=34993&section=1#tabs-tree-start)

### Instructions
- [ ]The starter vault for ldrs 101 is not linked in the course book.  Could you please add it to the X2 course?
- location:  1.3.2 Activity: Download the Starter Vault
[ldrs101-vault-main.zip](https://github.com/user-attachments/files/17818977/ldrs101-vault-main.zip)

Thank you!

**Comment by chloecwh** [comment]
I'm on it!

**Comment by chloecwh** [comment]
Log: worked on inno101-q dev files
added zip
flagged and commented out invalid links (see issues on[ inno101](https://github.com/twu-innovation/inno101/issues)

Note: I haven't incorporate Kelly's edits, need to update TOP and GX after the edits are edited

[X2 updated course link](https://learn.twu.ca/course/view.php?id=34993&section=1)

@kmarjanovic
