### ISSUE TITLE
Production - LDRS 410 Guide

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#107]
### Course
LDRS 410

### URL
https://far.twu.ca/guides/lead-ba
### Instructions
Please add the facilitator's guide to the website.
[LDRS-410-Facilitator’s Guide_Oct23_KM.docx](https://github.com/TWUOnline/bug-tracking/files/3791868/LDRS-410-Facilitator.s.Guide_Oct23_KM.docx)

Note for this course (& 303 I think) I need to add intro pages (course description, assessment info, etc.)

**Comment by kmarjanovic** [comment]
Just checking up on this issue.  @345-Jay are you still working on it?
I think the process is, if you're putting it aside for a while, put the issue back into a priority column so someone else can attend to it.

Also - @cmadland is there a way to hide content that's not relevant?  Right now looking at the [410 guide](https://far.twu.ca/guides/lead-ba/ldrs-410-persuasion-and-positive-influence) online, there's info from other courses (very confusing for any facilitator or SME).  Let's address this issue.

**Comment by faitht1023** [comment]
@kmarjanovic I've added the notes from the attached docx file to the "Lesson Notes" section in LDRS 410 guides. I noticed that there was also a copy of it under "Facilitator's Guide", so I left there in case that was the appropriate place for it. I formatted and split up the notes by unit under "Lesson Notes". Please let me know if anything else needs to be done for this? Thank you!

**Comment by kmarjanovic** [comment]
@faitht1023 
In looking at the guide online - it still has all the info for another course.  Could you check the [guide](https://far.twu.ca/guides/lead-ba/ldrs-410-persuasion-and-positive-influence) please?

**Comment by faitht1023** [comment]
@kmarjanovic I think it's working now. Looks like my first few commits didn't go through, but now it contains the 410 info. Sorry about that! 
Is there other information that should go under the "Facilitation Notes for LDRS 410" section now?

**Comment by kmarjanovic** [comment]
Excellent! Thanks @faitht1023 !

Could you also replace the info in the Course Overview & Syllabus page with [this](https://github.com/TWUOnline/ba-lead/blob/master/pages/12.ldrs410/06.home/page.md)

And then delete the other note pages (has info for 302 still)

Perhaps in the Assessment page, just add this [table](https://github.com/TWUOnline/ba-lead/blob/master/pages/12.ldrs410/assessment/page.md) and a generic note:

! See the specific Assessment details in Moodle.

Thanks again!

**Comment by faitht1023** [comment]
@kmarjanovic no worries, I have replaced the info with what you linked (and I also added the pdf from the same folder to the guide), as well as adding the table to the assessment page.

Which note pages did you want removed?

As well, the academic dishonesty button was not working, so I hyperlinked it at the end of the syllabus/course overview instead.

**Comment by kmarjanovic** [comment]
Thanks @faitht1023 !

If you see in the 410 section after the [notes](https://far.twu.ca/guides/lead-ba/ldrs-410-persuasion-and-positive-influence/facilitation-notes) section, there are all these 302 lesson notes pages.

**Comment by faitht1023** [comment]
@kmarjanovic I've changed the header to say 410 notes now, but all the lesson note pages are 410 notes; I took the facilitation notes and split them by unit a few days ago. Was something else supposed to be in the "Lesson Notes" section?

**Comment by kmarjanovic** [comment]
Ah, I see them now.  If [this page](https://far.twu.ca/guides/lead-ba/ldrs-410-persuasion-and-positive-influence/facilitation-notes) is a repeat of all the other lesson notes split up, then let's delete it.

**Comment by kmarjanovic** [comment]
Also the [assessment details](https://far.twu.ca/guides/lead-ba/ldrs-410-persuasion-and-positive-influence/assessment-details) aren't correct.  Just keep the chart at the bottom of the page.  This other info is from another course.

**Comment by kmarjanovic** [comment]
Also, just a frustration.  I don't know if you've navigated the pages on Grav much, but the side navigation menu always goes back to the first BA LEAD course listed (LDRS 220).

@cmadland could we fix this?  Or....I would suggest we discuss another format for the guides (presbooks!)

**Comment by faitht1023** [comment]
@kmarjanovic I've deleted the faciliatation n

**Comment by kmarjanovic** [comment]
@faitht1023 
Thanks for clearing up 410 - it looks great.
As for the blank pages in the other courses - yes, please delete.

**Comment by faitht1023** [comment]
@kmarjanovic You are welcome! I've removed the blank pages.

**Comment by kmarjanovic** [comment]
Thanks again!
