### ISSUE TITLE
Production - WRSH 101 - H5P

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#11]
### URL https://learn.twu.ca/course/view.php?id=10744&section=1
Unit 1 - Topic 2 - Learning Activity 1.3

### Instructions

Could we make an H5P drag and drop for the verses to the categories of (or columns for)
1. All of our lives
2. Gathered worship
3. Specific Acts of worship.

Perhaps we have a background image of these 3 columns? (see https://h5p.org/node/415944).

Could we brainstorm and discuss?  Perhaps a google doc would be easier - but we'd like it interactive and individual.

**Comment by kmarjanovic** [comment]
https://learn.twu.ca/course/view.php?id=10744&section=1

**Comment by rezakh66** [comment]
@kmarjanovic Hi, Please look at this [here](https://create.twu.ca/h5p/wp-admin/admin.php?page=h5p&task=show&id=87). How is it?

**Comment by kmarjanovic** [comment]
Hi @rezakh66 
I think this is a great option!  Could you put the content in and we can see how it looks?
Thank you!

**Comment by kmarjanovic** [comment]
@rezakh66 
Looking at the background image again, it seems a little blurry (hope it's not my eyes!!).
Could we get a better resolution and then try adding the content so we can see if this activity makes sense?

**Comment by rezakh66** [comment]
@kmarjanovic Where can I find content? I'm thinking of the content's length and if they can fit in limited space we have in this method

**Comment by kmarjanovic** [comment]
@rezakh66 you can see the content in the learning activity (now relabeled [Activity 1.4](https://learn.twu.ca/course/view.php?id=10744&section=1)).
The answers are in the pwpt below the activity.

**Comment by kmarjanovic** [comment]
@Jeff-TWU @mellaurie 
Could we meet this week to discuss media requests?  
For this one in particular, Reza and I have discussed some options (see [here](https://create.twu.ca/h5p/wp-admin/admin.php?page=h5p&task=show&id=87)) but it's not quite what I have in mind.
See [example](https://barabus.tru.ca/mngt1211/unit1_option3/story_html5.html) from TRU

**Comment by mellaurie** [comment]
@kmarjanovic @Jeff-TWU 
Happy to meet anytime.  
Do you want this activity to work like the TRU example or just look like it? (I think H5P's Summary activity is similar)

**Comment by Jeff-TWU** [comment]
@kmarjanovic @mellaurie 
Yes, anytime. Let me know when. 

 @cmadland I don't have access to the link Kelly mentioned. Could I get access please?

**Comment by cmadland** [comment]
Jeff,

I’ve added you as a manager to all courses in the ‘Development’ category on Moodle. This should work to get you perpetual access to all the courses under development.

To track down a course, click ‘Site home’ in Moodle, then search for the course you are looking for. Alternately, the direct link should get you in.

Let me know if you have further questions!

Colin

**Comment by Jeff-TWU** [comment]
@cmadland Thanks Colin!

**Comment by Jeff-TWU** [comment]
@kmarjanovic @mellaurie @karenroeck 

So I found [this](https://h5p.org/drag-and-drop#example=68888). Visually not what your looking for, but I think it code-wise it would work with the idea of dropping coloured tokens on to the different scripture sections. Thoughts?

**Comment by karenroeck** [comment]
I think this could work nicely and would bring a fun interactive element to the course - great work, Jeff!

**Comment by kmarjanovic** [comment]
Yes - thank you!!

**Comment by kmarjanovic** [comment]
Here is the answer key

[WRSH-101-Unit1_Topic2_Act1-4.docx](https://github.com/TWUOnline/bug-tracking/files/4996839/WRSH-101-Unit1_Topic2_Act1-4.docx)

**Comment by Jeff-TWU** [comment]
@kmarjanovic Thanks!

**Comment by Jeff-TWU** [comment]
How about [this](https://create.twu.ca/h5p/wp-admin/admin.php?page=h5p&task=show&id=104)?

**Comment by karenroeck** [comment]
This is so slick - love it!

**Comment by kmarjanovic** [comment]
Yes yes yes!!! Thank you so much, Jeff!! (I'm so happy you're on our team!!)

**Comment by kmarjanovic** [comment]
@mellaurie perhaps at your next meeting with Joan, you can have her review this activity in case there need to be edits?  I'll close this issue for now - but feel free to open if there are further edits.
Thanks again Jeff!

**Comment by kmarjanovic** [comment]
(See Unit 1 topic 2 for embedded H5P)
Moodle: https://learn.twu.ca/course/view.php?id=10744&section=1

WordPress: https://create.twu.ca/wrsh101/unit-1/
(note the wp site needs redesign)

**Comment by mellaurie** [comment]
So awesome.  Thanks Jeff!!

Kelly, yes,  I will share this with Joan next time we meet.

**Comment by Jeff-TWU** [comment]
Glad you all like it. Happy to be a part of the team!

**Comment by Jeff-TWU** [comment]
@cmadland Thanks Colin!
