### ISSUE TITLE
broken links - WRSH 101 links

### ISSUE THREAD

**Issue by rezakh66** [TWUOnline/bug-tracking#111]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 WRSH101
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 there are 4 hyperlinks all broken and no result found. I think all links to biblegateway .com are broken and need to be updated.
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=10744&section=2
2. Unit #2         Topic #  3/learning activity       Activity#  2.6
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
@cmadland - can these bugs automatically go to Issue Tracking, or can ATAs add each ticket to the Issue Tracking Project so we can track things?

**Comment by kmarjanovic** [comment]
@cmadland @rezakh66 - Could you please remove all of the bible hyperlinks in the course?  (Just have the bible verse until we figure out a bible website that works)

**Comment by rezakh66** [comment]
@kmarjanovic I have deactivated all hyperlinks for now so we can replace them with new links later.

**Comment by kmarjanovic** [comment]
Yikes!  All the bible verses are missing now!  I'll need to track them down.
Next time, please just deactivate the hyperlink (e.g - take out (psalm4) but leave in [psalm4]

**Comment by kmarjanovic** [comment]
Praying I didn't miss any verses!
@cmadland could we make sure when links are deactivated the title/content isn't taken out?

**Comment by kmarjanovic** [comment]
I found a site that will work now, as Bible Gateway redirected all verses.

Could someone help to hyperlink all of the Bible verses in the course? 
Please use https://www.biblica.com/bible/ and search for the verse.

**Comment by rezakh66** [comment]
@kmarjanovic Hi Kelly,
I have substituted verses with new links from biblica.com . Can I have the doc file to check if all are done properly?

**Comment by kmarjanovic** [comment]
[WRSH101_Unit 4_Aug21_KM.docx](https://github.com/TWUOnline/bug-tracking/files/4017184/WRSH101_Unit.4_Aug21_KM.docx)
[WRSH101_Unit 2_July22_KM.docx](https://github.com/TWUOnline/bug-tracking/files/4017185/WRSH101_Unit.2_July22_KM.docx)
[WRSH101_Unit1_KM_July5.docx](https://github.com/TWUOnline/bug-tracking/files/4017186/WRSH101_Unit1_KM_July5.docx)
[WRSH101_Unit 3_Aug21_KM.docx](https://github.com/TWUOnline/bug-tracking/files/4017187/WRSH101_Unit.3_Aug21_KM.docx)
Hi Reza,
Here are the 4 units with Bible verses.  Note that they are old versions, so the current info in Moodle should be used.
Thanks!

**Comment by rezakh66** [comment]
@kmarjanovic Hi Kelly,
while I am working on this course I have found that  online contents  are not linedup same as document files. they are either missed or moved in wrong pages. I want just to reconfirm that should I  make changes based on attached docx files or they are modified intentionally?

**Comment by kmarjanovic** [comment]
@rezakh66<https://github.com/rezakh66>
Hi Reza,
The online content is always the most recent.  Some of the word docs have been changed significantly, so please don’t revert back to those unless specified.  The word docs are just for reference.
Thanks,
Kelly

KELLY MARJANOVIC
Instructional Designer | TWU Global
Trinity Western University | e. Kelly.Marjanovic@twu.ca<mailto:Kelly.Marjanovic@twu.ca>
twu.ca<http://www.twu.ca/>

[cid:image003.png@01D567BE.8201A250]<https://www.facebook.com/trinitywestern/>  [cid:image004.png@01D567BE.8201A250] <https://www.instagram.com/trinitywestern/>   [cid:image005.png@01D567BE.8201A250] <https://twitter.com/TrinityWestern>   [cid:image006.png@01D567BE.8201A250] <https://www.youtube.com/user/TrinityWesternU>   [cid:image007.png@01D567BE.8201A250] <https://www.linkedin.com/school/trinity-western-university/>

[cid:image001.png@01D5649E.C2C49090]
