### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by rezakh66** [TWUOnline/bug-tracking#112]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 WRSH101
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 There are 11 hyperlinks that are all directed to a content that does not exist anymore.
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=10744&section=2
2. Unit #   2      Topic #   5/learning activity      Activity#  2.10
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
Need to figure out Bible Gateway glitch
 [Joshua 24](https://www.biblegateway.com/passage/?search=Joshua+24&version=NIV),
[Exodus 12](https://www.biblegateway.com/passage/?search=Exodus+12&version=NIV),
and
[Exodus 29](https://www.biblegateway.com/passage/?search=Exodus+29&version=NIV).

Any ideas @cmadland ?
