### ISSUE TITLE
link missing

### ISSUE THREAD

**Issue by rezakh66** [TWUOnline/bug-tracking#113]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 WRSH101
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 there should be a link directed to an article which is missing
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=10744&section=5
2. Unit #   5      Topic #  3/learning activities       Activity#  5.4
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
Waiting for resource from Joan.  Will add soon!

**Comment by kmarjanovic** [comment]
article linked.
