### ISSUE TITLE
Production - LDRS 410 pdf

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#114]
### Course
LDRS 410
### URL
https://learn.twu.ca/course/view.php?id=10720&section=8
### Instructions
For the pdf linked in Unit 8, Activity 8.1, is it possible to scan a cleaner copy of the chapter?  Could the librarians help with this (& check copyright)?

**Comment by kmarjanovic** [comment]
Checking with instructor about the inter library loan.

**Comment by kmarjanovic** [comment]
Shelley will drop this off at Global to be copied.

**Comment by karenroeck** [comment]
Scan request emailed to Shawn Brouwer in TWU Library.

**Comment by cmadland** [comment]
FYI, there has been some funding approved for the library to purchase a scanner or two...

**Comment by karenroeck** [comment]
@rezakh66 Could you please crop the attached reading and replace the existing file in Activity 8.1 in LDRS 410?

https://learn.twu.ca/course/view.php?id=10720&section=8

[Barrett.pdf](https://github.com/TWUOnline/bug-tracking/files/4982994/Barrett.pdf)
