### ISSUE TITLE
Production - LDRS 303 - U3 alert

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#115]
### Course
LDRS 303
### URL
https://learn.twu.ca/course/view.php?id=10748&section=3
### Instructions
Please take out the extra details from the alert.
Have format similar to Unit 1&2 - https://learn.twu.ca/course/view.php?id=10748&section=1

**Comment by kmarjanovic** [comment]
hold that thought...I think I see what is wrong...

**Comment by kmarjanovic** [comment]
Learning Activity plug-ins are fixed (although checkmarks still need formatting).

Could you please add the schedule plugin - like in Units 1&2?

**Comment by faitht1023** [comment]
@kmarjanovic is there a document with the schedule where I could copy the information into a schedule plugin? or would you prefer if I just summarized the activities that are already there?

**Comment by kmarjanovic** [comment]
Hi Faith,
The Unit word docs should have the original activity checklist.  Most should be in github, but let me know if you need others.
https://github.com/TWUOnline/ba-lead/tree/master/pages/10.ldrs303/10.U4

Summarizing works too - I can always edit.
Thank you for your help!!

**Comment by faitht1023** [comment]
Sounds good, I can summarize it for now, I can't seem to find the doc for U3 at the moment (maybe I'm missing it somewhere!), would you be able to add it to Github for me please? Thanks!

**Comment by faitht1023** [comment]
I've added the alert, the approximate times it takes to complete each activity isn't there for all of the activities though.
