### ISSUE TITLE
Production - LDRS 303 quizzes

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#117]
### Course
LDRS 303
### URL
https://learn.twu.ca/course/view.php?id=10748&section=14
### Instructions
Please add the 2 quizzes to Moodle.
Quiz files are in GitHub: https://github.com/TWUOnline/ba-lead/tree/master/pages/10.ldrs303/assignments/03.quizzes

**Comment by cmadland** [comment]
The file for ch8-10 won't open in Werd. Error is that the file is corrupt.

Can you re-upload? @kmarjanovic

**Comment by kmarjanovic** [comment]
[303-Ch08-10-Key.docx](https://github.com/TWUOnline/bug-tracking/files/3806091/303-Ch08-10-Key.docx)
[303-Ch11-13-Key.docx](https://github.com/TWUOnline/bug-tracking/files/3806092/303-Ch11-13-Key.docx)
Let me know if these work!

**Comment by shaymar1** [comment]
All of the questions are inputed into the LDRS 303 question bank. Sadly, chap 8-10 are not in order, even though they were inputed in order. Not sure how to fix that.

**Comment by kmarjanovic** [comment]
Could you please add them to the 2 quizzes? (Quiz #1: Chap. 8-10; Quiz #2: Chap. 11-13)
https://learn.twu.ca/course/view.php?id=10748&section=14

**Comment by kmarjanovic** [comment]
Just checking this is all done?  @cmadland , could you/ATAs please close the issue or Request Review so we know which tasks are complete?
