### ISSUE TITLE
Production - LDRS 410 - U1 pdf

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#119]
### Course
LDRS 410
### URL
https://learn.twu.ca/course/view.php?id=10720&section=1
### Instructions
Could we edit this pdf (pages 1-3 is required for Activity 1.4; pages 3-9 is required for Activity
 1.5).
If not, I'll just link the same pdf. 
[U1_Persuasion_Overview.pdf](https://github.com/TWUOnline/bug-tracking/files/3806057/U1_Persuasion_Overview.pdf)

**Comment by cmadland** [comment]
We could also just link to the original text in pressbooks...would that make sense? Should we clone the book to our own PB site?

**Comment by kmarjanovic** [comment]
Yes, let's do that! I didn't realize it was from Pressbooks.

**Comment by cmadland** [comment]
https://open.lib.umn.edu/businesscommunication/chapter/14-1-what-is-persuasion/

and

https://open.lib.umn.edu/publicspeaking/chapter/17-1-persuasion-an-overview/

**Comment by cmadland** [comment]
<a class="embedly-card" data-card-controls="0" href="https://open.lib.umn.edu/businesscommunication/chapter/14-1-what-is-persuasion/">Business Communication for Success</a>
<script async src="//cdn.embedly.com/widgets/platform.js" charset="UTF-8"></script>

**Comment by kmarjanovic** [comment]
Looks like we're working on this at the same time?

Could we not embed the article?  It looks a little funny

**Comment by kmarjanovic** [comment]
@cmadland I added these links 2 days ago, and just found they were gone. 
I've seen this before when activities are moved to the alert plugin.  Can we ensure no content is lost?
