### ISSUE TITLE
Production - PMPP 201 editing

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#121]
### Course
PMPP 201
### URL
https://learn.twu.ca/course/view.php?id=8951&section=1
### Instructions
Could we have help formatting PMPP 201 - based on our recent design? (e.g. Activity checklists, Presentation slides, etc.)
Also - all links will need to be checked.

**Comment by rezakh66** [comment]
@kmarjanovic Hi, where can I find .doc files of the units to start working on this?

**Comment by kmarjanovic** [comment]
Hi Reza,
I can upload the files here - but does it work to just use the info in github?
https://github.com/TWUOnline/ba-lead/blob/master/pages/01.pmpp201/07.U1/01.overview/section.md

Either way there will be reformatting - cut & paste.
Thankfully for the new courses, we won't have to do this!

Do you mind just trying out Unit 1 and then message me to review before you start the next ones?

**Comment by rezakh66** [comment]
@kmarjanovic Hi,
I made a quick formatting for u1 from GitHub info. please send me the doc files to follow same formatting if that looks good.
https://learn.twu.ca/course/view.php?id=8951

**Comment by kmarjanovic** [comment]
Hi Reza,
All the formatting seems to be lost in Unit 1 now (heading levels, bullets, etc.).
Attached is Unit 1 - however, I likely made changes online since we finalized the word docs in May.  They should probably be used as a reference, but not change any of the current online wording.
Thanks!
[PMPP_201_U1_May17_KM.docx](https://github.com/TWUOnline/bug-tracking/files/3924457/PMPP_201_U1_May17_KM.docx)
Could you fix Unit 1 first  and then I can check the formatting of the unit

**Comment by rezakh66** [comment]
@kmarjanovic Hi 
can you please check now?

**Comment by kmarjanovic** [comment]
Hi Reza,
I changed some things in the checklist (copied it to make 3 alerts - with the assessment one being in secondary alert).
Please have a look and if you can, make those changes to the rest of the units.
Thank you for your help!!

**Comment by rezakh66** [comment]
@kmarjanovic 
Can you please upload doc files for rest of units here then I can work on them.
Thank you

**Comment by kmarjanovic** [comment]
[PMPP_201_U2_May17_KM.docx](https://github.com/TWUOnline/bug-tracking/files/3929078/PMPP_201_U2_May17_KM.docx)
[PMPP_201_U5_050219_KM.docx](https://github.com/TWUOnline/bug-tracking/files/3929082/PMPP_201_U5_050219_KM.docx)
[PMPP_201_U4_050219_KM.docx](https://github.com/TWUOnline/bug-tracking/files/3929083/PMPP_201_U4_050219_KM.docx)
[PMPP_201_U3_May 17_KM.docx](https://github.com/TWUOnline/bug-tracking/files/3929085/PMPP_201_U3_May.17_KM.docx)
[PMPP_201_U6_May17_KM.docx](https://github.com/TWUOnline/bug-tracking/files/3929086/PMPP_201_U6_May17_KM.docx)

**Comment by kmarjanovic** [comment]
[PMPP_201_U10_050219_MS.docx](https://github.com/TWUOnline/bug-tracking/files/3929090/PMPP_201_U10_050219_MS.docx)
[PMPP_201_U11_050319_MS.docx](https://github.com/TWUOnline/bug-tracking/files/3929091/PMPP_201_U11_050319_MS.docx)
[PMPP_201_U7_042719_MS.docx](https://github.com/TWUOnline/bug-tracking/files/3929092/PMPP_201_U7_042719_MS.docx)
[PMPP_201_U8_043019_MS.docx](https://github.com/TWUOnline/bug-tracking/files/3929093/PMPP_201_U8_043019_MS.docx)
[PMPP_201_U12_050319_MS.docx](https://github.com/TWUOnline/bug-tracking/files/3929094/PMPP_201_U12_050319_MS.docx)
[PMPP_201_U9_050219_MS.docx](https://github.com/TWUOnline/bug-tracking/files/3929095/PMPP_201_U9_050219_MS.docx)

**Comment by kmarjanovic** [comment]
Note some changes were made online, so please use these as a reference, not replacing text as it is in Grav.
Thanks again!

**Comment by rezakh66** [comment]
@kmarjanovic 
Hi Kelly
All 12 units are reformatted according to unit 1 . a few things that I have noticed in contents:

1- Many video links need to be added in all units.
2- there are a few mismatches between activities in checklists  and activities in topics for example : u1,u10(personal activities) & u12(far center activities).
3- Resources are repeated in overview section and resource section. any one should be deleted?

**Comment by kmarjanovic** [comment]
Hi Reza,
I've reformatted Units 1 & 2 (see [Issue](https://github.com/TWUOnline/bug-tracking/issues/193).

I need to add all of the links and videos.  Slides need to be fixed (https://github.com/TWUOnline/bug-tracking/issues/192)

Thank you so much for your help!!!
