### ISSUE TITLE
Production - Alert #s/checkmarks (all courses)

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#123]
### Course
LDRS 410
### URL
https://learn.twu.ca/course/view.php?id=10720&section=1
### Instructions
@cmadland I just added #s to the questions in the case study alert - but it adds check marks as well.  Is there any way to remove the checkmarks and just have the numbers?

This likely applies to every course we build, as #s are important in some activities.

**Comment by cmadland** [comment]
As I update Grav on each site, this should resolve, but I'll keep this issue open as a reminder.

**Comment by kmarjanovic** [comment]
@cmadland please update all repos to fix this :)
