### ISSUE TITLE
Production - LDRS 410 U2 pwpt

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#127]
### Course
LDRS 410
### URL
https://learn.twu.ca/course/view.php?id=10720&section=2
### Instructions
Activity 2.1
Please add PowerPoint the Six Steps to Speaking as an Authentic Leader. (@cmadland I sent this in an email - zipfile that I cannot access - MAC issues)

**Comment by cmadland** [comment]
@kmarjanovic 
[six steps to speaking as authentic leader.pptx](https://github.com/TWUOnline/bug-tracking/files/3821968/six.steps.to.speaking.as.authentic.leader.pptx)
I'm not sure if you've seen the file. It's not great. poor resolution photos.
I'll create a presentation.

**Comment by kmarjanovic** [comment]
Yes - a presentation please for all pwpts.
Thanks Colin!

**Comment by kmarjanovic** [comment]
@cmadland  - for a future revision - could we add images?  Right now the black background with white text is a little uninspiring!  Can we find free images similar to the original pwpt?

**Comment by kmarjanovic** [comment]
@cmadland 
I'm just reviewing the course.  This powerpoint is missing all the images...which is the point of using the pwpt format (otherwise it's just a list).
Could we add the images in the pwpt?  
Or perhaps Jessica can help find open images that are similar?
@JessD9 what do you think?

six steps to speaking as authentic leader.pptx

**Comment by cmadland** [comment]
The images in the slide deck were...not good. Maybe a dive into unsplash?

**Comment by kmarjanovic** [comment]
I agree!
Unsplash, pixabay, pixel...
