### ISSUE TITLE
LDRS410

### ISSUE THREAD

**Issue by rezakh66** [TWUOnline/bug-tracking#128]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 wondering to see if we are not missing activity 4.4 as its not there. we only have 4.1,4.2,4.3,4.5
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=10720&section=4
2. Unit #    4     Topic #    2     Activity#  4.4
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
All fixed.

Somehow, activities (alerts) from LDRS 300 have snuck into this course.  @cmadland just wondering why this is?  I had to delete a 300 activity and add back the 410 from the word doc that was missing.
