### ISSUE TITLE
Production - MCOM 281 - Activity Checklist

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#132]
https://learn.twu.ca/course/view.php?id=10713&section=1

### Instructions
Please format Units 2-10 Activity Checklist to be the same format as Unit 1 (alert)

**Comment by rezakh66** [comment]
@kmarjanovic done. please let me know if changes are needed.

**Comment by kmarjanovic** [comment]
Hi Reza,
This isn't the format we need (no table).  Please see the markdown used in Unit 1: https://github.com/TWUOnline/samc-master/blob/master/pages/02.mcom281/07.U1/01.overview/_schedule/alert.md

Thank you for your help!

**Comment by rezakh66** [comment]
Hi,
so only overview sections need to be re-formatted again? but we don't have any extra information than tables to be added for rest of units.  like what you have done in unit1

**Comment by kmarjanovic** [comment]
H Reza,
It should just be the overview sections that need to be changed, but I'll review the course again.
The new format for the Activity Checklists in the Overview section of each unit is to be one alert.
Here is the template: (We need to copy-paste from current info in the current checklist table)

##### Activity 1.2
:fa-film: View the video ....

---
##### Activity 1.3
:fa-film: View the video ...

---
##### Activity 1.4
:fa-book: Read ....

---

##### Assessment: Title (...% )   
:fa-pencil: ...

---

**Comment by faitht1023** [comment]
@kmarjanovic I'm working on formatting the MCOM 281 schedule alerts as well, but there are only titles for the activity names, the tables in the .docx don't have the little blurb about the activity past Unit 1 I don't think. Was there supposed to be information in overview's schedule as well?

**Comment by kmarjanovic** [comment]
Hi Faith,
Could you keep formatting Units 7-10 like you've done?  I'll go through and add the blurbs.  As a default, the icon can be :fa-pencil.
Thanks so much for your help!

**Comment by rezakh66** [comment]
@kmarjanovic Good morning, done.

**Comment by kmarjanovic** [comment]
Thank you Reza!!
