### ISSUE TITLE
Production - 303 help!

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#134]
https://learn.twu.ca/course/view.php?id=10748&section=2

### Instructions
It seems like there is LDRS 300 content in this 303 course.  @cmadland could we sort this out?  I'd rather not go back to the word docs to check whether every activity is correct.

Please see the formatting in Unit 2 Learning Activities and check all other units for these glitches.

**Comment by cmadland** [comment]
do you have a moment to zoom? @kmarjanovic
