### ISSUE TITLE
Production - LDRS 410 link

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#135]
### URL
https://learn.twu.ca/course/view.php?id=10720&section=2
### Instructions
At the end of the Unit Assessment sections, there's a blue button hat says "Assignments" and goes to an error page.  Could you please delete the button?

**Comment by cmadland** [comment]
@kmarjanovic that button is there from the '_pitch' folder inside the 'assessment' folder.

<img width="350" alt="image" src="https://user-images.githubusercontent.com/12282929/68894738-c40d5000-06dc-11ea-953d-d379b7ebeeac.png">

Apparently we can't have hidden folders inside 'section' folders.

https://github.com/TWUOnline/ba-lead/commit/7a314fabac64c7b3b231de70fb74f2f0077d23d2?short_path=42ae723#diff-42ae723d6fc124aceffbbc43070f04f6

**Comment by kmarjanovic** [comment]
Thanks for fixing this!
I didn't know the folder was hidden.
