### ISSUE TITLE
Production - LDRS 303 U4 pwpt & formatting

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#137]
# URL
https://learn.twu.ca/course/view.php?id=10748&section=3
### Instructions
Please add the 2 pwpts.
Also - @cmadland is there a way to fix the formatting of the checkmarks in alerts?  It's very difficult to read, so we need to find a fix.

**Comment by rezakh66** [comment]
@kmarjanovic Can I have the link to dropbox folder where I can find PPt files.

**Comment by kmarjanovic** [comment]
https://www.dropbox.com/home/FAR/LDRS%20303%20PPT%20-%20HBR
https://www.dropbox.com/home/FAR/LDRS%20303%20PPT%20-%20Northouse%208e

Let me know if you can access these.  If not...I can download a zipfolder.

**Comment by rezakh66** [comment]
@kmarjanovic seems file does not exist. can you please email them  to me?

**Comment by kmarjanovic** [comment]
[LDRS 303 PPT - HBR.zip](https://github.com/TWUOnline/bug-tracking/files/3843632/LDRS.303.PPT.-.HBR.zip)
[LDRS 303 PPT - Northouse 8e.zip](https://github.com/TWUOnline/bug-tracking/files/3843633/LDRS.303.PPT.-.Northouse.8e.zip)
