### ISSUE TITLE
LDRS 410 IF FA19 Assessment Tabs - Assessment Details are missing in each tab

### ISSUE THREAD

**Issue by BLMSasaki** [TWUOnline/bug-tracking#138]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 
LDRS 410 IF FA19 Assessment Tabs 
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 
 Under the assessment tabs --- the assessment guidelines are missing for each tab

**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=10800&section=10
2. Unit #   ASSESSMENT      Topic #  TABS     Activity#  ALL TABS  - the assessments are missing
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
@cmadland  - do you know where all the assessment info went?!  I put it in Atom last week and can't find it (code says replace with plugin, but not sure where they are).

**Comment by kmarjanovic** [comment]
All done now!
