### ISSUE TITLE
LDRS 410 IF FA19 Assessment Tab- Field Interview Report - may need editing

### ISSUE THREAD

**Issue by BLMSasaki** [TWUOnline/bug-tracking#139]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 
 LDRS 410 IF FA19 Assessment Tab -- Field Interview Report Tab

**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 
Editing the content of the Field Interview Report Script:

 “My name is ______and I am a student in the Bachelor of Arts in Leadership program at Trinity Western University.

**Please consider changing to: I am a student in the Trinity Western University GEP Pre-Masters Program at ______**

“I am taking a course called “Methods and Mediums of Persuasion and Positive Influence” and one of our assignments is to interview 2 different leaders in 2 different industries. 

**The name of the course mentioned here is different from the name in the moodle** 

**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=10800&section=14
2. Unit #   Assessment Tab     Topic #     Field Interview Report Tab   Activity#  Field Interview
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
now changed.  Thanks for catching that Brenda!
