### ISSUE TITLE
LDRS 303 IF FA19 Unit 1 Assessment - bottom of page - Reflective Journal blue tab not working

### ISSUE THREAD

**Issue by BLMSasaki** [TWUOnline/bug-tracking#140]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 
 LDRS 303 IF FA 19 

**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 
Unit 1 -- Assessment -- please go to the bottom of the page - Reflective Journal blue tab not working (Error 404 when clicked)
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=10798&section=1
2. Unit #   1     Topic # Assessment        Activity#  Reflective Journal blue tab
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
@cmadland This button shouldn't be there (it appeared when I added the alert). 
Can you please fix this?

Note Brenda that they don't need this button.  I'm adding the assignment dropboxes now in the assessment section
