### ISSUE TITLE
LDRS 303 IF FA19 Assessment tab Strength Paper Tab - link broken

### ISSUE THREAD

**Issue by BLMSasaki** [TWUOnline/bug-tracking#141]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 
 LDRS 303 IF FA19

**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.

 Under the Assessment tab, 
 --> the Strengths Paper and Presentation Tab, 
--------> 6.a Strengths Report
----------------->In Activity 6.2: Assessing Your Strengths, you completed a survey at **strengths.gallup.com.** 
this link (strengths.gallup.com) is broken - Error 404
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=10798&section=13&notifyeditingon=1
2. Unit #   Assessment     Topic #   Strengths Paper and Presentation      Activity#  6.a link to strengths.gallup.com does not work --error 404
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
Link fixed.  @BLMSasaki please confirm whether this is the exact one the text mentions. (students should have the access code in their text).
