### ISSUE TITLE
wrsh101 - u1

### ISSUE THREAD

**Issue by cmadland** [TWUOnline/bug-tracking#145]
Learning activities need to be moved to 'Alerts' and embedded.
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:

 https://far.twu.ca/samc/wrsh101/u1

**Comment by cmadland** [comment]
Not urgent for current cohort. Complete before Jan 1

**Comment by faitht1023** [comment]
U4 numbering of learning activities is slightly unclear. Between the week 6/7/8 schedules, there appears to be some overlap, but I wasn't sure of how to number them/order them, would it be possible to get this clarified please?
