### ISSUE TITLE
SOCI 101 - U1 images

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#15]
### Course
SOCI 101 FAR Master

### URL
https://learn.twu.ca/course/view.php?id=10781&section=1

### Instructions

Please format the 3 images (Topic 1: Activity 1.1).  I've uploaded smaller image sizes, but those don't seem to be showing.  (See word doc if needed)

**Comment by cmadland** [comment]
unit 3 md file and media created in https://github.com/TWUOnline/arts-master/tree/master/pages/06.soci101/_files

**Comment by 345-Jay** [comment]
I added the third image.

**Comment by 345-Jay** [comment]
@kmarjanovic added the third image

**Comment by kmarjanovic** [comment]
Images still missing in Unit 1 (Topic 2 activities)
@cmadland is there a Unit 1 media file?

**Comment by kmarjanovic** [comment]
Thank you!
