### ISSUE TITLE
Production - LDRS 500 Activity checklists

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#150]
### URL
https://learn.twu.ca/course/view.php?id=10719
### Instructions
Could we add the newest format of the Activity checklist to this course?

@cmadland this may need to wait until the Fall cohort is done - or we can try that new server method you mentioned the other day.

**Comment by rezakh66** [comment]
@kmarjanovic all checklists are reformatted

**Comment by kmarjanovic** [comment]
Thank you Reza!
