### ISSUE TITLE
PHIL 210 - Activity Checklists

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#153]
### URL
https://learn.twu.ca/course/view.php?id=8095&section=1
### Instructions
Please add new alert format for unit checklists.

##### Activity 1.1
:fa-book: Read...

---

##### Activity 1.2
:fa-film: Watch

**Comment by rezakh66** [comment]
@kmarjanovic Hi,

should we change activities into alert format too or not? like what I have done in unit 1.

**Comment by kmarjanovic** [comment]
Hi Reza,
Let's just wait on that part for now.  I'll get some feedback from the SME.

**Comment by rezakh66** [comment]
@kmarjanovic all done. only unit 1 activities are in alert format too.

**Comment by kmarjanovic** [comment]
Hi Reza,
Can we go ahead and do the rest of the activity alerts for Units 2-10?
Also, could you check that all Activity titles have heading level #4, and that there are no awkward checkmarks?
Thank you!!

**Comment by rezakh66** [comment]
@kmarjanovic 
Hi Kelly,
I reformatted all the activities and I think that following items should be revised:
1- unit 2 activity 2.6 is missing
2- unit 3 activity 3.3 first video is private
3- unit 4 assignment 3 is missing
4-unit 5 activity 5.2 second video is private
5- unit 7 activity 7.2 please check if right video is inserted. it should be.
6- unit 9 activity 9.5 is missing

**Comment by kmarjanovic** [comment]
All fixed. Thanks so much!!
