### ISSUE TITLE
CMPT 113 Formatting Issue

### ISSUE THREAD

**Issue by dgaudet48** [TWUOnline/bug-tracking#157]
**Which course contains the bug?**  
- CMPT 113 FNAS Master
 
 
**Describe the error and/or your suggestion**  
On my Topic 4 Learning Activity/Alert - I cannot get the "checkmark" bullet points to format correctly.
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=12657&section=1
2. Unit # 1        Topic #  4       Activity#  (Alert 1_4)
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
I've had the same issue in my courses.  @cmadland  any ideas to fix this?

**Comment by cmadland** [comment]
It can be fixed by ensuring there are no empty lines between bullet points.

https://github.com/TWUOnline/fnas-master/commit/0d01774d3d897ac6192385a6c1fa508d1b441bec

**Comment by kmarjanovic** [comment]
Thanks Colin!!!  I've been trying things out for weeks, so glad to have that issue resolved.

Now - any tips for when numbers are required?  1. - always has a checkmark before it, but 1) seems to work fine.   Does 1. work?
