### ISSUE TITLE
SOCI 101 U1 image & button

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#16]
### Course
SOCI 101 FAR
### URL
https://learn.twu.ca/course/view.php?id=10781&section=1

### Instructions
Topic 2 - activity 1.3 & 1.4
Please upload & format 3 images in word (need to find credit info on pixabay).

Also - add button at bottom of page to go to Topic 3 (once you click on the flashcard activity, it's difficult to get back to the unit.)

**Comment by kmarjanovic** [comment]
@cmadland is there a way to add navigation buttons on embedded pages? (See Unit 1, Topic 2, Activity 1.4.  Once you click on the flashcard activity, it's difficult to get back to the unit.

**Comment by kmarjanovic** [comment]
@cmadland Please delete Media button in the Assessment section of Unit 1
https://learn.twu.ca/course/view.php?id=10781&section=1

**Comment by faitht1023** [comment]
@kmarjanovic the media button in the assessment section of Unit 1 should be gone now. Where are the word files for SOCI 101 U1 for the images? I looked in the "files" folder of SOCI 101 but found only U3-U7 word files there.

**Comment by kmarjanovic** [comment]
Hi Faith,
I still see a broken button in the assessment section of each unit (some say media, other say quiz or paper).
I've uploaded Units 1-2 in github files now, so that's all of them.
Thank you for your help!

**Comment by rezakh66** [comment]
@kmarjanovic Hi, I moved 3 pictures into activity 1.3.

**Comment by kmarjanovic** [comment]
Hi Faith,
I've been moving all pictures and and content not related to activity instructions to the Topics.  Please don't move back into the activity alerts.

The major issue for now in this course is that images are missing.  I have notes in red & Issue Tracking requests for these.

Broken buttons are still there in the Assessment section in the units.  @cmadland  do you know how to fix this?

**Comment by cmadland** [comment]
Here is the issue with the extra buttons...

![Screen Shot 2019-12-18 at 4 34 12 PM](https://user-images.githubusercontent.com/12282929/71135783-86a65180-21b7-11ea-8539-7fa813888fed.png)

To solve, we need to move the alert out of the 'Assessment' folder and into the Unit folder, then update the path on the 'section.md' file in the Assessment folder.

![Screen Shot 2019-12-18 at 5 05 04 PM](https://user-images.githubusercontent.com/12282929/71136393-932ba980-21b9-11ea-965b-31c99fbd2529.png)

Does that make sense?
