### ISSUE TITLE
SOCI 101 - U7

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#160]
https://learn.twu.ca/course/view.php?id=10781&section=7
### Instructions
Please upload & format Unit 7.
[SOCI_101_Unit7_Nov26_KM.docx](https://github.com/TWUOnline/bug-tracking/files/3893708/SOCI_101_Unit7_Nov26_KM.docx)

**Comment by cmadland** [comment]
unit md file and media created in https://github.com/TWUOnline/arts-master/tree/master/pages/06.soci101/_files
