### ISSUE TITLE
Uploading files to GH

### ISSUE THREAD

**Issue by cmadland** [TWUOnline/bug-tracking#161]
When you upload word or ppt or pdf files to a repo, please do so in the '_files' folder above unit 1. When it is in the unit folder, the converted markdown file interferes with the template in grav because there are two .md files in the folder and grav can't decide which to use.

Hey, we can do a 'check if you've read this' thing...last one to check can close the issue...let me know if this is weird.

- [x] @dgaudet48 
- [ ] @kmathews1 
- [x] @kmarjanovic

**Comment by kmarjanovic** [comment]
sounds good!

**Comment by dgaudet48** [comment]
Sounds good to me as well...
