### ISSUE TITLE
SOCI 101 U1 alert

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#163]
https://learn.twu.ca/course/view.php?id=10781&section=1
### Instructions
I've added the alert for the Activity checklist, but it is still showing the old format. @cmadland am I missing something?
Also - could we add the proper buttons/tabs to the left and bottom?

**Comment by cmadland** [comment]
https://github.com/TWUOnline/arts-master/commit/15977e2fd32a190e3f11eb87a20f98215a7a5b50

@kmarjanovic
