### ISSUE TITLE
NURS 510 U1

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#165]
## URL
https://learn.twu.ca/course/view.php?id=10939&section=1
### Instructions
Please upload Unit 1.
[NURS_510_Unit_1_KM.docx](https://github.com/TWUOnline/bug-tracking/files/3906065/NURS_510_Unit_1_KM.docx)

@cmadland could you add the Bug Report link to this course?  Also, please let me know the embed code / URL so I can review the course online.

**Comment by kmarjanovic** [comment]
Could we have the table in Topic 4 formatted?

@cmadland could you add the Bug Report link to this course? 

Also - is the youtube plugin enabled in this directory? (see Activity 1.5)

**Comment by rezakh66** [comment]
@kmarjanovic 
Hi,
I uploaded the table as a picture. is it good or change it back to the table format?

**Comment by rezakh66** [comment]
youtube video fixed

**Comment by kmarjanovic** [comment]
Excellent!  Thanks Reza!!
