### ISSUE TITLE
youtube video

### ISSUE THREAD

**Issue by rezakh66** [TWUOnline/bug-tracking#166]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 SOCI 101
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
inserted  youtube video is private
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=10781&section=5
2. Unit #    5     Topic # 5        Activity# 5.13 
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
Thanks Reza!  I'll check with the SME.
