### ISSUE TITLE
SOCI 101 - U1 activity alerts

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#168]
### URL
https://learn.twu.ca/course/view.php?id=10781&section=1
### Instructions
Could you please put the learning activities in alerts?  Also move to the Topics page, rather than it's own activity page.
Thank you!

**Comment by rezakh66** [comment]
@kmarjanovic Done.

**Comment by kmarjanovic** [comment]
Thank you!
