### ISSUE TITLE
Video link is missing?

### ISSUE THREAD

**Issue by rezakh66** [TWUOnline/bug-tracking#169]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 
 SOCI 101
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 Population pyramids: Powerful predictors of the future - Kim Preshoff (5 minutes)
is this supposed to be linked to a video?
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=10781&section=6
2. Unit #   6      Topic #    1     Activity#  6.2
 
**Optional: Screenshots**

**Comment by rezakh66** [comment]
@kmarjanovic 
I found a video with same title and inserted. please check if that's correct.?

**Comment by kmarjanovic** [comment]
yes - it's linked in the activity checklist - just forgot to link it here.
Please add:
https://www.youtube.com/watch?v=RLmKfXwWQtE

**Comment by rezakh66** [comment]
Sure
