### ISSUE TITLE
SOCI 101 U1 image & format

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#17]
### Course
SOCI 101 FAR

### URL
https://learn.twu.ca/course/view.php?id=10781&section=1

### Instructions

Topic 3.  Please upload google map image in word doc.
Also, please format chart (top row of header info is missing).

**Comment by rezakh66** [comment]
@kmarjanovic 
Hi,
done.

**Comment by kmarjanovic** [comment]
Looks great! Thank you!
