### ISSUE TITLE
LDRS 410 IF FA19 Unit 6 Topic 2 broken link

### ISSUE THREAD

**Issue by BLMSasaki** [TWUOnline/bug-tracking#172]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 
 LDRS 410 IF FA19

**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
this link appears to be broken --> *_The oxford union rough guide to debating._**

Midway down the page where it says:
Reference 

The information included in the document How to Debate was adapted from: 

Kidd, A. (2002). **_The oxford union rough guide to debating._** The English Speaking Union. Retrieved August 26, 2002 from the World Wide Web.

**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=10800&section=6
2. Unit #  6       Topic #   2      Activity#  Reference
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
Checking with Shelley
