### ISSUE TITLE
LDRS 303 IF FA19 question repeated in two units

### ISSUE THREAD

**Issue by BLMSasaki** [TWUOnline/bug-tracking#173]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 LDRS 303 IF FA19  
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 
a question posted for the discussion section in Unit 7 is also the same question posed in Unit 5
 **How can we apply the leader-follower relationship in our family, school, work, community, and societal?** 
I think it is meant for unit 5 and needs to be deleted from unit 7 - please verify 

**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  Unit 7 Link --> https://learn.twu.ca/course/view.php?id=10798&section=7
Unit 5 link --> https://learn.twu.ca/course/view.php?id=10798&section=5

2. Unit #  7 & Unit #5     Topic #       Learning Activities   Activity#  7.4 & 5.4
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
Thanks for catching that Brenda!  I've deleted the question.
