### ISSUE TITLE
LDRS 303 IF FA19 Unit 10 video Professor Liang is a repeated one from an earlier unit

### ISSUE THREAD

**Issue by BLMSasaki** [TWUOnline/bug-tracking#174]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 
 LDRS 303 IF FA19

**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 
 The video in unit 10, activity 10.1 is a repeat of an earlier video in a different unit.

**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=10798&section=10
2. Unit #    10     Topic #  Activity 10.1       Activity#  Activity 10.1 video
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
Checking with Stephen.

**Comment by karenroeck** [comment]
@BLMSasaki Did this video get updated or can I help here?

**Comment by BLMSasaki** [comment]
Hi Karen -- not sure which video this is!

B


Brenda-Lee Sasaki, MA, CLC, ACC

Adjunct Professor | TWU Richmond

Academic Facilitation Specialist | TWU GLOBAL

Trinity Western University | t. 604.513.2193 | c. 604.785.4126 | e. Brenda-lee.Sasaki@twu.ca


twu.ca<http://www.twu.ca/>



[cid:image003.png@01D567BE.8201A250]<https://www.facebook.com/trinitywestern/>  [cid:image004.png@01D567BE.8201A250] <https://www.instagram.com/trinitywestern/>   [cid:image005.png@01D567BE.8201A250] <https://twitter.com/TrinityWestern>   [cid:image006.png@01D567BE.8201A250] <https://www.youtube.com/user/TrinityWesternU>   [cid:image007.png@01D567BE.8201A250] <https://www.linkedin.com/school/trinity-western-university/>



[cid:image001.png@01D5649E.C2C49090]


Trinity Western University is located on the traditional, ancestral, and unceded territory of the Sto:lo people.
________________________________

**Comment by karenroeck** [comment]
No worries - I'm just going through old bugs and this was one that seemed unresolved. Here are the details from your original ticket. Let me know if this got resolved and I'll close the ticket :)

Which course contains the bug?

**Course Code, section, and term (e.g. LDRS 591 OL SP2019)**
LDRS 303 IF FA19

**Describe the error and/or your suggestion**
A clear and concise description of what the error or suggestion is.

The video in unit 10, activity 10.1 is a repeat of an earlier video in a different unit.

**Location of the bug**
Please provide a specific link to the page with the error, as well as where the error is on the page:

URL: https://learn.twu.ca/course/view.php?id=10798&section=10
Unit # 10 Topic # Activity 10.1 Activity# Activity 10.1 video

**Comment by BLMSasaki** [comment]
No - Karen -- I don't think this was resolved.



Brenda-Lee Sasaki, MA, CLC, ACC

Adjunct Professor | TWU Richmond

Academic Facilitation Specialist | TWU GLOBAL

Trinity Western University | t. 604.513.2193 | c. 604.785.4126 | e. Brenda-lee.Sasaki@twu.ca


twu.ca<http://www.twu.ca/>



[cid:image003.png@01D567BE.8201A250]<https://www.facebook.com/trinitywestern/>  [cid:image004.png@01D567BE.8201A250] <https://www.instagram.com/trinitywestern/>   [cid:image005.png@01D567BE.8201A250] <https://twitter.com/TrinityWestern>   [cid:image006.png@01D567BE.8201A250] <https://www.youtube.com/user/TrinityWesternU>   [cid:image007.png@01D567BE.8201A250] <https://www.linkedin.com/school/trinity-western-university/>



[cid:image001.png@01D5649E.C2C49090]


Trinity Western University is located on the traditional, ancestral, and unceded territory of the Sto:lo people.
________________________________

**Comment by karenroeck** [comment]
I went through and checked all of Stephen's video lectures and can't find where the Activity 10.1 video is repeated earlier. Do you remember where in the course it is already shown?

**Comment by BLMSasaki** [comment]
Hi Karen -- I went back and looked as well and it has been changed. These all seem to be the correct videos!

yeah!

Well done!
Brenda


Brenda-Lee Sasaki, MA, CLC, ACC

Adjunct Professor | TWU Richmond

Academic Facilitation Specialist | TWU GLOBAL

Trinity Western University | t. 604.513.2193 | c. 604.785.4126 | e. Brenda-lee.Sasaki@twu.ca


twu.ca<http://www.twu.ca/>



[cid:image003.png@01D567BE.8201A250]<https://www.facebook.com/trinitywestern/>  [cid:image004.png@01D567BE.8201A250] <https://www.instagram.com/trinitywestern/>   [cid:image005.png@01D567BE.8201A250] <https://twitter.com/TrinityWestern>   [cid:image006.png@01D567BE.8201A250] <https://www.youtube.com/user/TrinityWesternU>   [cid:image007.png@01D567BE.8201A250] <https://www.linkedin.com/school/trinity-western-university/>



[cid:image001.png@01D5649E.C2C49090]


Trinity Western University is located on the traditional, ancestral, and unceded territory of the Sto:lo people.
________________________________
