### ISSUE TITLE
WRSH 101 alert checkmarks

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#175]
# URL
https://learn.twu.ca/course/view.php?id=10744&section=1
### Instructions
We need some formatting help for this course still.  In the alerts with checkmarks, there are extra spaces (content on next line), and some have a number and a checkmark.  I'm not sure how to delete these checkmarks.

Also, for some "Questions to Consider" we can add :fa-question:  instead of the checkmark.

**Comment by faitht1023** [comment]
@kmarjanovic I'm working on formatting WRSH 101 right now, I believe that the checkmarks are a part of the alerts (not sure if there's any way to remove them other than by removing the space between the number and the words beside it?).

**Comment by kmarjanovic** [comment]
Hi @faitht1023 
There is a way to fix it by ensuring there are no empty lines between bullet points.  I usually have to double check the results in Moodle, as this formatting is so finicky!!

**Comment by faitht1023** [comment]
@kmarjanovic I've gone through all the units and fixed the empty lines. Is there anything else to be formatted in this course?

**Comment by kmarjanovic** [comment]
@faitht1023 
Thanks Faith!
I still want to find a way to not have both numbers and a checkmark.  @cmadland do you have a solution?
![image](https://user-images.githubusercontent.com/35148983/73690832-7296b080-468e-11ea-8827-5dc6c617ed38.png)
I'll look through the rest of the course this week, as I see a couple other items to fix.

**Comment by cmadland** [comment]
I've updated Grav and that seems to have resolved the issue. @kmarjanovic @faitht1023

**Comment by kmarjanovic** [comment]
Thank you Colin!!!! This has been bugging me for months!!!
