### ISSUE TITLE
SOCI 101 - click to enlarge

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#178]
### URL
https://learn.twu.ca/course/view.php?id=10781&section=4
### Instructions
For the image at the end of Unit 4, Topic 4, could we have a ‘click to enlarge’ feature so we can read all of the text?

**Comment by rezakh66** [comment]
@kmarjanovic Hi
we just added a zooming plugin. please see if you have any idea.
?lightbox=1024&cropResize=200,200 is the extra code. for example:
![](pic10.jpg?lightbox=1024&cropResize=400,400)

**Comment by rezakh66** [comment]
![](pic10.jpg?lightbox=1024&cropResize=400,400)
