### ISSUE TITLE
LDRS 303 - U10 video

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#179]
### URL
https://learn.twu.ca/course/view.php?id=10748&section=10
### Instructions
Please upload video to Unit 10 learning activities.
(file in dropbox sent via email.)
Scott could you format first? (The current Unit 10 video is incorrect)

**Comment by scottmacklin** [comment]
Updated U10 video has been uploaded to Streams and now has to be embedded into Moodle Course.

**Comment by kmarjanovic** [comment]
Thanks so much, Scott!
I updated the embed code, so all good now.

When there's time, could you edit out the first few seconds and add the title like the other videos?
