### ISSUE TITLE
SOCI U5 images

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#181]
### URL
https://learn.twu.ca/course/view.php?id=10781&section=5
### Instructions
Please see comments to Production in unit (adding images).

@cmadland can we discuss the process for inserting media?  When units are uploaded can ATAs add images as well, or flag these missing images? I find I'm looking back at the word docs to search for missing pieces.
Thank you!

**Comment by rezakh66** [comment]
@kmarjanovic baby picture is added. it was saved in a wrong folder.

**Comment by kmarjanovic** [comment]
Please add Table 10.3 at the end of Topic 1.

**Comment by rezakh66** [comment]
@kmarjanovic Hi,
these are added.

**Comment by kmarjanovic** [comment]
Thanks Reza!!

Just a note about this course.  Most images don't go in the activity alerts.  I've corrected most of these, but if you're adding images to other units, please add to the topic section (above or below an activity alert).
