### ISSUE TITLE
NURS 510 U4 Overview

### ISSUE THREAD

**Issue by faitht1023** [TWUOnline/bug-tracking#183]
**Which course contains the bug?**  
- NURS 510 (OL Master)
 
 
**Describe the error and/or your suggestion**  
Discrepancies in U4 learning activities (between what's actually on Moodle and the .docx file)
From the .docx file:
"Activity Checklist
Here is a checklist of learning activities you will benefit from in completing this unit. You may find it useful for planning your work. 
Activity 4.1: Watch/View and Take Note (Videos) in Topic #1 
Activity 4.2: Complete three/four articles (in the order listed in the topics) 
Activity 4.3: Explore one contemporary ethical theory and teach peers (Thought exchange)  
Assessment: Thought exchange (four select theories); integration of content into final integration paper; "

What is currently on Moodle:
"Here is a checklist of learning activities you will benefit from in
completing this unit. You may find it useful for planning your work.

##### Activities 4.1-4.2:
:fa-film: View and take note of the videos listed in Topic #1.

---
#####  Activity 4.3:
:fa-book: Read, reflect, analyze, and critique two articles listed.

---
#####  Activity 4.4:
:fa-book: Read the Yeo article and Identify Influences. See additional resources about Roy’s Adaptation Model.

---
#####  Activity 4.5:
:fa-book: Explore one of three contemporary ethical theories and teach peers (Thought exchange).

---
#####  **Assessment:**
:fa-book: **Synchronous Session** Thought exchange; integration of content into final integration paper.
"

Which is the correct version of the learning activities? 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=10939&section=4
2. Unit # 4   Topic # Overview        Activity#  
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
Hi Faith,
I corrected things online the other day, so the checklist and activities are good as is.  The unit docs can be a reference - but I often change things online.
