### ISSUE TITLE
SOCI 101 - U7 media

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#184]
### URL
https://learn.twu.ca/course/view.php?id=10781&section=7
### Instructions
For Activity 7.1, could we have a different layout for the 5 images?  Perhaps we can put it into a slideshow? - Presentations plugin.

**Comment by rezakh66** [comment]
@kmarjanovic I put them in a slideshow. please see how does it look?

**Comment by kmarjanovic** [comment]
That looks great Reza!
I modified the credit line, and added instructions about scrolling.
Also, is there a way to hide/remove the "U7" that is above the slideshow?

**Comment by kmarjanovic** [comment]
@rezakh66 - not sure what happened to the images/slideshow, but it's not working.

@cmadland is this a glitch in the system?
