### ISSUE TITLE
SOCI 101 pdf 

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#187]
### URL
https://learn.twu.ca/course/view.php?id=10781&section=10
### Instructions
Could we possibly get a cleaner version of this pdf? (or put in github in markdown)?

[Social_Issues_Paper_A.pdf](https://github.com/TWUOnline/bug-tracking/files/3947286/Social_Issues_Paper_A.pdf)

**Comment by rezakh66** [comment]
@kmarjanovic Hi
do we know name of the book? then I can look in library to see if we can find it

**Comment by kmarjanovic** [comment]
Hi Reza,
It's from The Sociology Students Writing Manual 6ed, (Johnson, Rettig, Scott & Garrison, 2010).
Thanks for checking on this!

**Comment by rezakh66** [comment]
@kmarjanovic 
Hi Kelly,
I checked with the librarian and she is asking to check if below link is what we are looking for? they need more details.
https://www.amazon.com/Criminal-Justice-Student-Writers-Manual/dp/0133514382

**Comment by kmarjanovic** [comment]
Hi Reza,
This is the book: https://www.amazon.ca/Sociology-Student-Writers-Manual-6th/dp/0205723454

**Comment by kmarjanovic** [comment]
Hi Reza,
I converted the pdf to a word doc and then copied the markdown to atom.  All done!
