### ISSUE TITLE
PMPP 201 Unit Slides

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#192]
https://learn.twu.ca/course/view.php?id=8951&section=1

Could you please add the Unit Slides to the correct activities? (Usually first personal activity of each unit.
Note all slides are currently in each unit folder, so I would suggest move them to [Presentations folder in Github](https://github.com/TWUOnline/ba-lead/tree/master/pages/01.pmpp201/presentations)

**Comment by 345-Jay** [comment]
@kmarjanovic I made the changes to PMPP 201. However, I noticed that the TWU image in the first power point presentation; didn't come out well. 

I tried lookin for other TWU logos but it didnt work out. Is there work around for this? Also, some chapter power points didn't have any images to be inserted. Is that supposed to be?

**Comment by kmarjanovic** [comment]
Hi @345-Jay ,
I deleted the twu image (too fuzzy to use).
Also - could you please add the Unit Slides to the correct activities? (Usually first personal activity of each unit. (Unit 1, Topic 1, Personal Activity 1.1.3; Unit 2, Personal Activity 2.0.1, etc.)
Note all slides are currently in each unit folder, so I would suggest move them to Presentations folder in Github.

I'm still editing this course, as I see major sections are missing from the original unit documents.

Thank you for your help!
