### ISSUE TITLE
PMPP 201 - activities

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#193]
https://learn.twu.ca/course/view.php?id=8951&section=2

### Instructions
For Units 3-12, please move the Personal Activities at the bottom of the Overview section - to their own page (See Unit 2 as an example).

Also - For this course I'm switching all the FAR activities to Green (alert-success) and Assessments to Grey (alert-secondary). Personal Learning Activities will stay blue (primary)

**Comment by rezakh66** [comment]
all Far center activities are changed to green alert-success

**Comment by kmarjanovic** [comment]
Thank you!
