### ISSUE TITLE
NURS 510 - U3 pdf

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#194]
https://learn.twu.ca/course/view.php?id=10939&section=4
### Instructions
Could we fix the pdf in Activity 3.4 (Unit 3, Topic 4)?  Every other page is turned around.

@cmadland could you please add the Bug Report link to this repository?

**Comment by rezakh66** [comment]
@kmarjanovic Pdf is fine now.

**Comment by kmarjanovic** [comment]
Thank you!
