### ISSUE TITLE
NURS 510 Overviews

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#195]
https://learn.twu.ca/course/view.php?id=10939&section=2
### Instructions
In the Overview of each unit, please have a Click to Open feature for the section: COURSE LEARNING OUTCOMES PARTICULARLY RELEVANT THIS UNIT:

**Comment by faitht1023** [comment]
added the click to open feature for Units 1-7, Units 8-11 have yet to be added

**Comment by kmarjanovic** [comment]
Perfect!! Thanks Faith!
@faitht1023
