### ISSUE TITLE
WRTG 101 - M2

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#197]
### URL
https://learn.twu.ca/course/view.php?id=10769&section=3### Instructions

Please see Module 2: Lesson 5 and add missing content.
[WRTG_101 _M2_Aug_8_SH.DOCX](https://github.com/TWUOnline/bug-tracking/files/3970387/WRTG_101._M2_Aug_8_SH.DOCX)

**Comment by rezakh66** [comment]
@kmarjanovic Hi
please check and let me know how it can be improved.

**Comment by kmarjanovic** [comment]
It's looking good!  
I still see some blurry pics, but realize now some of them have that click to enlarge feature.  I'll have another look this weekend, but it's definitely shaping up!
Thanks for your help!!!
