### ISSUE TITLE
WRTG 101 M4 Lesson 2

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#199]
### URL
https://learn.twu.ca/course/view.php?id=10769&section=5
### Instructions
Instead of the pdf posted in Lesson 2 of Module 4, could we have the content on the page (or if necessary a presentations plugin or image capture of charts?)

**Comment by rezakh66** [comment]
@kmarjanovic Hi
I have worked on both screenshots and ppt methods to compare and pick one. ppt is not showing properly though which I and Colin are working to see why slides get aligned vertically rather than horizontally.

**Comment by kmarjanovic** [comment]
Hi Reza,
The screen shots seem a little blurry, so I'm going to suggest we have a mix of content on the page and then we can have the image capture of charts or things that don't come across in markdown.  I'll work on this this afternoon and will add notes.

**Comment by kmarjanovic** [comment]
Hi Reza & Colin,
I've revised the lesson, and I think it looks best (& most like the prof's original work) - when we use markdown & insert images of coloured text/charts.
See: https://learn.twu.ca/course/view.php?id=10769&section=5

I'll be making those changes with the rest of the modules.  Thank you for your help in figuring out the options!!
