### ISSUE TITLE
PHIL 210 Assessment

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#200]
### URL
https://learn.twu.ca/course/view.php?id=8095&section=11

### Instructions
Could we add assessment pages for the assignments?  Currently the info is in pdfs linked from the table.  Please put in separate pages and have tabs at the side to navigate from the assessment page.
![image](https://user-images.githubusercontent.com/35148983/71146231-422bad80-21d9-11ea-89d5-2167913451b2.png)

[PHIL-210-Ethics-Video.docx](https://github.com/TWUOnline/bug-tracking/files/3981773/PHIL-210-Ethics-Video.docx)
[PHIL-210-Ethics-Committee.docx](https://github.com/TWUOnline/bug-tracking/files/3981774/PHIL-210-Ethics-Committee.docx)
[PHIL-210-Reflective-Journal.docx](https://github.com/TWUOnline/bug-tracking/files/3981775/PHIL-210-Reflective-Journal.docx)
[PHIL-210-Partner-Project-Presentation.docx](https://github.com/TWUOnline/bug-tracking/files/3981776/PHIL-210-Partner-Project-Presentation.docx)

**Comment by kmarjanovic** [comment]
Could we have this completed by Tuesday if possible?

**Comment by 345-Jay** [comment]
Good morning @kmarjanovic and @cmadland 

The assessment tab that is in PHIL 210 on moodle isnt showing up in Atom; please advise.

**Comment by kmarjanovic** [comment]
I see it in Atom.  Here it is in GitHub: https://github.com/TWUOnline/arts-master/tree/master/pages/02.phil210/assessment

It's just the assessment page at this point with pdfs.  Needs folders /sections for each assignment.

**Comment by kmarjanovic** [comment]
@345-Jay has there been any progress with this?
I'll do it today if not.

**Comment by 345-Jay** [comment]
@kmarjanovic  apolagies for the late response, I have been responding to help requests.

**Comment by kmarjanovic** [comment]
@345-Jay No worries.  Could you confirm whether this issue is done (closed)?  If not, I'll work on it today.

**Comment by 345-Jay** [comment]
No the issue/s haven't been completed.

**Comment by kmarjanovic** [comment]
@345-Jay No problem!  I see some now in Atom so will work on the others.
Thanks for your help!
