### ISSUE TITLE
NURS 510 Assessments

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#201]
### URL
https://learn.twu.ca/course/view.php?id=10939&section=13
### Instructions
Please add the info in the word doc to separate assignment pages - https://github.com/TWUOnline/nurs-master/tree/master/pages/02.nurs510/assignments
Rubrics may need to be formatted.

[N_510_Marking_Rubrics_2020.docx](https://github.com/TWUOnline/bug-tracking/files/3989563/N_510_Marking_Rubrics_2020.docx)

Thank you!

**Comment by kmarjanovic** [comment]
I've added all the assessment info but still need help with the rubrics.  
https://learn.twu.ca/course/view.php?id=10939&section=14

**Comment by rezakh66** [comment]
@kmarjanovic Hi,
Can you please check if rubrics are in the way that you want them?

**Comment by kmarjanovic** [comment]
@rezakh66 
These are looking great!!  Just a couple of changes...could you make the headings in the left column and the headings in the top role bold?  The first rubric in the [Inquiry-based paper](https://learn.twu.ca/course/view.php?id=10939&section=18) is a perfect example of what I'd prefer.

Also, for the participation rubric, could you make columns 3 and 4 the same formatting as the first 2 columns? (smaller text and no checkmarks).
Thanks!!

**Comment by rezakh66** [comment]
@kmarjanovic Hi
I think it should be fine now.

**Comment by kmarjanovic** [comment]
@rezakh66 
Perfect!!  Thanks so much Reza!
