### ISSUE TITLE
NURS 510 Unit 2

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#202]
### URL
https://learn.twu.ca/course/view.php?id=10939&section=3
### Instructions
Please add Unit 2 (note all units are now called lessons.  Please do 'replace all' in course.)

[NURS_510_Unit 2_Dec20_KM.docx](https://github.com/TWUOnline/bug-tracking/files/3989581/NURS_510_Unit.2_Dec20_KM.docx)

**Comment by rezakh66** [comment]
@kmarjanovic Done
