### ISSUE TITLE
NURS 510 Rubrics

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#212]
# URL
https://learn.twu.ca/course/view.php?id=12339&section=14
### Instructions
Could you please add the rubrics to the Assessment pages?  I have them in pdf form now, which I want to keep as an option.  Please add the rubric above the pdf links.
[Personal_Philosophy_Paper_Grading_Rubric.docx](https://github.com/TWUOnline/bug-tracking/files/4027008/Personal_Philosophy_Paper_Grading_Rubric.docx)
[Course_Participation_Grading_Rubric.docx](https://github.com/TWUOnline/bug-tracking/files/4027009/Course_Participation_Grading_Rubric.docx)
[Student-Led_Seminars_Grading_Rubric.docx](https://github.com/TWUOnline/bug-tracking/files/4027010/Student-Led_Seminars_Grading_Rubric.docx)
[Inquiry-based_Writing_Grading_Rubric.docx](https://github.com/TWUOnline/bug-tracking/files/4027011/Inquiry-based_Writing_Grading_Rubric.docx)

**Comment by cmadland** [comment]
I'm not sure I understand what you mean...do you want the rubrics created as Moodle rubrics? or content pages?

**Comment by kmarjanovic** [comment]
I was thinking a content page (part of the assignment page - e.g. https://learn.twu.ca/course/view.php?id=12339&section=18), and having a link to the pdf as well.

However - the instructors may want it in Moodle as well.  I'll check with them.
