### ISSUE TITLE
SOCI 101 Quizzes

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#217]
### URL
https://learn.twu.ca/course/view.php?id=12682&section=9
### Instructions
Could you please add these quizzes to Moodle for SOCI 101?  Note that some quizzes have a B version that can be used later if needed.

**Comment by rezakh66** [comment]
@kmarjanovic Hi,
we need answer key to be able to create the quizzes. Can you please upload them here or in "file" folder?

**Comment by cmadland** [comment]
@rezakh66 we can start creating these questions and just set the answer to 'A' for all of them for now. It will be quick to go back and edit the answers once we have the correct ones.

**Comment by rezakh66** [comment]
@cmadland I got you. good idea

**Comment by rezakh66** [comment]
@kmarjanovic Hi,
I have created all 16 units questions. units 5-16 need to be updated by the correct answers.

**Comment by kmarjanovic** [comment]
Thank you @rezakh66 !

**Comment by kmarjanovic** [comment]
Todd to send us answer keys.

**Comment by rezakh66** [comment]
@kmarjanovic Hi,
He sent me the answer key for all 16 units but I could only update up to unit 14.units 15 and 16 answer keys were for 15B and 16 B. I think Daniel is going to send right answer keys soon.

**Comment by kmarjanovic** [comment]
Thanks @rezakh66 !
I assume the quizzes went well!
