### ISSUE TITLE
LDRS 300 Activity Checklists

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#220]
### URL
https://learn.twu.ca/course/view.php?id=10828&section=6
### Instructions
The Activity Checklists are not in a consistent format for this course.
Please add an alert checklist for Units 5 and 8 - similar to the format of Unit 6.

When we have more time...please change the checklists in the rest of the units to match (not separate activity alerts, but a condensed checklist).

Thank you!
Kelly

**Comment by rezakh66** [comment]
@kmarjanovic Hi Kelly,
Me and Faith did this for whole course. please have a look. please note that unit 9,10 don't exist yet

**Comment by kmarjanovic** [comment]
Hi Reza,
I see this now.  Thank you!!  I think those changes were in a branch that needed to be merged, correct?  @cmadland is there an easier way to see unmerged branches? (that new Git program you mentioned?)

**Comment by rezakh66** [comment]
some were changing of branches but some needed to be changed to alert format from table format
