### ISSUE TITLE
I need to get the Moodle sight updated for SOCI 101 sp 2020 - new syllabus, working links, etc. Any help would be appreciated.

### ISSUE THREAD

**Issue by toddfmartin** [TWUOnline/bug-tracking#222]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  
2. Unit #         Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
Hi Todd,
I've uploaded the syllabus.  Please let us know what else needs to be done.
(Note quizzes are being put on Moodle  - @cmadland  please confirm!)

**Comment by kmarjanovic** [comment]
Course in Moodle: https://learn.twu.ca/course/view.php?id=12682
Course in Github: https://github.com/TWUOnline/arts-master/tree/master/pages/06.soci101
