### ISSUE TITLE
SOCI101 rogue alert.md file

### ISSUE THREAD

**Issue by cmadland** [TWUOnline/bug-tracking#223]
There is a rogue alert.md file in Unit 1 of soci101. It appears to be activity 4-1 in that course, but I'm not sure if it is needed or not.

<img width="1265" alt="image" src="https://user-images.githubusercontent.com/12282929/72559887-aedaac00-385a-11ea-9548-c238484cdda3.png">

**Comment by kmarjanovic** [comment]
I'm not sure what you mean.  In looking at the course, 4.1 is where it's supposed to be.

**Comment by cmadland** [comment]
Yes, 4.1 looks ok, but there is an extra ‘alert.md’ in Unit 1…I presume it can be deleted, but want to check.


--
Colin Madland, MEd (Distance Education)
Online Learning and Instructional Technologies
Trinity Western University  | 7600 Glover Road
Langley, BC | V2Y 1Y1
604.513.2121 ext. 3876 |  colin.madland@twu.ca<mailto:colin.madland@twu.ca>
@colinmadland | create.twu.ca<http://create.twu.ca>

Trinity Western University is located on the traditional, ancestral, and unceded territory of the Sto:lo people.

On Jan 16, 2020, at 12:25 PM, Kelly Marjanovic <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm not sure what you mean. In looking at the course, 4.1 is where it's supposed to be.

**Comment by kmarjanovic** [comment]
I don't see what your screenshot has in my Atom.  It shows the old alert (I had to change sooooo many for this course as the topic content was in most of the activities).  
Perhaps fetch and pull?  (don't revert back to old alerts!)

**Comment by kmarjanovic** [comment]
yes, please delete. (although I still don't see it in my atom)
