### ISSUE TITLE
Content fix and content links

### ISSUE THREAD

**Issue by toddfmartin** [TWUOnline/bug-tracking#225]
**Which course contains the bug?**  
- SOCI 101 OL Spirng 2020
 
 
**Describe the error and/or your suggestion**  
I would like assessment of quizzes to 1% each rather 1.25% each.

- I also noticed the links to practices quizzes are not linked to the right chapter.

- Finally I think it may be easier to remove the online quiz and let the facilitator administer it in class?

Thoughts?
Todd

 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  
2. Unit #         Topic #         Activity#  
 
**Optional: Screenshots**  
![image](https://user-images.githubusercontent.com/59940510/72670765-50e2cb80-39f6-11ea-8934-2a96f0d4df01.png)

![image](https://user-images.githubusercontent.com/59940510/72670780-8d162c00-39f6-11ea-9bd8-c0912c7aaa10.png)

**Comment by kmarjanovic** [comment]
Hi @toddfmartin ,
So would you like the Quiz total to be 16% of the course grade? (1% each?).  What other mark needs to minus a percent then?
I've added the notes to the quiz pages that the quizzes may be administered in the lab.  This was the original intent I believe - that it would be online but taken during lab time.

Also fixed the wrong practice links.  Sorry about that!

**Comment by toddfmartin** [comment]
Hi Kelly, leave everything else. It translate into one absent or a bonus if they do all 16.

Todd

TODD MARTIN, Ph.D, CFLE
Dean, Associate Professor of Sociology | Faculty of Humanities and Social Sciences
Managing Editor | Journal of Comparative Family Studies
Trinity Western University | t. 604.513.2121 (3121)
e. Todd.Martin@twu.ca<mailto:todd.martin@twu.ca>

twu.ca<http://www.twu.ca/>
jcfs.ca<http://www.jcfs.ca/>

[cid:image029.png@01D5882A.376138A0]
