### ISSUE TITLE
Quizzes

### ISSUE THREAD

**Issue by toddfmartin** [TWUOnline/bug-tracking#226]
**Which course contains the bug?**  
-SOCI 101 OL
 
 
**Describe the error and/or your suggestion**  
- This is correct andf I the way IO think we should administer quizzes. maybe the only fix is to remove directing a student to the quizzes at the end of each unit and tell them that they will be administered in the learning lab?
 
 
**Location of the bug**  
https://learn.twu.ca/course/view.php?id=12682&section=1

- all units
 
**Optional: Screenshots**  
![image](https://user-images.githubusercontent.com/59940510/72670835-54c31d80-39f7-11ea-9a2d-a049409ecc86.png)

**Comment by kmarjanovic** [comment]
I've added the note that the quizzes will be administered in the Learning Lab.

**Comment by toddfmartin** [comment]
Thanks

TODD MARTIN, Ph.D, CFLE
Dean, Associate Professor of Sociology | Faculty of Humanities and Social Sciences
Managing Editor | Journal of Comparative Family Studies
Trinity Western University | t. 604.513.2121 (3121)
e. Todd.Martin@twu.ca<mailto:todd.martin@twu.ca>

twu.ca<http://www.twu.ca/>
jcfs.ca<http://www.jcfs.ca/>

[cid:image029.png@01D5882A.376138A0]
