### ISSUE TITLE
Sociology 101 Course Introduction page ... there are 2 pictures or links to videos that are not loading; there is just a spinning circle but it doesn't ever materialize.

### ISSUE THREAD

**Issue by danielsplett** [TWUOnline/bug-tracking#228]
**Which course contains the bug?**  

Sociology 101 Course Introduction page ... there are 2 pictures or links to videos that are not loading; there is just a spinning circle but it doesn't ever materialize.

![image](https://user-images.githubusercontent.com/54082665/72838101-867cf400-3c44-11ea-86ba-0ca0b25e0fa9.png)

**Comment by kmarjanovic** [comment]
Hi @danielsplett 
You have to sign in to access those photos.
I'll add instructions for students.

**Comment by kmarjanovic** [comment]
@cmadland I see the instructions in the WRSH 101 course, but the images aren't working.
Could you fix and add to SOCI 101 please?

**Comment by danielsplett** [comment]
What do you mean 'sign in'?


Sent from my iPhone

On Jan 21, 2020, at 11:56 AM, Kelly Marjanovic <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @danielsplett<https://github.com/danielsplett>
You have to sign in to access those photos.
I'll add instructions for students.

**Comment by kmarjanovic** [comment]
@danielsplett you should be able to use your regular TWU sign in credentials to login to this Microsoft Stream content.
Is the sign in box showing?  It's either in a pop-up, or on the box where the video should be.

**Comment by danielsplett** [comment]
It's just a problem on the Course Introduction page; as I go into Unit I, Topic 1 there are no problems.  Something is wonky with that first - ever-so-important - page that has the revolving circle!  No indication anywhere for signing in.




"The Big 'C' in life is Communication!"

~ Daniel k SPLETT ~


________________________________

**Comment by kmarjanovic** [comment]
@danielsplett has this issue been resolved?  Do you see the videos?
