### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by rezakh66** [TWUOnline/bug-tracking#23]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 PHIL 210 - FAR
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 
"Ethical decision making" is Hyperlinked to be redirected to an application page which seems broken.
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=8095&section=4
2. Unit #  4       Topic #  3       Activity#  4.5
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
Replace with https://play.google.com/store/apps/details?id=com.mcae.decision&hl=en_CA

**Comment by cmadland** [comment]
sorted
