### ISSUE TITLE
MCOM281 ... For the Syllabus, I-Pads do not have the 2nd bar to scroll down to see the rest

### ISSUE THREAD

**Issue by danielsplett** [TWUOnline/bug-tracking#231]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  
2. Unit #         Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by cmadland** [comment]
resolved
