### ISSUE TITLE
NURS 510 - L6

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#233]
### URL
https://learn.twu.ca/course/view.php?id=10939&section=7
### Instructions
Please upload lesson 6
[NURS_510_Lesson_6_Empiric_Final_KM.docx](https://github.com/TWUOnline/bug-tracking/files/4136604/NURS_510_Lesson_6_Empiric_Final_KM.docx)

**Comment by faitht1023** [comment]
@kmarjanovic in topic 3 of unit 6, there's an activity labelled "activity 7.3: student-led seminar". Is this for Unit 7 or it just numbered differently?

**Comment by kmarjanovic** [comment]
@faitht1023 
Hi Faith, 
It should be 6.3.  I'll double check all the numbers after (this is a common missed mistake as we reorder the activities).
Thanks!

**Comment by faitht1023** [comment]
@kmarjanovic no worries, should I leave the numbering alone for now then, since there's already another activity 6.3 in this unit? I've completed formatting/uploading the rest of the unit onto Moodle now!

**Comment by kmarjanovic** [comment]
Yes please.  Thanks so much for your help!
