### ISSUE TITLE
WRTG 101 L3 images

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#234]
### URL
https://learn.twu.ca/course/view.php?id=10769&section=4
### Instructions
In Lesson 3, Body Paragraphs, at the bottom of the page there are 2 images that were difficult to screen shot.  Could we have a Click to Enlarge feature - or another way to show the content? (must be in the same format as original).
![image](https://user-images.githubusercontent.com/35148983/73672572-5da82600-466a-11ea-92d1-e916d1be6368.png)

**Comment by cmadland** [comment]
We had a 'Click to Enlarge' plugin, but it broke the presentations plugin, so we deleted it. This would be an excellent use for the Tufte format page in the new scholar theme...which isn't helpful here...but...I'll look for options.

**Comment by kmarjanovic** [comment]
Ah, that's what happened to the presentations!  Good to know.
Thanks for your help!

**Comment by kmarjanovic** [comment]
@cmadland just circling back to this comment.  Any ideas for clarity of those images?  Should I split up the screenshot?

Also - are there any updates on the new format for this course?  Let me know if we can wrap this one up.
Thanks!!

**Comment by kmarjanovic** [comment]
@cmadland since this course is part of the bundle, could we wrap up this issue?
@JessD9 do you mind going through the course and flagging any design/formatting issues?

A couple of flagged issues already:
[ ] We need to have tags/filters for the FAR and BUNDLE versions of this course.  There are several references to facilitators and Learning Labs.  We can wait until Bundle wording for the support teams is confirmed.

**Comment by kmarjanovic** [comment]
@Jeff-TWU

**Comment by Jeff-TWU** [comment]
@cmadland Sorry, ignorant here. Is there a Github repository that I can make edits on this in Atom? If so, how do I find it? If not please let me know how I should proceed. Thanks!

**Comment by rezakh66** [comment]
@Jeff-TWU Hi Jeff, you should be able to clone the art-master repository in [here](https://github.com/TWUOnline/arts-master). If you have GitHub desktop and Atom installed on your computer, follow the screenshot.
![github](https://user-images.githubusercontent.com/55214859/89352362-c3e92200-d668-11ea-8048-c1c06fb7b6ea.jpeg)

**Comment by Jeff-TWU** [comment]
@rezakh66 Thank you sir!

**Comment by Jeff-TWU** [comment]
Hi @rezakh66 @cmadland  said I should connect with you to see about installing this plugin https://github.com/getgrav/grav-plugin-featherlight on Grav. Would you be able to help me with that? It should give us the expand feature we are wanting.

**Comment by rezakh66** [comment]
@Jeff-TWU  Hi Jeff, I worked on this over the weekend and It's not the way we do normally. I think I need root access to get this up. I'll talk with Colin and let you know

**Comment by Jeff-TWU** [comment]
@rezakh66 No worries. Thanks for looking into that. Much appreciated!

**Comment by Jeff-TWU** [comment]
@cmadland Hi Colin, do you have a moment to see about installing this plugin? Reza tried and didn't seem to have the right access. [https://github.com/getgrav/grav-plugin-featherlight](https://github.com/getgrav/grav-plugin-featherlight)

**Comment by Jeff-TWU** [comment]
@cmadland Just following up on this, should I look into finding a workaround without a plugin? Let me know what you'd prefer. Thanks!

**Comment by Jeff-TWU** [comment]
@cmadland Just circling back to this. It looks like the course has been updated and the content no longer exists. I'm not sure if this is still a general issue that you'd like me to pursue? Or would this now be something that Barish would handle? Please let me know thanks!

**Comment by kmarjanovic** [comment]
This seems to be fixed!  Thanks!
https://learn.twu.ca/course/view.php?id=10769&section=10#tabs-tree-start
