### ISSUE TITLE
LDRS 300 IF FA19 Unit 9 Overview - link not working

### ISSUE THREAD

**Issue by BLMSasaki** [TWUOnline/bug-tracking#235]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 LDRS 300 IF FA19
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 
 Unit 9, Overview, in the blue box, activity 9.1 the link to the video is incorrect (what is culture video) this is the correct link https://www.youtube.com/watch?time_continue=1&v=l57vvpelfHI

**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=10796&section=9&notifyeditingon=1 
2. Unit #   9      Topic #    overview    Activity#  9.1
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
This seems to be the same link as we had.  Could you double check?
