### ISSUE TITLE
LDRS 300 IF FA19 Unit 9 Link should be removed

### ISSUE THREAD

**Issue by BLMSasaki** [TWUOnline/bug-tracking#236]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 
 LDRS 300 IF FA19 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 
 Overview page, at the bottom, under the Resources section, 4th bullet point, the last link is not meant to be there (and is says error 404)

**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=10796&section=9&notifyeditingon=1 
2. Unit #  9       Topic #   overview resources     Activity#  Resources
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
Done!
