### ISSUE TITLE
LDRS 300 IF FA19 Link not working

### ISSUE THREAD

**Issue by BLMSasaki** [TWUOnline/bug-tracking#237]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 
 LDRS 300 IF FA19
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 
 Overview page, bottom of page under Resources, bullet point #5, the video link to chick-fil-a is not activated and the link to the Chick-fil-article is on the same line but should be moved below to as a separate bullet point with its own link
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=10796&section=9&notifyeditingon=1
2. Unit #   9     Topic #   overview      Activity#  resources
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
Done!
