### ISSUE TITLE
LDRS 300 IF FA19 section needs reformatting

### ISSUE THREAD

**Issue by BLMSasaki** [TWUOnline/bug-tracking#239]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 LDRS 300 IF FA19
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 Unit 9, topic 2, the quote in the second paragraph, half is in a yellow box and the other half of the quote and its origin is below the box. Needs to be reformatted
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=10796&section=9&notifyeditingon=1
2. Unit #   9      Topic #    2     Activity#  second paragraph
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
Done!
