### ISSUE TITLE
LDSR 300 IF FA19 link to template missing

### ISSUE THREAD

**Issue by BLMSasaki** [TWUOnline/bug-tracking#240]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 
 LDRS 300 IF FA19 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.

 In the learning activity section, activity 9.2.2, it says "[link to word document template]" but there is no actual link and at the bottom of the three videos in this section it says [Brenda will send template]. I will send the template right now to Kelly.

**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=10796&section=9&notifyeditingon=1
2. Unit #    9     Topic #   2      Activity#  9.2.2
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
Done!
