### ISSUE TITLE
LDRS 300 IF FA19 Unit 9 Topic 3 tab is incorrect

### ISSUE THREAD

**Issue by BLMSasaki** [TWUOnline/bug-tracking#241]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 
 LDRS 300 IF FA19
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 
 The tab section both on the left-hand side of the page and at the bottom of the page (blue topic tab) in topic 2 and topic 3 are mislabeled as topic 2. They should be changed to topic 3. 

**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=10796&section=9&notifyeditingon=1
2. Unit #   9      Topic #     3    Activity#  tabs
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
Done!
