### ISSUE TITLE
LDRS 300 IF FA19 Unit 10 Overview - formatting issue

### ISSUE THREAD

**Issue by BLMSasaki** [TWUOnline/bug-tracking#242]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 LDRS 300 IF FA19
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 
On the overview page, under the heading Topics, the letters and bullet points seem to be jumbled. I think it just needs some reformatting.
 
Also on this page under the resource section one of the bullet points needs reformatting to be aligned with the other ones.

**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=10796&section=10
2. Unit #    10     Topic #     overview   Activity#  topic
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
Done!
