### ISSUE TITLE
LDRS 300 IF FA19 Unit 10 wrong video in lesson

### ISSUE THREAD

**Issue by BLMSasaki** [TWUOnline/bug-tracking#243]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 LDRS 300 IF FA19 UNit 10
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 
 Activity 10.1, the first video is the wrong video. It should be this one https://www.zappos.com/about/stories/why-company-culture-matters 

**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=10796&section=10
2. Unit #  10       Topic #    1     Activity#  10.1
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
Done!
