### ISSUE TITLE
LDRS 300 IF FA19 Unit 10, Topic 2, correction in an activity

### ISSUE THREAD

**Issue by BLMSasaki** [TWUOnline/bug-tracking#244]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 
LDRS 300 IF FA19 Unit 10, Topic 2, Activity 10.4, 3rd sentence
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 
 Unit 10, Topic 2, Activity 10.4, 3rd sentence should read, "Review these four articles and videos."
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=10796&section=10
2. Unit #  10        Topic #   2      Activity#  10.4
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
Done!
