### ISSUE TITLE
Soci 101 u4-5 topic lists

### ISSUE THREAD

**Issue by cmadland** [TWUOnline/bug-tracking#246]
@faitht1023 or @rezakh66  would you please  follow the changes I made at https://github.com/TWUOnline/arts-master/commit/3ba0af211866e7dedc89d99c919abefba9f838eb for the rest of the lists in units 4-5?

The code is 
```
[details="Summary text"]
* Item 1
* Item 2
 * Sub item 1
 * Sub item 2
[/details]
```

**Comment by rezakh66** [comment]
@cmadland Done.

**Comment by kmarjanovic** [comment]
Thank you both!
