### ISSUE TITLE
PMPP 201 linking files

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#247]
### URL
https://github.com/TWUOnline/ba-lead/tree/master/pages/01.pmpp201/19.files
### Instructions
I've added about 30 files to [this folder](https://github.com/TWUOnline/ba-lead/tree/master/pages/01.pmpp201/19.files).
@cmadland will this work to link files in the course?  There are several references throughout the units, so it may be easier to have them in this one place.
Please let me know what works.

e.g. See Unit 3, Topic 1, [FAR Centre Activity 3.1.1: Draft a Scope Management Plan](https://learn.twu.ca/course/view.php?id=8951&section=3)

**Comment by cmadland** [comment]
oh, wow…looks like many of these can be content pages in Grav. Spreadsheets, maybe as downloads from Moodle?


--
Colin Madland, MEd (Distance Education)
Online Learning and Instructional Technologies
Trinity Western University  | 7600 Glover Road
Langley, BC | V2Y 1Y1
604.513.2121 ext. 3876 |  colin.madland@twu.ca<mailto:colin.madland@twu.ca>
@colinmadland | create.twu.ca<http://create.twu.ca>

Trinity Western University is located on the traditional, ancestral, and unceded territory of the Sto:lo people.

On Feb 10, 2020, at 2:05 PM, Kelly Marjanovic <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #247<https://github.com/TWUOnline/bug-tracking/issues/247> to @cmadland<https://github.com/cmadland>.

**Comment by kmarjanovic** [comment]
Yes, definitely.  Matt didn't seem to want that - but perhaps we can have both options - content in Github and downloadable file.  Most are for FAR Centre learning activities that students don't need to see beforehand.

**Comment by kmarjanovic** [comment]
Could we have an ATA convert them all to pages?  
For [Units 1](https://learn.twu.ca/course/view.php?id=8951&section=1) and 2 I started just adding the files to Moodle...I'd rather have files/pages linked in the lesson though.

**Comment by rezakh66** [comment]
@kmarjanovic Hi, I have uploaded all docx files and images. Please see if they are uploaded in right activities or any change needs to be made.

**Comment by kmarjanovic** [comment]
@rezakh66 
Thanks so much, Reza!  I'll have a look.

**Comment by kmarjanovic** [comment]
For FAR Center Activity 1.2.1 (https://learn.twu.ca/course/view.php?id=8951&section=1)
I changed the repeat #s to checkmarks.
But we still have the default checkmarks by each number.  @cmadland can you make sure that fix is in this repository?
![image](https://user-images.githubusercontent.com/35148983/74564669-d3df3f00-4f2c-11ea-896a-da5fe496df52.png)

**Comment by kmarjanovic** [comment]
This issue hasn't been resolved:
![image](https://user-images.githubusercontent.com/35148983/75183610-1e687480-5700-11ea-88c1-da9d9d37f928.png)


Also - please change the colour back to green (not sure why it was changed to blue).

**Comment by 345-Jay** [comment]
Changed the activity colour that was previously green for 1.2.0 to 1.4.1 back to blue.

**Comment by 345-Jay** [comment]
Correction changes acitivities colour to green. https://learn.twu.ca/course/view.php?id=8951&section=1

**Comment by kmarjanovic** [comment]
Hi @345-Jay,
I still see the FAR Centre Activities for Topic 2 in blue.  For this course, Personal Activities are in blue, FAR Centre Activities are in green.
Could you please make that change back?

Also - @cmadland can you please check on the checkmarks issue? (Unit 1, Topic 2, FAR Center Activity 1.2.1)

https://learn.twu.ca/course/view.php?id=8951&section=1

**Comment by rezakh66** [comment]
@kmarjanovic Activity 1.2 is back to green.

**Comment by kmarjanovic** [comment]
We still need to fix the formatting of FAR Center Activity 1.2.1.  
Please compare the original pdf to the The Traits in the click to open feature.  (#s and letters).

**Comment by kmarjanovic** [comment]
I added bold titles to make it stand out.  Still need help with those pesky checkmarks!!!
![image](https://user-images.githubusercontent.com/35148983/76023533-96941e80-5ee6-11ea-9ae9-eb354561756a.png)
