### ISSUE TITLE
PMPP 201 - rubric

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#249]
### URL
https://github.com/TWUOnline/ba-lead/tree/master/pages/01.pmpp201/assignments
### Instructions
Could you please add an alert to the [Assessment section](https://github.com/TWUOnline/ba-lead/tree/master/pages/01.pmpp201/assignments) to be a similar format to the NURS 510 [Assignment rubrics](https://github.com/TWUOnline/nurs-master/tree/master/pages/02.nurs510/assignments)?

Attached is the rubric for PMPP 201.  Currently it's in the assessment section of each unit, but I'd like to replace it with an alert.
[PMPP-201-Written-Assignment-Grading-Criteria.docx](https://github.com/TWUOnline/bug-tracking/files/4187370/PMPP-201-Written-Assignment-Grading-Criteria.docx)

**Comment by rezakh66** [comment]
This is being done for unit 2 assessment section. please let me know if I can use same format for rest of units.
https://learn.twu.ca/course/view.php?id=8951&section=2

**Comment by kmarjanovic** [comment]
Hi @rezakh66 !  That looks great! 
Could we just italicize where it says: 

Emerging (0 to 6 points) | Developing (7 to 8 points) | Mastering (9 to 10 Points)
-- | -- | --

Please feel free to add this rubric alert to the other assessment sections.
Thank you!!
