### ISSUE TITLE
Link needs to be added

### ISSUE THREAD

**Issue by rezakh66** [TWUOnline/bug-tracking#25]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 MCOM 281
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 
a link is supposed to be added
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=10713&section=1
2. Unit #   1      Topic # assessment        Activity#  
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
Which Topic # Activity #?

**Comment by rezakh66** [comment]
i cant find it now. ill look up and will open another issue.
