### ISSUE TITLE
LDRS 410 - H5P activities

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#250]
### URL
https://learn.twu.ca/course/view.php?id=10720&section=3

### Instructions
Please create 2 H5P activities.  Instructions & content in word doc:

[LDRS-410–H5P-Figures-of-Speech-Activities.docx](https://github.com/TWUOnline/bug-tracking/files/4193759/LDRS-410.H5P-Figures-of-Speech-Activities.docx)

**Comment by rezakh66** [comment]
@kmarjanovic Hi,
Both activities are uploaded in 3.6 and 3.7.   https://h5p.org/advanced-fill-the-blanks does not exist in  version of  WordPress that we have. it may comes with the new upgrade.

**Comment by kmarjanovic** [comment]
Thanks @rezakh66 !

For the second activity, is it possible to number the questions.  Could we also have spaces in between?  Is there a setting that allows for lowercase too, or so we need to instruct students to use all caps?
(see screenshot)
![image](https://user-images.githubusercontent.com/35148983/76021488-9f82f100-5ee2-11ea-97f8-3344979b9791.png)

**Comment by rezakh66** [comment]
@kmarjanovic Hi, I have reformatted the second activity and checked off the case sensitivity in settings.

**Comment by kmarjanovic** [comment]
@rezakh66 Perfect!!!
Just one more thought...for the first activity, does it need to have the images in a list to scroll down, or is there a slideshow feature/format for this H5P activity?

**Comment by kmarjanovic** [comment]
@rezakh66  Okay no problem!  Just thought I'd ask!
Thanks again for your help!  The activities look great :)

**Comment by kmarjanovic** [comment]
I hate to ask but...for the first activity could we switch the format to [Quiz (Question Set)](https://h5p.org/question-set)?
In reading the [comments/solutions](https://h5p.org/guess-the-answer) for the 1 image issue, this was suggested.  It makes more sense as the question set rather than scrolling down the page.

**Comment by rezakh66** [comment]
Hi @kmarjanovic There are different types of quizzes that can be made by Quiz(Question Set) like multiple choice, drag and drop, fill in the blanks, drag text, and .... I have found multiple choice most related to the activity but then I need to know choices for each question. please see [here](https://learn.twu.ca/course/view.php?id=10720&section=3) how does it look like and let me know.

**Comment by kmarjanovic** [comment]
@rezakh66 
Yes!  This is much better!
I've added the options to the attached doc:
[LDRS-410–H5P-Figures-of-Speech-Activities_May4_KM.docx](https://github.com/TWUOnline/bug-tracking/files/4577018/LDRS-410.H5P-Figures-of-Speech-Activities_May4_KM.docx)

**Comment by rezakh66** [comment]
@kmarjanovic Hi, It's done. Please let me know if changes are needed.

**Comment by kmarjanovic** [comment]
Perfect!
Thank you @rezakh66 !!
