### ISSUE TITLE
Production

### ISSUE THREAD

**Issue by kmathews1** [TWUOnline/bug-tracking#251]
### Instructions
- Please create lesson 1. Content in word doc attached below:

[NURS_520_lesson_1_Feb_22.docx](https://github.com/TWUOnline/bug-tracking/files/4240500/NURS_520_lesson_1_Feb_22.docx)

**Comment by faitht1023** [comment]
@kmathews1 I've created Lesson 1 according to the .docx and followed the formatting of NURS 510. Please let me know if any changes need to be made.

**Comment by kmathews1** [comment]
@faitht1023 Please add "TO" in the heading...PARTICULARLY RELEVANT THIS LESSON: in the overview page. I think this should be done for all the NURS 510 and 520 lessons. Thanks

**Comment by kmathews1** [comment]
Is there a way of displaying the image of the video like a placeholder image instead of the links of the video?

**Comment by faitht1023** [comment]
@kmathews1 I've added "TO" to both NURS 510 and 520 lessons. 
Would it be possible for you to screenshot and give me an example of which videos you're referring to?

**Comment by kmathews1** [comment]
See an example attached. You will notice that it's not only showing a link to the video but an image of the video. Please let me know if you need more clarifications.
![video sample](https://user-images.githubusercontent.com/56735229/75779540-cea13300-5d27-11ea-9e48-f37a63c86905.jpg)
![video sample1](https://user-images.githubusercontent.com/56735229/75779742-29d32580-5d28-11ea-93d3-6aae9373820c.jpg)

**Comment by faitht1023** [comment]
@kmathews1 I've done this with all video links except the one Vimeo link in Activity 1.1 in U1 of NURS 520. Sharing is currently not enabled on the Vimeo video and needs to be in order for it to be embedded in Moodle. Please let me know if there is anything else you would like edited.
