### ISSUE TITLE
LDRS 662 Assignment pages

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#256]
## URL
https://learn.twu.ca/course/view.php?id=8931&section=11
### Instructions
Could we create pages in Github for the different assignments?  (Currently we have our old style (table of pdf links)

Ideally I'd like the navigation menu on the left linking to the different assignments, but we can create tabs in Moodle to link to the pages as well. (See [LDRS 663](https://learn.twu.ca/course/view.php?id=8958&section=11) navigation pane.

Here are the Assignments:
[3-CulturallyInclusiveLearningCommunity.docx](https://github.com/TWUOnline/bug-tracking/files/4294702/3-CulturallyInclusiveLearningCommunity.docx)
[4-PersonalizedLearningPlan.docx](https://github.com/TWUOnline/bug-tracking/files/4294703/4-PersonalizedLearningPlan.docx)
[5-Culturally-Inclusive-Lesson-Plan.docx](https://github.com/TWUOnline/bug-tracking/files/4294704/5-Culturally-Inclusive-Lesson-Plan.docx)
[1-CulturallyInclusiveTeachingandLearning–Interview.docx](https://github.com/TWUOnline/bug-tracking/files/4294705/1-CulturallyInclusiveTeachingandLearning.Interview.docx)
[2-CulturallyInclusiveLearningSpaces–Observation.docx](https://github.com/TWUOnline/bug-tracking/files/4294706/2-CulturallyInclusiveLearningSpaces.Observation.docx)
[Discussions.docx](https://github.com/TWUOnline/bug-tracking/files/4294708/Discussions.docx)

Here are the grading Rubrics:
[RUBRICCulturallyInclusiveLessonPlan.docx](https://github.com/TWUOnline/bug-tracking/files/4294712/RUBRICCulturallyInclusiveLessonPlan.docx)
[RUBRICCulturallyInclusiveTeachingandLearning–Interview.docx](https://github.com/TWUOnline/bug-tracking/files/4294713/RUBRICCulturallyInclusiveTeachingandLearning.Interview.docx)
[RUBRICPersonalizedLearningPlan.docx](https://github.com/TWUOnline/bug-tracking/files/4294715/RUBRICPersonalizedLearningPlan.docx)

**Comment by rezakh66** [comment]
@kmarjanovic Hi, which assignment's rubric is discussion.docx for?

**Comment by kmarjanovic** [comment]
Hi @rezakh66 ,
The discussions rubric will go in a separate tab (https://learn.twu.ca/course/view.php?id=8931&section=12)
I don't think there's a page for it yet.

**Comment by kmarjanovic** [comment]
Hi @rezakh66  & @cmadland 

This is a situation in which I think we need to branch the changes, or especially ask for ID review. 
Students are seeing the new changes right now and are seeing errors (see [bug report](https://github.com/TWUOnline/bug-tracking/issues/272)

Can we discuss this process?

**Comment by kmarjanovic** [comment]
Fixed now - lots of errors (all links broken, tables needed formatting, etc.)

All assignments have 2 folders - very confusing as it's unclear which one to edit.  Assignment 2: Observation - is the only one that's not in the numbered folders.  We should fix this so we know for future edits.

This rubric I had lots of trouble with.  If you can have a clearer look, please help.

**Comment by faitht1023** [comment]
@kmarjanovic I've sorted out the assignment folders and deleted the extra ones. I also formatted the rubrics in markdown. Please let me know if they need to be fixed still!

**Comment by kmarjanovic** [comment]
@faitht1023 
Perfect! Thank you!!
