### ISSUE TITLE
LDRS 500 branching for FAR

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#258]
### Course
LDRS 500 FAR MASTER
### URL
https://learn.twu.ca/course/view.php?id=10719&section=0
### Instructions
In the "Learning Activities" & "Assessment" sections of each unit, there are instructions for FAR Centre students and for online students.
Could we make an OL and FAR version in Github? Make sure the FAR branch is seen in this moodle shell - and perhaps make another LDRS 500 OL Master to show that version?

**Comment by kmarjanovic** [comment]
@cmadland any update on branching?
We need this course for a 6 week offering in August (& likely online 12 & FAR in the fall).

**Comment by cmadland** [comment]
Still working on this. To confirm, 591 is the only course where we use the tags right now right? @kmarjanovic 

Should be done this morning...

**Comment by kmarjanovic** [comment]
Yes that's right.  Although I think it's only been tested with the OL version.
Thanks Colin!
