### ISSUE TITLE
file not found error 404

### ISSUE THREAD

**Issue by rezakh66** [TWUOnline/bug-tracking#26]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 MCOM 281
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 there are 3 broken links 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=10713&section=2
2. Unit #  2       Topic #  5       Activity#  2.7
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
Please replace with
[Plagiarism, Eh? How to recognize it and get it out of your life](https://vimeo.com/163566887/bece097c99)

I may add more later.
Thanks!

**Comment by rezakh66** [comment]
Hi,
replaced
