### ISSUE TITLE
PMPP 201 - checkmark issue & alert review

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#261]
### URL
https://learn.twu.ca/course/view.php?id=8951&section=5
### Instructions
Once the checkmark issue is solved, we'll need to look at all of the alerts in this course again.

For example, U5 FAR Centre Activity 5.3.1: Family Vacation Actual Costs - the formatting doesn't come across as nicely as it does in the Word doc.  We have to make sure it's more readable.

![image](https://user-images.githubusercontent.com/35148983/76028693-59cd2500-5ef0-11ea-94cf-597690a7d4d5.png)

**Comment by kmarjanovic** [comment]
I hate to be picky...but are there other options?  
I tried adding numbers, but the checkmarks are still there.  
![image](https://user-images.githubusercontent.com/35148983/76105792-e6c8ba80-5f92-11ea-9783-16fdde8f71d7.png)

One related question...can the title of the Click to Open features be a heading level #3, or at least bolded?  I tried and it didn't work.

**Comment by cmadland** [comment]
The text in the 'details' title can be bold if it is removed from the toggle. The data looks better as a table...but I have a sneaking suspicion that Matt wants it NOT in a table...

![image](https://user-images.githubusercontent.com/12282929/76125273-4635c300-5fb1-11ea-8ccd-c52c0391f111.png)

Thoughts?

**Comment by kmarjanovic** [comment]
I love the table!  Let's do that!!!

**Comment by faitht1023** [comment]
@kmarjanovic is there anything else in PMPP 201 that needs formatting/reformatting?

**Comment by kmarjanovic** [comment]
Hi @faitht1023 ,
The checkmarks are still an issue in this course.  Once that's resolved, I'll need to look back at all of the alerts to see the formatting.

**Comment by faitht1023** [comment]
@kmarjanovic would you like the checkmarks removed?

**Comment by kmarjanovic** [comment]
@faitht1023 
Yes please, Faith!  That activity looks much better with checkmarks removed.

**Comment by faitht1023** [comment]
@kmarjanovic I've just gone through the whole course and formatted it to the best of my ability. Please let me know if anything else should be fixed.
One thing I noticed is that at bottom of the "Assessment" section in each unit, there is an extra "Schedule" button which does not work. I believe that this needs to be fixed in Grav, @cmadland ?

**Comment by kmarjanovic** [comment]
Hi @faitht1023 & @cmadland 
I'll have a look through the course tonight.  Thanks so much for your help!

For the assessment button, it's the same issue we've had in other courses.  The alerts within the unit assessment folder need to be moved to the unit folder.  Then the plugin references (../../ etc.) have to change.
See this issue: [https://github.com/TWUOnline/bug-tracking/issues/16#issuecomment-567284398](this https://github.com/TWUOnline/bug-tracking/issues/16#issuecomment-567284398)

**Comment by faitht1023** [comment]
@kmarjanovic fixed, the extra "schedule" buttons are gone now.

**Comment by kmarjanovic** [comment]
@faitht1023 
Thank you!!
