### ISSUE TITLE
PMPP 201 Editing tasks (for Jessica?)

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#262]
### URL
https://learn.twu.ca/course/view.php?id=8951&section=1
### Instructions
There are a lot of missing periods or spaces in the Activity Checklists. (e.g. Read Fundamentals of PM (FPM), chapters 12-14.(50 minutes))
Please check consistency throughout course (in Overview section of each unit).

**Comment by faitht1023** [comment]
@kmarjanovic I've gone through all the overviews + schedule alerts and formatted it with the style <period><space> (n minutes). As well, I've edited the spacing of the overviews to all be the same to the best of my ability. Please let me know if this needs to be further edited! Thanks.

**Comment by kmarjanovic** [comment]
@faitht1023 
Thanks so much for your help!
