### ISSUE TITLE
Research Ethics Form Link: Not Responsive.

### ISSUE THREAD

**Issue by emmanuelD-AFK** [TWUOnline/bug-tracking#266]
**Which course contains the bug?**  
LDRS 662 A Culturally Responsive Comm (SP 2020)

**Describe the error and/or your suggestion**  
The link to access the Research Ethics Form link is not responsive 
 
**Location of the bug**  
1. URL:  https://learn.twu.ca/course/view.php?id=13590&section=1
2. Unit # 1         Topic # Assessment 1          Activity#  Part 1: 3 
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
@emmanuelD-AFK 
Thanks for catching this!  I've added the info, but Cathy may send more clarification this week.
