### ISSUE TITLE
Remove Due Dates from Course Introduction in LDRS 662A Culturally Responsive Comm (SP 2020)

### ISSUE THREAD

**Issue by cpenfoldnavarro** [TWUOnline/bug-tracking#269]
**Which course contains the bug?**  
- LDRS 662A Culturally Responsive Comm (SP 2020)
https://learn.twu.ca/course/view.php?id=13590&section=0
 
 
**Describe the error and/or your suggestion**  
Due dates have changed. Please delete the due dates listed here in the table (they are published elsewhere in Moodle).
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=13590&section=0
2.  Course Introduction 

**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
Due dates deleted :)

**Comment by cpenfoldnavarro** [comment]
Merci!

CATHARINE PENFOLD NAVARRO, PhD
Part-Time Instructor, MA Leadership | TWU GLOBAL
Trinity Western University | e. c.penfoldnavarro@twu.ca<mailto:c.penfoldnavarro@twu.ca>

twu.ca<http://www.twu.ca/>

[cid:image001.png@01D56D6B.9FBB05E0]
