### ISSUE TITLE
confusing sentence

### ISSUE THREAD

**Issue by rezakh66** [TWUOnline/bug-tracking#27]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 
 MCOM 281
**Describe the error and/or your suggestion**  

  it's written that"You should view the following videos as you prepare for this speech." and there are two links but only the second one is video and first one is like an article. its better to split them.
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=10713&section=3
2. Unit #    3     Topic #    1     Activity#  3.1
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
Please replace with
You should view the following resources as you prepare for this speech.

Thank you!

**Comment by rezakh66** [comment]
Replaced.
Thanks
