### ISSUE TITLE
LDRS 662 A - Culturally Responsive Comm (SP 2020) - 'Assignments'

### ISSUE THREAD

**Issue by danielsplett** [TWUOnline/bug-tracking#272]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 
LDRS 662 A - Culturally Responsive Comm (SP 2020) - 'Assignments'
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 
There are 6 graded assignments listed and they have various percentages.  But for the last 3 assignment numbers, these last 3 do NOT coincide with their instructions links to the left, which also do not necessarily coincide with the drop-boxes on the bottom!  And, within some of the documents the percentages in the instructions are different than what is listed on the 'Assignments' page!  

This is confusing and should be corrected, please!
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:

https://learn.twu.ca/course/view.php?id=13590

'Assignments' tab - the last 3 of the 6 listed do NOT coincide with the tabs to the left of the, which also do not coincide with the drop boxes at the bottom.  This is confusing and should be corrected - "Mist in the pulpit, fog in the pews!" or modified for teaching/facilitating: "Mist at the whiteboard, fog at the desks!" - DkS
1. URL:  
2. Unit #         Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
@danielsplett 
Thanks for letting us know, Daniel!
All should be fixed now.

**Comment by danielsplett** [comment]
Hello Kelly & Bug exterminators:  😁

Thank you very much for attending to this so quickly, no doubt a fairly easy quick fix.

It's just SO much better for students, especially when they're ESL, if everything is laid out in an orderly manner.

I struggled for some time figuring out what was what on that page. So, maybe others would as well?

Thanks and God bless,

DkS



"The Big 'C' in life is Communication!"

~ Daniel k SPLETT ~


________________________________

**Comment by kmarjanovic** [comment]
Thanks Daniel!
Yes, we definitely want to have everything in order and working before students see the course.
Thanks for your patience as we made these last minute tweaks!
Kelly
