### ISSUE TITLE
Nurs520_L3_Production

### ISSUE THREAD

**Issue by kmathews1** [TWUOnline/bug-tracking#273]
### Nurs520_Lesson_3
[NURS_520_Lesson 3 working_March 30.docx](https://github.com/TWUOnline/bug-tracking/files/4404319/NURS_520_Lesson.3.working_March.30.docx)
[Lesson_3_Blank_step_1-concept_definition_and_inclusion_exclusion.docx](https://github.com/TWUOnline/bug-tracking/files/4404336/Lesson_3_Blank_step_1-concept_definition_and_inclusion_exclusion.docx)
[Lesson_3_Example_step_1-concept_definition_and_inclusion_exclusion.docx](https://github.com/TWUOnline/bug-tracking/files/4404337/Lesson_3_Example_step_1-concept_definition_and_inclusion_exclusion.docx)
[Lesson_3_Forum_Rubric.docx](https://github.com/TWUOnline/bug-tracking/files/4404338/Lesson_3_Forum_Rubric.docx)

### Instructions
- Could we have an ATA put Unit 3 in GitHub this week? There are some attachments which I have included as well.

**Comment by Raulmelara** [comment]
uploaded unit 3 with attachments

**Comment by kmathews1** [comment]
@Raulmelara  @cmadland  Thanks for adding lesson 3. There are a couple of formatting issues:
1. Figure 1 not displayed.
2. Please add activity checklist to alert.
3. The whole of lesson 1 is not displayed.
4. Attachments are not available.
5. No left-side navigation menu.

Thanks for your help.

**Comment by Raulmelara** [comment]
Added attachments, added activity checklist to alert. Navigation menu now visible as well as lesson 1
