### ISSUE TITLE
Nurs520 Lesson 1 Production

### ISSUE THREAD

**Issue by kmathews1** [TWUOnline/bug-tracking#274]
### Instructions
- Can you insert a link in lesson 1 under the Melnyk & Fineout-Overholt resource citation with this photocopy (Chapter 1_update)?

[Chapter_1_update.pdf](https://github.com/TWUOnline/bug-tracking/files/4405766/Chapter_1_update.pdf)

**Comment by cmadland** [comment]
Is there a library link for this?

**Comment by kmathews1** [comment]
The students will buy a textbook but Sarah said they can't get the book in time for the start of the course.
