### ISSUE TITLE
Nurs520 Lesson 2_Production

### ISSUE THREAD

**Issue by kmathews1** [TWUOnline/bug-tracking#275]
### Instructions
- Please add the attached lesson 2 to Github. 
[Nurs520_Lesson_2_March_30_Working_systematic_reviews.docx](https://github.com/TWUOnline/bug-tracking/files/4406007/Nurs520_Lesson_2_March_30_Working_systematic_reviews.docx)

- Please link the lessons to the Moodle shell for Nurs520.

**Comment by cmadland** [comment]
Ok, I added this as unit 2. Is Sarah using 'Lesson' rather than 'unit'?

**Comment by cmadland** [comment]
@rezakh66 @faitht1023 or @raulmelara would you please clean up the MD and move activities to the alerts?

**Comment by Raulmelara** [comment]
@cmadland I moved the activities to the alerts

**Comment by kmathews1** [comment]
Yes, Sarah is using lesson instead of unit.
