### ISSUE TITLE
Youtube Plugin Not working

### ISSUE THREAD

**Issue by dgaudet48** [TWUOnline/bug-tracking#276]
**Which course contains the bug?**  
- LDRS 220 FAR Master
 
 
**Describe the error and/or your suggestion**  
The Youtube plugin is not displaying the video on the Moodle course page
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://github.com/TWUOnline/ba-lead/blob/master/pages/02.ldrs220/10.U4/03.topic-2/section.md
2. Unit #    4     Topic #   2      Activity: The first video - second one works fine. 
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
I had this issue as well with PMPP 201. See https://github.com/TWUOnline/bug-tracking/issues/267
The solution was to delete the time hash in the url (e.g. &t=53s…including the ampersand)

**Comment by dgaudet48** [comment]
Perfect 

Seems to be working now

Thanks!
