### ISSUE TITLE
Presentation Not Working

### ISSUE THREAD

**Issue by dgaudet48** [TWUOnline/bug-tracking#277]
**Which course contains the bug?**  
- LDRS 220 FAR Master
 
**Describe the error and/or your suggestion**  
Presentation of slides will not display - keep getting an error message no matter how many times I reformat it. 
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://github.com/TWUOnline/ba-lead/blob/master/pages/02.ldrs220/15.U9/02.topic-1/section.md
2. Unit #  9       Topic #  1       Activity#  
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
I've added this to Issue Tracking Project and High Priority.
@cmadland do the ATA's track bug reports too, or should we always add it to a project?
