### ISSUE TITLE
LDRS 662 Learning Activity 4.3

### ISSUE THREAD

**Issue by cpenfoldnavarro** [TWUOnline/bug-tracking#279]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
LDRS 662 A SPRING 2020
 
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
One of the links is broken. Please replace:
Cross, T.L. (2001). Cultural competence continuum.
With:
Cultural Competence Continuum: https://www.eri-wi.org/download/conference/2013-conference/20_h_WhyDoesntEveryone_chart.pdf
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=13590&section=4
2. Unit #  4       Topic #   Overview      Activity# 4.3  
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
@cpenfoldnavarro 
Hi Cathy, 
I've made those edits.  Just want to double check that no rewording is required for the rest. as in the document it says - Adapted from Terry L. Cross, et., at., 1989), Coleman/Pellitteri 2000 & Updated 2/4/13

Now in Activity 4.3
Read: Cross, T.L. (2001). [Cultural competence continuum - Characteristics](https://www.eri-wi.org/download/conference/2013-conference/20_h_WhyDoesntEveryone_chart.pdf).

Focus on the discussion of the “Cultural Competence Continuum” – from “Cultural Destructiveness” to “Advanced Cultural Competence” (Cross, 2001).

Considering the Cross (2001) continuum, where do you think you fall? Considering your professional context (or other aspects of your life), how would you evaluate those organizations on the continuum? Of the five approaches outlined by Choudhury (2017), which most closely aligns with the approach of the organization?

**Comment by cpenfoldnavarro** [comment]
Thanks, Kelly.

No other adjustment is needed, as that resources provides an overview of the Cross Continuum.
Cathy

CATHARINE PENFOLD NAVARRO, PhD
Part-Time Instructor, MA Leadership | TWU GLOBAL
Trinity Western University | e. c.penfoldnavarro@twu.ca<mailto:c.penfoldnavarro@twu.ca>

twu.ca<http://www.twu.ca/>

[cid:image001.png@01D56D6B.9FBB05E0]

**Comment by kmarjanovic** [comment]
Okay perfect. Thanks!
