### ISSUE TITLE
duplicated link 

### ISSUE THREAD

**Issue by rezakh66** [TWUOnline/bug-tracking#28]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=10713&section=4
2. Unit #  4       Topic #  1       Activity# 4.1 
 
**Optional: Screenshots**  
there are two links both to the same video. i think the first one should be changed.

**Comment by kmarjanovic** [comment]
Please correct the following:
- remove hyperlink from title
- remove numbers 1 and 2

**Comment by rezakh66** [comment]
Done
