### ISSUE TITLE
LDRS 300 Review / Edit

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#281]
### URL
https://learn.twu.ca/course/view.php?id=10828&section=0

http://far.twu.ca/ba-lead/ldrs300/u1/overview

### Instructions
I've noticed lots of editing mistakes/glitches that didn't seem to be there in the fall (or I missed it!).

Jessica, could you have a look and edit things?
e.g. Unit 6 activity checklist, Unit 5 topic 1 plugin isn't working, etc.
Resources section in overview - later units use icons (:fa-film:) - all should

**Comment by rezakh66** [comment]
@kmarjanovic Hi, I have made all unit's assessment section consistent using primary and secondary alerts according to unit 1. please see how does it look like

**Comment by kmarjanovic** [comment]
Thanks @rezakh66 @JessD9 
The last things to change are the icons in the Resources section of the Overview.  Please add the icons for Units 1-4; 8-10 to make it consistent.
