### ISSUE TITLE
LDRS 662 A SP 20: Unit 5 Activity 5.3

### ISSUE THREAD

**Issue by cpenfoldnavarro** [TWUOnline/bug-tracking#282]
**Which course contains the bug?**  
LDRS 662 A SP 20
 
 **Describe the error and/or your suggestion**  
Add this link to the Peggy McIntosh article.
Learning Activity 5.3: Read the following article and complete the checklist: McIntosh, P. (1989). White privilege: Unpacking the invisible knapsack. Peace and Freedom Magazine. Women’s International League for Peace and Freedom: Philadelphia, PA, (pp. 10-12).
--

LINK: https://www.racialequitytools.org/resourcefiles/mcintosh.pdf
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=13590&section=5
2. Unit #    5     Topic # Overview        Activity#  5.3
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
@cmadland I changed this in Atom, but it's not showing up.  Does Grav need to be refreshed?
