### ISSUE TITLE
Nurs520_L2_Production

### ISSUE THREAD

**Issue by kmathews1** [TWUOnline/bug-tracking#283]
### Instructions
- Left-side navigation menu not showing

**Comment by kmathews1** [comment]
@cmadland @rezakh66 Please add lesson 2 to Moodle. Can you explain how to generate the iFrame?

**Comment by cmadland** [comment]
Hi @kmathews1 the way I generate the iFrame is to copy it from another tab in the course.

Here is the structure...
`<p><iframe scrolling="yes" style="border: 0px #ffffff none;" src="https://far.twu.ca/arts/phil210/syllabus/chromeless:true/hidepagetitle:true" allowfullscreen="allowfullscreen" width="100%" height="1000"></iframe></p>`

Then you need to update the URL for the individual course section.

**Comment by cmadland** [comment]
I added lesson 2 to moodle, bu tthe tab is still hidden.
