### ISSUE TITLE
Remove HREB from LDRS 662 Assignment 1

### ISSUE THREAD

**Issue by cpenfoldnavarro** [TWUOnline/bug-tracking#284]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 LDRS 662 A SPRING 2020
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.

Delete this:
3. Complete the Research Ethics Form. See more information on Research Ethics, including Class Project Template Documents, at https://www.twu.ca/research/research-services/research-ethics/approval-forms.

Replace this:
Upload this assignment to Moodle, including your answers to the questions, the name and interview details (time/place) for your interview, as well as the Research Ethics form.

With this:
Upload this assignment to Moodle, including your answers to the questions, the name and interview details (time/place) for your interview.
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=13590&section=11
2. Unit # Assignment 2        Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by rezakh66** [comment]
done
