### ISSUE TITLE
Correct Assignment Values in LDRS 662

### ISSUE THREAD

**Issue by cpenfoldnavarro** [TWUOnline/bug-tracking#285]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
LDRS 662 OL SP 2020
 
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
In several of the assignments, the points value listed in the PDF of the assignment is incorrect. These need to be adjusted to reflect the correct points value (listed in Due Dates and Assignments tabs). 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=13590&section=11
2. Unit # Assignments       Topic #         Activity# 
ASSIGNMENT 2: PDF should list point values as 10%
This assignment is due at the end of Unit 2. See pdf of assignment details here.

ASSIGNMENT 3: PDF should list point value as 15%
See pdf of assignment details here.

ASSIGNMENT 4: PDF should read as Assignment 4: Personalized Learning Plan (it currently says Assignment 5)

Assignment 5: PDF should read "Assignment 5" (it currently just says "assignment"
See pdf of assignment details here.

 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
@cpenfoldnavarro  is it okay if we just delete the pdfs?  I've deleted them for now but can put them back (with corrections).

@Raulmelara could you please fix the rubric in Assignment 3 (there's no top row that describes the points). For Assignment 4, the top row isn't aligned with the correct column (shift to right).

**Comment by Raulmelara** [comment]
@kmarjanovic I fixed the rubrics. Let me know if I missed anything.

**Comment by kmarjanovic** [comment]
Thank you @Raulmelara !!
