### ISSUE TITLE
MCOM 221 - units 

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#286]
### Instructions
!! Note this course goes live April 28!!!

- [x] Please format unit 1 (activity checklist alert, activity alerts, etc.)
- [x] add units 2-4 and format
- [x] embed url (when working) in Moodle course: [MCOM 221 - Digital Filmmaking (FAR Master)](https://learn.twu.ca/course/view.php?id=10829)

I don't think we need the book now (see [comment](https://github.com/TWUOnline/bug-tracking/issues/270))

**Comment by rezakh66** [comment]
@kmarjanovic Hi, I have reformatted unit 1.However changes are not showing up yet. the cache may need to be cleared up? I don't have SAMC Grav access to do that. And please send me Unit2-4 docx files .

**Comment by rezakh66** [comment]
Also, please note that I have added activity 1.5 to the checklist and alerts.  it was not there previously. let me know if you don't want that.

**Comment by kmarjanovic** [comment]
Hi Reza,
Thanks so much for your help!
Here are the other units:
[MCOM-221_Unit 4-Motion_Oct16_KM.docx](https://github.com/TWUOnline/bug-tracking/files/4467550/MCOM-221_Unit.4-Motion_Oct16_KM.docx)
[Unit-3-Visual-Composition_Oct16_KM.docx](https://github.com/TWUOnline/bug-tracking/files/4467553/Unit-3-Visual-Composition_Oct16_KM.docx)
[MCOM-221-Unit-2-Process_Aug 19_KM.docx](https://github.com/TWUOnline/bug-tracking/files/4467554/MCOM-221-Unit-2-Process_Aug.19_KM.docx)

**Comment by kmarjanovic** [comment]
@cmadland could you email Reza & I the Grav login info so we can clear the cache?
(Why is this happening in recent sites?)

**Comment by faitht1023** [comment]
@kmarjanovic I've just added U3 and U4 to Moodle, please let me know if there are issues with formatting. The activity checklist for U4 schedule is missing some details for the last two activities/assignments, would you know where I can find that information?

**Comment by rezakh66** [comment]
Unit 2 is added as well.

**Comment by kmarjanovic** [comment]
@rezakh66  @faitht1023  
Just in case you haven't put Units 3-4 in GitHub, here are some updates from Ned (still has comments and tracked changes in case you need to compare versions).  Please also add Unit 5.

@JessD9 could you revise Units 1-2 based on the documents below?  Let us know if you have any questions!

[MCOM-221-Unit3-Visual-Composition-13April.docx](https://github.com/TWUOnline/bug-tracking/files/4489044/MCOM-221-Unit3-Visual-Composition-13April.docx)
[MCOM-221-Unit2-Changes-13-April.docx](https://github.com/TWUOnline/bug-tracking/files/4489045/MCOM-221-Unit2-Changes-13-April.docx)
[MCOM-221-Unit1-Intro-9Aprl.docx](https://github.com/TWUOnline/bug-tracking/files/4489046/MCOM-221-Unit1-Intro-9Aprl.docx)
[MCOM-221-Unit4-Motion-14-April.docx](https://github.com/TWUOnline/bug-tracking/files/4489047/MCOM-221-Unit4-Motion-14-April.docx)
[MCOM-221-Unit5-Film-Grammar-14April.docx](https://github.com/TWUOnline/bug-tracking/files/4489048/MCOM-221-Unit5-Film-Grammar-14April.docx)

**Comment by JessD9** [comment]
Sure, no problem Kelly.

Besides grammar/syntax, is their anything specific you wanted me to revise
or add?

-Jessica

**Comment by rezakh66** [comment]
@kmarjanovic Hi, I have uploaded unit 5.

**Comment by kmarjanovic** [comment]
@JessD9 - just checking that the tracked changes Ned included in the revised documents are now in the course.  And yes, definitely grammar/syntax.
If there are other design questions, questions for me or the instructor, feel free to add those in (you can use 2 exclamation marks to make it stand out in red). 
e.g.
!! Question for Kelly:
Or email works too!

Please feel free to go through the rest of the units as well if you have time.

**Comment by kmarjanovic** [comment]
@JessD9 @rezakh66 
Just going through the first units.
Could you check that any links are hyperlinked - and working?
eg. Activity 1.2
Durham University’s Glossary of Film Terms (some of which are unique to UK English and industry) https://community.dur.ac.uk/m.p.thompson/filmterms.htm#V

should be 
[Durham University’s Glossary of Film Terms](https://community.dur.ac.uk/m.p.thompson/filmterms.htm) (some of which are unique to UK English and industry)

**Comment by kmarjanovic** [comment]
Here is Unit 6 to upload:
[MCOM-221-Unit6-Visual-Storytelling15April.docx](https://github.com/TWUOnline/bug-tracking/files/4490466/MCOM-221-Unit6-Visual-Storytelling15April.docx)

Thank you @rezakh66 !!

**Comment by kmarjanovic** [comment]
@faitht1023 thanks for catching that!  If the info isn't in the word files for the unit 4 activities, I'll check with the writer.

**Comment by rezakh66** [comment]
@kmarjanovic Hi, 
U6 is online now

**Comment by JessD9** [comment]
Here is Unit 1:

**Comment by kmarjanovic** [comment]
@rezakh66 Please add the last units:
[MCOM-221-Unit9-Making-Your-Short-Film-April-20_KM.docx](https://github.com/TWUOnline/bug-tracking/files/4505138/MCOM-221-Unit9-Making-Your-Short-Film-April-20_KM.docx)
[MCOM-221-Unit-7-Editing-and-Montage-April-20_KM.docx](https://github.com/TWUOnline/bug-tracking/files/4505139/MCOM-221-Unit-7-Editing-and-Montage-April-20_KM.docx)
[MCOM-221-Unit-8-Crating-Narrative-Short-FIlms-April-20_KM.docx](https://github.com/TWUOnline/bug-tracking/files/4505140/MCOM-221-Unit-8-Crating-Narrative-Short-FIlms-April-20_KM.docx)
[MCOM-221-Unit-10-Course-Summary-and-Celebration-APril-20_KM.docx](https://github.com/TWUOnline/bug-tracking/files/4505141/MCOM-221-Unit-10-Course-Summary-and-Celebration-APril-20_KM.docx)

@JessD9 there may be some editing needed in these units as well (unnecessary capitals, links need to be hyperlinked, title headings, etc.)

Thank you both!!

**Comment by kmarjanovic** [comment]
@JessD9 
Thanks so much for reviewing these units!  Are the changes now in GitHub as well? (no need to use Word documents once files are in GitHub).
For comments to me or the course writer, you can use an !! to make the comment stand out.  For changes that are minor (grammar) we don't need comments, but anything content related should be flagged for the instructor to review.
Let me know if you have further questions.

**Comment by rezakh66** [comment]
@kmarjanovic I have uploaded all the units. I think unit 9 needs to be changed a little bit. please look at  Topic 7, topic 9, and topic 9-2.

**Comment by kmarjanovic** [comment]
Thank you @rezakh66 !

We have a bunch of editing to do for this course, so this is a HUGE help!!  I'll have a look at Unit 9 tomorrow.
