### ISSUE TITLE
Gradebook Setup - FAR Courses

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#288]
### Instructions
For all FAR courses, I'd like to double check that the MASTER shells have the gradebook set up correctly.
- [ ] check percentages in gradebook match syllabus
- [ ] check the instructors can see the percentages, rather than the points total (see [instructions](http://create.twu.ca/help/moodle/faculty/grade-book/course-total-display)

**Comment by 345-Jay** [comment]
@kmarjanovic  @cmadland  There seems to be varied information with percentages for LDRS 300. The course information tab show a 15% percentage for the Case Study Paper: Saving Mr. Banks verses the 20% percentage on the Assessment tab. Which percentage should it be?

**Comment by kmarjanovic** [comment]
Hi @345-Jay 
The instructor has made some changes to the assessments, so I'll just double check and then make those changes.
Thanks for checking!!

**Comment by kmarjanovic** [comment]
@345-Jay 
Case Study In Leadership: Saving Mr. Banks should be 15% of total grade.
Could you make that change?
