### ISSUE TITLE
Rubric Setup - LDRS 662 & 664

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#289]
### Instructions
For LDRS 662 & 664 please add the rubric using the Moodle tool.

@cmadland we should check for other rubric plugins & discuss whether we should set up for all FAR courses.

If rubrics can easily be transferred, then add to master and copy to current spring course:

| [LDRS 664 - MASTER](https://learn.twu.ca/course/view.php?id=8884)                                                                             | [LDRS 664 A (SP20)](https://learn.twu.ca/course/view.php?id=13591)  |
|-----------------------------------------------------------------------------------------------|---------------------------------------------------------------------|
| [LDRS 662: Culturally Responsive Comm (MASTER)](https://learn.twu.ca/course/view.php?id=8931) | [LDRS 662 A (SP20)](https://learn.twu.ca/course/view.php?id=13590)  |

**Comment by faitht1023** [comment]
@kmarjanovic are you referring to the rubrics in the assignment tabs? How would you like those to be formatted?

**Comment by kmarjanovic** [comment]
Hi @faitht1023 ,
The instructor would like to use the tools in Moodle.  Could you add the rubric info for assignments to the rubric tool in Moodle?

**Comment by faitht1023** [comment]
Hi @kmarjanovic, I'm not too familiar with the rubric tool in Moodle, is it under gradebook setup? I am looking into it further!

**Comment by kmarjanovic** [comment]
Hi @faitht1023 
Try this [link](https://docs.moodle.org/38/en/Rubrics)
It's been a while since I've set one up too.  Perhaps try first in the [LDRS 664 - MASTER](https://learn.twu.ca/course/modedit.php?update=266361&return=1) course and we can test it out there.

You go to Assignments, click on the dropbox, and change settings from there.

**Comment by faitht1023** [comment]
@kmarjanovic I've figured it out! I just did one for Assignment 1: Identity as a Facilitator/Teacher in LDRS 664 Master and currently saved it as a draft, please let me know if it is the appropriate format and I can do it for the rest of the rubrics. I used the points system from the provided rubric (0, 2, 3, 4 points respectively for F, C, B, A). Thank you!

**Comment by faitht1023** [comment]
@kmarjanovic I added Assignment 2: Company Website Analysis Rubric in LDRS 664 as a draft. Is the rubric for Assignment 3: Platform Paper the same as Assignment 2's rubric? On Moodle, the rubric for Assignment 3 is titled "Company Website Analysis Rubric".

**Comment by kmarjanovic** [comment]
Hi @faitht1023 
The rubrics for the assignments are different.  Let me just check with Cathy to see if the rubric created works for her.  If so, we can add the others.
Thanks for your help!

**Comment by kmarjanovic** [comment]
closing this issue as we'll change some rubric formatting in our courses.
