### ISSUE TITLE
LDRS 664 Unit 5 discussion instructions

### ISSUE THREAD

**Issue by cpenfoldnavarro** [TWUOnline/bug-tracking#290]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 LDRS 664 A SP20
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 There is an error in the Unit 5 Discussion instructions that should be updated.
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=13591&section=5
2. Unit #    5     Topic #  Assessment       Activity# Unit 5 Discussion  
 
REPLACE:
After you have completed the interview, reflect on your classmate’s responses and your own reading. Synthesizing your learning, prepare a 250-word discussion post, identifying at least three strategies you can use to help learners develop questions with each other. Be sure to reference the other learner for her/his original ideas.
WITH:
After you have completed the interview, prepare a 250-word blog post, identifying at least three strategies you can use to engage students in collaborative learning as well as strategies you can use to support connections between students in online learning environments. Be sure to reference the other learner for her/his original ideas. 

**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
Done! :)
