### ISSUE TITLE
Reminder for ATAs

### ISSUE THREAD

**Issue by cmadland** [TWUOnline/bug-tracking#291]
When you are working on an issue, please move it to the 'In Progress' column in the project. If you can't resolve it, please make sure you move it back to its original column (High Priority, etc). If you do resolve it, then either close the issue, or if it needs review, move it to the 'Review' column and mention @kmarjanovic in the comment to alert her to the update.

Thanks!

Colin

**Comment by meher-ahmed** [comment]
@cmadland @kmarjanovic can we close this issue?
