### ISSUE TITLE
LDRS 667 upload units

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#292]
### URL
Prework: https://learn.twu.ca/course/view.php?id=13600&section=1
Unit 1: https://learn.twu.ca/course/view.php?id=13600&section=1
### Instructions

Please upload units to GitHub:
[LDRS667-Unit-1-Reflective-Practice_April20_KM.docx](https://github.com/TWUOnline/bug-tracking/files/4504948/LDRS667-Unit-1-Reflective-Practice_April20_KM.docx)
[LDRS667-Unit-0-PreWork-Practicum-Proposal_April20_KM.docx](https://github.com/TWUOnline/bug-tracking/files/4504950/LDRS667-Unit-0-PreWork-Practicum-Proposal_April20_KM.docx)

**Comment by Raulmelara** [comment]
@kmarjanovic Units uploaded.

**Comment by kmarjanovic** [comment]
Thank you @Raulmelara !!
