### ISSUE TITLE
Latest Announcement block not showing

### ISSUE THREAD

**Issue by toddfmartin** [TWUOnline/bug-tracking#294]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
###  ****SOCI 101 A6 - Introduction to Sociology (SU 2020)****

 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 Latest Announcement block not showing
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=13489&section=0
2. Unit #   Introductory Page     Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
@toddfmartin 
Hi Todd,
I see one Announcement at the bottom of your course intro page.  Is there another one that you're looking for?
