### ISSUE TITLE
Content not accessible from the Hyperlink.

### ISSUE THREAD

**Issue by emmanuelD-AFK** [TWUOnline/bug-tracking#296]
**LDRS 664A (SP 2020) 
 
**Describe the error and/or your suggestion**  
The video is not accessible from the hyperlink provided
 
 
* **  
1. URL:  https://learn.twu.ca/course/view.php?id=13591&section=7
2. Unit #7         Topic # 2        Activity#  7.4
 
**Optional: Screenshots**  
<img width="512" alt="Screen Shot 2020-04-27 at 8 42 33 AM" src="https://user-images.githubusercontent.com/59032072/80393608-93256f80-8865-11ea-8265-fe4255c07aa3.png">

**Comment by kmarjanovic** [comment]
Thanks @emmanuelD-AFK !

The link is fixed (should be [this](https://www.youtube.com/watch?v=1vIPrR_clEg)).

@cmadland does this need a Grav sync, as it's not showing up online yet.

**Comment by kmarjanovic** [comment]
Shows up now.  Thanks!
