### ISSUE TITLE
LDRS 410 - pwpt

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#297]
### URL
https://learn.twu.ca/course/view.php?id=10720&section=2
### Instructions
Could you please add the attached pwpt to a presentations plugin?
[Change-the-way-you-Persuade-PPP.pptx](https://github.com/TWUOnline/bug-tracking/files/4566152/Change-the-way-you-Persuade-PPP.pptx)

It should then go in an alert as a new Activity

#### Activity 2.5: Review and Reflect
The following slide presentation describes the five types of decision makers and how they are persuaded in making decisions.  As you review these think of people in your own family or leaders who fit the descriptions listed.  Which type are you?

[plugin:presentation](...)

Please update the Activity Checklist in the Overview section as well

**Comment by cmadland** [comment]
Should this be activity 2.4 or 2.5? The schedule suggests maybe 2.4...or perhaps I'm late.

![image](https://user-images.githubusercontent.com/12282929/81604957-92bcc680-9385-11ea-9d10-55a97a82d332.png)

**Comment by kmarjanovic** [comment]
Ahh, I see the problem.
We recently added a new 2.1 - devotional Isee Topic 1)- so all the activity #s need to change.

**Comment by kmarjanovic** [comment]
Activity #s all matching now.
Thank you for your help with the slideshow!!
