### ISSUE TITLE
Add PDF of article in LDRS 662A Activity 3.1

### ISSUE THREAD

**Issue by cpenfoldnavarro** [TWUOnline/bug-tracking#298]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 LDRS 662(A) SP 20
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
In Activity Checklist, Activity 3.1, please include the PDF of the Chen and Lin article (attached)
This PDF should replace the current url listed there.
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL: https://learn.twu.ca/course/view.php?id=13590&section=3 
2. Unit #   3      Topic #   Activity Checklist      Activity#  3.1
[Chen and Lin 2016 Cultural Identities.pdf](https://github.com/TWUOnline/bug-tracking/files/4577225/Chen.and.Lin.2016.Cultural.Identities.pdf)

 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
Thanks Cathy!
I've added the pdf.  It may take a couple minutes for it to sync with the Moodle site.

**Comment by cpenfoldnavarro** [comment]
Thanks!

CATHARINE PENFOLD NAVARRO, PhD
Part-Time Instructor, MA Leadership | TWU GLOBAL
Trinity Western University | e. c.penfoldnavarro@twu.ca<mailto:c.penfoldnavarro@twu.ca>

twu.ca<http://www.twu.ca/>

[cid:image001.png@01D56D6B.9FBB05E0]
