### ISSUE TITLE
H5P Issue

### ISSUE THREAD

**Issue by cmadland** [TWUOnline/bug-tracking#299]
I've recently learned of an issue in H5P that we should start to consider.

@kmarjanovic @rezakh66 @dgaudet48 @kmathews1 

re: #250 

When a fill in the blank interactive is long and narrow (smaller screens), the words to choose from are at the bottom of the interaction, even if the correct spot for them is above the scroll. Clicking and dragging the word is problematic because it seems the h5p frame doesn't scroll automatically. This means it is impossible to put the word in the correct spot.

I don't have a specific example right now...

**Comment by kmarjanovic** [comment]
Yes, I flagged this last year.  [LDRS 303 H5P #89](https://github.com/TWUOnline/bug-tracking/issues/89)
I'd like to find a solution as this affects a couple of our courses.

**Comment by cmadland** [comment]
of course you did...sorry!

Will dig around.

**Comment by kmarjanovic** [comment]
No worries!!  
Actually, for 303, I had originally asked to alternate between using Fill in the Blanks and Flashcards ([Issue 80](https://github.com/TWUOnline/bug-tracking/issues/80)).
I'd still like to do that...just so little time!
Perhaps Jessica can dig through that course and check which H5P activities aren't working well - then we can switch formats?

**Comment by dgaudet48** [comment]
I actually had this issue with Psych 106 - I didn't think there was a solution so I just made the activities shorter...would be super helpful though if we could even make it side-by-side.

**Comment by JessD9** [comment]
@kmarjanovic On it!

**Comment by JessD9** [comment]
@cmadland @kmarjanovic Same scrolling issue for ldrs 303 Units 4,5,7,9,10 Drag& Drop ...not sure if this has already been suggested, but could we use a drop-down menu? 
[Advanced Fill in the Blanks](https://h5p.org/advanced-fill-the-blanks)

**Comment by kmarjanovic** [comment]
@JessD9 did you want to try to make one into the Advanced Fill in the Blanks? 
We could also use the Flashcards H5P.  It'd be nice to alternate between 2-3 types throughout the course for variety.
Do you have access to our H5P site in wordpress? https://create.twu.ca/h5p/wp-admin/admin.php?page=h5p

**Comment by JessD9** [comment]
@kmarjanovic yes I can try.
No, haven't been able to access WordPress (You attempted to access the "H5P Content for TWU" dashboard, but you do not currently have privileges on this site.)

**Comment by kmarjanovic** [comment]
@cmadland could you give Jessica access - and perhaps check if Dave has access as well?

**Comment by dgaudet48** [comment]
@cmadland I have access and I have been using it in my courses so all good over here

**Comment by kmathews1** [comment]
@cmadland I also need access to the "H5P Content for TWU" dashboard. I have been using the one available in Moodle.

**Comment by JessD9** [comment]
@kmarjanovic Just realized that rezakh66 commented on this in ldrs 410... Advanced Fill the Blanks does not exist in the version of WordPress we have.                        
https://github.com/TWUOnline/bug-tracking/issues/250

**Comment by kmarjanovic** [comment]
@cmadland can we update our WP to get access to all H5P?
In the meantime @JessD9 , perhaps let's try the flashcards for a couple of those problem lessons.

**Comment by kmarjanovic** [comment]
I think this was resolved.
