### ISSUE TITLE
WRTG 101 - Presentation Slides (M1:L3)

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#3]
**Which course contains the bug?**
- Course Code and section e.g. WRTG 101 FAR MASTER

**Describe the error or your suggestion**
Lesson 3 - Paraphrasing section.
Need to create a Presentation instead of pdf (5 Steps of Effective Paraphrasing)

**Comment by michaelamulder** [comment]
The Paraphrasing presentation is almost up on Moodle. I just need to make some changes to the font/theme. You can look at what it is so far on the presentation site.
