### ISSUE TITLE
MCOM 281 - Missing Link

### ISSUE THREAD

**Issue by faitht1023** [TWUOnline/bug-tracking#30]
**Which course contains the bug?**  
MCOM 281: Public Speaking (FAR Centre MASTER)
 
 
**Describe the error and/or your suggestion**  
Missing link.
 "Grading Criteria:
See the Journal guidelines for more details. [link to document]"
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=10713&section=10
2. Unit # 10     Topic # Assessment   Activity#  
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
Please link to the attached pdf
[MCOM_281_Journal_Guidelines.pdf](https://github.com/TWUOnline/bug-tracking/files/3692405/MCOM_281_Journal_Guidelines.pdf)
