### ISSUE TITLE
Broken link in LDRS 627 OL SU20

### ISSUE THREAD

**Issue by AmberZacharias91** [TWUOnline/bug-tracking#300]
**Which course contains the bug?**  
- LDRS 627 OL SU20
 
 
**Describe the error and/or your suggestion**  
There is a broken link in Unit 3-Topic 3, Activity 3.4 Item 2: Read this article from Ryerson University's Learning and Teaching Office.
Clicking the link results in an Error 404 message:  Sorry, we can't find the page you requested.
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=13688&section=4 
2. Unit #3        Topic#3         Activity#  3.4 (2) 
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
@smecastellon 
Adrienne, have you found a replacement resource?  The link was taken down, but Ryerson also has these:
<https://www.ryerson.ca/experiential/what-is-experiential-learning/>
<https://www.ryerson.ca/content/dam/learning-teaching/teaching-resources/teach-a-course/experiential-learning.pdf>

**Comment by smecastellon** [comment]
Hi Kelly
Would this be a good place to integrate some of the TWU's/Jenn Skelding's work on Experiential Learning?  I am fine with Ryerson's as well if it's more user friendly.



ADRIENNE CASTELLON, EdD
Associate Dean, MA Leadership | TWU GLOBAL
Trinity Western University | t: 604.888.7511 (3330)
e. Adrienne.Castellon@twu.ca<mailto:Adrienne.Castellon@twu.ca>


TWU MA LEAD has moved all operations online until further notice. We are working hard to ensure we continue to provide you with the same quality of service.

Our online office hours are Monday to Friday, 8:30AM-4:30PM. During these times, we will aim to respond to you within the same business day. To speak on the phone with someone regarding your request, please call (236) 982-5698 during office hours.


To make a ZOOM appointment with me, please send an email to adrienne.castellon@twu.ca


“Peace I leave with you; my peace I give you. I do not give to you as the world gives. Do not let your hearts be troubled and do not be afraid.” (John 14:27, NIV)


[cid:image003.png@01D567BE.8201A250]<https://www.facebook.com/trinitywestern/>  [cid:image004.png@01D567BE.8201A250] <https://www.instagram.com/trinitywestern/>   [cid:image005.png@01D567BE.8201A250] <https://twitter.com/TrinityWestern>   [cid:image006.png@01D567BE.8201A250] <https://www.youtube.com/user/TrinityWesternU>   [cid:image007.png@01D567BE.8201A250] <https://www.linkedin.com/school/trinity-western-university/>



[cid:image001.png@01D5649E.C2C49090]


#1 Learning Matters Podcast

<https://hubhopper.com/podcast/learning-matters-a-bridge-to-practice/87726>

Learning Matters: a Bridge to Practice


________________________________

**Comment by kmarjanovic** [comment]
@smecastellon 
It would be great to integrate Jenn's work!  Do you have any links?

**Comment by smecastellon** [comment]
No, just the docs I forwarded to you and Cathy.



ADRIENNE CASTELLON, EdD
Associate Dean, MA Leadership | TWU GLOBAL
Trinity Western University | t: 604.888.7511 (3330)
e. Adrienne.Castellon@twu.ca<mailto:Adrienne.Castellon@twu.ca>


TWU MA LEAD has moved all operations online until further notice. We are working hard to ensure we continue to provide you with the same quality of service.

Our online office hours are Monday to Friday, 8:30AM-4:30PM. During these times, we will aim to respond to you within the same business day. To speak on the phone with someone regarding your request, please call (236) 982-5698 during office hours.


To make a ZOOM appointment with me, please send an email to adrienne.castellon@twu.ca


“Peace I leave with you; my peace I give you. I do not give to you as the world gives. Do not let your hearts be troubled and do not be afraid.” (John 14:27, NIV)


[cid:image003.png@01D567BE.8201A250]<https://www.facebook.com/trinitywestern/>  [cid:image004.png@01D567BE.8201A250] <https://www.instagram.com/trinitywestern/>   [cid:image005.png@01D567BE.8201A250] <https://twitter.com/TrinityWestern>   [cid:image006.png@01D567BE.8201A250] <https://www.youtube.com/user/TrinityWesternU>   [cid:image007.png@01D567BE.8201A250] <https://www.linkedin.com/school/trinity-western-university/>



[cid:image001.png@01D5649E.C2C49090]


#1 Learning Matters Podcast

<https://hubhopper.com/podcast/learning-matters-a-bridge-to-practice/87726>

Learning Matters: a Bridge to Practice


________________________________

**Comment by kmarjanovic** [comment]
@smecastellon 
Do you mean the Theology of Work document?  I don't think it explains Experiential Learning
I've listed a couple of resources in our TONE site ([Unit 1, Topic 2, Activity 1.5](https://learn.twu.ca/course/view.php?id=15550&section=1)) if it helps.

I'd suggest using https://www.ryerson.ca/content/dam/learning-teaching/teaching-resources/teach-a-course/experiential-learning.pdf.

**Comment by smecastellon** [comment]
Hi Kelly
You're right the Theology of Work doc doesn't explain experiential learning per se but it could be included in some way to differentiate how TWU approaches work, vocation etc.  I like the links and resources in Activity 1.5 a lot!



ADRIENNE CASTELLON, EdD
Associate Dean, MA Leadership | TWU GLOBAL
Trinity Western University | t: 604.888.7511 (3330)
e. Adrienne.Castellon@twu.ca<mailto:Adrienne.Castellon@twu.ca>


TWU MA LEAD has moved all operations online until further notice. We are working hard to ensure we continue to provide you with the same quality of service.

Our online office hours are Monday to Friday, 8:30AM-4:30PM. During these times, we will aim to respond to you within the same business day. To speak on the phone with someone regarding your request, please call (236) 982-5698 during office hours.


To make a ZOOM appointment with me, please send an email to adrienne.castellon@twu.ca


“Peace I leave with you; my peace I give you. I do not give to you as the world gives. Do not let your hearts be troubled and do not be afraid.” (John 14:27, NIV)


[cid:image003.png@01D567BE.8201A250]<https://www.facebook.com/trinitywestern/>  [cid:image004.png@01D567BE.8201A250] <https://www.instagram.com/trinitywestern/>   [cid:image005.png@01D567BE.8201A250] <https://twitter.com/TrinityWestern>   [cid:image006.png@01D567BE.8201A250] <https://www.youtube.com/user/TrinityWesternU>   [cid:image007.png@01D567BE.8201A250] <https://www.linkedin.com/school/trinity-western-university/>



[cid:image001.png@01D5649E.C2C49090]


#1 Learning Matters Podcast

<https://hubhopper.com/podcast/learning-matters-a-bridge-to-practice/87726>

Learning Matters: a Bridge to Practice


________________________________

**Comment by kmarjanovic** [comment]
@smecastellon  
Please let us know which resources to use - & other wording:

#### Activity 3.4: Read and Reflect
- Read Wang chapter 16 focusing on pages 411-420.
- Read this article from Ryerson University's Learning and Teaching Office.

Taking the above two readings into account, why would an adult learner especially benefit from experiential learning? Identify 3 activities that could work for your learner population and content. What challenges might you encounter when integrating experiential learning in your context?

!! Note we still need to take out the Wang reference.

**Comment by smecastellon** [comment]
Hi Kelly,

Please add this doc, (marked clearly as draft) to the course activity or assignment.

Here's some wording - feel free to adapt:

Taking the above two readings into account (TWU doc attached and Ryerson's):

  *   Why would an adult learner especially benefit from experiential learning?
  *   Considering the Theology of Experiential and Embodied Learning (p. 4 TWU doc), how does work help us be image-bearers of God?
  *   What types of experiential learning (pgs 8-10 TWU doc) could you implement in your context?  What are the potential benefits and challenges of doing so?

Hope this is helpful!



ADRIENNE CASTELLON, EdD
Associate Dean, MA Leadership | TWU GLOBAL
Trinity Western University | t: 604.888.7511 (3330)
e. Adrienne.Castellon@twu.ca<mailto:Adrienne.Castellon@twu.ca>


TWU MA LEAD has moved all operations online until further notice. We are working hard to ensure we continue to provide you with the same quality of service.

Our online office hours are Monday to Friday, 8:30AM-4:30PM. During these times, we will aim to respond to you within the same business day. To speak on the phone with someone regarding your request, please call (236) 982-5698 during office hours.


To make a ZOOM appointment with me, please send an email to adrienne.castellon@twu.ca


“Peace I leave with you; my peace I give you. I do not give to you as the world gives. Do not let your hearts be troubled and do not be afraid.” (John 14:27, NIV)


[cid:image003.png@01D567BE.8201A250]<https://www.facebook.com/trinitywestern/>  [cid:image004.png@01D567BE.8201A250] <https://www.instagram.com/trinitywestern/>   [cid:image005.png@01D567BE.8201A250] <https://twitter.com/TrinityWestern>   [cid:image006.png@01D567BE.8201A250] <https://www.youtube.com/user/TrinityWesternU>   [cid:image007.png@01D567BE.8201A250] <https://www.linkedin.com/school/trinity-western-university/>



[cid:image001.png@01D5649E.C2C49090]


#1 Learning Matters Podcast

<https://hubhopper.com/podcast/learning-matters-a-bridge-to-practice/87726>

Learning Matters: a Bridge to Practice


________________________________

**Comment by kmarjanovic** [comment]
Hi Adrienne, 
I don't see a doc attached.  Could you attach it here, or email me?
Thanks!
Kelly

@smecastellon

**Comment by kmarjanovic** [comment]
@smecastellon 
All fixed now.  Thanks Adrienne & Amber!
