### ISSUE TITLE
591 OL Unit 1 LA 4

### ISSUE THREAD

**Issue by HeatherStrong11** [TWUOnline/bug-tracking#301]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 LDRS 591 OL
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
I have changed the LA 4 in unit 1 topic 4.  There is new information in github that is not showing up in Moodle.

**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=11670&section=4
2. Unit # 1        Topic # 4        Activity#  4
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
@HeatherStrong11 , do you see the changes in Moodle now?
If not, please let us know what the changes are and we can check.

**Comment by cmadland** [comment]
Hi @HeatherStrong11, there was some missed syntax in creating the URL. You can see the changes I made at https://github.com/TWUOnline/ldrs-master/commit/41d40c41d202ed2f2c68d4fc787e4753c57d685f on line 16
