### ISSUE TITLE
Image not showing

### ISSUE THREAD

**Issue by HeatherStrong11** [TWUOnline/bug-tracking#303]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 LDRS 591 OL
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
I tried to add an image to Unit 1 topic 2 content, but it is not showing.
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=11670&section=4
2. Unit #  1       Topic #   2      Activity#  n/a
 
**Optional: Screenshots**  
![Capture](https://user-images.githubusercontent.com/30911687/81763214-8fa80000-9483-11ea-87eb-57fa6fff6306.JPG)

**Comment by HeatherStrong11** [comment]
I figured it out!!!

**Comment by HeatherStrong11** [comment]
it shows up on github, by not on Moodle.

**Comment by kmarjanovic** [comment]
All fixed!
Just as a reminder, upload the image with no spaces:
![ResearchParadigms](U1_Research_Paradigms.jpg)
