### ISSUE TITLE
LDRS 591 - alerts

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#304]
### Course
LDRS 591
### URL
https://learn.twu.ca/course/view.php?id=11670
### Instructions
Could we change the learning activities to the alert format we have in our newer courses? (blue box after Topic, not in a separate Learning Activity tab.

Please just change Units 1 & 2, as Heather is editing/removing activities from the other units. 

Note also that we need to delete some activities (See [bug 302](https://github.com/TWUOnline/bug-tracking/issues/302#event-3329426931)) 

@HeatherStrong11 let us know when the other Units are ready to reformat.

**Comment by rezakh66** [comment]
@kmarjanovic Hi Kelly, I have added primary alerts for the first two units. There are four copies of each activity that look pretty the same. Can I remove redundant files?

**Comment by HeatherStrong11** [comment]
Hi Reza,

Yes, please remove redundant files.   I just checked the course on Moodle, and it looks like you have done this already!

Thanks!

Heather

HEATHER STRONG, Ph.D
Sessional Assistant Professor, MA Leadership | TWU GLOBAL
Trinity Western University | c. 250-551-8583 | e. heather.strong@twu.ca<mailto:heather.strong@twu.ca>

[cid:image001.png@01D56D6B.9FBB05E0]
