### ISSUE TITLE
LDRS 667 - formatting

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#305]
### URL
https://learn.twu.ca/course/view.php?id=13600&section=2
### Instructions
Please format the following in Units 1 & 2 (& others when they come).

- [x] Activity Checklist - make into alert
- [x] Learning Activities - make into alert (& in same page as topic, not separate tab)
- [ ] URLs - hyperlink titles of resources 
- [x] Checking Your Learning - take out of table and just list bullet points.
- [x] Unit 0 is missing the navigation menu on the left.

**Comment by cmadland** [comment]
@JessD9 I fixed the missing navigation menu...do you know how to get started on the others?

**Comment by JessD9** [comment]
@cmadland not sure how to make the alerts

**Comment by kmarjanovic** [comment]
@JessD9 
It's easier to add folders (& alerts) by using Atom.  Perhaps look at another course that has this (BA LEAD courses)
@cmadland @rezakh66 could you please send your Git/Atom tutorial?  Could we make it a collaborative document so we can add to it?  I have my notes in the ID manual, but Colin mentioned there's a master tutorial?

**Comment by kmarjanovic** [comment]
@JessD9 @mellaurie
I'll be adding the other units today.  Please have a look at the first 2 units online (see the edits that need to be made - font consistency, alerts for checklist, etc.).
Let me or Colin know if you'd like a tutorial on how to make these changes.

**Comment by kmarjanovic** [comment]
@rezakh66 please add these 3 last units.  @JessD9  @mellaurie - Once we see the units online, we can add an assessments section & discussion section with dropboxes - copying and pasting into from the assessments section in the units.  

[LDRS-667-Unit-5-Summative-Reflective-Practice_June11_KM.docx](https://github.com/TWUOnline/bug-tracking/files/4767079/LDRS-667-Unit-5-Summative-Reflective-Practice_June11_KM.docx)
[LDRS-667-Unit-4-Teaching-Facilitating_June11_KM.docx](https://github.com/TWUOnline/bug-tracking/files/4767080/LDRS-667-Unit-4-Teaching-Facilitating_June11_KM.docx)
[LDRS-667-Unit-3-Designing-Learning-Experiences_June11_KM.docx](https://github.com/TWUOnline/bug-tracking/files/4767081/LDRS-667-Unit-3-Designing-Learning-Experiences_June11_KM.docx)
[LDRS-667-Unit-2-Classroom-Observation_June11_KM.docx](https://github.com/TWUOnline/bug-tracking/files/4767082/LDRS-667-Unit-2-Classroom-Observation_June11_KM.docx)

**Comment by rezakh66** [comment]
@kmarjanovic Hi Kelly, I have uploaded up to unit 5. Just please note that U2>>activity 2.2 is missing and U5>>assessment is a little bit confusing. there are Checking your Learning and assessment of learning sections. I have put both in the assessment section

**Comment by kmarjanovic** [comment]
@JessD9 @mellaurie
Just to give you an idea of the editing required in GitHub:

- [ ]  font/formatting issues.  see e.g. topics that have an indent or > to remove

- [ ]  activity checklist - some items are grouped together, need to be separated by a line

- [ ]  hyperlinks need to be linked
e.g.
Read: Mulder, P. (2018). [Gibbs Reflective Cycle](https://www.toolshero.com/management/gibbs-reflective-cycle-graham-gibbs/) by Graham Gibbs. 
rather than
Mulder, P. (2018). Gibbs Reflective Cycle by Graham Gibbs. Retrieved from
ToolsHero: <https://www.toolshero.com/management/gibbs-reflective-cycle-graham-gibbs/>

- [ ]  adding colour boxes for quote (add ! to beginning of quote)
 - Note I also did this for a list of items - !!!! green boxes - see after image in Topic 2.

- [ ]  delete  Learning Activity folder (first copy content, move to alert), add reference to alert in topic.

- [ ]  compare with Word doc.  For example - image in word doc is missing online.  (Since this was a diagram in word, I needed to take a screen shot, save as image, edit, save a copy in Atom/GitHub), and reference the png file in the topic. - ![](U1-diagram.png)

- [ ]  Checking Your Learning - take outcomes out of boxes.  add :fa-check: 

- [ ]  Double check all links.
e.g. one source wasn't accessible, so I needed to check if we have it in the library.  For those, insert a note for students.
:fa-book: Read: Forrest, M. E. S. (Sep 2008). On becoming a critically reflective practitioner. *Health Information & Libraries Journal, 25*(3), 229-232. Article can be accessed through the TWU Library.

Other articles not in TWU library search online for open versions.

- [ ]  Chunking paragraphs.  Check for readability online.  More paragraph breaks, indents, colour boxes, etc.

- [ ]  check grammar - missing punctuation.  References section - APA formatting.

- [ ]  reformat Grading rubric (still need to do this).

- [ ]  note when all units are in/formatted I revisit the assessment section.  Sometimes we add minimal instructions in Unit Assessment pages - copying full instructions to Assessment tab.  Grading rubric will likely go there.

Total editing time for unit 1...maybe 30 minutes.  
I'll get to the other units later (or feel free to make some of these edits).  Let me know if you want to review how to do these changes.

**Comment by kmarjanovic** [comment]
@rezakh66 could you help with formatting for Units 2-5?  There are a lot more issues than I thought there would be.   

- [ ]  font/formatting issues.  see e.g. topics that have an indent or > to remove

- [ ]  activity checklist - some items are grouped together, need to be separated by a line

- [ ]  hyperlinks need to be linked in title - not show url (see example in list above)

- [ ]  insert image for Unit 3 - see word doc.

- [ ]  Checking Your Learning - take outcomes out of boxes.  add :fa-check:

**Comment by rezakh66** [comment]
@kmarjanovic Hi Kelly, Sure, I will work on it by today.

**Comment by kmarjanovic** [comment]
Hi @rezakh66 
Just as we're training the new IDs, I want to point out a couple things I needed to fix in the list above:

- [ ]  font/formatting issues.  see e.g. topics that have an indent or > to remove **Note that some topics had a colon, some had an icon, some were missing a number.  Please ensure all topics have a number and check the formatting**  

- [ ]  activity checklist - some items are grouped together, need to be separated by a line.  **Still needed a space for separation between icons; some checklist are all in italics**

- [ ]  hyperlinks need to be linked in title - not show url (see example in list above) **Mel and I can work on this**

- [ ]  Checking Your Learning - take outcomes out of boxes.  add :fa-check: **box is gone but font is bigger - take out >**

**Comment by kmarjanovic** [comment]
Hi all,
The course is nearly ready!  I still need some help formatting the rubrics. (see Assessment section).
Other than that, will need to check all hyperlinks and make sure all resources listed are accessible.

Thanks for your help!
@rezakh66 @JessD9  @mellaurie

**Comment by JessD9** [comment]
@kmarjanovic For Unit 1: Hyperlinks have been linked, sources have been checked for accessibility, APA format+ grammar checked

**Comment by JessD9** [comment]
@kmarjanovic Unit 2 (Activity 2.1 & 2.2) links not working...will get to these later today

**Comment by kmarjanovic** [comment]
Thanks all!
