### ISSUE TITLE
Correct Activity 8.4 instructions

### ISSUE THREAD

**Issue by cpenfoldnavarro** [TWUOnline/bug-tracking#306]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 LDRS 664 A Authentic Learning Communities (SP 2020)
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.

Activity 8.4 instructions should be identical to the Assignment for Unit 8: Company Website Analysis.

In Activity 8. 4 Instructions:
Replace: Write a 300-500 (total) word response to the above questions. See the Assessment section for the grading rubric.

With: 
Your paper should be 4-5 pages and should incorporate references to at least five scholarly sources you have studied in this course, or other scholarly sources you have identified.

The paper should include:
Introduction
Analysis (responding to the prompts)
Conclusion
Reference List

 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=13591&section=8
2. Unit #      8   Topic #   1      Activity#  8.4
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
Thanks Cathy!
I've changed this, as well as a wonky Activity Checklist.

It's not showing up in Moodle or Grav.  @cmadland do we need a Grav refresh?

**Comment by kmarjanovic** [comment]
All good now!
