### ISSUE TITLE
Problem with LDRS 662 Unit 4

### ISSUE THREAD

**Issue by danielmingluito** [TWUOnline/bug-tracking#307]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
LDRS 662 Until 4
 
**Describe the error and/or your suggestion**  

Unit 4. Learning Activity 4.3 - Link 1 doesn't work.  Please replace with the link below
 
 https://ezproxy.student.twu.ca/login?url=https://search.ebscohost.com/login.aspx?direct=true&db=edsovi&AN=edsovi.00005855.201505000.00017&site=eds-live&scope=site
 

**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=13689&section=4
2. Unit #  4       Topic #         Activity#  4.3
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
Hi @danielmingluito 

The 2 links in the activity seem to be working:

#### Learning Activity 4.3: Cultural Competence Continuum
1. Cross, T., Bazron, B., Dennis, K., & Isaacs, M. (1989). [Towards a culturally competent system of care](https://spu.edu/~/media/academics/school-of-education/Cultural%20Diversity/Towards%20a%20Culturally%20Competent%20System%20of%20Care%20Abridged.ashx,)*.* (Vol. 1). Washington, DC: Georgetown University Child Development Center, CASSP Technical Assistance Center.

2. Cross, T.L. (2001). [Cultural competence continuum - Characteristics](https://www.eri-wi.org/download/conference/2013-conference/20_h_WhyDoesntEveryone_chart.pdf).

The library link you mention isn't the same resource.  (Berger and Peerson - [Cultural competence lessons learned: the continuum model](https://eds-a-ebscohost-com.ezproxy.student.twu.ca/eds/detail/detail?vid=0&sid=03fecfaf-b4e7-410d-aecf-d8f1dfae0900%40sdc-v-sessmgr01&bdata=JnNpdGU9ZWRzLWxpdmUmc2NvcGU9c2l0ZQ%3d%3d#AN=edsovi.00005855.201505000.00017&db=edsovi)

Could you let me know if you still can't access the 2 Cross resources?

**Comment by kmarjanovic** [comment]
Ahh, I see it now.  The links in the Activity Checklist are broken.  I'll update it with what's listed in the actual 4.3 activity.

**Comment by kmarjanovic** [comment]
All fixed.  Let me know about that Berger & Peerson reference.

**Comment by danielmingluito** [comment]
Thanks Kelly

I only suggested that as a substitute if the other couldn’t be fixed - all good - thank you

Warmly,

Daniel To, Ed.D
Instructor, MA Leadership | TWU Global |
Trinity Western University | M 604.726.282 | T@DanielToSD36

Website https://www.twu.ca
Blog and Personal Site https://www.drdanielto.com

On May 18, 2020, at 10:40 AM, Kelly Marjanovic <notifications@github.com> wrote:

﻿

All fixed. Let me know about that Berger & Peerson reference.

**Comment by kmarjanovic** [comment]
No problem!  Thanks so much Daniel for checking!!
