### ISSUE TITLE
picture is not appearing and bullet list is not normal

### ISSUE THREAD

**Issue by HeatherStrong11** [TWUOnline/bug-tracking#309]
**Which course contains the bug?**  
LDRS 591 A SP2020
 
 
**Describe the error and/or your suggestion**  
The picture in Unit 4 TOPIC 2 LA 2 is not showing up and the bulleted list is also not showing up correctly. 
 
**Location of the bug**  
1. URL:  https://learn.twu.ca/course/view.php?id=13220&section=4
2. Unit # 4         Topic #   2      Activity#  2
![Screenshot (28)](https://user-images.githubusercontent.com/30911687/83790105-865a1f80-a64c-11ea-9850-954761205575.png)

 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
Hi Heather,
In looking at the code, there are a couple things to do:
- Save picture file names without any spaces (e.g. statement_1.jpg)
- ![Criteria for the Statement of the Problem](statement_1.jpg)
- delete extra spaces at the front of each bullet point
e.g.  *   Is the topic interesting?
