### ISSUE TITLE
MCOM 281 - missing links

### ISSUE THREAD

**Issue by faitht1023** [TWUOnline/bug-tracking#31]
**Which course contains the bug?**  
MCOM 281: Public Speaking (FAR Centre MASTER)
 
 
**Describe the error and/or your suggestion**  
Missing links in two spots on the same page:

"Grading Criteria:
See the Persuasive Feedback and Evaluation rubric. [link to document]"
 
and

"Refer to the Speeches guidelines for creating and delivering your speeches. [link to document]"
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=10713&section=9
2. Unit # 9      Topic # Assessment   Activity#  
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
added pdfs
