### ISSUE TITLE
MCOM 221 U10 Assessment

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#310]
### Course
MCOM 221 (FAR MASTER)
### URL
https://learn.twu.ca/course/view.php?id=10829&section=10
### Instructions
The Assessment page in Unit 10 isn't showing.

Please upload required files as attachments.
![image](https://user-images.githubusercontent.com/35148983/83815394-54ad7c80-a67d-11ea-9ca5-79b3040bef0f.png)

**Comment by rezakh66** [comment]
@kmarjanovic Hi, Both units 9 and 10 assessment are showing now.

**Comment by kmarjanovic** [comment]
Thank you Reza!
