### ISSUE TITLE
MCOM 221 Facilitator's Guide

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#311]
### Course
MCOM 221 
### URL
https://far.twu.ca/guides/
### Instructions
Please add 221 to the facilitator's guide.  Or, we can wait until Colin has set up the new template for guides?
Jessica, do you mind editing the document?  Or wait to edit in GitHub?
[Facilitator_Guide_for_MCOM_221.docx](https://github.com/TWUOnline/bug-tracking/files/4732945/Facilitator_Guide_for_MCOM_221.docx)

**Comment by JessD9** [comment]
@kmarjanovic Sure, anything specific to look for besides grammar?

**Comment by kmarjanovic** [comment]
Grammar and clarity for the facilitator (non-subject matter expert).
Thank you!

**Comment by JessD9** [comment]
[Facilitator_Guide_for_MCOM_221 (Revised).docx](https://github.com/TWUOnline/bug-tracking/files/4739126/Facilitator_Guide_for_MCOM_221.Revised.docx)

**Comment by kmarjanovic** [comment]
Thank you Jess!  Reza, please use this latest version.

**Comment by rezakh66** [comment]
@kmarjanovic Hi, I have uploaded mcom221 [facilitator guide](https://far.twu.ca/guides/samc/mcom-221-digital%20film%20making)
Please be informed that  course syllabus and overview section should be completed. Practitioner documents are missing yet
Let me know when we any of these to be uploaded

**Comment by kmarjanovic** [comment]
Thank you @rezakh66 !!
