### ISSUE TITLE
LDRS 623 Units

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#312]
### Course
LDRS 623
### Instructions
@JessD9 @rezakh66  @mel (I don't see her GitHub name)
Just want to clarify or set up the process for Production, steps needed, who does what, etc.

- [x] Reza, please upload units to GitHub/Atom (may need to create 623 folder in github)
- [x] ID/ATA to create Master course in Moodle
- [x] ID/ATA to put embed code in Moodle tabs
- [x] ATA to check formatting (e.g. activity checklist and activities in alerts)

[LDRS 623_U1_June6_KM_FINAL.docx](https://github.com/TWUOnline/bug-tracking/files/4740952/LDRS.623_U1_June6_KM_FINAL.docx)
[LDRS623_U2_June6_KM-FINAL.docx](https://github.com/TWUOnline/bug-tracking/files/4740953/LDRS623_U2_June6_KM-FINAL.docx)
[LDRS623_U3_June_4_KM.docx](https://github.com/TWUOnline/bug-tracking/files/4740954/LDRS623_U3_June_4_KM.docx)

**Comment by rezakh66** [comment]
@cmadland Hi Colin, How and where should I create LDRS 623 folder? is it going to be in ldrs-master?

**Comment by cmadland** [comment]
Hi Reza, yes, that would be in ldrs-master

**Comment by rezakh66** [comment]
@kmarjanovic @cmadland Hi, is the Moodle page for this course created yet or maybe I need to create it?
Thanks

**Comment by kmarjanovic** [comment]
Hi Reza,
I don't think there's a master shell yet.  Could you create it ?  624 will need it too (I hope to send files today)

**Comment by rezakh66** [comment]
@kmarjanovic Hi Kelly, I have uploaded the first 3 units. Here is the link: https://learn.twu.ca/course/view.php?id=15687&section=1
There are a couple of small settings that I will change after asking Colin

**Comment by kmarjanovic** [comment]
@rezakh66 
Thanks Reza!  I'll have a look now.
Also - please add Unit 4
[LDRS623_U4_June19_FINAL.docx](https://github.com/TWUOnline/bug-tracking/files/4806521/LDRS623_U4_June19_FINAL.docx)

**Comment by rezakh66** [comment]
@kelly Hi Kelly, Unit 4 is uploaded just please note that activity 4.2 and 4.3 seem to be the same.

**Comment by kmarjanovic** [comment]
Thank you @rezakh66 !!  Just waiting for the final unit 5 from the SME.
