### ISSUE TITLE
LDRS 667 MASTER Remove "Timeline" Column from Course Intro 

### ISSUE THREAD

**Issue by cpenfoldnavarro** [TWUOnline/bug-tracking#313]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 LDRS 667 Practicum (MASTER)
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
In the table for "Schedule and Assessment Summary" please remove the column titled "Timeline."

(Since this course will be offered in multiple formats and on different timelines, this column shoudl be removed).
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=13600
2. Unit #  Course Introduction       Topic #    Schedule and Assessment Summary     Activity#  Timeline Column
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
all done
