### ISSUE TITLE
LDRS 667 Pre-Work Activity Checklist: Italicize Palmer book title (per APA)

### ISSUE THREAD

**Issue by cpenfoldnavarro** [TWUOnline/bug-tracking#314]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 LDRS 667 Practicum MASTER
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.

Italicize the book title (per APA) in this resource:
Activity 0.2: Re-read: Palmer, P.J. (2017). _The courage to teach: Exploring the inner landscape of a teacher's life._ Hoboken, NJ: Jossey-Bass. Re-read: Introduction, Ch 1: The Heart of a Teacher, Ch 3: The Hidden Wholeness: Paradox in Teaching and Learning, as well as other readers to prepare yourself for the practicum.
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=13600&section=3
2. Unit #   Pre-Work      Topic # Activity Checklist         Activity# Activity 0.2
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
Hmm, when I see it online, it is italicized.

Re-read: Palmer, P.J. (2017). *The courage to teach: Exploring the inner landscape of a teacher's life. *Hoboken, NJ: Jossey-Bass. Re-red: Introduction, Ch 1: The Heart of a Teacher, Ch 3: The Hidden Wholeness: Paradox in Teaching and Learning), as well as other readers to prepare yourself for the practicum

Am I missing something?

**Comment by kmarjanovic** [comment]
whoops! now I see it's not in the checklist. will do.
