### ISSUE TITLE
LDRS 667 Master: Pre-work Assessment: fix bolding

### ISSUE THREAD

**Issue by cpenfoldnavarro** [TWUOnline/bug-tracking#315]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 LDRS 667 Practicum (MASTER)
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
1. FIRST CHANGE
In the Practicum Proposal topic list there are several words bolded that shouldn't be. Just bold the following:
Practicum Site
Practicum Mentor
Learning Outcomes
Planned Schedule for 20 Hours of Experiential Learning
Learning
Career Planning

2. Second change:
REPLACE
The Practicum Proposal is due a minimum of two weeks prior to the start of the Practicum course. It is worth 10% of your course grade.
WITH
The Practicum Proposal is due prior to the start of the Practicum course, usually 1-2 weeks in advance. (Review the Due Dates tab for exact date). 

The Practicum Proposal is worth 10% of your course grade.

3. THIRD CHANGE
Update link to "Mentor Agreement" (I can send an updated copy).
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=13600&section=3
2. Unit #    Assessment     Topic #  Practicum Proposal      Activity#  
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
Done.  Cathy, could you double check that the correct version of the Mentor agreement is attached?
