### ISSUE TITLE
LDRS 667 (MASTER) Prework Summary 

### ISSUE THREAD

**Issue by cpenfoldnavarro** [TWUOnline/bug-tracking#316]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 LDRS 667 (MASTER) 
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
Remove "Unit 0" as that isn't used elsewhere.
Replace with: Pre-Work Summary
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=13600&section=3
2. Unit #   Pre-Work      Topic # Summary         Activity#  
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
done
