### ISSUE TITLE
Update Course Description in LDRS 667 PreWork

### ISSUE THREAD

**Issue by cpenfoldnavarro** [TWUOnline/bug-tracking#318]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 LDRS 667 Practicum MASTER
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.

REPLACE:
Using reflective practice, learners apply adult learning theory, facilitation practices, cross-cultural competency, and assessment strategies in a professional learning facilitation setting. Learners compete a supervised practicum within an educational institution, business, non-profit agency, social service agency, or organization related to their personal interests and career goals. Learners complete 20 hours of experiential learning, including observation of teaching, lesson plan design, and facilitation of learning activities.

WITH: 
 Course Description: This course provides students with a practical setting in which to apply what they have learned in the Certificate in Coaching and Facilitation. Using reflective practice, learners apply learning theory, assessment theory, facilitation practices, and cross-cultural competency, in a professional learning facilitation setting. The practicum must be with a supervised business, non-profit agency, social service agency, or institution related to the student’s personal interests and future plans.

(While the course description has been changed, it has not yet been approved by the Curriculum Committee).

**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=13600&section=3
2. Unit #  Pre-Work       Topic # Course Description        Activity#  
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
done.  I'll check on the status of approval.
