### ISSUE TITLE
LDRS 667 MASTER: Unit 1 Learning Activity Checklists

### ISSUE THREAD

**Issue by cpenfoldnavarro** [TWUOnline/bug-tracking#319]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 LDRS 667 MASTER
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 
Activity 1.1 should only include the Merriam reference. 
All the other references should be moved to Activity 1.2 Checklist (which will include: Larrivee, Forrest, Claiborne, Mulder, U of Edinburgh)

SECOND CHANGE:
In the rubric, remove the numbers 2,3, 4, and 4 in the heading row. Instead, just use: Unsatisfactory 0%,Developing 50% (C) etc.

THIRD CHANGE:
In the Reference List, change last reference to read "Gibbs' Reflective Cycle" instead of "Gibb's Reflective Cycle"
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=13600&section=4
2. Unit #  1      Topic # 1        Activity#  Learning Activities
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
Done.
Note I want to reformat the rubrics to be a bit more clean and readable.

@JessD9  @mellaurie  - let's look at some rubric options for formatting in Grav/GitHub .  On my to-do list is [rubric tools in Moodle](https://docs.moodle.org/38/en/Rubrics), but I haven't come across any I like.  Perhaps a project for July?
See rubric used in [Assignment 1 of LDRS 664](https://learn.twu.ca/grade/grading/form/rubric/edit.php?areaid=23261)
As well as the screenshots below.

![image](https://user-images.githubusercontent.com/35148983/85061634-65bdb980-b164-11ea-807c-b14863b889cf.png)

![image](https://user-images.githubusercontent.com/35148983/85061956-ea103c80-b164-11ea-8f03-1f30a5854148.png)
