### ISSUE TITLE
LDRS 667 Practicum (MASTER) Unit 2 Activity Checklist

### ISSUE THREAD

**Issue by cpenfoldnavarro** [TWUOnline/bug-tracking#320]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 LRDS 667 Master
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 
Add a link to this document:
Read: Madland, C. (2017). The Trinity Community of Inquiry. Creative Commons License.
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=13600&section=5
2. Unit # 2        Topic # Overview and Topic 1        Activity#  Activity Checklist
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
Done
Note to @JessD9 & @mellaurie  - check out Colin's paper - some great framing for online multi-access courses at TWU!
