### ISSUE TITLE
LDRS 667 MASTER Unit 5

### ISSUE THREAD

**Issue by cpenfoldnavarro** [TWUOnline/bug-tracking#323]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 LDRS 667 MASTER
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
In the Learning Outcomes and Course Overview/Assessment Replace Gibb's with Gibbs' (apostrophe after the s)

Also note: The rubric does not have a header row, and there are some changes in font size. 
In the Summary of Unit 5, there are a few extra line breaks in the "Checking your Learning" section.
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=13600&section=8
2. Unit #   5      Topic # Overview         Activity# Learning Outcomes, Activity Checklist (Assessment) 
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
Done.

Note the rubrics were giving me grief!  For now I've put them in a pdf form.  @rezakh66 can you help with the formatting?  We can keep the pdf version, but also add the formatting rubric table back in for Unit 5 Assessment, and Assignment 4 (Portfolio).

@JessD9 @mellaurie Rubric formatting is a common issue in Grav just fyi.

**Comment by rezakh66** [comment]
@Hi Kelly, Done. Is there anything else that needs to be changed?

**Comment by kmarjanovic** [comment]
Perfect! Thanks @rezakh66
