### ISSUE TITLE
LDRS 667 MASTER Assignments

### ISSUE THREAD

**Issue by cpenfoldnavarro** [TWUOnline/bug-tracking#324]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 LDRS 667 MASTER
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
In Assignments/Index: Schedule and Assessment Summary: Remove the column "Timeline"
In Assignments/Discussions/Rubric: remove 0, 2, 3, 4 from Rubric heading  

Add discussion boxes for Reflective Practice Discussions 8, 9, and 10. Named: 
Reflective Practice Discussion 8: Teaching/Facilitation
Reflective Practice Discussion 9: Teaching/Facilitation
Reflective Practice Discussion 10: Teaching/Facilitation

In Assignments/Practicum Proposal:
Remove" In preparation for the practicum, review the LDRS 667 Practicum Student Guide." 
Replace with: "In preparation for the practicum, write a 3-5 page Practicum Proposal, including the following sections:"

Under the Practicum Mentor section, remove: "found in the LDRS 667 Practicum Student Guide)

From the Rubric: Practicum Proposal remove: 0, 2, 3, 4 in the heading row.  

In Assignments/Lesson Plan:
In the rubric, replace "Student Learning Outcome" with "Learning Outcome"  and "SLO: with "Learning Outcome"

In Assignments/Practicum Portfolio:
Replace Gibb's with Gibbs' (apostrophe after the s) in both the rubric and instructions.
Check line spacing
Formatting in rubric needs work.

**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=13600&section=9
2. Unit #  Assignments       Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
Done,
@rezakh66 some same issues with the rubric.  Please help format in GitHub, and we can keep the pdf version as well.
(Unit 3 Assessment and Assignment 3 Lesson Plan)

[LDRS_667_Lesson_Plan_Rubric.docx](https://github.com/TWUOnline/bug-tracking/files/4800968/LDRS_667_Lesson_Plan_Rubric.docx)

**Comment by rezakh66** [comment]
@kmarjanovic Hi, Can you please check if the format is the way you want? https://learn.twu.ca/course/view.php?id=13600&section=6

**Comment by kmarjanovic** [comment]
@rezakh66 Yes, that's great!  We may look into other rubric styles but this is perfect for now.

Could you delete one of the learning outcomes in the first right column (LEARNING OUTCOME(S) (LEARNING OUTCOME)(20%)
And then in that row - make the 8 LEARNING OUTCOME(S) lowercase?

Thank you!

**Comment by rezakh66** [comment]
@kmarjanovic Hi Kelly,Done.
