### ISSUE TITLE
LDRS 624 Units

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#325]
Course not in Moodle or GitHub yet.

### Instructions
Please upload & format units

[LDRS 624_U1_May19_KM-FINAL.docx](https://github.com/TWUOnline/bug-tracking/files/4806487/LDRS.624_U1_May19_KM-FINAL.docx)
[LDRS624_U2_June6_KM-FINAL.docx](https://github.com/TWUOnline/bug-tracking/files/4806488/LDRS624_U2_June6_KM-FINAL.docx)
[LDRS624_U3_June19_KM-FINAL.docx](https://github.com/TWUOnline/bug-tracking/files/4806489/LDRS624_U3_June19_KM-FINAL.docx)
[LDRS624_U4_June19_KM_FINAL.docx](https://github.com/TWUOnline/bug-tracking/files/4806498/LDRS624_U4_June19_KM_FINAL.docx)

@JessD9 @mellaurie - Let me know if you'd like to meet next week to go over formatting changes/steps in Production.

**Comment by JessD9** [comment]
@kmarjanovic Yes, I'd like to briefly go over Production steps

**Comment by cmadland** [comment]
624 created in github

**Comment by rezakh66** [comment]
@kmarjanovic Hi, I have formatted up to unit 4 available [here](https://learn.twu.ca/course/view.php?id=15704&section=1)

**Comment by kmarjanovic** [comment]
Thank you @rezakh66 !
I'll review things this next week.
In the meantime, can you add this last unit?
[LDRS624_U5_July1_KM.docx](https://github.com/TWUOnline/bug-tracking/files/4859933/LDRS624_U5_July1_KM.docx)

**Comment by rezakh66** [comment]
Hi Kelly,
Unit 5 is uploaded.

**Comment by kmarjanovic** [comment]
Thanks Reza!
