### ISSUE TITLE
LDRS 667 MASTER Change to Schedule and Assessment Summary

### ISSUE THREAD

**Issue by cpenfoldnavarro** [TWUOnline/bug-tracking#326]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 LDRS 667 Practicum MASTER
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.

Change the topic of the table titled "Schedule and Assessment Summary" to "Assessment Summary" 
In the table titled "Schedule and Assessment Summary" there is one row missing. 
In Unit 3: Designing Learning Experiences, after Lesson Plan 3, there should be line that reads:
Lesson Plan Peer Review, Reflective Practice Discussions: 5, 6, 7 10% 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:

1. URL:  https://learn.twu.ca/course/view.php?id=13600
AND
https://learn.twu.ca/course/view.php?id=13600&section=9

2.
NOTE: This change needs to be made to both the Course Introduction and the Assignments Tab
 Unit # Course Intro        Topic #   Schedule and Assessment Summary      Activity#  
Unit # Assignments       Topic #   Schedule and Assessment Summary      Activity#  

![Table of assignments LDRS 667](https://user-images.githubusercontent.com/36927821/85316629-0d9bf580-b48b-11ea-9285-1179da882788.PNG)

 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
done!
