### ISSUE TITLE
LDRS 620 - Add Units

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#327]
### Instructions
- [ ] Please upload units.  Both the Git repository and Moodle master shell may need to be created.

[LDRS_620_U1_July1_KM.docx](https://github.com/TWUOnline/bug-tracking/files/4860113/LDRS_620_U1_July1_KM.docx)
[LDRS_620_U2_July1_KM.docx](https://github.com/TWUOnline/bug-tracking/files/4860108/LDRS_620_U2_July1_KM.docx)
[LDRS_620_U3_July1_KM.docx](https://github.com/TWUOnline/bug-tracking/files/4860110/LDRS_620_U3_July1_KM.docx)
[LDRS_620_U4_July1_KM.docx](https://github.com/TWUOnline/bug-tracking/files/4860111/LDRS_620_U4_July1_KM.docx)
[LDRS_620_U5_July1_KM.docx](https://github.com/TWUOnline/bug-tracking/files/4860112/LDRS_620_U5_July1_KM.docx)

Links to assessment rubric & activity word doc:
[LDRS_620_forum_post_rubric.docx](https://github.com/TWUOnline/bug-tracking/files/4860126/LDRS_620_forum_post_rubric.docx)
[LDRS_620_reflection_and_application_rubric.docx](https://github.com/TWUOnline/bug-tracking/files/4860119/LDRS_620_reflection_and_application_rubric.docx)
[LDRS_620_unit_reflection_rubric.docx](https://github.com/TWUOnline/bug-tracking/files/4860120/LDRS_620_unit_reflection_rubric.docx)
[LDRS_620_summative_academic_paper_rubric.docx](https://github.com/TWUOnline/bug-tracking/files/4860492/LDRS_620_summative_academic_paper_rubric.docx)

[Activity_4-6_First_Peoples_Principles_of_Learning.docx](https://github.com/TWUOnline/bug-tracking/files/4860123/Activity_4-6_First_Peoples_Principles_of_Learning.docx)

**Comment by rezakh66** [comment]
@kmarjanovic Hi Kelly, We uploaded and formatted up to [unit 5](https://learn.twu.ca/course/view.php?id=15710&section=5). Rubrics are attached within the assessment section as per required or do you want a separate tab for assessments rubric to be created?

**Comment by kmarjanovic** [comment]
Hi @rezakh66  
I haven't had a chance to look at the course yet, but Karen and I will this week and can move assessment details.  (likely to a separate assessment tab, but we need to look at the content again.)
@karenroeck
