### ISSUE TITLE
LDRS 301 Units

### ISSUE THREAD

**Issue by JessD9** [TWUOnline/bug-tracking#328]
### Instructions
@rezakh66 Please upload units to GiHub/Atom (may need to create 301 folder in github)

[LDRS_301_U1_Jul6_2020_DA.docx](https://github.com/TWUOnline/bug-tracking/files/4882456/LDRS_301_U1_Jul6_2020_DA.docx)
[U1_topic1_activity1.3_ppt.pptx](https://github.com/TWUOnline/bug-tracking/files/4886869/U1_topic1_activity1.3_ppt.pptx)
(Please convert unit 1 PWPT to presentation plugin)
[LDRS_301_U2_Jun28_DA.docx](https://github.com/TWUOnline/bug-tracking/files/4882457/LDRS_301_U2_Jun28_DA.docx)

**Comment by rezakh66** [comment]
@JessD9 I will get this done by today. Thanks

**Comment by rezakh66** [comment]
@JessD9 I have uploaded both units [here](https://learn.twu.ca/course/view.php?id=15711&section=1)

**Comment by rezakh66** [comment]
@JessD9 Hi Jessica, Presentation is uploaded.

**Comment by JessD9** [comment]
@rezakh66 Thank you Reza!

**Comment by JessD9** [comment]
Please add Grading Rubric that's on page 14 of the doc.

[LDRS_301_U2_Jul26_DA.docx](https://github.com/TWUOnline/bug-tracking/files/4981148/LDRS_301_U2_Jul26_DA.docx)

**Comment by rezakh66** [comment]
@JessD9 Done.

**Comment by JessD9** [comment]
@rezakh66 Here are Units 4, 5, 6
[LDRS_301_U4_Jul30_DA.docx](https://github.com/TWUOnline/bug-tracking/files/5177684/LDRS_301_U4_Jul30_DA.docx)

[LDRS_301_U5_Aug27_DA.docx](https://github.com/TWUOnline/bug-tracking/files/5177694/LDRS_301_U5_Aug27_DA.docx)

[LDRS_301_U6_Aug27_DA.docx](https://github.com/TWUOnline/bug-tracking/files/5177695/LDRS_301_U6_Aug27_DA.docx)

**Comment by JessD9** [comment]
@karenroeck still in progress:)

**Comment by rezakh66** [comment]
@JessD9 Hi Jessica, Units 4-6 are uploaded.

**Comment by JessD9** [comment]
@rezakh66 Here are units 7 and 8 
these are the last ones:)

[LDRS_301_U7_Aug28_DA.docx](https://github.com/TWUOnline/bug-tracking/files/5257770/LDRS_301_U7_Aug28_DA.docx)
[LDRS_301_U8_Sep13_DA.docx](https://github.com/TWUOnline/bug-tracking/files/5257771/LDRS_301_U8_Sep13_DA.docx)

**Comment by rezakh66** [comment]
Hi @JessD9 Both units are uploaded. ;)

**Comment by JessD9** [comment]
Thanks @rezakh66.
If you have some time this week, can you upload the 399 Facilitator Guide?

**Comment by JessD9** [comment]
@rezakh66 Can you "shade" the x and y axis of the rubric in Unit 2? (Make top and left borders of the table darker)

Also in Unit 3 Assessment, can you make the Rubric look like the rubric in Unit 2? (you can delete the screenshot)
[LDRS_301_U3_Rubric.docx](https://github.com/TWUOnline/bug-tracking/files/5412466/LDRS_301_U3_Rubric.docx)

In Unit 4 Assessment, please add and format the rubric. (You can delete the screenshot)
[LDRS_301_U4_Rubric.docx](https://github.com/TWUOnline/bug-tracking/files/5412497/LDRS_301_U4_Rubric.docx)

Lastly, please add Rubric to Unit 8 in the same format: 
[LDRS_301_Final_Paper_Rubric_U8.docx](https://github.com/TWUOnline/bug-tracking/files/5412481/LDRS_301_Final_Paper_Rubric_U8.docx)

**Comment by rezakh66** [comment]
Hi @JessD9 I have formatted the tables with similar colors as the screenshots. Please let me know if you need a different color.  Darker or brighter. I have kept the screenshots for easier comparison.

**Comment by JessD9** [comment]
@rezakh66 Thank You! They look great

**Comment by JessD9** [comment]
@rezakh66 Please add the Facilitator Guide. Thank You
[LDRS301_Facilitator_Guide_Dec31_DA.docx](https://github.com/TWUOnline/bug-tracking/files/5761110/LDRS301_Facilitator_Guide_Dec31_DA.docx)

**Comment by rezakh66** [comment]
Hi @JessD9 I have added the Facilitator's guide.

**Comment by JessD9** [comment]
thank you!!
