### ISSUE TITLE
LDRS 620 presentation plugin

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#330]
### Course
LDRS 620- FAR MASTER

### URL
https://learn.twu.ca/course/view.php?id=15710&section=1

### Instructions
For Unit 1, Topic 1, create 3 presentation plugins to show the images in a slideshow format.  See course for photo links

Presentation 1: 
Which woman is the most beautiful? Photo 1 | Photo 2| Photo 3
Presentation 2: 
Who is being treated the most unfairly? Photo 1 | Photo 2| Photo 3
Presentation 2: 
Who is living the “good life”? Photo 1 | Photo 2 | Photo 3

**Comment by rezakh66** [comment]
@kmarjanovic  Hi Kelly, This is done

**Comment by kmarjanovic** [comment]
Thank you @rezakh66 !!  This looks great!
@karenroeck let us know if there are any other changes to this activity.
