### ISSUE TITLE
Youtube plugin

### ISSUE THREAD

**Issue by HeatherStrong11** [TWUOnline/bug-tracking#331]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 LDRS 591 A SU 2020
 
**Describe the error and/or your suggestion**  
I am trying to use the youtube plugin in two spots in the Unit 1 Topic 2 content.  The plugin is not working like it does when I include it in the alerts.  What am I doing wrong?
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=13220&section=2
2. Unit #  1       Topic # 2     
![plugin](https://user-images.githubusercontent.com/30911687/86958937-ce6bd680-c111-11ea-9ae5-7c3686efbdfc.JPG)
  
 
**Optional: Screenshots**

**Comment by rezakh66** [comment]
@HeatherStrong11 Hi Heather, I fixed the youtube link issue. please always make sure to insert clean(ads-free) links which is to the video itself, not the video and the ads before that. Please see the screenshot where you can find the clean link.
![youtube](https://user-images.githubusercontent.com/55214859/87192216-e3c83880-c2aa-11ea-9e32-038141974329.jpeg)
Let me know if it's not clear and we can Zoom

**Comment by kmarjanovic** [comment]
@rezakh66 Thanks for the tip!!  I don't think I've been doing that for the youtube videos!
