### ISSUE TITLE
MCOM 281 

### ISSUE THREAD

**Issue by karenroeck** [TWUOnline/bug-tracking#333]
**Which course contains the bug?**  
MCOM 281
 
**Describe the error and/or your suggestion**  
At the bottom of the "Assessment" section in each unit, there is a blue "Schedule" button that leads to a 404 page. Please remove this button from Units 1-10. 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL: https://learn.twu.ca/course/view.php?id=10713&section=7
2. Unit #         Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
@cmadland @rezakh66 
We have this same button issue we've had in other courses.  Please help!

**Comment by rezakh66** [comment]
@kmarjanovic I think this is resolved in another issue and we can close it?

**Comment by kmarjanovic** [comment]
Yes - thank you!
