### ISSUE TITLE
MCOM 281 "Schedule" button in Moodle

### ISSUE THREAD

**Issue by karenroeck** [TWUOnline/bug-tracking#334]
**Which course contains the bug?**  
MCOM 281
 
**Describe the error and/or your suggestion**  
At the bottom of the "Assessment" section in each unit, there is a blue "Schedule" button that leads to a 404 page. Please remove this button from Units 1-10. 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL: https://learn.twu.ca/course/view.php?id=10713&section=7
2. Units 1-10, "Assessment" 
 
**Optional: Screenshots**  
![Screen Shot 2020-07-09 at 11 33 58 AM](https://user-images.githubusercontent.com/67760065/87077597-371d8680-c1d8-11ea-9eda-e8e50928cf06.png)

**Comment by rezakh66** [comment]
@karenroeck Hi Karen, I removed all Schedule buttons.

**Comment by karenroeck** [comment]
@rezakh66 Thanks so much! Maybe you can show me how to do that sometime.

**Comment by rezakh66** [comment]
@karenroeck Hi Karen, Sure, slack me when it's more convenient to you.

**Comment by mellaurie** [comment]
@rezakh66 Please show me too!  I am finding the same problem in LDRS 303

**Comment by rezakh66** [comment]
@mellaurie Sure, slack me when is more convenient to you.
