### ISSUE TITLE
Two bugs in MCOM 281: Public Speaking (FAR Centre MASTER)

### ISSUE THREAD

**Issue by karenroeck** [TWUOnline/bug-tracking#335]
**Which course contains the bug?**  
MCOM 281: Public Speaking (FAR Centre MASTER)
 
**Describe the error and/or your suggestion**  

1. In Unit 5, Topic 3 ("Crafting a Strong Introduction") is incorrectly listed under Topic 2. Topic 3 needs its own section, and the current Topics 3-5 need to be relabelled as Topics 4-6 in the sidebar and the titles.

2. For Units 1-10, the Unit Summary is incorrectly located at the end of the last topic for that unit. Please create a separate section for "Summary" and insert it between the last topic and "Assessment" in the sidebar.
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:

1. URL: https://learn.twu.ca/course/view.php?id=10713&section=5

2. URL (for Unit 1 - this needs to be fixed in Units 1-10): https://learn.twu.ca/course/view.php?id=10713&section=1

**Comment by rezakh66** [comment]
@karenroeck Hi Karen, I made the changes. Please check and let me know if that's ok.

**Comment by karenroeck** [comment]
@rezakh66 Unit 5, Topics 1-6 look correct. Thanks for doing that. "Summary" is showing twice in the sidebar for Units 1, 5, and 6 - could you please delete the second folder in Atom? "Summary" should only appear before "Assessments." Thanks!

**Comment by rezakh66** [comment]
@karenroeck Done

**Comment by karenroeck** [comment]
Looks great - thanks!
