### ISSUE TITLE
PHIL 210 Wrong navigation button

### ISSUE THREAD

**Issue by mellaurie** [TWUOnline/bug-tracking#336]
**Which course contains the bug?**  
- PHIL 210 FAR
 
 
**Describe the error and/or your suggestion**  

1. There is a button at the bottom of the reflective journal assignment page that says "header image." This needs to be changed to a button that leads to the next assignment, ethics committee.  
2. In ethics committee, the navigation button for the reflective journal needs to replace the "assessment" button.
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=8095&section=12
2. Tab: Assignments         Sub-tab: Reflective Journal and Ethics Committee

**Comment by karenroeck** [comment]
@mellaurie Colin showed me how to fix this issue - can you take a look at the page to make sure everything is resolved?

**Comment by mellaurie** [comment]
Thanks for fixing this!  @karenroeck I'd love to learn how this is done.

**Comment by karenroeck** [comment]
@mellaurie Sure thing - send me a zoom invite for tomorrow sometime and we can muddle through together ;)
