### ISSUE TITLE
LDRS 620 - Facilitator's Guide

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#338]
### Course
LDRS 620
### URL
https://github.com/TWUOnline/far-centre-guides/tree/master/pages/02.lead-ma
### Instructions
Please add the attached guide.

@cmadland with the new format you're working on (embedded page in moodle with dropdown menu) - is this repository still what we're using?

Can we start moving all guides to this new format?

[LDRS_620_Facilitator_Guide.docx](https://github.com/TWUOnline/bug-tracking/files/4921014/LDRS_620_Facilitator_Guide.docx)

**Comment by rezakh66** [comment]
@kmarjanovic Hi Kelly, the guide is up now.

**Comment by kmarjanovic** [comment]
Thanks @rezakh66 !
There are just minor formatting tweaks to fix (asterisk at the end of headings), Heading consistency (see Unit 5).
@karenroeck could you review and let us know other changes?

**Comment by karenroeck** [comment]
@rezakh66 @kmarjanovic The Facilitator's Guide looks great. I noticed two further tweaks needed:

-The title in the sidebar needs to be capitalized without dashes (e.g. Worldview Foundations of Educational Leadership")
-In Unit 3, there is an extra line space between the Activity 3.8 heading and the sentence below. This extra line needs to be removed.

**Comment by rezakh66** [comment]
@kmarjanovic @karenroeck I have made the changes, Can you please check and let me know if you want different headings for different activities. I have used #### for now.

**Comment by karenroeck** [comment]
@rezakh66 Are you able to edit the name of the course in the sidebar? It is still showing as LDRS 620: worldview-foundations-of-educational-leadership

Could you make Topic and Assignment Headings bigger? The Activity and Facilitated Learning Lab headings are great as is.

**Comment by rezakh66** [comment]
@karenroeck Hi Karen, I made the changes. Assignments and topics are now one size bigger.

**Comment by karenroeck** [comment]
@rezakh66 looks great! Last picky detail then we can close this bug - can you please capitalize the name of the course in the sidebar? e.g. Worldview Foundations of Educational Leadership

**Comment by rezakh66** [comment]
@karenroeck I changed it 👍

**Comment by kmarjanovic** [comment]
I'm trying to link this to the course.  Could you let me know the correct embed code?

<p><iframe scrolling="yes" style="border: 0px #ffffff none;" src="https://far.twu.ca/lead-ma/LDRS-620-Worldview Foundations of Educational Leadership/chromeless:true/hidepagetitle:true" allowfullscreen="allowfullscreen" width="100%" height="1000"></iframe></p>

https://learn.twu.ca/course/view.php?id=15710&section=11

**Comment by rezakh66** [comment]
@kmarjanovic It was not created yet, It's available [here](https://learn.twu.ca/course/view.php?id=15710&section=11) now.

**Comment by kmarjanovic** [comment]
Thank you @rezakh66 !!
