### ISSUE TITLE
LDRS 624 formatting

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#339]
### Course
LDRS 624
### URL
https://learn.twu.ca/course/view.php?id=15704&section=5

### Instructions
@rezakh66  Could you have a look at the formatting in Unit 5 Assessment?   Checking your learning, bug report line, etc.

**Comment by rezakh66** [comment]
@kmarjanovic I made the changes and also change the order of summary and assessment throughout the whole units.

**Comment by kmarjanovic** [comment]
Thanks @rezakh66 !!
