### ISSUE TITLE
Production LDRS 620 Unit 5

### ISSUE THREAD

**Issue by karenroeck** [TWUOnline/bug-tracking#340]
### Course
LDRS 620 FAR Centre MASTER

### URL
https://learn.twu.ca/course/view.php?id=15710&section=5

### Instructions
- Please edit the attached PDF to clean up the scanning job (crop out half pages and unneeded white spaces)
- Insert into Activity 5.1 ("Read the following excerpt...")

Please upload required files as attachments.

[Cha3-Nouwen.pdf](https://github.com/TWUOnline/bug-tracking/files/4928156/Cha3-Nouwen.pdf)

**Comment by Raulmelara** [comment]
@karenroeck I've made the edits on the file and uploaded as attachment in Activity 5.1

**Comment by karenroeck** [comment]
@rezakh66 thank you, this file looks so much cleaner now!
