### ISSUE TITLE
LDRS 624 Scanned documents

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#341]
### Course
LDRS 624

### URL
Moodle: https://learn.twu.ca/course/view.php?id=15704&section=0
GitHub: https://github.com/TWUOnline/ldrs-master/tree/master/pages/10.624/Files
Blueprint (has page references): https://docs.google.com/document/d/1SesDUwCHe603aJWRGsSXpnmhjxV2m13gmpE33D9Ab2I/edit

### Instructions

The scanned docs for this course (& 623 & 620) need some major TLC!  @cmadland @Jeff-TWU do you have any suggestions?  Could you clean up and combine the docs?  Then add to the Files repository in GitHub so we can direct the link in the units?
### LDRS 664
Unit 5
[Beerens.pdf](https://github.com/TWUOnline/bug-tracking/files/4928432/Beerens.pdf)
[Beerens000.pdf](https://github.com/TWUOnline/bug-tracking/files/4928433/Beerens000.pdf)
[Beerens001.pdf](https://github.com/TWUOnline/bug-tracking/files/4928434/Beerens001.pdf)
[Beerens002.pdf](https://github.com/TWUOnline/bug-tracking/files/4928435/Beerens002.pdf)
[Beerens003.pdf](https://github.com/TWUOnline/bug-tracking/files/4928436/Beerens003.pdf)

Unit 4
[Cloud.pdf](https://github.com/TWUOnline/bug-tracking/files/4928437/Cloud.pdf)
[Cloud000.pdf](https://github.com/TWUOnline/bug-tracking/files/4928438/Cloud000.pdf)
[Cloud001.pdf](https://github.com/TWUOnline/bug-tracking/files/4928439/Cloud001.pdf)
[Cloud002.pdf](https://github.com/TWUOnline/bug-tracking/files/4928440/Cloud002.pdf)
[Cloud003.pdf](https://github.com/TWUOnline/bug-tracking/files/4928441/Cloud003.pdf)
[Cloud004.pdf](https://github.com/TWUOnline/bug-tracking/files/4928442/Cloud004.pdf)
[Cloud005.pdf](https://github.com/TWUOnline/bug-tracking/files/4928443/Cloud005.pdf)
[Cloud006.pdf](https://github.com/TWUOnline/bug-tracking/files/4928444/Cloud006.pdf)
[Cloud007.pdf](https://github.com/TWUOnline/bug-tracking/files/4928445/Cloud007.pdf)

[Couros and Novak.pdf](https://github.com/TWUOnline/bug-tracking/files/4928446/Couros.and.Novak.pdf)
[Couros and Novak000.pdf](https://github.com/TWUOnline/bug-tracking/files/4928447/Couros.and.Novak000.pdf)
[Couros and Novak001.pdf](https://github.com/TWUOnline/bug-tracking/files/4928448/Couros.and.Novak001.pdf)
[Couros and Novak002.pdf](https://github.com/TWUOnline/bug-tracking/files/4928449/Couros.and.Novak002.pdf)
[Couros and Novak003.pdf](https://github.com/TWUOnline/bug-tracking/files/4928450/Couros.and.Novak003.pdf)
[Couros and Novak004.pdf](https://github.com/TWUOnline/bug-tracking/files/4928451/Couros.and.Novak004.pdf)
[Couros and Novak005.pdf](https://github.com/TWUOnline/bug-tracking/files/4928452/Couros.and.Novak005.pdf)
[Couros and Novak006.pdf](https://github.com/TWUOnline/bug-tracking/files/4928453/Couros.and.Novak006.pdf)
[Couros and Novak007.pdf](https://github.com/TWUOnline/bug-tracking/files/4928454/Couros.and.Novak007.pdf)
[Couros and Novak008.pdf](https://github.com/TWUOnline/bug-tracking/files/4928455/Couros.and.Novak008.pdf)
[Couros and Novak009.pdf](https://github.com/TWUOnline/bug-tracking/files/4928456/Couros.and.Novak009.pdf)

Unit 2
[Ferguson.pdf](https://github.com/TWUOnline/bug-tracking/files/4928457/Ferguson.pdf)
[Ferguson000.pdf](https://github.com/TWUOnline/bug-tracking/files/4928458/Ferguson000.pdf)
[Ferguson001.pdf](https://github.com/TWUOnline/bug-tracking/files/4928459/Ferguson001.pdf)
[Ferguson002.pdf](https://github.com/TWUOnline/bug-tracking/files/4928460/Ferguson002.pdf)
[Ferguson003.pdf](https://github.com/TWUOnline/bug-tracking/files/4928461/Ferguson003.pdf)
[Ferguson004.pdf](https://github.com/TWUOnline/bug-tracking/files/4928462/Ferguson004.pdf)
[Ferguson005.pdf](https://github.com/TWUOnline/bug-tracking/files/4928463/Ferguson005.pdf)
[Ferguson006.pdf](https://github.com/TWUOnline/bug-tracking/files/4928464/Ferguson006.pdf)
[Ferguson007.pdf](https://github.com/TWUOnline/bug-tracking/files/4928465/Ferguson007.pdf)

[Leman.pdf](https://github.com/TWUOnline/bug-tracking/files/4928416/Leman.pdf)
[Leman000.pdf](https://github.com/TWUOnline/bug-tracking/files/4928417/Leman000.pdf)

Unit 1
[Finzel 2.pdf](https://github.com/TWUOnline/bug-tracking/files/4928466/Finzel.2.pdf)
[Finzel 2000.pdf](https://github.com/TWUOnline/bug-tracking/files/4928467/Finzel.2000.pdf)
[Finzel 2001.pdf](https://github.com/TWUOnline/bug-tracking/files/4928468/Finzel.2001.pdf)
[Finzel 2002.pdf](https://github.com/TWUOnline/bug-tracking/files/4928469/Finzel.2002.pdf)
[Finzel 2003.pdf](https://github.com/TWUOnline/bug-tracking/files/4928470/Finzel.2003.pdf)
[Finzel.pdf](https://github.com/TWUOnline/bug-tracking/files/4928471/Finzel.pdf)
[Finzel000.pdf](https://github.com/TWUOnline/bug-tracking/files/4928410/Finzel000.pdf)
[Finzel001.pdf](https://github.com/TWUOnline/bug-tracking/files/4928411/Finzel001.pdf)
[Finzel002.pdf](https://github.com/TWUOnline/bug-tracking/files/4928412/Finzel002.pdf)
[Finzel003.pdf](https://github.com/TWUOnline/bug-tracking/files/4928413/Finzel003.pdf)
[Finzel004.pdf](https://github.com/TWUOnline/bug-tracking/files/4928414/Finzel004.pdf)
[Finzel005.pdf](https://github.com/TWUOnline/bug-tracking/files/4928415/Finzel005.pdf)

### LDRS 623
Unit 4
[VanBrummelen.pdf](https://github.com/TWUOnline/bug-tracking/files/4928418/VanBrummelen.pdf)
[VanBrummelen000.pdf](https://github.com/TWUOnline/bug-tracking/files/4928419/VanBrummelen000.pdf)
[VanBrummelen001.pdf](https://github.com/TWUOnline/bug-tracking/files/4928420/VanBrummelen001.pdf)
[VanBrummelen002.pdf](https://github.com/TWUOnline/bug-tracking/files/4928421/VanBrummelen002.pdf)
[VanBrummelen003.pdf](https://github.com/TWUOnline/bug-tracking/files/4928422/VanBrummelen003.pdf)
[VanBrummelen004.pdf](https://github.com/TWUOnline/bug-tracking/files/4928423/VanBrummelen004.pdf)
[VanBrummelen005.pdf](https://github.com/TWUOnline/bug-tracking/files/4928425/VanBrummelen005.pdf)
[VanBrummelen006.pdf](https://github.com/TWUOnline/bug-tracking/files/4928426/VanBrummelen006.pdf)
[VanBrummelen007.pdf](https://github.com/TWUOnline/bug-tracking/files/4928427/VanBrummelen007.pdf)
[VanBrummelen008.pdf](https://github.com/TWUOnline/bug-tracking/files/4928428/VanBrummelen008.pdf)
[VanBrummelen009.pdf](https://github.com/TWUOnline/bug-tracking/files/4928429/VanBrummelen009.pdf)
[VanBrummelen010.pdf](https://github.com/TWUOnline/bug-tracking/files/4928430/VanBrummelen010.pdf)
[VanBrummelen011.pdf](https://github.com/TWUOnline/bug-tracking/files/4928431/VanBrummelen011.pdf)

**Comment by Jeff-TWU** [comment]
I can do this. Deadline?

**Comment by kmarjanovic** [comment]
Thanks Jeff!!  I don't think this course is scheduled yet.  Possibly September but more likely January.

**Comment by Jeff-TWU** [comment]
Sounds good. I'll add it to my busy list.

**Comment by kmarjanovic** [comment]
I forgot the Van Brummelen pages are for LDRS 623.  I've added the unit references for the rest of the pages.

**Comment by Jeff-TWU** [comment]
Uploaded the files to [https://github.com/TWUOnline/ldrs-master/tree/master/pages/10.624/Files](https://github.com/TWUOnline/ldrs-master/tree/master/pages/10.624/Files).
Think I did that right, please let me know otherwise.

**Comment by karenroeck** [comment]
@Jeff-TWU Thanks so much! I was able to put all the LDRS 624 files into the course. For some reason, the Van Brummelen PDF will not download for me - it is a file of 12 blank pages. No idea why. Could you please email that PDF to me directly?

**Comment by Jeff-TWU** [comment]
@karenroeck Sent. Also replaced the file. Don't know what happened there.
