### ISSUE TITLE
LDRS 620 FAR Centre MASTER

### ISSUE THREAD

**Issue by karenroeck** [TWUOnline/bug-tracking#342]
**Which course contains the bug?**  
LDRS 620 FAR Centre MASTER
 
**Describe the error and/or your suggestion**  
[] Units 2-5: In the Assessment tab, please create grey alerts for all Assignments (see Unit 1 Assessment tab for sample).
[] Units 3-5: Move Summary tab before Assessment and move all references to a new References tab (references are currently located at the end of Assessment tab - see Units 1-2 for sample).
  
**Location of the bug**  
1. URL:  https://learn.twu.ca/course/view.php?id=15710&section=1

**Comment by rezakh66** [comment]
@karenroeck These are done. Do we need icons in the reference list?

**Comment by karenroeck** [comment]
@rezakh66 no icons needed. thanks!
