### ISSUE TITLE
Link Broken

### ISSUE THREAD

**Issue by KarenAsenavage** [TWUOnline/bug-tracking#343]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 
 **LDRS664**
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 
 Video link to  Beatriz Escobar: Sense of Belonging (5 minutes) is broken.
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:   Beatriz Escobar: Sense of Belonging (5 minutes).
2. Unit #  2       Topic #     2    Activity#  3.2
 
**Optional: Screenshots**  
Firefox Can’t Open This Page
![image](https://user-images.githubusercontent.com/68361498/87619726-dbc52a00-c6ea-11ea-90f6-3746c37c61b5.png)

To protect your security, www.youtube.com will not allow Firefox to display the page if another site has embedded it. To see this page, you need to open it in a new window.
Video private

Karen Asenavage

**Comment by kmarjanovic** [comment]
Hi Karen,
I can't seem to find any replacement link.  I'll ask the course writer, Cathy, but for now will delete.

**Comment by kmarjanovic** [comment]
Hi Karen,
Cathy mentioned we can just remove the video, since the activity discussion references the literature.

Thanks again for letting us know about the bug!

**Comment by KarenAsenavage** [comment]
Thank you for following up!  Have a wonderful time with your family.  Karen
________________________________
