### ISSUE TITLE
LDRS 303 Button Problem

### ISSUE THREAD

**Issue by mellaurie** [TWUOnline/bug-tracking#344]
**Which course contains the bug?**  
- LDRS 303 FAR MASTER
 
 
**Describe the error and/or your suggestion**  
All the "Reflective Journal" blue buttons leads to a 404. 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
https://learn.twu.ca/course/view.php?id=10748&section=1
 All units, in the assessment section, very bottom
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
@mellaurie what section are those links in?  Unit assessments or in the units?

**Comment by mellaurie** [comment]
At the end of each unit except for Unit 6 (which doesn't have the Reflective Journal Assignment)

![Screenshot (69)_LI](https://user-images.githubusercontent.com/65783200/87697188-a3ebd000-c746-11ea-9d04-7d75b68c07f6.jpg)

**Comment by kmarjanovic** [comment]
Ah I see.  It's that same button issue.  @rezakh66 , could you please fix this?

I think this issue started when we switched to alerts, but those alerts were in the wrong folder, correct?  Now we put them in the main unit folder so we don't have this issue.

**Comment by rezakh66** [comment]
@kmarjanovic Hi Kelly, 
yes, assignments should be moved out of the assessment folder and go under the main unit folder. I will work on this today.

**Comment by rezakh66** [comment]
@kmarjanovic I have removed the reflective journal button. Also, I just noticed that we are having an old format of learning activities when they were not embedded in the topic itself. Do you want to change it to the new format?

**Comment by mellaurie** [comment]
@rezakh66 That is probably my fault for following an old format.  Can you show me what I should be doing tomorrow?

**Comment by kmarjanovic** [comment]
@mellaurie @rezakh66 

Let's leave the learning activities where they are.  Some courses need that extra chunking, so we separate them from the Topics.
