### ISSUE TITLE
SOCI 101 edits

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#346]
### URL
https://learn.twu.ca/course/view.php?id=10781
### Instructions

- [x] For all the Activity Checklists in the units, could you please unlink all hyperlinks?

@JessD9 could you add/fix the other items we discussed with Todd yesterday?

**Comment by Raulmelara** [comment]
@kmarjanovic Hyperlinks have been unlinked for Activity Checklist in the units

**Comment by kmarjanovic** [comment]
Thanks @Raulmelara !!
