### ISSUE TITLE
Production: LDRS 620 H5P

### ISSUE THREAD

**Issue by karenroeck** [TWUOnline/bug-tracking#347]
### Course
LDRS 620 FAR Centre MASTER

### URL
https://learn.twu.ca/course/view.php?id=15710&section=5

### Instructions
- [x] Please create an H5P fill in the blank activity in Activity 5.3

Please upload required files as attachments.

**Comment by Raulmelara** [comment]
@karenroeck I created a Fill in the blank H5P for Activity 5.3

**Comment by karenroeck** [comment]
@rezakh66 thank you!
