### ISSUE TITLE
LDRS 500 article links valid, but won't display

### ISSUE THREAD

**Issue by mellaurie** [TWUOnline/bug-tracking#348]
**Which course contains the bug?**  
- LDRS 500 Far Master
 
 
**Describe the error and/or your suggestion**  
The links to the Catalyst articles are good, but they are not working in Moodle. When you click on the link in Moodle, it tries to embed the website on the page.  I think it would work better if it could just open in a new tab (but I don't know the code for that). 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL: https://learn.twu.ca/course/view.php?id=10719&section=7 
2. Unit # 7        Topic #Learning Activities         Activity#  7.2
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
@mellaurie @rezakh66 
We just need to take out /chromeless:true/hidepagetitle:true from the url.

**Comment by Raulmelara** [comment]
@kmarjanovic @mellaurie chromeless:true/hidepagetitle:true has been removed

**Comment by kmarjanovic** [comment]
Thanks @Raulmelara ! (& welcome back! ;)
