### ISSUE TITLE
LDRS 620 - embed audio 

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#351]
### Course
https://learn.twu.ca/course/view.php?id=15710&section=4

Activity 4.4. - 2 interviews to fix formatting

### Instructions
I tried to embed the code for the audio - but it ended up messsing with the format of the rest of the activity.  Please help!

embed code: <iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/768573700&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/ray-klapwyk-307793991" title="From My Perch" target="_blank" style="color: #cccccc; text-decoration: none;">From My Perch</a> · <a href="https://soundcloud.com/ray-klapwyk-307793991/1-treuer-interview-preparation" title="200225 - 1 - Treuer Interview - Preparation" target="_blank" style="color: #cccccc; text-decoration: none;">200225 - 1 - Treuer Interview - Preparation</a></div>

location of code: https://soundcloud.com/ray-klapwyk-307793991/1-treuer-interview-preparation

**Comment by rezakh66** [comment]
@karenroeck Hi Karen, I embedded both audio files. Please change the second file title.

**Comment by karenroeck** [comment]
@rezakh66 It is not formatted quite correctly. Can we meet this afternoon to troubleshoot?

**Comment by rezakh66** [comment]
@karenroeck Sure, 3 pm works for you?

**Comment by karenroeck** [comment]
Yep sounds good. Just emailed you a Zoom invite.

**Comment by rezakh66** [comment]
@karenroeck Good Morning, I think embedded files are in their final form. transcripts are attached right below the interviews.

**Comment by kmarjanovic** [comment]
@rezakh66  that looks great!  What do you think, Karen?

**Comment by karenroeck** [comment]
@rezakh66 you are a star! Thank you! The only last change is to remove the soundcloud link at the top of each text file, since we have the files embedded directly in Moodle now. Then we can close off this bug. Thanks!

**Comment by rezakh66** [comment]
Thanks @karenroeck. I made the changes and removed all Soundcloud links in the transcript files.
