### ISSUE TITLE
LDRS 620 - image resolution

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#352]
### Course
LRS 620
### URL
https://learn.twu.ca/course/view.php?id=15710&section=1

### Instructions
For the chart in Topic 2, could we have a click to enlarge feature?
If not, @karenroeck could you provide a link/pdf to a chart with better resolution/bigger print?

**Comment by karenroeck** [comment]
Click to enlarge would be ideal - otherwise, here is the PDF: https://www.summit.org/wp-content/uploads/2016/08/10.05.2017-WVchart.pdf

**Comment by cmadland** [comment]
We had a plugin that worked to open images in a larger view, but it borked a different and more important plugin, so we ditched it. Linking to the download from Summit that Karen provided makes sense to me.

**Comment by kmarjanovic** [comment]
okay sounds good.

Could someone keep looking for a click to enlarge feature that works?  This is needed in some courses.

**Comment by karenroeck** [comment]
I think I figured something out - !!!!

https://learn.twu.ca/course/view.php?id=15710&section=1

**Comment by cmadland** [comment]
Interesting…I moved it to be a sub-item of unit 1.

Trouble is the page doesn’t have the ToC.

We might have to link to it instead in order to preserve the navigation…

**Comment by karenroeck** [comment]
Darn :( ok back to the death by download....


KAREN ROECK, MA, BEd

Instructional Designer | TWU GLOBAL

Trinity Western University | e. karen.roeck@twu.ca<mailto:karen.roeck@twu.ca>

twu.ca<http://www.twu.ca/>



[cid:image003.png@01D567BE.8201A250]<https://www.facebook.com/trinitywestern/>  [cid:image004.png@01D567BE.8201A250] <https://www.instagram.com/trinitywestern/>   [cid:image005.png@01D567BE.8201A250] <https://twitter.com/TrinityWestern>   [cid:image006.png@01D567BE.8201A250] <https://www.youtube.com/user/TrinityWesternU>   [cid:image007.png@01D567BE.8201A250] <https://www.linkedin.com/school/trinity-western-university/>



[cid:image001.png@01D5649E.C2C49090]


________________________________

**Comment by cmadland** [comment]
We can still have that page you created, just have it outside the ToC, then link from the spot it is supposed to be.

**Comment by karenroeck** [comment]
I'm not having any luck figuring this out.... @rezakh66 could you please take a look at this? https://learn.twu.ca/course/view.php?id=15710&section=1

We want to link a page.md in Topic 2 where it says "Click here to enlarge the image" but I can't get the title out of the sidebar or navigation buttons. See screenshots for what it looks like and what we want removed:


![Screen Shot 2020-07-27 at 11 54 01 AM](https://user-images.githubusercontent.com/67760065/88580470-7a615d00-d000-11ea-9592-10326da80952.png)
![Screen Shot 2020-07-27 at 11 55 26 AM](https://user-images.githubusercontent.com/67760065/88580473-7b928a00-d000-11ea-9db4-11aa71b46b57.png)

**Comment by karenroeck** [comment]
@rezakh66 We have the same issue in Unit 4, Topic 2 - I inserted a page to enlarge an image, and the word "Model" shows up in the sidebar and as a button:

https://learn.twu.ca/course/view.php?id=15710&section=4

**Comment by rezakh66** [comment]
@karenroeck I have removed them from the sidebar.

**Comment by karenroeck** [comment]
@rezakh66 thank you so much! Is there any way to remove the button at the bottom of the overview page? 
"Summit" for Unit 1: https://learn.twu.ca/course/view.php?id=15710&section=4
"Model" for Unit 4: https://learn.twu.ca/course/view.php?id=15710&section=4

**Comment by rezakh66** [comment]
@karenroeck I moved them to the last tab in the reference pages for now but I will check to see if we could get rid of them totally.
