### ISSUE TITLE
Facilitator's Guide (e.g. 591)

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#353]
### Course
LDRS 591 (& all other FAR courses)

### URL
https://github.com/TWUOnline/far-centre-guides/tree/master/pages/02.lead-ma/07.ldrs-591-scholarly-inquiry - GitHub - old 591 (nothing to use in there)

New Guide content: https://github.com/TWUOnline/ldrs-master/tree/master/pages/03.591/17.11-facilitators-guide

In Moodle: https://learn.twu.ca/course/view.php?id=8924&section=11

### Instructions

@rezakh66 can you add Heather's facilitator's guide to the new format Colin has suggested?

**Comment by rezakh66** [comment]
@kmarjanovic Hi Kelly, I have uploaded this with the new format. do you want this to be done for the rest of the facilitator's guide?

**Comment by kmarjanovic** [comment]
This is great!  Thanks @rezakh66 !!

As for the other guides - it would be great to have them in a Moodle tab for the ones starting in August (potentially):

| [LDRS 300 - Leadership Theory & Practice (FAR Master)](https://learn.twu.ca/course/view.php?id=10828)       |
| [LDRS 302 - Historical Concepts & Theories (FAR Master)](https://learn.twu.ca/course/view.php?id=10827)     |
| [LDRS 303 - Contemporary Leadership Approaches (FAR MASTER)](https://learn.twu.ca/course/view.php?id=10748) |
| [LDRS 410: Persuasion (FAR MASTER)](https://learn.twu.ca/course/view.php?id=10720)                                               |

| [PHIL210FAR](https://learn.twu.ca/course/view.php?id=8095)                                         |
| [MCOM 281: Public Speaking (FAR Centre MASTER)](https://learn.twu.ca/course/view.php?id=10713)                                    |
| [SOCI 101 - Introduction to Sociology (FAR Master)](https://learn.twu.ca/course/view.php?id=10781)                                           |
| [WRTG 101: Introduction to Writing (FAR Master)](https://learn.twu.ca/course/view.php?id=10769)                                              |
| [MCOM 221 - Digital Filmmaking (FAR Master)](https://learn.twu.ca/course/view.php?id=10829)        |
| [HIST 107 - World History to 1750 (FAR Master)](https://learn.twu.ca/course/view.php?id=10809)                                                |
| [PSYC 106: Intro to Psych (FAR Master)](https://learn.twu.ca/course/view.php?id=10885)             |

**Comment by rezakh66** [comment]
@kmarjanovic Sure, ill get them ready before August.

**Comment by rezakh66** [comment]
@kmarjanovic Hi Kelly, I have uploaded all these courses facilitation guide. However, it would be great if you send me the docx file for SOCI 101, and WRTG 101 as it seems some parts are missing.

**Comment by kmarjanovic** [comment]
Hi Reza,
I've attached the facilitator's guides below.  @JessD9 perhaps you can confirm with Shine whether there are any changes / updates to the FAR Centre version of WRTG 101?

Also - I've asked Todd to confirm the Facilitator's Guide Daniel created, but haven't heard feedback.  @JessD9 you may need to confirm that as well before it launches (whenever that is).

[WRTG-101-Facilitators-Guide.docx](https://github.com/TWUOnline/bug-tracking/files/4996519/WRTG-101-Facilitators-Guide.docx)
[Soc_101-Facilitator-Guide-DkS.docx](https://github.com/TWUOnline/bug-tracking/files/4996524/Soc_101-Facilitator-Guide-DkS.docx)

**Comment by JessD9** [comment]
@kmarjanovic yes, will confirm with Shine and Todd

**Comment by JessD9** [comment]
@rezakh66 waiting on response, will be in touch

**Comment by JessD9** [comment]
@rezakh66 We can keep the same wrtg 101 guide for now.

**Comment by karenroeck** [comment]
@JessD9 Any further updates needed on this card, or good to close?

**Comment by JessD9** [comment]
no updates from Todd re facilitator's guide...
@rezakh66 let's keep the same one for SOCI 101
