### ISSUE TITLE
LDRS 399

### ISSUE THREAD

**Issue by JessD9** [TWUOnline/bug-tracking#355]
### Instructions
@rezakh66 Please upload unit 1 to GiHub/Atom (may need to create 399 folder in github)

[LDRS_399_U1_July24_JD.docx](https://github.com/TWUOnline/bug-tracking/files/4971161/LDRS_399_U1_July24_JD.docx)

[LDRS_399_Journal.docx](https://github.com/TWUOnline/bug-tracking/files/4971126/LDRS_399_Journal.docx)

[Samples_of_Assignments_in_Leadership.docx](https://github.com/TWUOnline/bug-tracking/files/4971131/Samples_of_Assignments_in_Leadership.docx)

[Critical_Reading_Graphic_Organizer.docx](https://github.com/TWUOnline/bug-tracking/files/4971140/Critical_Reading_Graphic_Organizer.docx)

[Grading_Criteria_in_Graduate_Work.docx](https://github.com/TWUOnline/bug-tracking/files/4971159/Grading_Criteria_in_Graduate_Work.docx)

**Comment by rezakh66** [comment]
@JessD9 Hi Jessica, I have uploaded unit 1. a few notes: assessment section needs a lot of editing. activity 1.8 is between two assessments? and also MS videos are private. please grant me access then I can get them embedded.And please if you wanted to edit in Atom, edit in LDRS399reza. the other LDRS 399 folder is copied from another course with all its materials.we will rename the folder after Kelly confirms we can get rid of the other one.Thanks

**Comment by JessD9** [comment]
@rezakh66 I have shared the 4 videos with you via email. Can you move Activity 1.8 to Topic 2? (place it right after Activity 1.7). I think this makes it clearer. Do you think we need a separate Assessments tab where students can submit their assignments to the dropbox?

**Comment by JessD9** [comment]
Here is Unit 2: 
[LDRS_399_U2_July26_JD.docx](https://github.com/TWUOnline/bug-tracking/files/4979773/LDRS_399_U2_July26_JD.docx)

[PPT_Writing_persuasive_infographic.pptx](https://github.com/TWUOnline/bug-tracking/files/4979774/PPT_Writing_persuasive_infographic.pptx)

[Persuasive_Infographic_Rubric.docx](https://github.com/TWUOnline/bug-tracking/files/4979776/Persuasive_Infographic_Rubric.docx)

[Questions_for_Analyzing_an_Infographic.docx](https://github.com/TWUOnline/bug-tracking/files/4979791/Questions_for_Analyzing_an_Infographic.docx)

**Comment by rezakh66** [comment]
@JessD9 Hi Jessica, which email have you shared the videos with? I am still unable to access them via my @twu email. Assessments dropbox would be created within Moodle itself by the instructor of the course or Online learning team if they request. Here is the link oh how to create Assignment dropbox. http://create.twu.ca/help/moodle/faculty/activity-or-resource/creating-an-assignment-dropbox

**Comment by JessD9** [comment]
thanks Reza. I messaged you on Slack as well.

**Comment by rezakh66** [comment]
@JessD9 I have uploaded unit 2 and made the changes in unit 1. please let me know if anything else needs to be changed.

**Comment by rezakh66** [comment]
@JessD9 I have embedded MS videos in unit 1.

**Comment by JessD9** [comment]
Thank You!

**Comment by JessD9** [comment]
Here is Unit 3: 
*Please note:  SME wants Assignment Part 1 to remain between the Learning Activities (so please keep the same format as the document)
*You can place Assignments Parts 1 and 2 in red boxes. 

[LDRS_399_U3_July30_JD.docx](https://github.com/TWUOnline/bug-tracking/files/4998949/LDRS_399_U3_July30_JD.docx)

[Critical Analysis Assignment.docx](https://github.com/TWUOnline/bug-tracking/files/4998956/Critical.Analysis.Assignment.docx)

[Walk through a critical analysis.pptx](https://github.com/TWUOnline/bug-tracking/files/4998960/Walk.through.a.critical.analysis.pptx)

[Writing a gist summary.pptx](https://github.com/TWUOnline/bug-tracking/files/4998965/Writing.a.gist.summary.pptx)

[How to write a critical analysis.pptx](https://github.com/TWUOnline/bug-tracking/files/4998966/How.to.write.a.critical.analysis.pptx)

[Critical Reading Graphic Organizer.docx](https://github.com/TWUOnline/bug-tracking/files/4998975/Critical.Reading.Graphic.Organizer.docx)

[RUBRIC Critical Analysis.docx](https://github.com/TWUOnline/bug-tracking/files/4998979/RUBRIC.Critical.Analysis.docx)

**Comment by rezakh66** [comment]
Hi @JessD9 Unit 3 is uploaded. Please let me know if we need changes.

**Comment by JessD9** [comment]
@rezakh66 thanks Reza. Would you mind adding the course intro page? You can copy and paste the same introduction from ldrs 301: https://learn.twu.ca/course/view.php?id=15711

I'll change the wording later.

**Comment by JessD9** [comment]
Also, please embed the following into Activity 1.6 (after Grading Criteria for Graduate Work)

[Grading Criteria in Graduate Work.docx](https://github.com/TWUOnline/bug-tracking/files/5013445/Grading.Criteria.in.Graduate.Work.docx)

**Comment by JessD9** [comment]
Here is Unit 4: 

[LDRS_399_U4_July30_JD.docx](https://github.com/TWUOnline/bug-tracking/files/5013821/LDRS_399_U4_July30_JD.docx)

[Case_Study_Analysis_Assignment.docx](https://github.com/TWUOnline/bug-tracking/files/5013814/Case_Study_Analysis_Assignment.docx)

[A_Model_of_Virtuous_Leadership_in_Africa.docx](https://github.com/TWUOnline/bug-tracking/files/5013818/A_Model_of_Virtuous_Leadership_in_Africa.docx)

[Case_Study_Analysis_Rubric.docx](https://github.com/TWUOnline/bug-tracking/files/5013807/Case_Study_Analysis_Rubric.docx)

**Comment by rezakh66** [comment]
> @rezakh66 thanks Reza. Would you mind adding the course intro page? You can copy and paste the same introduction from ldrs 301: https://learn.twu.ca/course/view.php?id=15711
> 
> I'll change the wording later.

updated course intro page

**Comment by rezakh66** [comment]
@JessD9 Unit 4 is uploaded.

**Comment by JessD9** [comment]
Great, thank you. 
[LDRS_399_U4_July30_JD.docx](https://github.com/TWUOnline/bug-tracking/files/5026593/LDRS_399_U4_July30_JD.docx)

@Jeff-TWU @rezakh66 There's some colour-coded text on pages 3,4,8.
I'm guessing the only way to display this is via screenshot?

**Comment by JessD9** [comment]
Can you insert a screenshot of the chart on Page 7 as well?

**Comment by rezakh66** [comment]
@JessD9 Screenshots are added

**Comment by JessD9** [comment]
Perfect, thanks.

Please note, Unit 5 requires a screenshot of a section on page 7 ('Paragraph Structure", Point 1) 

"Paragraph Structure" should not be placed in a blue box, because it is not a Learning Activity (and the colour won't show up)

[LDRS399_ U5_AUG11_JD.docx](https://github.com/TWUOnline/bug-tracking/files/5059907/LDRS399_.U5_AUG11_JD.docx)

[Reflection _Rubric.docx](https://github.com/TWUOnline/bug-tracking/files/5059920/Reflection._Rubric.docx)

**Comment by rezakh66** [comment]
@JessD9 Hi Jessica, unit 5 is uploaded
