### ISSUE TITLE
LDRS 623 Media Request (H5P?)

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#359]
### Course
LDRS 623 

### URL
LDRS 623: https://learn.twu.ca/course/view.php?id=15687&section=5

### Instructions
Media Request: Activity 4.4: Ministry, School, or Personal? 
Can we look for an interactive option here (H5P?) so students can group the statements into categories?  Perhaps once the [WRSH 101 activity](https://github.com/TWUOnline/bug-tracking/issues/11) is created, we can follow that template?

**Comment by Jeff-TWU** [comment]
@cmadland Could I please get access to this?

**Comment by cmadland** [comment]
done

**Comment by kmarjanovic** [comment]
Note request on hold as course activities may be modified.  @karenroeck to confirm.
