### ISSUE TITLE
MCOM 281 - missing links

### ISSUE THREAD

**Issue by faitht1023** [TWUOnline/bug-tracking#36]
**Which course contains the bug?**  
MCOM 281: Public Speaking (FAR Centre MASTER)
 
 
**Describe the error and/or your suggestion**  
Missing links in these spots:

"Grading Criteria:
See the Demonstration Feedback and Evaluation rubric. **[link to document]**"

and 

"Refer to the Speeches guidelines for creating and delivering your speeches. **[link to document]**" 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=10713&section=7
2. Unit # 7      Topic #  Assessment       Activity#  
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
added pdfs
