### ISSUE TITLE
PHIL 210 FAR

### ISSUE THREAD

**Issue by mellaurie** [TWUOnline/bug-tracking#360]
**Which course contains the bug?**  
PHIL 210 FAR 
 
**Describe the error and/or your suggestion**  
Link to Ethics Committee pdf gives 404 code.  I updated the pdf and link, but it still doesn't work.  Not sure what I am missing.
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=8095&section=14
2. Assessment Tab, Ethics Committee Sub tab   
 
**Optional: Screenshots**

**Comment by karenroeck** [comment]
@mellaurie it is fixed now - I repasted the name of the PDF file (even though it was exactly the same as what you already had there) and it seemed to do the trick.

**Comment by mellaurie** [comment]
@karenroeck Thanks!  So weird.  That is what I did too.
