### ISSUE TITLE
LDRS 697 - Upload Units

### ISSUE THREAD

**Issue by karenroeck** [TWUOnline/bug-tracking#361]
### Course
LDRS 697

### Instructions
- [ ] Please upload Units 1-5 (there is a folder in Atom already, but no content).
- [ ] Please create a Moodle shell for LDRS 697 FAR Centre MASTER

Please upload required files as attachments.

[LDRS_697_Unit_1_July_27_KR.docx](https://github.com/TWUOnline/bug-tracking/files/4984054/LDRS_697_Unit_1_July_27_KR.docx)
[LDRS_697_Unit_2_July_27_KR.docx](https://github.com/TWUOnline/bug-tracking/files/4984055/LDRS_697_Unit_2_July_27_KR.docx)
[LDRS_697_Unit_3_July_27_KR.docx](https://github.com/TWUOnline/bug-tracking/files/4984056/LDRS_697_Unit_3_July_27_KR.docx)
[LDRS_697_Unit_4_July_27_KR.docx](https://github.com/TWUOnline/bug-tracking/files/4984057/LDRS_697_Unit_4_July_27_KR.docx)
[LDRS_697_Unit_5_July_27_KR.docx](https://github.com/TWUOnline/bug-tracking/files/4984058/LDRS_697_Unit_5_July_27_KR.docx)
[LDRS_697_Unit_6_July_31_KR.docx](https://github.com/TWUOnline/bug-tracking/files/5008400/LDRS_697_Unit_6_July_31_KR.docx)

**Comment by karenroeck** [comment]
@rezakh66 I have uploaded LDRS 591 Units 1-6. Please upload them to Atom and create a Moodle shell when you have time. Thanks!

**Comment by rezakh66** [comment]
@karenroeck Hi,units 1-6 are available [here](https://learn.twu.ca/course/view.php?id=15767&section=2)

**Comment by karenroeck** [comment]
Thanks so much @rezakh66!
