### ISSUE TITLE
LDRS 620 - assignment rubrics

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#363]
### Course
LDRS 620
### URL
https://learn.twu.ca/course/view.php?id=15710&section=7

### Instructions
@karenroeck 
Could we enlarge the rubrics a bit in the Assessments section?   The print is too small.  We can either enlarge the screenshot - or it might be better to build it in grav, or even Moodle.

See Mel's [rubric example](https://learn.twu.ca/course/view.php?id=8189&section=12) in the Sandbox.

See html below - @rezakh66 @cmadland - could we discuss a rubric template at our design meeting?  It would be good to have a standard code to use, or some samples in grav that can be easily modified. (integrate into our word doc templates?)

<table style="margin-left: auto; margin-right: auto;" border="2" cellpadding="5">
<tbody>
<tr>
<td></td>
<td>
<p style="text-align: center;"><strong> UNSATISFACTORY <br />0% </strong></p>
</td>
<td>
<p style="text-align: center;"><strong> DEVELOPING <br />50% (C) </strong></p>
</td>
<td bgcolor="#B9D3EE">
<p style="text-align: center;"><strong> PROFICIENT <br />75% (B) </strong></p>
</td>
<td>
<p style="text-align: center;"><strong> EXEMPLARY <br />100% (A) </strong></p>
</td>
</tr>
<tr>
<td>
<p style="text-align: left;"><strong> INTRODUCTION (10%) </strong></p>
</td>
<td style="padding: 10px;">Does not includes an introduction to the practicum portfolio. Does not list the practicum learning outcomes.</td>
<td style="padding: 10px;">Includes an introduction to the practicum portfolio or lists some or none of the practicum learning outcomes.</td>
<td bgcolor="#B9D3EE" style="padding: 10px;"><em> Includes an introduction to the practicum portfolio. Lists each of the practicum learning outcomes. </em></td>
<td style="padding: 10px;">Includes an introduction to the practicum portfolio, Gibb’s (1988) Reflective Practice Model. Lists each of the practicum learning outcomes, and includes an explanation of how specific elements of the portfolio demonstrate achievement of learning outcomes.</td>
</tr>
<tr>
<td>
<p style="text-align: left;"><strong> DESCRIPTION (15%) </strong></p>
</td>
<td style="padding: 10px;">Does not include a description of the practicum experience. <br /><br />Does not include Classroom Observation Log, Facilitation Log, and/or Verification of Hours. (Note: These are all required to pass the Practicum). <br /><br />Does not includes three Lesson Plans.</td>
<td style="padding: 10px;">Does not include a description of the practicum experience. <br /><br /> Includes some, but not all of the following: Classroom Observation Log, Facilitation Log, and/or Verification of Hours. (Note: These are all required to pass the Practicum). <br /><br /> Does not include all three Lesson Plans.</td>
<td bgcolor="#B9D3EE" style="padding: 10px;"><em> Includes a description of the practicum experience. <br /><br /> Includes all of the following: Classroom Observation Log, Facilitation Log, and Verification of Hours. (Note: These are all required to pass the Practicum). <br /><br /> Includes three Lesson Plans. </em></td>
<td style="padding: 10px;">Includes an insightful description of the practicum experience, integrating scholarly sources to support description. <br /><br /> Includes all of the following: Classroom Observation Log, Facilitation Log, and Verification of Hours. (Note: These are all required to pass the Practicum). <br /><br /> Includes three Lesson Plans</td>
</tr>
</tbody>
</table>

**Comment by karenroeck** [comment]
Sure would love some help with this. The larger PDF version of the rubric is already hyperlinked. The displayed jpg is 2.13 MB and 4200x2550 - would be great to get it to display larger somehow.

**Comment by rezakh66** [comment]
@karenroeck Hi,
I have made it 20% wider but then students need to scroll horizontally to be able to see the text. Let me know if you think the earlier version would be better.

**Comment by karenroeck** [comment]
Thanks @rezakh66 - it is still quite small :( Is there any way to get the actual image to show up larger? There is a lot of white space around the image itself...could you please try cropping it and reuploading?
