### ISSUE TITLE
Psych 106 - Extra Navigation Button

### ISSUE THREAD

**Issue by dgaudet48** [TWUOnline/bug-tracking#364]
**Which course contains the bug?**  

Psyc106 Dev 2
 
 
**Describe the error and/or your suggestion**  
On the Unit 4 Assessment tab there is an extra link "Writing Assignment 1" that should not be there. I am not sure why, but I cannot get rid of it. 
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=13547&section=4
2. Unit #4         Topic #  Assessment      
 
**Optional: Screenshots**

**Comment by rezakh66** [comment]
@dgaudet48 Hi, I have removed that.
