### ISSUE TITLE
WRSH 101 interactive map

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#366]
### Course
WRSH 101
### URL
https://learn.twu.ca/course/view.php?id=10744&section=4
### Instructions

Unit 4 - Topic 2: Christian Worship During the Reformation (1511) until the 1960’s
[Put bullet points on an interactive map]  

o	The Lutheran church, following Martin Luther, took hold mainly in Germany and Scandinavia. 
o	John Calvin’s reform movement started in Geneva, Switzerland, but later became centered in the Netherlands where it was called the Reformed church. 
o	The Calvinist branch also took hold in Scotland (through John Knox) where it was named Presbyterian.
o	In England King Henry 8th instituted a break from the Roman Catholic Church, declaring it instead the Anglican Church. Since his reasons were partly political and personal rather than theological, little changed in some places except for the name. As White indicates in his chart on p. 107, Lutheranism and Anglicanism stayed the closest to the Roman Catholic practice and traditions. 
o	Many of these churches eventually became state-sponsored churches, which created other problems such as nominalism (belonging in name only). For example, all infants would be automatically baptized whether there was living faith in the family or not. It was simply a tradition, a rite of passage. 
o	Christians in Britain who wanted the Reformation to go further than Anglicanism, started a free church movement and were called the Puritans. They rejected most forms of worship inherited from the Roman Catholic tradition. In some ways they were more closely aligned with a Calvinist Reformed church. Puritans held political power for about 15 years, but when their reform eventually failed and they were being persecuted, the Puritan movement transplanted to North America to begin anew.

**Comment by karenroeck** [comment]
@mellaurie I created an interactive map - check it out and let me know what you think. https://learn.twu.ca/course/view.php?id=10744&section=4

**Comment by Jeff-TWU** [comment]
Nice job @karenroeck! I think it works well.  The one thing I would suggest is maybe changing the pin icon to not be a caution sign, and maybe making it a little smaller. If you choose to go that route and would like some help, let me know.

**Comment by karenroeck** [comment]
@Jeff-TWU Brilliant - thanks for the tip. I updated the pin to an Info sign, but I can't get it to show smaller. Could you take a look at that when you get a chance?

**Comment by Jeff-TWU** [comment]
@karenroeck sure thing. Yeah, it's weird. It's making the icon's much larger once embedded as opposed to on Wordpress. I'll see if can replacing them with uploaded images instead of predefined icons would change how the CSS is acting.
<img width="350" alt="map icons" src="https://user-images.githubusercontent.com/66963480/89808768-7bf64f00-daef-11ea-8bb9-97227f799f80.png">

**Comment by karenroeck** [comment]
@Jeff-TWU Cool thanks!

**Comment by Jeff-TWU** [comment]
@karenroeck I attempted to replace with images, and it didn't make a difference. Looked into the CSS and it's scaling based on screen size, so it's probably a better idea to just let it do its thing. Changing the icon is an improvement.

**Comment by karenroeck** [comment]
@Jeff-TWU Ah, too bad. Thanks for looking into those changes!
