### ISSUE TITLE
LDRS 624 - Unit Assessment alerts

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#369]
### Course
LDRS 624
### URL
https://learn.twu.ca/course/view.php?id=15704&section=1
### Instructions
Please put the Assessments from each Unit into an alert (see [LDRS 623 example](https://learn.twu.ca/course/view.php?id=15687&section=1))

**Comment by rezakh66** [comment]
@kmarjanovic I have added secondary alert to the assessment section.

**Comment by kmarjanovic** [comment]
Thank you @rezakh66 !
