### ISSUE TITLE
 LDRS664

### ISSUE THREAD

**Issue by KarenAsenavage** [TWUOnline/bug-tracking#373]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 
 LDRS664 OL Karen Asenavage
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 
 Broken Link to Video
The Six Adult Learning Principles.

**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=13691&section=9
2. Unit #   8      Topic #  1       Activity#  8.1
 
**Optional: Screenshots**

**Comment by karenroeck** [comment]
Hi @KarenAsenavage I checked the link and it is working from my end - could you please take a look again and let me know if it opens for you?
