### ISSUE TITLE
LDRS664 OL Asenavage

### ISSUE THREAD

**Issue by KarenAsenavage** [TWUOnline/bug-tracking#374]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 LDRS664 OL Asenavage
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 The artivle does not open to a full PDF
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://www.semanticscholar.org/paper/Workplace-%E2%80%98-learning-%E2%80%99-and-adult-education-Fenwick/dd220d93e5e07aea232ec87a1ae237bf7ea4b76a?p2df
2. Unit #    8     Topic #     1    Activity#  8.2
 
**Optional: Screenshots**

**Comment by karenroeck** [comment]
@KarenAsenavage this has been fixed - please take a look and confirm.

**Comment by KarenAsenavage** [comment]
Thank you.  I will check and get back to you.  Karen
________________________________
