### ISSUE TITLE
LDRS 667 Practicum: Add Lesson Plan Template to Discussion Tab

### ISSUE THREAD

**Issue by cpenfoldnavarro** [TWUOnline/bug-tracking#375]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 LDRS 667 Practicum (Summer 2020) Please add to MASTER as well.
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
Please add the Lesson Plan Template to the Discussion Page in the Assignment Tab.

Under Reflective Practice Discussions 5, 6, and 7: Designing Learning Experiences, each section should include a link to the Lesson Plan Template. (This is already found in the Unit 3 Assessment tab.

The link should be immediately following this sentence, in all three sections: Lesson Plan 1, 2, and 3:
Post your draft Lesson Plan in a discussion post for feedback from your instructor and other learners. You may also share with your practicum supervisor, as appropriate. 
Lesson Plan Template (link)
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=15526&section=10
2. Unit #   Assignments  Topic #   Discussions      Activity#  
[Lesson Plan Template.docx](https://github.com/TWUOnline/bug-tracking/files/5029005/Lesson.Plan.Template.docx)
     
 
**Optional: Screenshots**

**Comment by karenroeck** [comment]
@cpenfoldnavarro I've updated the Discussions section with the Lesson Plan Template x 3 - please take a look and let me know if this is what you were hoping for.

**Comment by cpenfoldnavarro** [comment]
Karen,
Thanks so much! It’s in the right place for the first lesson plan section, but it is in a different location (after the italicized text) in the other two sections. Could you make all three look like this?

Post your draft Lesson Plan in a discussion post for feedback from your instructor and other learners. You may also share with your practicum supervisor, as appropriate.
Lesson Plan Template (link<https://far.twu.ca/ldrs/667/assignments/assignment-1/Lesson.Plan.Template.docx>)
Provide feedback to two other learners on their learning outcomes, learning activity, and/or assessments tools. Also, provide helpful input on their inclusion of adult learning theory and/or community of learning principle.
I was also hoping that the learners would simply be able to click on “Lesson Plan Template” … the word link would not be there, but the words “Lesson Plan Template” would contain a hyperlink. Does that make sense?

Thanks again!
Cathy

CATHARINE PENFOLD NAVARRO, PhD
Part-Time Instructor, MA Leadership | TWU GLOBAL
Trinity Western University | e. c.penfoldnavarro@twu.ca<mailto:c.penfoldnavarro@twu.ca>

twu.ca<http://www.twu.ca/>

[cid:image001.png@01D56D6B.9FBB05E0]

**Comment by karenroeck** [comment]
@cpenfoldnavarro Yes makes total sense - should be good to go now!

**Comment by cpenfoldnavarro** [comment]
Perfect! Thanks ☺

CATHARINE PENFOLD NAVARRO, PhD
Part-Time Instructor, MA Leadership | TWU GLOBAL
Trinity Western University | e. c.penfoldnavarro@twu.ca<mailto:c.penfoldnavarro@twu.ca>

twu.ca<http://www.twu.ca/>

[cid:image001.png@01D56D6B.9FBB05E0]
