### ISSUE TITLE
LDRS 697 revisions

### ISSUE THREAD

**Issue by karenroeck** [TWUOnline/bug-tracking#376]
**Which course contains the bug?**  
LDRS 667 FAR Centre MASTER
 
**Describe the error and/or your suggestion**  
- [ ] Course Introduction tab: Need the course description, themes, syllabus, etc.
- [ ] Unit 5, Topic 1, Activity 2.1: The video was starting at 56 seconds. I changed the URL to start from the beginning, but let me know if you wanted it to start at 56 seconds and I will change it back.
- [ ] Unit 5, Topic 3, Activity 2.3: Should we link the Leadership Competency Worksheets as downloadable PDF files instead of a Google Doc? Just thinking of international students who may not be able to access Google. Also - we should space out the pages so each competency is on its own page vs splitting pages between competencies.
- [ ] Unit 7, Topic 2, Activity 4.5: Need a link of an action research literature review introduction.
- [ ] Unit 7, Topic 2, Activity 4.5: The links for article review, synthesized information, and summary/template example all go to the same Google Doc. Should these be different?
- [ ] Unit 8, Assessment: Need a rubric for Assignment 3 (also add to Assessments tab)
- [ ] Unit 9, Topic 2, Activity 6.2: Is the link for “Information and Consent Letters Templates” correct? I found it on the TWU website.
- [ ] Unit 9, Assessment: The four ethical issues under the Discussion Post and Response differs slightly from the four ethical issues listed in Activity 6.4. Are they supposed to be the same?
- [ ] Unit 9, Assessment: Need to add details re: ethics application (also add to Assessments tab)
- [ ] Assessments tab: Need to add percentages for graded assignments.
  
**Please provide a specific link to the page with the error, as well as where the error is on the page:**
URL:  https://learn.twu.ca/course/view.php?id=15767&section=0

**Comment by karenroeck** [comment]
@HeatherStrong11 I created this checklist for us to keep track of revision progress on LDRS 697 when you have time.

**Comment by HeatherStrong11** [comment]
@karenroeck Thanks Karen!  This is great.
