### ISSUE TITLE
RELS 100 Moodle/Atom

### ISSUE THREAD

**Issue by karenroeck** [TWUOnline/bug-tracking#377]
### Course
RELS 100

### Instructions
- [x] Create a RELS 100 course in the rels-master repository
- [x] Create a RELS 100 Master shell in Moodle and link all units from Atom

**Comment by rezakh66** [comment]
@karenroeck Hi Karen, RELS100 is available [here](https://learn.twu.ca/course/view.php?id=15768&section=5).

**Comment by karenroeck** [comment]
Thank you @rezakh66! I forgot to mention to please call this OL MASTER instead of FAR MASTER. Could you make the switch?

**Comment by rezakh66** [comment]
@karenroeck Hi Karen,
I changed the name.

**Comment by karenroeck** [comment]
@rezakh66 Perfect thanks!
