### ISSUE TITLE
LDRS 623 sidebar

### ISSUE THREAD

**Issue by karenroeck** [TWUOnline/bug-tracking#378]
**Which course contains the bug?**  
LDRS 623 FAR MASTER 
 
**Describe the error and/or your suggestion**  
In Unit 1, please remove the title "Journal" from the sidebar.
 
 
**Location of the bug**  
1. URL:  https://learn.twu.ca/course/view.php?id=15687&section=1
2. Unit #1 
 
**Optional: Screenshots**  
![Screen Shot 2020-08-06 at 9 40 21 AM](https://user-images.githubusercontent.com/67760065/89558406-09246580-d7c9-11ea-86f0-a85186ead1d2.png)

**Comment by karenroeck** [comment]
@rezakh66 please take a look at this when you get a chance. Thanks!

**Comment by rezakh66** [comment]
@karenroeck Are you using Journal page anywhere within the unit 1? I can't find where its being used

**Comment by karenroeck** [comment]
@rezakh66 yes - Unit 1, Topic 1, Activity 1.1

![Screen Shot 2020-08-06 at 12 51 27 PM](https://user-images.githubusercontent.com/67760065/89576066-907ed280-d7e3-11ea-8a18-f78a56ec6a2f.png)

**Comment by rezakh66** [comment]
@karenroeck Hi, I removed the journal from the sidebar. It only appears at the bottom of the page in the assessment section

**Comment by karenroeck** [comment]
@rezakh66 Thanks! I guess that button can't be removed...? If not, we can live with it 👍
