### ISSUE TITLE
LDRS 623 H5P

### ISSUE THREAD

**Issue by karenroeck** [TWUOnline/bug-tracking#379]
### Course
LDRS 623 FAR Centre MASTER

### Instructions
Please create a drag and drop activity like you did for "[Worshipping](https://create.twu.ca/h5p/wp-admin/admin.php?page=h5p&task=show&id=104)". The three categories are: Ministry component; School component; Personal component. Answers are indicated in bold - some statements have more than one answer.

1) Classify local plants and animals into groups on the basis of visible characteristics, adaptations for survival, such as claws, beaks and prickles. **(Ministry)**

2) McMillan Farm visit (Pumpkin art, Pumpkin carving, estimating seeds and counting seeds). **(School)** **(Personal)**

3) Teacher observations and records as well as student-generated products may be included in the portfolio. **(Ministry)**

4) Pet Day: Have students bring pets for show and tell. **(School)** **(Personal)**

5) Students self-mark and correct homework. **(School)** **(Personal)**

6) Students demonstrate an understanding of relations and functions in Math. **(Ministry)**

7) Students will learn through questioning and observations during experiments, that there is order and wisdom in what God created and why. **(Ministry)** **(School)**

8) God gave us the ability to hear and to create sound (Make a joyful noise unto the Lord, all ye lands. -Psalm 100:1). **(School)**

9) We have a responsibility to care for God’s world. **(School)** **(Personal)**

10) Favourite animal research project (appearance, food, habitat, babies, enemies, endangered etc). **(Ministry)**

**Comment by Jeff-TWU** [comment]
@karenroeck [Here you go!](https://create.twu.ca/h5p/wp-admin/admin.php?page=h5p&task=show&id=114)

**Comment by karenroeck** [comment]
@Jeff-TWU 🙌  this looks awesome! One tweak - could you adjust the dotted circles to have two circles if there are two answers but only one if there is one answer? In the way it is now, some students might think all categories have two answers. Thanks!

**Comment by Jeff-TWU** [comment]
Sure. Makes sense. [Updated](https://create.twu.ca/h5p/wp-admin/admin.php?page=h5p&task=show&id=114).

**Comment by karenroeck** [comment]
Awesome - love this! Thanks again.

**Comment by Jeff-TWU** [comment]
Welcome!
