### ISSUE TITLE
PHIL 105 Production

### ISSUE THREAD

**Issue by mellaurie** [TWUOnline/bug-tracking#380]
### 

### Instructions @rezakh66 
- [x] Create a PHIL 105 course in the arts-master repository
- [x] Please create Moodle shell 
- [x] put home and unit 1 in 

[PHIL 105_U1_Aug6_ML.docx](https://github.com/TWUOnline/bug-tracking/files/5043372/PHIL.105_U1_Aug6_ML.docx)

[PHIL 105 Home_Aug7_ML.docx](https://github.com/TWUOnline/bug-tracking/files/5044069/PHIL.105.Home_Aug7_ML.docx)

Please let me know if there are any issues or oversights.  Thanks!

**Comment by rezakh66** [comment]
@mellaurie Good Morning, Here is [unit 1](https://learn.twu.ca/course/view.php?id=15769&section=1).

**Comment by mellaurie** [comment]
Thanks so much Reza!!

**Comment by mellaurie** [comment]
Can I have help with the following formatting things?
- Course schedule table headings should be Week, Topic, Readings
-  all the video links embedded
- add horizontal lines between activities in the checklist

**Comment by rezakh66** [comment]
Hi @mellaurie I have made the changes. Let me know If you want to add Icons for watching video activities and activities checklist

**Comment by mellaurie** [comment]
Thanks @rezakh66!  Yes, please also add in the icons for the activities.  Will the icon :fa-comments-o: for the discuss activities?

Also, I know there is a long history about the way tables look in html and all, but could you see if you can make the course schedule look nicer and easier to read?

**Comment by rezakh66** [comment]
@mellaurie I have made the changes and updated the table. please let me know your thoughts

**Comment by mellaurie** [comment]
Thank you @rezakh66, the table looks much better.

Can you Unit 2 and 3 with the same formatting as mentioned above?
[PHIL 105_U2_Aug14_ML.docx](https://github.com/TWUOnline/bug-tracking/files/5077390/PHIL.105_U2_Aug14_ML.docx)
[PHIL 105_U3_Aug14_ML.docx](https://github.com/TWUOnline/bug-tracking/files/5077391/PHIL.105_U3_Aug14_ML.docx)

**Comment by mellaurie** [comment]
I have more units ready for you (@rezakh66 )

[PHIL 105_U7_aug18_ML.docx](https://github.com/TWUOnline/bug-tracking/files/5104968/PHIL.105_U7_aug18_ML.docx)
[PHIL 105_U8_Aug18_ML.docx](https://github.com/TWUOnline/bug-tracking/files/5104969/PHIL.105_U8_Aug18_ML.docx)
[PHIL 105_U9_aug18_ML.docx](https://github.com/TWUOnline/bug-tracking/files/5104970/PHIL.105_U9_aug18_ML.docx)

Thanks in advance!!

**Comment by rezakh66** [comment]
@kmathews1 Hi Mathew, are you working on phil 105 as well? I think we have overlapped each other's changes.:). I can work units 5-9 and you work on units 2-5. is that ok?

**Comment by kmathews1** [comment]
@rezakh66 Hi, No I'm not working Phil 105.

**Comment by mellaurie** [comment]
Could we please have all units formatted:
- [ ] all the video links embedded
- [ ] icons added to alerts (see Activity checklist 1)
- [ ] fix the formatting of the check marks in any of the alerts (usually in the assessment)

**Comment by rezakh66** [comment]
@JessD9 Unit 6 is uploaded and videos are embedded.

**Comment by mellaurie** [comment]
Thanks for all the work you are doing @rezakh66!!

Here are the rest of the units ready to go in:
[PHIL 105_U10_Aug24_ML.docx](https://github.com/TWUOnline/bug-tracking/files/5132855/PHIL.105_U10_Aug24_ML.docx)
[PHIL 105_U11_aug25_ML.docx](https://github.com/TWUOnline/bug-tracking/files/5132856/PHIL.105_U11_aug25_ML.docx)
[PHIL 105_U12_aug25_ML.docx](https://github.com/TWUOnline/bug-tracking/files/5132857/PHIL.105_U12_aug25_ML.docx)
[PHIL 105_U13_aug25_ML.docx](https://github.com/TWUOnline/bug-tracking/files/5132858/PHIL.105_U13_aug25_ML.docx)

**Comment by mellaurie** [comment]
In each unit assessment section, the self-quizzes have questions from the text.  Can we add these pdfs (labeled according to textbook chapter, not course units) as links?  

See [Unit 1](https://learn.twu.ca/course/view.php?id=15769&section=3) for example.

[PHIL_105_Self-Quizzes.zip](https://github.com/TWUOnline/bug-tracking/files/5133047/PHIL_105_Self-Quizzes.zip)

**Comment by rezakh66** [comment]
Hi @mellaurie, All units and self-quizzes are uploaded.

**Comment by mellaurie** [comment]
Amazing @rezakh66!

Can you go through and double check that the right pdf chapters match up to the self quizzes?  I noticed that in Unit 11 and Unit 13, the chapters don't line up.

Thanks!

**Comment by rezakh66** [comment]
@mellaurie I double-checked them and all seem to be in the right folder.

**Comment by mellaurie** [comment]
Thanks so much @rezakh66!!

**Comment by mellaurie** [comment]
More to format/add: (sorry! @rezakh66 and TIA!)

- In each unit alert titled: Apply and Explore the Ideas (usually the u.2 and u.5), please link to the pdf for that self quiz.  See unit 1 and 2 for examples. 

- When a JTA chapter is referenced, can we hyperlink it to the corresponding chapter in the online text.  Usually in activity n.3 and n.6 and in the assessment section.  Attached doc has all the links.
[JTA Links.docx](https://github.com/TWUOnline/bug-tracking/files/5176088/JTA.Links.docx)
