### ISSUE TITLE
PSYC ADC course template in Atom

### ISSUE THREAD

**Issue by karenroeck** [TWUOnline/bug-tracking#382]
### Course
All PSYC ADC courses

### Instructions
Please create a new course template in Atom for upcoming PSYC ADC courses. We need the following folders:
- [x] Course Introduction
- [x] Unit 1
- [x] Unit 2
- [x] Unit 3
- [x] Unit 4
- [x] Unit 5
- [x] Unit 6
- [x] Assessment
- [x] Course Café

**Comment by rezakh66** [comment]
@karenroeck Hi Karen, Please check what I have created for[ PSYC106(ADC Master)](https://learn.twu.ca/course/view.php?id=15775&section=1), if that's how you want that, i can do the same for PSYC 215 & 340

**Comment by karenroeck** [comment]
@rezakh66 Looks great! One question about the Activity Checklist in each Unit overview - is this an old template? I haven't worked with the dropdown boxes in my other courses. Also - could you load the [Course Café content](https://learn.twu.ca/course/view.php?id=10828&section=19) into each ADC Master?
