### ISSUE TITLE
Psych 105 - Extra Button on Page

### ISSUE THREAD

**Issue by dgaudet48** [TWUOnline/bug-tracking#386]
**Which course contains the bug?**  
- Psych 105 - Dev
 
 
**Describe the error and/or your suggestion**  
There is an extra button "Writing Assignment #2" appearing at the bottom of the screen - it needs to be removed. 
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=15666&section=11
2. Unit #   9      Topic #    "Assessment "    
 
**Optional: Screenshots**

**Comment by karenroeck** [comment]
@dgaudet48 It's all gone 👍
