### ISSUE TITLE
LDRS 664 Facilitator's Guide

### ISSUE THREAD

**Issue by karenroeck** [TWUOnline/bug-tracking#387]
### Course
LDRS 664: Creating Authentic Learning Communities

### URL
https://learn.twu.ca/course/view.php?id=8884

### Instructions
- [x] Please add the Facilitator's Guide to the Master course

Please upload required files as attachments.
[LDRS 664 Facilitator's Guide .docx](https://github.com/TWUOnline/bug-tracking/files/5070685/LDRS.664.Facilitator.s.Guide.docx)

**Comment by rezakh66** [comment]
Hi, @karenroeck I have uploaded the facilitator's guide. The course overview section is empty though. Do you want to keep that section or I should remove that?

**Comment by karenroeck** [comment]
@rezakh66 I added a blurb in the course overview section. Thanks!
