### ISSUE TITLE
LDRS 697 production

### ISSUE THREAD

**Issue by karenroeck** [TWUOnline/bug-tracking#388]
### Course
LDRS 697: Leadership Integration Project

### URL
https://learn.twu.ca/course/view.php?id=15767

### Instructions
- [x] Please upload Units 7-10 in Atom

[LDRS_697_Unit_7_Aug_13_KR.docx](https://github.com/TWUOnline/bug-tracking/files/5071952/LDRS_697_Unit_7_Aug_13_KR.docx)
[LDRS_697_Unit_8_Aug_13_KR.docx](https://github.com/TWUOnline/bug-tracking/files/5071954/LDRS_697_Unit_8_Aug_13_KR.docx)
[LDRS_697_Unit_9_Aug_13_KR.docx](https://github.com/TWUOnline/bug-tracking/files/5071955/LDRS_697_Unit_9_Aug_13_KR.docx)
[LDRS_697_Unit_10_Aug_13_KR.docx](https://github.com/TWUOnline/bug-tracking/files/5071956/LDRS_697_Unit_10_Aug_13_KR.docx)

**Comment by rezakh66** [comment]
@karenroeck Hi Karen, Can you please check unit 8 pictures from page 8 afterward. they are not loaded in the file here. maybe you can send me by email?

**Comment by karenroeck** [comment]
@rezakh66 That is so bizarre! The pictures disappeared from my end as well. I had to go back a few drafts to find them. Just emailed them to you.

**Comment by rezakh66** [comment]
Hi @karenroeck I have uploaded up to unit 10. Let me know if changes are needed.

**Comment by rezakh66** [comment]
Hi @karenroeck I have uploaded up to unit 10. Let me know if changes are needed.

**Comment by karenroeck** [comment]
@rezakh66 These look great - thanks so much!
