### ISSUE TITLE
MCOM 281 - broken link (404 not found)

### ISSUE THREAD

**Issue by faitht1023** [TWUOnline/bug-tracking#39]
**Which course contains the bug?**  
MCOM 281
 
 
**Describe the error and/or your suggestion**  
The word "here" has been hyperlinked, but the link leads to a 404 not found page.

"The syllabus includes key information about the course schedule, assignments, and policies. Please read the full course syllabus **here**. "
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL: https://learn.twu.ca/course/view.php?id=10713&section=0
2. Unit # Course Introduction
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
Please add this:
[MCOM_281_Syllabus_Fall_2019.docx](https://github.com/TWUOnline/bug-tracking/files/3693848/MCOM_281_Syllabus_Fall_2019.docx)
