### ISSUE TITLE
WRTG 101 (Bundle Master)

### ISSUE THREAD

**Issue by JessD9** [TWUOnline/bug-tracking#390]
### Instructions
@rezakh66 Create WRTG 101 folder in github
**This is different from the FAR Master version (do not delete FAR Master)

-format Course Introduction page. You can copy the same introduction from here: 
https://learn.twu.ca/course/view.php?id=15711&section=0 
I will reword later.

**Comment by JessD9** [comment]
@rezakh66 Can you upload Module 2? 
[WRTG 101_M2_Aug 12_final.DOCX](https://github.com/TWUOnline/bug-tracking/files/5115779/WRTG.101_M2_Aug.12_final.DOCX)

**Comment by rezakh66** [comment]
@JessD9 Hi, I uploaded Module 2 with the same format as Module1. let me know if you decided to change the activities checklist.

**Comment by JessD9** [comment]
@rezakh66 Thank you Reza. Please move the "Summary" tab before/above "Assessment"

And in the Assessment chart, the "Module 2" title/header is not showing up

**Comment by cmadland** [comment]
Is M3 ready for production? Or am I misunderstanding what you need? @JessD9

**Comment by JessD9** [comment]
Yes, it's ready. 
[WRTG 101_M3_Aug 12_final.docx](https://github.com/TWUOnline/bug-tracking/files/5131224/WRTG.101_M3_Aug.12_final.docx)

**Comment by JessD9** [comment]
@rezakh66 Hey Reza, do have some time? Are you able to embed module 3? (don't worry about formatting, I will fix this later)

**Comment by rezakh66** [comment]
Hi @JessD9 Module 3 is uploaded.

**Comment by cmadland** [comment]
@rezakh66 @JessD9 I did a bit of formatting in M3

**Comment by JessD9** [comment]
@rezakh66 @cmadland Great, thank you!

**Comment by JessD9** [comment]
@rezakh66 I've started uploading unit 4, but need help formatting the checklist (pages 3-5).
[WRTG 101_M4_Aug 12_final.docx](https://github.com/TWUOnline/bug-tracking/files/5143836/WRTG.101_M4_Aug.12_final.docx)

**Comment by rezakh66** [comment]
@JessD9 I uploaded the checklist

**Comment by JessD9** [comment]
@rezakh66 Here's the unit 5 checklist
[wrtg101U5.docx](https://github.com/TWUOnline/bug-tracking/files/5152540/wrtg101U5.docx)

**Comment by JessD9** [comment]
@rezakh66 Can you format checklists in units 2-4, so they match the format of Unit 1 checklist?
(White border at top)

**Comment by rezakh66** [comment]
@JessD9 I updated checklist with the white border at the top

**Comment by JessD9** [comment]
Thanks;)

**Comment by JessD9** [comment]
@rezakh66 the words aren't showing up in the table headings (units 2 and 4)... that's strange.
I'll try to reformat

**Comment by JessD9** [comment]
done!

**Comment by karenroeck** [comment]
@JessD9 anything further on this bug, or can we close it off?
