### ISSUE TITLE
LDRS 503 - HTML Source Editor problem

### ISSUE THREAD

**Issue by dgaudet48** [TWUOnline/bug-tracking#391]
**Which course contains the bug?**  
- LDRS503 Dev Master

 
 
**Describe the error and/or your suggestion**  

The Unit 2 content from ATOM will not show up in the Unit 2 tab. HTML source editor code looks correct. I have played around with Grav but I still can not get content to show up. I keep getting error message. 
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=13614&section=4
2. Unit # 2        
 
**Optional: Screenshots**

**Comment by karenroeck** [comment]
@dgaudet48 I am having the same issue with LDRS 697 - Reza and I tried everything we could think of yesterday and no luck :(
