### ISSUE TITLE
LDRS 300 IF FAR Master Unit 10.1 video fail

### ISSUE THREAD

**Issue by BLMSasaki** [TWUOnline/bug-tracking#392]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 LDRS 300 IF FAR Master 
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 Unit 10.1 Activity -- the current embedded video is removed/ null. Can you please replace it with this one
 https://www.youtube.com/watch?v=QU78TiTOSow

**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=10828&section=10
2. Unit #    10     Topic #   10.1      Activity#  Learning Activity 10.1 #2
 
**Optional: Screenshots**

**Comment by karenroeck** [comment]
@BLMSasaki all updated 👍
