### ISSUE TITLE
Extra Button

### ISSUE THREAD

**Issue by dgaudet48** [TWUOnline/bug-tracking#399]
**Which course contains the bug?**  
- Psych106 Dev 2
 
 
**Describe the error and/or your suggestion**  

On the "Assessment" tab - if you scroll to the bottom there is an extra button titled "Writing Assignment 1" that does not lead anywhere - it needs to be deleted. 
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=13547&section=5
2. Unit #    4     Topic #  Assessment        
 
**Optional: Screenshots**

**Comment by karenroeck** [comment]
@dgaudet48 The button is all gone 👍
