### ISSUE TITLE
WRTG 101 - Lesson 3 content

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#4]
**Which course contains the bug?**
- Course Code and section e.g. 
WRTG 101 FAR MASTER

**Describe the error or your suggestion**
Subtopic 3 was missing (just learning activity and alert are in GitHub).
content needs formatting (tables, coloured font, bold, etc.)  See the original word document (p.24), and perhaps change to Presentation Slides if needed.

**Location of the bug**
Lesson 3 - subtopic 3 - in text citation

**Comment by michaelamulder** [comment]
Hi Kelly,
It looks to me that subtopic 3 is there. The formatting is different than the word document, but Colin has already looked at it and doesn't know if he can make anymore changes to the format @cmadland

**Comment by kmarjanovic** [comment]
Okay, thanks for checking Michaela!
