### ISSUE TITLE
LDRS 500 Community of Inquiry: Link to Rubric is broken

### ISSUE THREAD

**Issue by cpenfoldnavarro** [TWUOnline/bug-tracking#40]
LDRS 500 Online Fall 2019  

Assessment/Community of Inquiry

Link to the Rubric for the Community of Inquiry is broken (404) error. 
 
 https://learn.twu.ca/course/view.php?id=9714&section=13
 
 Please correct link as soon as possible.

 
[LDRS 500 Community of Inquiry RUBRIC.docx](https://github.com/TWUOnline/bug-tracking/files/3698671/LDRS.500.Community.of.Inquiry.RUBRIC.docx)

**Comment by kmarjanovic** [comment]
Fixed error.
