### ISSUE TITLE
Production: PSYC 340 welcome video

### ISSUE THREAD

**Issue by karenroeck** [TWUOnline/bug-tracking#400]
### Course
PSYC 340

### URL
https://mytwu-my.sharepoint.com/personal/m_manning-shull_twu_ca/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fm%5Fmanning%2Dshull%5Ftwu%5Fca%2FDocuments%2FAttachments%2Fzoom%5F6%2Emp4&parent=%2Fpersonal%2Fm%5Fmanning%2Dshull%5Ftwu%5Fca%2FDocuments%2FAttachments&originalPath=aHR0cHM6Ly9teXR3dS1teS5zaGFyZXBvaW50LmNvbS86djovZy9wZXJzb25hbC9tX21hbm5pbmctc2h1bGxfdHd1X2NhL0VmcThvcUh1QjB4Q29kSjZRQjJFQXMwQkJlRUVNRExua3hrbkdjN1VGSW1xU1E_cnRpbWU9N3JmT1MwMVEyRWc

### Instructions
Please edit this video (starts at 0:44). Add intro/outro TWU branding, instructor title, and background music. The instructor's title is Margaret Manning-Shull, MS., M.Div., LMHCA, Instructor, TWU-Bellingham Extension Campus. Let me know if the resolution is high enough, or if she needs to reshoot with a different camera.

**Comment by Jeff-TWU** [comment]
@karenroeck Sounds good. I'm not able to access the file. Can you get me access? 
<img width="810" alt="Screen Shot 2020-09-04 at 9 05 39 AM" src="https://user-images.githubusercontent.com/66963480/92261280-07b09080-ee8e-11ea-9fda-862e34d79c79.png">

**Comment by karenroeck** [comment]
@Jeff-TWU Just shared it with you - it is called zoom_6.mp4 Did that work?

**Comment by Jeff-TWU** [comment]
@karenroeck Got the file. Oh man the quality is not great. Both audio and video. Sounds like Zoom had to apply a ton of noise cancellation, I'm guessing because the she used the built in mic?  I wish we had some minimum standards. They should at least record with an external mic. 720p video minimum. Please let me know if we can get another recording. If not I'll go with this one. Sorry for the hassle!

**Comment by karenroeck** [comment]
@Jeff-TWU Yeah I was worried the a/v wouldn't be up to snuff. I'll connect with her to get a higher quality recording.

**Comment by Jeff-TWU** [comment]
@karenroeck Sounds good. Thanks!

**Comment by karenroeck** [comment]
@Jeff-TWU I just shared the updated video file with you - titled "Psych340 Welcome Edited.mp4"- is this one ok?

**Comment by Jeff-TWU** [comment]
@karenroeck I think this will work. I should be able to clean up some of the audio. I'll get you a file tomorrow morning if that works for you.

**Comment by karenroeck** [comment]
@Jeff-TWU Yes, tomorrow morning is perfect. Thanks so much!

**Comment by Jeff-TWU** [comment]
@karenroeck https://web.microsoftstream.com/video/c688875b-dba8-45bd-bc83-dc55723ac3d6

**Comment by karenroeck** [comment]
@Jeff-TWU Awesome - this is great! Thanks so much. Is there a way to change the viewing permissions so all Margaret's students can see this video from where it currently "lives" in Stream, or do I need to download it and reupload it to a different group/channel?

**Comment by Jeff-TWU** [comment]
@karenroeck Great, glad it works for you. I believe all students should have access if they are logged in. You shouldn't need to re-upload it. 
<img width="495" alt="Screen Shot 2020-09-09 at 4 59 38 PM" src="https://user-images.githubusercontent.com/66963480/92666393-f7e5e180-f2bd-11ea-98a1-5121cea5b11d.png">
@mellaurie can you confirm? Mel also  created a channel for her course, just to group things and make them easier.

**Comment by mellaurie** [comment]
I made a channel that has company wide access.  If you need to it to remain private within her class, she will need to create a group for her class (though I believe this is done in conjunction with the MS Teams teams, so she may just have to search for it), then select in the share with box, and then she will uncheck the "allow everyone in the company..."

**Comment by karenroeck** [comment]
@mellaurie Cool, thanks for the info!
