### ISSUE TITLE
PHIL 105 WP

### ISSUE THREAD

**Issue by moreccom** [TWUOnline/bug-tracking#401]
For PHIL 105 WP, the Announcements tab is missing and the Getting Started Resources for Faculty tab is appearing in its place.

**Comment by karenroeck** [comment]
@moreccom I see the Announcements tab - has this issue been resolved?

![Screen Shot 2020-09-08 at 11 06 46 AM](https://user-images.githubusercontent.com/67760065/92512302-73af3380-f1c3-11ea-97ed-4d396ffb509e.png)
