### ISSUE TITLE
PHIL 105 IS

### ISSUE THREAD

**Issue by moreccom** [TWUOnline/bug-tracking#402]
For PHIL 105 IS, the Announcements tab is missing and the Getting Started Resources for Faculty tab is appearing in its place.

**Comment by karenroeck** [comment]
@moreccom Same as PHIL 105 WP - I see the Announcements tab in this section as well. Please let me know if this is fixed or if you need further assistance.

![Screen Shot 2020-09-08 at 11 08 20 AM](https://user-images.githubusercontent.com/67760065/92512487-b40eb180-f1c3-11ea-9875-b47df2c9517c.png)
