### ISSUE TITLE
Production: LDRS 623

### ISSUE THREAD

**Issue by karenroeck** [TWUOnline/bug-tracking#403]
### Course
LDRS 623 - Developing Educational Programs (FAR MASTER)

### URL
https://learn.twu.ca/course/view.php?id=15687

### Instructions
@rezakh66 This course is going through a complete rewrite. Please clear all content from Atom so we have Units 1-5 with empty folders. Then please put new Unit 1 into production.

[LDRS_623_Unit_1.docx](https://github.com/TWUOnline/bug-tracking/files/5233694/LDRS_623_Unit_1.docx)

**Comment by rezakh66** [comment]
@karenroeck Hi Karen, I have uploaded unit 1

**Comment by karenroeck** [comment]
@rezakh66 Thanks so much! @mellaurie Could you please go through and finalize LDRS 623 Unit 1?

**Comment by mellaurie** [comment]
I've addressed all the production notes.  Please take a look @karenroeck

**Comment by karenroeck** [comment]
Looks awesome @mellaurie!
