### ISSUE TITLE
LDRS 500 Online Fall: Unit 1 navigation menu is missing

### ISSUE THREAD

**Issue by cpenfoldnavarro** [TWUOnline/bug-tracking#406]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
LDRS 500 OL Fall 2020
 
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
The navigation menu that usually appears at the top left of each unit (i.e. Overview, Topic 1, Topic 2, Learning Activities, etc.) seems to be missing from Unit 1. Please add.
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=14492&section=1
2. Unit #    1     Topic #  All pages       Activity#  
 
**Optional: Screenshots**

**Comment by karenroeck** [comment]
@cpenfoldnavarro The navigation menu now appears in Unit 1.

**Comment by cpenfoldnavarro** [comment]
Thanks so much!

CATHARINE PENFOLD NAVARRO, PhD
Part-Time Instructor, MA Leadership | TWU GLOBAL
Trinity Western University | e. c.penfoldnavarro@twu.ca<mailto:c.penfoldnavarro@twu.ca>

twu.ca<http://www.twu.ca/>

[cid:image001.png@01D56D6B.9FBB05E0]
