### ISSUE TITLE
LDRS 500 Online Fall 2020 Update Community of Inquiry Rubric

### ISSUE THREAD

**Issue by cpenfoldnavarro** [TWUOnline/bug-tracking#407]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 LDRS 500 Online Fall 2020
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
Please update the rubric for the Community of Inquiry in TWO places in the course, using the updated rubric attached here. 
[LDRS 500 Community of Inquiry RUBRIC.pdf](https://github.com/TWUOnline/bug-tracking/files/5299186/LDRS.500.Community.of.Inquiry.RUBRIC.pdf)
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=14492&section=1
2. Unit # Unit 1 Tab       Topic # Assessment     Activity#  Community of Inquiry for Online Students
 
1. URL:  https://learn.twu.ca/course/view.php?id=14492&section=12
2. Unit # Assessment Tab       Topic # Community of Inquiry        Activity#  Rubric

**Optional: Screenshots**

**Comment by karenroeck** [comment]
@cpenfoldnavarro The rubric has been updated in both places. Thank you for your clear instructions - much appreciated!

**Comment by cpenfoldnavarro** [comment]
Thank you so much!

CATHARINE PENFOLD NAVARRO, PhD
Part-Time Instructor, MA Leadership | TWU GLOBAL
Trinity Western University | e. c.penfoldnavarro@twu.ca<mailto:c.penfoldnavarro@twu.ca>

twu.ca<http://www.twu.ca/>

[cid:image001.png@01D56D6B.9FBB05E0]
