### ISSUE TITLE
Production LDRS 623 Unit 2

### ISSUE THREAD

**Issue by karenroeck** [TWUOnline/bug-tracking#408]
### Course

LDRS 623: Developing Educational Programs (FAR MASTER)

### URL

https://learn.twu.ca/course/view.php?id=15687&section=2

### Instructions

Reza, please put Unit 2 into production. Thanks!

[LDRS_623_Unit_2.docx](https://github.com/TWUOnline/bug-tracking/files/5322735/LDRS_623_Unit_2.docx)

**Comment by rezakh66** [comment]
Hi, @karenroeck I have uploaded unit 2. Please let me know if we need changes.
