### ISSUE TITLE
Production - LDRS 300 - U1 pwpt

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#41]
### Course
LDRS 300
### URL
https://learn.twu.ca/course/view.php?id=10828&section=1
Unit 1 Topic 1 Activity 1.1
### Instructions
-Upload pwpt & link in Activity 1.1- Unit 1.1 ppt Spheres of Influence

pwpt is in github

**Comment by mattdennis15** [comment]
https://github.com/TWUOnline/ba-lead/commit/c4f3172e4300940c270a9b0a23fcb454aba29311

**Comment by mattdennis15** [comment]
Task done

**Comment by kmarjanovic** [comment]
Thank you!
