### ISSUE TITLE
PSYC 106

### ISSUE THREAD

**Issue by karenroeck** [TWUOnline/bug-tracking#410]
**Which course contains the bug?**  
PSYC 106 ADC Master 
 
**Describe the error and/or your suggestion**  
I can't figure out how to remove the text "[pdfjs]" displaying above the embedded PDF.
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=15775&section=0

**Optional: Screenshots**  
<img width="974" alt="Screen Shot 2020-10-05 at 3 10 31 PM" src="https://user-images.githubusercontent.com/67760065/95137615-549db600-071d-11eb-9770-fcfe768e9d1d.png">

**Comment by karenroeck** [comment]
@rezakh66 Could you take a look at this bug when you have a chance? This course is now live. Thanks!

**Comment by rezakh66** [comment]
Hi @karenroeck This comes along with the pdfjs plugin. I think it would not be possible to get that removed as long as we are utilizing the plugin. However, I'm looking for any possible workaround.

**Comment by karenroeck** [comment]
@rezakh66 no worries! I tried so many things to get rid of that text, so I'm glad it wasn't "user error" on my part haha!
