### ISSUE TITLE
LDRS 500 Online Fall 2020

### ISSUE THREAD

**Issue by cpenfoldnavarro** [TWUOnline/bug-tracking#411]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
Please correct the authors' names in the Activity Checklist in Activity 3.1.
Instead of: Wang, Og, Croutright & Colbert (2011)
It should be: Wang, Oh, Courtright & Colbert, A.E. (2011)
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=14492&section=3
2. Unit #   3     Topic # Overview        Activity#  Activity Checklist: Activity 3.1

AND
https://learn.twu.ca/course/view.php?id=14492&section=3
Unit 3, Learning Activities, Learning Activity 3.1 list
 
**Optional: Screenshots**

**Comment by karenroeck** [comment]
@cpenfoldnavarro Updates have been made. Double-checking: Colbert, A. E. is the only author with initials listed. Would you prefer all the authors to have initials listed, or only Colbert? APA 7 does not list author initials for in-text citations :)

**Comment by cpenfoldnavarro** [comment]
Thanks, Karen.

For the activity checklist, it looks like most resources are formatted as an in-text citation. If so, it would be:
Wang, Oh, Courtright & Colbert (2011).

Thanks for the attention to detail!
Cathy

CATHARINE PENFOLD NAVARRO, PhD
Part-Time Instructor, MA Leadership | TWU GLOBAL
Trinity Western University | e. c.penfoldnavarro@twu.ca<mailto:c.penfoldnavarro@twu.ca>

twu.ca<http://www.twu.ca/>

[cid:image001.png@01D56D6B.9FBB05E0]

**Comment by karenroeck** [comment]
@cpenfoldnavarro Perfect! I've made the updates. I am doing coursework right now, so my APA 7 spidey-senses are on full tilt haha.

**Comment by cpenfoldnavarro** [comment]
Thanks! Hope your coursework is going well!

CATHARINE PENFOLD NAVARRO, PhD
Part-Time Instructor, MA Leadership | TWU GLOBAL
Trinity Western University | e. c.penfoldnavarro@twu.ca<mailto:c.penfoldnavarro@twu.ca>

twu.ca<http://www.twu.ca/>

[cid:image001.png@01D56D6B.9FBB05E0]
