### ISSUE TITLE
Production - LDRS 623, Unit 3

### ISSUE THREAD

**Issue by karenroeck** [TWUOnline/bug-tracking#412]
### Course

LDRS 623: Developing Educational Programs (FAR MASTER)

### URL

https://learn.twu.ca/course/view.php?id=15687

### Instructions
- [x] @rezakh66 Please upload Unit 3 to Atom and insert .pdf and .docx files where specified.

Please upload required files as attachments.

[LDRS_623_Unit_3.docx](https://github.com/TWUOnline/bug-tracking/files/5410024/LDRS_623_Unit_3.docx)

[Gerber_2019.pdf](https://github.com/TWUOnline/bug-tracking/files/5410028/Gerber_2019.pdf)
[Howard_2007.pdf](https://github.com/TWUOnline/bug-tracking/files/5410029/Howard_2007.pdf)
[Pino-Pasternak_2014.pdf](https://github.com/TWUOnline/bug-tracking/files/5410031/Pino-Pasternak_2014.pdf)
[SK_curriculum_objectives.pdf](https://github.com/TWUOnline/bug-tracking/files/5410032/SK_curriculum_objectives.pdf)
[Template_1.docx](https://github.com/TWUOnline/bug-tracking/files/5410033/Template_1.docx)
[Template_2.docx](https://github.com/TWUOnline/bug-tracking/files/5410034/Template_2.docx)
[Tyler_1949.pdf](https://github.com/TWUOnline/bug-tracking/files/5410035/Tyler_1949.pdf)
[VanTassel-Baska_2015.pdf](https://github.com/TWUOnline/bug-tracking/files/5410036/VanTassel-Baska_2015.pdf)

**Comment by cmadland** [comment]
Is there a reason to upload these articles as pdf rather than creating MD pages? Also, maybe we shouldn't be pushing students to Teachers Pay Teachers, which is a bit of a sketchy site. We can create templates based on Wiggins and McTighe just as easily and at a higher quality than Chase 'n Darla Guymon or Mission Bay High School...

**Comment by karenroeck** [comment]
Can we create MD pages from PDFs? Would it compromise the original typeface, photos, etc?

Is there a web-based way to create the UbD templates with fillable fields for students? These Word templates follow UbD principles from the W/McT text and are not original work by anyone on TpT.


KAREN ROECK, EdD (cand.), MA

Instructional Designer | TWU GLOBAL

Trinity Western University | e. karen.roeck@twu.ca<mailto:karen.roeck@twu.ca>

twu.ca<http://www.twu.ca/>

________________________________

**Comment by rezakh66** [comment]
@karenroeck @cmadland I have uploaded the unit itself, Please let me know when I can proceed with inserting the files.

**Comment by karenroeck** [comment]
@reza66 Please embed these edited templates.

[Template_1.docx](https://github.com/TWUOnline/bug-tracking/files/5418292/Template_1.docx)
[Template_2.docx](https://github.com/TWUOnline/bug-tracking/files/5418294/Template_2.docx)

**Comment by karenroeck** [comment]
Thanks @reza66! Can you please create MD pages for the Gerber (2019) and Howard (2007) articles? 

@cmadland Can you confirm the process for embedding published journal articles? In my EdD classes at Western, the prof puts journal articles directly into the LMS. As a student, I appreciate not having to click a link to go to the Western database and access the article there - but I understand the point about providing those click analytics to the librarians. Please advise on how to proceed here.

**Comment by karenroeck** [comment]
@cmadland Any further thoughts here re: embedding published journal articles vs linking to TWU library site?

**Comment by rezakh66** [comment]
> Thanks @reza66! Can you please create MD pages for the Gerber (2019) and Howard (2007) articles?
> 
> @cmadland Can you confirm the process for embedding published journal articles? In my EdD classes at Western, the prof puts journal articles directly into the LMS. As a student, I appreciate not having to click a link to go to the Western database and access the article there - but I understand the point about providing those click analytics to the librarians. Please advise on how to proceed here.

I added Gerber and Howard pdfs in MD format. Let me know when we can add the rest pf pdfs

**Comment by karenroeck** [comment]
@rezakh66 could you please add them now? We can change them later if the format needs adjusting. Thanks!

**Comment by rezakh66** [comment]
Hi @karenroeck PDFs are uploaded.

**Comment by karenroeck** [comment]
@rezakh66 thanks so much - you are a star!
