### ISSUE TITLE
UNIV 301 Master Moodle Shell

### ISSUE THREAD

**Issue by mellaurie** [TWUOnline/bug-tracking#413]
### Instructions
- [x] Create copy of: https://learn.twu.ca/course/view.php?id=15685 but without groups or students or calendar 
- [x] Create a Master Moodle Shell for UNIV 301
- [x] Import copy into the Moodle Master

**Comment by rezakh66** [comment]
Hi @mellaurie you can find UNIV 301 (FAR MASTER) [here](https://learn.twu.ca/course/view.php?id=17766).

**Comment by mellaurie** [comment]
Thank you @rezakh66 !!
