### ISSUE TITLE
LDRS 662 Facilitator's Guide

### ISSUE THREAD

**Issue by mellaurie** [TWUOnline/bug-tracking#414]
### Instructions
- [x] Please produce Facilitator's Guide in master course shell

Here is the link to the doc: https://docs.google.com/document/d/1i4n4fq72f4PLuqCfzOSSrJg58iig8xNBe-OP96ca47Q/edit#

**Comment by rezakh66** [comment]
Hi @mellaurie I have uploaded the facilitator's guide.

**Comment by karenroeck** [comment]
@rezakh66 Do you mind adjusting the titles on each accordion to have title case capitalization? e.g. Unit 1 Notes instead of unit 1 notes

**Comment by mellaurie** [comment]
Looking good @rezakh66!  In the second to last paragraph before the accordion, could you remove "LDRS 591" out of "their participation in labs as specified by the LDRS 591 Participation Rubric"

**Comment by rezakh66** [comment]
Hi @mellaurie @karenroeck I made the changes.Thanks

**Comment by mellaurie** [comment]
Thanks @rezakh66!!
