### ISSUE TITLE
LDRS 500 online: Fix spelling of Northouse in Unit 4 Activity Checklist

### ISSUE THREAD

**Issue by cpenfoldnavarro** [TWUOnline/bug-tracking#415]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 
Please correct the spelling of Northouse. It should be:

Activity 4.2
Take the Authentic Leadership Questionnaire (ALQ) found in Chapter 9 of Northouse (2019). After completing the assessment, in your Reflective Journal, prepare a 150 word synthesis commenting on the overall results of the surveys Expected time commitment: 30 minutes
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=14492&section=4
2. Unit #    4     Topic #   Overview      Activity#  Activity Checklist (4.2)
 
**Optional: Screenshots**

**Comment by karenroeck** [comment]
Hi @cpenfoldnavarro I updated the wording to reflect what you have here - but I can't see where "Northouse" is misspelled. It looks correct in Activity 4.2:

![Screen Shot 2020-10-26 at 9 32 40 AM](https://user-images.githubusercontent.com/67760065/97200379-5ed83080-176e-11eb-88ce-df1dbe784afe.png)

**Comment by cpenfoldnavarro** [comment]
Karen,
It’s incorrect in the Unit 4 Overview Page, in the Activity Checklist under Activity 4.2.

https://learn.twu.ca/course/view.php?id=14492&section=4

CATHARINE PENFOLD NAVARRO, PhD
Part-Time Instructor, MA Leadership | TWU GLOBAL
Trinity Western University | e. c.penfoldnavarro@twu.ca<mailto:c.penfoldnavarro@twu.ca>

twu.ca<http://www.twu.ca/>

[cid:image001.png@01D56D6B.9FBB05E0]

**Comment by karenroeck** [comment]
@cpenfoldnavarro Got it, fixed it! Thanks for the clarification.

**Comment by cpenfoldnavarro** [comment]
Thanks.

CATHARINE PENFOLD NAVARRO, PhD
Part-Time Instructor, MA Leadership | TWU GLOBAL
Trinity Western University | e. c.penfoldnavarro@twu.ca<mailto:c.penfoldnavarro@twu.ca>

twu.ca<http://www.twu.ca/>

[cid:image001.png@01D56D6B.9FBB05E0]
