### ISSUE TITLE
LDRS 500 Online Unit 5 and Unit 6 menu bar missing

### ISSUE THREAD

**Issue by cpenfoldnavarro** [TWUOnline/bug-tracking#416]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 LDRS 500 Online Fall 2020
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 The menu bar is missing form Unit 5. 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=14492&section=5
2. Unit #  5 and 6       Topic #   overview      Activity#  menu bar is missing from both Units 5 and 6.
 
**Optional: Screenshots**

**Comment by karenroeck** [comment]
@cpenfoldnavarro The menus are now visible in Units 5-6.

**Comment by cpenfoldnavarro** [comment]
Thanks!

CATHARINE PENFOLD NAVARRO, PhD
Part-Time Instructor, MA Leadership | TWU GLOBAL
Trinity Western University | e. c.penfoldnavarro@twu.ca<mailto:c.penfoldnavarro@twu.ca>

twu.ca<http://www.twu.ca/>

[cid:image001.png@01D56D6B.9FBB05E0]
