### ISSUE TITLE
LDRS 500 Online Fall 2020 Links not working in Unit 4

### ISSUE THREAD

**Issue by cpenfoldnavarro** [TWUOnline/bug-tracking#417]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 
links need to be updated:
Example of Lateral Thinking when it matters: https://www.youtube.com/watch?v=q3HjWA7bii4

Beyond Common Sense: Critical Thinking Skills and Decision Making for Leaders: https://www.youtube.com/watch?v=QTWc-JLh3Fw

 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=14492&section=5
2. Unit #  4       Topic #  Formative Learning Activities        Activity#  Learning Activity 5.1
 
**Optional: Screenshots**

**Comment by karenroeck** [comment]
@cpenfoldnavarro I updated the two video links and embedded all the videos directly in Moodle for Learning Activity 5.1 - let me know what you think.

**Comment by cpenfoldnavarro** [comment]
Great! Thank should work.
Cathy

CATHARINE PENFOLD NAVARRO, PhD
Part-Time Instructor, MA Leadership | TWU GLOBAL
Trinity Western University | e. c.penfoldnavarro@twu.ca<mailto:c.penfoldnavarro@twu.ca>

twu.ca<http://www.twu.ca/>

[cid:image001.png@01D56D6B.9FBB05E0]

**Comment by cpenfoldnavarro** [comment]
Karen,
I just noticed that the same resources are listed here as well:
https://learn.twu.ca/course/view.php?id=14492&section=14
(LDRS 500 Online Fall 2020, Assessment/Critical Analysis – Instructions for Assignment 3).

Could you update these as well?

Thanks so much!
Cathy

CATHARINE PENFOLD NAVARRO, PhD
Part-Time Instructor, MA Leadership | TWU GLOBAL
Trinity Western University | e. c.penfoldnavarro@twu.ca<mailto:c.penfoldnavarro@twu.ca>

twu.ca<http://www.twu.ca/>

[cid:image001.png@01D56D6B.9FBB05E0]

**Comment by karenroeck** [comment]
@cpenfoldnavarro For sure - done :)

**Comment by cpenfoldnavarro** [comment]
Merci!

CATHARINE PENFOLD NAVARRO, PhD
Part-Time Instructor, MA Leadership | TWU GLOBAL
Trinity Western University | e. c.penfoldnavarro@twu.ca<mailto:c.penfoldnavarro@twu.ca>

twu.ca<http://www.twu.ca/>

[cid:image001.png@01D56D6B.9FBB05E0]
