### ISSUE TITLE
LDRS 623, Unit 4

### ISSUE THREAD

**Issue by karenroeck** [TWUOnline/bug-tracking#418]
### Course

LDRS 623: Developing Educational Courses (FAR MASTER)

### URL

https://learn.twu.ca/course/view.php?id=15687&section=4

### Instructions
Please add Unit 4 and embed attached PDFs where indicated.

[LDRS_623_Unit_4.docx](https://github.com/TWUOnline/bug-tracking/files/5441672/LDRS_623_Unit_4.docx)
[Chapter_7.pdf](https://github.com/TWUOnline/bug-tracking/files/5441675/Chapter_7.pdf)
[Fullan.pdf](https://github.com/TWUOnline/bug-tracking/files/5441676/Fullan.pdf)
[Mehta.pdf](https://github.com/TWUOnline/bug-tracking/files/5441677/Mehta.pdf)
[Tomlinson.pdf](https://github.com/TWUOnline/bug-tracking/files/5441678/Tomlinson.pdf)

**Comment by rezakh66** [comment]
Good Morning @karenroeck  I have uploaded unit 4.

**Comment by karenroeck** [comment]
thank you!
