### ISSUE TITLE
Chart for PSYC 340

### ISSUE THREAD

**Issue by karenroeck** [TWUOnline/bug-tracking#420]
### Course
PSYC 340: Interpersonal and Helping Skills (ADC Master)

### URL
https://learn.twu.ca/course/view.php?id=15808&section=5

### Instructions
- [ ] Please create a visually appealing chart based off the attached file. This chart will be displayed in Moodle for PSYC 340, Unit 5.

[Why giving advice is unhelpful chart.pdf](https://github.com/TWUOnline/bug-tracking/files/5461727/Why.giving.advice.is.unhelpful.chart.pdf)

**Comment by Jeff-TWU** [comment]
@karenroeck I'll get on this on Tuesday. Thanks!

**Comment by karenroeck** [comment]
Sounds great - enjoy your vacation days!!

**Comment by Jeff-TWU** [comment]
![PSYC 340 Chart](https://user-images.githubusercontent.com/66963480/98184075-5a262180-1ebe-11eb-9bf6-b4b0ad28613a.png)
@karenroeck I had fun with this one. Please let me know what you think.

**Comment by karenroeck** [comment]
@Jeff-TWU This looks awesome! Love the graphic and the TWU colours. 

Some minor suggestions:
- [ ] Can the "YES" and "NO" arrows be consistent? e.g. "YES" = all yellow and "NO" = all blue
- [ ] Can you add the third column from the chart as the first bullet point under each section? e.g. Counselee is blamed, Counselor is credited, etc
- [ ] Under the third "YES," can you adjust the text box to remove the hyphen from "displeasure"?

**Comment by Jeff-TWU** [comment]
@karenroeck Glad you like it! 

Changes made. Let me know if you need anything else.
![PSYC 340 Chart_R1](https://user-images.githubusercontent.com/66963480/98285975-27c90280-1f58-11eb-839b-bd2a2656d368.png)

**Comment by karenroeck** [comment]
Brilliant - thanks so much!

**Comment by Jeff-TWU** [comment]
@karenroeck Welcome!

**Comment by Jeff-TWU** [comment]
![PSYC 340 Chart_R2](https://user-images.githubusercontent.com/66963480/98309354-121b0380-1f7f-11eb-838d-aa65714a4134.png)
Just Noticed a mistake. Fixed!
