### ISSUE TITLE
PSYC 340, Week 5

### ISSUE THREAD

**Issue by karenroeck** [TWUOnline/bug-tracking#421]
### Course

PSYC 340: Interpersonal and Helping Skills (ADC MASTER)

### URL

https://learn.twu.ca/course/view.php?id=15808&section=5

### Instructions
- Please input Week 5 in Atom. I've already formatted 0.7references in Atom, so please leave that as is :) Thanks!

Please upload required files as attachments.
[PSYC_340_Unit_5.docx](https://github.com/TWUOnline/bug-tracking/files/5462156/PSYC_340_Unit_5.docx)

**Comment by rezakh66** [comment]
Hi @karenroeck I uploaded unit 5. Please let me know if changes are needed.

**Comment by karenroeck** [comment]
Looks great - thank you @rezakh66!
