### ISSUE TITLE
MCOM 353 Production

### ISSUE THREAD

**Issue by mellaurie** [TWUOnline/bug-tracking#422]
### Instructions
- [x] Please create Moodle shell for this course
- [x] Upload Unit 1 and 2 to art-master

Please upload required files as attachments.
[MCOM_353_Unit 1_Nov4_ML.docx](https://github.com/TWUOnline/bug-tracking/files/5489884/MCOM_353_Unit.1_Nov4_ML.docx)
[MCOM_353_Unit 2_Nov4_ML.docx](https://github.com/TWUOnline/bug-tracking/files/5489885/MCOM_353_Unit.2_Nov4_ML.docx)

**Comment by rezakh66** [comment]
Hi @mellaurie both units are uploaded [here](https://learn.twu.ca/course/view.php?id=17787&section=0).

**Comment by mellaurie** [comment]
Thanks @rezakh66!

In both these units, could you make a new alert box when you see "Questions to consider for topic #" in the Learning Activities section in each Topic?

**Comment by rezakh66** [comment]
Hi @mellaurie Done :)

**Comment by mellaurie** [comment]
Thank you @rezakh66.  Here is Unit 4 ready for production. 
[MCOM_353_Unit 4_Nov 10_ML.docx](https://github.com/TWUOnline/bug-tracking/files/5532404/MCOM_353_Unit.4_Nov.10_ML.docx)

**Comment by rezakh66** [comment]
Hi @mellaurie Unit 4 is uploaded :)

**Comment by mellaurie** [comment]
@rezakh66 Can you help me move this repo to the samc master?  I didn't realize we had a samc master when I asked for this in the arts one. 

Thanks in advance :)

**Comment by rezakh66** [comment]
Hi @mellaurie I have moved MCOM 353 to the Samc-master.

**Comment by karenroeck** [comment]
How is this "bug" coming along? Just cleaning up the queue.

**Comment by mellaurie** [comment]
More edits and units to come.  Just waiting for a meeting with Divine.
