### ISSUE TITLE
LDRS 320

### ISSUE THREAD

**Issue by JessD9** [TWUOnline/bug-tracking#423]
### Instructions
- @rezakh66 Please upload Units 2 and 3 to GiHub/Atom (may need to create 320 folder in github)
- Copy/paste course introduction from LDRS 301
- **Unit 1 will be added later...I'm still making edits**

[LDRS_320_U2_June19_JD_KM.docx](https://github.com/TWUOnline/bug-tracking/files/5491667/LDRS_320_U2_June19_JD_KM.docx)

[LDRS_320_U3_JUNE26_JD.docx](https://github.com/TWUOnline/bug-tracking/files/5491668/LDRS_320_U3_JUNE26_JD.docx)

**Comment by rezakh66** [comment]
@JessD9 Hi, I uploaded unit 1 on Friday, but let me know the updates and I will revise that. Unit 2 and 3 are updated since Friday?

**Comment by rezakh66** [comment]
Hi @JessD9 I have uploaded units 2 & 3.

**Comment by JessD9** [comment]
Thanks @rezakh66! 
Please insert the following PPT into Unit 1, Topic 2-  Activity 2.1

[ldrs320_PPT_U1.pptx](https://github.com/TWUOnline/bug-tracking/files/5528806/ldrs320_PPT_U1.pptx)

**Comment by rezakh66** [comment]
Good Morning @JessD9 PPT file is inserted in activity 2.1

**Comment by JessD9** [comment]
@rezakh66 Great:)

**Comment by JessD9** [comment]
@rezakh66 Here are units 4-6
[LDRS_320_U4_Nov21_JD.docx](https://github.com/TWUOnline/bug-tracking/files/5579633/LDRS_320_U4_Nov21_JD.docx)
[Worksheet_InquiryVsAdvocacy.docx](https://github.com/TWUOnline/bug-tracking/files/5579634/Worksheet_InquiryVsAdvocacy.docx)
[LDRS_320_U5_Nov22_JD.docx](https://github.com/TWUOnline/bug-tracking/files/5579635/LDRS_320_U5_Nov22_JD.docx)
[LDRS_320_U6 _Nov22_JD.docx](https://github.com/TWUOnline/bug-tracking/files/5579637/LDRS_320_U6._Nov22_JD.docx)

**Comment by rezakh66** [comment]
Hi @JessD9 Units 4-6 are ready to go.

**Comment by JessD9** [comment]
@rezakh66 Thank you!!

**Comment by JessD9** [comment]
@rezakh66  Here are Units 7 & 8

[LDRS_320_U7_JAN03_JD.docx](https://github.com/TWUOnline/bug-tracking/files/5763241/LDRS_320_U7_JAN03_JD.docx)
[LDRS_320_Activity_7.7_Worksheet.docx](https://github.com/TWUOnline/bug-tracking/files/5763242/LDRS_320_Activity_7.7_Worksheet.docx)

[LDRS_320_U8 _JAN03_JD.docx](https://github.com/TWUOnline/bug-tracking/files/5763243/LDRS_320_U8._JAN03_JD.docx)
[LDRS_320_Activity_8.5_Case study.pdf](https://github.com/TWUOnline/bug-tracking/files/5763244/LDRS_320_Activity_8.5_Case.study.pdf)

**Comment by rezakh66** [comment]
Hi @JessD9 Both units 7 & 8 are uploaded.

**Comment by JessD9** [comment]
Thanks!

**Comment by JessD9** [comment]
Activity 4.6 @Jeff-TWU (Unit 4, Topic 3) 

You should have manager access

**Comment by JessD9** [comment]
@rezakh66 Activity 4.6 resolved.

**Comment by karenroeck** [comment]
How is this "bug" coming along? Just cleaning up the queue.

**Comment by JessD9** [comment]
@karenroeck resolved

**Comment by JessD9** [comment]
Hi @rezakh66. Please upload the final 3 units for [LDRS 320](https://learn.twu.ca/course/view.php?id=17788&section=12#tabs-tree-start)

[LDRS320_U9_DEC12_JD.docx](https://github.com/TWUOnline/bug-tracking/files/7700822/LDRS320_U9_DEC12_JD.docx)

[LDRS320_U10_DEC12_JD).docx](https://github.com/TWUOnline/bug-tracking/files/7700842/LDRS320_U10_DEC12_JD.docx)
[LDRS320_U10_Table_4.2.pdf](https://github.com/TWUOnline/bug-tracking/files/7700847/LDRS320_U10_Table_4.2.pdf)

**Insert PDF "Table"** into Activity 10.3
**Create H5P Drag/Drop for Activity 10.6**

[LDRS_320_U11_DEC12_JD.docx](https://github.com/TWUOnline/bug-tracking/files/7700848/LDRS_320_U11_DEC12_JD.docx)

**Comment by rezakh66** [comment]
@JessD9 I completed units 9-11. H5P inserted as well. Please let me know if any adjustment is needed.

**Comment by JessD9** [comment]
Thank you!
