### ISSUE TITLE
PSYC 340, Unit 6 Production

### ISSUE THREAD

**Issue by karenroeck** [TWUOnline/bug-tracking#424]
### Course

PSYC 340: Interpersonal and Helping Skills (ADC Master)

### URL

https://learn.twu.ca/course/view.php?id=15808&section=6

### Instructions
- [x] Please upload Unit 6 and embed attachments as indicated in red.

Please upload required files as attachments.

[PSYC_340_Unit_6.docx](https://github.com/TWUOnline/bug-tracking/files/5512994/PSYC_340_Unit_6.docx)
[Helper_Egan_Reese](https://user-images.githubusercontent.com/67760065/98590274-6970ea80-2283-11eb-8326-836caa530fab.jpg)
[Three_Stage_Hill](https://user-images.githubusercontent.com/67760065/98590284-6d9d0800-2283-11eb-8752-15a518001c17.jpg)
[SAFE-T.pdf](https://github.com/TWUOnline/bug-tracking/files/5512993/SAFE-T.pdf)

**Comment by rezakh66** [comment]
Hi @karenroeck Unit 6 is uploaded.

**Comment by karenroeck** [comment]
Thank you, Reza!
