### ISSUE TITLE
LDRS 623, Unit 5 Production

### ISSUE THREAD

**Issue by karenroeck** [TWUOnline/bug-tracking#425]
### Course

LDRS 623: Developing Educational Programs (FAR MASTER)

### URL

https://learn.twu.ca/course/view.php?id=15687&section=5

### Instructions
- [x] Please upload Unit 5.

Please upload required files as attachments.

[LDRS_623_Unit_5.docx](https://github.com/TWUOnline/bug-tracking/files/5513759/LDRS_623_Unit_5.docx)

**Comment by rezakh66** [comment]
Hi @karenroeck I have uploaded unit 5.
