### ISSUE TITLE
LDRS 500 Online Fall 2020 Unit 7 Broken Links

### ISSUE THREAD

**Issue by cpenfoldnavarro** [TWUOnline/bug-tracking#426]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 LDRS 500 Online Fall 2020
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 Several of the links to articles in Unit 7 Learning Activities appear to be broken. A window opened up within Moodle, in the course, that took me to Catalyst., but not to the article. 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=14492&section=7
2. Unit #    7     Topic #     Learning Activities    Activity#  Learning Activity 7.2

 Read: The day-to-day experiences of workplace inclusion and exclusion.
https://www.catalyst.org/research/the-day-to-day-experiences-of-workplace-inclusion-and-exclusion/

Read: Day-to-day experiences of emotional tax among women and men of color in the workplace.
https://www.catalyst.org/research/day-to-day-experiences-of-emotional-tax-among-women-and-men-of-color-in-the-workplace/

Read: Emotional tax: How Black women and men pay more at work and how leaders can take action.
https://www.catalyst.org/research/emotional-tax-how-black-women-and-men-pay-more-at-work-and-how-leaders-can-take-action/

Read: Bourke, J. (2018). The diversity and inclusion revolution: 8 powerful truths. Deloitte Review (22).
https://www2.deloitte.com/au/en/blog/leadership-blog/2019/the-diversity-inclusion-8-powerful-truths.html#
**Optional: Screenshots**

**Comment by karenroeck** [comment]
@cpenfoldnavarro all fixed :)
