### ISSUE TITLE
LDRS 500 Online Unit 7: Trusted 10 Worksheet

### ISSUE THREAD

**Issue by cpenfoldnavarro** [TWUOnline/bug-tracking#427]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 LDRS 500 Fall 2020 
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.

The "Trusted 10 worksheet" should include a link/pdf.
For now, we can link to: 
 https://create.twu.ca/ldrs500/trusted-10-worksheet/

**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=14492&section=7
2. Unit #   7      Topic #  Learning Activity       Activity#  7.4 Trusted 10
 
**Optional: Screenshots**

**Comment by karenroeck** [comment]
@cpenfoldnavarro I linked the Trusted 10 worksheet - can students edit this? If not, would you rather have an editable template for this activity?

**Comment by cpenfoldnavarro** [comment]
Karen,
Something they can edit and download (save to their computer) would be ideal.

CATHARINE PENFOLD NAVARRO, PhD
Part-Time Instructor, MA Leadership | TWU GLOBAL
Trinity Western University | e. c.penfoldnavarro@twu.ca<mailto:c.penfoldnavarro@twu.ca>

twu.ca<http://www.twu.ca/>

[cid:image001.png@01D56D6B.9FBB05E0]

**Comment by karenroeck** [comment]
@cpenfoldnavarro I created an Excel spreadsheet and linked to Activity 7.4 - let me know if another format would be better or if this is ok.
