### ISSUE TITLE
Production: Overview videos for PSYC 340, Units 2-6

### ISSUE THREAD

**Issue by karenroeck** [TWUOnline/bug-tracking#428]
### Course

PSYC 340: Interpersonal and Helping Skills

### Instructions
- [x] Please edit the overview videos for PSYC 340, Units 2-6. Unit 6 has two takes - Take 1 has a better introduction and Take 2 has better content. The speaker (Margaret) pauses and restarts at certain sections, so please edit these "bloopers" out.
- [x] All videos are located in the [Learning Design](https://web.microsoftstream.com/group/2c4b5c0e-7227-4bf6-9ee2-b68a6f01dd31?view=videos) Stream group (published Nov 17).
- [x] You can see the first video [here](https://web.microsoftstream.com/video/c688875b-dba8-45bd-bc83-dc55723ac3d6). Please use the same title for Margaret and similar intro/outro overlays.

**Comment by karenroeck** [comment]
@Jeff-TWU This course launches Nov 30, so the sooner the better :) Thanks!

**Comment by Jeff-TWU** [comment]
@karenroeck On it. Sounds good!

**Comment by Jeff-TWU** [comment]
@karenroeck 

Uploaded.

[Unit 2](https://web.microsoftstream.com/video/3055b285-07af-4e86-bd85-dfdad2977baa) 
[Unit 3](https://web.microsoftstream.com/video/78640f5d-f31f-4004-9fa5-b8875b034883)
[Unit 4](https://web.microsoftstream.com/video/635f5560-1b9a-4084-911e-ad9d63c00f3a)
[Unit 5](https://web.microsoftstream.com/video/a0752409-cebc-4355-8a03-96e4a421aac6)
[Unit 6](https://web.microsoftstream.com/video/b25be31f-986c-4c18-af89-b276c713de0a)

**Comment by karenroeck** [comment]
@Jeff-TWU You are amazing!! I embedded the vids in Moodle and sent to my SME for review - she will be thrilled!
