### ISSUE TITLE
LDRS 500 Unit 9, Learning Activity 9.3: Update page numbers

### ISSUE THREAD

**Issue by cpenfoldnavarro** [TWUOnline/bug-tracking#429]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 LDRS 500 Online Fall 2020
(As always, please make this change to the master)
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
Please correct the page number for the Team Leader Questionnaire. The correct pages are pp. 397-8 (not 297-8) as currently stated.

This is found in two different locations in Unit 9:
 
Activity 9.3:
Complete the “Team Excellence and Collaborative Team Leader Questionnaire” (Northouse, 2019**, pp. 397-8)**
Expected time commitment: 1-2 hours

Learning Activity 9.3: Reflective Journal
Complete the “Team Excellence and Collaborative Team Leader Questionnaire” (Northouse, 2019, **pp. 397-8**).

**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=14492&section=9
AND
https://learn.twu.ca/course/view.php?id=14492&section=9
2. Unit # 9        Topic # Overview AND Learning Activities       Activity#  9.3
 
**Optional: Screenshots**

**Comment by karenroeck** [comment]
@cpenfoldnavarro all fixed!

**Comment by cpenfoldnavarro** [comment]
Thanks, Karen!

CATHARINE PENFOLD NAVARRO, PhD
Part-Time Instructor, MA Leadership | TWU GLOBAL
Trinity Western University | e. c.penfoldnavarro@twu.ca<mailto:c.penfoldnavarro@twu.ca>

twu.ca<http://www.twu.ca/>

[cid:image001.png@01D56D6B.9FBB05E0]
