### ISSUE TITLE
Production: LDRS 623 Facilitator's Guide

### ISSUE THREAD

**Issue by karenroeck** [TWUOnline/bug-tracking#430]
### Course

LDRS 623: Developing Educational Programs (FAR MASTER)

### URL

https://learn.twu.ca/course/view.php?id=15687&section=13

### Instructions
- [x] Please upload the Facilitator's Guide.

Please upload required files as attachments.
[LDRS_623_Facilitator_Guide.docx](https://github.com/TWUOnline/bug-tracking/files/5626048/LDRS_623_Facilitator_Guide.docx)

**Comment by rezakh66** [comment]
Hi @karenroeck Facilitator's Guide is uploaded.

**Comment by karenroeck** [comment]
Amazing - you rock @rezakh66!!
