### ISSUE TITLE
LDRS 502 Fac Guide

### ISSUE THREAD

**Issue by mellaurie** [TWUOnline/bug-tracking#431]
### Instructions
- [x] Please upload and format the Faciliator's Guide
[LDRS_502_Facilitator_Guide.docx](https://github.com/TWUOnline/bug-tracking/files/5690815/LDRS_502_Facilitator_Guide.docx)

**Comment by rezakh66** [comment]
Hi @mellaurie ,  Facilitator's Guide is uploaded.
