### ISSUE TITLE
LDRS 501 - Extra Button

### ISSUE THREAD

**Issue by dgaudet48** [TWUOnline/bug-tracking#432]
**Which course contains the bug?**  
- LDRS 501:Dev
 
 
**Describe the error and/or your suggestion**  
At the bottom of the "Assessment" page there is an extra button labeled "Activity 2-6" - it needs to be removed
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=15738&section=3
2. Unit #  2       Topic #     Assessment    Activity#  
 
**Optional: Screenshots**

**Comment by karenroeck** [comment]
@dgaudet48 The button is all gone!
