### ISSUE TITLE
Production

### ISSUE THREAD

**Issue by danielmingluito** [TWUOnline/bug-tracking#434]
### Course LDRS 662 SP01

https://learn.twu.ca/course/view.php?id=16625&section=3 

IN Unit 3 Activity Checklist - please change the words "Assignment 1" to Assignment 2.

Thanks

Daniel

**Comment by cmadland** [comment]
@karenroeck I think you have a better idea of the implications here...

**Comment by danielmingluito** [comment]
Thanks. All I did was swap assignments 1 and 2 - and its reflected on every section except that one for some reason.  I had asked before to swap them and the person that did it did it all except in that one spot =)

I tried to change it but couldn’t and I don’t want to screw up the system... =)

Warmly,

Daniel To, Ed.D
Instructor, MA Leadership | TWU Global |
Trinity Western University | M 778.772.4992 | T@DanielToSD36

Website https://www.twu.ca
Blog and Personal Site https://www.drdanielto.com


On Jan 11, 2021, at 9:32 AM, Colin Madland <notifications@github.com> wrote:

﻿

@karenroeck<https://github.com/karenroeck> I think you have a better idea of the implications here...

**Comment by karenroeck** [comment]
@danielmingluito I've changed the wording in the Unit 3 Activity Checklist. I noticed your heading at the top: ***NOTE Learning activity 3.1 and 3.3 don't work.  I can't delete it here for some reason SO - GO TO THE UNIT 3 DISCUSSION FOR NEW LINKS*** Is this something I can help fix from my end?

**Comment by danielmingluito** [comment]
Hi Karen

If you find a way to fix the links - for sure - or put my links in place of the old ones.  I couldn’t make the old links work at all

Warmly,

Daniel To, Ed.D
Instructor, MA Leadership | TWU Global |
Trinity Western University | M 778.772.4992 | T@DanielToSD36

Website https://www.twu.ca
Blog and Personal Site https://www.drdanielto.com

On Jan 11, 2021, at 3:26 PM, Karen Roeck <notifications@github.com> wrote:

﻿

@danielmingluito<https://github.com/danielmingluito> I've changed the wording in the Unit 3 Activity Checklist. I noticed your heading at the top: NOTE Learning activity 3.1 and 3.3 don't work. I can't delete it here for some reason SO - GO TO THE UNIT 3 DISCUSSION FOR NEW LINKS Is this something I can help fix from my end?

**Comment by karenroeck** [comment]
@danielmingluito I updated the link for the Kim article (the Chen & Lin article seemed to be working) and embedded the YouTube video for Learning Activity 3.3. Is everything fixed now?

**Comment by danielmingluito** [comment]
It appears to all work.  I’ll delete my comment at the top of the page.

THANKYOU!!! =)

Warmly,

Daniel To, Ed.D
Instructor, MA Leadership | TWU Global |
Trinity Western University | M 778.772.4992 | T@DanielToSD36
Website https://www.twu.ca
Blog and Personal Site https://www.drdanielto.com
I would like to respectfully acknowledge the shared traditional territory of the Katzie, Semiahmoo, Kwantlen, and Coast Salish Peoples where I work, play and learn.
