### ISSUE TITLE
Incorrect content 

### ISSUE THREAD

**Issue by emmanuelD-AFK** [TWUOnline/bug-tracking#436]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 LDRS 302 IF SP2021
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 The content in the Graded Assignment Tab does not reflect the course evaluations found in the syllabus or in the course overview!
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=17846&section=2
2. Assignments # Graded Assignments         Topic # Assignments         Activity#  
 
**Optional: Screenshots**  
If applicable, add screens
<img width="734" alt="Screen Shot 2021-01-15 at 9 56 55 PM" src="https://user-images.githubusercontent.com/59032072/104798568-a7572700-577c-11eb-9939-f0a674b9ea98.png">
<img width="728" alt="Screen Shot 2021-01-15 at 9 56 19 PM" src="https://user-images.githubusercontent.com/59032072/104798577-b8079d00-577c-11eb-9562-dff7f5db208a.png">

hots to help explain your problem.

**Comment by karenroeck** [comment]
@emmanuelD-AFK The syllabus I see is from FA 2019. @deannadams Do you have a copy of Kennedy's syllabus for LDRS 302? We need to embed it in this section of the course, and then I can check for alignment with the course evaluation and graded assignments.

**Comment by deannadams** [comment]
Hi Karen,

I don’t have an updated syllabus—sorry.
Let’s chat about this when we connect later this afternoon.

DeAnn


DeAnn Adams
Director, Faculty Services and Development | TWU GLOBAL
Trinity Western University | t. 604.513.2121 x3810 | e. deann.adams@twu.ca<mailto:deann.adams@twu.ca>

**Comment by karenroeck** [comment]
@emmanuelD-AFK I met with Kennedy today and sorted out the needed change. All fixed!
