### ISSUE TITLE
Course length 

### ISSUE THREAD

**Issue by emmanuelD-AFK** [TWUOnline/bug-tracking#437]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 LDRS 302 IF Sp 2021
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 Edit the length of the course: Instead of 4 weeks please read 15 weeks! Instead of 3hrs twice a week read 1 1/2 hrs each day Twice weekly. 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/editsection.php?id=207811&sr=0
2. Unit #  Welcome to LDRS 302!
<img width="564" alt="Screen Shot 2021-01-15 at 10 04 31 PM" src="https://user-images.githubusercontent.com/59032072/104798855-fc943800-577e-11eb-9f24-8aeb5dc92748.png">
         Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by karenroeck** [comment]
@emmanuelD-AFK I've updated the wording to reflect your timeline.
