### ISSUE TITLE
MCOM 221 

### ISSUE THREAD

**Issue by mellaurie** [TWUOnline/bug-tracking#440]
**Which course contains the bug?**  
- MCOM 221 FAR MASTER
 
 
**Describe the error and/or your suggestion**  
The unit navigation menu on the left is missing for unit 4.  Embed code looks normal.  In the repo, there is an extra section.md in the U4 folder (it's a copy of topic 1).  Could this be the problem? 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=10829
2. Unit #   4      
 
**Optional: Screenshots**

**Comment by karenroeck** [comment]
@mellaurie Yes, you got it- that extra section.md was causing the issue. I deleted it, so you are good to go now!

**Comment by rezakh66** [comment]
@karenroeck Thanks
