### ISSUE TITLE
Schedule Button unwanted

### ISSUE THREAD

**Issue by mellaurie** [TWUOnline/bug-tracking#441]
**Which course contains the bug?**  
- NURS 510 Master
- https://learn.twu.ca/course/view.php?id=10939
 
 
**Describe the error and/or your suggestion**  
There is a schedule button that leads nowhere (says error, 404).  We just need to remove this button altogether. 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
On the assessment page of Unit 3-9, at the bottom.  It seems that if there is a schedule folder with an alert for the unit's assessment page, then this schedule button shows up.
 
**Optional: Screenshots**  

![Screenshot (120)_LI](https://user-images.githubusercontent.com/65783200/106314529-b7601380-621e-11eb-8cb6-5df4a62f1380.jpg)

**Comment by rezakh66** [comment]
Hi @mellaurie I have removed the schedule buttons but please check the alert activities in assessment and let me know how you want them to be formatted. I think they are not consistent.

**Comment by mellaurie** [comment]
Thanks @rezakh66! 
 @karenroeck Can you advise on the formatting of the alerts in the assessment section for the upcoming units?
(Please note, there is an alert for unit 4 assessment, but Darlaine has requested it be removed.  I'm just leaving it in the repo but not directing to the page).

**Comment by karenroeck** [comment]
@mellaurie For Units 1-3, I changed publish to "false" if Darlaine did not want the alert to show for her students. Does that help?
