### ISSUE TITLE
Production: LDRS 624 Unit 1

### ISSUE THREAD

**Issue by karenroeck** [TWUOnline/bug-tracking#442]
### Course
LDRS 624: School Leadership and Supervision (FAR MASTER)

### URL
https://learn.twu.ca/course/view.php?id=15704&section=1

### Instructions
- [ ] First, please wipe all content from LDRS 624 in Atom (this course is a complete rewrite, starting from scratch)
- [ ] Once the folders are cleared out, please upload Unit 1 and embed the two articles as indicated in the .docx

Please upload required files as attachments.
[Maharaj.pdf](https://github.com/TWUOnline/bug-tracking/files/5936237/Maharaj.pdf)
[Rikkert.pdf](https://github.com/TWUOnline/bug-tracking/files/5936238/Rikkert.pdf)
[LDRS_624_Unit_1.docx](https://github.com/TWUOnline/bug-tracking/files/5936239/LDRS_624_Unit_1.docx)

**Comment by rezakh66** [comment]
Hi @karenroeck I have uploaded unit 1.

**Comment by karenroeck** [comment]
Thanks! 👍🏻
