### ISSUE TITLE
Plugin Not Working

### ISSUE THREAD

**Issue by dgaudet48** [TWUOnline/bug-tracking#444]
**Which course contains the bug?**  
- LDRS503 Dev Master

 
 
**Describe the error and/or your suggestion**  
Plugin for alert call out is not working on the "Assignments" page
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=13614&section=1
2. Unit #  Assignments   - Under the Discussion Forum section, right after the first paragraph
 
**Optional: Screenshots**

**Comment by rezakh66** [comment]
Hi @dgaudet48 That's being fixed

**Comment by karenroeck** [comment]
@rezakh66 Is this issue all cleared up? The course is currently live.

**Comment by rezakh66** [comment]
Hi @karenroeck Just saw your comments here. yes, it's being fixed and can be closed.
