### ISSUE TITLE
LDRS 624 (Unit 2)

### ISSUE THREAD

**Issue by karenroeck** [TWUOnline/bug-tracking#445]
### Course
LDRS 624: School Leadership and Supervision

### URL
https://learn.twu.ca/course/view.php?id=15704&section=2

### Instructions
- [x] Please upload Unit 2 in Atom. Please take note of the formatting for the extra resources - labelled "1-1a" and "1-2a" in Unit 1 Atom folder

Please upload required files as attachments.
[LDRS_624_Unit_2.docx](https://github.com/TWUOnline/bug-tracking/files/6006414/LDRS_624_Unit_2.docx)

**Comment by rezakh66** [comment]
Hi @karenroeck unit 2 is ready to go ;)

**Comment by karenroeck** [comment]
Thanks, Reza!
