### ISSUE TITLE
Punctuation and Awkward Sentence

### ISSUE THREAD

**Issue by emmanuelD-AFK** [TWUOnline/bug-tracking#446]
**Which course contains the bug?**  
-  LDRS 303 IF SP2021)
 
 
**Describe the error and/or your suggestion**  
 Awkward sentence and missing punctuation:(first and third point of the topic's outcomes)
 
 
**Location of the bug**  
1. URL: https://learn.twu.ca/course/view.php?id=17847&section=4 
2. Unit # 3         Topic # Servant Leadership
<img width="650" alt="Screen Shot 2021-02-24 at 3 15 41 PM" src="https://user-images.githubusercontent.com/59032072/109079047-3415ce80-76b3-11eb-8c27-ab1d9349906e.png">
         Activity#  
 
**Optional: Screenshots**

**Comment by karenroeck** [comment]
@emmanuelD-AFK I've gone in and made the corrections. Thanks!
