### ISSUE TITLE
Production: Infographic for PSYC 330

### ISSUE THREAD

**Issue by karenroeck** [TWUOnline/bug-tracking#447]
### Course

PSYC 330: Leadership in Organization & Small Groups

### Instructions
Hi Jeff, please create an infographic with the info below. The full acronym is STATE, but the prof only wants STA in this section of the course. I'm thinking like a windy road with S, T, A staggered along the way...let me know if you need more context.

The “S” in STATE your path is: Share your facts. We will learn and practice to describe the facts of what you see and hear, instead of your opinion about what your saw and heard. 

The “T” in STATE your path is: Tell your story. We will learn and practice how to safely share some of your view of the facts without trip wiring a defensive respond from the team member you are talking with. 

The “A” in STATE your path is: Ask for other’s paths. Before we try to get agreement on our viewpoints, we learn and practice how to ask a team member we are talking with what their view and perspective is about the facts we described to them.

**Comment by karenroeck** [comment]
Great question. Something that would display within a 13" laptop screen with the Moodle drawer open. Final deliverable as image would be ideal 👍🏻

**Comment by Jeff-TWU** [comment]
@karenroeck Let me know what you think.
![20210301_PSYC 330 Infographic](https://user-images.githubusercontent.com/66963480/109708453-48911580-7b50-11eb-919d-5acbec7425d6.jpg)

**Comment by karenroeck** [comment]
Briliant! The SME is thrilled with the graphic as-is. Thanks so much, Jeff!

**Comment by Jeff-TWU** [comment]
@karenroeck Nice! That was faster than I expected.
