### ISSUE TITLE
PSYC 330 intro videos

### ISSUE THREAD

**Issue by karenroeck** [TWUOnline/bug-tracking#448]
### Course
PSYC 330: Leadership in Organizations & Small Groups

### Instructions
- Jeff, please add title slides (PSYC 330) and a lower third to each of the videos with the following:
**Mark Warren, M.Ed., B.A.
Instructor, TWU Bellingham Extension Campus**

**Note:** This course launches March 8, so the Course Overview and Week 1 videos are needed ASAP.

Please upload required files as attachments.
[Course Overview](https://web.microsoftstream.com/video/c0a8000f-ff98-4072-a354-780184d4a0e5)
[Week 1](https://web.microsoftstream.com/video/31d9e8bc-0a53-41c1-ace9-1cee5c82bc60)
[Week 2](https://web.microsoftstream.com/video/c34cca85-a33c-4371-9d9d-e76323be7dd5)
[Week 3](https://web.microsoftstream.com/video/abf8045b-522d-4fa5-b703-e7aab9b9e0bf)
[Week 4](https://web.microsoftstream.com/video/626901a9-f303-44cb-80a7-bd6ca3e6ec1e)
[Week 5](https://web.microsoftstream.com/video/db681f34-a78d-46f4-b095-1a126aec4f86)
[Week 6](https://web.microsoftstream.com/video/f0eccbbe-a0aa-4f43-a2a1-daca8375b850)

**Comment by Jeff-TWU** [comment]
@karenroeck Will do. Timeline should not be a problem. Thanks!

**Comment by Jeff-TWU** [comment]
@karenroeck Hi Karen here are the videos. 

-Does you want different titles?

-In terms of delivery, is pasting in hyperlinks like this ok, or would pasting the embed code be more beneficial?
[Intro](https://web.microsoftstream.com/video/c5e2da74-f010-4207-bebe-5f2be60f461b)
[Session 1](https://web.microsoftstream.com/video/d6c44789-fc2e-4993-aaf5-e84ef1ade480)
[Session 2](https://web.microsoftstream.com/video/d660cb79-4b17-4820-8519-b89b1517b789)
[Session 3](https://web.microsoftstream.com/video/9d93380d-6409-48e0-913a-a6c07a4b002c)
[Session 4](https://web.microsoftstream.com/video/cd5917d2-6ae6-40de-999b-e29e7cb265ec)
[Session 5](https://web.microsoftstream.com/video/57aab9db-acaf-41d2-babc-4e6c9a6d2818)
[Session 6](https://web.microsoftstream.com/video/082e999e-8215-47c1-b306-b0c3a217aa58)

@karenroeck @cmadland 
Now that I've been working a few months, I have some clarifying questions on how I might make things easier for IDs  :)

-My understanding is that channels are auto generated when a course is created in Moodle. If I do not find a channel for a course should I create one and add videos to it? 

-By default, if I find a channel for a course, should I be adding the videos to it, or is that a case-by-case decision to be made by the ID?   

-By default, when I upload a video, I give both the 'Learning Design' group and the prof owner access. I'm assuming profs should have owner access, is that a fair assumption?

-By default I am allowing company wide access. Is this a course-by-course decision to be made by the ID?

**Comment by karenroeck** [comment]
@Jeff-TWU Thanks for all your work on these! Answers to your questions below in **bold:**

-Does you want different titles? **Yes - for the first video, please change it to "WELCOME TO PSYC 330" with the subtitle "LEADERSHIP IN ORGANIZATIONS & SMALL GROUPS." The other videos should say "Week" instead of "Session" please.**

-In terms of delivery, is pasting in hyperlinks like this ok, or would pasting the embed code be more beneficial? **Pasting the hyperlinks is great. As long as the ID is also an owner, they will be able to grab the embed code they need.**

Now that I've been working a few months, I have some clarifying questions on how I might make things easier for IDs :)

-My understanding is that channels are auto generated when a course is created in Moodle. If I do not find a channel for a course should I create one and add videos to it? **Not quite. MS Stream *Groups* are auto generated by our registration software Jenzabar. The prof is given ownership of this group and all registered students are automatically added. Channels live within groups and their primary function is like that of a YouTube Playlist. At TWU, we generally use channels for limited access to synchronous session Zoom recordings/webinars. We don't really need channels to organize introductory videos, such as these for PSYC 330. Since all videos are companywide access and embedded as one-offs versus a playlist, the channel is kind of a moot point.**

-By default, if I find a channel for a course, should I be adding the videos to it, or is that a case-by-case decision to be made by the ID? **Unless a prof grants you access to their group or channel, you will not be able to add videos (same goes for IDs).**

-By default, when I upload a video, I give both the 'Learning Design' group and the prof owner access. I'm assuming profs should have owner access, is that a fair assumption? **It doesn't hurt to give profs owner access, but honestly, most of our SMEs are unfamiliar with how MS Stream works. If you give the LD group owner access, then IDs can assign prof access if/when needed.**

-By default I am allowing company wide access. Is this a course-by-course decision to be made by the ID? **Yes, companywide access as a default is the way to go. The ID will let you know if access should be limited in any way.**

**Comment by Jeff-TWU** [comment]
@karenroeck Thanks for your input! 

Video titles have been updated. Please let me know if you need anything else.

[Intro](https://web.microsoftstream.com/video/c5e2da74-f010-4207-bebe-5f2be60f461b)
[Week 1](https://web.microsoftstream.com/video/d6c44789-fc2e-4993-aaf5-e84ef1ade480)
[Week 2](https://web.microsoftstream.com/video/d660cb79-4b17-4820-8519-b89b1517b789)
[Week 3](https://web.microsoftstream.com/video/9d93380d-6409-48e0-913a-a6c07a4b002c)
[Week 4](https://web.microsoftstream.com/video/cd5917d2-6ae6-40de-999b-e29e7cb265ec)
[Week 5](https://web.microsoftstream.com/video/57aab9db-acaf-41d2-babc-4e6c9a6d2818)
[Week 6](https://web.microsoftstream.com/video/082e999e-8215-47c1-b306-b0c3a217aa58)

**Comment by karenroeck** [comment]
Amazing! They look great. Thanks again!

**Comment by Jeff-TWU** [comment]
@karenroeck Welcome!
