### ISSUE TITLE
image replacement

### ISSUE THREAD

**Issue by rezakh66** [TWUOnline/bug-tracking#45]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 MCOM 281
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 there is a note for Kelly to replace the image.
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=10713&section=1
2. Unit #  1       Topic #    1     Activity#  
 
**Optional: Screenshots**  

![Image 7-17-1398 AP at 12 08 3](https://user-images.githubusercontent.com/55214859/66512623-2e9ff000-ea8e-11e9-9476-6892464ac9de.jpg)

**Comment by kmarjanovic** [comment]
Please replace with 
https://commons.wikimedia.org/wiki/File:Shannon_communication_system.svg

**Comment by faitht1023** [comment]
added image
