### ISSUE TITLE
LDRS 624 Unit 3 Production

### ISSUE THREAD

**Issue by karenroeck** [TWUOnline/bug-tracking#450]
### Course

LDRS 624: School Leadership and Supervision (FAR MASTER)

### URL

https://learn.twu.ca/course/view.php?id=15704&section=3

### Instructions
- [x] Hi Reza, please add Unit 3 in Atom.

Please upload required files as attachments.
[LDRS_624_Unit_3.docx](https://github.com/TWUOnline/bug-tracking/files/6064477/LDRS_624_Unit_3.docx)

**Comment by rezakh66** [comment]
Hi @karenroeck I have uploaded unit 3. This course formatting is slick. well done Karen.

**Comment by karenroeck** [comment]
Thank you, Reza! This made my day :)
