### ISSUE TITLE
PSYC 207 Videos

### ISSUE THREAD

**Issue by Jeff-TWU** [TWUOnline/bug-tracking#451]
Convert PPT recordings to videos

[Link to PPT Files](https://mytwu-my.sharepoint.com/personal/melanie_laurie_twu_ca/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fmelanie%5Flaurie%5Ftwu%5Fca%2FDocuments%2FPSYC%20207%2Fppt%20to%20video&originalPath=aHR0cHM6Ly9teXR3dS1teS5zaGFyZXBvaW50LmNvbS86ZjovZy9wZXJzb25hbC9tZWxhbmllX2xhdXJpZV90d3VfY2EvRWozRUFMckRlZnBEbUszZVNRSmJUVlFCN1JrZnFWUnFjUXpKaGRwZEFFUHpMUT9ydGltZT1sOTJTcklzVjJVZw)

**Comment by Jeff-TWU** [comment]
Hi @mellaurie , do you know of any other videos that need to be made for this, or can I mark this as complete?

**Comment by mellaurie** [comment]
Hi @Jeff-TWU!!  We will have more ppts to convert for Units 4-6.  I will let you know when the next batch is in the folder and ready for you.

**Comment by Jeff-TWU** [comment]
@mellaurie Sounds good! No rush on my end. :) Thanks for the update.

**Comment by Jeff-TWU** [comment]
@mellaurie Looks like there are [a few more files in](https://mytwu-my.sharepoint.com/personal/melanie_laurie_twu_ca/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fmelanie%5Flaurie%5Ftwu%5Fca%2FDocuments%2FPSYC%20207%2Fppt%20to%20video&originalPath=aHR0cHM6Ly9teXR3dS1teS5zaGFyZXBvaW50LmNvbS86ZjovZy9wZXJzb25hbC9tZWxhbmllX2xhdXJpZV90d3VfY2EvRWozRUFMckRlZnBEbUszZVNRSmJUVlFCN1JrZnFWUnFjUXpKaGRwZEFFUHpMUT9ydGltZT1sOTJTcklzVjJVZw). Would you mind renaming the files themselves to what you'd like them to ultimately be? I think that will be easiest (assuming you can use all the characters you need, naming the file). Please let me know. Thanks!

**Comment by mellaurie** [comment]
@Jeff-TWU The names are correct. They are ready to go.  Thanks!

**Comment by Jeff-TWU** [comment]
@mellaurie Awesome. Thanks!
