### ISSUE TITLE
SOCI 201 Production

### ISSUE THREAD

**Issue by mellaurie** [TWUOnline/bug-tracking#453]
### Instructions
- [x] Please create Moodle shell for ADC Master
- [x] Please set up course in arts-master repo
- [x] Please upload Unit 1

Please upload required files as attachments. [SOCI201_U1_Mar3.docx](https://github.com/TWUOnline/bug-tracking/files/6085664/SOCI201_U1_Mar3.docx)

**Comment by rezakh66** [comment]
Hi @mellaurie I uploaded u1 [here](https://learn.twu.ca/course/view.php?id=18696&section=1).

**Comment by mellaurie** [comment]
Hi @rezakh66 Unit 2 and 3 are ready to be uploaded.

Thanks for all your help in this!!

[SOCI201_U2.docx](https://github.com/TWUOnline/bug-tracking/files/6266330/SOCI201_U2.docx)
[SOCI 201_U3.docx](https://github.com/TWUOnline/bug-tracking/files/6266331/SOCI.201_U3.docx)

**Comment by rezakh66** [comment]
Hi @mellaurie I uploaded both units.Have a nice evening.

**Comment by mellaurie** [comment]
Hi again @rezakh66!  Can you upload this unit for me asap?  Thanks so much!
[SOCI 201_U4.docx](https://github.com/TWUOnline/bug-tracking/files/6469457/SOCI.201_U4.docx)

**Comment by rezakh66** [comment]
@mellaurie sure, it should be uploaded by 5 PM.

**Comment by mellaurie** [comment]
You're amazing @rezakh66.  Thank you!

**Comment by rezakh66** [comment]
@mellaurie Unit 4 is ready.Your welcome.

**Comment by rezakh66** [comment]
Hi, Following changes requested by Debra are made to the Github:
1. 
There’s a typo on the poem besides the artwork – on the second last line it should say “….in this world” (not I) 
2. 
Under Required text for the second reference, the Seaton book, please delete what is in brackets and replace it with (This booklet is provided on this course as a PDF download).

3. 
Please replace the Course Evaluation with the updated one on the attached syllabus. 

Under the Assignments tab, please insert the same chart from #3 in this spot as well.

**Comment by rezakh66** [comment]
Following changes are made to the course requested by Debra Hanenburg: 
Changes to make on SOCI 201 OL – both the Master Course AND FALL 2021
Unit 1, Topic 1, Activity 1.1 – delete the part in brackets and add (See PowerPoint under the Course Resources Tab)
Unit 1, Topic 3, Activity 1.3 – change (add link) to (See PowerPoint under the Course Resources Tab)
Unit 2, Overview – under Resources – ADD “Rent Freedom Writers Film” 
Unit 2, Topic 3, Activity 2.3 – Remove “Cultural Map” – the link is broken
Unit 2, Activity 2.5 – Remove “View and Discuss” and replace with “Watch Freedom Writers Film”. Take out last two sentences that starts with “We will be…..” Add – This film is central to your final paper. See assignment instructions under the Assignments Tab. 
For Unit 1-5 there is an Assessment section that refers to completing the discussion forum. Please add at the end of all these, “Please see Syllabus and the Assignments Tab for other assignments and due dates”.  
Unit 6: Wrapping up – delete number 1 and 2. Replace with “Please see Syllabus and the Assignments Tab for other assignments and due dates”.
