### ISSUE TITLE
LDRS 627 Production

### ISSUE THREAD

**Issue by mellaurie** [TWUOnline/bug-tracking#456]
### Instructions
- [x] Please re-number activities to match with the new unit numbers for Unit 5-7
- [x] Create alerts for Activity Checklists and Learning Activities for Units 1, 2, 5, 6, 7 (skip Unit 3 and 4 right now)
- [x] If you have time, check for broken links for Units 1, 2, 5-7

Thank you so much for your help with this!!  This course starts Mar 22, 2021.

**Comment by rezakh66** [comment]
Hi @mellaurie I have made the changes. i have created the alerts for unit 2 and 3 as well.

**Comment by mellaurie** [comment]
Thank you so much @rezakh66 !!!
