### ISSUE TITLE
LDRS 624 Unit 5 production

### ISSUE THREAD

**Issue by karenroeck** [TWUOnline/bug-tracking#457]
### Course

LDRS 624: School Leadership & Supervision (FAR MASTER)

### URL

https://learn.twu.ca/course/view.php?id=15704&section=5

### Instructions
@rezakh66 Please upload Unit 5 and the Facilitator's Guide (both attached).

Please upload required files as attachments.
[LDRS_624_Facilitator_Guide.docx](https://github.com/TWUOnline/bug-tracking/files/6143208/LDRS_624_Facilitator_Guide.docx)
[LDRS_624_Unit_5.docx](https://github.com/TWUOnline/bug-tracking/files/6143209/LDRS_624_Unit_5.docx)

**Comment by rezakh66** [comment]
Hi @karenroeck Unit 5 and the facilitator's guide are both uploaded

**Comment by karenroeck** [comment]
Awesome - thanks @rezakh66!
