### ISSUE TITLE
H5P Drag and Drop

### ISSUE THREAD

**Issue by karenroeck** [TWUOnline/bug-tracking#459]
### Course

LDRS 624: School Leadership & Supervision (FAR MASTER)

### URL

https://learn.twu.ca/course/view.php?id=15704&section=5

### Instructions
@Jeff-TWU, please create a drag and drop activity similar to [this one](https://create.twu.ca/h5p/wp-admin/admin.php?page=h5p&task=show&id=129) with the following info (I'm open to other suggestions if you have ideas):

Three categories: 
-Character
-Competence
-Collaboration

Moveable labels: 
- Setting strategic direction
- Leading the organization
- Ensuring accountability
- Developing people
- Building relationships
- Shifting the narrative
- Securing agreement about what a year’s progress looks like
- Expect a year’s worth of progress
- Develop new assessment and evaluation tools to provide feedback to teachers
- Know thy impact
- Ensure teachers have expertise in diagnosis
- Interventions
- Evaluation
- Stop ignoring what we know and scale up
- Linking autonomy to a year’s progress

Please upload required files as attachments.

**Comment by Jeff-TWU** [comment]
@karenroeck Hi Karen, might you have an answer key for me? I'm happy to guess if you like ;) Not sure how beneficial that will be though.

**Comment by karenroeck** [comment]
Ah good question :) There is no **right answer** - students will sort the labels based on their own experiences and priorities. In that sense, we need all labels to be eligible for all categories.

**Comment by Jeff-TWU** [comment]
@karenroeck Gotcha. Sounds good. Thanks!

**Comment by Jeff-TWU** [comment]
@karenroeck Here is the [link](https://create.twu.ca/h5p/wp-admin/admin.php?page=h5p&task=show&id=251). H5p was a frustration for my designer brain. It's not possible to get be pixel accurate. I had to resort to the text which was listed by centre aligning all text, no real alignment tools. My original plan was to use images. It would have looked like this.
![Original vision](https://user-images.githubusercontent.com/66963480/111706396-75efeb80-87ff-11eb-8c54-28dfb0b30bb1.png)

Let me know what changes you have.

**Comment by karenroeck** [comment]
@Jeff-TWU Looks great to me! Other than the white lines beside the text, I can't see the difference between the image you have here and the H5P.....? I know what you mean about the pixels - would an online pixel converter help?

**Comment by Jeff-TWU** [comment]
@karenroeck Unfortunately that would not help. The issue is that H5P is adding height to images, even when I specify exactly how many pixels and image should be. It's fine. I'll take some melatonin tonight so I can sleep. :)

**Comment by karenroeck** [comment]
Gah, that is sooo frustrating!! At least you have the soothing sound of pounding raindrops to lull you to sleep tonight...
