### ISSUE TITLE
LDRS 500 ON Fall 2019: Learning Activity 4.3

### ISSUE THREAD

**Issue by cpenfoldnavarro** [TWUOnline/bug-tracking#46]
**Which course contains the bug?**  
LDRS 500 Online Fall 2019
 
 
**Describe the error and/or your suggestion**  
In the Unit 4 Learning Activity list, it should read "Authentic Leadership" instead of "Transformational Leadership"
Activity 4.3
Community of Inquiry (graded discussion). Choose three principles of **Authentic** Leadership and give an example of each principle in a new discussion post.
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=9714&section=5
2. Unit #   4      Topic #   Overview      Activity#  4.3
 
**Optional: Screenshots**

**Comment by faitht1023** [comment]
edited
