### ISSUE TITLE
LDRS 300 quizzes

### ISSUE THREAD

**Issue by karenroeck** [TWUOnline/bug-tracking#460]
**Which course contains the bug?**  
LDRS 300 - Leadership as Service (FAR Master)
 
**Describe the error and/or your suggestion**  
@rezakh66 SME Brenda-Lee Sasaki has some Moodle quiz edit requests. See attached Word doc.
 
**Location of the bug**  
https://learn.twu.ca/course/view.php?id=10828&section=16 

**Attachments**
[LDRS 300 IF FAR Master Assessment Tab Revisions (quizzes).docx](https://github.com/TWUOnline/bug-tracking/files/6160432/LDRS.300.IF.FAR.Master.Assessment.Tab.Revisions.quizzes.docx)

**Comment by rezakh66** [comment]
Hi @karenroeck I have made the changes. She has asked regarding the order of questions. Please let her know that questions are reordered and as of now shuffle check box is not selected but when selected, the order of questions for each student would be different.

**Comment by karenroeck** [comment]
@rezakh66 Thanks so much - I'll pass along the message!
