### ISSUE TITLE
PSYC 301 interactive worksheets

### ISSUE THREAD

**Issue by karenroeck** [TWUOnline/bug-tracking#461]
### Course

PSYC 301: Theories of Personality (ADC MASTER)

### URL

https://learn.twu.ca/course/view.php?id=18759&section=9

### Instructions

@Jeff-TWU, under "Assessment" -> "Projects," there are three PDFs (Jay Hall Survey, Keirsey Temperament Sorter, Alderian Life-Style Analysis). Students need to complete the listed activities, but they are currently in old school pen and paper format. Could you take a look and let me know if there is a way to digitize these so students can just complete them online (or on their desktop)?

**Comment by karenroeck** [comment]
FYI the course starts April 26, so anytime before that would be swell.

**Comment by Jeff-TWU** [comment]
@karenroeck Are you thinking a fillable PDF?  That wouldn't be too difficult. Or do you want a form, like [Gravity Forms](https://www.gravityforms.com), that would collect information?

**Comment by karenroeck** [comment]
@Jeff-TWU Fillable PDF would do the trick for sure - it is a self-assessment worksheet that does not need to be submitted to the instructor. Thanks!

**Comment by Jeff-TWU** [comment]
@karenroeck All done! Let me know if you need any changes. Tested and everything works fine. The one caveat is that these files should only be filled out using [Adobe Acrobat](https://get.adobe.com/reader/). For the future, if we anticipate similar tasks, it would likely be worth investing in a form builder. Acrobat has got to be about the jankiest "professional" software I've ever had to use.  
[PSYC_301_Alderian.pdf](https://github.com/TWUOnline/bug-tracking/files/6352931/PSYC_301_Alderian.pdf)
[PSYC_301_Jay_Hall_Survey.pdf](https://github.com/TWUOnline/bug-tracking/files/6352932/PSYC_301_Jay_Hall_Survey.pdf)
[PSYC_301_Keirsey.pdf](https://github.com/TWUOnline/bug-tracking/files/6352933/PSYC_301_Keirsey.pdf)

**Comment by karenroeck** [comment]
Amazing! Thanks for working through the growing pains of Acrobat... @cmadland will have more to say about investing in a form builder.
