### ISSUE TITLE
LDRS 502 Gradebook issue

### ISSUE THREAD

**Issue by karenroeck** [TWUOnline/bug-tracking#462]
**Which course contains the bug?**  
LDRS 502 IN SP 2021

**Describe the error and/or your suggestion**  
When the instructor tries to enter student grades using the Turnitin system, the grades will not display in Moodle gradebook. 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/grade/report/grader/index.php?id=16582
2. Dropbox: Personal Reflection and Application Project
 
**Optional: Screenshots**  
![LDRS 502 gradebook issue](https://user-images.githubusercontent.com/67760065/114627253-d260f200-9c69-11eb-9026-6369e943fd30.png)

**Comment by rezakh66** [comment]
Hi @karenroeck I fixed that. seems the Reflection activity was locked so the grades in Turnitin did not synch with the grade book. now graded papers are populated in the grade book. Hidden from students though.

**Comment by karenroeck** [comment]
@rezakh66 Thanks so much - Dr Mo will be very grateful!
