### ISSUE TITLE
LDRS 625 units

### ISSUE THREAD

**Issue by JessD9** [TWUOnline/bug-tracking#466]
### Instructions
- @rezakh66 Please upload Units 1 & 2 to GiHub/Atom (may need to create ldrs 625 folder in Github)
- Please copy/paste same Course Introduction from LDRS 301 (I will edit later)

[LDRS_625_Unit1_May30_JD.docx](https://github.com/TWUOnline/bug-tracking/files/6622393/LDRS_625_Unit1_May30_JD.docx)

[Unit1_Resource_1_Values_Chart.pdf](https://github.com/TWUOnline/bug-tracking/files/6622398/Unit1_Resource_1_Values_Chart.pdf)

[wong_davey_Servant_Leadership.pdf](https://github.com/TWUOnline/bug-tracking/files/6622399/wong_davey_Servant_Leadership.pdf)

[LDRS_625_Unit2_May30_JD.docx](https://github.com/TWUOnline/bug-tracking/files/6622404/LDRS_625_Unit2_May30_JD.docx)

[LDRS625_U2_Topic2_slides.pptx](https://github.com/TWUOnline/bug-tracking/files/6622406/LDRS625_U2_Topic2_slides.pptx)

**Comment by rezakh66** [comment]
Hi @JessD9 Units 1 & 2 are uploaded.

**Comment by JessD9** [comment]
Thanks Reza!

**Comment by JessD9** [comment]
@rezakh66 Please upload Units 3-6. 

[LDRS625_U3_JULY2_JD.docx](https://github.com/TWUOnline/bug-tracking/files/6757814/LDRS625_U3_JULY2_JD.docx)

[LDRS625_U4_JULY2_JD.docx](https://github.com/TWUOnline/bug-tracking/files/6757815/LDRS625_U4_JULY2_JD.docx)

[LDRS625_U5_JULY2_JD.docx](https://github.com/TWUOnline/bug-tracking/files/6757817/LDRS625_U5_JULY2_JD.docx)

[LDRS625_U6_JULY2_JD.docx](https://github.com/TWUOnline/bug-tracking/files/6757818/LDRS625_U6_JULY2_JD.docx)

**Comment by JessD9** [comment]
@rezakh66 Thanks for uploading these. When you have time, can you also convert Units 1 & 2 to the new format?

**Comment by rezakh66** [comment]
Hi @JessD9 Sure, there are some formattings left though for units 3-6.

**Comment by JessD9** [comment]
np

**Comment by rezakh66** [comment]
Hi @JessD9 Unit 1-6 are ready

**Comment by JessD9** [comment]
Great, thanks @rezakh66:)

**Comment by JessD9** [comment]
@rezakh66 Here are Units 7-9. 

Note:
- Unit 7 has no Learning Activities
- Please embed PDF into Unit 8 (L.A. 8.2)
- Please embed PDF into Unit 9 (L.A. 9.1)
Thanks!

[LDRS625_U7_AUG22_JD.docx](https://github.com/TWUOnline/bug-tracking/files/7030374/LDRS625_U7_AUG22_JD.docx)

[LDRS625_U8_AUG22_JD.docx](https://github.com/TWUOnline/bug-tracking/files/7030388/LDRS625_U8_AUG22_JD.docx)
[LDRS625_U8_Case_Study.pdf](https://github.com/TWUOnline/bug-tracking/files/7030389/LDRS625_U8_Case_Study.pdf)

[LDRS625_U9_AUG23_JD.docx](https://github.com/TWUOnline/bug-tracking/files/7030390/LDRS625_U9_AUG23_JD.docx)
[LDRS625_U9_Learning_Activity.pdf](https://github.com/TWUOnline/bug-tracking/files/7030392/LDRS625_U9_Learning_Activity.pdf)

**Comment by rezakh66** [comment]
Hi @JessD9 Units 7-9 are uploaded and inserted in LDRS 625 Moodle page.

**Comment by JessD9** [comment]
Hi @rezakh66. Here's the last unit: 

[LDRS625_U10_SEPT08_JD.docx](https://github.com/TWUOnline/bug-tracking/files/7127715/LDRS625_U10_SEPT08_JD.docx)

[LDRS_625_U10_rubric.docx](https://github.com/TWUOnline/bug-tracking/files/7127710/LDRS_625_U10_rubric.docx)

- Please insert “LDRS_625_U10_RUBRIC” into Topic 3

Thanks
