### ISSUE TITLE
LDRS 620 H5P Issue

### ISSUE THREAD

**Issue by karenroeck** [TWUOnline/bug-tracking#467]
**Which course contains the bug?**  
LDRS 620 FAR MASTER 
 
**Describe the error and/or your suggestion**  
Learning Activity 5.2 contains a fill in the blank H5P activity; however, when students fill in the correct answer with correct spelling, they are marked wrong.
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL: https://learn.twu.ca/course/view.php?id=15710&section=5#tabs-tree-start
2. Unit 5         Topic 2         Activity 5.2  
 
**Optional: Screenshots**  
![LDRS 620 Activity 5 2](https://user-images.githubusercontent.com/67760065/122647041-27d8d580-d0d7-11eb-9174-bb40a8b5541a.jpg)

**Comment by Jeff-TWU** [comment]
@karenroeck @cmadland Fixed. It looks like a strong/bold HTML tag was used in the answer key. This is why you see the opening "<strong>" tag at the beginning of the correct answer. SMEs/IDs should be aware that styling should not be used pluggin in answers in the answer key.

**Comment by karenroeck** [comment]
@Jeff-TWU Ah, makes sense. Thanks for taking care of this!
