### ISSUE TITLE
LDRS 617

### ISSUE THREAD

**Issue by MaraChequer** [TWUOnline/bug-tracking#468]
From unit 1 to 5 all editions must show in 2 course shells one for business and one for healthcare. From 6 to 12 both courses need independent folders.

**Comment by rezakh66** [comment]
Hi @MaraChequer Now we have two folders for LDRS 617. We can utilize LDRS 617 units 1-5 for common contents in both health and business, and use units 6-12 only for business. the second folder is LDRS 617health which will be used to upload health content for units 6-12.

**Comment by MaraChequer** [comment]
Thank you @rezakh66
