### ISSUE TITLE
LDRS 612 Course Shell

### ISSUE THREAD

**Issue by dgaudet48** [TWUOnline/bug-tracking#469]
### Instructions
-  Can you create a master course development shell for LDRS 612 please?
- [ ]

Please upload required files as attachments.

**Comment by rezakh66** [comment]
Hi @dgaudet48 I created ldrs 612 both in LDRS-Master GitHub and Moodle. You are also enrolled in the Moodle shell as a manual course manager so you can enroll other participants as well.
