### ISSUE TITLE
LDRS 500 Online Unit 4: Second Error Needs to be fixed

### ISSUE THREAD

**Issue by cpenfoldnavarro** [TWUOnline/bug-tracking#47]
**Which course contains the bug?**  
LDRS 500 Online Fall 2019
 
 
**Describe the error and/or your suggestion**  
Learning Activity 4.3: Community of Inquiry (Discussion Post)
After viewing and reading the sources provided, provide a definition of this leadership theory. Choose three principles of **Authentic** Leadership and give an example of each principle in a new discussion post. Include an analysis of the potential strengths and challenges of each principle, how **Authentic** Leadership values align with the Christian virtues, and how a **authentic** leader influences organizational outcomes.

Pose one question that emerged from your analysis of this leadership theory. Respond to the questions of two other learners.

This writing will prepare you for the Leadership Theory paper.
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=9714&section=5
2. Unit #  4       Topic # Assessment        Activity#  4.3
 
**Optional: Screenshots**

**Comment by faitht1023** [comment]
changed to "authentic"
