### ISSUE TITLE
Video Interview for MCOM 353

### ISSUE THREAD

**Issue by mellaurie** [TWUOnline/bug-tracking#471]
### MCOM 353: Intro to Public Relations

Hi Jeff,

Wondering if we can book some time to film Divine soon.  He would like it Q&A style, but with the interviewer (potentially me) off screen.  Thoughts?  Here is the [script](https://mytwu-my.sharepoint.com/:w:/g/personal/melanie_laurie_twu_ca/ESa9yDKxpQxCqkPROc2pTTIBzrjrhYtR2au97nya7o57wg?e=Sb60lQ).

Thanks.
Mel

**Comment by Jeff-TWU** [comment]
@mellaurie I think the script could work depending on context.

Is this for Devine's class? Is it for another prof? if it's for another prof, that prof should be conducting the interview. If this is for Devine's own class, I don't think an interview makes as much sense.

If sticking with the interview format, the interviewer needs to give their own introduction beforehand (ideally having a rational for conducting the interview in the first place) and they should also introduce Devine at the beginning. The interviewer intro wouldn't have to be long, but there does needs to be more context.

**Comment by mellaurie** [comment]
This is for Divine's course, which at this point in time, he is planning on teaching.  I like your idea of adding an introduction before hand to provide context to the answers he has.  Could we do it where the question is just on a slide before his answer?  Something like [this](https://www.youtube.com/watch?v=mLzCqoPFxRw)?

**Comment by Jeff-TWU** [comment]
@mellaurie 

It could work. However, long text does not work well on title cards. 

ex. "What about integration with other areas of public relations? From your experience, to what extent do media relations people need to work in cooperation with other public relations specialists."

The production value of the example video is so-so. We can do better.

Title cards should be short.

The best thing to do would be to phrase all of the questions as statements. I could still use title cards to break things up, but wouldn't need to have a long question on screen for a long period of time.

ex. The question (interviewer) "How can students best prepare for a media relations job?" could be changed to ...

(Devine) **"As a student, here are some ways that can prepare for a job in media relations."**  

Title card might be: **Preparing for the Job**

I also don't think there is any rational for an interview if it's his own class/content. It might come across as pretentious? Just my opinion.

**Comment by mellaurie** [comment]
That makes a lot of sense.  When I meet with Divine next, I will discuss reformatting the interview.  I think a video would still be great, but maybe just more "lecture" style.  He has a lot of text in his course, so another form of media would be great. 

Thanks for your help!

**Comment by MaraChequer** [comment]
Link to Video https://www.dropbox.com/s/qyh817nbumnrypm/20220125_MCOM353%20Intro_Divine_R1.mp4?dl=0
