### ISSUE TITLE
Wordpress Tutorial Revamp

### ISSUE THREAD

**Issue by Jeff-TWU** [TWUOnline/bug-tracking#473]

**Comment by Jeff-TWU** [comment]
Hi @mellaurie Just needing some clarification on this.

I'm assuming that I'm revamping this first [video](https://web.microsoftstream.com/video/cf47d9c2-5a1c-42cd-9e7f-676b2df7cfcb?search=wordpress)?

I could also make it a standalone intro? Preference?

**Comment by mellaurie** [comment]
Hi @Jeff-TWU!

Yes, please replace the intro to that first video. Thanks!

**Comment by Jeff-TWU** [comment]
@mellaurie Would you like lower thirds? If so what would you like your name and title to be?

**Comment by mellaurie** [comment]
@Jeff-TWU Lower thirds = title banner across the bottom at the beginning?  If so, yes. How about:
 Melanie Laurie, Instructional Designer, Online Learning Team

Hopefully that's not too long.

**Comment by Jeff-TWU** [comment]
@mellaurie 
Yep, exactly. Should be fine.

**Comment by mellaurie** [comment]
@Jeff-TWU  Looks great.  Thank you so much!!

**Comment by Jeff-TWU** [comment]
Welcome!
