### ISSUE TITLE
FNDN 101 Production

### ISSUE THREAD

**Issue by mellaurie** [TWUOnline/bug-tracking#476]
### Instructions for all units
- [ ] Change the font from grey to black in the overview and the Unit Learning Outcomes section
- [ ] Make the font in Unit Learning Outcomes section larger.  I put 18 in the font size box in the styling tab.
- [ ] The Unit Learning Outcomes heading will also change to black.  Will need to change the color to dark blue.

**Comment by rezakh66** [comment]
Hi @mellaurie Please check unit 1 and see if that's what you want to be done for the rest of the units. Which font do you want for learning outcomes? Times New Roman?

**Comment by mellaurie** [comment]
Hi @rezakh66 Please see styling for Unit 4.  I think I like the default font vs. Times New Roman.  Joan is mainly concerned about the text being grey and small.  Thanks so much!

**Comment by mellaurie** [comment]
Hi @rezakh66!!  I need some help asap.

Can you import [FNDN 101 1 FA21](https://learn.twu.ca/course/view.php?id=19201) into FNDN 101 FA21 sections 2-42 and then  50 and 51.

Thanks so much! Mel

**Comment by rezakh66** [comment]
Hi @mellaurie I made the changes. Do you need this for FNDN GX? https://learn.twu.ca/course/view.php?id=20692

**Comment by mellaurie** [comment]
Thank you @rezakh66! 

Not for GX, as that section will have different info.
