### ISSUE TITLE
LDRS 612 - Dropdown box request

### ISSUE THREAD

**Issue by dgaudet48** [TWUOnline/bug-tracking#478]
### Instructions
- There are 5 Stages on the page - I was hoping you could create a dropdown box for each of the 5 Stages so that students can open one at a time (or all at once)
- [ ]

Please upload required files as attachments.

**Comment by rezakh66** [comment]
Hi @dgaudet48 The link that you have sent me is a dropbox, Do you need dropboxes within this dropbox? What we can do is to create a page and then link 5 dropboxes to the page. Page contents would be what you have in the Final assignment dropbox now. Please see "Final Assignment" pageunder unit 10.

**Comment by dgaudet48** [comment]
Hi @rezakh66  - Apologies, I think I used the wrong terminology...I am not looking for a dropbox. I am looking for an expandable textbox. Here is an example of what I mean from 501:

https://learn.twu.ca/course/view.php?id=15738&section=2#tabs-tree-start

The grey expandable boxes in Topic 3 are what I am after - I'd like the the stages on the assessment page I sent you set up in this manner...

Hopefully that makes more sense? If not, I can meet quickly with you and show you...?

Thank you again (and sorry for the confusion

**Comment by kmarjanovic** [comment]
I always forget the term too!  It's a collapsed content section: https://about.gitlab.com/handbook/markdown-guide/#collapse

**Comment by rezakh66** [comment]
Hi @dgaudet48 I created the collapsed menu. Please have a look and let me know if you need any further changes to be made.
