### ISSUE TITLE
LDRS 697 Unit 1 not showing

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#480]
**Which course contains the bug?**  
LDRS 697 - Leadership Integration Project (FAR MASTER) 
 
**Describe the error and/or your suggestion**  
Unit 1 not showing 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=15767&section=2#tabs-tree-start
2. Unit # 1

**Comment by rezakh66** [comment]
Hi @kmarjanovic This is fixed
