### ISSUE TITLE
LDRS 500 rubrics

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#481]
### Course
LDRS 500 - FAR & Flexible Masters

### URL
https://learn.twu.ca/course/view.php?id=20751&section=11#tabs-tree-start
(5 assignment rubrics are at the bottom of the page in Moodle - and in the assignment folder in Atom)

### Instructions
Please convert the rubric pdfs for all 5 assignments to a in-text rubric.   I'd like to keep the pdf as a reference for students, so the text can be:  
###Grading Criteria
Please see the following rubric that details how your instructor will grade your assignment.  Be sure to carefully read through each section and use it as a guide as you complete your work. (Also available as a pdf.)

**Comment by rezakh66** [comment]
Hi @kmarjanovic Do we have access to the .docx file?

**Comment by kmarjanovic** [comment]
@rezakh66 Here are the docs
[Case-Study-in-Leadership-Rubric.docx](https://github.com/TWUOnline/bug-tracking/files/7228036/Case-Study-in-Leadership-Rubric.docx)
[personal-leadership-story.docx](https://github.com/TWUOnline/bug-tracking/files/7228038/personal-leadership-story.docx)
[leadership-development-plan.docx](https://github.com/TWUOnline/bug-tracking/files/7228039/leadership-development-plan.docx)

[Critical-Analysis.docx](https://github.com/TWUOnline/bug-tracking/files/7228040/Critical-Analysis.docx)

Note there are 2 versions of this rubric - one for FAR and one for Online
[Community_of_Inquiry_Rubric_OL.docx](https://github.com/TWUOnline/bug-tracking/files/7228044/Community_of_Inquiry_Rubric_OL.docx)
[Community_of_Inquiry_Rubric_FAR.docx](https://github.com/TWUOnline/bug-tracking/files/7228045/Community_of_Inquiry_Rubric_FAR.docx)

Thank you!

**Comment by rezakh66** [comment]
@kmarjanovic I turned the rubrics into text tables. Please have a look and let me know if they need to be adjusted. Specifically for community of inquiry rubric.
Thank you.
