### ISSUE TITLE
Page navigation in Flexible courses missing unit intros

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#482]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 LDRS 627 - Flexible Master (& Jim's new section?)
 
**Describe the error and/or your suggestion**  
The last page of the unit goes to Topic 1 of the next unit.  It should go to the Unit Intro page (pretty crucial info students would miss).
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
e.g. Unit 2 https://learn.twu.ca/mod/page/view.php?id=557047

**Comment by mellaurie** [comment]
I wonder if this is a pages format limitation because the Moodle navigation at the bottom only tracks activity types, so the unit tab and content isn't considered.  The next activity according to Moodle is Topic 1 after the former unit's assessment activity.

**Comment by rezakh66** [comment]
Yes, it is. @mellaurie  Do we still need to keep this issue open?

**Comment by kmarjanovic** [comment]
@rezakh66 I still think we need to address this in case some faculty want to use the page format.
@mellaurie we could change the unit overview page to be just the unit title and image, and then have a page for the Overview...
Still not the best formatting option but at least students wouldn't miss the key info.

**Comment by kmarjanovic** [comment]
@rezakh66 @cmadland 
For all the flexible page courses - could we could change the unit overview page to be just the unit title and image, and then have a page for the Overview? (I forgot I proposed this solution in November!)

**Comment by rezakh66** [comment]
Hi @kmarjanovic I have done this in LDRS 500 [u1](https://learn.twu.ca/course/view.php?id=20751&section=1). Please have a look and let me know if I can proceed with the rest of the courses.

**Comment by kmarjanovic** [comment]
Hi @rezakh66 - it looks good!  
Could you add a label as well.  See the updated [Unit 1](https://learn.twu.ca/course/view.php?id=20751&section=1)

**Comment by kmarjanovic** [comment]
Hi @rezakh66 
I've changed the wording to: Click on the link below for an outline of this unit's topics, learning outcomes, and resources.
Also - for the new Overview page - please add the Unit #.
Thank you!

**Comment by kmarjanovic** [comment]
@MaraChequer @dgaudet48 @cmadland @MeeksonHundoo 
After chatting with Mara, we'd suggest that we not convert the Overview section to a new page because...
- Students will more likely click on the Unit tab than navigate to the next unit using the breadcrumbs at the bottom of the page
- They might skip the Overview page entirely and go right to the topics page, so best to have the overview show up right away.

Does this make sense? We can chat at our meeting on Wednesday - and then perhaps Meekson can change LDRS 500 back to having the Overview info all in that Unit tab?  (See [LDRS 504](https://learn.twu.ca/course/view.php?id=20826&section=1#tabs-tree-start))

Thanks all for your feedback!!!
