### ISSUE TITLE
LDRS 627 - Heading links

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#483]
**Which course contains the bug?**  
LDRS 627 Flexible Master 
 
**Describe the error and/or your suggestion**  
On most Headings in the course, when you hover on the title there is a blue attachment link icon that doesn't go anywhere.  
Can we remove these?
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
[LDRS 627 (Flexible)](https://learn.twu.ca/course/view.php?id=20746&section=6#tabs-tree-start)

**Comment by rezakh66** [comment]
Hi @kmarjanovic  I think it was decided to keep them like this, right?

**Comment by kmarjanovic** [comment]
I just noticed these links seem to be in most courses, so @cmadland is there a reason they are added?
  
They're definitely helpful if we're on the grav site, or in bookdown...but it doesn't make sense in Moodle as it doesn't link anywhere.  
Or are we letting students/instructors know that they can find their course online outside of Moodle? e.g. https://far.twu.ca/ldrs/591/readme
