### ISSUE TITLE
Academic Dishonesty Policy Button

### ISSUE THREAD

**Issue by mellaurie** [TWUOnline/bug-tracking#484]
**Which course contains the bug?**  
**ALL** of our courses that have this red button on the course home page
 
**Describe the error and/or your suggestion**  
Link leads to a 403 - Permission Denied 
 
Need to update to: [https://www.twu.ca/student-handbook/university-policies/academic-misconduct/procedures-dealing-acts-academic-0](https://www.twu.ca/student-handbook/university-policies/academic-misconduct/procedures-dealing-acts-academic-0)

**Comment by rezakh66** [comment]
Hi @mellaurie All links are updated in the following repositories: ba-lead,DLC-Help, far-community, fnas-master, nurs-master,samc-master, art-master,ldrs-master. Is there any more repository that I have missed?

**Comment by mellaurie** [comment]
Thanks @rezakh66!  That sounds like all the master repos.  @cmadland can you confirm?
