### ISSUE TITLE
Production - FAR Course imports

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#485]
### Course
FAR courses

### URL
search Moodle or see [GXP Master links](https://www.notion.so/twuid/Graduate-Express-Pathway-GXP-9efebda59ba34d54aa46803a98fe0373)

### Instructions
Once sections are created, please import Master shells and add instructors and facilitators
PHIL 210 – Paul Chamberlain & Facilitator: Emmanuel Denguessi 
WRT 101 – Shine Hong& Facilitators: 
SOCI 101 – Todd Martin & Facilitators: 
HIST 107 – Darren Provost & Facilitators: 
FNDN 101  – Rob Rhea; Facilitators: 
MCOM 281  – Ned Vankevich & Facilitators: Emmanuel Denguessi; Kathryn

@cmadland - checking whether this process works (OL does import, facilitators/instructors modify from there)

**Comment by kmarjanovic** [comment]
I see sections have been created:

[(WRTG 101 GX (FA21)](https://learn.twu.ca/course/view.php?id=20697) - done (instructor imported)
[HIST 107 GX (FA21)](https://learn.twu.ca/course/view.php?id=20693) - done (instructor imported)

[MCOM 281 GX (FA21)](https://learn.twu.ca/course/view.php?id=20694) - needs import
[PHIL 210 GX (FA21)](https://learn.twu.ca/course/view.php?id=20695&section=0#tabs-tree-start)  - needs import

[FNDN 101 GX (FA21)](https://learn.twu.ca/course/view.php?id=20692) - Is this course running for FAR? @mellaurie do students need to access the Moodle course, or is it all through the [FNDN 101 WP site](https://create.twu.ca/fndn101/)?

@cmadland we still need to clarify process: Who notifies instructor/facilitators when section is created? Are facilitators able to import (yes - but some may need tech support), if our online team is responsible for the import and content check, we need to be notified.

**Comment by mellaurie** [comment]
@kmarjanovic For FNDN 101, there is a specific WP site: https://create.twu.ca/fndn101gxp.  For UG, I do open up a Moodle section so that students know that they are enrolled in it (see [FNDN 101 FA21](https://learn.twu.ca/course/view.php?id=19201)).  Do we feel like that's necessary for GXP students?

**Comment by kmarjanovic** [comment]
@mellaurie in looking at the course in Moodle, the FAR/GXP students are enrolled there - and I assume they will use Moodle to see their final grades?  Could you copy what you've done for FA 21?  (or again, this should probably be the responsibility of the facilitator).
Perhaps we need a FNDN 101 FAR/GXP Master shell in Moodle so facilitators know which course to import (& have access to it).

**Comment by mellaurie** [comment]
@kmarjanovic @cmadland Let's discuss all this as I feel like we threw out an idea that maybe FNDN 101 GXP actually follows the Git/Moodle format rather than WP. So if we're going to make a Master (or if FNDN 101 UG gets a major revision like the other FNDN courses)...

Also, IT/registrar encourages all students to go to ICS to check their final grades and not to rely on Moodle gradebook.

**Comment by kmarjanovic** [comment]
Perhaps @emmanuelD-AFK and @catheryn-zuo can try importing?
See [guide to import](http://create.twu.ca/help/moodle/faculty/organization/importing-content-from-previous-cohort), and then in course settings check whether the course is hidden.

**Comment by mellaurie** [comment]
@kmarjanovic @emmanuelD-AFK @catheryn-zuo 
Sorry! I've already imported. Realized for GXP, I needed to use Rob's FNDN 101 Sp21 section and it needed to be un-Bundle-d too.

**Comment by kmarjanovic** [comment]
@mellaurie no worries!  All courses are imported now.  @cmadland we need to show facilitators how to do this...I'll try to create a resources/video to help.
