### ISSUE TITLE
PSYC 320 sections

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#486]
**Which course contains the bug?**  
- SOCI 320 OL (FA21)
 
**Describe the error and/or your suggestion**  
Could you make the Praxis Preparation (aka Unit 1), content to have the sections format?  For some reason it's only showing in the summary and assessment tabs.
Once the navigation pane is showing, we can delete the tabs in Moodle.
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=20505&section=1#tabs-tree-start
2. Unit #  Praxis Preparation  - all content in tab (child tabs should be deleted once navigation panel is restored)

**Comment by mellaurie** [comment]
Sorry!  Accidentally clicked the wrong button!

**Comment by rezakh66** [comment]
Hi @kmarjanovic I fixed this.

**Comment by kmarjanovic** [comment]
@rezakh66 thank you!

**Comment by rezakh66** [comment]
Following changes requested by DEBRA HANENBURG are made to the course :

1.	Under the General Tab – 
a.	Change “Welcome to SOCI 411: Human Services Practicum Two!
b.	Under learning objectives #6 – change “up to four…” to “three”
2.	Under the Praxis Preparation Tab – 
a.	Overview – change “300 hours” to 225 hours and at the end of “…of field experience…”  put this in parenthesis (over 3 practicum courses that are a full semester each)
b.	For Activity 1.2 change to “Attend Live Zoom Meeting on Monday, Jan.10th at 6 pm”
