### ISSUE TITLE
Course Cafe - unwanted buttons

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#487]
**Which course contains the bug?**  
Some courses with Course Cafe tab (LDRS 501...and others I will add cafe to)
 
**Describe the error and/or your suggestion**  
@rezakh66 can you help remove the buttons at the bottom of the page?

**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=20779&section=13 

![unwanted-buttons](https://user-images.githubusercontent.com/35148983/133545318-c1b8e4db-37b3-46b1-ade6-a6b0284919af.png)
 

Also - I see in Issue Tracking that this issue keeps coming up and that a couple IDs know the tricks? (@mellaurie )  Could someone write down the instructions so we can fix this ourselves?

**Comment by mellaurie** [comment]
@kmarjanovic I fix this one by changing the course cafe to a page.md instead of a section.md.  I think that's all it needs (@rezakh66 can you confirm?)

**Comment by kmarjanovic** [comment]
Thanks @mellaurie and @rezakh66 !!
I've added the notes to the OMG: https://www.notion.so/twuid/Course-Content-Development-e866f16f2d724f49b792df61e33941be
