### ISSUE TITLE
WRTG 101 Lesson 4 Presentation

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#5]
**Which course contains the bug?**
- Course Code and section e.g. WRTG 101 FAR Master

**Describe the error or your suggestion**
Make Presentation instead of pdf: Reference Guide for Developing Academic Tone

**Location of the bug**
Module 1, Lesson 4

**Comment by michaelamulder** [comment]
Presentation made. It's also on the presentation site. If you see anything that needs to be changed, please let me know @cmadland

**Comment by kmarjanovic** [comment]
Great! Thank you!
