### ISSUE TITLE
Production

### ISSUE THREAD

**Issue by cmadland** [TWUOnline/bug-tracking#50]
### WRSH101

https://github.com/TWUOnline/samc-master/commit/88620019a9cdc7337f73d8309dfa5d52545db4c3

### Instructions
- [x] Create 'Accordion' H5P from key terms
- [x] divide by unit and topic
- [x] insert shortcode in course content

Please upload required files as attachments.

**Comment by rezakh66** [comment]
Hi,
all are done in overview section.
please let me know if can fit them in a better section.

**Comment by cmadland** [comment]
@kmarjanovic has this been resolved?

**Comment by kmarjanovic** [comment]
@cmadland no - they are all in the overview section of each unit, but need to be moved to the specific learning activity in the unit.

**Comment by rezakh66** [comment]
@kmarjanovic can you please let me know where we need to move them exactly? headings  in WRSH 101_Oct4_JD.docx and topics in https://far.twu.ca/samc/wrsh101 are not well compatible.

**Comment by kmarjanovic** [comment]
You're right - sorry it wasn't clear!
I've moved all of the activities to their correct place.

@cmadland - Could we get help with this course this week as well (lots of formatting issues to resolve).  Course starts on Monday.
