### ISSUE TITLE
HIST 107 Assignments

### ISSUE THREAD

**Issue by cmadland** [TWUOnline/bug-tracking#51]
### HIST107

[https://far.twu.ca/arts/hist107/assignments](https://far.twu.ca/arts/hist107/assignments)

### Instructions
Could you help me set up tabs for HIST 107?  Within the Assessments tab, in the Research Proposal & Essay, I’d like 10 tabs with the assignment info (https://github.com/TWUOnline/arts-master/tree/master/pages/07.hist107/assignments). 
Raul put some things in Github (see Assignment 3 and Assignment 4), but there are some new documents.  Please let me know if you or an ATA can help.
https://learn.twu.ca/course/view.php?id=10809&section=7

 @kmarjanovic can you confirm that you want a table of contents in Grav here, rather than another layer of sub-topics in Moodle?

Thank you!

Please upload required files as attachments.

**Comment by kmarjanovic** [comment]
@cmadland yes please in Grav! Thank you!

**Comment by kmarjanovic** [comment]
Hi @345-Jay & @cmadland 
I've noticed there's tabs now in Moodle, but I can't seem to move them under the main sub tab [Research Proposal & Essay](https://learn.twu.ca/course/view.php?id=10809&section=10).

If this doesn't work, perhaps we can just have the tabs in Grav/Github?  Kind of like the Overview, Topics, etc. tabs on the left navigation pane. 

Do you mind populating Assignment 3 with the [assignment info sheets](https://github.com/TWUOnline/arts-master/tree/master/pages/07.hist107/assignments) and setting up the navigation?

**Comment by kmarjanovic** [comment]
@345-Jay let's for sure do the navigation pane on the left, rather than the tabs in Moodle.  It'll be much easier to navigate.

**Comment by 345-Jay** [comment]
Good morning, 

Ok will do. 

Sincerely, 

Jared McGill

**Comment by kmarjanovic** [comment]
@345-Jay or @cmadland 
Could you please set up the navigation for these pages?  I see them in [github](https://github.com/TWUOnline/arts-master/tree/master/pages/07.hist107/assignments/assignment-4) but it's not working/connecting to navigate in Moodle/Grav.
![image](https://user-images.githubusercontent.com/35148983/76124007-0d98e800-5fb7-11ea-94f2-2251710b5876.png)

**Comment by kmarjanovic** [comment]
@345-Jay or @cmadland do you need more info for this issue?

**Comment by 345-Jay** [comment]
Good afternoon,

Yes, it seems as if the changes that were being in made github weren't
showing up in moodle

Sincerely,

Jared McGill



<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by kmarjanovic** [comment]
@345-Jay  do you know the steps to make this happen?
@cmadland do we need a sections page?  E.g.:
---
title: 'Research Essay & Proposal'
date: '00:26 14-11-2018'
hide_page_title: false
show_sidebar: true
hide_git_sync_repo_link: false
visible: false
content:
    items: '@self.children'
    order:
        by: folder
        dir: asc
    limit: 0
---

**Comment by faitht1023** [comment]
@kmarjanovic this is currently what is in the page.md of the "Assignments" folder in HIST 107:

title: Assignments
date: '20:38 23-11-2018'
hide_page_title: false
show_sidebar: true
hide_git_sync_repo_link: false
visible: true
content:
    items: '@self.children'
    order:
        by: folder
        dir: asc
    limit: 0

Should this be edited to match what you have commented above?

**Comment by 345-Jay** [comment]
Good afternoon,

@faith I think Kelly was using that as an example for Colin and I. However
I believe the folder labelled "Assignments" should actually be labelled
assessments as the instructions for the HIST 107 issue looks specifically
at the "Research Proposal & Essay" being under the Assessment Tab.

Sincerely,

Jared McGill

**Comment by kmarjanovic** [comment]
@faitht1023 @345-Jay  @cmadland 
Any idea how to get the content to show?

**Comment by faitht1023** [comment]
@kmarjanovic I'm not sure which tab you're referring to - or if the tab is not there yet? I will check with Colin and see. I see the Moodle tabs but doesn't seem to be the left panel navigation yet.

**Comment by kmarjanovic** [comment]
@faitht1023 
Can you check in [Moodle](https://learn.twu.ca/course/view.php?id=10809&section=10)? 
Right now none of the Assessment info is showing so I'm not sure what happened.

This is the Research Proposal and Essay tab that I'm referring to:
![image](https://user-images.githubusercontent.com/35148983/80635131-b6dce700-8a18-11ea-9277-deaf4e138791.png)

**Comment by kmarjanovic** [comment]
@cmadland @faitht1023 @345-Jay 
Assignment info is still missing.  Is this due to Jared's comment above about relabeling Assignments?

**Comment by faitht1023** [comment]
@kmarjanovic I've tried renaming the folder, changing the frontmatter on the assignments to be the same as other page.md's that were working, and changing the assignments from page.md's to section.md's instead, but I haven't been able to figure out what the issue may be yet. I will look into it more. Would you have any suggestions?

**Comment by kmarjanovic** [comment]
@faitht1023 Sorry I don't know!  Help @cmadland !

Here's the embed code in Moodle - it was working before:
<p><iframe scrolling="yes" style="border: 0px #ffffff none;" src="https://far.twu.ca/arts/hist107/assignments/chromeless:true/hidepagetitle:true" allowfullscreen="allowfullscreen" width="100%" height="1000"></iframe></p>

**Comment by cmadland** [comment]
Diving in...

Sent from my iPhone

On May 1, 2020, at 1:26 PM, Kelly Marjanovic <notifications@github.com> wrote:

﻿

@faitht1023<https://github.com/faitht1023> Sorry I don't know! Help @cmadland<https://github.com/cmadland> !

Here's the embed code in Moodle - it was working before:

<iframe scrolling="yes" style="border: 0px #ffffff none;" src="https://far.twu.ca/arts/hist107/assignments/chromeless:true/hidepagetitle:true" allowfullscreen="allowfullscreen" width="100%" height="1000"></iframe>

**Comment by cmadland** [comment]
Ok sorted.

The URL in Moodle was looking for an ‘assignments’ folder, but should have been looking for ‘assessments’.

I’ve updated the urls.

Colin

Sent from my iPhone

On May 1, 2020, at 1:27 PM, Colin Madland <Colin.Madland@twu.ca> wrote:

﻿ Diving in...

Sent from my iPhone

On May 1, 2020, at 1:26 PM, Kelly Marjanovic <notifications@github.com> wrote:

﻿

@faitht1023<https://github.com/faitht1023> Sorry I don't know! Help @cmadland<https://github.com/cmadland> !

Here's the embed code in Moodle - it was working before:

<iframe scrolling="yes" style="border: 0px #ffffff none;" src="https://far.twu.ca/arts/hist107/assignments/chromeless:true/hidepagetitle:true" allowfullscreen="allowfullscreen" width="100%" height="1000"></iframe>

**Comment by kmarjanovic** [comment]
@cmadland @faitht1023 
Thanks Colin!
Now back to my original request from October...please help show all details for the research essay - chunking the info by putting it in Github folders/pages and having a navigation pane at the left.

See [LDRS 300 - Portfolio Assignment](https://learn.twu.ca/course/view.php?id=10828&section=14) as an example.

**Comment by kmarjanovic** [comment]
@cmadland @rezakh66 
Any update on this issue?  It's been 7 months since I made the request...

**Comment by rezakh66** [comment]
@kmarjanovic Hi, Now we have the "left sub-tabs". Lots of formatting need to be done. If you can send me the Docx files, I can do it.

**Comment by cmadland** [comment]
@kmarjanovic @rezakh66 I *think* I did a helpful thing. But I might have done an unhelpful thing.

I fixed the missing table of contents on the left side of the assignments page, then deleted some unnecessary Moodle pages. I REALLY hope there weren't a bunch of forums and assignment dropboxes on those pages!! 

This [commit fixed the ToC](https://github.com/TWUOnline/arts-master/commit/299e8eff49e122b6f9ffb58abf4326383f98c916#diff-74a0bd6879b53bfd1ca7d7d751ad9b4d) along with [this one](https://github.com/TWUOnline/arts-master/commit/c282e171d7f8a480f8ae476113a1c85af75aa2c9#diff-74a0bd6879b53bfd1ca7d7d751ad9b4d). Once that was done, the individual tabs in Moodle became redundant.

**Comment by kmarjanovic** [comment]
hmm...I prefer it the other way.  It's hard to navigate back to the other assessment pieces after you get to the essay tabs.  Plus, quizzes are a part of assessment.

**Comment by kmarjanovic** [comment]
@cmadland could you change it back?  I'd like all things related to the research essay (including essay proposal) in one area with the different tabs.  Then there are 4 other assessment types that should be separate.

**Comment by cmadland** [comment]
ok @kmarjanovic ...the 'Assessments' tab in Hist107 is in its final form, aside from some formatting tweaks on the Reseach paper section...

i hope...

**Comment by rezakh66** [comment]
@kmarjanovic I formatted research paper section with a few notes that need your feedback.

**Comment by kmarjanovic** [comment]
It's getting there!

I love the drop down menu for writing the paper - so definitely want to keep that.  I still think the proposal, essay, and all info sheets should be in one tab.

If you look at the hyperlinks in the proposal and essay sections - they link to the info sheets.  How do we link to sections in the drop down menu?

**Comment by cmadland** [comment]
We can link directly to one of the headings...

https://far.twu.ca/arts/hist107/writing-history#heading7

But all the headings fit on one page so it doesn't actually scroll down.

There are anchors on each of the headings inside the accordions, but apparently a direct link doesn't go there, at least in FireFox.
________________________________

**Comment by kmarjanovic** [comment]
Hmmm...
testing out having it all in the accordion.  Will change those link references to say - see section below - or something like that.

**Comment by cmadland** [comment]
That's not a bad idea at all, although it would take the Research essay item out of the ToC of all the assignments. Perhaps the 'section' page could contain a link to the accordion?

I tried the content-inject route and accordions don't play that song.

Colin

________________________________

**Comment by kmarjanovic** [comment]
See here: https://learn.twu.ca/course/view.php?id=10809&section=6
I think in one tab is best.  I'll take out of the other Assignments section.

**Comment by cmadland** [comment]
looks good...nice and clear.
________________________________

**Comment by kmarjanovic** [comment]
@cmadland @rezakh66 
Thank you both for all your help with this issue!!!
