### ISSUE TITLE
Characters in front of the final paragraph in course description

### ISSUE THREAD

**Issue by MargMannShull** [TWUOnline/bug-tracking#510]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 Psych 340 OL FA2021
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
!!It will be assumed that you have read, understand, and agree to the information provided at the 'Academic Dishonesty Policy' button below. If you have any questions at all please contact your instructor. [The two exclamation points at the start of this sentence should be removed.] 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=20392&section=0
2. Unit #  Course Overview       Topic #   Last full paragraph before the Academic Dishonesty policy      Activity#  
 
**Optional: Screenshots**

**Comment by MargMannShull** [comment]
Please update this in the FA2021 course as it has already been updated in the Master. Thank you

**Comment by kmarjanovic** [comment]
All fixed.
(@rezakh66 @cmadland I changed it to ***, as the ! don't seem to be working.  Any idea why?)
