### ISSUE TITLE
Video Analysis Assessment

### ISSUE THREAD

**Issue by MargMannShull** [TWUOnline/bug-tracking#511]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 Psych 340 OL FA2021
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
Please change the percentage of the grade to 50% instead of 40% in the assessment tab for this assignment.
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/editsection.php?id=249095&sr=10
2. Unit #  Assessments       Topic #  Video Recordings and Transcripts       Activity#  
 
**Optional: Screenshots**  
Video Recordings and Transcripts (40% of final grade) - change to 50%
Assignment 4.2 (Week 4): Video Upload with Transcript and Analysis

**Comment by MargMannShull** [comment]
Please update the FA2021 course as the Master is already done!  I try to edit this myself, but cannot make any changes???

**Comment by kmarjanovic** [comment]
All done.

Sorry @MargMannShull - most of the content is created through GitHub.  Things that change often (e.g. zoom links, due dates), we usually try to have created in Moodle so instructors can easily change.  Let me know if you'd like to meet to discuss any issues or I can show you how to make changes.
