### ISSUE TITLE
Introductory Video on Week 6 only accessible by YouTube

### ISSUE THREAD

**Issue by MargMannShull** [TWUOnline/bug-tracking#512]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019) Psych 340 OL FA2021
 
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
My introductory video to Week 6 says that it is only accessible on YouTube - this is a video that I made for the course and not one from YouTube - check out other weeks to see my other intros which appear to be accessible.
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=20392&section=6
2. Unit #     6    Topic #     Overview    Activity#  Overview video for week 6
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
Hi @MargMannShull ,
That was strange!  There was a youtube link instead of your video.  I fixed it, but please confirm it is the correct video.
Kelly

**Comment by MargMannShull** [comment]
Hi Kelly - it is the correct video - very strange!  Thank you!

Margaret Manning-Shull, MS., M.Div., LMHCA
Instructor, TWU-Bellingham Extension Campus

________________________________
