### ISSUE TITLE
Overview Section of Week 6

### ISSUE THREAD

**Issue by MargMannShull** [TWUOnline/bug-tracking#513]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019) Psych 340 OL FA2021
 
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
At the bottom of the overview section of Week 6, the blue tabs that either advance the students to the next topic or back to the previous unit, say Topic 1 on the right hand side, that is good, and hill on the left hand side.  I'm not sure why the Hill model of helping skills is a stand alone page tab/page - I looked in week 5 and cannot find any reference to the Hill model as a stand alone.  Not sure exactly what is happening here?  But, it should take students back to Week 5 topic 3/4 (cannot remember if there are three or four topics in week 5.
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=20392&section=6
2. Unit #   Week 6      Topic #     Overview    Activity#  
 
**Optional: Screenshots**  
[Course_ PSYC 340 OL - Interpersonal and Helping Skills (FA 2021), Topic_ Week 6.pdf](https://github.com/TWUOnline/bug-tracking/files/7494236/Course_.PSYC.340.OL.-.Interpersonal.and.Helping.Skills.FA.2021.Topic_.Week.6.pdf)

**Comment by rezakh66** [comment]
@MargMannShull I have moved it from the overview page to the bottom of the reference page. Is that ok?

**Comment by MargMannShull** [comment]
Yes!

Sent via the Samsung Galaxy S8, an AT&T 5G Evolution capable smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
