### ISSUE TITLE
Ranking Activity

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#514]
**Which course contains the bug?**  
LDRS 664 - but others may use it too
 
 
**Describe the error and/or your suggestion**  
Still looking for ranking activities - with no correct order.
will this work? https://github.com/surveyjs/survey-library/issues/2612
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://ma-lead.github.io/ldrs664/the-heart-of-a-teacher.html#activity-ranking

**Comment by cmadland** [comment]
Some thoughts...

This activity asks learners to 
- rank
- list strategies

Ranking is one thing, and the surveyjs looks like it might work, although the ranking won't be saved (I'm happy to test), but the listing strategies needs to happen somewhere else (blog post? written journal? forum?). Perhaps we suggest learners complete the whole thing in a journal while we test surveyjs?

**Comment by kmarjanovic** [comment]
Part 2 of that activity references the journal, but you're right, I should add that instruction earlier.

I was thinking too of the h5p journal 9[LDRS634 example](https://learn.twu.ca/mod/page/view.php?id=530639) but there is a lot references to the reflective learning journal - all optional and ungraded but connected to assessments of course.

I think perhaps we need some student feedback for this course - whether they find the ungraded activities helpful, are they doing them, etc.

**Comment by kmarjanovic** [comment]
I hadn't seen the Sort the Paragraphs H5P!  We're going to use it in SKLS 500 (unit 8).

Any idea if this can rank with no correct answer?
https://h5p.org/content-types/sort-the-paragraphs
