### ISSUE TITLE
Graphic request LDRS 664

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#515]
### Course
LDRS 664
### URL
https://ma-lead.github.io/ldrs664/creating-space-for-all-learners.html#creating-collaborative-learning-in-an-online-environment 
### Instructions
Could we make a graphic for the 8 principles of AI?

Here's an example I found online, but it's not very eye-catching!
Please upload required files as attachments.
![image](https://user-images.githubusercontent.com/35148983/141533113-b2187dd9-c659-4499-a899-50bcdbd1336b.png)

**Comment by MaraChequer** [comment]
Hi Kelly, yes, I think I can do something better than your example, do you have any particular idea or am I free to create something?

**Comment by MaraChequer** [comment]
![TheEightPrinciplesofAppreciativeInquiry-v2](https://user-images.githubusercontent.com/84353161/155433214-f21e0a99-246c-4681-9734-01355a956c3d.jpg)
![TheEightPrinciplesofAppreciativeInquiry-v1](https://user-images.githubusercontent.com/84353161/155433218-f6edd752-ddb1-4e86-a2a6-89b503888483.jpg)

**Comment by MaraChequer** [comment]
@kmarjanovic Please review. Two options. Please let me know if you would like another description of the concept for the first one.

**Comment by kmarjanovic** [comment]
@MaraChequer this is fantastic!!  Let's keep both options - the first being the go-to and the second in case the SME wants to add their own intro to the principles.

On both, could we make the text in the centre circle say "Principles of Appreciative Inquiry"  - and centre the text as well?

**Comment by MaraChequer** [comment]
I have updated the files @kmarjanovic ;)

**Comment by kmarjanovic** [comment]
Perfect!  Thanks @MaraChequer !!
