### ISSUE TITLE
LDRS 664 Credits

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#516]
**Which course contains the bug?**  
LDRS 664 bookdown
 
 
**Describe the error and/or your suggestion**  
Please add a page for Course Credits.  Note that I tried this last night and it erased the assessment page!  (I added the 98.credits rmd but it didn't work).

Content to add: 

# Course Credits {-}

### Curriculum Developer
***Catharine (Cathy) Penfold Navarro, Ph.D.***
Catharine Penfold Navarro, Ph.D., is a higher education leader and scholar with a focus on leadership, faculty and staff development, learning-centered teaching strategies, learning assessment, creating inclusive learning communities, and academic advising. Dr. Penfold Navarro is passionately committed to authentic learning and to creating inclusive learning experiences for students that result in meaningful connections with the discipline, faculty, and student colleagues.

Dr. Penfold Navarro served as the Vice Provost, Teaching + Learning at Trinity Western University from 2016-2018. Prior to her work at TWU, Dr. Penfold Navarro served as Project Director for a $1.89 million grant from the US Department of Education at Valencia College in Orlando, Florida. There she led faculty and staff in action research focused on the infusion of college success skills across the curriculum, and integrating learning-centered strategies into academic advising. At Valencia College, she also led the faculty of Student Success and provided administrative leadership for Learning in Community (LinC), Service Learning, and Supplemental Learning, designed to close the gaps in student achievement and facilitate student success.

Dr. Penfold Navarro has previously provided leadership for academic advising, faculty development, and student development initiatives at the University of Kentucky, Bluegrass Community and Technical College, Asbury College, and LCC International University in Lithuania.

### Course Instructors
- Cathy Penfold Navarro
- Daniel To
- Marilyn Ang

## Copyright & Credits
Copyright © Trinity Western University. All rights reserved.

The content of this course material is the property of Trinity Western University (TWU) and is protected by copyright law worldwide. This material may be used by students enrolled at TWU for personal study purposes only.

TWU seeks to ensure that any course content that is owned by others has been appropriately cleared for use in this course. Anyone wishing to make additional use of such third party material must obtain clearance from the copyright holder.
Course Development Team

Course Writer: Catharine Penfold Navarro, Ph.D.
Instructional Designer: Kelly Marjanovic, M.A., Cert. Learning Technologies
Production Team: Colin Madland, Manager of Online Learning and Instructional Technology;
Academic Director: Phil Laird, Ph.D., Vice President of Innovation, Global and Academic Partnerships

Trinity Western University
22500 University Drive
Langley, BC, Canada | V2Y 1Y1

 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
Please put it after the references page: https://ma-lead.github.io/ldrs664/references-6.html

**Comment by kmarjanovic** [comment]
@MeeksonHundoo any update on adding a credits page?  We'll likely add this to all our courses, so I'd like to see how the formatting works.
Thanks!

**Comment by MeeksonHundoo** [comment]
Hello @kmarjanovic. I would absolutely love to do this and keeping learning more about how to get content into bookdown format. However, I've just started working on how put content into a bookdown format like a month back and unfortunately my RStudio issues have plagued my learning and development. I'll contact Colin today and try to get this resolved at the earliest.

**Comment by kmarjanovic** [comment]
Thank you @cmadland !
https://ma-lead.github.io/ldrs664/course-credits.html
