### ISSUE TITLE
LDRS 664 rubrics

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#517]
**Which course contains the bug?**  
LDRS 664 bookdown
 
**Describe the error and/or your suggestion**  
Please help fix the rubric for the Company Website Analysis.

For now - let's go with the formatting Colin has suggested - but perhaps we can make it accordion style?
I'm going to search for better formatting this week...

**Location of the bug**  
https://ma-lead.github.io/ldrs664/assessment-10.html#company-website-analysis-rubric

**Comment by kmarjanovic** [comment]
Coming back to this issue...
@Jeff-TWU could you help format the rubrics in this course?  Accordion for the criteria?  Could we brainstorm?
https://ma-lead.github.io/ldrs664/assessment-10.html

I'd like this course featured on our website...but this has always been a troublesome page!

**Comment by Jeff-TWU** [comment]
> Coming back to this issue... @Jeff-TWU could you help format the rubrics in this course? Accordion for the criteria? Could we brainstorm? https://ma-lead.github.io/ldrs664/assessment-10.html
> 
> I'd like this course featured on our website...but this has always been a troublesome page!

@kmarjanovic Hi Kelly, I've [playing around with a table + an Accordion](https://ma-lead.github.io/ldrs664/assessment-10.html#assignment-identity-as-a-teacherfacilitator). I think it's much cleaner. Let me know if you like it and I'll adjust everything else. Will also need to update some formatting in the rest of the course.

**Comment by kmarjanovic** [comment]
Yes!! @Jeff-TWU you are a miracle worker!  Please update in this course.
