### ISSUE TITLE
LDRS 500 H5P text

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#518]
**Which course contains the bug?**  
LDRS 500 
 
**Describe the error and/or your suggestion**  
Could we reduce the text size in the H5P hotspots?
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
https://far.twu.ca/ldrs/500/u1/overview/filter:far/chromeless:true

https://learn.twu.ca/course/view.php?id=10719&section=1

**Comment by rezakh66** [comment]
@kmarjanovic I just checked that. It is already in smallest font size available.

**Comment by kmarjanovic** [comment]
Okay thanks for checking!!  It's funny - I saw some open H5Ps yesterday that had font way too small!!  They need to fix this issue!
