### ISSUE TITLE
LDRS 591 - bookdown activity questions

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#522]
### Course
LDRS 591
### URL
https://ma-lead.github.io/ldrs591/
### Instructions
For Units 3-10, could you copy the added questions from the [591 repo](https://github.com/TWUOnline/ldrs-master/tree/master/pages/15.591) and paste them into the bookdown learning activities?  See example from [unit 1](https://solid-winner-d993df4b.pages.github.io/introduction-to-scholarly-inquiry.html#learning-activity-watch-and-reflect).

The questions needed are in the alerts in 591...so lots of copying and pasting!!

Thank you!!!

**Comment by cmadland** [comment]
I've made the site public, which changed the URL to https://ma-lead.github.io/ldrs591/

**Comment by cmadland** [comment]
also updated the url in Moodle

**Comment by kmarjanovic** [comment]
Seems to be complete.  I'll check with Heather.
