### ISSUE TITLE
SOCI 221 - ADC

### ISSUE THREAD

**Issue by JessD9** [TWUOnline/bug-tracking#524]
### Instructions
- @rezakh66 Please upload Units 1, 2 & 3 to GiHub/Atom (may need to create 221 folder in github)

[SOCI221_U1_updated_JAN10_JD.docx](https://github.com/TWUOnline/bug-tracking/files/7842076/SOCI221_U1_updated_JAN10_JD.docx)

[SOCI221_U2_JAN03_JD.docx](https://github.com/TWUOnline/bug-tracking/files/7801107/SOCI221_U2_JAN03_JD.docx)
[SOCI221_U3_JAN03_JD.docx](https://github.com/TWUOnline/bug-tracking/files/7801108/SOCI221_U3_JAN03_JD.docx)

Let me know if you have any questions!

**Comment by cmadland** [comment]
Hi @melissapodolak, this is an example of what usually happens when an ID (Jess) has course materials ready for the web. The process from here is to use Pandoc to convert from .docx to .md, then copy and paste into the appropriate github repo to be published.

**Comment by cmadland** [comment]
@rezakh66, I'm using this to give Melissa a preview on the workflow.

**Comment by JessD9** [comment]
@rezakh66 Here are Units 4 & 5. 
[SOCI221_U4_JAN07_JD.docx](https://github.com/TWUOnline/bug-tracking/files/7832112/SOCI221_U4_JAN07_JD.docx)
[SOCI221_U5_JAN07_JD.docx](https://github.com/TWUOnline/bug-tracking/files/7832128/SOCI221_U5_JAN07_JD.docx)

Unit 5 - Please embed the following PDFs:

Activity 5.5: 
[SOCI221_U5_Activity_5.5_Infographic.pdf](https://github.com/TWUOnline/bug-tracking/files/7832114/SOCI221_U5_Activity_5.5_Infographic.pdf)

Activity 5.6
[SOCI221_U5_Activity_5.6_Mahoney_article.pdf](https://github.com/TWUOnline/bug-tracking/files/7832117/SOCI221_U5_Activity_5.6_Mahoney_article.pdf)

Activity 5.13
[SOCI221_U5_Activity_5.13_Divorce_Trends.pdf](https://github.com/TWUOnline/bug-tracking/files/7832122/SOCI221_U5_Activity_5.13_Divorce_Trends.pdf)
[SOCI221_U5_Activity5.13_Divorce_Fact_Sheet.pdf](https://github.com/TWUOnline/bug-tracking/files/7832123/SOCI221_U5_Activity5.13_Divorce_Fact_Sheet.pdf)

Activity 5.14
[SOCI221_U5_Activity_5.14_Paul_Amato.pdf](https://github.com/TWUOnline/bug-tracking/files/7832124/SOCI221_U5_Activity_5.14_Paul_Amato.pdf)

Thank You!

**Comment by JessD9** [comment]
hey @rezakh66 - checking in to see if these have been uploaded? Thanks

**Comment by rezakh66** [comment]
Hi @JessD9 I have uploaded units 1-5, please have a look and let me know if further adjustments are needed.

**Comment by JessD9** [comment]
Hi @rezakh66, here is the last unit. Thanks!
[SOCI221_U6_JAN18_JD.docx](https://github.com/TWUOnline/bug-tracking/files/7892177/SOCI221_U6_JAN18_JD.docx)

Notes:
- Topic 5, L.A. 6.7, please insert "The_Gerontologist_2015_Stowe" PDF
[The_Gerontologist_2015_Stowe.pdf](https://github.com/TWUOnline/bug-tracking/files/7892183/The_Gerontologist_2015_Stowe.pdf)

- Topic 9, L.A. 6.9, please insert "Conflict_Tactics_Scale” PDF"
[Conflict_Tactics_Scale.pdf](https://github.com/TWUOnline/bug-tracking/files/7892194/Conflict_Tactics_Scale.pdf)

-Topic 10, L.A. 6.11, please insert "Amato_et_al_2016” PDF
[Amato_et_al_2016.pdf](https://github.com/TWUOnline/bug-tracking/files/7892202/Amato_et_al_2016.pdf)

**Comment by rezakh66** [comment]
Hi @JessD9 [U6](https://learn.twu.ca/course/view.php?id=23371&section=6) is uploaded as well

**Comment by JessD9** [comment]
Great, thanks @rezakh66!
