### ISSUE TITLE
Video Transcript and Analysis Assignment Psych 340 FA 2021

### ISSUE THREAD

**Issue by MargMannShull** [TWUOnline/bug-tracking#525]
**Which course contains the bug?**  
-PSYCH 340 OL FA 2021
 
 
**Describe the error and/or your suggestion**  
I received the following note from a student in my Psych 340 OL course:

Happy weekend. I found the click under the video recording and transcripts was not working to allow me to upload the video. The system showed that “This may not be for you. Failed to load the channel. The authenticated user is not authorized to access this resource”. Could you please look it up and allow me to upload the video. Thank you so much.

Jen
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=15808&section=10
2. Unit # Week 4        Topic # Video Upload Transcript and Analysis        Activity#  Assessment - Video Recordings and Assessments - this could be an issue with MSStream?  There should be MSStream channels for Video Recording 4.2 and Video Recording 6 from Psych 340.  Thank you!
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
@MargMannShull 
This should be fixed now: https://learn.twu.ca/course/view.php?id=20392&section=10
