### ISSUE TITLE
LDRS220

### ISSUE THREAD

**Issue by cmadland** [TWUOnline/bug-tracking#529]
**Which course contains the bug?**  
- [LDRS220](https://github.com/TWUOnline/ba-lead/tree/master/pages/02.ldrs220)
 
 
**Describe the error and/or your suggestion**  
### From email

Simone,

Nice catch… you discovered an old textbook list was never revised to delete the ‘Rowntree’. And YES, the other two books should be on the list.

 COLIN, I cannot edit this course (in Moodle) for some reason. Is there a switch that needs to be flipped?
 
Simone,

The Accounting Game is ISBN 978-1-4022-1186-1

Stats for the Absolute Beginner is ISBN 978-8-6549-7612-3

I secure my books from Amazon for fast shipping.

Matt

From: Simone Van Der Merwe <Simone.VanDerMerwe@twu.ca>
Date: Tuesday, January 18, 2022 at 5:29 PM
To: Matthew Simonis <Matthew.Simonis@twu.ca>
Subject: LDRS 220: Quick Question about Required Books

Hello Dr. Matt,

 

I hope you are having a great day so far!

 

I have a few questions regarding the reading materials and assignment due dates.

    In the syllabus and in the course “Introduction” tab in Moodle, there are two required books listed: 

Berman K, and Knight, J. (2013). Financial Intelligence. Boston: Harvard Business Review Press.

Rowntree, D. (2004). Statistics Without Tears: A Primer for Non-Mathematicians. TWU Package.

However, I see there are also readings from the following books:

Mullis, D. and Orloff, J.; (1998) The Accounting Game. Naperville, Ill: Sourcebooks.

Theobald, O. (2017) Statistics for Absolute Beginners. Columbia, SC: Scatterplot Press

I searched the TWU library database and could not find any of these books. Could you please clarify if the students should purchase all four books, or if some of them can be accessed free of charge (e.g., PDF)?

    At the end of each Unit, students will submit “Written Assignments” and “Weekly Status Reports”. I notice that there are no specific “due dates”. I was thinking about arranging the weekly due dates to every Sunday at 11:59 PST? Would that work for you? I welcome your thoughts on this! 😊

Thank you very much for all your support!

Many Blessings,

Simone
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  
2. Unit #         Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
@dgaudet48 could you confirm the course resources for this course?  Also - we should take out the "see syllabus here" info in the course intro tab and say to locate the syllabus at the bottom of the page.  

Is there a specific syllabus from Matt for this GXP cohort?  Can the facilitator upload this?

**Comment by dgaudet48** [comment]
@kmarjanovic 

I spoke to Matt yesterday - he is going to pass along updates and edits...

He said he would be using the same syllabus - I will move that to the bottom of the page...

I offered to show him how to use the bug report feature for his edits but he declined the offer

**Comment by kmarjanovic** [comment]
This seems to be resolved.
