### ISSUE TITLE
PHIL 210 Changes to Assignments

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#530]
(Kelly is working on this)

**Which course contains the bug?**  
 PHIL 210 GX (SP22)
 
**Describe the error and/or your suggestion**  

- [x] In Course Overview tab: Ethics Committee Responses | 45% (3 @ 15% each)
- [x] Update Schedule. Committee assignment in Unit 1,4,7

- [x] In Units - Move Unit 3 & Unit 5 committee assignment to be learning activities
- [x] Unit 4 ungraded make graded.
- [x] Change Activity checklists

- [x] Change pdf in Assessment tab
- [x] Remove Self-Reflection: (5%)

 **Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=22618&section=0#tabs-tree-start

**Comment by kmarjanovic** [comment]
Hi @SimoneVanDerMerwe and @emmanuelD-AFK 
I've made those changes.  Just need to add a pdf.
All should be correct now though, so feel free to open the course to students!

**Comment by SimoneVanDerMerwe** [comment]
That is great news! Thank you so much!

I will ask Dr. Paul about the updated PDF file and send it to you.

Have a super blessed weekend!


Simone Van Der Merwe

Global Educational Facilitator - Far Center | TWU GLOBAL

Trinity Western University | ***@***.******@***.***>

twu.ca<http://www.twu.ca/>/



________________________________

**Comment by kmarjanovic** [comment]
@SimoneVanDerMerwe I've added the following pdf version to the [Ethics Committee section](https://learn.twu.ca/course/view.php?id=22618&section=13#tabs-tree-start).
If there are changes, please let us know.
Thanks!
[PHIL-210-Ethics-Committee-Assignment.pdf](https://github.com/TWUOnline/bug-tracking/files/7917555/PHIL-210-Ethics-Committee-Assignment.pdf)

**Comment by SimoneVanDerMerwe** [comment]
Thank you so much! You are awesome!


Simone Van Der Merwe

Global Educational Facilitator - Far Center | TWU GLOBAL

Trinity Western University | ***@***.******@***.***>

twu.ca<http://www.twu.ca/>/



________________________________
