### ISSUE TITLE
Production - PSYC 354 H5P request

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#532]
### Course
PSYC 354
### URL
(none yet...please create a git folder.  Unit 1 coming soon!)

### Instructions

Please create an H5P dialog card activity – similar to the following:
[https://create.twu.ca/h5p/wp-admin/admin.php?page=h5p&task=show&id=103](https://create.twu.ca/h5p/wp-admin/admin.php?page=h5p&task=show&id=103)

Content:
Title: Introduction to Behavioral Neuroscience 
Unit 1: Topic 1
1.	__________ is the study of the nervous system 
(on flip side...)Neuroscience 
2.	__________ is the study of the biological basis of psychological processes. 
(on flip side...) Behavioral neuroscience 
3.	__________ who thought the “heart” was the seat of mental capacities.  
Aristotle
4.	__________ wrote of the brain as the seat of thoughts and emotions.
Hippocrates
5.	__________’s experience in treating brain injured gladiators led him to propose that behavior results from connections between the brain and the body.
Galen
6.	The Renaissance artist and scientist __________ pioneered anatomical drawings which bore little resemblance to the actual brain structure.  
Leonardo da Vinci
7.	__________ explained control of behavior in terms of the machine.  He proposed the concept of spinal reflexes and their neural pathways.  He argued that free will and moral choice could not arise from a mere “machine.”
Rene Descartes
8.	__________ is the notion promoted by Descartes that humans have a non-material soul as well as a material body, that the soul governs behavior through a point of contact the pineal gland.
Dualism
9.	__________ was popular popularized localization of function and the belief that bumps on the skull resulted from enlargements of brain regions responsible for certain behavior.  
Phrenology
10.	__________ is the concept that different brain regions specialize in specific behaviors.  
Localization of Function
11.	Researchers have shown that damage to specific brain regions causes predictable impairment. For instance, __________ noted that damage to a particular region of the left side of the brain reliably impairs speech.
Paul Broca
12.	__________ is the change in an individual during its lifetime.
ontogeny
13.	__________ is a phenomenon in which behavior and experiences alter the physical brain.
Neuroplasticity
14.	__________ is the young field focusing on factors that have a lasting effect on patterns of gene expression.  
Epigenetics
15.	__________ is the field of study that uses the tools of neuroscience to discover both the biological bases of social behavior and the effects of social circumstances on brain activity.  
Social neuroscience
16.	__________ is the neural bases of decision making.  
Neuroeconomics

I want to add images as well, so will send that soon.
[Media Requests for PSYC 354.docx](https://github.com/TWUOnline/bug-tracking/files/7930348/Media.Requests.for.PSYC.354.docx)

**Comment by rezakh66** [comment]
Github folder and Moodle shell created: https://learn.twu.ca/course/view.php?id=23420&section=0#tabs-tree-start

**Comment by kmarjanovic** [comment]
@rezakh66 I'm going to put this request on hold, as I now have more course material from the SME, so we may add this content to a different H5P tool.  More info to come!

**Comment by kmarjanovic** [comment]
Cancelled.  Using Publisher materials instead as this courses starts soon.  More requests to come!
