### ISSUE TITLE
FNDN 101 H5P copy & edit

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#533]
**Which course contains the bug?**  
- [FNDN 101](https://create.twu.ca/fndn101/unit-5/)
 
**Describe the error and/or your suggestion**  
Could you please duplicate the H5P activity - interactive book in Unit 5: Topic 2: 

Add the following to the new version: On page 3 of the book, Activity 5.3, add 
“NOTE: You will be doing this material together in the next class, so you do not need to do it yourself right now. It is left in here for you to refer back to if you desire.” 
 
I couldn't find the H5P in the [H5P content](https://create.twu.ca/h5p/wp-admin/admin.php?page=h5p) section, but is in the site - see [Sophisticated - Interactive Book](https://create.twu.ca/h5p/sophisticated/#h5pbookid=4&section=top&chapter=h5p-interactive-book-chapter-e7f072c2-312d-40e2-9592-c564934374cf)

Note we need this duplicated because the [FNDN 101 GXP](https://create.twu.ca/fndn101gxp/unit-5/#h5pbookid=1&section=top&chapter=h5p-interactive-book-chapter-e7f072c2-312d-40e2-9592-c564934374cf) also uses this H5P.

Please add the new H5P to Joan's [FNDN 101](https://create.twu.ca/fndn101/unit-5/) course.

**Comment by rezakh66** [comment]
Hi @kmarjanovic I duplicated the activity and added your note. Where do you need it to be inserted? you can find it here: https://create.twu.ca/fndn101/wp-admin/admin.php?page=h5p

**Comment by kmarjanovic** [comment]
@rezakh66 Could you add it to the Joan's FNDN 101 course? Unit 5: Topic 2
Thank you!!!

**Comment by rezakh66** [comment]
Done.
