### ISSUE TITLE
PHIL 210: Requesting editing

### ISSUE THREAD

**Issue by SimoneVanDerMerwe** [TWUOnline/bug-tracking#537]
PHIL 210 GX SP 2022
 
Assessment tab > Partner Project Presentations tab
Under: Here are a couple of final rules for the class presentations 
Item 4: Presentations must conclude at the **15** minute mark.

 URL: https://learn.twu.ca/course/view.php?id=22618&section=15#tabs-tree-start
 
Thank you very much!
Simone
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
[91b5488](https://github.com/TWUOnline/arts-master/commit/91b5488f60e8399661abcc7ce615f0ae06f727ab) fixed
