### ISSUE TITLE
PHIL 210: Requesting editing

### ISSUE THREAD

**Issue by SimoneVanDerMerwe** [TWUOnline/bug-tracking#538]
PHIL 210 GX SP 22

Unit 5: Assessment tab
 
 1. Please remove "plugin:content-inject" 
 2. Green Box: This is not an assignment, it is just a reminder for students to select the video topic. Actions: please, (a) change the title to "Ethics Video Assignment: Choose Your Topic",  (b) Keep the content, but remove the "green box", and (c) Remove "instructions for assignment submission" and the "red box".

 URL: https://learn.twu.ca/course/view.php?id=22618&section=5#tabs-tree-start
 
Thank you so much for the previous changes you made! You guys rock!

Blessings,

Simone

**Comment by MeeksonHundoo** [comment]
@SimoneVanDerMerwe We've fixed those issues. However, cant see a red box in Unit 5: Assessment tab.
