### ISSUE TITLE
Unit Images for LDRS 504

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#539]
[**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 
[LDRS 504 Flexible pages version](https://learn.twu.ca/course/view.php?id=20826&section=1#tabs-tree-start)

**Describe the error and/or your suggestion**  
Now that we've switched to having just the unit title + image on the flexible pages format, we might need to add some images.

@dgaudet48 or @MaraChequer do you want to have a look at the course and suggest options?

Feel free to add them in the flexible master or [Notion 504 page](https://www.notion.so/twuid/LDRS-504-Graphics-816d362b6ee14d90bb4e570d66195e39).

**Comment by dgaudet48** [comment]
@kmarjanovic I am just looking in Atom - what "overview" page should the images be uploaded into (overview or overview1) for the flexible format?

**Comment by kmarjanovic** [comment]
@dgaudet48 I would suggest the landing overview page for the Unit. (the one with only the title, not the overview info).

**Comment by MaraChequer** [comment]
Hello @dgaudet48 and @kmarjanovic 
I would suggest following the format of 631,634, 617 and other courses. I have moved a few things around in your unit 1 Dave, I hope you don't mind. I can put some time today and help add the images and do this changes. It would take me less then an hour. 

https://learn.twu.ca/course/view.php?id=20826&section=1#tabs-tree-start

**Comment by dgaudet48** [comment]
@MaraChequer Not at all...

I am swamped dealing with 614 so there would be no arguments from me if you wanted to do that...please though, let me know if there is anything I can do to help the cause!

**Comment by MaraChequer** [comment]
@dgaudet48 I can imagine your challenges with 614... 
Yes, no problem Dave, I will move a few things around, but not from the course content. In the introduction page, I might only add something that is necessary. :)

**Comment by MaraChequer** [comment]
@dgaudet48 @kmarjanovic 

Done, https://learn.twu.ca/course/view.php?id=20826&section=0#tabs-tree-start
-Intro page according to the other LDRS courses
-Overview images for all units added
-Removed the Overview1 link in initial page of each unit

**Comment by kmarjanovic** [comment]
@MaraChequer 
Thanks Mara for adding the pictures!  The only thing is we need to keep the Overview link page, so that at the end of the unit's activities, it will go to the overview info.  Before - students could miss the overview page.  
When you click on the Unit tab - you should see the Unit title and an image.  Then the Overview page will have the unit details.
Does that make sense?

**Comment by MaraChequer** [comment]
@kmarjanovic . I see. Due to the fact that the units are linked to sessions and when they enter the course they are always brought to the home page and not to an specific unit and they need to select the unit corresponding to that session, I do not believe it is necessary for this format because we are adding an extra click to get to the overview. Does it make sense?

The student still has access to guidance in the top of the page via the unit tab. Is this also something I should apply to the other courses? I can certainly bring those links back and fix them if you like.

**Comment by kmarjanovic** [comment]
@MaraChequer @dgaudet48 @cmadland @MeeksonHundoo 
After chatting with Mara, we'd suggest that we not convert the Overview section to a new page because...
- Students will more likely click on the Unit tab than navigate to the next unit using the breadcrumbs at the bottom of the page
- They might skip the Overview page entirely and go right to the topics page, so best to have the overview show up right away.

Does this make sense? We can chat at our meeting on Wednesday - and then perhaps Meekson can change LDRS 500 back to having the Overview info all in that Unit tab?  (See [LDRS 504](https://learn.twu.ca/course/view.php?id=20826&section=1#tabs-tree-start))

Thanks all for your feedback!!!
