### ISSUE TITLE
ANTH 101 syllabus

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#540]
**Which course contains the bug?**  
[ANTH 101 GX (SP22)](https://learn.twu.ca/course/view.php?id=22625)
 
**Describe the error and/or your suggestion**  
Course Overview section 

In the red alert - change this:
!! The syllabus includes key information about the course schedule, assignments, and policies. The course syllabus can be found by clicking [HERE ](https://far.twu.ca/arts/anth101/home/ANTH_101_Syllabus.pdf). If you are having issues with the link, a .pdf copy of the course syllabus can be found at the bottom of the page.

To this:
!! The syllabus includes key information about the course schedule, assignments, and policies. The course syllabus can be found at the bottom of the page.
 
Please also add the pdf in Moodle
 
@dgaudet48 - that way when we copy this course to a new section, we don't need to change the Git info each time.  It helps for multiple sections happening at the same time too.

**Comment by MeeksonHundoo** [comment]
@kmarjanovic Amendments have been made

**Comment by kmarjanovic** [comment]
Thanks @MeeksonHundoo !!
