### ISSUE TITLE
Graphic for NURS 510

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#542]
### Course
[NURS 510 - Foundations (OL Master)](https://learn.twu.ca/course/view.php?id=10939)
### URL
https://learn.twu.ca/course/view.php?id=10939&section=10#tabs-tree-start
### Instructions
@MaraChequer could you rework the graphic in Lesson 9, Topic 2, 2.1?  It's difficult to read the text, and has a pretty basic design.

![image](https://user-images.githubusercontent.com/35148983/157493290-8b330571-2646-4991-8884-6755fb67a2b0.png)

The original pic can be found [here](https://github.com/TWUOnline/nurs-master/tree/master/pages/02.nurs510/12.u9/03.topic-2)

**Comment by MaraChequer** [comment]
Sure, @kmarjanovic . I'll be able to work on this on Friday

**Comment by MaraChequer** [comment]
![Critical-Theory](https://user-images.githubusercontent.com/84353161/159372354-e8a66b75-64fc-4d77-9288-1b6dc4ce4ee0.jpg)

Hi @kmarjanovic, Please review :)

**Comment by kmarjanovic** [comment]
@MaraChequer this looks great!!  I'll check with the SMEs
