### ISSUE TITLE
PSYC 354 Unit quizzes

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#543]
### Course
PSYC 354
### URL
[PSYC 354 (ADC MASTER)](https://learn.twu.ca/course/view.php?id=23420)
current section: [PSYC 354 OL (SP22)](https://learn.twu.ca/course/view.php?id=22417)

### Instructions

@MeeksonHundoo could you please add the Unit 3 quiz:

- [x] See the attached Chapter 8 & Chapter 10 quiz questions that make up unit 3 quiz.
- [x] Modify in [the testbank course](https://learn.twu.ca/course/view.php?id=23457)
- [x] Change the name to Unit 3 quiz
- [x] Delete the quiz questions we don’t need 
- [x] Check weighting of short answer questions
- [x] When ready, copy to both the PSCY 354 master and Jayme’s section that is currently running: PSYC 354 OL (SP22)
- [x] Add to Assessment section under Unit quizzes
- [x] Set quiz to 1 hour to complete 
- [x] **Hide from students**

[Unit 3 Chapter 8 Graded Quiz.docx](https://github.com/TWUOnline/bug-tracking/files/8216729/Unit.3.Chapter.8.Graded.Quiz.docx)
[Unit 3 Chapter 10 Graded Quiz.docx](https://github.com/TWUOnline/bug-tracking/files/8216730/Unit.3.Chapter.10.Graded.Quiz.docx)

@cmadland please also make the quiz accommodation (90 mins) for the specific student (see email).

**Comment by MeeksonHundoo** [comment]
@kmarjanovic this is done
