### ISSUE TITLE
SOCI 320 google forms

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#545]
### Course
SOCI 320

### URL
https://github.com/TWUOnline/arts-master/tree/master/pages/27.soci320adc

### Instructions
Could you please help convert these 3 documents into 3 google forms?
-	Learning Contract Forms 
-	Practicum_Evaluation_Student_2021
-	Practicum_Evaluation_Mentor_2021

[Practicum_Evaluation_Student.docx](https://github.com/TWUOnline/bug-tracking/files/8234236/Practicum_Evaluation_Student.docx)
[Practicum_Evaluation_Mentor.docx](https://github.com/TWUOnline/bug-tracking/files/8234238/Practicum_Evaluation_Mentor.docx)
[Learning Contract Forms.docx](https://github.com/TWUOnline/bug-tracking/files/8234239/Learning.Contract.Forms.docx)

**Comment by kmarjanovic** [comment]
@cmadland could we look into an onlinetwu google account so ATAs can work on this?

**Comment by kmarjanovic** [comment]
@cmadland @MeeksonHundoo - any progress on this issue?  Should TWU Online have a google account?  Or we get Meekson more space so he can work on these projects?

**Comment by kmarjanovic** [comment]
@MeeksonHundoo could I suggest you get another gmail account so you can work on these issues?  Could we have these forms done by next week?

**Comment by MeeksonHundoo** [comment]
Hello @kmarjanovic Here are the links to the google docs:
https://docs.google.com/document/d/1jw3d882RWQxZ4idnKdslwDGA8tHD_Q-1/edit
https://docs.google.com/document/d/1rfD5Qg7NToDYH7pCjNEUAvscwxX2s-30/edit?rtpof=true
https://docs.google.com/document/d/1Hs6yXFQmpOLKXU9zJgE7yTm1k8zt9ZLM/edit#heading=h.gjdgxs

**Comment by kmarjanovic** [comment]
Hi @MeeksonHundoo.  Could you please convert them to Google forms?  
Also, just for future google docs, you'll need to change permissions as it says I don't have access.  
Thank you!

**Comment by MeeksonHundoo** [comment]
Hello @kmarjanovic I've converted all of these to google forms. I've also updated the permission to edit these links.
I had to break down the Practicum Evaluation student & supervisor docs into multiple forms as we just have access to setup 10 questions per form. Anything more than 10 needs a payment. Apologies for that. Could you please take a look and advice.

**Learning Contract Forms.docx**
https://docs.google.com/forms/d/1W5A_u5Xty9duhF8xEUlXcwKBWgF9D9h9mtTMpaxUz0o/edit

**Practicum Evaluation Student Form (To be completed by the Student)**
https://docs.google.com/forms/d/1VEDRwwUcJAbt6HwBhX5sRvxLGj5jmSCWouXXAMFzPFM/edit
https://docs.google.com/forms/d/1-pNPMIbbYQL42VpphgSiphl5FTAlrO3HEETqEsU88DI/edit
https://docs.google.com/forms/d/1B6Dj8dCF4nXmBKuqHopeyTrs8gcEsepH2ow3JucV0Uw/edit
https://docs.google.com/forms/d/1KbOOPda8NWMlGLOAsxZQsXhySLTJNfRq1z2DuBB4-C4/edit
https://docs.google.com/forms/d/1Li41Pk9ezmpKveAP--BrNobAYWEseVA2Ol6AYW4cbk0/edit
https://docs.google.com/forms/d/1zWshPu4pWEnsGj9Ic8nSHvWOr62jy6A56G4-jUIpY_E/edit
https://docs.google.com/forms/d/1Dq4vbBVOG0W_m4S5iVFgpZg1wWT81q3Q9PrlyB1WYL0/edit
https://docs.google.com/forms/d/1zYIFDZmWXmdEwnZhL74Pz-43EOqVG0SOxl65VthCFLY/edit?usp=sharing
https://docs.google.com/forms/d/177Y-e9LDH58XvFbfnr6TVsOXSrUHzh67y0mG2kTefrc/edit

**Practicum Evaluation Supervisor Form (To be completed by the Mentor)**
https://docs.google.com/forms/d/1RxgZk60SMtJQjrRWxxpqTmQjqJUUk_piX561chPSFPI/edit
https://docs.google.com/forms/d/1_XFGbnBGCtPPmvMQoi4mpN0cWRs7Xy3v_ShlGmPJKOw/edit
https://docs.google.com/forms/d/1_p_glWPSgB5pfvMG-4dHjawR4ZgXZ77YNL5CeyZYYe8/edit
https://docs.google.com/forms/d/1nrWjYPElZHLQYoIKtTQ-SbaJo_DeIZy9XI7rEI-cADs/edit
https://docs.google.com/forms/d/12qzgZZBXqUHwF8wN5EXu78xKuY67696FmCVt3-g9fPM/edit
https://docs.google.com/forms/d/1AxhA1iNTWng7zex-LovTJp134QdaVQHs7P-lCoPgb6Q/edit
https://docs.google.com/forms/d/1_FQY3XM2oHAIOcGe6L24V0_Ax84oIBIWuhY6CEzuhkw/edit
https://docs.google.com/forms/d/1uhlxJ5pOIyuTngr2aiyWTzsh-7fuFf0mGKPA_TlzlCw/edit
https://docs.google.com/forms/d/1RtibnMbBnRxHomziCVUuonA0gUuNfjHocwMtroEOD-I/edit

**Comment by Jeff-TWU** [comment]
@kmarjanovic Per our conversation, I've created MS Forms + a fillable PDF from the doc files.

MS Forms can be viewed/managed at [forms.office.com](forms.office.com). Click on the 'ID Team' under 'My Groups'
![Screen Shot 2023-01-25 at 2 51 01 PM](https://user-images.githubusercontent.com/66963480/214710444-ebf49966-9465-45df-9856-67e626aeb463.png)
![Screen Shot 2023-01-25 at 2 59 10 PM](https://user-images.githubusercontent.com/66963480/214711030-142d557c-edd6-4d09-8c42-a2ebe098d10b.png)

The Contract made more sense as a fillable PDF. I've attached it below. Please let me know if you would like any changes or have any questions.

[SOCI 230_Learning Contract_fillable.pdf](https://github.com/TWUOnline/bug-tracking/files/10504409/SOCI.230_Learning.Contract_fillable.pdf)

**Comment by kmarjanovic** [comment]
This is fantastic!!! Thanks so much @Jeff-TWU 

What's the best way to share access with Debra so she can manage these documents and make edits?

**Comment by Jeff-TWU** [comment]
> This is fantastic!!! Thanks so much @Jeff-TWU
> 
> What's the best way to share access with Debra so she can manage these documents and make edits?

@kmarjanovic Welcome!

For the MS Forms, open the form and then click on the Ellipsis points on the right. Click 'Collaborate or Duplicate'. 
![Screen Shot 2023-01-26 at 1 05 56 PM](https://user-images.githubusercontent.com/66963480/214951189-5284d048-1a55-44d1-83a9-4c688d721618.png)

Click 'Get a link to view and edit'.
![Screen Shot 2023-01-26 at 1 07 29 PM](https://user-images.githubusercontent.com/66963480/214951214-46d40e97-6339-4137-a568-12ea0b245307.png)

For the fillable pdf, she'll have to send requests to me. I designed it in in Illustrator, and then added fillable sections in Acrobat.

**Comment by kmarjanovic** [comment]
Perfect! Thanks again!
