### ISSUE TITLE
PSYC 354 unit 3

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#546]
### Course
PSYC 354
### URL
[PSYC 354 (ADC MASTER)](https://learn.twu.ca/course/view.php?id=23420)
current section: [PSYC 354 OL (SP22)](https://learn.twu.ca/course/view.php?id=22417)

### Instructions
Please add to the master and spring course.
[PSYC 354_U3_March 15_KM-for production.docx](https://github.com/TWUOnline/bug-tracking/files/8256167/PSYC.354_U3_March.15_KM-for.production.docx)

**Comment by cmadland** [comment]
Activity 3.7 issue

![image](https://user-images.githubusercontent.com/12282929/158690200-37d7e5ba-65c6-4d1a-a0f7-4c654fccae5b.png)

---

![image](https://user-images.githubusercontent.com/12282929/158690272-a393925d-0a8d-44d5-a40c-58e3ef1914c2.png)

**Comment by cmadland** [comment]
looks like it's sorted now @meekson 

<img width="859" alt="image" src="https://user-images.githubusercontent.com/12282929/158696571-77577e75-00ba-47fe-aaf8-8cf3781efb91.png">

**Comment by MeeksonHundoo** [comment]
Indeed Colin. Thanks for all your help.

Regards.
Meekson.
________________________________

**Comment by MeeksonHundoo** [comment]
@kmarjanovic this is done now

**Comment by kmarjanovic** [comment]
@MeeksonHundoo thank you!!!
I think for the case studies we'll have a green background (!!!!)
![2022-03-17 (3)](https://user-images.githubusercontent.com/35148983/158875729-80230e58-60f5-441e-b520-4547536b3b03.png)
