### ISSUE TITLE
PSYC 411 Guide

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#548]
### Course
[PSYC 411 (Master)](https://learn.twu.ca/course/view.php?id=22610)

### Instructions
Please add the attached info to the [guide tab](https://learn.twu.ca/course/view.php?id=22610&section=16)

See PSYC 207 [guide](https://learn.twu.ca/course/view.php?id=18684&section=13#tabs-tree-start) as an example.  First paragraph should be in the text - but all other sections in accordion style.
[PSYC 411 Instructor Guide - for Production.docx](https://github.com/TWUOnline/bug-tracking/files/8266954/PSYC.411.Instructor.Guide.-.for.Production.docx)

**Comment by kmarjanovic** [comment]
@MeeksonHundoo any update on this issue?  I marked it as low priority 5 months ago and the course starts in 2 weeks.

**Comment by MeeksonHundoo** [comment]
Hello @kmarjanovic Apologies for the delay. I thought the course facilitators were going to work on this issue, given we had decided in one of our meetings that this way they would get a good hands on experience of making edits in Git themselves. I have added the accordion now. I just wanted to ask if the content of Synchronous Class sessions should be added under the tabs of the accordion labelled as Unit's 1 to Unit 5 accordingly?

**Comment by MeeksonHundoo** [comment]
Hello @kmarjanovic As per our conversation I have reused the PSYC 340 ADC instructors Guide as our template and added the course contents to it. Could you please take a look and advice if any changes are needed? Here is the link:
https://learn.twu.ca/course/view.php?id=22610&section=16

**Comment by kmarjanovic** [comment]
Perfect!!  Thanks so much Meekson!
