### ISSUE TITLE
PSYC 322 Guide

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#549]
### Course
[PSYC 322 (Master)](https://learn.twu.ca/course/view.php?id=20680)

### Instructions
Please add guide (letter) to [guide tab](https://learn.twu.ca/course/view.php?id=20680&section=10)

Since it's a short letter it can be all in the text (no accordion)
[LETTER TO ANOTHER INSTRUCTOR OF PSYCHOLOGY 322 OL.docx](https://github.com/TWUOnline/bug-tracking/files/8266969/LETTER.TO.ANOTHER.INSTRUCTOR.OF.PSYCHOLOGY.322.OL.docx)

**Comment by MeeksonHundoo** [comment]
@kmarjanovic the letter has been uploaded to the instructor guide tab.

**Comment by kmarjanovic** [comment]
Hi @MeeksonHundoo 
Thanks for adding that!  Instead of an attached doc, though, could you please add it through Git?  See the PSYC 207 as an example.
https://github.com/TWUOnline/arts-master/tree/master/pages/23.psyc207adc/99.facilitator's%20guide
Thanks!

**Comment by kmarjanovic** [comment]
Actually I've just added an accordion.  Could you add the letter to the Unit Notes section?  Thank you!
https://learn.twu.ca/course/view.php?id=20680&section=10

**Comment by MeeksonHundoo** [comment]
done
