### ISSUE TITLE
PHIL 210: Requesting a few changes

### ISSUE THREAD

**Issue by SimoneVanDerMerwe** [TWUOnline/bug-tracking#555]
PHIL 210 GX (SP22)
 
1) Unit 5>Assessment Tab>"Ethics Video Assignment: Choose Your Topic (15%)":
a) Line 3: please remove (Units 5-9 topics).
b) The Last line, after "provide the URL", please add the following: You will write 3 posts (150 words minimum for each) responding to three videos presented by your classmates, stating your agreement or disagreement with the arguments in the video, and explaining why you agree or disagree. 
URL: https://learn.twu.ca/course/view.php?id=22618&section=5#tabs-tree-start

2) "Assessment Tab">"Ethics Video">"Assignment; Ethics Video (15%):
a) Line 2: please remove (Units 5-9 topics).
b) PDF version of the assignment: please, remove (Units 5-9 topics) from the PDF file.
URL: https://learn.twu.ca/course/view.php?id=22618&section=11#tabs-tree-start 

 3) Unit 10 >Assessment Tab:
a) Please remove: plugin:content-inject
b) The Assignment Ethics Committee Reflection is an ungraded activity. Actions: (a) Please remove (5%) and instead add (Ungraded), (b) Please change the word count to 150-250 words, and (c) Please change the background colour from green to gray.
URL: https://learn.twu.ca/course/view.php?id=22618&section=10#tabs-tree-start

Thank you so much for your incredible help!!!!
Blessings,
Simone

**Comment by MeeksonHundoo** [comment]
@kmarjanovic I have made the changes to these. However, I couldn't remove the plugin:content-inject from unit 10. I tried looking it out but couldn't search it. Also if you could help with the editing of the pdf version of the assignement.

**Comment by MeeksonHundoo** [comment]
@SimoneVanDerMerwe All the changes have been incorporated.

**Comment by SimoneVanDerMerwe** [comment]
@MeeksonHundoo Thank you so much!!! Unit 9 is perfect! In Unit 5>Assessment Tab>"Ethics Video Assignment: Choose Your Topic (15%)": where it says (150 words minimum for each), can you please delete "minimum for", so it will look the same as in Unit 9 (150 words each)?
URL: https://learn.twu.ca/course/view.php?id=22618&section=5#tabs-tree-start
Thank you very much!

**Comment by MeeksonHundoo** [comment]
Your welcome @SimoneVanDerMerwe This has been done.

**Comment by SimoneVanDerMerwe** [comment]
@MeeksonHundoo Thank you!

**Comment by SimoneVanDerMerwe** [comment]
@MeeksonHundoo I am so sorry, but could you please delete the following: "You are also asked to respond to at least 3 of your peers videos". I forgot to mention it, my apologies! 

It is after the bolded addition in both places:

1. In Unit 5>Assessment Tab>"Ethics Video Assignment: Choose Your Topic (15%)": Last line.
URL: https://learn.twu.ca/course/view.php?id=22618&section=5#tabs-tree-start
2. Unit 9 >Assessment Tab>"Ethics Video (15%)": Second last line
URL: https://learn.twu.ca/course/view.php?id=22618&section=5#tabs-tree-start

**Comment by MeeksonHundoo** [comment]
No worries @SimoneVanDerMerwe I have deleted that statement from both the assessments tab under their respective units.

**Comment by SimoneVanDerMerwe** [comment]
@MeeksonHundoo Thank you, thank you! 😊😊
