### ISSUE TITLE
PSYC 354 Unit 5 Quiz

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#557]
### Course
[PSYC 354 (ADC MASTER)](https://learn.twu.ca/course/view.php?id=23420)
[Unit Quizzes](https://learn.twu.ca/course/view.php?id=23420&section=9)

### Instructions
Please see the highlighted quiz questions from the 2 chapters and combine for the Unit 5 quiz (last quiz for this course! :))
[Unit 5 Ch 13 graded quiz .docx](https://github.com/TWUOnline/bug-tracking/files/8354484/Unit.5.Ch.13.graded.quiz.docx)
[Unit 5 Ch 15 graded quiz.docx](https://github.com/TWUOnline/bug-tracking/files/8354485/Unit.5.Ch.15.graded.quiz.docx)

**Comment by MeeksonHundoo** [comment]
@kmarjanovic I've added the quiz.

**Comment by kmarjanovic** [comment]
Thank you @MeeksonHundoo !

**Comment by kmarjanovic** [comment]
@MeeksonHundoo could you please add it to the spring shell as well? (and hide from students)
https://learn.twu.ca/course/view.php?id=22417&section=9#tabs-tree-start

**Comment by MeeksonHundoo** [comment]
@kmarjanovic this has been added and hidden as well.
