### ISSUE TITLE
PSYC 305 

### ISSUE THREAD

**Issue by JessD9** [TWUOnline/bug-tracking#559]
### Instructions

- @MeeksonHundoo Please upload Unit 1 to  GiHub/Atom (may need to create PSYC 305 folder in github)

[PSYC305_U1_April01_JD.docx](https://github.com/TWUOnline/bug-tracking/files/8401198/PSYC305_U1_April01_JD.docx)

Let me know if you have any questions!

**Comment by MeeksonHundoo** [comment]
Hello @JessD9. U1 has been uploaded.

**Comment by JessD9** [comment]
Great, thanks!

**Comment by JessD9** [comment]
Hi @MeeksonHundoo. Here is Unit 2:
[PSYC305_U2_April14_JD.docx](https://github.com/TWUOnline/bug-tracking/files/8488384/PSYC305_U2_April14_JD.docx)

**Comment by MeeksonHundoo** [comment]
Hello @JessD9 U2 has been updated. Should we delete topic 3 as we don't have this for U2? Have a great weekend.

**Comment by JessD9** [comment]
Hi @MeeksonHundoo. Yes, please delete topic 3. Thanks!

**Comment by MeeksonHundoo** [comment]
Hello @JessD9 Topic 3 has been deleted.

**Comment by JessD9** [comment]
Hi @MeeksonHundoo. Please upload Unit 3. Thank You
[PSYC305_U3_MAY06_JD.docx](https://github.com/TWUOnline/bug-tracking/files/8644486/PSYC305_U3_MAY06_JD.docx)

**Comment by MeeksonHundoo** [comment]
Hello @JessD9 Unit 3 has been uploaded now. Could you please check if the link for (DSM Announcement) under Topic 1, Learning activity 1.1 is right? The link on the word doc was not opening. I had to manually enter it.

**Comment by JessD9** [comment]
Hi @MeeksonHundoo. Thanks for doing this on short notice. Yes, the link you fixed is correct now.

**Comment by JessD9** [comment]
Hi @MeeksonHundoo Here is Unit 4.
Let me know if you have any questions. Thanks!
[PSYC305_U4_MAY05_JD.docx](https://github.com/TWUOnline/bug-tracking/files/8674997/PSYC305_U4_MAY05_JD.docx)

**Comment by MeeksonHundoo** [comment]
Hello @JessD9 Unit 4 is up.

**Comment by JessD9** [comment]
Great, thank you @MeeksonHundoo!

**Comment by JessD9** [comment]
Hi @MeeksonHundoo. Here is Unit 5.
(Note, there are no Learning Activities in Topic 2). Thank You

[PSYC305_U5_MAY20_JD.docx](https://github.com/TWUOnline/bug-tracking/files/8735930/PSYC305_U5_MAY20_JD.docx)

**Comment by MeeksonHundoo** [comment]
Hello @JessD9 Unit 5 has been uploaded

**Comment by JessD9** [comment]
Perfect! Thanks so much @MeeksonHundoo. 
Have a wonderful long weekend.

**Comment by JessD9** [comment]
Hi @MeeksonHundoo. Here is the last Unit:
[PSYC305_U6_MAY26_JD.docx](https://github.com/TWUOnline/bug-tracking/files/8777758/PSYC305_U6_MAY26_JD.docx)

Note: Please embed the following PDF under Activity 6.5

[U6_Activity_6.5_Flourish_Wellness_Wheel.pdf](https://github.com/TWUOnline/bug-tracking/files/8777759/U6_Activity_6.5_Flourish_Wellness_Wheel.pdf)

**Comment by MeeksonHundoo** [comment]
Hello @JessD9 Unit 6 has been updated
