### ISSUE TITLE
unresponsive Links 

### ISSUE THREAD

**Issue by emmanuelD-AFK** [TWUOnline/bug-tracking#562]
**Which course contains the bug?**  
- LDRS 300 IF SP2022)
 
 
**Describe the error and/  
Several links meant to support an assignment are unresponsive
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=22704&section=3#tabs-tree-start
2. Unit # 2         Topic # Assessments         Activity#  Assignment 2.2. Portfolio #1  
 
**Optional: Screenshots**  
<img width="531" alt="Screen Shot 2022-04-08 at 2 29 05 PM" src="https://user-images.githubusercontent.com/59032072/162535111-014f2e72-ec32-41ec-9397-2d6e5a6d505c.png">
<img width="498" alt="Screen Shot 2022-04-08 at 2 28 55 PM" src="https://user-images.githubusercontent.com/59032072/162535115-99c5e516-814a-4e4f-b96b-5af913786318.png">

**Comment by JessD9** [comment]
Hi @emmanuelD-AFK. The links under Assignment 2.2. have been updated.

**Comment by emmanuelD-AFK** [comment]
Hi Jessica

Hope you are doing well!
The issue seems to not be fixed on my end. Can you please, give another look at it?

Blessing!



Emmanuel Denguessi, MA

Academic Facilitation Specialist - Far Center Overhead | TWU Global

Trinity Western University | e. ***@***.***

twu.ca<http://www.twu.ca/>/ 778-552-4861

________________________________

**Comment by JessD9** [comment]
Hi @emmanuelD-AFK . For "Assignment 2.2", all the links are opening for me... (using Chrome browser)
![2 2](https://user-images.githubusercontent.com/62358789/162808151-3e066a06-229c-41ac-8fc6-b95bc6023f2d.png)

**Comment by JessD9** [comment]
resolved
