### ISSUE TITLE
FNDN 102 - Facilitator's Guide

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#563]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 [FNDN 102 (Master)](https://learn.twu.ca/course/view.php?id=20673)
[Facilitator's Guide](https://learn.twu.ca/course/view.php?id=20673&section=19)
 
**Describe the error and/or your suggestion**  
@MeeksonHundoo could you add facilitator's guide as an accordion?  (see [PSYC 340](https://learn.twu.ca/course/view.php?id=15808&section=14#tabs-tree-start) as an example)

[FNDN 102 Letter to Another Inst Edited Nov15-KM.docx](https://github.com/TWUOnline/bug-tracking/files/8484186/FNDN.102.Letter.to.Another.Inst.Edited.Nov15-KM.docx)

**Comment by MeeksonHundoo** [comment]
Hello @kmarjanovic FDN 102 doesn't have a GRAV site. Should we create one or do we add the content of the letter to the tab in moodle?

**Comment by kmarjanovic** [comment]
Sorry - I forgot it doesn't have a grav site.  For now, let's delay this request until we've confirmed we'll need a Git version of this course.
Thanks!
