### ISSUE TITLE
Requesting Changes PHIL 210 GX Summer 22

### ISSUE THREAD

**Issue by SimoneVanDerMerwe** [TWUOnline/bug-tracking#564]
PHIL 210 GX Summer 22

We need to make small changes in the Partner Project Presentation assignment for the Summer Cohort.

**Unit 3 > Assessment tab:** 
1. 1st paragraph: "For this partner project, **you** will choose ...", please change "you" to your group
2. 2nd paragraph:  Where it says: "You must choose a **partner** and topic this week (see Units **5-10** topics)", please change "partner" to group and change "5-10" to 1-10.
 
URL: https://learn.twu.ca/course/view.php?id=22618&section=3#tabs-tree-start

**The same changes will apply in the "Assessments" tab, including the PDF version.** as follows:

**Assessments > Partner Project Presentation:**
1. 1st paragraph: "For this partner project, **you** will choose ...", please change "you" to your group.
2. 2nd paragraph:  Where it says: "You must choose a **partner** and topic this week (see Units **5-10** topics)", please change "partner" to group and change "5-10" to 1-10.

URL: https://learn.twu.ca/course/view.php?id=22618&section=15#tabs-tree-start

Thank you very much!!

Blessings,
Simone

**Comment by MeeksonHundoo** [comment]
@SimoneVanDerMerwe this is done now. Have a nice weekend.

**Comment by SimoneVanDerMerwe** [comment]
@MeeksonHundoo Thank you so much! Have a wonderful Easter weekend!!
