### ISSUE TITLE
SOCI 420 OL SU2022

### ISSUE THREAD

**Issue by dhanenburg** [TWUOnline/bug-tracking#565]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  
2. Unit #         Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by dhanenburg** [comment]
Please change "Practicum 2" to "Practicum 3" on the Title under the "General Tab". Thank you.

**Comment by dhanenburg** [comment]
and in the same place change SOCI 411 to SOCI 420.

**Comment by MeeksonHundoo** [comment]
@dhanenburg These changes have been made.
