### ISSUE TITLE
Production

### ISSUE THREAD

**Issue by dhanenburg** [TWUOnline/bug-tracking#566]
UNIV 301 OL SU2022

https://learn.twu.ca/course/view.php?id=23325&section=9#tabs-tree-start 

Can you please delete the "Class Notes Packet" (from the page link listed above) and replace it with the following: 

**Intro to Self MOD#1 - Discover Your Core** - https://mytwu-my.sharepoint.com/:b:/g/personal/debra_hanenburg_twu_ca/EeZDQ5tQcilBhUuUapR6anIBs9KmWP-GjWRFQXKnuJaTsQ?e=lWZNmK
**Intro to Self MOD#2 - Personality Type** - https://mytwu-my.sharepoint.com/:b:/g/personal/debra_hanenburg_twu_ca/EcZ5Za5fTBBFtpqNR-M-uDsBNiIC3gamJz1fAptb25HmLg?e=wHYSeb
**Intro to Self MOD#3 - Core Strengths** - https://mytwu-my.sharepoint.com/:b:/g/personal/debra_hanenburg_twu_ca/EcFPtzhfhDBOpEj7KrjWWOUBpv2L4b-xoSC1Z5UNfmgSrg?e=GgF8kt 

Please upload required files as attachments - I didn't see how to upload a file attachment here. Hope this works. Let me know if you need me to send these in a different format.

**Comment by MeeksonHundoo** [comment]
Hello @dhanenburg  These files have been uploaded.
