### ISSUE TITLE
ENGL 101 - Facilitator's Guide 

### ISSUE THREAD

**Issue by JessD9** [TWUOnline/bug-tracking#567]
### Course
[ENGL 101 (Master)](https://learn.twu.ca/course/view.php?id=15705&section=15#tabs-tree-start)

### Instructions
Please add the attached info to the [Fac. Guide tab](https://learn.twu.ca/course/view.php?id=15705&section=15#tabs-tree-start)

All 4 Modules should be added accordion style.

See WRTG 101 [guide](https://learn.twu.ca/course/view.php?id=10769&section=15#tabs-tree-start) as an example.  

[ENGL101_Fac_Guide_M1.docx](https://github.com/TWUOnline/bug-tracking/files/8694048/ENGL101_Fac_Guide_M1.docx)
[ENGL101_Fac_Guide_M2.docx](https://github.com/TWUOnline/bug-tracking/files/8694049/ENGL101_Fac_Guide_M2.docx)
[ENGL101_Fac_Guide_M3.docx](https://github.com/TWUOnline/bug-tracking/files/8694050/ENGL101_Fac_Guide_M3.docx)
[ENGL101_Fac_Guide_M4.docx](https://github.com/TWUOnline/bug-tracking/files/8694051/ENGL101_Fac_Guide_M4.docx)

**Comment by MeeksonHundoo** [comment]
Hello @JessD9 All the 4 modules have been added as an Accordion. I have left the Course Overview, Syllabus and Introduction tabs from the pervious course as it is. As soon as we have these details for our course i.e. ENGL 101, I'll update it in the accordion.
