### ISSUE TITLE
SOCI 201: Introduction to Human Services (ADC Master)

### ISSUE THREAD

**Issue by dhanenburg** [TWUOnline/bug-tracking#568]
**Which course contains the bug?**  - SOCI 201: Introduction to Human Services (ADC Master)

 
 
**Describe the error and/or your suggestion**  

**On the "Home" tab, please make the following changes:** 

1. Please replace the first paragraph with the following: The goal of this course is to prepare students for thoughtful and compassionate engagement in a helping profession, through application of the social sciences and a faith-based understanding of people and agencies. Introduction to Human Services introduces students to the beliefs, values, attitudes, skills and practices that are associated with high quality care in the helping professions both locally and globally. This course examines the helping relationship in terms of self (including values and professional attitudes), process (the requisite skills and models of human service delivery) and context (including faith/philosophical orientation, culture and a history of human services practice). Students shall prepare a guided autobiography and engage in vocational discernment. Recognizing students are from both the USA and Canada and different regions within those countries, the course will include application of learning to your current context. 
2. Please remove the statement and link about how to navigate moodle. 
3. Please remove the embedded syllabus (I will just upload it as a file) 
 
**In Unit 2,** Overview, yellow box, remove "8" from the reading and add a dash between 6 and 7. 
**In Unit 3**, Overview, yellow box, change reading to 8-9
**In Unit 4**, Overview, add same yellow box for reading and add: Required Readings: For this week, please read Chapter 10 from the textbook. Also, continue to read the Seaton booklet so you will be prepared to complete your own guided autobiography.
While not required, you are encouraged to journal as you read. Write down any questions or topics you would like to discuss in our next zoom meeting or on the discussion forum.
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=18696&section=0#tabs-tree-start
2.
4. Unit #         Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @dhanenburg these edits have been made.
