### ISSUE TITLE
Psych 331 OL Su 2022

### ISSUE THREAD

**Issue by Mike2625** [TWUOnline/bug-tracking#569]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 Unit 1: bottom of the page under "Resources"

Case of Stan” videos: at times we will watch these together in our synchronous class session or you can find them in the Class Recordings tab

 Change it to "can find them in the mindtap section from the publisher"

**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 
 
**Location of the bug**  
Under Resources section in the first page of unit one
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  
2. Unit #         Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @Mike2625 this has been updated
