### ISSUE TITLE
Psyc 331 :Summer 2022 (Theories of Counseling)

### ISSUE THREAD

**Issue by Mike2625** [TWUOnline/bug-tracking#570]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 Copy and pasted:Learning Activity 1.2: Read and Reflect
 Read Chapter 1 of Theory and Practice of Counseling and Psychotherapy by Gerald Cory. 

Change to say the following:
Read chapter 1 sections 1-4 entitled "Overview of the Theories"

**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  
2. Unit #         Topic #         Activity#  
 
Unit 1: Learning Activity 1.2
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @Mike2625 This has been updated
