### ISSUE TITLE
Pych 331 Summer 2022 (Theories of Counseling)

### ISSUE THREAD

**Issue by Mike2625** [TWUOnline/bug-tracking#571]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
Psych 331 Summer 2022

When you read the section of "Personal Characteristics of the Effective Counselor" on pages 19-20, answer these questions: 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.

Learning Activity 1.3: Journal Entry (graded)
 Read Chapter 2 of Theory and Practice of Counseling and Psychotherapy by Gerald Cory.

Change to say the following:
Read chapter 2 section 2-2A "Personal Characteristics of an Effective Counselor"

 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  
2. Unit #         Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @Mike2625 This has been updated
