### ISSUE TITLE
Psych 331: Summer 2022 (Theories of Counseling)

### ISSUE THREAD

**Issue by Mike2625** [TWUOnline/bug-tracking#573]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 Psych 331 Summer 2022: Assessment section end of moodle in unit 1
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 
Please change the following in the assessment section:

 When you read the section of "Personal Characteristics of the Effective Counselor" on pages 19-20, answer these questions:

To: When you read the section of "Personal Characteristics of the Effective Counselor" in chapter two answer the following questions 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  
2. Unit #         Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
hello @Mike2625 this has been updated
