### ISSUE TITLE
Psyc 331 Summer 2022 (Theories of Counseling)

### ISSUE THREAD

**Issue by Mike2625** [TWUOnline/bug-tracking#574]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 Unit 2 Topic 3
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 Adler discusses four phases of therapy (pages 108 to 114): 

Please remove page numbers

**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  
2. Unit #         Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
hello @Mike2625  this has been updated
