### ISSUE TITLE
SOCI 201 Intro to Human Services ADC OL

### ISSUE THREAD

**Issue by dhanenburg** [TWUOnline/bug-tracking#578]
**Which course contains the bug?**  - SOCI 201 Intro to Human Services ADC OL Master 
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.

On the Home tab, please **remove all text below the red line** that says "The syllabus includes key information about the course schedule, assignments, and policies. Please read the full course syllabus found at the bottom of this page."
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=18696 
2. Unit #         Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @dhanenburg this has been updated
