### ISSUE TITLE
HIST 107 Quizzes

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#58]
### Instructions
(adding issue tracking from Sept 11 email sent to Jared)

Attached is a zipfile of quizzes for HIST 107.  Could you please create the quizzes in Moodle?
There are just 4 quizzes that cover several chapters each.
Unit 1 – chapters 1-2
Unit 2 – chapters 3-6
Unit 3 – chapters 7-11
Unit 4 – chapters 12-15
For each quiz, please set it up so that there are 15 random questions selected from the quiz database (e.g. unit 1 – choose 15 of the 24 questions from chapters 1 & 2).
Please add the instructions:
After you have completed this unit, including all of the class learning activities, take the Unit 1 quiz. There are 15 multiple choice questions and you will only have 10 minutes to complete the quiz.
This quiz is worth 5% of your course grade.
 
Colin, for this course there are also 15 key term quizzes for each chapter (terms are in the units in GitHub).  We were thinking they would be an H5P activity (https://h5p.org/drag-the-words ), but there are a couple of issues here:
•	Some have over 20 terms with 1-2 sentences.  With H5P drag the words, it’s difficult (or impossible) to drag a word to an item that isn’t on the screen.  Is there another option?  Should we see how the first chapter looks?
•	Darren would like this graded.  Should we just create a matching quiz in Moodle?
 
(If we can't grade using H5P let's do this in Moodle)

**Comment by 345-Jay** [comment]
@kmarjanovic everything in this case seems to be completed. Is there anything that should be done for HIST 107?

**Comment by kmarjanovic** [comment]
Hi Jay,
The first Unit quiz has a number of mistakes in it.  Could you check it over?

Also - For each quiz, it should be set it up so that there are 15 random questions selected from the quiz database (e.g. unit 1 – choose 15 of the 24 questions from chapters 1 & 2).

There are several other H5P quizzes that need to be completed as well for each of the 4 units.   @cmadland can these be graded in H5P?  If not, please create matching quizzes in Moodle (content in Learning Activities for the units).

**Comment by 345-Jay** [comment]
I have this done before the end of the day.

Sincerely, 

Jared McGill

**Comment by 345-Jay** [comment]
Good morning,

I have made the necessary changes to HIST 107 Unit 1 Quizzes. Can you
verify?

Sincerely,

Jared McGill

**Comment by rezakh66** [comment]
@kmarjanovic Hi,
any update on how to present these quizzes? they are impossible by H5P. I can see 13 different quizzes need to be looked at.

**Comment by kmarjanovic** [comment]
Hi Reza,
Could you please make matching quizzes in Moodle for these assessments?

**Comment by kmarjanovic** [comment]
Hi @345-Jay,
For each quiz, please set it up so that there are 15 random questions selected from the quiz database (e.g. unit 1 – choose 15 of the 24 questions from chapters 1 & 2).
Please add the instructions:
After you have completed this unit, including all of the class learning activities, take the Unit ... quiz. There are 15 multiple choice questions and you will only have 10 minutes to complete the quiz.
This quiz is worth 5% of your course grade.

**Comment by rezakh66** [comment]
@kmarjanovic Hi,
I have matching quizzes 1.3,1.7,2.3,2.4 created. can you please have a look and let me know if you have any concern to be observed for them and rest of quizzes?

**Comment by 345-Jay** [comment]
@kmarjanovic I have created the random question for each Unit 1-2, 3-6, 7-11, and 11-15 respectively. Additionally, I added the Instructions for each unit as well. https://learn.twu.ca/course/view.php?id=10809&section=8

**Comment by kmarjanovic** [comment]
Hi @345-Jay ,
For Unit 1 Quiz and Unit 2 Quiz - there are a couple items in there that are the matching quizzes.  Could you remove these and make them their own separate quizzes?

There should be 11 Chapter Key term quizzes (in the course topics/activities) that we would like to pull out into a Moodle assessment (rather than H5P).

I've added a section in Moodle where these term quizzes can go: https://learn.twu.ca/course/view.php?id=10809&section=7

Thank you for your help!

**Comment by kmarjanovic** [comment]
Also, could you let me know where the matching quizzes 1.3,1.7,2.3,2.4 are located?

**Comment by cmadland** [comment]
@kmarjanovic As it turns out, we can't have a random question with 15 options...
![image](https://user-images.githubusercontent.com/12282929/72753501-f4a8b480-3b79-11ea-92e2-9432525fab5c.png)

We could do 10 or 20, or a 10 and a 5. Having a 10 and a 5 question quiz would likely lead to duplicates between the two questions.

Thoughts?
cm

**Comment by cmadland** [comment]
Also @kmarjanovic , @345-Jay is worried you will give him something more to do if he asks you a question...so here we are.

the Unit 1 quiz should be 15 of 24 questions from chapter 1-2. should the unit 2 quiz be 15 of 48 questions from ch 3-6? Or should it be proportional?

cm

**Comment by kmarjanovic** [comment]
Hi @345-Jay & @cmadland,
The instructor would like only 15 questions per quiz.  For the random selection, does it work to select 5 and then 10 can be random?
@345-Jay please keep asking questions!!  My apologies if things aren't clear!

**Comment by kmarjanovic** [comment]
I realize proportional questions would be better, but I lost that battle! :(

**Comment by cmadland** [comment]
Selecting 5, then a random question of 10 will still create duplicates. I can't find anywhere in Moodle that will allow a random question to pull 15...but will keep looking.

**Comment by kmarjanovic** [comment]
I'll check with Darren and see if we can change it to 20 questions.

**Comment by kmarjanovic** [comment]
Darren says we can make the quizzes out of 20.  @cmadland @345-Jay  does that help?

**Comment by rezakh66** [comment]
@kmarjanovic Hi Kelly, matching quizzes are all created at the bottom of each unit. please let us know if changes are needed @faitht1023

**Comment by kmarjanovic** [comment]
Hi @rezakh66 & @faitht1023 ,
These look great!  Could we possibly move them to the [Chapter Key Term Quizzes](https://learn.twu.ca/course/view.php?id=10809&section=7) section?
Also - since it is all in Question 1 - does this result in just one mark?  Is it possible to add numbers to each definition so students can see how many marks they get? (E.g. Quiz 1.3 marked out of 19).

**Comment by faitht1023** [comment]
@kmarjanovic, I'm editing the quizzes now and adding them to the Chapter Key Term Quizzes section. I've done 1.3 and 1.7 so far, please let me know if this is what you are looking for? I've changed the mark to be out of the number of terms there are per section, but I've left the maximum grade out of 10.

**Comment by faitht1023** [comment]
@kmarjanovic I've moved all the quizzes to the Chapter Key Term Quizzes section and changed the marks to reflect the number of questions in each quiz. This does not affect the weighting of the quizzes. Please let me know if you'd like something changed?

**Comment by kmarjanovic** [comment]
Thank you @faitht1023 !
Do you mind changing the titles so that it says the Chapter only? ("Chapter 1 Key Terms Quiz" instead of "Quiz 1.3")
Also - could you then delete the learning activities / alerts in the course that are this same content? (e.g. Activity 1.3).

**Comment by kmarjanovic** [comment]
@faitht1023  - rather than removing the learning activities / alerts in the course, I'll just modify the instructions and point to the assessment section.
Thanks for your help with this issue!

**Comment by kmarjanovic** [comment]
Could we please fix the unit quizzes?  They have 20 questions each - randomly selected from the test bank. (I see unit 1 has 10 questions, unit 2 has 1 question, unit 3 has 73 questions, unit 4 64 questions).

**Comment by faitht1023** [comment]
@kmarjanovic so sorry for the late reply on this! For the renaming of the chapter quizzes, there will be duplicates, i.e. there will be two "Chapter 1 Key Terms Quiz", four "Chapter 2 Key Terms Quiz", etc.. Is this what you would like? As well, for the unit quizzes, which questions should they be referencing?

**Comment by kmarjanovic** [comment]
Hi Faith, @faitht1023 
There should be just one quiz for each chapter (note there may be more than one chapter done in a unit, so there can be several quizzes per unit).  Please refer to the course to see what chapters the quizzes are testing and name accordingly (this was in the original document).
For the unit quizzes, please randomly select 20 from the test bank.
Thank you for your help!

**Comment by faitht1023** [comment]
@kmarjanovic I understand now about the Chapter quizzes, do you know where the original document is? I just want to be sure that I'm naming the quizzes appropriately, as there are a few issues with the naming and numbering of the questions.

**Comment by kmarjanovic** [comment]
Hi Faith,
I would suggest just going to the overview page of each unit.  In the Activity checklist it says the quizzes for that unit (Unit 1: Chapter Key Terms quizzes (Ch.1 & 2).
The original documents are all of the course files, so easier to look in Moodle/Git.

**Comment by kmarjanovic** [comment]
Thank you @faitht1023 !
