### ISSUE TITLE
Psych 331: summer 2022

### ISSUE THREAD

**Issue by Mike2625** [TWUOnline/bug-tracking#588]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 Unit 1: section 2.4
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 Read Chapter 5 from the textbook.

Also, we will watch a video ("The Case with Ruth") that is a model of the Alderian Approach. This will be shown in the synchronous class session. If you cannot make it, be sure to view the class recording. Please read section 3.1 in your book "A case of Ruth" and then as part of your grade please answer "Questions for Reflection" (section 3.3a). For further details, please see the assessment tab

Change to: 
Read Chapter 5 in the Reading Alderian Therapy

Also, we will watch a video on the cast of Stan that is a model of the alderian approach in class from the "How do I practice what I've learned" section in Chapter 5.  
Please also read section 3.1 in your mindtap "A Case of Ruth" and then answer the Questions for Reflection in section 3.3A.  The "Case of Ruth" readings are found in the section entitled: "The Case Approach Reading: Adlerian Therapy".
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  
2. Unit #         Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @Mike2625 this has been updated
