### ISSUE TITLE
PSYCH 331: SUMMER 2022

### ISSUE THREAD

**Issue by Mike2625** [TWUOnline/bug-tracking#591]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 Unit 4: section Activity 4.1
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 Activity 4.1: The Case of Stan (Behavioral Approach)
Read Chapter 9 of Theory and Practice of Counseling and Psychotherapy by Gerald Cory.

In our synchronous class session, we will continue with watching “The Case of Stan” through the lens of Behavioural Therapy. If you cannot attend, please watch the recorded lecture.

Ponder these questions:
 What are three techniques the therapist uses that would mirror what we have learned about the behavioral approach thus far from the video?
What are some strengths of this approach? How does it help implement change?
 What are some drawbacks to this approach? How might the focus on primarily behavior (and not the past or mindset) hinder a client from fully changing?

CHANGE TO: 
In the Synchronous session we will be watching "The Case of Stan" which is found in the section, "How do I practice what I've learned?" noted as "Case of Stan: Behavioral Therapy" 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  
2. Unit #         Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @Mike2625 this has been updated
