### ISSUE TITLE
FNDN 102 in Git

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#594]
### Course
FNDN 102
### URL
https://learn.twu.ca/course/view.php?id=20673
### Instructions
@MeeksonHundoo could you add all of the course content from FNDN 102 (all in Moodle) to a Git/Grav site?

@cmadland - I suppose we need a new repo for this.  FNDN 201 has [2 repos](https://github.com/TWUOnline?q=fndn&type=all&language=&sort=) - or does it make sense to have one that covers all FNDN courses, & SKLS courses from the Learning Commons?

This will require a lot of copying and pasting... and lots of reorganizing.  As long as all the content is in Git, I can rearrange and edit.
Let me know if you have any questions.
Thanks!
Kelly

**Comment by kmarjanovic** [comment]
@MeeksonHundoo could you please add the git links to the new Moodle course: https://learn.twu.ca/course/view.php?id=25352

**Comment by MeeksonHundoo** [comment]
Hello @kmarjanovic. Apologies for this delay. I've already started working on this and have uploaded 2 Units. I'll work on the remaining ones and have them uploaded soon.

**Comment by MeeksonHundoo** [comment]
Hello, @kmarjanovic I have uploaded all the 13 units to Bookdown. There were some H5Ps and word docs that I tried uploading, but I Couldn't.

**Comment by kmarjanovic** [comment]
Thank you so much @MeeksonHundoo !!
