### ISSUE TITLE
Remove Sections 

### ISSUE THREAD

**Issue by dhanenburg** [TWUOnline/bug-tracking#595]
**Which course contains the bug?**  - SOCI 201 OL Introduction to Human Services 
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 
 
**Describe the error and/or your suggestion**  - Please remove the "Course Evaluation" Section completely on the "Home" Tab. 
A clear and concise description of what the error or suggestion is.
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=23300
2. Unit #         Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @dhanenburg This has been updated.
