### ISSUE TITLE
PSYC 408 

### ISSUE THREAD

**Issue by JessD9** [TWUOnline/bug-tracking#596]
### Instructions
- @MeeksonHundoo Please upload Unit 1 to GiHub/Atom (may need to create PSYC 408 folder in github)

- Note: There is an infographic on Page 5 that I would like embedded. However, if this isn't possible, you can simply add the file as an attachment (i.e. "Click here to view Figure 1")

[PSYC408_U1_JUNE06_JD.docx](https://github.com/TWUOnline/bug-tracking/files/8848801/PSYC408_U1_JUNE06_JD.docx)

Let me know if you have questions. Thanks!

**Comment by MeeksonHundoo** [comment]
Hello @JessD9 Unit 1 has been updated.

**Comment by JessD9** [comment]
Thank You @MeeksonHundoo. Please upload Units 2 & 3.
Let me know if you have any questions.

[PSYC408_U2_June16_JD.docx](https://github.com/TWUOnline/bug-tracking/files/8924820/PSYC408_U2_June16_JD.docx)
[PSYC408_U3_June16_JD.docx](https://github.com/TWUOnline/bug-tracking/files/8924823/PSYC408_U3_June16_JD.docx)

**Comment by JessD9** [comment]
Hi @MeeksonHundoo. Here is Unit 4.

[PSYC408_U4_June22_JD.docx](https://github.com/TWUOnline/bug-tracking/files/8962798/PSYC408_U4_June22_JD.docx)

**Comment by JessD9** [comment]
Hi @MeeksonHundoo. Here are the last two units. 
Thanks again!

[PSYC408_U5_June27_JD.docx](https://github.com/TWUOnline/bug-tracking/files/8995519/PSYC408_U5_June27_JD.docx)

[PSYC408_U6_June27_JD.docx](https://github.com/TWUOnline/bug-tracking/files/8995516/PSYC408_U6_June27_JD.docx)

**Comment by MeeksonHundoo** [comment]
Hello @JessD9 All units have been updated

**Comment by JessD9** [comment]
Much appreciated. Thank you @MeeksonHundoo
