### ISSUE TITLE
Psych 331 Summer 2022:

### ISSUE THREAD

**Issue by Mike2625** [TWUOnline/bug-tracking#598]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019) 
 **{Psych 331 Summer 2022 Unit 4 Section 4.5**

**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
  Under the section that gives them info on the "Case of Stan" with specific page numbers please add the following info

"For those of you who have the mindtap (not the textbook), please pick ONE of the three "Questions for Reflection" on the case of Ruth based on the theory you most are comfortable with:  These sections are located as follows in the section entitled "Case Approach Reading":
The Behavior Approach: 7-4A
CBT Approach: 8-4A
Reality Therapy Approach: 9-4A

 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  
2. Unit #         Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @Mike2625 this has been updated
