### ISSUE TITLE
Psych 331 summer 2022

### ISSUE THREAD

**Issue by Mike2625** [TWUOnline/bug-tracking#599]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 
 Unit 5: Topic 1
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 Under the pages noted as 374-376 please add the following:
"You can find info on Solution Focused therapy in section 13-3 on the mindtap if you don't have the textbook"

In the same unit and same "page", under activity 5.1 please add the following to the page numbers in chapter 13:
"For those of you on the mindtap, you can find this in the reading in section 13-3"

 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  
2. Unit #         Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @Mike2625 This has been updated
