### ISSUE TITLE
Production - LDRS 300 - Guide

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#60]
### Course
LDRS 300
### URL
https://far.twu.ca/guides/lead-ba
### Instructions
Please add attached
[LDRS 300 Facilitator's Guide.docx](https://github.com/TWUOnline/bug-tracking/files/3727516/LDRS.300.Facilitator.s.Guide.docx)
 to LDRS 300 Facilitators guide - Lesson Notes (1st 2 sections will be course overview and schedule)

**Comment by faitht1023** [comment]
added everything on the docx to the website (units 1-6), however, missing course overview/schedule

**Comment by kmarjanovic** [comment]
Could you also add the course description and course evaluation sections from here:
https://github.com/TWUOnline/ba-lead/blob/master/pages/04.ldrs300/06.home/page.md

We won't worry about the schedule for now.
Thank you!!

**Comment by cmadland** [comment]
@faitht1023 would you please have a look at this?

**Comment by faitht1023** [comment]
@kmarjanovic , I've changed the guide to reflect the 300 material now, but did you want me to remove https://far.twu.ca/guides/lead-ba/ldrs-300-leadership-as-service/facilitation-notes for now? It has some notes and the schedule

**Comment by kmarjanovic** [comment]
Thanks Faith!  Yes, please remove for now.
@faitht1023

**Comment by faitht1023** [comment]
I have removed it @kmarjanovic

**Comment by kmarjanovic** [comment]
Please make changes to the guide according to the syllabus and notes from Brenda:
[LDRS-300-IF-Syllabus-Sasaki-2020.docx](https://github.com/TWUOnline/bug-tracking/files/4450491/LDRS-300-IF-Syllabus-Sasaki-2020.docx)

[LDRS-300-Facilitators-Guide.docx](https://github.com/TWUOnline/bug-tracking/files/4450494/LDRS-300-Facilitators-Guide.docx)

### Notes
Here is what I need to do/ still needs to be done: 

Course Overview Page: I have changed the syllabus since the fall and just need the new one uploaded. (I have attached the new one in this email). 

Unit 7 - there is no content there so I need to write that unit's content.

Unit 10 - it is the wrong content from a different course. Can someone from your team please remove all of unit 10 and then I can write the content for this unit.

Assessment Details page - is all wrong - it is content from another course. Can someone from your team remove all of this page and then I can write the content for this unit. (Although I will definitely need help with the tables in git-hub -- have not figured that one out yet).

Blank page at the end of the guide - may I ask what that is for? (delete)
