### ISSUE TITLE
Psych 331 Summer 

### ISSUE THREAD

**Issue by Mike2625** [TWUOnline/bug-tracking#600]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 Unit 5 :section 5.2
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 Underneath the section that has the page numbers in the text please add the following:
"For those you who have the mindtap, you will find this in the reading section of chapter 13 in 13-3 and following"
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  
2. Unit #         Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @Mike2625 this has been updated
