### ISSUE TITLE
Psych 331: summer

### ISSUE THREAD

**Issue by Mike2625** [TWUOnline/bug-tracking#601]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 Unit 5: Topic 4

Next to each page number in the brackets ( ), please add the following:

Bowen: "in the mindtap, look to section 14-2"
Structural: "In the mindtap look to section 14-2A"
Genogram: "In the mindtap look to section 14-3 and in the casestudy section on Ruth"
 
On the same page, Under activity 5.6 add this to the page numbers:
"In the mindtap, you can find the Questions for Reflection in the casestudy sections: in Chapter 14 in 12-2 and in Chapter 13 in section 11-5A"

 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  
2. Unit #         Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @Mike2625 This has been updated
