### ISSUE TITLE
PSYC 354 guide

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#602]
### Course
[PSYC 354 (ADC MASTER)](https://learn.twu.ca/course/view.php?id=23420)
### URL
https://learn.twu.ca/course/view.php?id=23420&section=16
### Instructions
Please add the attached to the guide section
[PSYC 354 Instructor Guide_June 2022.docx](https://github.com/TWUOnline/bug-tracking/files/9022101/PSYC.354.Instructor.Guide_June.2022.docx)
.

See [Instructor's Guide](https://learn.twu.ca/course/view.php?id=15808&section=14) as an example

**Comment by MeeksonHundoo** [comment]
Hello @kmarjanovic Was in the middle of working on it, when my ATOM crashed again. Will fix this issue and start working on the remaining part of the instructors guide.

**Comment by MeeksonHundoo** [comment]
Hello @kmarjanovic this has been added now.

**Comment by kmarjanovic** [comment]
Thanks so much @MeeksonHundoo !!
