### ISSUE TITLE
FNDN 102 from Bookdown to Moodle

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#603]
### Course
[FNDN 102 (FAR MASTER)](https://learn.twu.ca/course/view.php?id=25352)

### URL
https://animated-sniffle-c26f9054.pages.github.io/
https://learn.twu.ca/course/view.php?id=25352

### Instructions
Could you please help move the bookdown content into the FAR Master shell?  I think it will be easier to make edits in Moodle (for the SME) and then transfer back into bookdown.

**Comment by kmarjanovic** [comment]
I've asked @dgaudet48 to help with this course in Bookdown - as we're getting new content from the SME.  

I think we'll get all the edits in Bookdown - then maybe convert to Moodle html if needed.  I'll close this for now.

**Comment by MeeksonHundoo** [comment]
Cool @kmarjanovic thanks for informing me about it.
