### ISSUE TITLE
SKLS 500 intro & U1

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#605]
### Course
SKLS 500
### URL
new bookdown course
### Instructions
Please add the Course Overview info and Unit 1 to a new bookdown format.
[SKLS 500_Intro_U1_July19_KM-for production.docx](https://github.com/TWUOnline/bug-tracking/files/9146083/SKLS.500_Intro_U1_July19_KM-for.production.docx)

**Comment by kmarjanovic** [comment]
@MeeksonHundoo is there an update to this unit?  Will it be ready for Monday? I'd like to show the SMEs.
Thanks!

**Comment by MeeksonHundoo** [comment]
Hello @kmarjanovic I've added the overview and Unit 1 to Bookdown.

**Comment by kmarjanovic** [comment]
@MeeksonHundoo could you please provide the bookdown link?

**Comment by kmarjanovic** [comment]
Hi @MeeksonHundoo 
Could you help with formatting issues in Unit 1?  Linking urls, embedding videos, etc.

Please see for examples:
https://ma-lead.github.io/ldrs591/introduction-to-scholarly-inquiry.html
https://ma-lead.github.io/ldrs664/the-heart-of-a-teacher.html

**Comment by kmarjanovic** [comment]
@MeeksonHundoo 
I've done some U1 edits:
- [ ] Activity checklist - add a space after line so there is a break.
- [ ] Take out tips for instructors
- [ ] embed videos (see code in topic 1.1)
- [ ] add activity boxes 
- [ ] add media boxes
- [ ] add images

I still need help with the following
- [ ] add H5Ps
- [ ] fix image (not sure why this code didn't work: [a young woman taking a break from technology](assets/unit1/istockphoto-1173619383-612x612.jpg)

I had to stop at [Activity 1.3](https://jubilant-system-53a680b6.pages.github.io/introduction-to-the-writing-centre.html#activity-1.3-practice-a-prewriting-strategy).  Could you continue with edits?

**Comment by MeeksonHundoo** [comment]
Hello @kmarjanovic thanks for making the edits. I continued with editing and have made all the edits. Could you please take a look now and let me know if  any changes are needed ? Here is the link: https://jubilant-system-53a680b6.pages.github.io/introduction-to-the-writing-centre.html
Also, link https://miro.com/wisemapping.com/ under Learning Activity 1.3 is not correct. This page does not have any content. Could you maybe please check and advice on this too.

**Comment by kmarjanovic** [comment]
Thanks Meekson!  It's looking good...I'll do a full review this weekend.
Please change link to https://miro.com/

**Comment by MeeksonHundoo** [comment]
thanks @kmarjanovic I've updated the link.

**Comment by kmarjanovic** [comment]
Thanks @MeeksonHundoo !

Could you double check all links open in a new window?  That way students won't have trouble getting back to the course book.  I forget the code for this...

**Comment by kmarjanovic** [comment]
Hi @MeeksonHundoo 
Please fix the following:
- [ ] Topic 1: Add before the videos:  Watch the following videos on TWU's Writing Centre.
- [ ] Delete [Intro to Writing Centre PPT from Canva](https://www.canva.com/design/DAFDImlB2cU/SGzyksNUOlDmYSJyLE3BOg/watch?utm_content=DAFDImlB2cU&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink)
- [ ] Is it possible to enlarge the first embedded video (Canva) ?
- [ ] Activity 1.1 - hyperlink:  Log in via the Booking System [here](https://www.twu.ca/learning-commons/writing-centre/contact-us]
- [ ] Activity 1.2: - move first bullet into bullet list (see word doc as reference) (•	Where do you work best?)
- [ ] Strategies for understanding the assignment: - fix bullet 2 and 3
- [ ] Brainstorming Techniques - fix bullets (not lines)
- [ ] Bullet lists aren't consistent (sorry - I should have caught that in the word doc!)  Could you check all bullets are properly formatted?
- [ ] Activity 1.3  - change to Outline Tips: (remove Videos on )
- [ ] add bullet to [Types of Outlines and Samples](https://owl.purdue.edu/owl/general_writing/the_writing_process/developing_an_outline/types_of_outlines.html)
- [ ] Add colon to Videos on Brainstorming Tips and Brainstorming apps  - and capitalize Apps
- [ ] Stage 2L Drafting sections: move to first bullet point: • “Messy and Fat” Draft: 
- [ ] Stage 3: Revision - check bullet points
- [ ] Stage 4 - check bullet points
- [ ] Activity 1.5 - change to [Revision and Editing Checklist](https://www.twu.ca/sites/default/files/revision-editing-checklist.pdf);  delete repetition 
- [ ] Activity 1.6- add period - Freewrite for 10 minutes or discuss with a partner 
- [ ] Resources Revision and Editing Checklist PDF [Revision Checklist](https://www.twu.ca/sites/default/files/revision-editing-checklist.pdf) -  delete repetition 

- [ ] Topic 3 - check formatting.  bullets not formatted
- [ ] After Activity 1.7 - Resources - please add "Additional" Resources
- [ ] make a bulleted list - not embedded
 -   *Emailing a Professor. (2020).* Purdue University. Retrieved June 22, 2022,
    from   <https://www.purdue.edu/advisors/students/professor.php>  
-   [Communicating Through Email](https://h5pstudio.ecampusontario.ca/content/5807) from Ecampus Ontario.
-   [Parts of an Email](https://h5pstudio.ecampusontario.ca/content/5807) from Ecampus Ontario.


- [ ] Assessment: Learning Log Entries - please format the numbered list.
- [ ] Checking your Learning  - remove 1.4

**Comment by MeeksonHundoo** [comment]
Hello @kmarjanovic I've made the aforementioned changes. However, I could not enlarge the first Canava video and also the 1.4 is not there in Atom. I don't know where that figure is being pulled from? Requesting you to please take a look and advice.

**Comment by kmarjanovic** [comment]
Hi @MeeksonHundoo 
Thanks so much for these changes!
I can't see the book online now since we've hidden the units...so things like the 1.4 wouldn't show in Atom - as the numbering system is generated.  Is this the code for not showing numbers? {-}

I'll check Atom again - and I suppose we just rely on RStudio to see the preview until we're ready to show a unit, correct?  @cmadland can we show Unit 1?  (Please let me know how)

**Comment by kmarjanovic** [comment]
Please fix bullets in 
https://learning-commons.github.io/skls500/index.html#course-objectives
and 
https://learning-commons.github.io/skls500/index.html#course-navigation

**Comment by kmarjanovic** [comment]
- [ ] Please hide https://learning-commons.github.io/skls500/course-communities.html page
- [ ] Unit 1 Activity Checklist - please add email icon to last item 📧
- [ ] Stage 1 Prewriting - please make accordion for these sections and note tense changes and intro sentence

Click on each section for a Prewriting strategy
Understanding the Essay Prompt
Brainstorming
Surveying the Literature
Choosing a Focus
Outlining

- [ ] Activity 1.5 - take out **
- [ ] Topic 3 : - take out space between 3 and :
- [ ] Additional Resources section should be a bulleted list of the resources.  Please take out the embedded video and h5p.  Instead, have:

Emailing a Professor. (2020). Purdue University. Retrieved June 22, 2022,
from   https://www.purdue.edu/advisors/students/professor.php  

[Communicating Through Email](https://h5pstudio.ecampusontario.ca/content/5807) from Ecampus Ontario.

[Parts of an Email](https://h5pstudio.ecampusontario.ca/content/5807) from Ecampus Ontario.

- [ ] After the Assessment section, please add a note in a red box:
To submit assignments, please go to the Assessment section in Moodle and locate the instructions and assignment dropbox.

Add grading criteria:

<html>
<body>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(29, 33, 37); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, &quot;Liberation Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(248, 249, 250); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><b style="box-sizing: border-box; font-weight: bolder;"><i style="box-sizing: border-box;">Grading Criteria:</i></b><b style="box-sizing: border-box; font-weight: bolder;"><i style="box-sizing: border-box;"> </i></b></p><p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(29, 33, 37); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, &quot;Liberation Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(248, 249, 250); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"> </p><p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(29, 33, 37); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, &quot;Liberation Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(248, 249, 250); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><b style="box-sizing: border-box; font-weight: bolder;">Learning Log  Rubric</b><a id="_anchor_2" href="https://mytwu-my.sharepoint.com/personal/kelly_marjanovic_twu_ca/Documents/Documents/TWU/Learning%20Commons/SKLS%20500/SKLS500_U2_Aug17_KM.docx#_msocom_2" language="JavaScript" name="_msoanchor_2" style="box-sizing: border-box; color: rgb(35, 117, 218); text-decoration: none; background-color: transparent;"></a><br style="box-sizing: border-box;"><b style="box-sizing: border-box; font-weight: bolder;"></b></p>

Grading Criteria -   (80% is passing) | Weight | Score:  ____/100
-- | -- | --
Almost all parts of the writing prompt are addressed. It shows attempts at critical thinking and understanding of the content | 40% |  
Response is organized and  ideas are adequately developed, and ideas are clear and with sufficient detailed | 20 % |  
Paragraphs have a clear, central idea and ideas are linked.  There is some attempt at managing cohesion. | 10 % |  
Page format, citations, and references are appropriate to style (APA, MLA, ect.) | 10 % |  
Some errors in grammar, punctuation, or vocabulary, yet does not detract from meaning. | 10 % |  
Academic register and tone is developing, with some variation in  word choice and sentence type | 10 % |  

<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(29, 33, 37); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, &quot;Liberation Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(248, 249, 250); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><i style="box-sizing: border-box;">Additional Comments</i></p>
</body>
</html>

**Comment by kmarjanovic** [comment]
Sorry - please disregard criteria above!  This is the updated one:

Your Learning Log Entry should be approximately 250 words long and will be graded
according to the following checklist: 

| **Grading Criteria**                                                                                                                   |
|----------------------------------------------------------------------------------------------------------------------------------------|
| **Content:**   All parts of the writing prompt are addressed.                                                                          |
| **Organization**: Response is organized, and ideas are adequately developed,  clear, and have sufficient detail.                       |
| **Paragraph structure: **   Paragraphs have a clear, central idea and ideas are linked.  There is some attempt at managing cohesion.   |
| **Formatting:**   Page format, citations, and references are appropriate to style (APA, MLA, etc.)                                     |
| **Grammar:**   Some errors in grammar, punctuation, or vocabulary, yet does not detract from meaning.                                  |
| **Word Choice:**   Academic register and tone is developing, with some variation in  word choice and sentence type.                    |
| **Critical Thinking:**   All parts of the writing prompt are addressed. Displays critical thinking and understanding of the content    |

*Additional Comments:* * *

**Comment by kmarjanovic** [comment]
Please fix on the home page (index in R)
- [ ] Course Objectives - please fix bullets

- [ ] Grading System - the directions to the grading system are outdated - probably in all our courses, and from what I see in the newest syllabi templates.  Yikes!  We should change it to:
The Standard Grading System can be found on the TWU website at [https://www.twu.ca/about/policies-guidelines/university-standard-grading-system](https://www.twu.ca/about/policies-guidelines/university-standard-grading-system)

- [ ] delete red note: Note that not all sections of this course use all of the above resources. Please confirm which of the following texts are required by checking your course syllabus.

- [ ] Course navigation - fix bullets

**Comment by kmarjanovic** [comment]
@cmadland could we hide the Communities page?  I need feedback from SMEs on this.
https://learning-commons.github.io/skls500/course-communities.html

**Comment by cmadland** [comment]
yes. done

**Comment by kmarjanovic** [comment]
Closing issue!  Intro & unit 1 done!!  Yay!:)
