### ISSUE TITLE
Restore blank Moodle

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#606]
**Which course contains the bug?**  

[PSYC 490 OL (FA22)](https://learn.twu.ca/course/view.php?id=25128)
 
 
**Describe the error and/or your suggestion**  

Please delete the first 4 tabs from the fall section (intro, Module 1,2,3).  Maybe this requires restoring the course?  Please don't delete enrolled students!

**Comment by MeeksonHundoo** [comment]
Hello @kmarjanovic I was able to delete Module 1,2 & 3. However, introduction is just not getting deleted. I tried various ways of doing it, but it just wont delete. Could you please take a look at it.

**Comment by kmarjanovic** [comment]
Hi Meekson,
This is great!  Thank you so much!
