### ISSUE TITLE
LDRS 667 OL - Practicum (FA 2022)

### ISSUE THREAD

**Issue by DocV77** [TWUOnline/bug-tracking#607]
**Which course contains the bug?**  
- LDRS 667 OL - Practicum (FA 2022)
 
**Describe the error and/or your suggestion**  
I inherited the course from another instructor and there are some text changes and link changes that need to be made
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. Course introduction tab-Assessment Summary-% values are incorrect (https://learn.twu.ca/course/view.php?id=24340) 
2. Prework tab-Activity checklist-Activity 0.2 (in blue box) _If you need a refresher on how to write Learning Outcomes for your Practicum, read: Queens University Center for Teaching and Learning. (n.d.)_ [“Learning outcomes; course/curriculum design.”](http://www.queensu.ca/ctl/teaching-support/course-and-program-design)-link broken and needs to be replaced with current link (https://learn.twu.ca/course/view.php?id=24340&section=3#tabs-tree-start)
**Optional: Screenshots**  
![ldrs 667ol change 1](https://user-images.githubusercontent.com/111535268/185484288-a80cce09-0344-4478-aa62-1dc23e80f68d.jpg)
![ldrs 667ol change 2](https://user-images.githubusercontent.com/111535268/185484290-7c849414-023c-4133-8768-5510d26a9fb3.jpg)

**Comment by kmarjanovic** [comment]
@MeeksonHundoo @cmadland just checking if this issue was addressed?

**Comment by MeeksonHundoo** [comment]
Hello @DocV77 these edits have been made.

**Comment by kmarjanovic** [comment]
@MeeksonHundoo could you fix these issues please?

**Comment by MeeksonHundoo** [comment]
Hello @kmarjanovic this has been updated now.

**Comment by kmarjanovic** [comment]
Hi @MeeksonHundoo,
Thanks for trying - but it looks like a screenshot.  Could you edit the table in Git?  I know there's a certain code for extra lines in a table, so I can look that up on Monday if it helps.

**Comment by MeeksonHundoo** [comment]
Hello @kmarjanovic I did it now. Could you please take a look.

**Comment by kmarjanovic** [comment]
Perfect!  Thank you @MeeksonHundoo !
