### ISSUE TITLE
FNDN 102 Moodle request

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#608]
### Course
FNDN 102
### URL
multiple! ;)

### Instructions
Hi Meekson,
Could you please import [FNDN 102 Master](https://learn.twu.ca/course/view.php?id=20673) into the [FNDN 102 FAR Master](https://learn.twu.ca/course/view.php?id=25352&section=0#tabs-tree-start)?

I accidentally imported the wrong [FNDN 102 old master](https://learn.twu.ca/course/view.php?id=3640) so please help delete that content first (I've tried a few things and it's not working!).

Since we're having R/bookdown issues - I might just update this course in Moodle until we sort out our tech issues.

**Comment by MeeksonHundoo** [comment]
Hello @kmarjanovic this has been done.. Here is the link for the FNDN 102 : Human Flourishing (FAR MASTER)  https://learn.twu.ca/course/view.php?id=25352

**Comment by kmarjanovic** [comment]
Thank you!
