### ISSUE TITLE
delete tab

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#613]
**Which course contains the bug?**  
https://learn.twu.ca/course/view.php?id=18002&section=1#tabs-tree-start

[LDRS 634: Accountability & Performance (DEV MASTER)](https://learn.twu.ca/course/view.php?id=18002&section=1#tabs-tree-start)

**Describe the error and/or your suggestion**  
Please delete Schedule tab - and let me know how to do this in the new Moodle.

**Comment by MeeksonHundoo** [comment]
Hello @kmarjanovic this has been done!

**Comment by kmarjanovic** [comment]
Thank you!
