### ISSUE TITLE
Production SKLS 500 units

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#619]
### Course
SKLS 500
### URL
~~https://jubilant-system-53a680b6.pages.github.io/~~
https://learning-commons.github.io/skls500

### Instructions
Please add Units 3 and 5 to Bookdown course.

[SKLS500_U3_Aug31_KM - for production.docx](https://github.com/TWUOnline/bug-tracking/files/9464603/SKLS500_U3_Aug31_KM.-.for.production.docx)
[SKLS 500 _U5__August31_KM - for production.docx](https://github.com/TWUOnline/bug-tracking/files/9464618/SKLS.500._U5__August31_KM.-.for.production.docx)

Notes:
There are several H5P requests within the units.  Please create and let me know if you have any questions.

**Comment by kmarjanovic** [comment]
@cmadland could you help embed the course book [here](https://learn.twu.ca/course/view.php?id=25448&section=3)?

I tried to copy what [664](https://learn.twu.ca/course/view.php?id=22648&section=1) did but it's not working

<p><iframe scrolling="yes" style="border: 0px #ffffff none;" src="https://ma-lead.github.io/ldrs664" allowfullscreen="allowfullscreen" width="100%" height="970"></iframe></p>

**Comment by kmarjanovic** [comment]
As the SMEs are looking at the course, could you please delete the Module 4 content?  It must be from a different course.

**Comment by MeeksonHundoo** [comment]
Hello @kmarjanovic I have deleted all the content from Module 4

**Comment by kmarjanovic** [comment]
In the Moodle [Course Intro page](https://learn.twu.ca/course/view.php?id=25448&section=0) - there is a grey box around Course Learning Outcomes.  I can't seem to take the box out...or to add it to the other Headings, as it actually looks nice.  Could someone help fix this - either take out or replicate?

**Comment by kmarjanovic** [comment]
Please add Unit 2.  Note there are some H5P requests in the unit.  Please let me know if you have any questions.
Thank you!
[SKLS500_U2_Sept8 for Production.docx](https://github.com/TWUOnline/bug-tracking/files/9530192/SKLS500_U2_Sept8.for.Production.docx)

**Comment by kmarjanovic** [comment]
Please embed videos from Jack

https://web.microsoftstream.com/user/5df75f53-73c4-4ee1-82d0-3bd3c0354700

**Comment by kmarjanovic** [comment]
Please add unit 8
[SKS 500_U8_Sept9-for production.docx](https://github.com/TWUOnline/bug-tracking/files/9538199/SKS.500_U8_Sept9-for.production.docx)

**Comment by kmarjanovic** [comment]
Please add unit 7
[SKLS500_U7_sept9 - for production.docx](https://github.com/TWUOnline/bug-tracking/files/9538292/SKLS500_U7_sept9.-.for.production.docx)

![U7_4-pillars-of-analytics](https://user-images.githubusercontent.com/35148983/189432346-9bb8c5a4-49fb-4fe0-ae78-61d8ac5b0c80.png)

**Comment by kmarjanovic** [comment]
- [ ] Please change name of Unit 5 to Essay Formatting
- [ ] Unit 3 Overview: change "We will then move on to writing clear body paragraphs and focusing on strategies..." to "We will then move on to writing clear body paragraphs with a focus on strategies..."

**Comment by kmarjanovic** [comment]
Please add Unit 4.  That's the last of the units!!  Now for reviewing online...
Thanks @cmadland and @MeeksonHundoo for your help!
[SKLS500-Module4-Sep9-for production.docx](https://github.com/TWUOnline/bug-tracking/files/9538556/SKLS500-Module4-Sep9-for.production.docx)

**Comment by kmarjanovic** [comment]
Please edit formatting in Unit 3.  I can make a list this weekend, but if you see errors in font size, colour boxes, bullets, please change.

**Comment by cmadland** [comment]
Is there a unit 6?

**Comment by kmarjanovic** [comment]
yes - just reviewing SME comments from Friday.  will upload soon!

**Comment by cmadland** [comment]
ok...I have everything up to u8 (except 6) built 'as is' from the Werd files...will continue with formatting.

**Comment by cmadland** [comment]
ok, file is uploaded and converted to md.

**Comment by cmadland** [comment]
working on u3 this morning

**Comment by kmarjanovic** [comment]
Unit 2 comments
- [ ] Please embed the H5P for Activity 2.6 when ready (see issue https://github.com/TWUOnline/bug-tracking/issues/611)
other requests...not urgent:
- [ ] For all links (videos, pdfs, etc.) - can we check that they open in a new tab?  In these long units, it's hard to find where you left off, so a new tab will help.
- [ ] For all the learning commons videos - could we embed those?  Do we need a direct link from Emily to do this?  
- [ ] below most of the LC videos there is an H5P quiz.  Could we embed? e.g. https://learningcommons.twu.ca/how-to-use-cms/topic-1-general-format/topic-2-how-do-i-format-in-text-citations/topic-3-how-do-i-format-the-works-cited/


Thank you @cmadland !!!

**Comment by kmarjanovic** [comment]
Unit 3 note:
- [ ] Please add a Tips box to the [Navigation section](https://learning-commons.github.io/skls500/index.html#course-activities) to reflect what is [here](https://learning-commons.github.io/skls500/essay-structure.html#main-points). We should check that Note boxes have colours consistent with navigation. e.g. [example box](https://learning-commons.github.io/skls500/essay-structure.html#paragraph-structure)?

Other than that - Unit 3 is all done!  Thanks Colin!!

**Comment by kmarjanovic** [comment]
Unit 4
- [ ] I did most edits except for that last table - help please! https://learning-commons.github.io/skls500/introduction-to-research.html#activity  
- [ ] Also saw your comments, but will have to wait to address those with the SMEs 
- [ ] For other units, see generic language

**Comment by cmadland** [comment]
> Unit 2 comments
> 
>     * [x]  Please embed the H5P for Activity 2.6 when ready (see issue [SKLS 500 H5P Activities - Unit 2 #611](https://github.com/TWUOnline/bug-tracking/issues/611))
>       other requests...not urgent:
> 
>     * [ ]  For all links (videos, pdfs, etc.) - can we check that they open in a new tab?  In these long units, it's hard to find where you left off, so a new tab will help.
- done up to u4...will continue as I go through the rest
> 
>     * [ ]  For all the learning commons videos - could we embed those?  Do we need a direct link from Emily to do this?
> 
Tried this and there seemed to be a block...will check again

>     * [ ]  below most of the LC videos there is an H5P quiz.  Could we embed? e.g. https://learningcommons.twu.ca/how-to-use-cms/topic-1-general-format/topic-2-how-do-i-format-in-text-citations/topic-3-how-do-i-format-the-works-cited/

Only if we embed the videos...

**Comment by kmarjanovic** [comment]
Changes to Assessment section ([here](https://learning-commons.github.io/skls500/assessment-10.html#assignment-formatting-correction-task-activity-1))

Assignment: Formatting Correction Task Activity

1.  Open the *APA Format and Page Set-up Activity Paper* and the *APA Format
    Checklist.*

2.  Then, using the *APA Format and Page Set up Activity Paper* , go through the
    *APA Format Checklist,* step-by-step, and make any corrections to the sample
    paper. **Highlight the changes you’ve made.**

3.  Name the completed assignment: *ReverseOutline_Month Day_YourFullName.*

4.  Submit both the correct paper and your checklist (completed) to the dropbox
    with Teammates’ names.

### Grading Rubric

| **Criteria for Evaluation**                                                                                                                                    | **Weighting** |
|----------------------------------------------------------------------------------------------------------------------------------------------------------------|---------------|
| **Style Guidelines:** Page Setup follow APA guidelines. Font style and size is consistent, line spacing is correct, and alignment and margins are appropriate. | /20           |
| **Title Page:** All required information is present with correct font style, spacing, and alignment.                                                           | /20           |
| **Body:** APA guidelines for spacing and margins are correct. Paragraphs, citations, and headings are formatted appropriately.                                 | /30           |
| **References:** APA guidelines for formatting are appropriate, as well as alignment, spacing, and indentation.                                                 | /30           |
| *Total*                                                                                                                                                        | */100*        |

Also please link these docs 
[Unit 5 Assignment - APA Formatting Activity.docx](https://github.com/TWUOnline/bug-tracking/files/9657935/Unit.5.Assignment.-.APA.Formatting.Activity.docx)
[Unit 5 Assignment - APA Formatting Checklist.docx](https://github.com/TWUOnline/bug-tracking/files/9657936/Unit.5.Assignment.-.APA.Formatting.Checklist.docx)

**Comment by kmarjanovic** [comment]
not sure what's going on with that Unit 4 activity...https://learning-commons.github.io/skls500/introduction-to-research.html#activity

**Comment by kmarjanovic** [comment]
Unit 6 comments:
- [ ] Please fix image https://learning-commons.github.io/skls500/reflective-writing.html#learning-activities - 3rd activity under Additional Resources.  If its too big, should we link out?  Or a Click to Enlarge feature?
- [ ] for learning log entries in the units - let's keep it generic.  see (Unit 5 example)[https://learning-commons.github.io/skls500/essay-formatting.html#learning-log-entries-2].  All logs (and assignment details) will be the in [Assessment section](https://learning-commons.github.io/skls500/assessment-10.html)
- [ ] some strange formatting [here](https://learning-commons.github.io/skls500/reflective-writing.html#introduction-1).  Is there another way we can show this?

**Comment by kmarjanovic** [comment]
Unit 7 comments:
- [ ] Please fix target blank: https://learning-commons.github.io/skls500/analysis-and-evaluative-writing.html#activity-watch-and-reflect-1
- [ ] Please fix formatting here: https://learning-commons.github.io/skls500/analysis-and-evaluative-writing.html#using-thus-to-connect
- [ ] some formatting issues in the assessment as well: https://learning-commons.github.io/skls500/assessment-8.html#assignment-3-genre-specific-analysissummary-2
- Note, I'll need to changes numbering as it's a bit confusing!  Will check with SMEs.
- I played around with the table...not sure if it works.  check it out: https://learning-commons.github.io/skls500/analysis-and-evaluative-writing.html#writing-tip-1-choosing-the-proper-point-of-view
- [ ] References section may need a clean up later.

**Comment by kmarjanovic** [comment]
@cmadland could you see if you can fix this:
- [ ] when you click on [Assessment](https://learning-commons.github.io/skls500/assessment-3.html) it opens up all the tabs on the table of contents.

**Comment by kmarjanovic** [comment]
H5P plugin code?
https://learning-commons.github.io/skls500/research-writing.html#activity-read-and-organize

**Comment by kmarjanovic** [comment]
I think this is done!  Let's have another look before the fall term to suggest improvements.
