### ISSUE TITLE
missing PPT 1.2 for LDRS 300 IF Unit 1, Topic 2

### ISSUE THREAD

**Issue by BLMSasaki** [TWUOnline/bug-tracking#62]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 LDRS 300 IF
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 
 Missing PPT 2.1 for Unit 1, Topic 2
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  
2. Unit #         Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by cmadland** [comment]
I have slides for 2.3, but not 2.1...I think. What is the title?

**Comment by kmarjanovic** [comment]
2.1 is actually in the unit, not a separate PowerPoint.  (Originally I was integrating, but due to time/lesson flow, we've kept the rest of the PowerPoints).

I've changed the wording in the activity, so this should be resolved. (Sorry - I thought I closed the issue)
