### ISSUE TITLE
LDRS 591 OL FA 2022: Dates need to be updated for Course Schedule

### ISSUE THREAD

**Issue by cpenfoldnavarro** [TWUOnline/bug-tracking#620]
**Which course contains the bug?**  
-  LDRS 591 OL FA 2022)
 
 
**Describe the error and/or your suggestion**  
Course Schedule needs to be updated to reflect current term dates.
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=25409
2. Unit #    Course Schedule     Topic #         Activity#  
3. ALL DATES NEED TO BE UPDATED 
 
**Optional: Screenshots**  
Attached is the content from this page with edited dates (highlighted in yellow)
Also, one edit suggested for capitalization (see comment in attached document)

[Edits to Course Tab in LDRS 591 OL FA 2022.docx](https://github.com/TWUOnline/bug-tracking/files/9500564/Edits.to.Course.Tab.in.LDRS.591.OL.FA.2022.docx)

**Comment by kmarjanovic** [comment]
@cmadland or @MeeksonHundoo could you please help Cathy with edits to the schedule?  I've hidden the old Git Schedule and created a new schedule that can be edited in Moodle:  https://learn.twu.ca/course/view.php?id=25409&section=2#tabs-tree-start

Could you please use the info from Cathy's attached schedule to modify what's online? (then we can delete the git tab)

Thank you!

**Comment by cpenfoldnavarro** [comment]
I see the new tab you added, Kelly, and have updated the content in the "Course Schedule" tab on the right. I also selected "show topic" so that tab is now visible to students.

It doesn't have all the fancy icons before each item (which is awesome) but I have added bullets and heading formats throughout.

If someone could double-check this to be sure it's visible, that would be wonderful.

The "Course Schedule" tab on the left which has dates from Dec/Jan etc.) can now be deleted.

Thanks, all, for your help!
Cathy


CATHARINE PENFOLD NAVARRO, PhD

Part-Time Instructor, MA Leadership | TWU GLOBAL

Trinity Western University | e. ***@***.******@***.***>



twu.ca<http://www.twu.ca/>



***@***.***

________________________________

**Comment by MeeksonHundoo** [comment]
Hello @cpenfoldnavarro Thanks for making the edits to the course schedule tab and it is indeed visible. I have deleted the old one.

**Comment by cpenfoldnavarro** [comment]
Can you make the other sections editable in moodle as well? For example, in the "Assessment" tab in the "Overview" there are some policies that don't match my syllabus. I would like to be able to edit this content.


CATHARINE PENFOLD NAVARRO, PhD

Part-Time Instructor, MA Leadership | TWU GLOBAL

Trinity Western University | e. ***@***.******@***.***>



twu.ca<http://www.twu.ca/>



***@***.***

________________________________

**Comment by kmarjanovic** [comment]
Hi Cathy!

I added a simple assessment chart in Moodle and deleted the syllabus info.
Please have a look - and feel free to modify in Moodle.
https://learn.twu.ca/course/view.php?id=25409&section=5

**Comment by kmarjanovic** [comment]
@cpenfoldnavarro please let us know if you need anything else, or if we can close this issue.
Hope your course started well!

**Comment by cpenfoldnavarro** [comment]
Thanks for all your help! Yes, you can consider this closed.


CATHARINE PENFOLD NAVARRO, PhD

Part-Time Instructor, MA Leadership | TWU GLOBAL

Trinity Western University | e. ***@***.******@***.***>



twu.ca<http://www.twu.ca/>



***@***.***

________________________________
