### ISSUE TITLE
Production FNDN 102 Facilitators Guide

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#621]
### Course
FNDN 102 Master
### URL
https://learn.twu.ca/course/view.php?id=25352&section=18#tabs-tree-start

### Instructions
Please add the following guide
[Facilitator Guide FNDN 102 GX.docx](https://github.com/TWUOnline/bug-tracking/files/9509275/Facilitator.Guide.FNDN.102.GX.docx)

**Comment by MeeksonHundoo** [comment]
Hello @kmarjanovic the facilitators guide has been added. Here is the link:
https://animated-sniffle-c26f9054.pages.github.io/
Please, let me know if any edits are needed.

**Comment by kmarjanovic** [comment]
Hi @MeeksonHundoo 

Please do not add course guides to Bookdown repositories.  Students can then access answer keys.

Instead, please add them to the Moodle site - in a Instructors or Facilitator's Guide tab - and please make sure it is hidden from students.

I've added the doc to the [Facilitator's Guide](https://learn.twu.ca/course/view.php?id=25374&section=17#tabs-tree-start)

I also deleted the guide from the book: https://animated-sniffle-c26f9054.pages.github.io/letter-to-the-facilitator.html
