### ISSUE TITLE
SOCI 411 OL FA22

### ISSUE THREAD

**Issue by dhanenburg** [TWUOnline/bug-tracking#622]
**Which course contains the bug?**  
SOCI 411 OL FA22
 
 
**Describe the error and/or your suggestion**  
I teach 3 human service practicum courses and I use the same master for all 3. I would like to change the master at the top of the "General" tab to say "Welcome to Human Services Practicum" and delete the number. When the number is changed, it changes it for all 3 courses. I am not finding the master course but if this change could be made to SOCI 320 OL, SOCI 411 OL and SOCI 420 OL that would cover it. 
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=25267&section=0 
2. Unit # General Tab - heading        Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @dhanenburg I made the said amendments to SOCI 320 OL and SOCI 411 OL. However, could you please provide me with the link to your SOCI 420 OL course as I could not find the Fall version of this course.

**Comment by dhanenburg** [comment]
Thank you so much! This is the only SOCI 420 course I have at this point and it looks like the change applied here - https://learn.twu.ca/course/view.php?id=23311&section=0#tabs-tree-start

Can you tell me if all 3 of these courses are linked? If I make a change in one, will it change all 3? If so, I don’t want that to be the case.

Thanks,
Debra

**Comment by MeeksonHundoo** [comment]
Hello @dhanenburg soci411practicum is the master course. The change that I made for SOCI 411 OL - Practicum (FA 2022) made the change in SOCI 420 OL - Practicum (SU 2022) as well.

**Comment by dhanenburg** [comment]
Thanks. If I make a change to one of these three courses, does it change all 3? How are they linked?

Debra

**Comment by MeeksonHundoo** [comment]
Hello @dhanenburg Course SOCI 411 OL & SOCI 420 OL have their master repository as : soci411practicum. The master repository for SOCI 320 OL is soci320adc. These sub courses showcase the same content as the master courses, so any changes made to the content of the master course changes the content in its subsequent courses. 

Hello @kmarjanovic could you also please share your knowledge on this with @dhanenburg

**Comment by kmarjanovic** [comment]
Hi Debra!
Good call on making a more general title.  The nice thing is, the Moodle Shells will still have the course numbers (402, 411, etc.) but the GitHub content (the part our team edits), can have info related to all sections.

Does that make sense?  Please let us know if there are any other changes, or if we can close this issue.
Thanks,
Kelly
