### ISSUE TITLE
Production LDRS 301 ADC to Bookdown

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#623]
### Course
LDRS 301 - Lifelong Learning in Leadership (new ADC MASTER)
### URL
https://learn.twu.ca/course/view.php?id=15711&section=0#tabs-tree-start

### Instructions
Please convert FAR Master to Bookdown.

Edits coming from DeAnn, but will be minor revisions.
Course starts Oct 17 with Cynthia McCarthy.

**Comment by kmarjanovic** [comment]
@MeeksonHundoo please see the attached and make the changes to the FAR Master - before it's converted to a Bookdown course.  
[LDRS 301 FAR Master Updates - Sep 12 2022.docx](https://github.com/TWUOnline/bug-tracking/files/9569407/LDRS.301.FAR.Master.Updates.-.Sep.12.2022.docx)

@deannadams let us know if there are any other changes.
Thanks all!

**Comment by deannadams** [comment]
Thank you!!

Meekson – let me know if you have any questions at all. Can you let me know once it’s done?

Thanks so much!
DeAnn


DeAnn Adams

Director, Faculty Services and Development
TWU GLOBAL

**Comment by deannadams** [comment]
Hi Meekson - just checking in on the changes to the FAR Master. I think you have the document with the changes, correct?. Course starts Oct 17. Ideally we would have the course visible for students in Moodle by Oct 7. Let me know if you have any questions.

**Comment by kmarjanovic** [comment]
@MeeksonHundoo we're holding off on converting to bookdown until we have the capacity.

For now - please make all these changes to the FAR Master in Git/Grav
https://learn.twu.ca/course/view.php?id=15711&section=0

**Comment by MeeksonHundoo** [comment]
> t checking in on the changes to the FAR Mast

Hello @deannadams Apologies for not being able to get to this LDRS 301 adc earlier as I was caught up with doing the FNDN 102, my classes, assignments and my other job as well. Will start working on the editing soon and will inform you as quickly as I get done with it.

**Comment by MeeksonHundoo** [comment]
> @MeeksonHundoo we're holding off on converting to bookdown until we have the capacity.
> 
> For now - please make all these changes to the FAR Master in Git/Grav https://learn.twu.ca/course/view.php?id=15711&section=0

Hello @kmarjanovic Thanks for clarifying this, as the bug report says that we were supposed to convert it to bookdown. I'll start working on editing this course contents soon.

**Comment by deannadams** [comment]
@kmarjanovic  - Mark has confirmed that we will add the Birkman topic into the FAR Master for LDRS 301.

@MeeksonHundoo In addition to the changes to the FAR Master you already have, there will be one additional change. That is... we are **adding an additional topic to Unit 3**. I don't have the content done yet, but it will become Unit 3, new Topic 3. This means that the current Topic 3 (Feedback) will become Topic 4. And the current Topic 4 (Leading Self) will become Topic 5. 

To recap, the Unit 3 topics will be:
Topic 1 - Self-awareness as a component of emotional intelligence (no changes)
Topic 2 - Blind Spots (no changes)
Topic 3 - **NEW** Using Birkman to understand self (create placeholder for now... content and learning activities to come)
Topic 4 - Feedback 
Topic 5 - Leading Self

The learning activities will all need to be renumbered within topics 4 and 5, and also in the Unit 3 overview page... but we can't really do this until we know how many learning activities we will have for the new Topic 3.

Perhaps you can work on all the other changes, and leave unit 3 for now... until I have the new content ready.
Thanks +++

**Comment by deannadams** [comment]
> 

Not a problem, Meekson... I know how busy everyone is. 🙂

**Comment by MeeksonHundoo** [comment]
Hello @deannadams These changes have been made. Please let me know if anymore edits are needed.

**Comment by deannadams** [comment]
[LDRS 301 Corrections - Oct 4, 2022.docx](https://github.com/TWUOnline/bug-tracking/files/9710565/LDRS.301.Corrections.-.Oct.4.2022.docx)

Hi @MeeksonHundoo  - I'm waiting on Mark's approval for the new Unit 3, Topic 3 content (Using Birkman to Understand Self). In the meantime, there are a few fixes from the last round of changes. Please see attached. Would you mind fixing these up this week? Please let me know if there are any problems with the attachment.

**Comment by MeeksonHundoo** [comment]
Hello @deannadams these changes have been incorporated

**Comment by deannadams** [comment]
Perfect - thanks @MeeksonHundoo. Looks great. If it's not too much trouble (and to be consistent with other units), the sentence under Activity Checklist for unit 4, 5, 6 doesn't need to be bulleted ("Here is a checklist of learning activities you will benefit from in completing this unit. You may find it useful for planning your work."). It would be great to remove the bullet.

I'll be in touch as soon as I hear from Mark about the content for the new Birkman topic for Unit 3.

Almost there with this course. 😀

**Comment by MeeksonHundoo** [comment]
Hello @deannadams yeah.. you're right. I didn't notice that. Good catch! and it's no trouble at all. Also, Just let me know whenever Unit 3 is ready and I'll have it uploaded.

**Comment by deannadams** [comment]
Perfect - thanks @MeeksonHundoo - looks great!

**Comment by MeeksonHundoo** [comment]
Hello @deannadams thanks for letting me know about it. I will start working on this today and let you know once it's done.

**Comment by MeeksonHundoo** [comment]
> Hello @deannadams thanks for letting me know about it. I will start working on this today and let you know once it's done.

Hello @deannadams I've just finished putting Topic 3 and made the edits as guided on the word docs. Could you please take a look and advice if everything is okay? Here is the link : https://learn.twu.ca/course/view.php?id=15711&section=5#tabs-tree-start

**Comment by deannadams** [comment]
Hi @MeeksonHundoo - great job!! Just a couple of things...

1. You missed adding the new learning outcome in the Unit 3 overview - See Unit 3 Overview Screenshot (please add "Understand your Birkman map" in between the last 2 bullet points (indicated by the red arrow)
2. Just a copy and paste error in the new Birkman content. You've repeated "Start with Why? The Birkman Mindset" heading twice. Please change the second one to "The Birkman Behaviours and Motivations". See Birkman Topic Screenshot for guidance on where this goes.
3. The final learning activity in Unit 3, Topic 5 is missing now. There should be a 3.7: Self Leadership Video and Reflections after Activity 3.6 (Radical Candor video). See Unit 3 Overview - Activity 3.7 Screenshot for the piece that's missing in Topic 5. Really hoping this is retrievable. If not, let me know and I will dig out the original text.

Thanks again, for all your work on this!! 
![Unit 3 Overview Screenshot](https://user-images.githubusercontent.com/64105579/200919546-4afadd35-363e-4e5b-a486-eaf349dada69.JPG)
![Birkman Topic Screenshot](https://user-images.githubusercontent.com/64105579/200919568-171e1b8b-e9f0-47c5-be03-f8b8a3c05efb.JPG)
![Unit 3 Overview - Activity 3 7 Screenshot](https://user-images.githubusercontent.com/64105579/200919589-aaf63bac-a87c-4b4f-a524-0a0938054885.JPG)

**Comment by deannadams** [comment]
Hi @MeeksonHundoo - great work! We are almost there.

Now we are missing Learning Activity 3.6 (Unit 3, Topic 5). I see you've added Activity 3.7 Self Leadership Video and Reflections (thank you!), but now Learning Activity 3.6 Giving and Receiving Feedback (radical candor video). There should be 2 learning activities for Topic 5 (3.6 + 3.7). Can you please add the 3.6 activity back just before Activity 3.7?

Once this is done, I think we are set! 

![Unit 3, Topic 5 Learning Activities Screenshot](https://user-images.githubusercontent.com/64105579/202562024-82f79ab6-d4ca-4ce0-adfd-efa498a1de7a.JPG)

**Comment by MeeksonHundoo** [comment]
Hello @deannadams sorry about that. I forgot to write the plugin code for learning activity 3.6. Its there now. Here is the link:
https://learn.twu.ca/course/view.php?id=15711&section=5

**Comment by deannadams** [comment]
Hi @MeeksonHundoo - you make it all sound so simple!! 🙂
Thanks so much. I think we have it all totally completed now!!
Thanks for all your help with this one!
DeAnn

**Comment by MeeksonHundoo** [comment]
Hello @deannadams it indeed is very simple. Thanks for all your patience and understanding. I'll close this issue now. If there is anything, please feel free to reach out to us.

**Comment by deannadams** [comment]
Perfect - thanks for everything!
