### ISSUE TITLE
Production SKLS 500 Media

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#625]
### Course
SKLS 500: Graduate Scholarly Communication (MASTER)

### URL
https://learning-commons.github.io/skls500/essay-structure.html#learning-activity-3.2-watch-and-take-notes
### Instructions
Please add the attached graphic before activity 3.2 (and take out repeat info in the activity.
![U3_Thesis-statement](https://user-images.githubusercontent.com/35148983/189996576-c430625e-2e41-4fca-90ed-1ddf3932905b.jpg)

**Comment by cmadland** [comment]
@kmarjanovic I would recommend we keep the text in the activity as it is and not add the graphic as we would have to then also describe the graphic with text for accessibility.

**Comment by cmadland** [comment]
per our discussion in the design mtg today, I 'll add the image
