### ISSUE TITLE
LDRS 627 units missing

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#626]
**Which course contains the bug?**  
[LDRS 627 OL - Theory & Practice of Adult Educ. (FA 2022)](https://learn.twu.ca/course/view.php?id=25421&section=0#tabs-tree-start) 
 
**Describe the error and/or your suggestion**  
Email:
For the last two days units 9 and 10 of LDRS 627 OL - Theory & Practice of Adult Educ. (SU 2022) has been down on Moodle. When I try to open it, it shows error message. Please kindly help. Learners need access to these units asap. Thank you.
Kindly,
Emebet Mojo, MA 
 
 
**Location of the bug**  

My guess is that what was imported into 627 was the revised 8 week version - but I need to track this down.

There is a 627-old - but we need to compare what was revised.  In the future - these should be relabled for what was changed (e.g. 627-8wk)

Here is the current embed code:
<p><iframe scrolling="yes" style="border: 0px #ffffff none;" src="https://far.twu.ca/ldrs/627/u1/overview/chromeless:true/hidepagetitle:true" allowfullscreen="allowfullscreen" width="100%" height="1000"></iframe></p>

**Comment by kmarjanovic** [comment]
tagging @emebetM - as I can't see her username in Assignees...

**Comment by emebetM** [comment]
> tagging @emebetM - as I can't see her username in Assignees...

Thanks Kelly!

**Comment by kmarjanovic** [comment]
@emebetM @cmadland 
I've compared the different versions of the course.  Here's a [google doc](https://docs.google.com/document/d/1HBQ-A5UBLiCJOHghbahvVlOAxTdRPpbM7AI5Xu18C8w/edit#) comparing the 10 week version and the 8 week version.

@emebetM could you confirm the dates of your fall course?  If you need extra topics to teach, see the green highlights.

Please let us know what you and the instructor need (Jim Parsons?)

**Comment by emebetM** [comment]
Dear Kelly, 
There are two more discussion posts learners need to complete for units 9 and 10.  The course ends on 19/20 of Sept.

**Comment by kmarjanovic** [comment]
Hi @emebetM - so they are done on Tuesday?  I would suggest you and Jim come up with two more posts (if needed) that address the course learning outcomes.  In the 8 week course students have just taken, they should have gotten all the content that was required.
Please let me know if you need help with this.

**Comment by emebetM** [comment]
@kmarjanovic , we can do that. Thank you for the suggestion.
