### ISSUE TITLE
PHIL 100 GX Fall 22

### ISSUE THREAD

**Issue by SimoneVanDerMerwe** [TWUOnline/bug-tracking#627]
PHIL 100 GX - Philosophy for Life (FA 2022)

I accidentally added 3 tabs (Topic 1, Topic 2, and Topic 16). I do not need those tabs, and I couldn't find a way to delete them.

URL: https://learn.twu.ca/course/view.php?id=25401&section=0#tabs-tree-start
 
![Moodle](https://user-images.githubusercontent.com/98186755/191639945-dd2e9554-67cb-43fc-9102-2525c3b9c51c.jpg)

**Comment by MeeksonHundoo** [comment]
Hello @SimoneVanDerMerwe these tabs have been deleted.

**Comment by SimoneVanDerMerwe** [comment]
@MeeksonHundoo Thank you so much!!!!!!

Blessings,

Simone
