### ISSUE TITLE
Discussion Instructions are inconsistent (listed in different ways in various areas of the course)

### ISSUE THREAD

**Issue by cpenfoldnavarro** [TWUOnline/bug-tracking#628]
**Which course contains the bug?**  
LDRS 591 OL FA 2022
 
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.

The discussion instructions are inconsistent -- the discussion instructions for each unit in the "course book" differ from what is in the drop down menu on this page. 

Please add this note:
For discussion instructions, please refer to the unit in the "course book." You can also see discussion instructions in the unit discussion forum at the bottom of this page.
 
Please hide the following (including the drop down menu).

Specific instructions for each week are provided below. Please click on the link for each week to view the instructions.

Unit 1 Discussion Post
Unit 2 Discussion Post
Unit 3 Discussion Post
Unit 8 Discussion Post
Unit 10 Discussion Post

**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=25409&section=6
2. Unit #         Topic #         Activity#  
 
Assignment Tab
Participation/Discussion Posts tab

**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
@MeeksonHundoo just checking up on this issue.  Could you please make those changes?

**Comment by MeeksonHundoo** [comment]
Hello @kmarjanovic Apologies for this. So many bug requests in the last few days. Difficult to keep track of them all.
Hello @cpenfoldnavarro could you please provide me with the link for this course.

**Comment by kmarjanovic** [comment]
@MeeksonHundoo just checking on this issue again.
The link is in the request above: https://learn.twu.ca/course/view.php?id=25409&section=6
Note it is embedded from this git/grav content:
far.twu.ca/ldrs/591/assignments/posts-reflections/10w-ol

**Comment by MeeksonHundoo** [comment]
Hello @kmarjanovic this has been updated now. Sorry have become blind off lately...!!

**Comment by kmarjanovic** [comment]
Thanks so much @MeeksonHundoo !  I know these are busy times!!

@cpenfoldnavarro I'll close this issue, but please let us know if there's anything else you need for this course.

**Comment by cpenfoldnavarro** [comment]
Thanks.

I'm teaching LDRS 591 again in January. Will the new course be formatted in a way that it is more easily editable for the current instructor teaching the course? I know there was some discussion earlier about taking it out github so I could make changes in the current version (not the master).

Also, the current version in my dashboard is just a blank course. When will that be updated? I believe they now want us to have course content available one month before launch date -- presumably more to take the holidays into account?

Thanks for your help!
Cathy


CATHARINE PENFOLD NAVARRO, PhD

Part-Time Instructor, MA Leadership | TWU GLOBAL

Trinity Western University | e. ***@***.******@***.***>



twu.ca<http://www.twu.ca/>



***@***.***

________________________________

**Comment by kmarjanovic** [comment]
Hi @cpenfoldnavarro !
There is a way to take the course book and put the content directly in Moodle so you can edit it - but our department doesn't have the capacity to work on this until the spring (@cmadland please correct me if I'm wrong!;)

If your January course is still blank, I believe the procedure is for instructors to import.  Here are the [instructions](https://trinitywestern.teamdynamix.com/TDClient/1904/Portal/KB/ArticleDet?ID=45140) - but please let us know if you run into any difficulties.

btw - let's set up a meeting to chat!! :)
