### ISSUE TITLE
Adding a Resource

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#629]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 SOCI 400, ADC MASTER 
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 Under the Required Texts and Materials I would like to add another resource: 
Richardson, R. W. (2011). _Family ties that bind: A self-help guide to change through family of origin therapy_. Self-Counsel Press. 4th ed. 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=20745
2. Unit #  Course Overview       Topic #         Activity#  
3rd Heading down. 
 
**Optional: Screenshots**  
![Screen Shot 2022-09-23 at 4 49 56 PM](https://user-images.githubusercontent.com/114267346/192070392-2f01987e-f02f-4ec2-9785-00bdbe81b45c.png)

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse this has been updated
