### ISSUE TITLE
Missing PPT 1.3 for LDRS 300 IF Unit 1 Topic 3

### ISSUE THREAD

**Issue by BLMSasaki** [TWUOnline/bug-tracking#63]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 LDRS 300 IF FAR Centre
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 
 Missing PPT 1.3 Jesus and Servant Leadership for Unit 1, Topic 3

**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  
2. Unit #         Topic #         Activity#  
 
**Optional: Screenshots**  
https://learn.twu.ca/course/view.php?id=10796&section=1

**Comment by kmarjanovic** [comment]
I've added.  @cmadland not sure if you're going to replace with Presentation plugin. (or for next round)
