### ISSUE TITLE
Changing a section

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#630]
**Which course contains the bug?**  
- SOCI 400 Critical Issues in Human Services ADC Master
 
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 In Activity 1.7, I would like the PDF, Family Ties that Bind be removed as well as the description right underneath that talks about not reading the whole book. The students will now be required to read the whole book. The students will have bought this book as a required text. 
The description will now say: 

I invite you to read the following book, _Family Ties that Bind_ by Dr.Ronald W. Richardson. This text will help you in the creation of your genograms as it highlights some general family patterns and unspoken rules which will ideally help you noticing these in your own. The book is only 137 pages and is light reading. If you can't find the time to read the whole book, I would recommend looking in the Table of Contents and reading the chapters that you feel would most help you understand your family. I will be looking for some of the terminology that is used in this book in your family genograms assignment. 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=20745&section=2
2. Unit # 1        Topic # 2        Activity#  1.7 (just the first part of the activity) 
 
**Optional: Screenshots**  
![Screen Shot 2022-09-23 at 8 15 46 PM](https://user-images.githubusercontent.com/114267346/192077786-12b03ab8-90a6-487b-af7c-9d9cacdd86f4.png)

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse this has been updated
