### ISSUE TITLE
Replacing an entire page. 

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#631]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 SOCI 400 ADC Master 
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
This page was not like this before, however the overview section of unit 2 (not the rest of the topics), has been replaced with a page from SOCI 221, unit 4. This is what the overview page of unit 2 is supposed to have: 

Unit 2:  Professional Ethics Overview/Intro

Overview
In this second unit, we will examine some of the common themes and main components of ethics and what is required of you when working in this field. There is a difference between your ethical obligation and your legal obligation to your clients and it is important to understand the difference before entering into this profession. 
Ethics can be complicated-there is not a black and white answer for everything. We have to be able to sit in the grey and learn how to approach these dilemmas with a framework, not a step by step list. As the textbook will explore, this can both be scary and empowering. Since it is necessary to hang out in the grey, it is so important to take with us the pieces of self awareness that we started working on in the last unit (and to keep working on them). 

Topics
This unit is divided into the following topics:
An Overview of Ethics 
Steps to resolve an Ethical Dilemma
Client Rights vs. Counsellor Responsibilities

Learning Outcomes
When you have completed this unit, you should be able to:
Demonstrate a knowledge of basic ethical terms
Explain Kitchner’s 6 basic moral principles
Determine the steps necessary resolve an ethical dilemma
Compare and contrast client rights vs. counselor responsibilities
Demonstrate knowledge of informed consent

Activity Checklist
Here is a checklist of learning activities you will benefit from in completing this unit. You may find it useful for planning your work. 
Activity 2.1: Read Chapter 1 (p. 2-18)
Activity 2.2: Case Study
Activity 2.3: Case Study
Activity 2.4: Read Chapter 1 (p. 19-23)
Activity 2.5: Case Study https://www.youtube.com/watch?v=DbjUWSpE7nI  
Activity 2.6: Complete the Self-Inventory
Activity 2.7: Read Chapter 5
Activity 2.8: Watch an example of Informed Consent
Activity 2.9: Examine our Code of Ethics
Activity 2.10: Key Terms Quiz

Assessment
Start on your Class Presentations
Forum Discussion Participation

Resources
Here are the resources you will need to complete this unit.
[Textbook] Corey, G., Corey, M.S., & Corey, C. (2019). Issues & ethics in the helping professions. Boston, MA: Cengage. 
BCACC Code of Ethics: https://bc-counsellors.org/wp-content/uploads/2015/09/BCACC-Code-of-Ethical-Conduct-2014.pdf 
CAMFT Code of Ethics: https://camft.ca/resources/Documents/CAMFT%20-%20ACTCF%20Code%20of%20Ethics%20Feb%202019%20%20for%20Website%20pdf.pdf 
https://www.youtube.com/watch?v=DbjUWSpE7nI  (case study)
https://www.youtube.com/watch?v=QBZoWjn-XMs  (informed consent description)

 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=20745&section=3#tabs-tree-start 
2. Unit # 2        Topic #   Overview      Activity#  the whole page
![Screen Shot 2022-09-23 at 8 27 32 PM](https://user-images.githubusercontent.com/114267346/192078199-974711fe-1812-4574-b388-5a025e7b688a.png)

 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
@MeeksonHundoo @cmadland just checking on the status of the Unit 2 changes?  If you need the word doc, you can refer to this issue: https://github.com/TWUOnline/bug-tracking/issues/477

@emilyverse - is this course currently running?  Please let us know the start date.
Thanks!

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse & @kmarjanovic these changes have been incorporated.

**Comment by kmarjanovic** [comment]
Thanks @MeeksonHundoo !

Could you take out the resources section that's in between the Activity checklist?  The resources after the checklist should stay.
delete:
Resources
Here are the resources you will need to complete this unit.

White, J.M., Martin, T.F. and Bartolic, S. K.  (2012). Families Across the Life Course.  Toronto: Pearson Education 

[Hiebert, D. (2013). Sweet Surrender. Eugene, OR: Cascade Books.](https://www.amazon.ca/Sweet-Surrender-Cultural-Mandates-Christian-ebook/dp/B00EADBH28/ref=tmm_kin_swatch_0?_encoding=UTF8&qid=&sr=)

**Comment by emilyverse** [comment]
> @MeeksonHundoo @cmadland just checking on the status of the Unit 2 changes? If you need the word doc, you can refer to this issue: #477
> 
> @emilyverse - is this course currently running? Please let us know the start date. Thanks!

It will start on October 18th. 
Thanks!

**Comment by MeeksonHundoo** [comment]
> 1. https://learn.twu.ca/course/view.php?id=20745&section=3#tabs-tree-start

Hello @kmarjanovic removed those extra resources

**Comment by kmarjanovic** [comment]
Thanks @MeeksonHundoo!

@emilyverse I'll close this issue, but let us know if you need anything else!
