### ISSUE TITLE
Paper Templates are Missing in LDRS 591

### ISSUE THREAD

**Issue by cpenfoldnavarro** [TWUOnline/bug-tracking#633]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 LDRS 591 OL FA 2022
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.

There are links to templates for each of the assignments. However, these links are not active. Please link to the paper templates (attached below).
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1.Assignment #1 https://learn.twu.ca/course/view.php?id=25409&section=7#tabs-tree-start
2. Assignment #2 https://learn.twu.ca/course/view.php?id=25409&section=8#tabs-tree-start
3. Assignment #3 https://learn.twu.ca/course/view.php?id=25409&section=9#tabs-tree-start
4. Assignment #4 https://learn.twu.ca/course/view.php?id=25409&section=10#tabs-tree-start
5. Assignment #5 https://learn.twu.ca/course/view.php?id=25409&section=11#tabs-tree-start

The templates should be located at the bottom of the page where this text is found.

See the Sample Template located at the bottom of this page if you need help understanding how this assignment will be structured.

 
**Optional: Screenshots**  

[TEMPLATE Assignment #1 (Clarifying Your Research Interest) (SCE) (1).docx](https://github.com/TWUOnline/bug-tracking/files/9648529/TEMPLATE.Assignment.1.Clarifying.Your.Research.Interest.SCE.1.docx)

[TEMPLATE Assignment #2 (Literature Search Template), (SCE) (1).docx](https://github.com/TWUOnline/bug-tracking/files/9648531/TEMPLATE.Assignment.2.Literature.Search.Template.SCE.1.docx)

[TEMPLATE Assignment #3 (Evaluate Sections of a Research Study).docx](https://github.com/TWUOnline/bug-tracking/files/9648533/TEMPLATE.Assignment.3.Evaluate.Sections.of.a.Research.Study.docx)

[TEMPLATE Assignment #4 (Article Review Template).docx](https://github.com/TWUOnline/bug-tracking/files/9648538/TEMPLATE.Assignment.4.Article.Review.Template.docx)

[TEMPLATE Assignment #5 (Literature Review Template) (1).docx](https://github.com/TWUOnline/bug-tracking/files/9648540/TEMPLATE.Assignment.5.Literature.Review.Template.1.docx)

**Comment by kmarjanovic** [comment]
Hi @cpenfoldnavarro !

I see the templates in the FAR Master version of LDRS 591.  Was that the version your course was imported from?

I've enrolled you in that course as manager in case you need anything else.
https://learn.twu.ca/course/view.php?id=8924&section=15#tabs-tree-start

Are you able to upload documents in Moodle?  Please let us know if you need help with this, as these are things the instructor typically does in course delivery (different from our course development projects).

**Comment by MeeksonHundoo** [comment]
Hello @cpenfoldnavarro I have added the necessary templates under their designated assignment tabs.

**Comment by cpenfoldnavarro** [comment]
Thanks so much!


CATHARINE PENFOLD NAVARRO, PhD

Part-Time Instructor, MA Leadership | TWU GLOBAL

Trinity Western University | e. ***@***.******@***.***>



twu.ca<http://www.twu.ca/>



***@***.***

________________________________
