### ISSUE TITLE
PHIL 210 GX - Contemporary Ethical Issues (FA 2022)

### ISSUE THREAD

**Issue by SimoneVanDerMerwe** [TWUOnline/bug-tracking#634]
PHIL 210 GX - Contemporary Ethical Issues (FA 2022)

I added 2 tabs in the wrong place: "Topic 2" and "Topic 3". Could you please delete them for me?
 
https://learn.twu.ca/course/view.php?id=25042&section=0#tabs-tree-start

 
![Screenshot](https://user-images.githubusercontent.com/98186755/193186978-c9b2e897-3334-4dd1-ba19-c210cc1c39a6.jpg)

Thank you very much!!

Simone

**Comment by MeeksonHundoo** [comment]
Hello @SimoneVanDerMerwe done

**Comment by SimoneVanDerMerwe** [comment]
Thank you so much, @MeeksonHundoo!
