### ISSUE TITLE
PHIL 210 GX FALL 2022 

### ISSUE THREAD

**Issue by SimoneVanDerMerwe** [TWUOnline/bug-tracking#636]
PHIL 210 GX FALL 2022
 
 In Unit 2 > Assessment tab > Reflective Journal (Green Box) >Fifth line > please change 250-400 to 250-300.
 https://learn.twu.ca/course/view.php?id=25042&section=2#tabs-tree-start
 
Made this change in Atom, but it did not change in Moodle.

Thanks a lot!

**Comment by MeeksonHundoo** [comment]
Hello @SimoneVanDerMerwe The change has been already been incorporated.

![image](https://user-images.githubusercontent.com/98780625/194687347-c6688f8f-da28-4fec-8f30-9b423693b10f.png)

**Comment by SimoneVanDerMerwe** [comment]
@MeeksonHundoo Thank you so much!
