### ISSUE TITLE
Edit UNIV 301 

### ISSUE THREAD

**Issue by dhanenburg** [TWUOnline/bug-tracking#637]
**Which course contains the bug?**  - UNIV 301 OL (Master Course and FALL 2022 as I already imported the Master)
- Course Code, section, and term (e.g. LDRS 591 OL SP2019) - ADC Master and FALL 2022
 
 
**Describe the error and/or your suggestion**  - Under Unit 1, Topic 1, Activity 1.1 - please replace that whole section (including deleting the PDF) with the following - 

Activity 1.1: Title Introductions, Orientation, Syllabus Requirements

It’s important that you get a big picture perspective of the ADC program, this course and of psychology and human services. This will help guide you as you delve into each specific course and topic through the program: to know how it all connects and where you can go for resources and support.  

Please attend the live zoom class the first night or **watch the recorded class** under the "Course Connections" tab. This will provide an  orientation to TWU’s Degree Completion Program in Psychology and Human Services.

A clear and concise description of what the error or suggestion is.
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=17766&section=3#tabs-tree-start and https://learn.twu.ca/course/view.php?id=25313&section=3#tabs-tree-start
2. Unit # 1        Topic # 1        Activity# 1.1 
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @dhanenburg These changes have been made.

**Comment by dhanenburg** [comment]
Thank you so much!! This looks great.
