### ISSUE TITLE
LDRS 631 broken link

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#638]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
[LDRS 631](https://learn.twu.ca/course/view.php?id=18003&section=17#tabs-tree-start)
 

**Location of the bug**  
APA Checklist in Assessment section - bottom of page
Source: Information provided on this page has been adapted from [APA Style Errors Checklist](https://ocls.indwes.edu/APA/APAStyleChecklist.pdf).

change to link
https://ocls.indwes.edu//ld.php?content_id=60432032

Need to confirm with instructor (@cmadland @MaraChequer do you know who teaches this course?)
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
Same broken link in 634.  please fix:
https://learn.twu.ca/course/view.php?id=18002&section=17#tabs-tree-start

**Comment by MeeksonHundoo** [comment]
Hello @kmarjanovic the links have been updated in both LDRS 631 & 634 courses

**Comment by MeeksonHundoo** [comment]
Hello @kmarjanovic LDRS 631 is taught by Elizabeth Rackow

**Comment by kmarjanovic** [comment]
Thanks Meekson!!
