### ISSUE TITLE
Google docs in 591, 697 and 698, 631 and 634

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#639]
**Which course contains the bug?**  
LDRS 591, 697 and 698, 631 and 634
 
**Describe the error and/or your suggestion**  
There are links to Heather's personal google drive account in 591, 697 and 698, 631 and 634.  We need to copy the templates and add as a word doc - or @cmadland is there an online learning google account our team can manage?

Heather shared the templates with the course instructors via word documents, so the students should have access in the meantime.  

**Location of the bug**  
I'd suggest searching the directory in Atom for google to find the docs, as they're difficult to search for in Moodle.

**Comment by cmadland** [comment]
Can anyone add the Werd docs here?
@kmarjanovic 

do they need to be werd docs that we share, or can we create some pages in bookdown? I know Sergio had this issue a couple days ago.

**Comment by kmarjanovic** [comment]
@cmadland we have to search through the courses to find the google docs.  Could Meekson do this?

**Comment by kmarjanovic** [comment]
Adding Barish as I think it relates to Sergio's requests?
@barishgolland

**Comment by kmarjanovic** [comment]
I've searched through most of the courses for google docs. There are lots of versions of these courses!!!

@MaraChequer for 634 - do you have a copy of the [Team Charter Template](https://docs.google.com/document/d/1xBimyTQcHkuUELJ15Suj8P5uvZfcwQlPY0wN4wfyGso/edit?usp=sharing).  I see the note in the Facilitator's guide - unit 4 notes, so it's in Unit 4 somewhere as well.  

Most other google docs seem to be in the Files section in the course folder.  It's a little difficult to locate though.  When I go to the unit online, I see different content.

@cmadland please confirm if changes have been made and we can close this issue!

**Comment by cmadland** [comment]
## LDRS 697 Files
[A4 Critical Question Presentation.pdf](https://github.com/TWUOnline/bug-tracking/files/10429749/A4.Critical.Question.Presentation.pdf)

[A3 Preliminary Assessment Reflection Paper Exemplar.docx](https://github.com/TWUOnline/bug-tracking/files/10429753/A3.Preliminary.Assessment.Reflection.Paper.Exemplar.docx)


## LDRS698 Files
[Final Action Research Report Template.docx](https://github.com/TWUOnline/bug-tracking/files/10429738/Final.Action.Research.Report.Template.docx)

**Comment by kmarjanovic** [comment]
Closing.  Cathy will review this course so we'll see if these docs are needed.
