### ISSUE TITLE
LDRS 300 IF Unit 2 Topic 3 PPT problem

### ISSUE THREAD

**Issue by BLMSasaki** [TWUOnline/bug-tracking#64]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 
 LDRS 300IF Unit 2 Topic 3 PPT 2.3
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 
 PPT 2.3 The Mandela video embedded in the power point is not functioning. It cannot be clicked open to watch.

**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  
2. Unit #         Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
@BLMSasaki 
I don't see the Mandela video in that PowerPoint.  Could you send the video link?  We can add it to the activity.

**Comment by BLMSasaki** [comment]
https://www.youtube.com/watch?v=wX85KLMOnQg




Brenda-Lee Sasaki, MA, CLC, ACC

Adjunct Professor | TWU Richmond

Academic Facilitation Specialist / TWU GLOBAL

Trinity Western University | t. 604.513.2193 | c. 604.785.4126 | e. Brenda-lee.Sasaki@twu.ca


twu.ca<http://www.twu.ca/>



[cid:image003.png@01D567BE.8201A250]<https://www.facebook.com/trinitywestern/>  [cid:image004.png@01D567BE.8201A250] <https://www.instagram.com/trinitywestern/>   [cid:image005.png@01D567BE.8201A250] <https://twitter.com/TrinityWestern>   [cid:image006.png@01D567BE.8201A250] <https://www.youtube.com/user/TrinityWesternU>   [cid:image007.png@01D567BE.8201A250] <https://www.linkedin.com/school/trinity-western-university/>



[cid:image001.png@01D5649E.C2C49090]


Trinity Western University is located on the traditional, ancestral, and unceded territory of the Sto:lo people.
________________________________

**Comment by kmarjanovic** [comment]
Thanks Brenda!  It's added now.
@BLMSasaki
