### ISSUE TITLE
LDRS 697 missing docs

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#643]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 LDRS 697 Master - and [FA 2022](https://learn.twu.ca/course/view.php?id=25427&section=11#tabs-tree-start)

**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.

For [Unit 6 Topic 2](https://far.twu.ca/ldrs/697new/u6/topic-2/chromeless:true/hidepagetitle:true), Learning Activity 2: Create your questions and/or script.

Please add the word documents from the LDRS 697 Master (see [Templates and Resources section](https://learn.twu.ca/course/view.php?id=15767&section=24#tabs-tree-start)) - for the following:

1. Sample Interview/Focus Group Script (with questions)  
2. Sample Quantitative Survey (with instructions)  
3. Sample Qualitative Survey (with instructions)  
4. Sample Mixed-Methods Survey (with instructions)

**Comment by cmadland** [comment]
I will just import that 'Templates and Resources' tab with all the files.

**Comment by kmarjanovic** [comment]
Perfect! Thank you!

**Comment by cmadland** [comment]
hrm...maybe not. I've tried that twice with no success. Investigating...

**Comment by kmarjanovic** [comment]
If there is time...it's better to link to the docs in git though, correct?

There are lots of docs in 591 - word and google - so looking into that now

**Comment by cmadland** [comment]
Ideally, content should be in markdown as a page in bookdown. some files, like forms and such should be linked from their source, like the HREB site. We should move everything out of google.

**Comment by cmadland** [comment]
tried the import in my sample course and it worked just fine...not sure what's up with 697 FA22

**Comment by cmadland** [comment]
found them...they ended up on the Assignment 7 page...3 times. Moodle is dumb.

**Comment by cmadland** [comment]
Ok...finally sorted
