### ISSUE TITLE
images in ldrs 697

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#644]
**Which course contains the bug?**  
ldrs 697 
 https://learn.twu.ca/course/view.php?id=25427&section=19#tabs-tree-start
**Describe the error and/or your suggestion**  
In Assignment 2 - eportfolio - there are 3 images missing.  They seem to be there in git, so I'm not sure what's going on!
line 262
![](Effective Content 3-Circle Venn Diagram.png)

line 282-283
Syed1.jpg
Syed2.jpg

**Comment by cmadland** [comment]
I don't see those images in gh...

**Comment by kmarjanovic** [comment]
![image](https://user-images.githubusercontent.com/35148983/198727308-79a95868-a848-485c-949e-3e6504022f07.png)
in assessment section eportfolio

**Comment by cmadland** [comment]
looks like that is the old 697 folder...they aren't in `697new`...will fix

**Comment by cmadland** [comment]
fix't
