### ISSUE TITLE
LDRS 631 video missing

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#645]
**Which course contains the bug?**  
https://learn.twu.ca/mod/page/view.php?id=557901&forceview=1

3. The LEADS in A Caring Environment Framework
Unit 4

@MaraChequer perhaps you can track this down, or a replacement ( with sme input?)

**Comment by MaraChequer** [comment]
Kelly, I have fixed this bug with a note from Heather. Link was changed and text adjusted according to the video.

**Comment by kmarjanovic** [comment]
Thanks Mara!!
