### ISSUE TITLE
BUSI 111 - Video Time Stamps

### ISSUE THREAD

**Issue by dgaudet48** [TWUOnline/bug-tracking#647]
### Instructions
- [x] @Jeff-TWU as per our conversation, can you take this following sement out of the video so it is a stand-alone clip?:
- [x]  timestamp: (4:23-15:43)
- [ ] 
- [ ]

Please upload required files as attachments.

**Comment by Jeff-TWU** [comment]
Hi @dgaudet48, File is too big to upload here. So instead here is a [Dropbox link](https://www.dropbox.com/s/y67zc6mjvqhav5b/Ch1%20The%20Changing%20Face%20of%20Business_edit.mp4?dl=0).

I can also replace the file on MS stream if you prefer? Let me know.

**Comment by dgaudet48** [comment]
@Jeff-TWU Thanks Jeff - if possible, could you replace the file on MS Stream? Can you make myself and brian.albright@twu.ca owners?

**Comment by Jeff-TWU** [comment]
@dgaudet48 [Done](https://web.microsoftstream.com/video/16cf0042-517c-40de-8444-650e0d421c6d).
