### ISSUE TITLE
ldrs440 Learning Activity 1.3 

### ISSUE THREAD

**Issue by MeeksonHundoo** [TWUOnline/bug-tracking#649]
**What course/project is this request for?**
ldrs440

**Describe the request**
![image](https://user-images.githubusercontent.com/98780625/200941814-4cd0674e-4658-43cd-aee3-21e188e0e4d7.png)

Could we please have this image embedded in the bookdown course in a much better way than it is now?

**Additional context**

**Comment by MaraChequer** [comment]
is this a graphic request? or do you need help embedding the image @MeeksonHundoo?

**Comment by MeeksonHundoo** [comment]
Hello @MaraChequer I think a graphic request, where the students can maybe fill in their own answers.

**Comment by MaraChequer** [comment]
I see, can you send me the course link to take a look? @MeeksonHundoo , It may only be a diagram.

**Comment by MeeksonHundoo** [comment]
Hello @MaraChequer Apologies for replying late. I was in class, here is the bookdown link: https://psychic-giggle-6b21ea8e.pages.github.io/managing-and-performing.html

**Comment by kmarjanovic** [comment]
@MaraChequer  This is an activity where we ask students to write in the chart.  We could make it interactive, but let's put it on hold for now.  @MeeksonHundoo could you clean up the table?  it can be simple markdown.  
| First Header  | Second Header |
| ------------- | ------------- |
| Content Cell  | Content Cell  |
| Content Cell  | Content Cell  |

https://psychic-giggle-6b21ea8e.pages.github.io/managing-and-performing.html#learning-activities-2

**Comment by Jeff-TWU** [comment]
@kmarjanovic Replaced with [H5p Activity](https://psychic-giggle-6b21ea8e.pages.github.io/managing-and-performing.html#activity-important-vs.-urgent). Will this work?

**Comment by kmarjanovic** [comment]
Hi Jeff - I like the look of the h5p...but they are open ended questions - with no word length requirement.  A simple graphic would be better - for them to see the 4 categories and take notes (or we make it interactive.
Here's my 2 attempts - but they don't achieve the note-taking / categorizing goal of the activity
![image](https://user-images.githubusercontent.com/35148983/211657923-23a07fd9-b7c6-49a4-b8ce-c94705fa5134.png)

![image](https://user-images.githubusercontent.com/35148983/211658002-95e01cda-345e-4686-870c-110cfa19c1ce.png)

**Comment by Jeff-TWU** [comment]
@kmarjanovic Hi Kelly, I agree the H5p isn't quite working. Note-taking is probably the way to go. Would this graphic work?
![20230110_Important Vs Urgent](https://user-images.githubusercontent.com/66963480/211670929-9afbd4ab-25db-43fd-9d28-929b29836a58.png)

**Comment by kmarjanovic** [comment]
@Jeff-TWU yes - this graphic works!  Thank you!
