### ISSUE TITLE
LDRS 300 IF Unit 3 Topic 2 - Zappos Case study at end of page all gobbleygook!

### ISSUE THREAD

**Issue by BLMSasaki** [TWUOnline/bug-tracking#65]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 
 LDRS 300 IF Unit 3 Topic 2

**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 The case study at the end - Zappos - formatting needs correction. It is all crammed together (don't know the technical term! gobbly gook!) 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  
2. Unit #         Topic #         Activity#  
 UNIT 3    TOPIC 2      Activity 3.2 Zappos Case study -- originally it was ppt I created.
**Optional: Screenshots**

**Comment by faitht1023** [comment]
fixed!
