### ISSUE TITLE
LDRS 440 Graphics

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#652]
**What course/project is this request for?**
LDRS 440 ([bookdown link](https://psychic-giggle-6b21ea8e.pages.github.io/))
**Describe the request**
Please create graphics for the following
Unit 2 Topic 1:
![image](https://user-images.githubusercontent.com/35148983/202028584-01e076cf-fc35-4503-8b62-6d879fc49abb.png)

Could you also check Unit 1 graphics to see if you would recommend updating some of those? (e.g. colour scheme for graphs doesn't look so great [here](https://psychic-giggle-6b21ea8e.pages.github.io/managing-and-performing.html#topic-3-major-characteristics-of-the-managers-job))

**Comment by Jeff-TWU** [comment]
Oh my! What??
![image](https://user-images.githubusercontent.com/66963480/202033022-0bbdacc0-672d-43c8-b32e-2d2ba7a93f13.png)

I'll come up with something better. 


For [Unit 1 graphics](https://psychic-giggle-6b21ea8e.pages.github.io/managing-and-performing.html#topic-1-what-do-managers-do) I'd recommend removing the frames, having consistency in style (colour, font), improving margins.

**Comment by MaraChequer** [comment]
I'm speechless :D

**Comment by kmarjanovic** [comment]
@Jeff-TWU @MaraChequer  just wait...more goodies to come for this course! ;)

**Comment by Jeff-TWU** [comment]
I'm not excited about it, but there it is. Let me know if you need any changes.
![20221115_Organization and its Environment-01](https://user-images.githubusercontent.com/66963480/202299750-3e83489c-04b9-4337-bf35-3bd0c17efacc.png)

**Comment by MaraChequer** [comment]
That's way better Jeff, you nailed the idea.

**Comment by Jeff-TWU** [comment]
@MaraChequer Thanks Mara!
