### ISSUE TITLE
LDRS 611  Organizational Behaviour 

### ISSUE THREAD

**Issue by MaraChequer** [TWUOnline/bug-tracking#654]
**Which course contains the bug?**  
LDRS 611  Organizational Behaviour 

(Flexible)

 
**Describe the error and/or your suggestion**  
Please remove the syllabus attachment in the **red alert right above the Course Description** in the Course Introduction tab.

Please Replace with this text:
The syllabus includes key information about the course schedule, assignments, and policies. Please find the course syllabus file bellow in this page in Moodle.
 
 
**Location of the bug**  
Specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=20834&section=0#tabs-tree-start
2. Page # Course Introduction     
 

**Screenshot**  

![image](https://user-images.githubusercontent.com/84353161/202806108-48c8e174-83cc-40bd-bc86-70368625c22d.png)

**Comment by MeeksonHundoo** [comment]
Hello @MaraChequer this has been updated.

**Comment by MaraChequer** [comment]
Thank you @MeeksonHundoo !
