### ISSUE TITLE
LDRS 375 in bookdown

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#655]
### Course
LDRS 375: Culture & Christianity
### URL
bookdown url? https://ba-leadership.github.io/ldrs375/

### Instructions
- [x] Please upload Unit 1.  Note some content is still coming.

[LDRS 375_Unit 1-for Production.docx](https://github.com/TWUOnline/bug-tracking/files/10059199/LDRS.375_Unit.1-for.Production.docx)

**Comment by kmarjanovic** [comment]
Thanks Colin!  Could you please share the bookdown url?

**Comment by kmarjanovic** [comment]
Please upload Unit 2.
[LDRS 375 - Unit 2 for Production.docx](https://github.com/TWUOnline/bug-tracking/files/10106582/LDRS.375.-.Unit.2.for.Production.docx)
Thank you!

**Comment by Nataliadsanchez** [comment]
Hi Kelly,

Perfect! I will :)

________________________________

**Comment by kmarjanovic** [comment]
@Nataliadsanchez feel free to work on this to get used to Bookdown.
Otherwise - I believe Colin is working on this course.  Meekson and Jeff work on Production as well so can help if you run into issues.  Good luck!

**Comment by kmarjanovic** [comment]
Unit 2 revision:
Please take out reference to reading the Preface (Activity 2.1 & in checklist)

@cmadland Do we have a url for this course? (bookdown site)

**Comment by Nataliadsanchez** [comment]
Changes were made. Also, is this the bookdown URL? https://github.com/BA-Leadership/ldrs375

**Comment by cmadland** [comment]
Hey @Nataliadsanchez great job with unit 2! Did you just copy and past from the word file?

Nothing wrong with that if you did, but we can convert from Werd to markdown, then copy from there. Perhaps we can connect on Monday?

**Comment by cmadland** [comment]
@Nataliadsanchez I edited unit 2 real quick and added some comments in the commit, which you can see at [https://github.com/BA-Leadership/ldrs375/commit/fa77f7d34db5f88516378c118d8fe6fbff2b44ae](https://github.com/BA-Leadership/ldrs375/commit/fa77f7d34db5f88516378c118d8fe6fbff2b44ae)

Mostly just spacing...thanks again!

**Comment by Nataliadsanchez** [comment]
Thanks for the feedback @cmadland I took a look at the changes that you made, and the notes you added :) ...  Yes, I did copy/paste from Word.  Do you have the time to show me how to convert from Word to Markdown today in the afternoon? Thank you!!

**Comment by Nataliadsanchez** [comment]
Could you please upload the Assessment part? Grading Criteria is still missing.

[Assessments - LDRS 375--2nd draft--12-09-2022.docx](https://github.com/TWUOnline/bug-tracking/files/10197920/Assessments.-.LDRS.375--2nd.draft--12-09-2022.docx)

Thank you!

**Comment by Nataliadsanchez** [comment]
Could you please upload Unit 3 as well? I started to upload it but then, more changes were made.
This is the final version (for now) of U3. Thank you!
[LDRS 375 - Unit 3.docx](https://github.com/TWUOnline/bug-tracking/files/10210737/LDRS.375.-.Unit.3.docx)

**Comment by MeeksonHundoo** [comment]
> Could you please upload the Assessment part? Grading Criteria is still missing.
> 
> [Assessments - LDRS 375--2nd draft--12-09-2022.docx](https://github.com/TWUOnline/bug-tracking/files/10197920/Assessments.-.LDRS.375--2nd.draft--12-09-2022.docx)
> 
> Thank you!

Hello @Nataliadsanchez Assessment has been uploaded. Here is the link to it: https://fictional-spork-227906c2.pages.github.io/assessment-2.html

Below are two hyper links on the word doc that are not accessible. Could you please provide fresh links for these ones:
1. How to write a good forum response
2. Christian themes for the Final Project

**Comment by MeeksonHundoo** [comment]
> Could you please upload Unit 3 as well? I started to upload it but then, more changes were made. This is the final version (for now) of U3. Thank you! [LDRS 375 - Unit 3.docx](https://github.com/TWUOnline/bug-tracking/files/10210737/LDRS.375.-.Unit.3.docx)

@Nataliadsanchez I am working on this unit and will let you know once completed.

**Comment by Nataliadsanchez** [comment]
Thanks @MeeksonHundoo!!

These are the two missing documents:
[Christian Themes Suggestions - for Final Project .pdf](https://github.com/TWUOnline/bug-tracking/files/10270522/Christian.Themes.Suggestions.-.for.Final.Project.pdf)
[How to write a good forum response’ .pdf](https://github.com/TWUOnline/bug-tracking/files/10270524/How.to.write.a.good.forum.response.pdf)

Please let me know if you can open these files.

**Comment by MeeksonHundoo** [comment]
> > Could you please upload Unit 3 as well? I started to upload it but then, more changes were made. This is the final version (for now) of U3. Thank you! [LDRS 375 - Unit 3.docx](https://github.com/TWUOnline/bug-tracking/files/10210737/LDRS.375.-.Unit.3.docx)
> 
> @Nataliadsanchez I am working on this unit and will let you know once completed.

Hello @Nataliadsanchez U3 is up. Here is it's link: https://fictional-spork-227906c2.pages.github.io/what-is-christianity-ii-what-do-christians-believe.html
Please let me know if any further edits are needed.

**Comment by MeeksonHundoo** [comment]
> Thanks @MeeksonHundoo!!
> 
> These are the two missing documents: [Christian Themes Suggestions - for Final Project .pdf](https://github.com/TWUOnline/bug-tracking/files/10270522/Christian.Themes.Suggestions.-.for.Final.Project.pdf) [How to write a good forum response’ .pdf](https://github.com/TWUOnline/bug-tracking/files/10270524/How.to.write.a.good.forum.response.pdf)
> 
> Please let me know if you can open these files.

Hello @Nataliadsanchez thanks for providing these pdf's. They've been embedded now under assessments. Here is it's link:
https://fictional-spork-227906c2.pages.github.io/assessment-4.html

**Comment by Nataliadsanchez** [comment]
[LDRS 375_U4.docx](https://github.com/TWUOnline/bug-tracking/files/10316374/LDRS.375_U4.docx)
Could you please upload the Unit 4? Thank you!

**Comment by Nataliadsanchez** [comment]
Could you please upload Unit 4? Thank you!
[LDRS 375 - Unit 4 - 12-28-2022.docx](https://github.com/TWUOnline/bug-tracking/files/10316519/LDRS.375.-.Unit.4.-.12-28-2022.docx)

**Comment by MeeksonHundoo** [comment]
Hello @Nataliadsanchez U4 is up. Here is the link to it. https://fictional-spork-227906c2.pages.github.io/what-is-culture-part-i-to-engage-or-not-to-engage.html

**Comment by Nataliadsanchez** [comment]
Could you please upload Unit 6? Thank you!
[LDRS 375 Unit 6 - v.01.16.23.docx](https://github.com/TWUOnline/bug-tracking/files/10429962/LDRS.375.Unit.6.-.v.01.16.23.docx)

**Comment by Nataliadsanchez** [comment]
Could you please upload Unit 5 as well? Thank you!
[LDRS 375_U5 - v.01.16.23.docx](https://github.com/TWUOnline/bug-tracking/files/10430034/LDRS.375_U5.-.v.01.16.23.docx)
