### ISSUE TITLE
LDRS 440 Unit 5 image

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#658]
**What course/project is this request for?**
LDRS 440 - Unit 5 Topic 1

https://psychic-giggle-6b21ea8e.pages.github.io/

**Describe the request**
Could you please help with this graphic?  I believe it was a pwpt slide
![Unit 5 topic 1](https://user-images.githubusercontent.com/35148983/204691466-61b29ee7-cf7c-4871-91bf-e1de4ae925bb.jpg)

**Priority**
Course runs in January.

Use the label to add the priority**

**Comment by kmarjanovic** [comment]
Also looking for a replacement image of this
![U5 topic 1 balancing-budget-rocks](https://user-images.githubusercontent.com/35148983/204693123-fa486e06-d9c0-42bf-9760-1000550eb3eb.jpg)
from here: https://www.mymoneycoach.ca/budgeting/what-is-a-budget-planning-forecasting

**Comment by kmarjanovic** [comment]
And another from Unit 5 - topic 2
![U5 topic 2](https://user-images.githubusercontent.com/35148983/204693671-b67a6575-86bd-4567-80d7-cc68f6ef2d66.jpg)

**Comment by Jeff-TWU** [comment]
> **What course/project is this request for?** LDRS 440 - Unit 5 Topic 1
> 
> https://psychic-giggle-6b21ea8e.pages.github.io/
> 
> **Describe the request** Could you please help with this graphic? I believe it was a pwpt slide ![Unit 5 topic 1](https://user-images.githubusercontent.com/35148983/204691466-61b29ee7-cf7c-4871-91bf-e1de4ae925bb.jpg)
> 
> **Priority** Course runs in January.
> 
> Use the label to add the priority**

@kmarjanovic I think it would make more sense to put this in a table. What do you think? Would that be alright?

**Comment by kmarjanovic** [comment]
Yes that works too!  I put that notes in unit 5. Thanks for the feedback, Jeff!

**Comment by Jeff-TWU** [comment]
@kmarjanovic Replaced images. [See in context.](https://psychic-giggle-6b21ea8e.pages.github.io/budgeting.html)

The table didn't look right. Compromised with lists.  Let me know if you would prefer an image.
