### ISSUE TITLE
Editing Request - LDRS 302 IF Unit 1 Topic 3 - remove the table 

### ISSUE THREAD

**Issue by BLMSasaki** [TWUOnline/bug-tracking#66]
### Course
**LDRS 302 IF Unit 1 Topic 3**

Before starting on an editing project, please connect with the Instructional Designer to go over specific requests for the course.

### Copy Editing
- [ ] Editing for grammar, usage, spelling, punctuation, and other mechanics of style checking for consistency of mechanics. 
- [x] Check heading levels.
  - [ ] # Unit; ## Overview
  - [ ] ### Learning Activities; ### Activity 1.1
  - [ ] ##Assessment; ###Assignment 1; #### Grading Rubric
- [X] Format tables, figures, and lists. - The table in Unit 1-Topic 3 is the same one list in Unit 1-Topic 2 -- I think this is a mistake. (It should in Topic 2 only)
- [ ] Canadianizing (spelling).
- [ ] Edit for citation style consistent with the subject area.  
- [ ] Edit for consistent structure and basic formatting.
- [ ] Check all links (to web or docs). Flag broken links.  Ensure correct title and minutes are listed.
- [ ] Check that all images/tables have a description/caption.

### Specifics
- [ ] Unit Overview:
  - [ ] Topics are consistent with unit topics
  - [ ] Topics are numbered
  - [ ] Learning outcomes are bulleted; Capitalize the first letter and have a period.
- [ ] Format Activity Checklists – use alert plugin.

### Making Recommendations (Check with Instructional Designer)
- [ ] Make recommendations to ensure that the existing wording of the course content is appropriate for learners of diverse cultural backgrounds, e.g. the language is culturally sensitive.
- [ ] Clarifying meaning, eliminating jargon, polishing language, and other non-mechanical line-by-line editing, 

### Track Changes  
- [ ] On word documents, Track Changes should be used unless requested otherwise.
- [ ] On Github, make a pull request, detailing the changes/questions.

**Comment by faitht1023** [comment]
Good afternoon @BLMSasaki ,

Would you like the table and its contents removed or would you like the information in the table to be reformatted?

~Faith

**Comment by BLMSasaki** [comment]
Removed please


Brenda-Lee Sasaki, MA, CLC, ACC

Adjunct Professor | TWU Richmond

Academic Facilitation Specialist / TWU GLOBAL

Trinity Western University | t. 604.513.2193 | c. 604.785.4126 | e. Brenda-lee.Sasaki@twu.ca


twu.ca<http://www.twu.ca/>



[cid:image003.png@01D567BE.8201A250]<https://www.facebook.com/trinitywestern/>  [cid:image004.png@01D567BE.8201A250] <https://www.instagram.com/trinitywestern/>   [cid:image005.png@01D567BE.8201A250] <https://twitter.com/TrinityWestern>   [cid:image006.png@01D567BE.8201A250] <https://www.youtube.com/user/TrinityWesternU>   [cid:image007.png@01D567BE.8201A250] <https://www.linkedin.com/school/trinity-western-university/>



[cid:image001.png@01D5649E.C2C49090]


Trinity Western University is located on the traditional, ancestral, and unceded territory of the Sto:lo people.
________________________________

**Comment by kmarjanovic** [comment]
@BLMSasaki @cmadland @faitht1023 @345-Jay @rezakh66  
Sorry didn't mean to unassign you all! (Was trying to assign Dave, but didn't work for some reason).
Has this issue been resolved?

**Comment by faitht1023** [comment]
I have just removed the table
