### ISSUE TITLE
PHIL 210 GX FA 2022 Small edits

### ISSUE THREAD

**Issue by SimoneVanDerMerwe** [TWUOnline/bug-tracking#660]
PHIL 210 GX FA 2022
 
Edit the "Ethics Committee Assignment" percentage from 15% to 20% in 2 places:

1) Unit 1 > Assessment Tab > Green Box
URL: https://learn.twu.ca/course/view.php?id=25042&section=1#tabs-tree-start
2) Unit 4 > Assessment Tab > Green Box
URL: https://learn.twu.ca/course/view.php?id=25042&section=4#tabs-tree-start

![image](https://user-images.githubusercontent.com/98186755/205763445-41ec20ad-7d9b-4e12-9bba-c24594d008e2.png)

Edit the "Reflective Journal" Assignment percentage from 5% to 20%:

1) Unit 2 > Assessment Tab > Green Box
URL: https://learn.twu.ca/course/view.php?id=25042&section=2#tabs-tree-start
 
![image](https://user-images.githubusercontent.com/98186755/205763981-e714f8df-9575-4b9f-86d6-bc86f92cf499.png)

 
P.S. I did change these parts in Atom, but the changes did not appear in Moodle. 

Thank you very much!

**Comment by MeeksonHundoo** [comment]
Hello @SimoneVanDerMerwe these changes did not appear as we have push these changes and also clear cache in GRAV..! Which I did. Moreover, our team has stopped using ATOM as GitHub is archiving ATOM and won't be supporting it anymore from 15th Dec 2022.  Hence, we have all moved to using VS code as the new editor in which we do most of our stuff.

**Comment by SimoneVanDerMerwe** [comment]
Hello @MeeksonHundoo Thank you for letting me know!
