### ISSUE TITLE
PHIL 210 GX FA2022 - Removing an Assignment

### ISSUE THREAD

**Issue by SimoneVanDerMerwe** [TWUOnline/bug-tracking#661]
PHIL 210 GX FA2022
 
We need to remove the Ethics Video Assignment from the "Assessments" tab, **as well as the grading rubric**:
 
Assessments > Ethics Video
 
 URL: https://learn.twu.ca/course/view.php?id=25042&section=14#tabs-tree-start

![EditsPHiL210](https://user-images.githubusercontent.com/98186755/205765979-69136b9d-d934-4470-9618-9035f5103616.jpg)

Thank you!

Simone

**Comment by MeeksonHundoo** [comment]
Hello @SimoneVanDerMerwe this has been done as shown below.

![image](https://user-images.githubusercontent.com/98780625/205858481-009a5e3c-1886-433a-b098-111d92b0b341.png)

**Comment by SimoneVanDerMerwe** [comment]
@MeeksonHundoo Thank you very much!
