### ISSUE TITLE
SKLS 500 Revisions

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#662]
**Which course contains the bug?**  
[SKLS 500](https://learning-commons.github.io/skls500/) 
 
Please make the following revisions from Qinqin:
Module 4
- [x]	Add Qinqin Zhang as the author below the module title.
- [ ]	The labelling system of the activities throughout the module is not consistent in the box, Unit 4 Learning Activities. Check the activity # - and then fix in the checklist 

- [x]	Right within the current box of Activity 4.3.1, the line skls500_activity4-2 seems redundant.  Delete in H5P

- [x]	In Activity 4.4.1, add ‘Watch this video by Western Libraries…” as this is their video.

- [x]	add a screenshot for the off-campus access for 4.6 after the first paragraph below. Please see the attached screenshot.
Off-campus access
When you are off campus and want to access the full text of our electronic resources, our library system will prompt you to log in when you click on any full text links. Use your Moodle username + mytwu.ca ([john.doe@mytwu.ca](mailto:john.doe@mytwu.ca)) and your Moodle password.

![m4Off-CampusLoginScreen](https://user-images.githubusercontent.com/35148983/205993320-97f3f0d2-4f9c-4cd2-b892-ca5e095546f9.jpg)

- [x]	Still in 4.6, the paragraph about EBSCO login, EBSCO login (via the upper left corner on the search results page; see screenshot above) should say “see screenshot below”. The registration link towards the end of the paragraph is broken, and we could just remove that last line. Free registration link is [here](https://tinyurl.com/4p5sfabr). It should read ‘please register for a free EBSCO account separately via the Sign in page.’ (the highlighting is only to mark out the changes needed)

- [x]	In Activity 4.7.1, where it says Search in Library OneSearch Advanced Search using the search keywords you came up with from the previous learning activity should say … using the search keywords you identified from Activity 4.5.

- [x]	The first line under the section for Activity 4.9.1 should say ‘Pick one article you found from Activity 4.7.”

**Comment by kmarjanovic** [comment]
Please take out all Assessment info - from course home page, unit activity checklist and assessments sections, and main assessment section. (@cmadland can we hide the assessment page in bookdown?)
Instead, add at the end of each unit "Your instructor will provide details on the Assessment for this unit.  See also the Assignment dropboxes in Moodle for further instructions."

**Comment by cmadland** [comment]
re: labeling in u4 ... it looks like we need to change all the units...is that correct?

**Comment by kmarjanovic** [comment]
Yes - we'll need to check all activity checklists.  Perhaps we don't need to number the activities in the list?

**Comment by kmarjanovic** [comment]
Course home section: delete assignment list.  Change to:
See the Course Syllabus for assessment details. Submit all assignments via the assignment dropboxes in Moodle.

**Comment by MeeksonHundoo** [comment]
Sorry for replying late @kmarjanovic these edits have already been incorporated.

**Comment by kmarjanovic** [comment]
@cmadland @MeeksonHundoo the assessment info is still there.  Could we make that change before tomorrow's 11am meeting?  Just hiding in bookdown in case they want to show it another time.

**Comment by MeeksonHundoo** [comment]
Sorry. Forgot to share the link:
https://learning-commons.github.io/skls500/introduction-to-research.html

**Comment by kmarjanovic** [comment]
remove  (12 @ 5 each) from Learning Log in Course evaluation section

**Comment by MeeksonHundoo** [comment]
Hello @kmarjanovic both these changes have been implemented!

**Comment by kmarjanovic** [comment]
Thanks so much @MeeksonHundoo !!
