### ISSUE TITLE
PHIL 210 GX FA 2022

### ISSUE THREAD

**Issue by SimoneVanDerMerwe** [TWUOnline/bug-tracking#663]
PHIL 210 GX FA 2022
 
Unit 5 > Assessment > Remove the "grading rubric" for the video assignment.
 
 URL: https://learn.twu.ca/course/view.php?id=25042&section=5#tabs-tree-start 
 
![PHIL210](https://user-images.githubusercontent.com/98186755/206016695-f7c32f5f-f83d-4b3c-83fa-ab9b2d0dd25c.jpg)

Thank you very much!!
Simone

**Comment by MeeksonHundoo** [comment]
Hello @SimoneVanDerMerwe this has been updated as shown below

![image](https://user-images.githubusercontent.com/98780625/206317677-5564e310-a25b-4d25-8e64-f5bb7d3f3d89.png)

**Comment by SimoneVanDerMerwe** [comment]
Thank you so much, @MeeksonHundoo
