### ISSUE TITLE
LDRS 591 for January start (several changes to course schedule, assignment modification, etc.)

### ISSUE THREAD

**Issue by cpenfoldnavarro** [TWUOnline/bug-tracking#664]
**Which course contains the bug?**  

 LDRS 591 OL SP2023
 
**Describe the error and/or your suggestion**  

I am not able to make edits to the course in Moodle, so I am submitting them here. Changes are needed to:
Course Schedule
Assignment 4 (removed)
Assignment 5 (renamed to Assignment 4)
Unit 10 Discussion (removed)
Grade Values (adjusted to reflect above changes)
Syllabus (new syllabus uploaded)

All changes are outlined in word document attached.
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  various urls are provided in attached document. 
2. Unit #         Topic #         Activity#  
 
**Optional: Screenshots**  
[LDRS 591 OL Changes for January 2023.docx](https://github.com/TWUOnline/bug-tracking/files/10178475/LDRS.591.OL.Changes.for.January.2023.docx)
[LDRS 591 OL SPRING 2023 (Penfold Navarro).pdf](https://github.com/TWUOnline/bug-tracking/files/10178476/LDRS.591.OL.SPRING.2023.Penfold.Navarro.pdf)

**Comment by cpenfoldnavarro** [comment]
I have been able to update the "Course Schedule" tab, but also need access to update the "Course Introduction" section, so that I can post an updated Course Syllabus.

Thanks, in advance, for your help!

**Comment by kmarjanovic** [comment]
Hi Cathy,
We try not to include the syllabus in the Git content, so we don't need to change it for each term.  Instead we have this note:

"The syllabus includes key information about the course schedule, assignments, and policies. Please read the full course syllabus found at the bottom of this page."

Now that we have the new Moodle layout, perhaps we should say "Please read the full course syllabus found at the bottom of this tab."  

Could you confirm that Sergio has signed off on the Assessment changes for all 591 sections (that use this Git material)?  Then we can make all of those assessment changes, including the info on the Course Intro tab.

**Comment by cpenfoldnavarro** [comment]
Hi, Kelly,
Thanks! That make sense.

I'll try to add the Syllabus at the bottom. However, there is a tab that says "Read the Course Syllabus" that goes to the syllabus from the fall. Can that be removed?

Sergio, Gang LI and I met Friday. We're going to meet with Mark Halverson to discuss changes to be made to the course. He's onboard with making revisions, but wants to do so thoughtfully, with input from all of us -- which is great.

We discussed removing Assignment 4, so In the meantime, I'm going to remove that from the LDRS 591 class I'm teaching in January. I don't think I can change the content in the course (since it's not editable), so I'll just have to communicate clearly about that with the students.

Thanks!
Cathy


CATHARINE PENFOLD NAVARRO, PhD

Part-Time Instructor, MA Leadership | TWU GLOBAL

Trinity Western University | e. ***@***.******@***.***>



twu.ca<http://www.twu.ca/>



***@***.***

________________________________
