### ISSUE TITLE
PSYC 408 Assignment Edits

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#665]
### Course
[PSYC 408 - History & Systems of Psychology (ADC Master)](https://learn.twu.ca/course/view.php?id=23627&section=0#tabs-tree-start)
### Instructions
- Please add to the [Discussions tab](https://learn.twu.ca/course/view.php?id=23627&section=8#tabs-tree-start) - both the [git content](https://github.com/TWUOnline/arts-master/blob/master/pages/35.psyc408/15.assessments/01.discussion-forums/page.md) - and the dropboxes - use [SU 2022 info for discussions](https://learn.twu.ca/course/view.php?id=23277&section=8#tabs-tree-start)
- Also add [Class Presentations tab](https://learn.twu.ca/course/view.php?id=23627&section=10#tabs-tree-start) from [git content](https://github.com/TWUOnline/arts-master/blob/master/pages/35.psyc408/15.assessments/04.Class-Presentations/page.md) and [dropbox](https://learn.twu.ca/course/view.php?id=23277&section=9#tabs-tree-start)
- Please convert the image of grading criteria to markdown - in all assessments (low priority)

**Comment by kmarjanovic** [comment]
Note the [PSYC 408 SP 2023](https://learn.twu.ca/course/view.php?id=27110) course has all the assignment info, so I'll change this to low priority.  For the next offering, let's make sure the master is set up - with assignment info, dropboxes, and gradebook setup.
Thank you!

**Comment by cmadland** [comment]
Can we copy SP2023 back to the Master? @kmarjanovic @MeeksonHundoo

**Comment by kmarjanovic** [comment]
yes - that works too!

**Comment by MeeksonHundoo** [comment]
Hello @kmarjanovic Could you please advice if we can perform an import from the PSYC 408 OL - History and Systems of Psychology (SU 2022) to the PSCY 408 ADC master? That way we could have all that's needed.

**Comment by kmarjanovic** [comment]
Yes please!  Thanks Meekson!

**Comment by MeeksonHundoo** [comment]
Hello @kmarjanovic Import has been performed. Here is the link to the PSYC 408 (ADC Master) https://learn.twu.ca/course/view.php?id=23627

**Comment by kmarjanovic** [comment]
Thanks Meekson!
Please correct the following:
- [ ] remove presentation dropbox from Case studies section
- [ ] put in presentation section and delete case studies dropboxes
- [ ] remove duplicates from journal article and take home exam sections

**Comment by kmarjanovic** [comment]
just following up on this.  @MeeksonHundoo could you please help with those last edits?

**Comment by MeeksonHundoo** [comment]
> just following up on this. @MeeksonHundoo could you please help with those last edits?

Hello @kmarjanovic apologies for the delay. These edits have been implemented.

**Comment by kmarjanovic** [comment]
Thanks so much!
