### ISSUE TITLE
LDRS 440 Unit Images

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#667]
**What course/project is this request for?**
LDRS 440
https://psychic-giggle-6b21ea8e.pages.github.io/

**Describe the request**
Not a priority - but let's discuss what Header/Unit images could look like for this course.
Here's an example the SME provided for Unit 9 (no source, so let's find an open image).
![U9 unit image](https://user-images.githubusercontent.com/35148983/207155758-d1aac671-e745-46fd-8c4d-d699b273d998.jpg)

**Comment by kmarjanovic** [comment]
btw above image linked in unit intro with “A chain is only as strong as its weakest link”.  I'll check other unit intros for appropriate graphics.

**Comment by Jeff-TWU** [comment]
@kmarjanovic Photoshop to the rescue.
![broken_chain](https://user-images.githubusercontent.com/66963480/207181600-6a00a439-277c-4cc0-a791-8cb959950e68.png)
[Source](https://unsplash.com/photos/VKnWrMnxahg)
