### ISSUE TITLE
LDRS 631 Edits

### ISSUE THREAD

**Issue by erackow** [TWUOnline/bug-tracking#668]
**Which course contains the bug?**  
LDRS 631 N2, and LDRS 631 OL - please make changes in both courses
 
 
**Describe the error and/or your suggestion**  

Remove Huber et al. 2011 reference and link from Unit 1 Learning Activity 1.1 and Unit 1 on the course schedule.  Please also remove the remainder of the sentence after (2018) under "Read and Reflect"  (__...and the following article by Huber et al., (2011) ["How should we define health?"])__
URL of Learning Activity 1.1 https://learn.twu.ca/mod/page/view.php?id=804863

Remove Giacomini et al, 2001 reference and link from Unit 2 Learning Activity 2.2 and Unit 2 on the course schedule.  
Replace with Abelson, Miller, & Giacomini (2009) What does it Mean to Trust a Health System?: A Qualitative Study of Canadian Health Care Values.  Link: https://www-sciencedirect-com.twu.idm.oclc.org/science/article/pii/S016885100800256X?via%3Dihub
URL of Learning Activity 2.2  https://learn.twu.ca/mod/page/view.php?id=804883

Remove Barbuto, Gottfredson, and Searle, 2014 reference and link from Unit 5 Learning Activity 5.4 and Unit 5 on the course schedule.  Please change the word "articles" to "article" in the paragraph immediately below "Read and Reflect", and in the first two questions in the reflective journal.  
URL of Learning Activity 5.4  https://learn.twu.ca/mod/page/view.php?id=804926

Remove Timmins (2011) link from Unit 6 Learning Activity 6,3 and the link from the course schedule.  Please leave the reference to the article in both locations.  In Learning Activity 6.3 please remove the link and in its place add:  "PDF of article found following the reference page for Unit 6". 
URL for Learning Activity 6.3 https://learn.twu.ca/mod/page/view.php?id=804939

**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  
2. Unit #         Topic #         Activity#  

**I attempted to provide these descriptions above - however, the URL's that I added are all for the 631 N2 Moodle course - I don't know what they are in the OL course (or if they are the same.**  
 
**Optional: Screenshots**  

I didn't add these because I couldn't figure out how to just screenshot, and then "paste" below.

**Comment by MeeksonHundoo** [comment]
Hello @erackow I've made the changes. Could you please advice on "Remove Timmins (2011) link from Unit 6 Learning Activity 6,3 and the link from the course schedule. Please leave the reference to the article in both locations" please. It's  a bit confusing as to are we supposed to remove the Timmins (2011) link or keep it?

**Comment by erackow** [comment]
Hello,

Below this email it says that I can respond directly to the email, so I am going to do that.  I can figure out how to add screenshots to the email, but not to GitHub.

Sorry - I didn't mean to confuse.

It appears that everything has been removed, but what I wanted was for the link ONLY to be removed, but the reference left.

For example, I think it used to say:   In this learning activity you will read Jit, Sharma, and Kawatra (2017) “Servant leadership and conflict resolution: a qualitative study”<http://202.166.170.213:8080/xmlui/bitstream/handle/123456789/1722/Servant%20leadership%20and%20conflict%20resolution.pdf?sequence=1&isAllowed=y> and Timmins (2011) [link was here].  I wanted it to look like this:

 In this learning activity you will read Jit, Sharma, and Kawatra (2017) “Servant leadership and conflict resolution: a qualitative study”<http://202.166.170.213:8080/xmlui/bitstream/handle/123456789/1722/Servant%20leadership%20and%20conflict%20resolution.pdf?sequence=1&isAllowed=y> and Timmins (2011) (<-- this reference remains, but...) [link removed because it is broken].

If you look in Unit 6, after the reference list, there is a pdf of the Timmins article that the students have access to.  See just above Unit 7 on the left of this screenshot.  I have circled it in red in the attached screenshot pasted into Word.


[cid:f96ed9d9-a18e-4a88-a510-bf4aaec8681b]


The link doesn't work (remove it), but I don't want the reference (Timmins, 2011) removed, because the article is embedded in Unit 6 in Moodle.  They will still read the Timmins article, but they will access the article another way - not using that link that is broken.

I hope that is clearer?

Liz


ELIZABETH RACKOW, MA

Sessional Professor, Teaching Assistant MA Leadership | TWU GLOBAL

Trinity Western University | e. ***@***.***

[cid:92a94c6d-94b1-4a4b-b6cd-9db969ca2f53]
________________________________

**Comment by MeeksonHundoo** [comment]
Test Image.. please igore
![image](https://user-images.githubusercontent.com/98780625/210651784-ba60a95b-a85d-4ca1-9c83-90f8c787ec3c.png)
