### ISSUE TITLE
LDRS 591 M3 SP 2023 Small Edits

### ISSUE THREAD

**Issue by SimoneVanDerMerwe** [TWUOnline/bug-tracking#672]
LDRS 591 M3 SP 2023
 
I am requesting a few edits to some of the assignments' titles:
1. Assignment 1: Literature Search 
Please remove the subtitle: "Assignment 1: Literature Search"
URL: https://learn.twu.ca/course/view.php?id=26283#section-7
![Assignment 1](https://user-images.githubusercontent.com/98186755/211624268-e0c787a6-8bcc-4566-a66f-bc605e980192.jpg)

2. Group Article Critiques
Please remove the subtitle: "Assignment 2: Article Critiques"
URL: https://learn.twu.ca/course/view.php?id=26283#section-8
![Group Article Critiques](https://user-images.githubusercontent.com/98186755/211624680-c41cc05e-3044-4765-bd5d-e499d7fa9f78.jpg)

3. Assignment 2: Scholarly Article Review
Please remove the subtitle: "Assignment 3: Scholarly Article Review"
URL: https://learn.twu.ca/course/view.php?id=26283#section-9
![Assignment 2](https://user-images.githubusercontent.com/98186755/211625206-13408108-fd08-4272-a440-04913dcbb9d5.jpg)

4. Assignment 3: Formal Literature Review
Please remove the subtitle: "Assignment 4: Formal Literature Review"
URL:https://learn.twu.ca/course/view.php?id=26283#section-10
![Assignment 3](https://user-images.githubusercontent.com/98186755/211625490-35e11c09-a182-4483-96b3-cea5b25cbb75.jpg)

**Comment by kmarjanovic** [comment]
@SimoneVanDerMerwe - I'm going to close these 591 issues, as I assume they are fixed in the new Moodle Books.  Please let us know if you need anything.
