### ISSUE TITLE
LDRS 591 M3 SP 2023 Updates

### ISSUE THREAD

**Issue by SimoneVanDerMerwe** [TWUOnline/bug-tracking#673]
LDRS 591 M3 SP 2023 
I would like to have the required text references updated to APA 7th and the Assignments' names and values in **two places**.
 
**Location 1: Course Introduction**
1. Under "Required Texts", please change the references to the following:

American Psychological Association. (2020). _Publication manual of the American Psychological Association_ (7th ed.). [](http://doi.org/10.1037/0000165-000)

Frederiksen, L., & Phelps, S. F. (n.d.). _Literature reviews for education and nursing graduate students_. [](https://press.rebus.community/literaturereviewsedunursing/)

Plano Clark, V., & Creswell, J. (2015). _Understanding research: A consumer’s guide_ (2nd ed.). Pearson.

Electronic resources: Additional articles will be assigned in specific units and will be available from the TWU library.

 URL: https://learn.twu.ca/course/view.php?id=26283

2. Under "Course Evaluation", please update the assignments' names and values to the following:
                                                                           
Group Participation | Presentations/Group Article Critiques | 20%
Assignment 1 | Literature Review Search   (WC)                    | 25%
Assignment 2 | Scholarly Article Review   (WC)                      | 20%
Assignment 3 | Final Literature Review   (WC)                        | 35%
                                                       Total                                 | 100%
![LDRS 591 M3 Course introduction](https://user-images.githubusercontent.com/98186755/211649923-52ec2a93-adf2-4d56-9ebb-e2317766984f.jpg)

**Location 2: Course Book**

1. Under "Course Evaluation": please, adjust the names and values of the assignments as shown above.
2. Under "Required Texts":  please update the references as shown above.

URL: https://learn.twu.ca/course/view.php?id=26283#section-3

![LDRS 591 M3 Course Book 1](https://user-images.githubusercontent.com/98186755/211652749-447dc8be-22a3-4929-8ba4-9b85d17ff90c.jpg)

![LDRS 591 M3 Course Book 2](https://user-images.githubusercontent.com/98186755/211652447-704d22a5-3ceb-4fc2-9e7d-ec1ab9ef3870.jpg)

**Comment by kmarjanovic** [comment]
Hi @SimoneVanDerMerwe - has this been fixed for you?

**Comment by SimoneVanDerMerwe** [comment]
Hello @kmarjanovic, thank you for following it up!

No, the two issues I opened for 591 M3 have not yet been fixed.

**Comment by kmarjanovic** [comment]
@SimoneVanDerMerwe - I'm going to close these 591 issues, as I assume they are fixed in the new Moodle Books.  Please let us know if you need anything.
