### ISSUE TITLE
LDRS 591 M3 SP 2023: Small edits

### ISSUE THREAD

**Issue by SimoneVanDerMerwe** [TWUOnline/bug-tracking#674]
LDRS 591 M3 SP 2023. I would like to edit some details of Assignment 3, such as the number of articles and the length of the paper.

Location 1: Assignment 3: Formal Literature Review (left tab) > 4th Paragraph:
**Current text:**
Please note that I am NOT asking you to review ALL of the empirical evidence on your topic (this would be a huge undertaking). I am asking you to select a minimum of 10 scholarly sources that you will use to review for your paper. This means you are writing a literature review in a maximum of 12 pages (including title page, body of paper, reference list).

**Please, Change it to:**
Please note that I am NOT asking you to review ALL of the empirical evidence on your topic (this would be a huge undertaking). You will only use the five scholarly sources from Assignment 1. This means you are writing a literature review in **a maximum of 8 pages, including the title page, the writing centre report, the body of the paper, and the references list.**
URL: https://learn.twu.ca/course/view.php?id=26283&section=10
![Assignment 3 Edits 1](https://user-images.githubusercontent.com/98186755/211822767-a2a81dcb-bf49-4ae1-96bb-6c7d2d43f5bb.jpg)

 Location 2: Assignment 3: Formal Literature Review (left tab) > Your Literature Review Checklist > 2nd bullet point:

**Current text:**
[ ] Have a critical review of literature that expands upon at least 2 main themes, each based upon multiple sources (10 sources total).

**Please, changed it to:**
[ ] Have a critical review of literature that expands upon at least 2 main themes, each **based upon the five sources from Assignment 1.**

URL: https://learn.twu.ca/course/view.php?id=26283&section=10
![Assignment 3 Edits 2](https://user-images.githubusercontent.com/98186755/211823936-9cc41c61-563b-4d61-bc5b-9f77e50e8757.jpg)

**Comment by kmarjanovic** [comment]
@MeeksonHundoo @cmadland just checking that this issue has been addressed?

**Comment by SimoneVanDerMerwe** [comment]
Thank you @kmarjanovic, It has not yet been addressed. Thank you for following it up! I really appreciated it :)

**Comment by kmarjanovic** [comment]
@cmadland @chloecwh following up on this.  There are a couple issues from Simone in High priority. Were these fixed?

**Comment by kmarjanovic** [comment]
Actually - I see now it's addressing the Grav course, not the new Moodle books.  We should be able to close this.
