### ISSUE TITLE
PHIL 210 GX SP 2023 small edit

### ISSUE THREAD

**Issue by SimoneVanDerMerwe** [TWUOnline/bug-tracking#675]
PHIL 210 GX SP 2023 small edit: correcting an assignment percentage:
Location: "Course Introduction" > "Course Schedule" > "Unit 3: Why Be Moral?" row >Partner Project Presentation
 
Please change the percentage from 30% to 40%

URL: https://learn.twu.ca/course/view.php?id=27022
 

![Untitled](https://user-images.githubusercontent.com/98186755/212499190-14e4d40d-40d7-4625-ae9c-a7a0dd9e0b8f.jpg)

.

**Comment by MeeksonHundoo** [comment]
Hello @SimoneVanDerMerwe this is done

**Comment by SimoneVanDerMerwe** [comment]
Thank you so much @MeeksonHundoo  :)
