### ISSUE TITLE
Edits for PSYC 354

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#676]
**Which course contains the bug?**  
[PSYC 354- Brain and Behavior (ADC MASTER)](https://learn.twu.ca/course/view.php?id=23420&section=0) 
 
**Describe the error and/or your suggestion**  
Please see the attached word document with tracked changes and make the suggested edits. 
 
[Edits to Production - Course LOs - Grading - Revised Unit 1.docx](https://github.com/TWUOnline/bug-tracking/files/10427933/Edits.to.Production.-.Course.LOs.-.Grading.-.Revised.Unit.1.docx)

**Comment by MeeksonHundoo** [comment]
Edits have been made. https://learn.twu.ca/course/view.php?id=23420&section=0#tabs-tree-start

**Comment by kmarjanovic** [comment]
Thank you @MeeksonHundoo !
