### ISSUE TITLE
Course Import

### ISSUE THREAD

**Issue by dhanenburg** [TWUOnline/bug-tracking#677]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 SOCI 411 OL SP23
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 I imported my previous SOCI 411 OL SP 2022 course into the course above the way I usually import and it put all the material in one long stream instead of across in tabs. Can you align the course like it is structured in the FALL 2022 version - https://learn.twu.ca/course/view.php?id=25267  
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=27231
2. Unit #         Topic #         Activity#  - ALL the tabs across need to be added. 
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
hello @dhanenburg I see that you SOCI 411 SP 23 is already showing up in one topic format (i.e. topics show up on the top of your course page aligned across) https://learn.twu.ca/course/view.php?id=27231&section=3#tabs-tree-start
Let us know if you need any further assistance.
