### ISSUE TITLE
Course Import Issues

### ISSUE THREAD

**Issue by dhanenburg** [TWUOnline/bug-tracking#678]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 SOCI 320 OL SPRING 2023 - 
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 I imported a previous course into my current course the way I usually import and instead of there being tabs across, all the content is in one long stream. Would appreciate help getting the formatting aligned the way it was. This is the course that needs fixing - https://learn.twu.ca/course/view.php?id=27223 and I would like it formatted like the course I imported - https://learn.twu.ca/course/view.php?id=23304
 
This is the second practicum course that has done this. I have a third course that I'm not going to import in case this happens a third time. Could you please import SOCI 420 OL SU22 - https://learn.twu.ca/course/view.php?id=23311 into SOCI 420 OL SP23 - https://learn.twu.ca/course/view.php?id=27234 making sure all the tabs of content import correctly? 

**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  See above 
2. Unit #         Topic #         Activity#  - All tabs fixed.  
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
Hi @dhanenburg !
You can go to Settings, then in the Course Format section, select OneTopic, and that should give you the tabs at the top, rather than the long stream.
![Screenshot (140)](https://user-images.githubusercontent.com/35148983/212954313-1e58e875-8930-4430-a347-bba73519a2a2.png)

**Comment by dhanenburg** [comment]
Thank you, this worked and I like being able to learn how to make these fixes. Thanks for the instructions.

Debra

**Comment by kmarjanovic** [comment]
Glad it worked out! :)
