### ISSUE TITLE
Production BUSI 231 Unit 1 draft

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#680]
### Course
BUSI 231
### URL
please create a bookdown url.  I'll set up a Moodle master shell

### Instructions
Please upload Unit 1 to a bookdown repo.  Note it's incomplete, but might be a helpful contrast to show the Brians tomorrow.
@cmadland is it possible to do this today?  If you can set up the repo, I can get in there as well.
Thanks!!

[BUSI_231_Unit 1_draft for Production.docx](https://github.com/TWUOnline/bug-tracking/files/10459960/BUSI_231_Unit.1_draft.for.Production.docx)

**Comment by cmadland** [comment]
site is in progress...is there a moodle site ready?

**Comment by kmarjanovic** [comment]
There is now! :)
https://learn.twu.ca/course/view.php?id=27528&section=3

**Comment by cmadland** [comment]
deployment is not cooperating... will keep you posted

**Comment by cmadland** [comment]
@kmarjanovic Unit 1 book is ready, but the course book is taking it's sweet time...

**Comment by cmadland** [comment]
course book is ready @kmarjanovic
