### ISSUE TITLE
LDRS 375 gradebook set-up

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#681]
### Course
- [LDRS 375: Culture & Christianity (MASTER)](https://learn.twu.ca/course/view.php?id=27451)
- [LDRS 375 - SP 2023](https://learn.twu.ca/course/view.php?id=26220&section=4#tabs-tree-start)

### Instructions
@MeeksonHundoo - Could you please help set up the gradebook in both the Master & SP 2023 course?
Thank you!

**Comment by MeeksonHundoo** [comment]
Hello @kmarjanovic As per the course evaluation there are supposed to be 6 forums: 3- Online Forum Presentations [namely 2 (b), 3 (c), 4 (d)] and 3 - Cumulative Online Forum Interactions [namely 1 (a), 2 (b), 5 (e)]. Out of these learning outcomes 2b is reflecting in both of these, whereas we have only 5 forums created in the course https://learn.twu.ca/course/view.php?id=26220&section=4#tabs-tree-start . Could you please confirm with Paul if I should add another forum or is it that learning outcome 2b which is occurring in both the forums should only be in one of them.

**Comment by MeeksonHundoo** [comment]
Hello @kmarjanovic Sorry for responding late. I was in a writing centre appointment. Here are the links for the gradebooks:

LDRS 375: Culture & Christianity (MASTER): Setup: Gradebook setup:
https://learn.twu.ca/grade/edit/tree/index.php?id=27451

LDRS 375 A - Culture & Christianity (SP 2023): Setup: Gradebook setup
https://learn.twu.ca/grade/edit/tree/index.php?id=26220

**Comment by kmarjanovic** [comment]
Thanks so much Meekson!
