### ISSUE TITLE
hello, please take out the middterm exam and put a note: "please see the current syllabus"

### ISSUE THREAD

**Issue by catheryn-zuo** [TWUOnline/bug-tracking#682]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  
2. Unit #         Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
Hi @catheryn-zuo!  Could you please let us know which course this is for?  Section code and url?
Thanks!
Kelly

**Comment by kmarjanovic** [comment]
@cmadland do you know which course this is for?

**Comment by kmarjanovic** [comment]
@catheryn-zuo @cmadland can we close this issue or has this been fixed?  Still not sure which course it is for.
