### ISSUE TITLE
PSYC 330 missing page

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#683]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
[PSYC 330: Leadership in Organization & Small Groups (ADC MASTER)](https://learn.twu.ca/course/view.php?id=18681&section=8#tabs-tree-start)
 
**Describe the error and/or your suggestion**  
In the Assessment section, the Group Discussions page is missing.

**Comment by kmarjanovic** [comment]
Also the Final Presentation section.  Please find and fix :)

**Comment by MeeksonHundoo** [comment]
Hello @kmarjanovic This has been fixed. Here is the link:
https://learn.twu.ca/course/view.php?id=18681&section=7#tabs-tree-start

**Comment by kmarjanovic** [comment]
Thanks @MeeksonHundoo !!
