### ISSUE TITLE
LDRS 320 to bookdown

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#685]
### Course
[LDRS 320 - FAR Master](https://learn.twu.ca/course/view.php?id=17788&section=0#tabs-tree-start)

### Instructions

Please put this Grav course into Bookdown.  The SME would like to print her course (pdf from bookdown) in order to make some revisions.

Is it possible to move this up the priority list? (ready within 3 weeks?).  The course should be formatted nicely in grav 🤞

**Comment by Jeff-TWU** [comment]
> ### Course
> [LDRS 320 - FAR Master](https://learn.twu.ca/course/view.php?id=17788&section=0#tabs-tree-start)
> 
> ### Instructions
> Please put this Grav course into Bookdown. The SME would like to print her course (pdf from bookdown) in order to make some revisions.
> 
> Is it possible to move this up the priority list? (ready within 3 weeks?). The course should be formatted nicely in grav 🤞

@kmarjanovic @MeeksonHundoo No problem. I'll start working on this today.

**Comment by kmarjanovic** [comment]
Thank you @Jeff-TWU !!

**Comment by Jeff-TWU** [comment]
@kmarjanovic Bookdown course is up. https://ubiquitous-goggles-eyvewry.pages.github.io

**Comment by kmarjanovic** [comment]
Thank you so much @Jeff-TWU !!  It looks great!  I'll share with the SME so she can suggest edits moving forward.

**Comment by kmarjanovic** [comment]
Linda sends a big thank you to our online team!!  Thanks @Jeff-TWU :)

**Comment by Jeff-TWU** [comment]
@kmarjanovic Glad she's happy with it. Looks like there's also [another edit issue for this course](https://github.com/TWUOnline/bug-tracking/issues/687)?
