### ISSUE TITLE
LDRS 500 for Production

### ISSUE THREAD

**Issue by Jeff-TWU** [TWUOnline/bug-tracking#688]
[LDRS 500](https://upgraded-adventure-wlozgye.pages.github.io/) has been converted to Bookdown.

**Comment by Jeff-TWU** [comment]
@cmadland @kmarjanovic [LDRS 500](https://upgraded-adventure-wlozgye.pages.github.io/) is up.

**Comment by kmarjanovic** [comment]
Thank you @Jeff-TWU!
Closing this issue and adding edits to other card: https://github.com/TWUOnline/bug-tracking/issues/690
