### ISSUE TITLE
LDRS 502 for Production

### ISSUE THREAD

**Issue by Jeff-TWU** [TWUOnline/bug-tracking#689]
Bookdown for [LDRS 502](https://solid-adventure-l5ny946.pages.github.io)

**Comment by Jeff-TWU** [comment]
[Only 5 Units for this course](https://github.com/TWUOnline/ldrs-master/tree/master/pages/09.502new).

@cmadland @kmarjanovic [It has been ported](https://solid-adventure-l5ny946.pages.github.io).

**Comment by Jeff-TWU** [comment]
> Same format as 500 with the assignment out of the Moodle book and put into a dropbox.
> Note that the assignments in bookdown are from a different course. They should be the same as this: https://learn.twu.ca/course/view.php?id=17713&section=7#tabs-tree-start

- Sorry, The assignments in the bookdown version of the 502 course are not accurate but the rest of the content is?
- Do you want me to embed PDFs in the course, or have them live in their own "Course Material" folder?

**Comment by kmarjanovic** [comment]
pdfs should be embedded in the Learning Activities section.  I'd rather not have a course materials folder unless requested by the SME.

**Comment by Jeff-TWU** [comment]
@kmarjanovic [It's up](https://learn.twu.ca/course/view.php?id=28254&section=2#tabs-tree-start).

I think Learning Activities would function nicely as sub-chapters of the Topics they are associated with. Let me know what (if anything) you would like to change with LA.

**CSS stuff to fix:** 

- [ ] Table styles
- [ ] block quote styles
- [ ] Youtube H5P embed issue

@barishgolland  Can I please get  [LDRS 502]((https://learn.twu.ca/course/view.php?id=28254&section=2#tabs-tree-start)) ported to the dev site, or get some instruction on how I can do it? I have a few CSS things that I can't fix otherwise.

**Comment by kmarjanovic** [comment]
Thanks @Jeff-TWU for all your work on this today!  The course is looking great!

I agree sub-chapters for activities make sense for courses with substantial topics.  For now, let's keep Topics with Activities until we hear feedback from Mark next week  Perhaps on Monday though could you switch one of those units to sub-chapters so we can show the different layout?

Thank you again!!

**Comment by Jeff-TWU** [comment]
> Thanks @Jeff-TWU for all your work on this today! The course is looking great!
> 
> I agree sub-chapters for activities make sense for courses with substantial topics. For now, let's keep Topics with Activities until we hear feedback from Mark next week Perhaps on Monday though could you switch one of those units to sub-chapters so we can show the different layout?
> 
> Thank you again!!

[Unit 1, Topic 1 now displays Learning Activities is a sub-chapter.](https://learn.twu.ca/mod/book/view.php?id=867163&chapterid=6925)

**Comment by kmarjanovic** [comment]
Could we put this table in an accordion instead?
[LDRS 502 Unit 3 in Moodle](https://learn.twu.ca/mod/book/view.php?id=867167&chapterid=7049)
[LDRS 502 Unit 3 in Bookdown](https://solid-adventure-l5ny946.pages.github.io/leading-change-collaboratively.html#distributed-leadership-theory)

**Comment by kmarjanovic** [comment]
- [ ] Please add article in Unit 3 - end of Topic 2
 [Click here](https://learn.twu.ca/pluginfile.php/1070285/mod_resource/content/1/LDRS502_U3_Grigsby.pdf) to read his short article discussing the differences between committees, task forces, and teams.

**Comment by Jeff-TWU** [comment]
> Could we put this table in an accordion instead?
> [LDRS 502 Unit 3 in Moodle](https://learn.twu.ca/mod/book/view.php?id=867167&chapterid=7049)
> [LDRS 502 Unit 3 in Bookdown](https://solid-adventure-l5ny946.pages.github.io/leading-change-collaboratively.html#distributed-leadership-theory)

I can. But if the intent is just to hide it because it's ugly, let's hold off as I'm working on the CSS for this on the dev site right now. 

> [ ] Please add article in Unit 3 - end of Topic 2
> [Click here](https://learn.twu.ca/pluginfile.php/1070285/mod_resource/content/1/LDRS502_U3_Grigsby.pdf) to read his short article discussing the differences between committees, task forces, and teams.

@kmarjanovic As stated above, all articles were embedded But my embed was removed by someone else. I wonder if you might have deleted my embeds? They were previously hidden on the week page, same as the book.

**Comment by kmarjanovic** [comment]
Unit 4 Topic 1 table:
Could we either change the format of the table in the Moodle book, or add an accordion to replace the table?
[Moodle books](https://learn.twu.ca/mod/book/view.php?id=867169&chapterid=6963)
[Bookdown](https://solid-adventure-l5ny946.pages.github.io/conflict-negotiation.html#types-of-conflict)

**Comment by kmarjanovic** [comment]
Oh no!  Sorry @Jeff-TWU !  I did delete the files as they were on the unit pages.  I had thought the files were linked elsewhere in the unit.

**Comment by Jeff-TWU** [comment]
> Oh no! Sorry @Jeff-TWU ! I did delete the files as they were on the unit pages. I had thought the files were linked elsewhere in the unit.

@kmarjanovic They were linked in the course, but they have to be linked from somewhere. They were hidden, so students wouldn't see them next to the associated books.

**Comment by kmarjanovic** [comment]
I see.  Sorry, I didn't realize.  In that case, a separate Resources tab might work.  I'd rather keep the Unit tabs clean so instructors aren't encouraged to add a zillion pdfs without context ;)  Let's confirm tomorrow

**Comment by Jeff-TWU** [comment]
> Unit 4 Topic 1 table:
> Could we either change the format of the table in the Moodle book, or add an accordion to replace the table?
> [Moodle books](https://learn.twu.ca/mod/book/view.php?id=867169&chapterid=6963)
> [Bookdown](https://solid-adventure-l5ny946.pages.github.io/conflict-negotiation.html#types-of-conflict)

@kmarjanovic This is on the Dev site. Would this style of table work for you?
![Screen Shot 2023-04-04 at 3 56 13 PM](https://user-images.githubusercontent.com/66963480/229940143-7ea8ea81-111c-4b94-9513-cec16f7c4441.png)

**Comment by kmarjanovic** [comment]
Yes, that's much more readable!  Thanks @Jeff-TWU !!

**Comment by Jeff-TWU** [comment]
Hi @barishgolland 

[Here is the updated CSS](https://www.dropbox.com/s/liesbase6xmygxr/20230405_Moodle_dev.css?dl=0) for Moodle Books that I would like to use on the live site. This does include previous CSS styles, so it should just overwrite all styles. Thanks!

**Comment by barishgolland** [comment]
@Jeff-TWU did you want me to add this to Moodle Dev or Prod? Is it in addition to or replacement of the Additional CSS we've already added?

**Comment by Jeff-TWU** [comment]
> @Jeff-TWU did you want me to add this to Moodle Dev or Prod? Is it in addition to or replacement of the Additional CSS we've already added?

@barishgolland I've already tested it in Dev. Could you add it to [Prod](https://learn.twu.ca/admin/settings.php?section=themesettinglearnr#theme_learnr_advanced) please?

**Comment by barishgolland** [comment]
It's uploaded in Prod now - please check and confirm. Thanks!

**Comment by Jeff-TWU** [comment]
> It's uploaded in Prod now - please check and confirm. Thanks!

@barishgolland It is alive! Thanks.
