### ISSUE TITLE
LDRS 371 for Production

### ISSUE THREAD

**Issue by Nataliadsanchez** [TWUOnline/bug-tracking#692]
### URL
[Moodle shell](https://learn.twu.ca/course/view.php?id=28207&section=1)
[Bookdown](https://ba-leadership.github.io/ldrs371)

### Instructions

- [x] Unit 1
- [x] Unit 2
- [x] Unit 3
- [x] Unit 4
- [x] Unit 5
- [x] Unit 6 - Chapter 11 audio file is incomplete
- [x] Assessment
- [ ] Facilitation Guide

[LDRS 371_U1.docx](https://github.com/TWUOnline/bug-tracking/files/13604620/LDRS.371_U1.docx)
[LDRS 371_U2.docx](https://github.com/TWUOnline/bug-tracking/files/13604623/LDRS.371_U2.docx)
[LDRS 371_U3.docx](https://github.com/TWUOnline/bug-tracking/files/13604625/LDRS.371_U3.docx)
[LDRS 371_U4.docx](https://github.com/TWUOnline/bug-tracking/files/13604627/LDRS.371_U4.docx)
[LDRS 371_U5.docx](https://github.com/TWUOnline/bug-tracking/files/13604632/LDRS.371_U5.docx)
[LDRS 371_U6.docx](https://github.com/TWUOnline/bug-tracking/files/13604633/LDRS.371_U6.docx)

**Comment by cmadland** [comment]
Moving this from Grav to [bookdown](https://github.com/BA-Leadership/ldrs371) @dgaudet48

**Comment by Jeff-TWU** [comment]
> ### LDRS 371
> ### URL
> Moodle shell: https://learn.twu.ca/course/view.php?id=28207&section=1 Bookddown: https://ba-leadership.github.io/ldrs371
> 
> ### Instructions
> * Please upload Unit 2 for LDRS 371
> 
> [Unit 2 .docx](https://github.com/TWUOnline/bug-tracking/files/10736308/Unit.2.docx)

@Nataliadsanchez I'm on it.

**Comment by Jeff-TWU** [comment]
@Nataliadsanchez U2 is up in both [Moodle](https://learn.twu.ca/mod/book/view.php?id=861432&chapterid=6682) and [Bookdown](https://upgraded-goggles-29kp6lz.pages.github.io/unit-2-please-add-title.html)

**Comment by Nataliadsanchez** [comment]
Thanks @Jeff-TWU!

**Comment by Nataliadsanchez** [comment]
Could you please upload Units 1-6? Thank you!

[Unit 1 - v_03.14.2023.docx](https://github.com/TWUOnline/bug-tracking/files/10974401/Unit.1.-.v_03.14.2023.docx)
[Unit 2 - v_03.14.2023.docx](https://github.com/TWUOnline/bug-tracking/files/10974403/Unit.2.-.v_03.14.2023.docx)
[Unit 3 - v_03.14.2023.docx](https://github.com/TWUOnline/bug-tracking/files/10974397/Unit.3.-.v_03.14.2023.docx)
[Unit 4 - v_03.14.2023.docx](https://github.com/TWUOnline/bug-tracking/files/10974398/Unit.4.-.v_03.14.2023.docx)
[Unit 5 - v_03.14.2023.docx](https://github.com/TWUOnline/bug-tracking/files/10974399/Unit.5.-.v_03.14.2023.docx)
[Unit 6 - v_03.14.2023.docx](https://github.com/TWUOnline/bug-tracking/files/10974400/Unit.6.-.v_03.14.2023.docx)

**Comment by Jeff-TWU** [comment]
@Nataliadsanchez [Updated](https://ba-leadership.github.io/ldrs371/a-title-for-unit-1.html).

@cmadland Side note: I was going to try and link to the specific episodes on Netflix. Turned on my VPN and "The Toys that Built America: Season 2" is not available in the UK (not on Netflix or even on Amazon Prime). I'm not sure how students would be able to watch this?

**Comment by Nataliadsanchez** [comment]
> @Nataliadsanchez [Updated with Accordions](https://ba-leadership.github.io/ldrs371/a-title-for-unit-1.html)
> 
> **Notes:**
> 
>     * Using a free Podbean account,  I am limited to uploading 3 chapter summaries (podcasts) per day. I'll do this over the next few days. Not all episodes will be up until Monday. First 3 chapter summaries are up (u1-u2)
> 
>     * The audio for [Chapter 11](https://www.dropbox.com/s/hm1akromruvdgtq/Project_Clayton-Christensen-The-Innovators-Dilemma-Chapter-11.mp3?dl=0) is incomplete. Phil needs to provide an updated file.

Thanks @Jeff-TWU!! I'll let Phil know about Chapter 11 and also about "The Toys that Built America: Season 2" not available in the UK.

**Comment by Jeff-TWU** [comment]
Hi @Nataliadsanchez I made most of the requested edits + the additional format changes per the meeting today.

- I'm not quite certain what you meant by "Please check subheadings for all Learning Activities." I went through all activities and confirmed they are level 4 headings. Is this what you meant?

- The sizing for [h5p activities](https://ba-leadership.github.io/ldrs371/a-title-for-unit-2.html#value-networks-and-the-impetus-to-innovate) is automatically set. I can change it, but this would affect all user screen sizes and could negatively impact visibility depending on the device. I can't recommend it. @cmadland Thoughts on this?

**Comment by Nataliadsanchez** [comment]
Thanks for the edits @Jeff-TWU!

- About the Learning activities subheadings, when I click on topics 2.1, 2.2, 2.4, 3.1, 3.2, and 3.4, they do not expand. 
- The H5P size, did you change it? It looks smaller now. I like it! 
- A new question: Will students have to sign in to watch the Doodle videos in MS Stream? or would it be more convenient for students to watch the Doodle videos on Vimeo?

**Comment by Nataliadsanchez** [comment]
> Hi @Nataliadsanchez I made most of the requested edits + the additional format changes per the meeting today.
> 
>     * I'm not quite certain what you meant by "Please check subheadings for all Learning Activities." I went through all activities and confirmed they are level 4 headings. Is this what you meant?
> 
>     * The sizing for [h5p activities](https://ba-leadership.github.io/ldrs371/a-title-for-unit-2.html#value-networks-and-the-impetus-to-innovate) is automatically set. I can change it, but this would affect all user screen sizes and could negatively impact visibility depending on the device. I can't recommend it. @cmadland Thoughts on this?

Thanks for the edits @Jeff-TWU!

- About the Learning activities subheadings, when I click on topics 2.1, 2.2, 2.4, 3.1, 3.2, and 3.4, they do not expand.
- The H5P size, did you change it? It looks smaller now. I like it!
- A new question: Will students have to sign in to watch the Doodle videos in MS Stream? or would it be more convenient for students to watch the Doodle videos on Vimeo?

**Comment by Jeff-TWU** [comment]
@Nataliadsanchez [Updated](https://ba-leadership.github.io/ldrs371/index.html). 

- Changed all activities from H4 to H3 (H4 will not appear expand in the sidebar). They will now expand in the sidebar. Multiple activities were previously under a "Learning Activities" H3 heading (which is what you were seeing expand in the sidebar). I removed the "Learning Activities" Headings. They felt redundant. 
- No, I didn't change anything with the H5p. It must be browser-side somehow? 
- You had mentioned that you were going to ask @cmadland  if the Doodle videos should go to Vimeo for open access. I'm assuming they are. I can move them if you like. Please confirm.

**Comment by Jeff-TWU** [comment]
@Nataliadsanchez [Updated with SME videos](https://ba-leadership.github.io/ldrs371/index.html).

**Comment by Nataliadsanchez** [comment]
[Welcome:](https://learn.twu.ca/course/view.php?id=28298&section=2#tabs-tree-start) **Remove** "Insert the course description here."

**UNIT 1**
- [ ] **Add unit title:** The Challenge of Disruptive Innovation
- [ ] **Add unit 1 summary**: 

In this first unit, you have had the opportunity to learn about various crucial aspects of innovation and its challenges within sustaining organizations.  Firstly, we explored the Innovator's Dilemma, shedding light on why disruptive innovation can be particularly difficult for established companies. Disruptive innovation, as another significant challenge, was discussed, emphasizing its potential to disrupt traditional markets. 

We also we explore the fascinating history of innovation in the toy industry throughout the past 120 years. Understanding the importance of adaptation and market sensitivity, we discovered that innovation revolves around improving products, services, and systems to cater to consumer needs effectively. The "jobs to be done theory" offered insights into how innovation aims to improve customers' lives by addressing their essential tasks and requirements. 

Lastly, we explored value networks and their significance for companies in embracing disruptive innovation, stressing the need to recognize and value future value networks. 

**UNIT 2**
- [ ] **Add unit title:** Why Great Companies Fail and Why Leaders Let Them Fail
- [ ] **Add unit 1 summary**: 


**UNIT 2**
- [ ] **Add unit title:** 
- [ ] **Add unit 1 summary**: 

**UNIT 2**
- [ ] **Add unit title:** 
- [ ] **Add unit 1 summary**: 

**UNIT 2**
- [ ] **Add unit title:** 
- [ ] **Add unit 1 summary**:

**Comment by Nataliadsanchez** [comment]
Hi @Jeff-TWU! Could you please work on the following edits for LDRS 371?

[Welcome:](https://learn.twu.ca/course/view.php?id=28298&section=2#tabs-tree-start) **Remove** "Insert the course description here."

**UNIT 1**
- [ ] **Add unit 1 title:** The Challenge of Disruptive Innovation
- [ ] **Add unit 1 summary**: 

In this first unit, you have had the opportunity to learn about various crucial aspects of innovation and its challenges within sustaining organizations. Firstly, we explored the Innovator's Dilemma, shedding light on why disruptive innovation can be particularly difficult for established companies. Disruptive innovation, as another significant challenge, was discussed, emphasizing its potential to disrupt traditional markets. 

We also we explore the fascinating history of innovation in the toy industry throughout the past 120 years. Understanding the importance of adaptation and market sensitivity, we discovered that innovation revolves around improving products, services, and systems to cater to consumer needs effectively. The "jobs to be done theory" offered insights into how innovation aims to improve customers' lives by addressing their essential tasks and requirements. 

Lastly, we explored value networks and their significance for companies in embracing disruptive innovation, stressing the need to recognize and value future value networks. 

**UNIT 2**
- [ ] **Add unit 2 title:** Why Great Companies Fail and Why Leaders Let Them Fail
- [ ] **Add unit 2 summary**: 

Throughout the second unit, you have had the opportunity to learn about the importance of value networks and the impetus to innovate. Next, you explored the transformative impact of video games on children, reshaping their leisure time and even how they think about the world. 

In this unit we also covered the crucial role of innovative thinking in the development of video games. Moreover, you discovered how global events, such as WW II, changed divergent industries such as the toy industry and how innovation played a critical role in this evolution. 

Additionally, in this unit we also discussed the role of disruptive innovation and technology in the mechanical excavator industry, and how this disruption altered how we build buildings, roads, and highways today. You also learned about the transformative power of single ideas, capable of changing entire industries. Lastly, we explored the challenges of being an “idea man” and retaining your intellectual capital while transforming an industry.


**UNIT 3**
- [ ] **Add unit 3 title:** The Opportunity of Disruptive Innovation
- [ ] **Add unit 3 summary**: 

In this third unit, you explored the evolution of the disk drive industry and how disruptive innovation, storage capacity, size and flexibility played a role in the market acceptance of various innovations in this industry. It emphasized the need to give responsibility for disruptive innovation to people who have customers who need those products. 

In this unit we also highlighted the role of “drive” in the passion and competitiveness of individual innovators like AC Gilbert who competed to win at the building block industry. We emphasized that despite facing competition, failure, struggles, disloyalty, and criticism, passion is essential for continuous innovation. Additionally, we also discussed the significance of seemingly simple innovations, like the locking mechanism in Lego blocks, and how they can transform niche products into global market successes. 

Examples of how outsiders can impact industries positively with new ideas and innovations, as was evidenced in the creation of Tetris, Jenga, and Rubik's Cube, were also reviewed. Finally, the unit underscored the criticality of placing control over disruptive innovation in the hands of those who comprehend and are passionate about the opportunities it presents.


**UNIT 4**
- [ ] **Add unit 4 title:** Managing Disruptive Technological Change
- [ ] **Add unit 4 summary**: 

In this fourth unit, you have had the opportunity to learn about how market segmentation can help organizations to recognize areas for future innovation. The importance of experimentation, failure, and project maps in the innovation process was emphasized, acknowledging their role in fostering growth. Additionally, we explored the "Chasm" that often exists between sustaining and disruptive innovation and the challenges that organizations face in trying to cross this chasm too quickly.

A compelling example of Christensen's value economics was also presented through the case of Cabbage Patch Kids. Moreover, in this unit we emphasized the core value of innovators as a “relentless pursuit of value” for customers.  This is the drive that leads innovators to decrease cost, increase simplification, and increase value of products services and systems. Lastly, we explored the difference between invention and innovation as exemplified in the Toy Industry.


**UNIT 5**
- [ ] **Add unit 5 title:** The Appraisal, Performance, Demand and Life-Cycle of Innovation
- [ ] **Add unit 5 summary**: 

In this fifth unit, you have had the opportunity to learn how to appraise an organizations capabilities and disabilities in order to understand where it might be vulnerable to disruptive innovation. We also examined the critical value of innovators within organizations in order to foster the future of the organization. Itis important to understand that innovators have much greater future value that non-innovators within an organizational context. 

Additionally, you also learned how to describe the value proposition of an organization of product, emphasizing the importance of framing it in customer terms rather than organizational terms. Moreover, you have had the opportunity to learn how to explain the interrelatedness of produce performance, market demand, product life-cycle and current pricing to understand whether a company or product is vulnerable to a future disruptive innovation.


**UNIT 6**
- [ ] **Add unit 6 title:** The Dilemmas and Case Studies for Disruptive Innovation
- [ ] **Add unit 6 summary**: 

In this final unit, you explored various cases where disruptive innovation has transformed industries. You also learned why quality is always defined in the mind of the customer and not in the continuous improvement processes of the organization which often produce perceived value that does not add customer value.
The interrelationship between customer-defined quality, value, price, and experience as well as the understanding of innovation, disruption, adaptation, and value from the customer's perspective, were essential key takeaways. Additionally, we examined the characteristics of disruptive change that might cause established companies to miss this threat of disruption. 

Finally, we explored the evolution of the game system industry and how game systems transformed the experience of children around the world.

**Comment by MeeksonHundoo** [comment]
Hello @Nataliadsanchez this has been updated. Here is the link: https://ba-leadership.github.io/ldrs371/
For the Activity Watch and Reflect: I've added the questions you've requested.. could you please check to see if that's how you wanted it?

**Comment by Nataliadsanchez** [comment]
Hi @MeeksonHundoo Could you please modify the instructions for **Activity: Read and Reflect** under the topic 5.2:  

Read Chapter 9 of _The Innovator’s Dilemma_ and take notes as you go. Pay attention to the main concepts and ideas presented by the author.

**Comment by Nataliadsanchez** [comment]
> Hello @Nataliadsanchez this has been updated. Here is the link: https://ba-leadership.github.io/ldrs371/ For the Activity Watch and Reflect: I've added the questions you've requested.. could you please check to see if that's how you wanted it?

Hi @MeeksonHundoo. I still cannot see the questions to consider for the **Activity: Watch and Reflect** in Unit 5. Could you please check it again?

**Comment by MeeksonHundoo** [comment]
Hello @Nataliadsanchez I've updated the instructions for the LA 5.2 Read and reflect. There is a questions to consider tab header with no questions under it? Do you have the questions for it? or am I supposed to remove it?

Also, the questions have already been added to the activity Watch and Reflect as shown below:

![image](https://github.com/TWUOnline/bug-tracking/assets/98780625/ae04b647-8e32-4f93-9462-8f7dd12e3a0a)

**Comment by Nataliadsanchez** [comment]
I am sorry for the confusion @MeeksonHundoo Those 4 questions go under **Activity: Read and Reflect.** Please remove them from the Activity: Watch and Reflect

**Comment by MeeksonHundoo** [comment]
No Worries @Nataliadsanchez it's done.

**Comment by Nataliadsanchez** [comment]
@chloecwh could you please also make sure the content for this course is in the latest Bookdown template? Thanks!

**Comment by chloecwh** [comment]
updated CSS! I noticed the Reference page is empty, is there anything I can add to it? @Nataliadsanchez 
<img width="1100" alt="Screenshot 2023-11-30 at 4 38 14 PM" src="https://github.com/TWUOnline/bug-tracking/assets/150065592/c5b964a3-5bb3-483b-b65b-46f75e330cb0">

**Comment by kmarjanovic** [comment]
@meher-ahmed, most of our courses don't have a references section.  Please hide by default unless the ID gives content for that area.
Please see git issue re: this topic: https://github.com/TWUOnline/bug-tracking/issues/952

Thank you! :)

**Comment by Nataliadsanchez** [comment]
@chloecwh could you please add the assessment part in each unit? I have attached the most recent files

**Comment by chloecwh** [comment]
@Nataliadsanchez done!

**Comment by Nataliadsanchez** [comment]
@chloecwh could you please remove the following note under assessment in U6?: 
_Phil, could you please complete information pertaining to the final exam?_

**Comment by chloecwh** [comment]
@Nataliadsanchez done https://ba-leadership.github.io/ldrs371/the-dilemmas-and-case-studies-for-disruptive-innovation.html#assessment-5
