### ISSUE TITLE
WRSH 301 Graphics

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#694]
**What course/project is this request for?**
WRSH 301

**Describe the request**
Please create a graphic of the following:

The 4 C's of Effective, Reciprocal Leadership
1.	Character (generates trust on the part of followers).
2.	Conviction  (helps the congregation discern its purpose and vision).
3.	Competency (helps the congregation function as a healthy system—i.e., deal with the normal anxieties and conflicts of communal life in healthy and productive ways).
4.	Confluence (of the leader, congregation, time, place, ministry opportunity, and resources that is a gift of God’s Spirit and that enables a leader and congregation to work joyfully together in realizing God’s purposes.

*I realize the last ones are wordy...I'll check with the SME and send edits on Friday)

**Additional context**
Full text from SME - for context
“What are the positive things we can expect to see in situations where there is effective, reciprocal leadership?
Four factors (the four “Cs  ”) seem ever-present in situations of effective leadership: 
1.	Character in the leader (which generates trust on the part of followers).
2.	Conviction in the leader (which helps the congregation discern its purpose and vision).
3.	Competencies in the leader (which help a congregation function as a healthy system—i.e., deal with the normal anxieties and conflicts of communal life in healthy and productive ways).
4.	Confluence of leader, congregation, time, place, ministry opportunity, and resources that is a gift of God’s Spirit and that enables a leader and congregation to work joyfully together in realizing God’s purposes.
Three important clarifications must be made before expanding upon each of these factors.
First, notice how all four of these factors involve both leader and congregation, the relationship between them, and the impact they have on one another. For example, character in a congregation’s leaders helps the congregation trust those leaders, which in turn strengthens the character of the congregation, which in turn helps the leaders trust the congregation. Praise God for such an upward spiral of character and trust!
Second, it’s important to distinguish between personality traits and character traits. The focus in these four factors is not on personality—introvert, extrovert, charismatic, quiet—but on the character   of the leaders and those being led. Put another way, a church can be healthy with a leader who’s an introvert, but not with a leader who is untrustworthy, arrogant, or sexually promiscuous.
Third, these four factors can be applied to diverse cultural situations. Each cultural situation will define these factors according to norms appropriate to that culture. But these four factors reflect certain realities of human behavior and community that are present and must be reckoned with across all cultural differences.” Effective Leadership, 20. 

**Priority**
Use the label to add the priority**

**Comment by Jeff-TWU** [comment]
@kmarjanovic I'm on it.

**Comment by Jeff-TWU** [comment]
@kmarjanovic I'm not done, but wanted to make sure the idea is working before I carry on. Feedback please.
![Untitled-1](https://user-images.githubusercontent.com/66963480/219502208-09312616-7da1-458d-9722-a88137c72870.png)

**Comment by kmarjanovic** [comment]
This looks great! I'll pass it along to Joan to check for edits. Thanks Jeff!!

**Comment by Jeff-TWU** [comment]
> This looks great! I'll pass it along to Joan to check for edits. Thanks Jeff!!

@kmarjanovic I have a bit more I want to do with it, but want to make sure the imagery is working first.

**Comment by kmarjanovic** [comment]
Hi Jeff,
Just coming back to this...
Could we take out reciprocal in the title?

Competency - helps a congregation function as a healthy system  (take out examples)
Confluence - please take out "that is a gift of God's Spirit"

This is a low priority item (Sept/Oct is fine)

**Comment by Jeff-TWU** [comment]
@kmarjanovic Updated.
![20230216_WRSH 301 Graphic](https://github.com/TWUOnline/bug-tracking/assets/66963480/05e98b43-da9a-432b-be59-f10000a7e636)

**Comment by kmarjanovic** [comment]
Thank you @Jeff-TWU !
