### ISSUE TITLE
Psyc 339 Summer '23

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#695]
**Which course contains the bug?**  
- PSYC 339 OL SU2023 
 
 
**Describe the error and/or your suggestion**  
There is no link to the syllabus in this section: 
The syllabus includes key information about the course schedule, assignments, and policies. Please read the full course syllabus [here] I have attached the syllabus that can be uploaded to that link. 

 This section needs to be adjusted: 

REQUIRED TEXTS AND MATERIALS:			 

In the Realm of Hungry Ghosts by Gabor Mate  

Emotionally Focused Family Therapy by Adele LaFrance

This graph needs to be changed as well: 
<div class="OutlineElement Ltr SCXW6408654 BCX0" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; overflow: visible; cursor: text; clear: both; position: relative; direction: ltr; color: rgb(0, 0, 0); font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web&quot;, Arial, Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p class="Paragraph SCXW6408654 BCX0" xml:lang="EN-US" lang="EN-US" paraid="2031862362" paraeid="{6f95c000-9632-4689-8ed7-a42a5b07301b}{215}" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; overflow-wrap: break-word; white-space: pre-wrap; font-weight: normal; font-style: normal; vertical-align: baseline; font-kerning: none; background-color: transparent; color: windowtext; text-align: left; text-indent: 0px;"><span data-contrast="auto" xml:lang="EN-US" lang="EN-US" class="TextRun SCXW6408654 BCX0" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; font-variant-ligatures: none !important; font-size: 11pt; line-height: 18.3458px; font-family: Calibri, Calibri_EmbeddedFont, Calibri_MSFontService, sans-serif;"><span class="NormalTextRun SCXW6408654 BCX0" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent;">COURSE EVALUATION</span></span><span class="EOP SCXW6408654 BCX0" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; font-size: 11pt; line-height: 18.3458px; font-family: Calibri, Calibri_EmbeddedFont, Calibri_MSFontService, sans-serif;"> </span></p></div><div class="OutlineElement Ltr SCXW6408654 BCX0" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; overflow: visible; cursor: text; clear: both; position: relative; direction: ltr; color: rgb(0, 0, 0); font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web&quot;, Arial, Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="TableContainerV2 Ltr SCXW6408654 BCX0" style="margin: 2px 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; overflow: visible; position: relative; display: flex; justify-content: flex-start;"><div id="{6bfce741-7c5b-42cd-a0b7-deffa4a976ce}{55}" class="WACAltTextDescribedBy SCXW6408654 BCX0" aria-hidden="true" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; position: absolute; visibility: hidden; z-index: -100;"></div>

Assignment | Activity | Value | Due
-- | -- | -- | --
Research Paper | Pick a topic and research | 35% | A week after the last class
Forum Discussion Participation | Each session participation | 25% | Each Unit
Oral Presentation | Pre-recorded presentations | 20% | Unit 5
Case Conceptualizations | Report | 20% | Dependent on which Cases chosen

</div></div>
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112#section-0
2. Unit #  Course Overview section      Topic #   NA      Activity# NA 
 
**Optional: Screenshots**  
[PSYCH 339 SU 23 VERSEVELDT.pdf](https://github.com/TWUOnline/bug-tracking/files/10737338/PSYCH.339.SU.23.VERSEVELDT.pdf)

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse These edits have been incorporated. Here is the link to your course:
https://learn.twu.ca/course/view.php?id=28112
