### ISSUE TITLE
Instructor welcome video

### ISSUE THREAD

**Issue by JulietTeeter** [TWUOnline/bug-tracking#697]
**Which course contains the bug?**  
Psych 354OL Brain and Behaviour 
 
**Describe the error and/or your suggestion**  
Can you remove the 'info' from the instructor video where it shows views and likes etc. 
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL: https://learn.twu.ca/course/view.php?id=27104
2. Unit #   Course intro      Topic #   na      Activity#  na
 
**Optional: Screenshots**  
<img width="441" alt="Screen Shot 2023-02-16 at 5 59 39 AM" src="https://user-images.githubusercontent.com/125574908/219385028-4110a0d6-67bf-4b8a-bd53-212c0130732d.png">

**Comment by Jeff-TWU** [comment]
@kmarjanovic Fixed. This is a limitation with MS Stream. I moved the video over to Vimeo.

**Comment by JulietTeeter** [comment]
Thank so much!


Juliet Teeter, MA

Part time instructor of Psychology

Trinity Western University




________________________________
