### ISSUE TITLE
LDRS 500 interactive competency graph

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#7]
**Which course contains the bug?**
LDRS 550 FAR MASTER

**Describe the error or your suggestion**
Make interactive competency graph. 
See email.  Colin  started in H5P…
 
https://create.twu.ca/h5p/leadership-competencies-graphic/

**Location of the bug**
Unit 1 Overview

**Comment by rezakh66** [comment]
@kmarjanovic Hi Kelly,
I have completed this graph based on the Leadership Competency Framework.docx. we only can have Text, Image and Video format contents in this H5P activity. I have added an example image in team leadership module to see how it will look like when inserting image and text simultaneously.

**Comment by kmarjanovic** [comment]
Hi @rezakh66 ,
Thanks so much!  I made a couple edits, so it's good to go!
I see above it says LDRS 550, but it should be LDRS 500.  
Could you delete it from 550 if you put it in there?  
Please add to 500: https://learn.twu.ca/course/view.php?id=10719&section=1
Unit 1 Overview.

**Comment by rezakh66** [comment]
@kmarjanovic Hi, I have added this to LDRS500. LDRS550 does not exist though to be worry about.

**Comment by kmarjanovic** [comment]
Thank you!
