### ISSUE TITLE
Production - LDRS 303 tabs

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#70]
### Course 
LDRS 303

### URL
https://learn.twu.ca/course/view.php?id=10748&section=4
### Instructions
Units 4, 7-10 don't have the tabs to the side to navigate through the lesson.
Please add.

**Comment by rezakh66** [comment]
@cmadland can you please help on this. that's Grav.

**Comment by kmarjanovic** [comment]
Unit 8 still needs tabs please @cmadland

**Comment by kmarjanovic** [comment]
@cmadland can we please fix Unit 8 (I'm not sure how to do this)

**Comment by rezakh66** [comment]
@kmarjanovic Colin helped to fix this issue.

**Comment by kmarjanovic** [comment]
Thank you!
