### ISSUE TITLE
Adjusting amount of terms needed to be defined. 

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#700]
**Which course contains the bug?**  
- PSYC 339 OL SU2023 
 
 
**Describe the error and/or your suggestion**  
Taking away some of the terms that need to be defined. 
Eliminate: 
#1 Interpersonal trauma
#8 Historical Trauma
#14 Hyperarousal
#15 Hypoarousal
#16 Parasympathetic Nervous System
#19 Window of Engagement
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=2#tabs-tree-start
2. Unit #1         Topic # 1        Activity#  1.5
 
**Optional: Screenshots**

**Comment by Jeff-TWU** [comment]
@cmadland @kmarjanovic @emilyverse Completed.
