### ISSUE TITLE
Unit 2 adjustments

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#701]
**Which course contains the bug?**  
- PSYC 339 OL SU2023
 
 
**Describe the error and/or your suggestion**  
Eliminate some of the questions to consider in Activity 1.6:
Eliminate questions: #1, #4, #5, #9, #13

Activity 1.8- include the label Optional Reading. So the title would look like this: 
              Activity 1.8 Optional Website Reading | The Effects of Complex Trauma on Brain Development

Activity 1.9- include the label Optional Reading. So the title would look like this: 
               Activity 1.9 Optional Reading | Treating Adult Survivors of Childhood Emotional Abuse and Neglect

 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=2#tabs-tree-start 
2. Unit # 1        Topic # 2        Activity#  1.6, 1.8 & 1.9
 
**Optional: Screenshots**

**Comment by Jeff-TWU** [comment]
@cmadland @kmarjanovic @emilyverse Completed.
