### ISSUE TITLE
Broken link in ENGL 101 GX

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#703]
**Which course contains the bug?**  
ENGL 101 GX 
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.

Could you replace broken link in ENGL 101 GX. with this new link? [https://libguides.twu.ca/c.php?g=284747&p=1897344#s-lg-box-5804023](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Flibguides.twu.ca%2Fc.php%3Fg%3D284747%26p%3D1897344%23s-lg-box-5804023&data=05%7C01%7CKelly.Marjanovic%40twu.ca%7C0253d46d905947fa876908db18feb01d%7C2b4ef155167343efa480230c3d483f16%7C0%7C0%7C638131254369194168%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=qChMrfJBAj%2FeLKdC1t0QqoCG%2F8ZC%2Bup00Ene4lNsL%2FE%3D&reserved=0) 

The broken link is here: [https://learn.twu.ca/course/view.php?id=15705&section=8#tabs-tree-start](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.twu.ca%2Fcourse%2Fview.php%3Fid%3D15705%26section%3D8%23tabs-tree-start&data=05%7C01%7CKelly.Marjanovic%40twu.ca%7C0253d46d905947fa876908db18feb01d%7C2b4ef155167343efa480230c3d483f16%7C0%7C0%7C638131254369350404%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=2pQU3tcVuuoWZfCaj7UqK%2F%2F0yD0eL812Oj8OmwucjEY%3D&reserved=0) 

 
<img width="549" alt="engl 101 broken link" src="https://user-images.githubusercontent.com/35148983/221689593-cbd603ec-f594-4dde-a6bb-89f8bef02fb7.png">

**Comment by MeeksonHundoo** [comment]
Hello @kmarjanovic the link has been updated now.
