### ISSUE TITLE
Activity Changes 

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#704]
**Which course contains the bug?**  
- PSYC 339 OL SU 2023
 
 
**Describe the error and/or your suggestion**  
Change the title of Activity 1:10|Reading|Treating Adult Survivors of Childhood Emotional Abuse and Neglect-Page 12-16 to: 
          Activity 1.10|Optional Reading| Treating Adult Survivors of Childhood Emotional Abuse and Neglect Article
Change the description of Activity 1.10 from: Continue the literature in this section that discusses emotional abuse/neglect and psychological trauma. Also complement your reading with the following article. [Treating Adult Survivors of Childhood Emotional Abuse and Neglect](https://complextrauma.org/wp-content/uploads/2019/01/Adult-Treatment-2-Joseph-Spinazzola.pdf)
to: 
           Read the following article for a description on a New Framework for treating childhood emotional abuse and neglect. This article will be describing Component Based Psychotherapy. This is not essential for you to know as we will be focussing on learning Emotionally Focused Family Therapy in our time together, but if you are interested in working with Trauma or have been, I would recommend reading this article. [Treating Adult Survivors of Childhood Emotional Abuse and Neglect](https://complextrauma.org/wp-content/uploads/2019/01/Adult-Treatment-2-Joseph-Spinazzola.pdf)

Change the title of Activity 1.11|Reading | Complex Trauma and the Christian Context to: 
             Activity 1.11|Optional Reading | Complex Trauma and the Christian Context

Change the title of Activity 1.13| Explore | Trauma Informed therapies to:
              Activity 1.13| Optional Exploration | Trauma Informed therapies
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=2#tabs-tree-start
2. Unit # 1        Topic # 3        Activity# 1.10, 1.11, 1.13  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse these edits have been made
