### ISSUE TITLE
Eliminate some of the questions. 

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#705]
**Which course contains the bug?**  
- PSYC 339 OL SU 2023
 
 
**Describe the error and/or your suggestion**  
Activity 2.1 
Questions to Consider: 
Delete question # 5, 6, 12, 13, 14, 15, 16, 17
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=3#tabs-tree-start
2. Unit # 2        Topic # 1        Activity#  2.1
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse these questions have been removed
