### ISSUE TITLE
LDRS 623 broken links

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#706]
**Which course contains the bug?**  
LDRS 623([https://learn.twu.ca/course/view.php?id=26301&section=1_](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.twu.ca%2Fcourse%2Fview.php%3Fid%3D26301%26section%3D1_&data=05%7C01%7CKelly.Marjanovic%40twu.ca%7C5d215f1bca57485b9f5408db1ad8281f%7C2b4ef155167343efa480230c3d483f16%7C0%7C0%7C638133287912795601%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=jRgBQgtCJ1ZjOrlp%2Fi7l1pk51rlal5VgW%2Fq%2FX37RUnA%3D&reserved=0) ) 
For Unit 1, Activity 1.3 The links to What Project based learning looks like in….. The links don’t work.  The new links are:

1.	What Project based learning looks like in An Elementary Classroom
[https://www.ajjuliani.com/blog/what-project-based-learning-looks-like-in-an-elementary-classroom?rq=elem](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.ajjuliani.com%2Fblog%2Fwhat-project-based-learning-looks-like-in-an-elementary-classroom%3Frq%3Delem&data=05%7C01%7CKelly.Marjanovic%40twu.ca%7C5d215f1bca57485b9f5408db1ad8281f%7C2b4ef155167343efa480230c3d483f16%7C0%7C0%7C638133287912795601%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=6eE7i0J23Z7xk9mPo1n9BwB%2Fdr0FMHzXtEkZ30GXBKs%3D&reserved=0) 

2.	What Project based learning looks like in An Middle School Classroom
[https://www.ajjuliani.com/blog/what-project-based-learning-looks-like-in-a-middle-school-classroom?rq=Middle](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.ajjuliani.com%2Fblog%2Fwhat-project-based-learning-looks-like-in-a-middle-school-classroom%3Frq%3DMiddle&data=05%7C01%7CKelly.Marjanovic%40twu.ca%7C5d215f1bca57485b9f5408db1ad8281f%7C2b4ef155167343efa480230c3d483f16%7C0%7C0%7C638133287912795601%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=FkelVCmMK1peAjsXx0wu4Mq9dqWz2wLUuq4W9GjUYdc%3D&reserved=0) 
3.	What Project based learning looks like in An High School Classroom
[https://www.ajjuliani.com/blog/what-project-based-learning-looks-like-in-a-high-school-classroom](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.ajjuliani.com%2Fblog%2Fwhat-project-based-learning-looks-like-in-a-high-school-classroom&data=05%7C01%7CKelly.Marjanovic%40twu.ca%7C5d215f1bca57485b9f5408db1ad8281f%7C2b4ef155167343efa480230c3d483f16%7C0%7C0%7C638133287912795601%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YgFazY%2BabhRLH6iVPwiVEI%2FlPXPtLw59tKeAuhmUoBE%3D&reserved=0)

**Comment by MeeksonHundoo** [comment]
Hello @kmarjanovic i've updated these links

**Comment by kmarjanovic** [comment]
Thank you @MeeksonHundoo !  Have a great weekend :)
