### ISSUE TITLE
Topic 2 adjustments

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#707]
**Which course contains the bug?**  
PSYC 339 OL SU 2023
 
 
**Describe the error and/or your suggestion**  
Activity 2.6: 
Replace this paragraph: 
In this section, we will explore the reasons and mechanisms behind addiction. You will continue reading In the Realm of Hungry Ghosts through Chapter 19 in order to gain further insight into addiction and how it manifests in the brain for this activity.

It has been emphasized to you earlier that you should review the readings and the texts again. For learning to take place, repetition is essential.

WITH: 

In this section, we will explore the reasons and mechanisms behind addiction. You will continue reading In the Realm of Hungry Ghosts through Chapter 19 in order to gain further insight into addiction and how it manifests in the brain for this activity. You have already read chapters 17 & 18 during the last unit. You can take this opportunity to review the information or just read Chapter 19 if you feel like you have a good handle on the information. 

Replace the title: 
Activity 2.7: Website | Brain Imaging with Dr. Amen
with 
Activity 2.7: Optional Website Exploration | Brain Imaging with Dr. Amen
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=3#tabs-tree-start
2. Unit # 2        Topic # 2        Activity#  2.6 & 2.7
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse  this has been updated
