### ISSUE TITLE
Adjust Paragraph

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#708]
**Which course contains the bug?**  
PSYC 339 OL SU 2023
 
 
**Describe the error and/or your suggestion**  
Activity 2.1: 
Change the paragraph from this: 
Read pages 1-3, & Chapters 11-16. In the Realm of Hungry Ghosts, Gabor Mate's entire book, is one of the most important and valuable books one can read. For the sake of time available for this course, it is recommended that you complete specific readings. It is strongly recommended that you follow along with the questions provided below as they are quite substantial in and of themselves. As a result, you will be able to retain more information.

Additionally, before you read this chapter, take a moment to consider your own definition of addictions and what automatic thoughts or assumptions you have about people struggling with addictions.

To this: 

Read pages 1-3, & Chapters 11-16. In the Realm of Hungry Ghosts, Gabor Mate's entire book, is a very important and valuable book. For the sake of time available for this course, it is recommended that you complete specific readings. It is strongly recommended that you follow along with the questions provided below as the chapters are quite substantial in and of themselves. As a result, you will be able to retain more information.

Additionally, before you read this chapter, take a moment to consider your own definition of addictions and what automatic thoughts or assumptions you have about people struggling with addictions.
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=3#tabs-tree-start
2. Unit #   2      Topic #   1      Activity#  2.1
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse  this has been updated
