### ISSUE TITLE
Adjustment of title 

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#709]
**Which course contains the bug?**  
PSYC 339 OL SU 2023
 
 
**Describe the error and/or your suggestion**  
Change the title from: 
Activity 2.4: Reading | A Biblical Reflection 
to: 
Activity 2.4: Optional Reading | A Biblical Reflection
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=3#tabs-tree-start
2. Unit #2         Topic # 1        Activity#  2.4
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse  this has been updated
