### ISSUE TITLE
Editing Request - Missing PPTs in LDRS 300 IF Unit 3

### ISSUE THREAD

**Issue by BLMSasaki** [TWUOnline/bug-tracking#71]
### Course

LDRS 300 IF  Unit 3

Before starting on an editing project, please connect with the Instructional Designer to go over specific requests for the course.

### Copy Editing
- [ ] Editing for grammar, usage, spelling, punctuation, and other mechanics of style checking for consistency of mechanics. 
- [ ] Check heading levels.
  - [ ] # Unit; ## Overview
  - [ **X] ### Learning Activities; ### Activity 1.1

Unit 3 --  Missing Powerpoint 3.1 for Topic 1 & Powerpoint 3.3 for Topic 3**

  - [ ] ##Assessment; ###Assignment 1; #### Grading Rubric
- [ ] Format tables, figures, and lists.
- [ ] Canadianizing (spelling).
- [ ] Edit for citation style consistent with the subject area.  
- [ ] Edit for consistent structure and basic formatting.
- [ ] Check all links (to web or docs). Flag broken links.  Ensure correct title and minutes are listed.
- [ ] Check that all images/tables have a description/caption.

### Specifics
- [ ] Unit Overview:
  - [ ] Topics are consistent with unit topics
  - [ ] Topics are numbered
  - [ ] Learning outcomes are bulleted; Capitalize the first letter and have a period.
- [ ] Format Activity Checklists – use alert plugin.

### Making Recommendations (Check with Instructional Designer)
- [ ] Make recommendations to ensure that the existing wording of the course content is appropriate for learners of diverse cultural backgrounds, e.g. the language is culturally sensitive.
- [ ] Clarifying meaning, eliminating jargon, polishing language, and other non-mechanical line-by-line editing, 

### Track Changes  
- [ ] On word documents, Track Changes should be used unless requested otherwise.
- [ ] On Github, make a pull request, detailing the changes/questions.

**Comment by cmadland** [comment]
done
