### ISSUE TITLE
Changes to topic #3

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#710]
**Which course contains the bug?**  
PSYC 339 OL SU 2023
 
 
**Describe the error and/or your suggestion**  
Introduction Paragraph:
Change from:
For anyone considering a placement, volunteer position, or employment in the addiction field, there are certain aspects that are valuable. There can be difficulty in recognizing, explaining, and managing emotions. It may be difficult for individuals who have been affected by addiction for a considerable amount of time to determine moral leanings, personal boundaries, and what kinds of behaviors and styles are purely natural, rather than simply performative and survival-based. Public policy and literature are increasingly recognizing that addiction is a maladaptive response to trauma. It is estimated that approximately two-thirds of those seeking treatment for alcohol and substance abuse issues have been affected by trauma. There is no doubt that addiction is extremely difficult to navigate and overcome, and not everyone is able to succeed for long periods of time.

Addictions are a complex issue that can be addressed with many theories and models, but EFFT remains the main approach/theory that will be discussed in this unit. During the following Learning activities you will learn about Gabor Mate’s insights into the healing process and what he calls ‘Compassionate Inquiry’ which pairs nicely with EFFT. Through Compassionate Inquiry, the client gains an understanding of how the unconscious dynamics in their lives can be released.

to:

It may be difficult for individuals who have been affected by addiction for a considerable amount of time to determine moral leanings, personal boundaries, and what kinds of behaviors are normative, rather than simply performative and survival-based. Public policy and literature are increasingly recognizing that addiction is a maladaptive response to trauma. It is estimated that approximately two-thirds of those seeking treatment for alcohol and substance abuse issues have been affected by trauma. There is no doubt that addiction is extremely difficult to navigate and overcome, and not everyone is able to succeed for long periods of time.

Addiction is a complex issue that can be addressed with many theories and models, but EFFT remains the main approach/theory that will be discussed in this unit. During the following Learning activities you will learn about Gabor Mate’s insights into the healing process and what he calls ‘Compassionate Inquiry’ which pairs nicely with EFFT. Through Compassionate Inquiry, the client gains an understanding of how the unconscious dynamics in their lives can be released.

Activity #2.11
Change the title from: 
Activity 2.11: Reflect | Looking back
to
Activity 2.11: Optional Reflection | Looking back
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=3#tabs-tree-start
2. Unit #  2       Topic #  3       Activity#  Intro & Activity #2.11
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse this has been updated
