### ISSUE TITLE
Adjustments to Activit 3.3

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#712]
**Which course contains the bug?**  
PSYC 339 OL SU 2023
 
 
**Describe the error and/or your suggestion**  
1. Change the title of Activity 3.3: Read | 'Experiencing Grief' by H. Norman Wright
to
Activity 3.3: Optional Read | 'Experiencing Grief' by H. Norman Wright

2. Change the paragraph description from this: 

Wright describes grief from what seems to me like an inner monologue of his own experiences and wrestlings mixed in with his readings. There are some good descriptions and metaphors in here that may help you connect to the information in a different way. This is also an opportunity to read this little book and decide whether or not you feel like this would be a good resource to pass on. As Timothy Keller talks about in his book “Walking with God through Pain and Suffering,” each person’s experience of grief is so unique that we have to keep in mind that what may work for one person, may not work for another and in fact can even have the potential to make it worse. However, this does not imply that you should not pass on resources, but rather that you should be very careful about who and why you pass on resources.

In contrast to our previous readings from Elisabeth Kubler Ross, this one focuses on grieving from the perspective of a bereaved individual.

to this: 

In order to complete this optional reading, you will need to purchase the book, "Experiencing Grief" by N.T. Wright. This is not a required text, however the read may be valuable to you if you are interested in working in the area of grief or if you have experienced grief yourself. Again, this is an optional read and the text does not have to be purchased, nor does the reading have to be completed. 

Wright describes grief from what seems to me like an inner monologue of his own experiences and wrestlings mixed in with his readings. There are some good descriptions and metaphors in here that may help you connect to the information in a different way. This is also an opportunity to read this little book and decide whether or not you feel like this would be a good resource to pass on. As Timothy Keller talks about in his book “Walking with God through Pain and Suffering,” each person’s experience of grief is so unique that we have to keep in mind that what may work for one person, may not work for another and in fact can even have the potential to make it worse. However, this does not imply that you should not pass on resources, but rather that you should be very careful about who and why you pass on resources.

In contrast to our previous readings from Elisabeth Kubler Ross, this one focuses on grieving from the perspective of a bereaved individual.
 
 
3. Change the Questions section to a non fillable version and include only the following questions: 

Questions to Consider: 
1.Why is the imagery that grief is like waves of an ocean so applicable?
2.What are the multitude of emotions involved in the grief process?
3.What types of losses tend not to be understood or acknowledged?
4.Why is it important to cry?
5.What puts you at risk for complicated grieving?
6.What are the four signs of recovery? How long would it typically take to appear?

**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=4#tabs-tree-start
2. Unit # 3        Topic # 1        Activity#  3.3
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse these edits have been made
