### ISSUE TITLE
Please add a ta

### ISSUE THREAD

**Issue by JulietTeeter** [TWUOnline/bug-tracking#715]
**Which course contains the bug?**  
-PSYC 354 02
 
 
**Describe the error and/or your suggestion**  
My ta can't access the course. 
I have added her gmail (kenz11laird@gmail.com) but it doesn't seem to allow her acess
Can you add her old TWU account or have another suggestion? it is mackenzie.laird@twu.ca

 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  
2. Unit #         Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
@cmadland could you please help with this issue?

**Comment by MeeksonHundoo** [comment]
Hello @JulietTeeter & @kmarjanovic  Mackenzie Laird is already added as a TA in your course. Please see below:
![image](https://user-images.githubusercontent.com/98780625/223507525-d4edd2a1-2a04-4c87-908f-c70c3c4524d2.png)

**Comment by kmarjanovic** [comment]
Thank you @MeeksonHundoo !

**Comment by JulietTeeter** [comment]
Hi! I added her but she isn't able to access the course. It doesn't show up in her courses when she logs in.


Juliet Teeter, MA

Part time instructor of Psychology

Trinity Western University




________________________________

**Comment by kmarjanovic** [comment]
Hi @JulietTeeter !  Has this issue been resolved?
