### ISSUE TITLE
Activity 3.9 Adjustment

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#717]
**Which course contains the bug?**  
PSYC 339 OL SU 2023
 
 
**Describe the error and/or your suggestion**  
Change the Questions section to a non fillable list of questions. Change the title of the question section to Questions to consider. Two questions are also eliminated. It will now look like this: 

Questions to Consider
1. What is a preventative factor for the development of complex grief?
2. What do bereavement practices intend to do?
3. What are the common themes across religious practices that Goodwyn has developed?
4. What is the role of the counselor?
5. What are the two considerations highlighted for further research?
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=4#tabs-tree-start
6. Unit #  3       Topic # 3        Activity#  3.9
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse these edits have been made
