### ISSUE TITLE
Activity 3.10 Adjustments

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#718]
**Which course contains the bug?**  
PSYC 339 OL SU 2023
 
 
**Describe the error and/or your suggestion**  
Change the Questions section to a non-fillable list of questions. Change the name of the questions section to "Questions to Consider." Four questions are now eliminated. It should now look like this: 

Questions to Consider
1. What are three things conditioned responses are based on?  
2. Describe what a block is.
3. What is block work?
4. What is the main paralyzing emotion that fuels blocks in caregivers?
5. When is caregiver resentment most likely to surface?
6. Describe what the authors mean by the ‘wisdom’ in the blocks? What does it help us do?
7. What is the tree metaphor?
8. Name some of the self-assessment tools.
9. What is the benefit of ‘speaking into the void?’
10. What are some other techniques they list that can regulate emotions in a caregiver?
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=4#tabs-tree-start
15. Unit #  3       Topic #  3      Activity#  3.10 
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse these edits have been made
