### ISSUE TITLE
Adjustments to Activity 3.11 part A

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#719]
**Which course contains the bug?**  
PSYC 339 OL SU 2023
 
**Describe the error and/or your suggestion**  
1. Change the title of the activity from: 
Activity 3.11: Read | “Walking with God through Pain and Suffering” by Timothy Keller - Chapter 11
to this: 
Activity 3.11: Optional Reading | “Walking with God through Pain and Suffering” by Timothy Keller

2. At the end of the following paragraph, add the next phrase and link to the text (in bold writing). 
The book written by Timothy Keller is an excellent resource for those interested in learning more about theology of suffering and pain. The only section that pertains to our topic today will be read. Despite the fact that he is primarily discussing pain and suffering, his words are applicable to our discussion on grief, loss, and death, as they are also engulfed in worlds of pain and suffering.
**Please read Chapter 11 which you can find here.** 
[Timothy Keller Ch.11.pdf](https://github.com/TWUOnline/bug-tracking/files/10906065/Timothy.Keller.Ch.11.pdf)

3. Please change the list of questions to a non-fillable list. Change the title of the questions section to "Questions to Consider." One of the questions has been eliminated.  It should now look like this: 

Questions to Consider:
1. What is the main metaphor describing how to experience pain and suffering and what is the idea behind it?
2. What is the difference between being in the fire versus having the fire within yourself?
3. What is the metaphor of the mixed gold?
4. What is the paradoxical balance of confidence and humility in the response of Shadrach, Meschach and Abednego?
5. We have been exploring how experiencing pain, loss, death, and suffering change you and open us up to access a deeper place within, how does Tim Keller expand on this discussion?
6. How does Tim Keller frame ‘the furnace’? How does he recommend viewing being in the furnace?

 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=4#tabs-tree-start
7. Unit # 3        Topic #  3       Activity#  3.11
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse these edits have been made
