### ISSUE TITLE
Adjustments to Activity 3.11 part B

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#720]
**Which course contains the bug?**  
PSYC 339 OL SU 2023
 
 
**Describe the error and/or your suggestion**  

1. After the first section (the Chapter 11 section) of this activity, there is a bold title that says **Read Chapter 12: Weeping**. This is followed by the following text: 
We can apply the concepts from this chapter to all of our units so far as well as our units to come. As scripture tells us, there is a time for everything; a time for weeping and despair is included in this and Tim Keller expands on the importance of weeping for healthy emotional development as well as a means for drawing us closer to God.

Please add the following phrase and link after this paragraph, but before the Questions section:

**Please Read Chapter 12: Weeping which you can find here.** 
[Timothy Keller Ch.12.pdf](https://github.com/TWUOnline/bug-tracking/files/10906135/Timothy.Keller.Ch.12.pdf)

2. Please change the list of questions to a non-fillable list. Change the title of the questions section to "Questions to Consider." It should now look like this: 

Questions to Consider:
1. Why did Christians feel the need to eliminate lamenting? 
2. How did God respond to Elijah during his time of suffering? Who did God send?
4. What does creating a climate of care do?
5. What are the three lessons that the psalms teach us? 
6. How does weeping drive us into joy? How can we experience seemingly paradoxical emotions at the same time?
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=4#tabs-tree-start
7. Unit # 3        Topic # 3        Activity# 3.11 
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse these edits have been made
