### ISSUE TITLE
videos not playing for student

### ISSUE THREAD

**Issue by JulietTeeter** [TWUOnline/bug-tracking#721]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 PSYC 354 OL SP 2023
 
**Describe the error and/or your suggestion**  

 I received this email from a student: I am enrolled in PSYC 354, and noticed that the first two videos in topic 1 are not accessible. The first two videos in topic 2 are also not working. 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:

 
**Optional: Screenshots**

**Comment by Jeff-TWU** [comment]
@JulietTeeter Hi Juliet, I just checked and all videos for PSYC 354 are viewable company wide. There are no restrictions. 

User experience may vary depending on browser (see screenshots below). The student might just need to click the "open in new window" button.
![Screen Shot 2023-03-07 at 2 44 35 PM](https://user-images.githubusercontent.com/66963480/223571201-fa2ee4d8-e2ac-4b50-8ab0-19b62c6423d2.png)

Feel free to put the student in touch with me directly if they are still having issues.  jeffrey.snider@twu.ca

**Comment by JulietTeeter** [comment]
Thank you very much.


Juliet Teeter, MA

Part time instructor of Psychology

Trinity Western University




________________________________
