### ISSUE TITLE
PSYC 354 02 gradebook setup

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#722]
**Which course contains the bug?**  
 [PSYC ADC Master](https://learn.twu.ca/grade/edit/tree/index.php?id=23420)
 
[PSYC 354 O2 - Brain and Behaviour (SP 2023)](https://learn.twu.ca/course/view.php?id=27104&section=0#tabs-tree-start)

**Describe the error and/or your suggestion**  
Could you set up Juliet's gradebook so it reflects the assessment? (O2 section)  Please also change the ADC Master gradebook (note, I added the discussion categories, but the weighting is still wonky! (I promise to attend Barish's gradebook session on Thursday!;)

**Comment by MeeksonHundoo** [comment]
Hello @kmarjanovic Both the gradebook's have been setup. Requesting you to please take a look and advice.

**Comment by kmarjanovic** [comment]
Thank you @MeeksonHundoo !
I switched the paper & presentation grades (30/10%), so now it's all good.  Thanks for your help!
