### ISSUE TITLE
Adjust Activity 4.1

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#723]
**Which course contains the bug?**  
PSYC 339 OL SU 2023
 
 
**Describe the error and/or your suggestion**  
Change the Questions section to a non fillable list of questions. Change the title to 'Questions to Consider.' The section should now look like this: 

Questions to Consider
1. What are the common symptoms of depression?
2. When is it called major depressive disorder? What is it called when it goes on for more than two years?
3. What are some neurochemical changes that make people more susceptible to depression? 
4. What are researchers exploring further?
5. How is stress related to depression?
6. What are some types of medications?
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=5#tabs-tree-start
7. Unit # 4        Topic # 1        Activity#  4.1
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse this has been updated
