### ISSUE TITLE
Adjust Activity 4.2

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#724]
**Which course contains the bug?**  
PSYC 339 OL SU 2023
 
 
**Describe the error and/or your suggestion**  
Under the Questions to consider section, make the questions a non-fillable list of questions and adjust the paragraph. One question eliminated from the list. Add the link of the pdf to the bolded words.  It will now look like this: 

Questions to Consider: 
After the reading, consider the following questions. The pdf of this text is provided for you here: 
**Read chapter 1: Men’s Hidden Depression**
[Real - Ch. 1.pdf](https://github.com/TWUOnline/bug-tracking/files/10918375/Real.-.Ch.1.pdf)

1.How does this description of his father relate to the intersection of both trauma and depression?
2. Why do we not tend to recognize depression in men?
3. What is the percentage of people that never get help for depression?
4. What, according to Terry Real, produces depression?
5. What are some of the signs of depression in men?
6. What do people tend to view depression as?
7. What compounds a depressed man’s condition?
8. Why do men die earlier than women?
9. What is the stigma around depression?
10. What is covert depression? 

 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=5#tabs-tree-start
2. Unit #  4       Topic #  1       Activity#  4.2
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse this has been updated
