### ISSUE TITLE
Include text link for Activity 4.5

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#725]
**Which course contains the bug?**  
PSYC 339 OL SU 2023
 
 
**Describe the error and/or your suggestion**  
Add the pdf link in the text. Add the link at the bottom of the second paragraph. This section will now look like this: 

This is an older book, written in the late 1990s. In this book, the author attempts to answer 200 questions regarding suicide. We will only discuss some of the pages/questions that I have included. Take note of the older style of discussion regarding mental health.

As he first began studying suicide in the 1950's, Edwin Shneidman is known as the "Father of Suicide". It is noteworthy that this text refers to his work (as do many other texts). p.1-3, 9-18, 29-42, 68-69, 108-109
[Why Suicide- Eric Marcus.pdf](https://github.com/TWUOnline/bug-tracking/files/10918443/Why.Suicide-.Eric.Marcus.pdf)

 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=5#tabs-tree-start
2. Unit #  4       Topic #  1       Activity#  4.5
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse this is done
