### ISSUE TITLE
Adjustments to activity 4.9

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#729]
**Which course contains the bug?**  
PSYC 339 OL SU 2023
 
 
**Describe the error and/or your suggestion**  
1. Add at the bottom of the following paragraphs the bolded section with a direct link to the PDF: 

Terry Real's book provides insight into how and why depression develops. This chapter will focus on the relationship between trauma and depression, which we discussed extensively in our first unit.

As you will see in the following chapter, Terry Real is a very systemic therapist. Notice the emphasis on process rather than content - HOW the client is showing up rather than what the client wishes to discuss or share. Observe how Terry Real's approach relates to our learning of EFFT.

**Read Chapter 4 here.** 
[Real Ch. 4.pdf](https://github.com/TWUOnline/bug-tracking/files/10925587/Real.Ch.4.pdf)

 2. Change the questions to a non fillable list of questions and change the title to 'Questions to consider'. Eliminate part of the paragraph. Eliminate the last two questions. It should now look like this: 
 
Questions to Consider: 
After the reading, consider the following questions and use them as a tool to help you process the information you are reading. 

1. Why is crisis a potential ally in therapy?
2. What is a body memory?
3. What needs to stop in order for the underlying depression to rise to the surface?
4. What did John Bowlby study and how does it relate to the manifestation of depression?
5. What does childhood injury in boys create?
6. What is major depression vs. Dysthymia?
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=5
8. Unit #  4       Topic #  2       Activity#  4.9
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse this is has been done
