### ISSUE TITLE
Editing Request - LDRS 302 - Guidelines for Paper #1 & #2

### ISSUE THREAD

**Issue by BLMSasaki** [TWUOnline/bug-tracking#73]
### Course

**LDRS 302 - Assignments #1 and #2 - additional information needed for the assignments.**
Before starting on an editing project, please connect with the Instructional Designer to go over specific requests for the course.

### Copy Editing
- [ ] Editing for grammar, usage, spelling, punctuation, and other mechanics of style checking for consistency of mechanics. 
- [ ] Check heading levels.
  - [ ] # Unit; ## Overview
  - [ ] ### Learning Activities; ### Activity 1.1
  - [ XX] ##Assessment; ###Assignment 1; #### Grading Rubric

Criteria for assignment #1 and #2 - helpful to know how many sources and citations expected for these papers and if outside sources are expected - academic sources? peer reviewed? or other specifics. 

- [ ] Format tables, figures, and lists.
- [ ] Canadianizing (spelling).
- [ ] Edit for citation style consistent with the subject area.  
- [ ] Edit for consistent structure and basic formatting.
- [ ] Check all links (to web or docs). Flag broken links.  Ensure correct title and minutes are listed.
- [ ] Check that all images/tables have a description/caption.

### Specifics
- [ ] Unit Overview:
  - [ ] Topics are consistent with unit topics
  - [ ] Topics are numbered
  - [ ] Learning outcomes are bulleted; Capitalize the first letter and have a period.
- [ ] Format Activity Checklists – use alert plugin.

### Making Recommendations (Check with Instructional Designer)
- [ ] Make recommendations to ensure that the existing wording of the course content is appropriate for learners of diverse cultural backgrounds, e.g. the language is culturally sensitive.
- [ ] Clarifying meaning, eliminating jargon, polishing language, and other non-mechanical line-by-line editing, 

### Track Changes  
- [ ] On word documents, Track Changes should be used unless requested otherwise.
- [ ] On Github, make a pull request, detailing the changes/questions.

**Comment by cmadland** [comment]
Hi @BLMSasaki , thanks for filing bug reports here! It's interesting that you are using this particular issue template in a way that I didn't anticipate. It was intended to be a checklist for an editor to follow when editing a course, and you are using it as a way to select issues that need attention.

I don't have a problem with that, but it might make sense to create a template that fits your needs as a facili-structor. Does that make sense?

Also paging @kmarjanovic 
cm

**Comment by BLMSasaki** [comment]
Hi Colin,

Yes, that makes sense for sure. Honestly, I didn't know if I should be using them. They were at the end of the pages in the moodle so I clicked on them because it said to report a problem! I didn't know if it was more expedient that way or if I just email you or Kelly about the issues I am encountering.

Honestly, tell me what would be better for y'all. As I am catching problems as we go through each unit, I want to make sure I am communicating them to you.

B


Brenda-Lee Sasaki, MA, CLC, ACC

Adjunct Professor | TWU Richmond

Academic Facilitation Specialist / TWU GLOBAL

Trinity Western University | t. 604.513.2193 | c. 604.785.4126 | e. Brenda-lee.Sasaki@twu.ca


twu.ca<http://www.twu.ca/>



[cid:image003.png@01D567BE.8201A250]<https://www.facebook.com/trinitywestern/>  [cid:image004.png@01D567BE.8201A250] <https://www.instagram.com/trinitywestern/>   [cid:image005.png@01D567BE.8201A250] <https://twitter.com/TrinityWestern>   [cid:image006.png@01D567BE.8201A250] <https://www.youtube.com/user/TrinityWesternU>   [cid:image007.png@01D567BE.8201A250] <https://www.linkedin.com/school/trinity-western-university/>



[cid:image001.png@01D5649E.C2C49090]


Trinity Western University is located on the traditional, ancestral, and unceded territory of the Sto:lo people.
________________________________

**Comment by kmarjanovic** [comment]
@BLMSasaki  & @cmadland 
I think the bug reporting on Github is easier to track than emails, so feel free to keep using it.

Perhaps though instead of selecting "Editing Request" you can choose "Bug Report"

Colin, I see that this won't be clear though for students/faculty.  Could we hide the Editing Request option, as it's just for course editors?

Or a descriptor?
Bug Report:
Have a correction or suggestion for your course?  Click here to create a report to help us improve.

**Comment by kmarjanovic** [comment]
@dgaudet48 
Do we have any other info on the 302 assignments?  
Brenda's question: Criteria for assignment #1 and #2 - helpful to know how many sources and citations expected for these papers and if outside sources are expected - academic sources? peer reviewed? or other specifics.

@BLMSasaki feel free to connect with Heather as well (Heather Strong <Heather.Strong@twu.ca>)

**Comment by dgaudet48** [comment]
I have emailed Heather and I am awaiting response....

**Comment by dgaudet48** [comment]
The expectations for the use of sources are included in the rubric for the assignment. The only one she was concerned about was Assignment #2...I double checked and the information is in that rubric...
