### ISSUE TITLE
Adjustment to the Resources Section in Unit 5

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#744]
**Which course contains the bug?**  
PSYC 339 OL SU 2023
 
 
**Describe the error and/or your suggestion**  
The resource section in Unit 5 has all of the resources from Unit 1. Please follow the same format that this page currently has but implement the following information. This entire page needs to be replaced with the following resources: 

Topic 1
Video: [Hans Selye's General Adaption Syndrome and the HPA Axis: Exploring the Connection](https://youtu.be/9FdmxfXrygA)

Website: https://stresscanada.org/

VicHealth 2015, Current theories relating to resilience and young people: a literature review, Victorian Health Promotion Foundation, Melbourne.

Chapter 1: Kottler, J. A., & Chen, D. D. (2008). Stress management and prevention: Applications to daily life. Thomson/Wadsworth.

Video: [InBrief: The Science of Resilience](https://youtu.be/1r8hj72bfGo)

Video: ["Building Resilience in Care Providers" Daniel Siegel | HagueTalks](https://youtu.be/RkC8hx-_k3Y)

Video: [Dan Siegel - The Opportunity to Build the Circuits of Kindness and Resilience](https://youtu.be/0XG8uOWEBbc)

Topic 2
Chapter 2 : Kottler, J. A., & Chen, D. D. (2008). Stress management and prevention: Applications to daily life. Thomson/Wadsworth.

Video: [When the Body Says No](https://youtu.be/Bz-VObNRmu0)

Website: [https://neufeldinstitute.org](https://neufeldinstitute.org/resilience-embracing-the-emotional-journey/)

Topic 3
Video: [The power of vulnerability | Brené Brown](https://youtu.be/iCvmsMzlF7o)

Video: [Dan Siegel on Neurobiology and Resilience](https://youtu.be/Zriw-jShjzY)

Lafrance, A., Henderson, K. A., & Mayman, S. (2020). Emotion-focused family therapy: A transdiagnostic model for caregiver-focused interventions. American Psychological Association.
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=6#tabs-tree-start
2. Unit # 5        Topic #  Resources       Activity#  the whole page
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse this is done
