### ISSUE TITLE
Adjustments to Unit 5 summary

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#745]
**Which course contains the bug?**  
PSYC 339 OL SU 2023
 
 
**Describe the error and/or your suggestion**  
Change one of the words in the description. Change the bolded word from second to fifth. 

As part of this **second** unit, you have learned about Stress and Resilience. It is so important that we understand how prolonged stress can affect our bodies and how urgent it is to take action. The fact that we can build up our resilience tangibly should also encourage you. In the beginning, it is easier to do it when we are young, but it is also possible to do when we are older. Fortunately, the brain is very malleable and can still be taught and learned.
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=6#tabs-tree-start
2. Unit #  5       Topic # Summary        Activity#  whole page
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse there does not seem to be any changes that are needed in this section. The summary is already updated. Could you please take a second look and advice if you still need any edits to it?

**Comment by emilyverse** [comment]
hello @MeeksonHundoo. It was just one bolded word in the summary. It says 'second' instead of 'fifth'. This summary is from the fifth unit and not the second unit-I'm sorry that my instructions were unclear! Looking at it again, can you change the first sentence to: 

In Unit 5, you have learned about Stress and Resilience. 


Thanks!!

**Comment by MeeksonHundoo** [comment]
> In Unit 5, you have learned about Stress and Resilience.

Hello @emilyverse i've made this change.
