### ISSUE TITLE
Adjustments to the overview section

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#746]
**Which course contains the bug?**  
PSYC 339 OL SU 2023
 
**Describe the error and/or your suggestion**  
1. Eliminate the second paragraph. (the section in bold)
Overview
This is your last unit in this course. Several approaches to living out your faith will be discussed. Psychologists, therapists, and counselors are ethically bound not to explicitly discuss their faith in a counseling session. If you are not directly asked about your faith, you cannot discuss it. Therefore, how should we live in this profession as followers of Christ? We will explore five different perspectives/approaches to integration in this unit. As we proceed through these questions, I invite you to reflect and consider what is most appropriate for you.

**We begin Unit 6 by unpacking ‘a levels of explanation view’. I invite you to read the previous chapter that goes over a brief history of Christians in psychology, however this chapter will not be assigned due to the amount of reading.**

2.  Eliminate the bolded resource. 

Resources:
**Johnson, E. L. (2010). Christianity and Psychology: 5 Views (2nd ed.). Intervarsity Press.**

Greggo, S., & Sisemore, T. (2012). Counselling and Christianity: 5 Approaches. Intervarsity Press.

Video: [Biblical Counseling vs. Christian Counseling: What’s the Difference?](https://www.youtube.com/watch?v=HBmyDw7BGfs)
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=7
5. Unit #  6       Topic #  Overview       Activity#  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse this is done
