### ISSUE TITLE
Adjustments to Required texts and materials section. 

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#747]
**Which course contains the bug?**  
PSYC 339 OL SU 2023
 
 
**Describe the error and/or your suggestion**  
Please add in the bold sentences to the required texts and materials section. 

Required Texts and Materials
Each unit overview includes a list of resources that are required and suggested. **The following are your required texts to purchase for this course. Take note you do not have to read the books in their entirety, although you are welcome to do so. See the Course units for the required chapters to read.** 

In the Realm of Hungry Ghosts by Gabor Mate

Emotionally Focused Family Therapy by Adele LaFrance
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112
2. Unit # Overview        Topic # Heading is Required texts and Materials        Activity#  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse this is done
