### ISSUE TITLE
Course syllabus link not working

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#748]
**Which course contains the bug?**  
PSYC 339 OL SU 2023
 
 
**Describe the error and/or your suggestion**  
The course syllabus link is not working in the overview page. I bolded the "here" that you are supposed to click. When i click on it in the course it goes to an ERROR 404 page. 

Course Description
A psychological perspective on the experiences and problems humans encounter in daily living. Self-understanding in such areas as love, work, religion, sexuality, values and meaning, and interpersonal relationships. Growth models and health.

The syllabus includes key information about the course schedule, assignments, and policies. Please read the full course syllabus **[here]**(https://far.twu.ca/arts/psyc339/home/LDRS_410-Syllabus-Fall-2019far.pdf).

For information on how to navigate through this course on Moodle, see [here](http://create.twu.ca/help/moodle).
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112
2. Unit #  Overview       Topic # Course description section        Activity#  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse Could you please provide us with the pdf copy of the syllabus such that i can have it uploaded on the course overview page.

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse you can ignore my previous comment, I got the syllabus from your moodle . This is done now.
