### ISSUE TITLE
Adding a new topic to the Before PSYC 339 Begins section

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#749]
**Which course contains the bug?**  
PSYC 339 OL SU 2023
 
**Describe the error and/or your suggestion**  
Please add a new topic to the bottom of the page. 

Topic 5: Optional Activities

Please pay close attention to which activities are optional and which are not. You can find out if the activity is optional in the title of the activity. Of course I invite you to do the optional activities as it will add to your learning, but I also recognize that this is a fast course and there is a lot of information coming at you already.  

 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=1#tabs-tree-start
2. Unit # Before Psych 339 Begins        Topic #  adding a new one       Activity#  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse this is done
