### ISSUE TITLE
Change the Chart in the Assessments section

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#750]
**Which course contains the bug?**  
PSYC 339 OL SU 2023
 
**Describe the error and/or your suggestion**  

1. Adjust the graph to the following screenshot. 
![Screen Shot 2023-03-09 at 2 22 55 PM](https://user-images.githubusercontent.com/114267346/224173997-ee93bd91-b1e6-4f7e-b623-1d87cfbae6d2.png)

2. Add the following written section after the chart and before the italicized sentence (_You will find the instructions, specific due dates and submission boxes for each of these assessments in the nested tabs above_.). 

The Structure of the Assignments: 
Please note that each of the assignments build on each other. The Forums will help you formulate your thoughts and interact with the material on a personal level, the Case Conceptualizations will help you start to apply the material to different situations. The Oral presentations will require you to research in more depth a treatment modality and then the paper will incorporate all of these pieces. You are encouraged to then thoughtfully plan out your assignments. For example one of your case conceptualizations that you choose should be connected to the topic that you will choose for your research paper. The same will apply for your oral presentations. Then when you write your paper, you will have already done some research you need and will already have a case conceptualization that you have reasoned through to include in your paper. For the personal section of the paper, you will also already have started wrestling through some of the reflections/questions in your Forums. The more time and intention you spend on these assignments, the easier your final paper will be to put together. 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=8#tabs-tree-start
2. Unit # Assessments section    Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse this is done
