### ISSUE TITLE
Adjustment to Research Paper Description

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#751]
**Which course contains the bug?**  
PSYC 339 OL SU 2023
 
 
**Describe the error and/or your suggestion**  
1. Please Reformat this section so that it is visually more appealing and easy to follow. I have included what the reformatting will look like here. Note also that there is also some adjustments and added sentences. These are in bold. 

Description:
Students can choose to expand on the topic that they were assigned for their class presentations and add three more research articles. OR they can pick a new topic and are still required to have 3 research articles. The topic of the paper will answer the question: How would you work with someone who is struggling with ‘your assigned topic’? I invite you to use one of your case conceptualization scenarios as an illustration/case study to incorporate into this paper. The paper will cover four main points:

1. An explanation of what the topic is, how and why the topic develops, and how it shows up:
              a) You are invited to use one of your case conceptualizations to illustrate your research findings.
              **b) the majority of the NEW research for your paper should be done in this section.** 

2. What are the preventative measures/what wellness looks like in this area:
              a) You are invited to use one of your case conceptualizations in this area as a case study/example to draw on as you 
              explore what preventative measures you would use or what wellness would look like. For example, if your character had 
              access to these resources, what may have happened or what would wellness look like for this character?

3. Evidenced based treatment directions/community resources to access:
              a) You may use the information from your oral presentations here if it aligns. 
              b) You are also invited to once again use your case conceptualization here to describe your 
              recommendations/treatment recommendations.

4. What approach to therapy and integration are you drawn to and why
              a) You may use your case conceptualization tool here once again to show how you would integrate your faith with this 
              case **and/or use some of your thoughts you formed from your Forum discussions.**
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=9#tabs-tree-start
3. Unit # Research Paper section        Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse this is done
