### ISSUE TITLE
Adjustments to the research paper section

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#752]
**Which course contains the bug?**  
PSYC 339 OL SU 2023
 
**Describe the error and/or your suggestion**  
1. Please Reformat this section so that it is visually more appealing and easy to follow. I have included what the reformatting will look like here.

Grading Rubric:

**Substance   /20**

The research paper provides evidence of critical thinking and analysis and synthesis of researched information throughout and presents a logical and persuasive argument. /2

Research sources are relevant, current, and credible. They are clearly documented in the paper. /1

The introduction offers a sense of direction for the paper and presents a clear thesis statement to the reader. /1

The body develops the necessary aspects of the main idea and provides examples, support, or illustration for each aspect of the main idea. /15

- [ ] A thorough explanation of the topic /5
- [ ] What would wellness look like in this area /1
- [ ] What are some preventative measures /3
- [ ] Evidence based treatment directions /3
- [ ] Therapy and Integration approach /3

The conclusion summarizes the main points and ties them to the thesis; it also presents an impact statement and/or suggests direction for future research. /1

**Writing Style and Format   /5**

Writing Style /3
               
- [ ] Paragraphs are unified, developed, and coherent, with transitions between ideas.
- [ ] Sentences are grammatically correct; words are chosen for accuracy and impact.
- [ ] The writing follows the conventions of spelling and mechanics (punctuation, etc.).

The format follows the APA documentation style accurately and consistently.  /2

- [ ] Include a separate title page with the title of the paper, your name, student number and date along with the name of our institution (school), the course name and number.
- [ ] Include a separate list of references that begins on a new page (as per APA style guidelines).
- [ ] Be double-spaced with 1” margins, typed using a 12 pt. standard font (e.g., Times, Arial or Helvetica) and be left- justified.
- [ ] Use the same font throughout your paper (do not use different styles or sizes of font for title, headings, etc.). You do not need to write an abstract for this paper.

**TOTAL:   /25**
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL: https://learn.twu.ca/course/view.php?id=28112&section=9#tabs-tree-start 
3. Unit # Research Paper Section        Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse this is done
