### ISSUE TITLE
Adjustments to oral presentations

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#753]
**Which course contains the bug?**  
PSYC 339 OL SU 2023
 
 
**Describe the error and/or your suggestion**  
1. Change the length of the presentation from 20 minutes to 10-15 minutes and the other changes are bolded as well. I also would like the last sentence of the second paragraph eliminated. These changes are highlighted in bold. 

A group of five students will be assigned one of the topics presented in the units (topics will be assigned by the professor). Students will use the jigsaw method to watch their fellow group members' presentations and provide a comment or question for each. The presentations will last for **10-15 minutes** and will contain information from two research articles and one community resource related to the student's topic. All presentations must be pre-recorded and uploaded to Microsoft streams by the end of week 5. The professor will go over how to upload videos to Microsoft streams during Week 2 class. Presentations must be **10-15 minutes,** the professor will only watch a minute past the **15 minute mark**.

Each student will then be required to watch their fellow group members' presentations before the start of Week 6 class. Each student will be required to write one comment **OR** one question on each presentation they view (4 presentations) **to be completed in Microsoft Streams**. 

2. Change the bolded words in the rubric. 

**The Rubric:**

- [ ] The research about therapy modality of choice related to your assigned topic. /9
- [ ] A bibliography must be provided in APA format and uploaded to Moodle separate from your recorded presentation. /1
- [ ] An example of a case study (Either drawn from personal experience or from a resource). You may use the Case Conceptualization Tool from your other assignments as a guiding point for this section as well /4
- [ ] Provide one comment **or** one question for each of your groups presentations /1

TOTAL:   /15 points

 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=10#tabs-tree-start
4. Unit # Oral Presentations        Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse I made changes to the timings on the presentation section, however, you have not highlighted the bolded words in the rubric that you want to change. Request you to please highlight the words on the rubric you want us to change.

**Comment by emilyverse** [comment]
Hello @MeeksonHundoo, its very small, but the bolded worded in the rubric section is OR on the last requirement. Before it had the word AND. So changing from AND to OR. Thanks!

**Comment by MeeksonHundoo** [comment]
> Hello @MeeksonHundoo, its very small, but the bolded worded in the rubric section is OR on the last requirement. Before it had the word AND. So changing from AND to OR. Thanks!

Hello @emilyverse this is done.
