### ISSUE TITLE
Adjustments to the Case Conceptualizations Tab

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#754]
**Which course contains the bug?**  
PSYC 339 OL SU 2023
 
 
**Describe the error and/or your suggestion**  

1. Please change the bolded sentence in the following paragraph. 

Description:
Each student will need to complete 3 out of the 6 case conceptualizations. Each case conceptualization is due by the next week's class. For example if you choose to do this week’s case conceptualization on Trauma, you will need to complete it by our next class. Please take note of the due dates on these and plan ahead which topics you would like to do. The case conceptualization form that you will need to fill out is provided **at the bottom of this page; you will use the same form for all three case conceptualizations.** We will go over how to complete this assignment during our first virtual class together. If you can not attend, then a recording of our class will be uploaded to Moodle for your viewing convenience. I would recommend that you choose your case conceptualizations based on which topics you are most interested in. Students will have the opportunity to use these case conceptualizations for their other assignments.
 

2. Please change the formatting of the Rubric to look like this: 

Grading Rubric:

- [ ] Is the Demographics section filled out correctly? /1
- [ ] Reason for referral /1
- [ ] Background information demonstrates that you watched the movie /2
- [ ] Observations and Impressions: connecting the movie to what you have learned /3
- [ ] Treatment recommendations /3

TOTAL:  /10
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=12#tabs-tree-start
2. Unit # Case Conceptualizations Section        Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse this is done
