### ISSUE TITLE
Adjustments to 6.19

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#756]
**Which course contains the bug?**  
PSYC 339 OL SU 2023
 
 
**Describe the error and/or your suggestion**  
Change the title of the activity from:
Activity 6.19: Case Study
to this: 
Activity 6.19: Optional Case Study
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=7#tabs-tree-start
2. Unit #  6       Topic #  3       Activity#  6.19
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse this is done
