### ISSUE TITLE
Adjustment to the Assessment Section in unit 6

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#758]
**Which course contains the bug?**  
PSYC 339 OL SU 2023
 
 
**Describe the error and/or your suggestion**  
Eliminate the entire section of  'Assignment 4: Open Book Quiz' and change Assignment 5: Research Paper, to **Assignment 3: Research Paper.** 

Move the chart that is labeled 'Grading Criteria' to under the Assignment 2: Forum Discussion Participation (after the last paragraph). 
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=7#tabs-tree-start
2. Unit # 6        Topic # Assessment section        Activity#  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse this is done
