### ISSUE TITLE
Blank flash cards

### ISSUE THREAD

**Issue by JulietTeeter** [TWUOnline/bug-tracking#759]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 PSCY 354 02 sp23
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 Starting from flash card #22 to #38, the descriptions do not show up. All I see are three dots (…), but the answers are on the back of the blank flash card.
Same thing with the Chapter 2 flashcards, blank from card #7 to #16.
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=27104&section=1#tabs-tree-start
2. 
3. Unit #         Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
Hi Juliet,
Those flashcards are designed so students can edit them.  I only added some of the definitions, based on other flashcards.  Here are the full instructions - but please let me know if you'd like to change this activity.

Key Terms Flashcards (ungraded)
✏️ To review key terms and prepare for your Unit quizzes, we have created flashcards on Quizlet. See below for the flashcards and select from the dropdown menu to choose a study mode (match, learn, test, flashcards, spell). Alternatively, you can click here to view all the flashcards for the course on Quizlet: [PSYC 354 Flashcards](https://quizlet.com/join/Xn4bzWems).

A couple notes:

Flashcards are available on the student resources website under Resources > [Flashcards](https://learninglink.oup.com/access/watson-breedlove4e-student-resources#tag_flashcards). They contain all key terms used in the textbook (e.g. 163 terms for chapter 1), whereas the Quizlet contains only the key terms you will be tested on.

We designed this activity to help you memorize terms using active learning (see Chapter 13 on Learning & Memory). Not all terms contain the definition or an accompanying image. You are encouraged to add definitions and images from the suggested answers, and/or look up the terms in the textbook.

If you would like to collaborate with your peers and edit the flashcards, use the following link: [PSYC 354 Editing Flashcards](https://quizlet.com/join/Xn4bzWems?i=4a98j9&x=1bqt). (To edit, you will need to sign up for a free Quizlet account.)

**Comment by JulietTeeter** [comment]
Ahhh, I see. Ok thanks!


Juliet Teeter, MA

Part time instructor of Psychology

Trinity Western University




________________________________
