### ISSUE TITLE
LDRS 473 in bookdown 

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#760]
### Course
Ldrs 473
### Instructions
- [x] please add content for 473 to bookdown. Right now there is not much there, but I think it might help Phil to see the framing. 

Links: [LDRS 473 Blueprint](https://docs.google.com/document/d/1ffgKuQK7AuRVaTZImNdr0vsJt0wct6YtuW-8zLvgyaM/edit#heading=h.48qcpkwodkpt) [LDRS 473 Units](https://docs.google.com/document/d/1MO26peVHnfu9tfOCfy-zeh0WPSVtlUt3/edit)

**Comment by Jeff-TWU** [comment]
I'm on it.

**Comment by Jeff-TWU** [comment]
@kmarjanovic [Content added.](https://ideal-disco-l5r1m56.pages.github.io)

**Comment by kmarjanovic** [comment]
Please update formatting for LDRS 473. Thank you!

**Comment by Jeff-TWU** [comment]
> Please update formatting for LDRS 473. Thank you!

@kmarjanovic [Updated.](https://ideal-disco-l5r1m56.pages.github.io/orientation-to-groups-and-capstone-project.html)

**Comment by kmarjanovic** [comment]
Colin or Jeff, does the bookdown url need to change for it to show in Moodle?  E.g. https://learn.twu.ca/course/view.php?id=28299&section=2

If possible, could you fix before the 10am meeting with Phil tomorrow?
Thank you!

**Comment by Jeff-TWU** [comment]
> Colin or Jeff, does the bookdown url need to change for it to show in Moodle? E.g. https://learn.twu.ca/course/view.php?id=28299&section=2
> 
> If possible, could you fix before the 10am meeting with Phil tomorrow? Thank you!

[Fixed](https://learn.twu.ca/course/view.php?id=28299&section=2). Yes, page settings needed to be changed from private to public, and then the URL needed to be updated.

Github Course page > Settings > Pages > Visibility needs to be changed to Public.

![Screen Shot 2023-03-28 at 8 52 14 AM](https://user-images.githubusercontent.com/66963480/228296809-9b3882c0-6e0f-44cc-b9af-69532b25fc62.png)

**Comment by kmarjanovic** [comment]
Hi @Jeff-TWU !  With those audio files I just sent, I'm going to have a similar style to https://ba-leadership.github.io/ldrs371/a-title-for-unit-1.html#how-can-great-firms-fail-insights-from-the-hard-disk-drive-industry - just without the topic headings.

Can you upload the files in a new section after the resources and before the [Unit Summary](https://ba-leadership.github.io/ldrs473/orientation-to-groups-and-capstone-project.html#unit-1-summary)?


Activity: The Innovator’s Solution Readings
Read Chapter # in the Christensen text *The Innovator’s Solution*. In this chapter, Clayton Christensen ...

Questions to Consider

After completing the Chapter # reading, consider the following questions:

- ...
- ...
- ...

I can edit this as well if you'd prefer me to do a unit example first.

**Comment by Jeff-TWU** [comment]
@kmarjanovic I'll need to upload them at a later date. With the free version of Podbean there is a limit of 3 podcasts I can upload in a day. I'm still working on getting all of the files up for 370.

Should I just start another account with my email? Or wait until next Friday (That's the backlog right now.)?

**Comment by kmarjanovic** [comment]
Friday is fine.  Just thinking though if we are adding more audio to our courses, should we look into a paid option?

**Comment by Jeff-TWU** [comment]
@kmarjanovic For clarification, it will be next Friday, not this upcoming Friday. 

Unless we get more use out of it, I don't think the price is worth it. The free version should be enough space, unless this takes off.

[Paid version is $108 a year, or $14 a month.](https://www.podbean.com/podcast-hosting-pricing)

**Comment by kmarjanovic** [comment]
Phil has 6 courses - each of the 6 units will likely have audio.  371 course audio is done - any others?

Perhaps 1-2 months would be worth it?  @cmadland what do you think?

**Comment by Jeff-TWU** [comment]
@cmadland @kmarjanovic Even If I only had 1 month, if I had all the files I could upload before the courses are put together.

**Comment by Jeff-TWU** [comment]
> Is podbean a long-term solution?

What is the criteria for long-term solution? I think it could be. Free version has 5 hour limit (total files duration). I don't see us hitting that any time soon. Doesn't seem to be any "expiry".

**Comment by kmarjanovic** [comment]
I'd suggest we go forward with this for 1 or 2 months.  It's helpful for IDs & SMEs - and definitely worth it to show a "finished" product in a timely manner.

**Comment by Jeff-TWU** [comment]
@kmarjanovic [Added chapter summaries](https://ba-leadership.github.io/ldrs473/orientation-to-groups-and-capstone-project.html#activity-chapters-1-2-of-the-innovators-solution), updated notes to Phil with the "prote" class so they standout a little more.
