### ISSUE TITLE
PSYC 354 video

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#761]
**Which course contains the bug?**  
[PSYC 354 O2 - Brain and Behaviour (SP 2023)](https://learn.twu.ca/course/view.php?id=27104&section=3#tabs-tree-start)

(or PSYC 354 Master)
 
 
**Describe the error and/or your suggestion**  
The Unit 3 Overview video is the same as the Unit 2 Overview video.  @Jeff-TWU do you have the Unit 3 video from Jayme (last year's course).  Could you please insert that [here](https://learn.twu.ca/course/view.php?id=27104&section=3#tabs-tree-start)?

**Comment by Jeff-TWU** [comment]
@kmarjanovic Not sure what happened there...Fixed. Please confirm.

**Comment by kmarjanovic** [comment]
Perfect!  Thanks @Jeff-TWU !
