### ISSUE TITLE
Changes to Overview Page

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#764]
**Which course contains the bug?**  
PSYC 339 OL SU 2023
 
 
**Describe the error and/or your suggestion**  
Please change the list of resources from this: 

Greggo, S., & Sisemore, T. (2012). Counselling and Christianity: 5 Approaches. Intervarsity Press.

Video: [Biblical Counseling vs. Christian Counseling: What’s the Difference?](https://www.youtube.com/watch?v=HBmyDw7BGfs)

to this: 

Resources: 
Greggo, S., & Sisemore, T. (2012). Counselling and Christianity: 5 Approaches. Intervarsity Press. 
 https://www.youtube.com/watch?v=dES1gyR8034 
https://www.youtube.com/watch?v=VONmMBVQaE8
https://www.youtube.com/watch?v=g0f6VxbP0GU 
https://www.youtube.com/watch?v=57HiA2kwQTA
https://www.youtube.com/watch?v=4Xj9FezdpXY
https://www.youtube.com/watch?v=q5OdfcBCzQw
https://www.youtube.com/watch?v=A1ZNfCnFL04 
https://www.youtube.com/watch?v=_71JqYyb5Jg
https://www.youtube.com/watch?v=3L72Gu_0FcQ
https://www.youtube.com/watch?v=G9STDM_JOgs&list=RDLVg0f6VxbP0GU&index=9

 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=7
2. Unit #  6       Topic # Overview        Activity#  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse this has been updated
