### ISSUE TITLE
Introduction section of topic 1

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#765]
**Which course contains the bug?**  
PSYC 339 OL SU 2023
 
 
**Describe the error and/or your suggestion**  
Please replace the introduction paragraphs (right before the learning activities start) from this: 
The Southern Baptist Theological Seminary's Professor of Pastoral Care, Eric L Johnson, received his doctorate from Michigan State University. A number of other books have been written by him, including 'God under Fire' and 'Foundations for Soul Care'. In addition to writing, he is also an associate editor of the Journal of Psychology and Theology, the Journal of Psychology and Christianity and the Journal of Spiritual Formation and Soul Care. In writing this collection of essays, he seeks to answer the question of 'How can Christians understand and apply psychology as a discipline?' Christian leaders have been grappling with this question as they strive to balance what can sometimes seem contradictory morals and values. What is the most effective way to reconcile these two historically opposing viewpoints? As a result of our readings, we will attempt to unravel 5 different ways in which academics have analyzed this issue.

In the following learning activities, you will learn more about the five approaches to integration; ‘A Levels of Explanation View’, ‘An integration view’, ‘A Christian Psychology View',’ A Transformational Psychology View’, and ‘A Biblical Counselling Approach’. Eric L Johnson’s book is formatted so that each of the authors presents his view at the beginning of each chapter. The other authors critique and review this view in the following sections. It is not mandatory for you to read the discussion or ‘reviews’, but if the viewpoint you are reading about interests you, you are encouraged to do so. Consider which view resonates most with you as we walk through each of the views. We will discuss how each of the views appears in the therapy room in our next topic.

**to this:** 

We will be unpacking the five views of approaching faith and counselling that has been compiled by Eric L. Johnson. The Southern Baptist Theological Seminary's Professor of Pastoral Care, Eric L Johnson, received his doctorate from Michigan State University. A number of other books have been written by him, including 'God under Fire' and 'Foundations for Soul Care'. In addition to writing, he is also an associate editor of the Journal of Psychology and Theology, the Journal of Psychology and Christianity and the Journal of Spiritual Formation and Soul Care. In writing this collection of essays, he seeks to answer the question of 'How can Christians understand and apply psychology as a discipline?' Christian leaders have been grappling with this question as they strive to balance what can sometimes seem contradictory morals and values. What is the most effective way to reconcile these two historically opposing viewpoints? As a result of our readings, we will attempt to unravel 5 different ways in which academics have analyzed this issue. 
In the following learning activities, you will learn more about the five approaches to integration; ‘A Levels of Explanation View’, ‘An integration view’, ‘A Christian Psychology View',’ A Transformational Psychology View’, and ‘A Biblical Counselling Approach’. Although I encourage you to read Eric L Johnson’s book, for the sake of time we will not be going through it. We will be using and benefiting from City Vision University’s series of free lectures that unpack these five views for us. Pay attention to where you need to start and end in the youtube clips as you do not need to listen to the whole presentation. The lectures are provided by the president of the City Vision University, Andrew Sears, PhD. City Vision University is an online accredited program located in Kansas City.  Consider which view resonates most with you as we walk through each of the views. We will discuss how each of the views appears in the therapy room in our next topic.

 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=7
2. Unit #  6       Topic #1         Activity#  paragraphs before learning activities
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
hello @emilyverse this has been updated
