### ISSUE TITLE
Change the entire learning activity

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#766]
**Which course contains the bug?**  
PSYC 339 OL SU 2023
 
 
**Describe the error and/or your suggestion**  
Please delete the entire learning activity 6.1 and change it to this: 

Activity 6.1: Watch “Introduction” Clip
Watch the following youtube clips to help introduce us to this discussion. We will cover some of the practical reasons why it is important to cover these different approaches and why it is important to start formulating our own ideas around this. 

WATCH:  https://www.youtube.com/watch?v=dES1gyR8034 (City Vision University) 
Beginning - 10:32
Questions to Consider
After completing the activities above, consider the following questions:
What is your calling? to work within more christian environments, secular environments? A mix of both? Who are your clients?
Where do each of the views tend to be taught? 
How does he condense the views from 5 to 3? 
Take note of the graph to help you consider the implications of where you fall. 

WATCH: https://www.youtube.com/watch?v=VONmMBVQaE8 (Eric L Johnson) 
Let’s hear from the original author himself. He provides a very brief overview of how psychology and Christianity overlap, and how the church needs to ‘reclaim’ psychology and figure out what it now looks like in Christian context. 

“Optional” WATCH: https://www.youtube.com/watch?v=g0f6VxbP0GU 
To enrich our discussion and to see an example of why it is relevant to consider these things, take a listen to this video. Notice the ‘how’ of the discussion and take note of the points that are being made as we dive deeper into the five approaches. 
Questions to Consider
After completing the activities above, consider the following questions:
What is the main question he brings up about integration? What do we need to understand at a deeper level that is missing? 

 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=7
2. Unit #  6       Topic #  1       Activity#  6.1
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse this has been updated
