### ISSUE TITLE
Change to activity 6.3

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#768]
**Which course contains the bug?**  
PSYC 339 OL SU 2023
 
 
**Describe the error and/or your suggestion**  
Please delete the entire Activity 6.3 and replace it with the following. Please just list the questions to consider, don't include a fillable form. 

Activity 6.3: Watch “An Integration View” 
https://www.youtube.com/watch?v=4Xj9FezdpXY (City Vision University) 
Start to 10:56 

Before you begin to engage in the clip, here is a little synopsis of what ‘An Integration View’ is; hopefully this will help guide your reading along with the ‘questions to consider’. 
The Integration View holds that we are responsible to live out our faith in all aspects of our lives and to trust in God’s divine and natural revelation to determine all of our beliefs and practices. This view does not go against science or research but holds to the idea that ‘all truth is God’s truth’ and God can reveal himself through natural revelation by means of scientific research. 
This view calls strong integrationists to really study the word, study christian integration and study psychology. This video talks about how the danger of integration is that many therapists don’t receive training in integration and then often become more ‘secularized’ in the process. 

Questions to Consider

- After completing the activities above, consider the following questions:
- What are the three types of integration? 
- What’s the popular integration slogan? 
- What are some of the strengths of the model?
- What are some of the weaknesses?

“Integration is a recursive process of expanding understanding, but always with our most fundamental loyalty being to the true teachings of the special revelation of the Bible. Integration is ultimately the task of the Christian person whom God has led to be a student or scholar of some facet of psychology, with the true teachings of special revelation as the guiding framework for how that person structures his or her deepest beliefs and loyalties.” (Johnson, 2010 p.117)

 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=7
2. Unit #  6       Topic #  1       Activity#  6.3
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse this is done
