### ISSUE TITLE
Production LDRS 300 pwpt

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#77]
### Course
LDRS 300
### URL
https://learn.twu.ca/course/view.php?id=10828&section=3
### Instructions

Unit 3 Topic 1 - add pwpt (Make into Presentations plugin when there is time)

pwpt too large so need to send via email.

**Comment by kmarjanovic** [comment]
pwpt files too large to email so are in dropbox: https://www.dropbox.com/sh/vy2vw9hvj9w5e8b/AACwhFFctUuzZTAmlKxmgXeUa?dl=0

Please add pwpt 3.1

**Comment by cmadland** [comment]
#

**Comment by cmadland** [comment]
@kmarjanovic do we know where this deck should go?
