### ISSUE TITLE
changes to Activity 6.5

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#770]
**Which course contains the bug?**  
PSYC 330 OL SU 2023
 
 
**Describe the error and/or your suggestion**  
Please delete Activity 6.5 and replace it with the following. Please just have a list of questions for the questions to consider section and not a fillable form. 

Activity 6.5: Watch “A Christian Psychology View” 
https://www.youtube.com/watch?v=q5OdfcBCzQw (City Vision University) 

Before you begin to engage in this clip, here is a little synopsis of what ‘A Christian Psychology View’ is; hopefully this will help guide your reading along with the ‘questions to consider’. 
The ‘Christian Psychology View’ holds that everyone should interpret psychology from their own set of values, including Christians. So no matter what faith or non faith perspective you hold to, that will be how you interpret, research and interact with the material, psychology or other, in front of you. 

Questions to Consider
After completing the activities above, consider the following questions:

- What is the agenda of Christian Psychology? 
- What areas of psychology are more worldview dependent?
- What are the major distinctives that characterize a Christian psychology worldview?
- What is the 4 dimensional model of christian psychology?
- What are some of the strengths and weaknesses of this model? 

“However our primary agenda in this chapter was to show the need for Christians to practice their psychology in light of their basic assumptions and the resources of their distinctive tradition. At the most comprehensive level, “tradition validity” for Christians will mean that the Christian worldview, which comes to us from the past, will enable us to meet the challenges of the present faithfully by rationally and empirically demonstrating how essential the love of Christ is for our future.” (Johnson, 2010, p. 173, 174)

 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=7
2. Unit #  6       Topic # 1        Activity#  6.5
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse this is done
