### ISSUE TITLE
CHanges to activity 6.7

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#772]
**Which course contains the bug?**  
PSYC 339 OL SU 2023
 
**Describe the error and/or your suggestion**  
Please delete activity 6.7 and replace it with the following. Please make the questions to consider section a non fillable list. 

Activity 6.7: Watch “A Transformational Psychology View
https://www.youtube.com/watch?v=A1ZNfCnFL04 (City Vision University)

Here is a brief overview of what 'A Transformational Psychology View' is:
In the Transformational Psychology View, you can take wisdom from both theological and psychological viewpoints, but we need to re-evaluate what traditional psychology would tell us to be appropriate psychology. Each area of study would need to be viewed through the lens of both reality and faith.  Considering the fact that the approach is based on Christian realities, this approach is only suitable for Christians. It is imperative to note that this approach has a great deal to do with the individual and how close the person is to God; the closer the person is to God, the more profound the psychology. 
“The bottom line will be that doing science and, in this case, psychology is ultimately an act of love.” (Johnson, 2010, p.199)

Questions to Consider

- After completing the activities above, consider the following questions:
- What are some of the major themes of transformational psychology?
- What are the three different Spiritual categories? 
- Take note of the graph that compares secular psychology with transformational psychology 

*Optional*WATCH:  https://www.youtube.com/watch?v=_71JqYyb5Jg (John Coe)

John Coe is one of the main contributors to the transformational psychology approach. In this video, you 
can see how John Coe talks about transformational psychology particularly around the concept of spiritual formation. 

Questions to Consider

- After completing the activities above, consider the following questions:
- What is spiritual theology? 
- Who is the agent of change? 
- Why has spiritual formation been misunderstood by the church according to John Coe?

 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=7
2. Unit # 6        Topic #  1       Activity# 6.7 
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse this is done
