### ISSUE TITLE
Update Activity 6.9

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#774]
**Which course contains the bug?**  
PSYC 339 OL SU 2023
 
**Describe the error and/or your suggestion**  
Please delete activity 6.9 and replace it with the following. Also please have the questions to consider section as a non fillable list of questions. 

Activity 6.9: Watch “A Biblical Counselling Approach” Clip
https://www.youtube.com/watch?v=3L72Gu_0FcQ (City Vision University)  
Start at 00:55-10:45

Here is a brief overview of what 'A Biblical Counselling Approach' is:
Ultimately, a Biblical Counseling Approach believes that the Bible and Christian faith depict humanity and behavior in the right light. Psychological insights can be gleaned from this approach, but the Bible possesses the deepest wisdom. 
“Christian Ministry is a psychotherapy.” p.245

Questions to Consider
After completing the activities above, consider the following questions:

- What is counselling based exclusively on? 
- What are the limitations of biblical counselling?
- What are the two groups/types of biblical counselling?
- What are the strengths of this approach?

*Optional* WATCH https://www.youtube.com/watch?v=G9STDM_JOgs&list=RDLVg0f6VxbP0GU&index=9 (David Powlison) 
David Powlison is one of the big ‘names’ in the field of biblical counselling and the biblical approach. Watch this clip to hear how he talks about how his approach differs from a ‘regular’ counselling approach.

Questions to Consider
After completing the activities above, consider the following questions:

- What are some similarities and some differences between a biblical approach to counselling versus a ‘regular’ counselling session?

 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=7
2. Unit #  6       Topic #1         Activity# 6.9 
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse this is done
