### ISSUE TITLE
Production - LDRS 300 alert

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#78]
### Course
LDRS 300
### URL
https://learn.twu.ca/course/view.php?id=10828&section=3
Unit 3, Topic 2
### Instructions

- [x] Please remove alert at the top of the topic (students may think they have to complete them at that time).  

I notice now that the Activities in this units aren't numbered correctly.  Please make these changes to the alerts:

- [x] Activity 3.3: Case Study: Delivering Happiness: Zappos.com

- [x] Activity 3.4: Read, Review, Reflect and Respond

- [ ] In topic 3, rename activity to Activity 3.5

**Comment by cmadland** [comment]
@kmarjanovic I think there is more going on here than just renaming activities...not sure what though
