### ISSUE TITLE
Eliminate Activity 6.17

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#781]
**Which course contains the bug?**  
PSYC 339 OL SU 2023
 
 
**Describe the error and/or your suggestion**  
Eliminate entirely Activity 6.17 
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=7
2. Unit #  6       Topic # 2        Activity#  6.17
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse this is done
