### ISSUE TITLE
Change Activity 6.18

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#782]
**Which course contains the bug?**  
PSYCH 339 OL SU 2023
 
 
**Describe the error and/or your suggestion**  
1. Change the title of Activity 6.18 to **Activity 6.17**

2. Imbed the following file into this section. 
[Activity 6.18 Summary Pdf.pdf](https://github.com/TWUOnline/bug-tracking/files/11022657/Activity.6.18.Summary.Pdf.pdf)

 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=7
4. Unit # 6        Topic # 2        Activity# 6.18 
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse this is done
