### ISSUE TITLE
Change the Resource Section

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#784]
**Which course contains the bug?**  
PSYC 339 OL SU 2023
 
 
**Describe the error and/or your suggestion**  
The entire resource section is incorrect as it is taken from unit 1. Delete the entire resource page and change it to the following: 

Unit 6 Resources

Topic 1: What is each view/approach to integration? 

Videos: 
https://www.youtube.com/watch?v=dES1gyR8034 
https://www.youtube.com/watch?v=VONmMBVQaE8
https://www.youtube.com/watch?v=g0f6VxbP0GU 
https://www.youtube.com/watch?v=57HiA2kwQTA
https://www.youtube.com/watch?v=4Xj9FezdpXY
https://www.youtube.com/watch?v=q5OdfcBCzQw
https://www.youtube.com/watch?v=A1ZNfCnFL04 
https://www.youtube.com/watch?v=_71JqYyb5Jg
https://www.youtube.com/watch?v=3L72Gu_0FcQ
https://www.youtube.com/watch?v=G9STDM_JOgs&list=RDLVg0f6VxbP0GU&index=9

Readings:
Greggo, S., & Sisemore, T. (2012). Counselling and Christianity: 5 Approaches. Intervarsity Press. 

Topic 2: Clinical Implications

Videos: 
There are no recommended videos for Topic 2

Readings: 
Greggo, S., & Sisemore, T. (2012). Counselling and Christianity: 5 Approaches. Intervarsity Press. 

Topic 3: Application
 There are no recommended resources for Topic 3
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=7
2. Unit # 6        Topic # Resources        Activity#  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse this is done
