### ISSUE TITLE
Changes to Assessment section

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#785]
**Which course contains the bug?**  
PSYC 339 OL SU 2023
 
 
**Describe the error and/or your suggestion**  
Delete the "Checking Your Learning" section and replace it with this: 

Checking Your Learning 

- Compare and contrast the 5 approaches to counseling and faith.
- Discover and determine which approach best suits each student
- Understand the parameters of talking about faith and spirituality in the counseling room.
- Discuss one's own faith journey and how it relates to their future profession.

 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=7
2. Unit # 6        Topic #  Assessment section       Activity#  Checking your Learning part
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse this is done
