### ISSUE TITLE
Changes to Facilitator Notes

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#786]
**Which course contains the bug?**  
PSYC 339 OL SU 2023
 
 
**Describe the error and/or your suggestion**  
Under Unit 1, Learning Activities explanation, eliminate the bolded sentence: 

This course involves a number of straightforward activities. **It is important to encourage students to complete all of them as well as to answer the questions regarding the sections since this can help them prepare for their final open book quiz**. The readings for this course are taken from a variety of resources and it is important for students to experience gaining information/insight from a variety of resources as this will hopefully help them understand and shape them for their final paper. The instructions for each activity are written in Moodle.
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=15#tabs-tree-start
2. Unit #  1       Topic #  Learning Activities       Activity#  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse this is done
