### ISSUE TITLE
Changes to Activity 1.8 in the Facilitator Guide 

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#788]
**Which course contains the bug?**  
PSYC 339 OL SU 2023
 
 
**Describe the error and/or your suggestion**  
Add the following bolded words to Activity 1.8 Section: 

Activity 1.8: Effects on the Brain: **Optional** Website exploration 
The purpose of exploring this website is to provide students with a resource for where to go if and when they encounter trauma in their personal or professional lives. This website is a gateway for other resources and sources of information that may be helpful. **This activity is optional for students.** 
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=15#tabs-tree-start
2. Unit #  1       Topic # 1        Activity# 1.8 
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse this is done
