### ISSUE TITLE
Changes to Activity 1.9 Facilitator Guide 

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#789]
**Which course contains the bug?**  
PSYC 339 OL SU 2023
 
 
**Describe the error and/or your suggestion**  

Add the following bolded words/sentence to Activity 1.9 in the Facilitators guide 

Activity 1.9: **Optional Reading** “Treating Adult Survivors of Childhood Emotional Abuse and Neglect” Page 3-12 
**The** purpose of this resource is to open up the discussion on psychological and emotional trauma. In the media we are more exposed to and understand physical and sexual abuse and its traumatic effects, but there is not a lot out there on emotions and psychological trauma in part due to the complexity of defining what it is and how to spot it. **This is an optional activity for students**
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=15#tabs-tree-start
2. Unit # 1        Topic #  2       Activity#  1.9
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse this is done
