### ISSUE TITLE
Changes to Activity 1.10 in the Facilitators Guide

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#790]
**Which course contains the bug?**  
PSYC 339 OL SU 2023
 
 
**Describe the error and/or your suggestion**  
Add the following bold words/sentences to Activity 1.10 in the Facilitators guide 

Activity 1.10: **Optional** Reading: Treating Adult Survivors of Emotional Abuse and Neglect The purpose of this reading is to unpack a popular treatment modality for psychological and emotional trauma that is based in research. In our class we are mostly focusing on the intervention of EFFT, however it is important to explore this treatment modality as it is specifically designed to deal with the psychological and emotional trauma piece which as we have previously discussed is a harder trauma to spot and at the same time there has been a lot of research done on it lately. **This is an optional activity for students.** 
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=15#tabs-tree-start
2. Unit # 1        Topic #3         Activity# 1.10 
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse this is done
