### ISSUE TITLE
Changes to Activity 1.13 Facilitators Guide 

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#792]
**Which course contains the bug?**  
PSYC 339 OL SU 2023
 
 
**Describe the error and/or your suggestion**  
Add the following words/sentences that are in bold to the following section in the Facilitators guide 

Activity 1.13: **Optional Exploration |**Trauma Informed therapies 
The purpose of this activity is to spend some time exploring other therapy modalities that are used for the treatment of trauma. The purpose is to allow the students an opportunity to become familiar with other treatments so if they end up in the field of therapy or in their conversations with loved ones they will be able to know what to recommend or explore. **This is an optional activity for students.** 
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=15#tabs-tree-start
2. Unit # 1        Topic # 3         Activity#1.13  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse this is done
