### ISSUE TITLE
Unit 2 Facilitators Guide 

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#793]
**Which course contains the bug?**  
PSYC 339 OL SU 2023
 
 
**Describe the error and/or your suggestion**  
1. Please eliminate the sentence in bold writing under the Synchronous Portion of Unit 2 Facilitator Guide 

There are a number of activities associated with this course. **Ideally, students should be encouraged to complete all of them and to answer the questions related to the sections in order to prepare for their final open book qui****z**. Throughout this course, students will be reading from a variety of sources, and it is important that they gain knowledge and insight from a variety of sources as this will hopefully help them understand and shape their final paper. In Moodle, instructions are provided for each activity. 

1. Please eliminate the sentence in bold writing under the Learning Activities of Unit 2 Facilitator Guide 
The activities for this course are pretty straightforward. **Students should be encouraged to complete all of them and to answer the questions to consider sections as in doing this it can help them with their final open book quiz**. The readings for this course are taken from a variety of resources and it is important for students to experience gaining information/insight from a variety of resources as this will hopefully help them understand and shape them for their final paper. The instructions for each activity are written in Moodle.
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=15#tabs-tree-start
3. Unit #  2       Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse this is done
