### ISSUE TITLE
Activity 2.4 Facilitator Guide

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#794]
**Which course contains the bug?**  
PSYC 339 OL SU 2023
 
 
**Describe the error and/or your suggestion**  
Please add the following words/sentences in bold to Activity 2.4 

Activity 2.4: **Optional Reading |** A Biblical Reflection 
The purpose of this activity is to spend some time reading a couple of biblical passages and reflecting on what God says about addiction. For those that are from a Christian background is good to provide a space to start to integrate what the world teaches about mental health and then what the bible does. **This is an optional activity for students**
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=15#tabs-tree-start
2. Unit # 2        Topic # 1        Activity# 2.4  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse this is done
