### ISSUE TITLE
Changes to Activity 2.7 Facilitators Guide

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#795]
**Which course contains the bug?**  
PSYC 339 OL SU 2023
 
 
**Describe the error and/or your suggestion**  
Add the words/sentences in bold to the following section

Activity 2.7: **Optional Website Exploration |** Brain Imaging with Dr. Amen 
The purpose of this activity is to visually see what the brain looks like when it is affected by an addiction. This will provide the students with an image they can apply to their readings. **This is an optional activity for students.** 
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=15#tabs-tree-start
2. Unit # 2        Topic # 2        Activity# 2.7 
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse this is done
