### ISSUE TITLE
Add a word to Activity 2.11

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#797]
**Which course contains the bug?**  
PSYC 339 OL SU 2023
 
 
**Describe the error and/or your suggestion**  
Change the title of Activity 2.11 from this: 
Activity 2.11: Reflect | Looking back 
to this: 
Activity 2.11: Optional Reflection | Looking back
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=3#tabs-tree-start
2. Unit #2         Topic # 3        Activity#2.11  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse this is done
