### ISSUE TITLE
Changes to Unit 3 in Facilitators Guide 

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#798]
**Which course contains the bug?**  
PSYC 339 OL SU 2023
 
 
**Describe the error and/or your suggestion**  
Please eliminate the bolded sentence from the following section under unit 3 Learning Activities and Assignments 

Learning Activities and Assignment
For this course, there are a number of activities that you will be required to complete. **There is no doubt that students should be encouraged to complete all of them and to answer the questions to consider sections, as this will prove to be useful when it comes to their final open book quiz.** The readings for this course are taken from a variety of resources and it is important for students to experience gaining information/insight from a variety of resources as this will hopefully help them understand and shape them for their final paper. The instructions for each activity are written in Moodle.
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=15#tabs-tree-start
2. Unit # 3        Topic # Learning Activities and Assignments        Activity#  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse this is done
