### ISSUE TITLE
Changes to Facilitator Guide Unit 4

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#801]
**Which course contains the bug?**  
PSYC 339 OL SU 2023
 
 
**Describe the error and/or your suggestion**  
Eliminate the bolded sentences from the following sections in the Unit 4 Synchronous portion and learning activities portion in the facilitator guides: 

Synchronous Portion
In the synchronous portion of this class, I would like you to address the topic of mental health and gender. What are some of the assumptions and stigmas around each of these mental health issues? How does this affect those seeking help as well as our potential biases and views of them? Draw upon some of the learning this past week to enhance the discussion. For example: Terry Real’s description of depression and what covert depression is, suicide clusters and the influence of gender here, committing suicide vs. dying by suicide, the population most likely to die by suicide, types of eating disorders and which genders are associated with each.

Spend some time going over the EFFT exercises for this week. This week there is more to go over as we have applied the principles of EFFT to all three of the topics. I still encourage you to go over all three as this will increase the skill level and versatility for the students to apply EFFT to each different subject. If you find yourself short on time, you can invite the students' feedback on which exercises they found more difficult or which ones they would like to go over.

Leave some time to go over any expectations for assignments at the end as their oral presentations are due the following week and some will have started to work on their papers. **You can also take some time to address the open book quiz if students would like time to prepare as the quiz will be open at the end of the following class to the beginning of the final class.**

 

Learning Activities and Assignment
For this course, there are a number of activities that you will be required to complete. **Students should be encouraged to complete all of them and to answer the questions to consider sections as in doing this it can help them with their final open book quiz.** The readings for this course are taken from a variety of resources and it is important for students to experience gaining information/insight from a variety of resources as this will hopefully help them understand and shape them for their final paper. The instructions for each activity are written in Moodle.

For this unit, note that there are three different subjects within the one heading: Suicidality, Depression and Eating Disorders. As such just be aware of the slight difference in nature of the presented material. The same format is followed as previous units with the “what it is, why it happens and how you work with it”, however the information does not go as in depth and this unit may feel slightly more disjointed than the previous units. Nothing else changes in terms of what is required of each activity and what the students need to do.
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=15#tabs-tree-start
2. Unit # 4        Topic #  Synchronous/Learning activities section       Activity#  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse this is done
