### ISSUE TITLE
Changes to Activity 4.8 in Facilitator Guide 

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#802]
**Which course contains the bug?**  
PSYC 339 OL SU 2023
 
 
**Describe the error and/or your suggestion**  
Add the following bolded words/sentences to Activity 4.8 in the facilitators guide 

Activity 4.8: **Optional Read |** Emotional Loss of Control and Eating 
The purpose of this activity is to read an article from Janet Treasure who is a prominent researcher in the field of eating disorders in England. She will expand our learning around eating disorders to include a systemic lens and what including family could look like in the healing process. Her animal models are referenced in our EFFT text. **This is an optional activity for students.** 
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=15#tabs-tree-start
2. Unit # 4        Topic # 1        Activity# 4.8 
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse this is done
