### ISSUE TITLE
Changes to the Facilitators Guide in Unit 5

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#805]
**Which course contains the bug?**  
PSYC 339 OL SU 2023
 
 
**Describe the error and/or your suggestion**  
Eliminate the following bolded sentences under the Synchronous portion of unit 5 and the learning activities and assignments portion. 

Synchronous Portion
In the synchronous portion of this class, I would like you to facilitate a discussion around self care and what role they see stress playing in their lives, how they manage it and what are some strategies to manage stress. In all professions it is important to manage stress well, but particularly in this profession it has the potential to become an ethical issue if the stress is affecting your work with your client. Draw on the learning from this unit to enhance the discussion, particularly around how to ‘safeguard’ yourself from stress high-jacking you and how to build up resilience.

Spend some time going over activity 5.11 (The case study) in class; review the answers and invite discussion around how to interact with this case study as if they were your client.

Leave some time to go over any last minute questions on the paper, remind them that their oral presentations are supposed to be uploaded by today and that their one question and comment (completed in Microsoft streams) should be done in this next week **and that the open book quiz is made available by the end of class today until the beginning of class next week.**

 

Learning Activities and Assignment
For this course, there are very few activities that need to be completed. **If students are encouraged to complete all of them and to answer the questions about the sections, it will be a big help to them when they take their final open book quiz at the end of the course.** The readings for this course are taken from a variety of resources and it is important for students to experience gaining information/insight from a variety of resources as this will hopefully help them understand and shape them for their final paper. The instructions for each activity are written in Moodle.
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=15#tabs-tree-start
2. Unit # 5        Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse this is done
