### ISSUE TITLE
Changes to the Facilitators Guide Activity 5.3

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#806]
**Which course contains the bug?**  
PSYC 339 OL SU 2023
 
 
**Describe the error and/or your suggestion**  
please add the bold words/sentences to Activity 5.3 in the facilitators guide

Activity 5.3: **Optional Reflection |** Table 1.3 For Reflection 
The purpose of this activity is to provide students with the space, after they have learned about what stress is, to reflect on how stress shows up in their own lives and influences their day to day. This is the reflective integrative piece. **This is an optional activity for students.** 

 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=15#tabs-tree-start
2. Unit #  5       Topic # 1        Activity#  5.3
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse this is done
