### ISSUE TITLE
Changes to Facilitator Guide Activity 5.9

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#807]
**Which course contains the bug?**  
PSYC 339 OL SU 2023
 
 
**Describe the error and/or your suggestion**  
Please add the following bolded words/sentences to Activity 5.9 in the facilitators guide 

Activity 5.9: **Optional Activity |** Watch the Clip The purpose of this activity is to connect the power of sharing emotions to building up resilience. This will set the stage for the importance of doing EFFT with this kind of work. **This is an optional activity for students.** 
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=15#tabs-tree-start
2. Unit # 5        Topic # 3        Activity#  5.9
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
hello @emilyverse this is done
