### ISSUE TITLE
Changes to the Course Resources section in the Facilitators Guide

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#808]
**Which course contains the bug?**  
PSYC 339 OL SU 2023
 
 
**Describe the error and/or your suggestion**  
Reformat the following section of Course resources in the Facilitators Guide to look like this: 

Course Resources
 

Textbook
In the Realm of Hungry Ghosts by Gabor Mate
Emotionally Focused Family Therapy by Adele LaFrance
 

Other Resources
The following is a list of recommended texts. The PDF’s will be provided, however if students would like to explore more, here are some of the texts:

Being Mortal by Atul Gwande
The Body Keeps the Score by Bessel Van der Kolk
Counselling and Christianity: 5 Approaches by Stephen Greggrio & Timothy Sisemore
Experiencing Grief by H. Norman Wright
Psychology and Christianity: 5 Views by Eric L Johnson
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=15#tabs-tree-start
2. Unit # Course Resources Section        Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse this is done
