### ISSUE TITLE
Changes to the Assessment Details section in Facilitators Guide

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#809]
**Which course contains the bug?**  
PSYC 339 OL SU 2023
 
 
**Describe the error and/or your suggestion**  
Please change the following percentages: 

Case Conceptualizations = 20%
Oral Presentations = 20%
Research Paper = 35% 

and eliminate completely the Open Book Quiz section. 
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=15#tabs-tree-start
2. Unit #  Assessment details section       Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse this is done
