### ISSUE TITLE
Change to Unit 6 Synchronous and learning activities section in facilitator guide

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#810]
**Which course contains the bug?**  
PSYC 339 OL SU 2023
 
 
**Describe the error and/or your suggestion**  
Please eliminate the sentences in bold and add the sentences in italicized to the following sections in Unit 6 in the facilitators guide. 

Synchronous Portion
In the synchronous portion of this class, introduce our ethical obligation to not bring up our faith in counseling and how we reconcile this with our beliefs. Draw on the learning for this unit on what that could look like and what role integration does have in our therapy room. If there is time you can engage in a discussion around what self care would look like faith wise as there can be some burn out or crisis of faith around what we are and are not allowed to do.

Spend some time going over **6.19** _6.18_ case study to discuss the integration approach along with the application to the EFFT principles that we have been going over.

Leave some time for the students to fill in the SETL online for the course- I usually do this at the beginning of the class so that I don’t forget to leave time for it. Leave some time to answer any final questions about the research paper and the requirements that are laid out for it.

 

Learning Activities and Assignment
**There is a lot of reading attached to this unit. Therefore you can encourage students to read only the pdfs as they provide a succinct summary for each chapter and then invite the students to read the textbook chapters if they are interested in the subject and would like to learn more. Ideally it would be important to read both, and as the facilitator I would encourage you to read both to provide you with a richer view.**  _Students are required to watch the video clips that describe each view and then if they would like to explore it further, read the provided pdf summaries. The video clips, however are requirement enough in order to begin to get a feel for the material and start to facilitate their own thoughts on integration._ 

The layout has a slightly different format as we are talking about specific approaches to therapy and the role of faith in the counseling room instead of a mental health issue that could present itself. You may want to warn students about this ahead of time so they can mentally prepare themselves to receive the information. Also note that the amount of resources to access is a lot less so be prepared for more reading and less resources.
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=15#tabs-tree-start
2. Unit # 6        Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
hello @emilyverse this is done
