### ISSUE TITLE
Change Activity 6.1 in the Facilitators Guide 

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#811]
**Which course contains the bug?**  
PSYC 339 OL SU 2023
 
 
**Describe the error and/or your suggestion**  
Please delete the description for Activity 6.1 and change it to this: 

Activity 6.1: Watch “Introduction” Clip
The purpose of the video clips provided in this section is to help introduce the students to the complexity and importance of having an integration/views discussion. This section covers some of the practical reasons why it is important to cover these different approaches and why it is important for students to start formulating their own ideas around this. 

 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=15#tabs-tree-start
2. Unit # 6        Topic # 1        Activity# 6.1 
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse this is done
