### ISSUE TITLE
Changes to Activity 6.2 in Facilitator Guide 

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#812]
**Which course contains the bug?**  
PSYC 339 OL SU 2023
 
 
**Describe the error and/or your suggestion**  
Eliminate Activity 6.2 in the facilitators guide and replace it with this:

Activity 6.2: Watch “Levels of Explanation” Clip
The purpose of this activity is to go over the first of the five views of how we can view the integration between psychology and theology. Students are not required to adopt a certain view, it is simply supposed to evoke critical thinking. This activity also has a succinct summary of this view to help students expand their understanding of this view.
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=15#tabs-tree-start
2. Unit # 6        Topic # 1        Activity# 6.2 
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse this is done
