### ISSUE TITLE
Changes to activity 6.5 in facilitators guide

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#815]
**Which course contains the bug?**  
PSYC 339 OL  SU 2023
 
**Describe the error and/or your suggestion**  
Please eliminate activity 6.5 in the facilitators guide and replace it with this: 

Activity 6.5: Watch “A Christian Psychology View” 
The purpose of this next activity is to go over the third of the five views of how we can view the integration between psychology and theology. Students are not required to adopt a certain view, it is simply supposed to evoke critical thinking.
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=15#tabs-tree-start
2. Unit #  6       Topic #  2       Activity#  6.5
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse this is done
