### ISSUE TITLE
Eliminate activity 6.17 in facilitators guide

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#818]
**Which course contains the bug?**  
PSYC 339 OL SU 2023
 
 
**Describe the error and/or your suggestion**  
Completely eliminate activity 6.17 in the facilitators guide and then re-label the following two activities accordingly. So Activity 6.18 Summary PDF would turn to **Activity 6.17 Summary PDF** and Activity 6.19 Case study would turn to **Activity 6.18 Case Study**
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=15#tabs-tree-start
2. Unit # 6        Topic #  2 & 3       Activity#  6.17, 6.18, 6.19 
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse this is done
