### ISSUE TITLE
Update forum questions 

### ISSUE THREAD

**Issue by JulietTeeter** [TWUOnline/bug-tracking#821]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 PSYC 354 0L SP 2023
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 I changed the forum post questions in the assessment but didn't realize they are also here and are un-editable for me. 
 
**Location of the bug**  
https://learn.twu.ca/course/view.php?id=27104&section=3

Please change the grey box content to this:
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  After completing this unit, including the learning activities, you are asked to complete the Forum Post for Unit 3:

Most discussion postings should be no more than 300 words using full sentences and paragraphs. All postings should be carefully written and edited before being posted. Opinions should be well supported and cited according to APA 7th edition guidelines. Your responses should also be communicated in professional language, respectful of others, and to the point.

You are also asked to read your fellow learner’s postings and then respond to at least two other people.

1. There are different types of hormones and different functions of each. Pick one hormone, define it, identify what class of hormone it is, and explain why its function is important to you. 

2. Sleep is incredibly important but many people do not get enough sleep.  What are the four biological functions of sleep?  Which seems important to you and which sleep hygiene practices do you use to try to ensure you get enough sleep?

3. If you missed the synchronous class session this week, please respond to the following questions:  What are two things you learned from the session, and why are they significant? How will you apply them to your practice?
2. Unit #         Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by Jeff-TWU** [comment]
@JulietTeeter Updated.

**Comment by JulietTeeter** [comment]
Thank you!


Juliet Teeter, MA

Part time instructor of Psychology

Trinity Western University




________________________________
