### ISSUE TITLE
LDRS 472 Graphic Requests

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#823]
**What course/project is this request for?**
LDRS 472

**Describe the request**
@ikarlar please suggest unit graphics:

Unit 1: Jobs to Be Done Theory
Unit 2: Competitive Advantage
Unit 3: Alignment
Unit 4: Adapting Systems to Customer Choice
Unit 5: Measuring Results
Unit 6: Conclusion and Assessment

**Comment by Jeff-TWU** [comment]
@kmarjanovic I can start on this now, or wait for input.

**Comment by kmarjanovic** [comment]
Hi @Jeff-TWU - sorry, we've asked Karla to help with this project.  We'll give an update at our meeting tomorrow.

**Comment by Ikarlar** [comment]
Hello @kmarjanovic please let me know whether these graphs must have the titles of the units or if the titles are only used as a guide for the graphics.

**Comment by kmarjanovic** [comment]
Hi @Ikarlar! I would suggest without the title, as future course revisions may have title changes.  We can do a test run though for a unit and see how both options look?

**Comment by Ikarlar** [comment]
Hello, I have attached the graphics proposals with titles and without titles. Let me know if It's ok.

![Unit-1-JBDT-Name](https://user-images.githubusercontent.com/128835710/230212933-7e587c9c-1af2-46ad-ad11-018e0a3463cf.jpg)
![Unit-1-JBDT](https://user-images.githubusercontent.com/128835710/230212941-f5934730-d744-4347-8408-de0db7d19a8a.jpg)

![Unit-2-CA-Name](https://user-images.githubusercontent.com/128835710/230212997-6b4c1b7b-a1d9-42b8-a117-92228d3c6a5e.jpg)
![Unit-2-CA](https://user-images.githubusercontent.com/128835710/230213005-f0337f11-410a-4544-a100-fe2433952c76.jpg)

![Unit-3-A-Name](https://user-images.githubusercontent.com/128835710/230213020-cb6773c1-0bc2-48ac-ac98-cd2c596f0986.jpg)
![Unit-3-A](https://user-images.githubusercontent.com/128835710/230213024-ee90aeea-dd1a-4471-809e-81878df8962f.jpg)

![Unit-4-ASCC-Name](https://user-images.githubusercontent.com/128835710/230213059-b687e637-d425-4c4b-bb40-159f8c2d9e6e.jpg)
![Unit-4-ASCC](https://user-images.githubusercontent.com/128835710/230213062-0ea167ab-402d-4c7b-b473-196b35d17819.jpg)

![Unit-5--MR](https://user-images.githubusercontent.com/128835710/230213213-0fd214bd-5de4-424c-a9f0-25f493e98762.jpg)
![Unit-5-MR-Name](https://user-images.githubusercontent.com/128835710/230213215-bb27e9c4-9d10-4891-87f7-cfc6a267548f.jpg)

![Unit-6-CA-Name](https://user-images.githubusercontent.com/128835710/230213243-a5f98e6f-505d-42cc-9467-e767dd32f826.jpg)
![Unit-6-CA](https://user-images.githubusercontent.com/128835710/230213245-706a2cb2-191b-49db-b5fb-f1647620e967.jpg)

**Comment by kmarjanovic** [comment]
Thanks so much for these, Karla!  I think the graphics with the titles look best, so let's go with those. 
@Jeff-TWU how should we manage the graphics files?  Keep in this media git card, copy to [Media Repo](https://www.notion.so/twuid/Media-Repo-f6ff38edb27b4ca48f372da791f85e20)?
This course has no content yet, so I'm guessing first Production requests will be in July!

**Comment by Jeff-TWU** [comment]
> Thanks so much for these, Karla! I think the graphics with the titles look best, so let's go with those.
> @Jeff-TWU how should we manage the graphics files? Keep in this media git card, copy to [Media Repo](https://www.notion.so/twuid/Media-Repo-f6ff38edb27b4ca48f372da791f85e20)?
> This course has no content yet, so I'm guessing first Production requests will be in July!

@kmarjanovic Keeping it here on Github works fine for me.

**Comment by kmarjanovic** [comment]
Okay thanks!
