### ISSUE TITLE
TONE graphic request

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#826]
**What course/project is this request for?**
TONE series on Quality - see [notes](https://www.notion.so/twuid/TONE-2023-series-on-Quality-f86efe9a68f7428388ece8e814d9dcc5)

**Describe the request**
We can discuss as a group - but perhaps a graphic for the series - or for each of the 3 themes?
@Jeff-TWU please let me know what you think.

**Comment by Jeff-TWU** [comment]
@kmarjanovic I think a single graphic that captures the themes: _structure, connection, inclusion_  makes the most sense.

**Comment by kmarjanovic** [comment]
Sounds good to me!

**Comment by kmarjanovic** [comment]
Yes, no worries!  The TONE email to faculty will go out Tuesday, so ideally before then would be great.
Thanks Jeff!

**Comment by Jeff-TWU** [comment]
@kmarjanovic @MaraChequer Here is my first round. Feedback please!
![Quality](https://user-images.githubusercontent.com/66963480/228968368-0043f949-bc65-4207-a646-b84dbed3ae96.png)

**Comment by kmarjanovic** [comment]
Hi Jeff!  I like the white text one better.  Could we chat on Monday about this?
Perhaps we can make the 3 themes stand out a bit more - and maybe with some sort of icon that we can use throughout the series.
e.g. See this [image ](https://ecampusontario.pressbooks.pub/qualitycourses/ )and how it relates to the [chapters](https://ecampusontario.pressbooks.pub/qualitycourses/part/orientation-of-the-virtual-space-structuring-the-online-course/).
(Modules 1, 2, and 4 are basically our themes - and it's CC license, so we could play with their icons.

Another example [here ](https://www.kimep.kz/en/blog/2020/07/20/quality-online-course-design/)- but limiting to 3 key icons that match our themes.

**Comment by Jeff-TWU** [comment]
@kmarjanovic Thanks for the feedback. I have some ideas.

**Comment by kmarjanovic** [comment]
Thank you Jeff for this!!  Could you add to our media repo as well so we have a record of finished graphics?
https://www.notion.so/twuid/Media-Repo-f6ff38edb27b4ca48f372da791f85e20

**Comment by Jeff-TWU** [comment]
> Thank you Jeff for this!! Could you add to our media repo as well so we have a record of finished graphics?
> https://www.notion.so/twuid/Media-Repo-f6ff38edb27b4ca48f372da791f85e20

[Added](https://www.notion.so/twuid/Workshops-Graphics-73d7ef80a1cc43e1be7c2426681ab5b5?pvs=4#cb3fe179050440869bb8dc837c4af8b6).
