### ISSUE TITLE
LDRS 632 assessment edits

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#828]
**Which course contains the bug?**  
LDRS 632 - OL, IR, IN, N2 - and Master
(see here for links) https://learn.twu.ca/course/search.php?areaids=core_course-course&q=LDRS+632+SP+2023

**Describe the error and/or your suggestion**  
Please change Assessment percentages
<html>
<body>

Assessment | Value | Due
-- | -- | --
Expressive Change Exercises | 25% | Weeks 1-4
Case Study – Team Assignment | 25% | Weeks 4 & 6
The Hero’s Journey Report | 35% | Week 10
Substantive Participation | 15% | Weekly
Total | 100%

</body>
</html> 
 

In Assessment section, please change the percentages, as well as the due dates.

<html>
<body>

Assignment | Activity | Value | Due Date
-- | -- | -- | --
Expressive Change Exercises | The purpose of this assignment is to practice and experience Expressive Change through embodying the change learners want to create in their organizations. This new tool will empower students to be innovators of change. | 25% | Units 2, 4, 5
Case Study - Team Assignment | The purpose of the team assignment(s) is to practice collaborative, cohesive teamwork, while critically evaluating topical course materials and using the Case Study method. | 25% | Unit's 6 & 7
Change Initiative Consulting Report | This assignment will give you the opportunity to re-anchor what you have learned in this course by using it in a consultant scenario. You are to create a customized improvement plan for a company or organization using course resources | 35% | Unit 10
Substantive Participation | Each student is expected to approach every session well prepared; that is, they have processed ALL materials related to the topic of the day. | 15% | Every unit

<br class="Apple-interchange-newline">
</body>
</html>
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=23556
2. Course Intro page & Assessment pages

Please check assignment dropboxes are in the correct unit

**Comment by MeeksonHundoo** [comment]
Hello @kmarjanovic this has been updated

**Comment by kmarjanovic** [comment]
Thank you Meekson!
