### ISSUE TITLE
TONE 2023 page

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#830]
### Course
http://multi-access.twu.ca/tone/

### Instructions
- [ ] could you please create a section for the TONE 2023 series and add the write-up?

Thank you!

**Comment by Jeff-TWU** [comment]
@kmarjanovic [Added](http://multi-access.twu.ca/tone/spring-2023/overview). Let me know if you have any updates to the content. I'll make the bitly link shortly and confirm the email image then. The web writeup doesn't have a url in the image.

**Comment by kmarjanovic** [comment]
Hi @Jeff-TWU !  I realized I just closed this issue, but wondering if we can change the subtitle to What makes a quality TWU Online course?
And make that text slightly bigger?  I'm just adding to a calendar invite so want to make sure the info is readable.

**Comment by Jeff-TWU** [comment]
> What makes a quality TWU Online course?

@kmarjanovic Updated.

However Grav seems to be having an issue. 

@cmadland I updated things in [Github](https://github.com/TWUOnline/tone/blob/master/pages/07.spring-2023/01.overview/page.md). Cleared cache in [Grav](https://multi-access.twu.ca/tone/admin/dashboard), but still the new image is not showing up on [the site](http://multi-access.twu.ca/tone/spring-2023/overview).


![2_3quality](https://user-images.githubusercontent.com/66963480/232152885-2932fa2b-fd17-48d3-b270-c41fe406be36.png)

For email:
![20230304_Tone_Quality_2](https://user-images.githubusercontent.com/66963480/232152915-b14b3274-5b4f-4a94-bd50-0a49096a4f7c.png)

**Comment by kmarjanovic** [comment]
Thanks again, Jeff!
