### ISSUE TITLE
UNIV 301 Edits

### ISSUE THREAD

**Issue by dhanenburg** [TWUOnline/bug-tracking#833]
**Which course contains the bug?**  
UNIV 301 OL Master Course 
 
 
**Describe the error and/or your suggestion**  
I have many edits needed as I have changed the course materials. I am attaching a document of the changes. Please note, I already submitted a bug report for UNIT 1 and 2 but it has changes to the formatting of all 6 units (headings). This should be done first. This document is for UNIT 3-6 changes. Note that after Unit 1 and 2 changes are made, the headings may be different than what I indicated. Let me know if you want to meet by zoom or MS teams to review together.  
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=17766&section=9#tabs-tree-start
3. Unit #         Topic #         Activity#  
 
**Optional: Screenshots**  
[Bug Reports for UNIV 301 Master Course Unit 3-6.docx](https://github.com/TWUOnline/bug-tracking/files/11126981/Bug.Reports.for.UNIV.301.Master.Course.Unit.3-6.docx)

The file below needs to be added to the course (see bug report doc above for instructions)
[Praxis Schedule CURRENT FA22.docx](https://github.com/TWUOnline/bug-tracking/files/11126975/Praxis.Schedule.CURRENT.FA22.docx)

**Comment by MeeksonHundoo** [comment]
Hello @dhanenburg these edits have been implemented
