### ISSUE TITLE
WRSH 301 Rating Activity

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#836]
**What course/project is this request for?**
WRSH 301
**Describe the request**
I'm looking for a tool where students can select from 1-10 on the leadership qualities they deem effective . Here is the wording:

Activity 3.1: Self-Assessment on Leadership Beliefs  

We begin Unit 3 by examining some possible polarities within leadership. Imagine there is a sliding scale from 0 to 10 (left to right) for each category of what a leader seeks or demonstrates. For example, is leadership a gift from God that we are given, or is it more of an authoritative role that God has appointed?  Does it rely more on charisma or the abilities of a leader?  Consider each category and identify where you would lean. Which is more important for good, effective leadership?  

Polarities 

Giftings                      		OR             	 Authority/Title? 

Abilities 			OR             	Character? 

Power 		     		OR         		Servanthood? 

Charisma 	     		OR 		Abilities/Skill? 

Gifts of the Spirit  	OR 		Fruit of the Spirit (love, joy, peace, patience, kindness, generosity, faithfulness, gentleness, self-control)? 

Boldness/Audacity           	OR 		Vulnerability? 

Person (yourself)		OR 		the leadership Context? 

I don't think H5P fits, but please let me know if you've seem something similar.

**Comment by kmarjanovic** [comment]
This is one of those activities where there is no right answer - but meant for students to reflect and identify their preference/views.

I keep picturing just a sliding scale that they can manipulate, but with no 'check your answer'
Does that make sense?
I'll try to find an example of what I'm looking for...

**Comment by Jeff-TWU** [comment]
@kmarjanovic Will [this](https://forms.office.com/Pages/ResponsePage.aspx?id=VfFOK3MW70OkgCMMPUg_FqpusM9i9hlDtWqU5y-HIGxURURQNkY1MjNYWDE3TjRLWFJaQVROVVdLRiQlQCN0PWcu) work?

**Comment by kmarjanovic** [comment]
Yes I think that looks great!
I have a couple of questions...just need to check again with the SME to see if she wants to see the results.  I assume responses are anonymous?  It can just go to the online account, or the SME can make a copy?

**Comment by kmarjanovic** [comment]
Okay thanks Jeff!  I'll share and see what she thinks.

**Comment by Jeff-TWU** [comment]
> Okay thanks Jeff! I'll share and see what she thinks.

Made [a copy](https://forms.office.com/Pages/ResponsePage.aspx?id=VfFOK3MW70OkgCMMPUg_Fg5cSywncvZLnuK2im8B3TFUMEpPM05GN1FSRE00OVJERkhOVFpBQ1hHQiQlQCN0PWcu) in the [Learning Design group](https://forms.office.com/Pages/DesignPageV2.aspx?groupid=2c4b5c0e-7227-4bf6-9ee2-b68a6f01dd31). This way all IDs should have access to forms created.
