### ISSUE TITLE
LDRS 440 tables in bookdown

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#837]
**Which course contains the bug?**  
[LDRS 440](https://ba-leadership.github.io/ldrs440/)
 
 **Describe the error and/or your suggestion**  
Could we look at some other formats for tables in bookdown?

Here's one [example](https://bookdown.org/paul/ai_ml_for_social_scientists/01_introduction.html#causal-questions-why) that passed the WAVE accessibility test.
 
**Location of the bug**  
We can test them out in LDRS 440
- [ ] Unit 3  [Activity: Analyzing Your Organization](https://ba-leadership.github.io/ldrs440/strategic-analysis-understanding-a-firms-competitive-environment.html#activity-analyzing-your-organization)
- [ ] [Activity: Comparing Strategies](https://ba-leadership.github.io/ldrs440/strategic-analysis-understanding-a-firms-competitive-environment.html#activity-comparing-strategies)
- [ ] [4.2 Firm Vision and Mission](https://ba-leadership.github.io/ldrs440/strategic-management-process-achieving-sustaining-competitive-advantage.html#firm-vision-and-mission)
- [ ] [How Grand Strategies Are Translated into Objectives and Actions](https://ba-leadership.github.io/ldrs440/strategic-management-process-achieving-sustaining-competitive-advantage.html#how-grand-strategies-are-translated-into-objectives-and-actions)

I'll add more...but perhaps we can look at options first?

**Comment by Jeff-TWU** [comment]
@cmadland it looks like Kelly's [example](https://bookdown.org/paul/ai_ml_for_social_scientists/01_introduction.html#causal-questions-why) is rendering a plain HTML Table. I would guess this is just telling R how we want markdown tables to be rendered?

I'm having trouble rendering a wave report for the [example](https://bookdown.org/paul/ai_ml_for_social_scientists/01_introduction.html#causal-questions-why), so can't confirm it's working properly.

**Comment by Jeff-TWU** [comment]
@kmarjanovic I got the wave report for your example and compared it to what we have for 440, it looks like it's recognizing the markdown tables just as well as the HTML tables.

**Comment by cmadland** [comment]
What is missing in the default tables from Rmd?

**Comment by kmarjanovic** [comment]
Maybe this isn't a priority, but yes, could we discuss different styles?  In the examples I listed above, ([e.g.](https://ba-leadership.github.io/ldrs440/strategic-management-process-achieving-sustaining-competitive-advantage.html#how-grand-strategies-are-translated-into-objectives-and-actions)) it looks a bit messy without the vertical lines.  Just wanted to talk about options.
