### ISSUE TITLE
PSYC 339 Unit 3 link

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#838]
**Which course contains the bug?**  
PSYC 339 Master
 
**Describe the error and/or your suggestion**  
please add permalink to [Activity 3.5](https://learn.twu.ca/course/view.php?id=25486&section=4#tabs-tree-start)

There is an online version of [this article](https://twu.idm.oclc.org/login?url=https://search.ebscohost.com/login.aspx?direct=true&db=a9h&AN=33516401&site=eds-live&scope=site) available through TWU's library.

**Comment by MeeksonHundoo** [comment]
Hello @kmarjanovic this has been updated
