### ISSUE TITLE
Courses not loading content 

### ISSUE THREAD

**Issue by danielmingluito** [TWUOnline/bug-tracking#844]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 
 LDRS 623 and LDRS 627
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.

Moodle pages not loading. Gives the error as shown by the screen shots Students also reporting this issue.  Not an issue with past courses, only SU 2023 ones.
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=27889
2. https://learn.twu.ca/course/view.php?id=26301
3. Unit #         Topic #         Activity#   All units all pages 
 
**Optional: Screenshots**  
![Screen Shot 2023-04-15 at 9 35 01 AM](https://user-images.githubusercontent.com/65248898/232238409-23309786-ddb1-4243-9827-e92269aee247.png)
![Screen Shot 2023-04-15 at 9 35 24 AM](https://user-images.githubusercontent.com/65248898/232238413-46b2d218-c6e4-44b6-bdbc-1d903a72f550.png)

**Comment by danielmingluito** [comment]
Hi Jeff

I can see that the UDL Chart for Unit 2 Topic 1 works

However Can we still fix these


  1.  Under activity 2.3 - The Universal Design for Learning from Set BC, Link doesn't work. Please use https://wp.setbc.org/2015/06/bc-universal-design-for-learning/ - but warning they let the certificate expire so it's no longer an HTTPS site...
  2.  Stil Under activity 2.3 - The UDL Resource . - change link to this https://www.udlresource.com/ Current link does not work (it should be .com not .ca)



  1.  https://learn.twu.ca/course/view.php?id=26301&section=2
  2.  Unit # 2 Topic # 3 Activity# 2.3
  3.  https://learn.twu.ca/course/view.php?id=26301&section=2
  4.  Unit # 2 Topic # 3 Activity# 2.3



Sincerely,
Daniel To, Ed.D
Instructor, MA Leadership | TWU Global |
Trinity Western University | M 778.772.4992 | ***@***.***
Website https://www.twu.ca<https://www.twu.ca/>
Blog and Personal Site https://www.drdanielto.com<https://www.drdanielto.com/>
I would like to respectfully acknowledge the shared traditional territory of the Katzie, Semiahmoo, Kwantlen, and Coast Salish Peoples where I work, play and learn.



From: Jeff Snider ***@***.***>
Reply-To: TWUOnline/bug-tracking ***@***.***>
Date: Monday, April 17, 2023 at 9:22 AM
To: TWUOnline/bug-tracking ***@***.***>
Cc: Daniel To ***@***.***>, Mention ***@***.***>
Subject: Re: [TWUOnline/bug-tracking] Courses not loading content (Issue #844)


@danielmingluito<https://github.com/danielmingluito> Hi Daniel, I just tested above links and didn't see any issues. Please try again. If it's still not working for you, please try clearing your cache<https://kinsta.com/knowledgebase/how-to-clear-browser-cache/> first. Let me know if the issues persist and I'll escalate from there. Thanks!

**Comment by danielmingluito** [comment]
Sorry

I don’t see the changes active yet.

In 2.3 The Set BC Link is still not working

And the UDL link is still .ca and not .com

Thanks

Sincerely,

Daniel To, Ed.D
Instructor, MA Leadership | TWU Global |
Trinity Western University | M 778.772.4992 | ***@***.***
Website https://www.twu.ca<https://www.twu.ca/>
Blog and Personal Site https://www.drdanielto.com<https://www.drdanielto.com/>
I would like to respectfully acknowledge the shared traditional territory of the Katzie, Semiahmoo, Kwantlen, and Coast Salish Peoples where I work, play and learn.



From: Jeff Snider ***@***.***>
Reply-To: TWUOnline/bug-tracking ***@***.***>
Date: Monday, April 17, 2023 at 1:37 PM
To: TWUOnline/bug-tracking ***@***.***>
Cc: Daniel To ***@***.***>, Mention ***@***.***>
Subject: Re: [TWUOnline/bug-tracking] Courses not loading content (Issue #844)


Closed #844<https://github.com/TWUOnline/bug-tracking/issues/844> as completed.

**Comment by Jeff-TWU** [comment]
@danielmingluito 

Please note that the issues for [this ticket](https://github.com/TWUOnline/bug-tracking/issues/844) have been resolved. You have responded with comments related to [another ticket](https://github.com/TWUOnline/bug-tracking/issues/845) in this thread. Please note that your [other ticket](https://github.com/TWUOnline/bug-tracking/issues/845) is still in process. Thanks!

**Comment by danielmingluito** [comment]
Ohh hahah

Ok..thanks. Sorry about that.. Thanks

Sincerely,

Daniel To, Ed.D
Instructor, MA Leadership | TWU Global |
Trinity Western University | M 778.772.4992 | ***@***.***
Website https://www.twu.ca<https://www.twu.ca/>
Blog and Personal Site https://www.drdanielto.com<https://www.drdanielto.com/>
I would like to respectfully acknowledge the shared traditional territory of the Katzie, Semiahmoo, Kwantlen, and Coast Salish Peoples where I work, play and learn.



From: Jeff Snider ***@***.***>
Reply-To: TWUOnline/bug-tracking ***@***.***>
Date: Monday, April 17, 2023 at 1:47 PM
To: TWUOnline/bug-tracking ***@***.***>
Cc: Daniel To ***@***.***>, Mention ***@***.***>
Subject: Re: [TWUOnline/bug-tracking] Courses not loading content (Issue #844)


@danielmingluito<https://github.com/danielmingluito>

Please note that the issues for this ticket<https://github.com/TWUOnline/bug-tracking/issues/844> have been resolved. You have responded with comments related to another ticket<https://github.com/TWUOnline/bug-tracking/issues/845> in this thread. Please note that your other ticket<https://github.com/TWUOnline/bug-tracking/issues/845> is still in process. Thanks!
