### ISSUE TITLE
LDRS 623 Change link 

### ISSUE THREAD

**Issue by danielmingluito** [TWUOnline/bug-tracking#845]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 LDRS 623
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 1) Under Overview where it says "Click here to view chart in larger format change the link from what it is (it doesn't open) to https://udlguidelines.cast.org/ 

2) Under activity 2.3 - The Universal Design for Learning from Set BC, Link doesn't work.  Please use https://wp.setbc.org/2015/06/bc-universal-design-for-learning/ -  but warning they let the certificate expire so it's no longer an HTTPS site...

3) Stil Under activity 2.3 - The UDL Resource . - change link to this https://www.udlresource.com/   Current link does not work (it should be .com not .ca)

 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=26301&section=2
2. Unit #    2     Topic #     Overview     Activity#  Overview
3. https://learn.twu.ca/course/view.php?id=26301&section=2 
4.  Unit #    2     Topic #     3     Activity#  2.3
5.  https://learn.twu.ca/course/view.php?id=26301&section=2 
6. Unit #    2     Topic #     3     Activity#  2.3

Also you can take out "Photo Credit CAST" as my link goes to it - and the link for CAST doesn't open.
 
**Optional: Screenshots**

**Comment by Jeff-TWU** [comment]
@cmadland Grav is not updating changes from Git. I made changes a few times in Git, tried to clear cache but changes do not take effect.

@danielmingluito Do you have another another link for https://wp.setbc.org/2015/06/bc-universal-design-for-learning/   (without an expired security certificate) that we could use? We should not be sending students to an insecure site. Thanks!

**Comment by danielmingluito** [comment]
Can you do this link

https://www.learningdesigned.org/resource/set-bc-udl-self-directed-course

But title it different: title it

SET BC Learning Universal Design for Learning Self Directed Course

Thank you so much!

Sincerely,

Daniel To, Ed.D
Instructor, MA Leadership | TWU Global |
Trinity Western University | M 778.772.4992 | ***@***.***
Website https://www.twu.ca<https://www.twu.ca/>
Blog and Personal Site https://www.drdanielto.com<https://www.drdanielto.com/>
I would like to respectfully acknowledge the shared traditional territory of the Katzie, Semiahmoo, Kwantlen, and Coast Salish Peoples where I work, play and learn.



From: Jeff Snider ***@***.***>
Reply-To: TWUOnline/bug-tracking ***@***.***>
Date: Monday, April 17, 2023 at 1:55 PM
To: TWUOnline/bug-tracking ***@***.***>
Cc: Daniel To ***@***.***>, Mention ***@***.***>
Subject: Re: [TWUOnline/bug-tracking] LDRS 623 Change link (Issue #845)


@cmadland<https://github.com/cmadland> Grav is not updating changes from Git. I made changes a few times in Git, tried to clear cache but changes do not take effect.

@danielmingluito<https://github.com/danielmingluito> Do you have another another link for https://wp.setbc.org/2015/06/bc-universal-design-for-learning/ (without an expired security certificate) that we could use? We should not be sending students to an insecure site. Thanks!

**Comment by Jeff-TWU** [comment]
@danielmingluito That will work. Thanks! I'll get the changes out as soon as our system is behaving properly.
