### ISSUE TITLE
UNIV 301 OL Master

### ISSUE THREAD

**Issue by dhanenburg** [TWUOnline/bug-tracking#847]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 UNIV 301 OL Master
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
1.  Please change the title under "Activity 1.2" to Ungraded. 
2. ALso, please remove the first orange box at the bottom of this section that starts with "Go to the discussion forum tab..."
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=17766&section=3#tabs-tree-start
2. Unit #         Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @dhanenburg edits have been made
