### ISSUE TITLE
Production - WRSH 101 - Unit 5

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#85]
### Course
WRSH 101
### URL
https://learn.twu.ca/course/view.php?id=10744&section=5
### Instructions

- [x] Please add content from attached unit.

[WRSH101_Unit 5_Oct10_KM.docx](https://github.com/TWUOnline/bug-tracking/files/3759804/WRSH101_Unit.5_Oct10_KM.docx)

- [x] Also add videos from Scott: 

https://web.microsoftstream.com/channel/3886f568-9b8f-4a01-85eb-5349090e5bb9

**Comment by rezakh66** [comment]
@kmarjanovic all are done. please check if videos are in right order.

**Comment by cmadland** [comment]
Content was added last week, but it seems incomplete.

**Comment by cmadland** [comment]
See https://far.twu.ca/samc/wrsh101/u5/topic-1 and let me know if you want the info showing on the videos or not. (see top two videos) @kmarjanovic

**Comment by kmarjanovic** [comment]
yes - i'll just commit some things to atom.
learning activities need to be moved to subfolder.

**Comment by kmarjanovic** [comment]
I've edited the topics.  Could you move the learning activities to the subfolders?

**Comment by kmarjanovic** [comment]
All done.
