### ISSUE TITLE
LDRS 301 FAR Master Updates (re: new logo + update textbook info)

### ISSUE THREAD

**Issue by deannadams** [TWUOnline/bug-tracking#851]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 LDRS 301 FAR Master (this will update the upcoming LDRS 301 A SU23)
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 1. Please update the TWU logo on the Course Introduction page
 2. Update required text on Course Course Introduction page and each unit
 3. Update the learning activities with new textbook information

Please refer to attached list of updates needed. This list includes updates for Unit 1 -3 only. We will submit another bug report for the remaining units
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  
5. Unit #         Topic #         Activity#  
 
**Optional: Screenshots**  
[LDRS 301 FAR Master updates APRIL 20, 2023.docx](https://github.com/TWUOnline/bug-tracking/files/11289856/LDRS.301.FAR.Master.updates.APRIL.20.2023.docx)

**Comment by MeeksonHundoo** [comment]
Hello @deannadams updates have been implemented.

**Comment by deannadams** [comment]
Hi @MeeksonHundoo - thanks for making these changes. It's mostly done the way we were hoping, but I didn't mean for you to overwrite "Unit Readings" in the activities. Are you on campus tomorrow? Wondering if it's easier to sit together for a few minutes to look at it together?

**Comment by MeeksonHundoo** [comment]
Hello @deannadams unfortunately I will not be on campus. But I am happy to connect via zoom if that works for you?

**Comment by deannadams** [comment]
@MeeksonHundoo - perfect. Does 10am work for you tomorrow? I can send a calendar invite with Zoom link. I don't think it will take more than 15-20 minutes.

**Comment by MeeksonHundoo** [comment]
Sure! it does.

**Comment by deannadams** [comment]
@MeeksonHundoo - perfect. Invite sent.

**Comment by kmarjanovic** [comment]
Just checking whether we should use one of these banners instead?  We're using the blue one for MA Lead courses...maybe we use the other for BA Lead?  Thoughts? I'd prefer these banners over the one currently in [LDRS 301](https://learn.twu.ca/course/view.php?id=27776), but maybe we just need to resize?

![bannerblue](https://user-images.githubusercontent.com/35148983/233530930-8a909022-4d05-47a2-bbea-5b869c413b78.jpg)

![LogoOverview](https://user-images.githubusercontent.com/35148983/233530964-a048efba-3380-45a8-bddc-518a4ff4ea02.jpg)

Also DeAnn & Cynthia - do you want us to change the settings to the horizontal tabs (OneTopic setting we used to have), or the dropdown one currently in the course (Topics setting).  Note, in September all courses will go back to the default OneTopic (my preference!;)

**Comment by deannadams** [comment]
Thanks Kelly... was going to talk to Meekson about that this morning.
Can we use the blue one?


DeAnn Adams

Director, Faculty Services and Development
TWU GLOBAL

**Comment by kmarjanovic** [comment]
@deannadams for sure!

**Comment by deannadams** [comment]
Looks great!!
Thanks Kelly.


DeAnn Adams

Director, Faculty Services and Development
TWU GLOBAL

**Comment by deannadams** [comment]
@MeeksonHundoo - how long does it usually take for the changes to push through. I don't see them yet even though we went through them about 90 minutes ago? Hoping Cynthia and I get get the rest of the changes to you next week, as I think you mentioned you were going to be away on May 3 or so?

**Comment by MeeksonHundoo** [comment]
Hello @deannadams the changes happen instantly, but GIT behaves weird at times, and we have to go to GRAV and clear cache and sync GIT. But the changes have taken place. Could you just refresh your course page. Here is the link:
https://learn.twu.ca/course/view.php?id=27776#section-0

**Comment by deannadams** [comment]
@MeeksonHundoo - got it... all looks good now. Thanks so much!! Will be in touch soon about the rest of the changes.
