### ISSUE TITLE
LDRS 664 Activity Checklists

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#852]
**Which course contains the bug?**  
https://ma-lead.github.io/ldrs664/the-heart-of-a-teacher.html#activity-checklist
 
 
**Describe the error and/or your suggestion**  
Could we update the Activity Checklists to our new format?  We may showcase this course at our TONE section.
Thank you!

**Comment by Jeff-TWU** [comment]
@kmarjanovic I [revamped all units](https://ma-lead.github.io/ldrs664/the-heart-of-a-teacher.html) and the [Assessment page](file:///Users/jeff/Documents/GitHub/ma-lead/ldrs664/docs/assessment-10.html). 

Let me know what you think.

I will update the course description once we have a consensus on the blocks/colours.

- I moved  the questions images  (units 1-6) to the top and added alt text. They were being used (without alt text) as text content. Added questions as text where the images were. The images are a little redundant now (but they look nice).
- Other units have no header image. It would be nice to refresh all new image headers on all units.

**Comment by kmarjanovic** [comment]
The assessment section looks great!! Thanks Jeff!

For the question images, I agree it looks better at the top.  I'll need to check with the SME though, as those questions are meant to be introduced at the end of the Overview section.  It should be fine though.
Yes, I'll reach out again for those last guiding questions that were requested.

**Comment by kmarjanovic** [comment]
whoops! my mistake!  Yes, the graphics for the rest of the units were approved.  Please add the missing question pics from here: https://www.notion.so/twuid/LDRS-664-Graphics-a4f4a9bcbd394be0b47d95ba547e809c

**Comment by Jeff-TWU** [comment]
> whoops! my mistake! Yes, the graphics for the rest of the units were approved. Please add the missing question pics from here: https://www.notion.so/twuid/LDRS-664-Graphics-a4f4a9bcbd394be0b47d95ba547e809c

[Updated](https://ma-lead.github.io/ldrs664/the-role-of-information-and-perception-in-choosing-strategies-and-an-appropriate-leadership-model.html).

Also note that some videos have embedding disabled by the Youtuber, for those I've removed the embed code and just left the link.
![Screen Shot 2023-04-21 at 2 30 38 PM](https://user-images.githubusercontent.com/66963480/234055657-f5483e7b-146f-482b-b08d-0eb86e3e5410.png)

**Comment by kmarjanovic** [comment]
Thanks so much Jeff!
