### ISSUE TITLE
Psych 331 Unit 1: overview

### ISSUE THREAD

**Issue by Mike2625** [TWUOnline/bug-tracking#854]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 Psych 331
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 
 Overview: under resources, please delete section re: "case of Stan Video" and instead state the following:
"The Case of Stan Video": will be seen in class 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  
2. Unit #         Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @Mike2625 this is done
