### ISSUE TITLE
Psych 331: unit 1 Learning activity 1.2

### ISSUE THREAD

**Issue by Mike2625** [TWUOnline/bug-tracking#855]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 
 Psych 331
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 Activity 1.2: Delete "read chapter one sections 1-4...." and instead write the following:

Read in chapter one the section noting "Overview of the Theory Chapters" (table 1.1)
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  
2. Unit #   1      Topic #   1.2      Activity#  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @Mike2625 this is done
