### ISSUE TITLE
Psych 331: Unit 2 Overview Learning Activity 2.4

### ISSUE THREAD

**Issue by Mike2625** [TWUOnline/bug-tracking#857]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 
 Psych 331 : unit 2 Overview
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 Learning Activity 2.4:

Delete what is said and state the following:
We will watch during class time: "The Case for Stan"
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  
2. Unit #  2       Topic #    2.4     Activity#  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @Mike2625 this is done
