### ISSUE TITLE
Psych 331: Unit 2 Topic 1

### ISSUE THREAD

**Issue by Mike2625** [TWUOnline/bug-tracking#858]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 Psych 331; topic 1  activity 2.1
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 Delete the first section noting "watching the video" instead state the following:

  After watching this video in class, consider the following questions that you will discuss in breakout sessions:
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  
2. Unit #         Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @Mike2625 this is done
