### ISSUE TITLE
Psych 331 Unit 2 Activity 2.4

### ISSUE THREAD

**Issue by Mike2625** [TWUOnline/bug-tracking#859]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 Psych 331 : activity 2.4
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 Keep first sentence: read chapter five....

Delete the following paragraph and instead state the following:

We will watch in class the video of the "Case of Stan".  Please read chapter five "Adlerian Therapy Applied to the Case of Stan" then in the moodle answer the questions under "Questions for Reflection" under the "Case for Stan" (page 122 in the text book)
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  
2. Unit #         Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @Mike2625 this is done
