### ISSUE TITLE
Psych 331: Unit 2 summary page

### ISSUE THREAD

**Issue by Mike2625** [TWUOnline/bug-tracking#860]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 psych 331 :summary page unit 2
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 Questions for Reflection: omit what is written about ruth instead state the following:

Do Questions for Reflection in chapter 5 in the section: "Adlerian Therapy Applied to the Case of Stan"
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  
2. Unit #         Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @Mike2625 this is done
