### ISSUE TITLE
Pysch 331: Unit 3  Topic 1

### ISSUE THREAD

**Issue by Mike2625** [TWUOnline/bug-tracking#861]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 
 psych 331; unit 3 topic 1 Activity 3.2 and Activity 3.3
**Describe the error and/or your suggestion**  
---A clear and concise description of what the error or suggestion is.
 Take out read section 7-3C..instead state the following:

Read in chapter 7 the sections entitled: "Client's Experience in Therapy" and "Relationship Between Therapist and Client"

---Section 3.3: take out the sentence of Emotionally Focused Therapy and Maslows Hierarchy and instead state the following:
   Pay particular attention to the sections entitled: "Emotionally Focused Therapy" and "Abraham Maslow's Contribution to Humanistic Psychology".  Please google "Maslows Heirarchy of Needs" and look at his stages of growth.

 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  
2. Unit #         Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @Mike2625 this is done
