### ISSUE TITLE
Psych 331: Unit 3 Topic 2 Activity 3.4

### ISSUE THREAD

**Issue by Mike2625** [TWUOnline/bug-tracking#862]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 Psych 331: Unit 3 Topic 1; Activity 3.4
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 Take out: "The Questions for Reflections in section...."

Instead write the following:
You will find the "Questions for Reflection" in each of the three chapters (6,7 and 8) in the "Case for Stan" in the textbook on pages: 157, 187 and 122.
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  
2. Unit #         Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @Mike2625 this is done
