### ISSUE TITLE
Psych 331: Unit 3 Assessment section

### ISSUE THREAD

**Issue by Mike2625** [TWUOnline/bug-tracking#863]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 Psych 331; Unit 3 Assessment section; Questions for Reflection section
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 
 Please mirror the exchange from the mindtap to what I put in the previous bug report in Unit 3.  Match what I put in the previous bug report
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  
2. Unit #         Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @Mike2625 this is done
