### ISSUE TITLE
Psych 331: Unit 4 Topic 2

### ISSUE THREAD

**Issue by Mike2625** [TWUOnline/bug-tracking#864]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 
 Psych 331: Unit 2 Topic 2
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 Ellis section: Simple change..Change page 275 to 273 in the textbook

Aaron Beck section: change pages from page 282 to pages 281-284 in the textbook
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  
2. Unit #         Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @Mike2625 this is done
