### ISSUE TITLE
Production - LDRS 300 - U3 pwpt

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#87]
### Course
LDRS 300
### URL
https://learn.twu.ca/course/view.php?id=10828&section=3

https://github.com/TWUOnline/ba-lead/blob/master/pages/04.ldrs300/09.U3/ldrs300-u3.docx

### Instructions
Presentations plugin isn't working! Please fix.  Unit 3 Topic 3
Should we have the pwpt available as well in case this happens?

**Comment by mattdennis15** [comment]
https://github.com/TWUOnline/ba-lead/commit/5a3af3344508ac012d06f76784a8709f0bb3259c
Slides are working

**Comment by kmarjanovic** [comment]
Thank you!

@cmadland - In Brenda's slides there are references to videos.  Are these clickable in Presentations plugin?

e.g. slide 13 - 
https://www.youtube.com/watch?v=Cswrnc1dggg

**Comment by cmadland** [comment]
no, they are not hyperlinked

**Comment by kmarjanovic** [comment]
Okay, we need to modify those slides then.  I'll change this.

Could ATAs flag when there is a link in a Presentation?

**Comment by cmadland** [comment]
We are not checking the content of the slides, all we do is export to images and put the images into a presentation.

I will see if there is a way to hyperlink the entire image.

**Comment by kmarjanovic** [comment]
Okay - there are usually a couple in each presentation.
In unit 1 I pulled these out into the lesson, but there hasn't been time to do this.

**Comment by cmadland** [comment]
"... but there hasn't been time to do this."

quote of the year

**Comment by kmarjanovic** [comment]
lol :)

**Comment by cmadland** [comment]
check teh presentation now...slide 14 is the video

**Comment by kmarjanovic** [comment]
I see it in Github, just not in Moodle yet.

**Comment by cmadland** [comment]
I can see it in moodle

**Comment by kmarjanovic** [comment]
Perfect! Thank you!
