### ISSUE TITLE
Link not working in Activity 3.5

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#870]
**Which course contains the bug?**  
PSYC 330 OL SU 2023
 
 
**Describe the error and/or your suggestion**  
The link for the following article is not working in this activity. 
Blevins, S. (2008). A Personal Journey through the Grief and Healing Process with Virginia Satir, Dr. E. Kubler-Ross, and J. William Worden. Satir Journal, 2(2), 89–105.
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=4#tabs-tree-start
2. Unit # 3        Topic #  2       Activity# 3.5 
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse I've fixed the link now
