### ISSUE TITLE
Files not embedded in Activity 3.6 & 3.7

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#871]
**Which course contains the bug?**  
PSYC 339 OL SU 2023
 
 
**Describe the error and/or your suggestion**  

The files for these two activities are not embedded for activities 3.6 & 3.7. The pdfs are attached as files the bottom of the page. Activity 3.6 needs Being Mortal Chapter 1 and Activity 3.7 needs Being Mortal Chapter 2
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=4#tabs-tree-start
2. Unit # 3        Topic # 2        Activity# 3.6 & 3.7 
[Being Mortal Ch. 1.pdf](https://github.com/TWUOnline/bug-tracking/files/11434683/Being.Mortal.Ch.1.pdf)

 [Being Mortal Ch.2.pdf](https://github.com/TWUOnline/bug-tracking/files/11434684/Being.Mortal.Ch.2.pdf)

**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse this is done
