### ISSUE TITLE
Link not work for activity 4.12

### ISSUE THREAD

**Issue by emilyverse** [TWUOnline/bug-tracking#872]
**Which course contains the bug?**  
PSYC 339 OL SU 2023
 
 
**Describe the error and/or your suggestion**  
In Activity 4.12 The link for the article brings you to a page that you have to pay for the article. Please embed the following pdf instead. (Thanks!) 
 
 
[Depression and Suicide.pdf](https://github.com/TWUOnline/bug-tracking/files/11449367/Depression.and.Suicide.pdf)

**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28112&section=5#tabs-tree-start
2. Unit #  4       Topic # 2        Activity#  4.12
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @emilyverse this is done
