### ISSUE TITLE
LDRS 504 in Moodle Books

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#874]
### Course
[LDRS 504 (6 week MASTER - 2023)](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.twu.ca%2Fcourse%2Fview.php%3Fid%3D28349%26section%3D0%23tabs-tree-start&data=05%7C01%7CKelly.Marjanovic%40twu.ca%7Cdd932079d4634413857a08db55844b4e%7C2b4ef155167343efa480230c3d483f16%7C0%7C0%7C638197798907052025%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=R4CS%2FiW47Zff6Ot1DE0MZkusS6bs3OBcPxdpHdqTpp0%3D&reserved=0)

https://ma-lead.github.io/ldrs504/

### Instructions
- [ ] Please create all of the Moodle Books for LDRS 504 for Units 1-9.
- [ ] Please take out all assessment info, as different sections will have different assignments

**Comment by kmarjanovic** [comment]
@Nataliadsanchez, once the books are in, could you review and add assignment dropboxes from the assignments outlined in Paul's syllabus?
[LDRS 504 Syllabus -- Spr 2023--PWC version-Chamberlain.docx](https://github.com/TWUOnline/bug-tracking/files/11483723/LDRS.504.Syllabus.--.Spr.2023--PWC.version-Chamberlain.docx)

Once the master is ready, we will need to import into Paul's summer section, which starts June 13th.
[LDRS 504 A (SU 2023)](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.twu.ca%2Fcourse%2Fview.php%3Fid%3D27879%26section%3D5%23tabs-tree-start&data=05%7C01%7CKelly.Marjanovic%40twu.ca%7Cdd932079d4634413857a08db55844b4e%7C2b4ef155167343efa480230c3d483f16%7C0%7C0%7C638197798907052025%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=nPDXaqAQQpOBXLkSoQ6YDSFHhdzhLNJ%2FVZMcmPZMkjk%3D&reserved=0)

**Comment by Jeff-TWU** [comment]
@kmarjanovic @Nataliadsanchez [All Moodle Books have been added](https://learn.twu.ca/course/view.php?id=28349&section=0#tabs-tree-start).

**Comment by Nataliadsanchez** [comment]
Thanks @Jeff-TWU!!

[Assignments instructions ](https://learn.twu.ca/course/view.php?id=28349&section=8)have been added as well. @kmarjanovic, only files (no dropboxes) were added since Paul prefers students to email assignments directly to him. He has mentioned this requirement in each assignment.

**Comment by kmarjanovic** [comment]
Thank you @Jeff-TWU and @Nataliadsanchez!!  You are both amazing!!!
