### ISSUE TITLE
Assessment in bookdown

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#875]
**Which course contains the bug?**  
[LDRS 504 in Bookdown](https://ma-lead.github.io/ldrs504/assessment-9.html) 
 
**Describe the error and/or your suggestion**  
Could you please take out the assessment info in the [Assessment section](https://ma-lead.github.io/ldrs504/assessment-9.html#assignment) in Bookdown and replace with the Assignment info from the [LDRS504dev Moodle course](https://learn.twu.ca/course/view.php?id=13615&section=1#tabs-tree-start)?

Note that the assignments in Paul's course (using 6 week Master) are different, but the bookdown should show the original assignments for Mark to review.

Also - I've seen this before in courses where the assessment section shows assignment [664 info](https://ma-lead.github.io/ldrs664/assessment-10.html).  Is this the template?  Could this be taken out of the template?

**Comment by MeeksonHundoo** [comment]
Hello @kmarjanovic i am working on this

**Comment by MeeksonHundoo** [comment]
Hello @kmarjanovic this is done
