### ISSUE TITLE
LDRS 301 updates

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#876]
**Which course contains the bug?**  
LDRS 301 FAR Master 
 
**Describe the error and/or your suggestion**  
Please see the attached requests.
[LDRS 301 FAR Master updates APRIL 20 2023.docx](https://github.com/TWUOnline/bug-tracking/files/11493811/LDRS.301.FAR.Master.updates.APRIL.20.2023.docx)

If possible, Cynthia would like this completed in the next day or two.

Cynthia (not sure if she has a Git account) or @deannadams , feel free to make comments/edits on this card as well.

**Comment by CynthiaMcCarthy** [comment]
Hello again! This course is almost finished, and I have tried to alert students to the correct names/chapter titles etc. However, I would really appreciate these updates being completed ASAP. 
If I had access, I would have done it. It should take only ~1 hour. :) Thank you!

**Comment by MeeksonHundoo** [comment]
Hello @CynthiaMcCarthy Apologies for the delay. These edits have been made.
