### ISSUE TITLE
LDRS 330-Graphics

### ISSUE THREAD

**Issue by MaraChequer** [TWUOnline/bug-tracking#877]
**What course/project is this request for?**
LDRS 330

**Describe the request**
Hello Karla, please help me recreate these graphics for the course:) 

**Additional context**
UNIT 1

**Priority**
Medium**
![image](https://github.com/TWUOnline/bug-tracking/assets/84353161/c0a92a34-e038-424e-8c55-38f0e43bf042)
![image](https://github.com/TWUOnline/bug-tracking/assets/84353161/a24bad17-c79b-44a0-9b55-8f64734a37cc)
![image](https://github.com/TWUOnline/bug-tracking/assets/84353161/c1cf6fe4-b972-421b-b751-4017ea2ab285)

**Comment by Ikarlar** [comment]
Hi Mara I attached the first image proposal, tell me if it works

![Image1_Framework-of-Problems](https://github.com/TWUOnline/bug-tracking/assets/128835710/80bd719b-871f-4e15-a513-7848dc6a93aa)

**Comment by Ikarlar** [comment]
Hello Mara, I attach the proposals of the graphics, for the first one I changed the size.

![Image1_Framework-of-Problems-2](https://github.com/TWUOnline/bug-tracking/assets/128835710/a9cd27fa-f986-4f7d-a399-1a55cb27fdc5)

Figure 2
![Image2_Figure-2](https://github.com/TWUOnline/bug-tracking/assets/128835710/43e2fa7e-fc5b-450c-8c95-a605d2e1ee1e)

**Comment by MaraChequer** [comment]
Thank you so much Karla! They look great!

**Comment by Ikarlar** [comment]
Hello Mara, I attach the last graphic proposal, tell me if they work for you and if you need something else :)

![Image3_Figure-3](https://github.com/TWUOnline/bug-tracking/assets/128835710/7b917a18-6d95-4e30-b8ab-8dd3ac477609)

**Comment by MaraChequer** [comment]
Thank you so much Karla :)! You are so great. Before you move on to another task, there are three small details to check. 
Highlighted: 
-Idea**l**s
-ou**r**
-?
![image](https://github.com/TWUOnline/bug-tracking/assets/84353161/e06b6498-9108-4cd5-a5d3-1b149b1f7ed0)

Thanks again! Loving what you do

**Comment by Ikarlar** [comment]
Hi Mara, here are the changes.

I changed the color of the bullets in the first image because I realized there was an accessibility issue, so I made the necessary modifications 
![Image1_Framework-of-Problems-3](https://github.com/TWUOnline/bug-tracking/assets/128835710/8bed9fc6-b48a-4211-a62e-4ec90a5cf483)

![Image3_Figure-3-2](https://github.com/TWUOnline/bug-tracking/assets/128835710/6331bce3-2ed6-4695-9639-8aab5b2a18f3)

**Comment by MaraChequer** [comment]
Thank you so much Karla! They are perfect 👍
