### ISSUE TITLE
Production LDRS 664 bookdown

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#878]
### Course
https://ma-lead.github.io/ldrs664/

### Instructions
- [x] Please update welcome section to our new template (see [440](https://ba-leadership.github.io/ldrs440/)) - just welcome & course notes sections (with navigation, units, activities sub section)
- [x] Note that BA Lead lists assessments as Personal Application - all others say Assessment, so please use Assessment in this course.

Thanks!

**Comment by MeeksonHundoo** [comment]
Hello @kmarjanovic I'll work on this

**Comment by MeeksonHundoo** [comment]
Hello @kmarjanovic this is done. Here is the link https://ma-lead.github.io/ldrs664/index.html
