### ISSUE TITLE
ANTH 101 bookdown homepage

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#879]
### Course
https://twu-fhss.github.io/anth101/

### Instructions
- [ ] Please update the home page of bookdown courses to reflect just the welcome & course notes sections (with navigation, units, activities sub section)
- [ ] See [LDRS 440](https://ba-leadership.github.io/ldrs440/) as an example 

Also @Jeff-TWU you mentioned there's a way to download word docs of bookdown.  Could you set this up for ANTH 101?  The instructor would like to edit the materials using the original docs, but this might work better.

**Comment by Jeff-TWU** [comment]
Hi @kmarjanovic, I've added the ability to export docs when rendering a book. Book will appear in the [doc folder](https://github.com/twu-fhss/anth101/blob/main/docs/anth101.docx).

Please note that this is still experimental, It's not as nicely formatted as I'd like, there are some issues.

**Comment by kmarjanovic** [comment]
@Jeff-TWU this is great!!  Thank you so much!

**Comment by Jeff-TWU** [comment]
> @Jeff-TWU this is great!! Thank you so much!

@kmarjanovic Following up on this. Meher was having an issue building this book with the doc feature enabled. It has been temporarily disabled. 

@cmadland This seems to be related to permissions to the [external doc file](https://twuonline.github.io/course-materials/bookdown_style.docx). Is it possible to give @meher-ahmed read/write access to [course materials](https://github.com/TWUOnline/course-materials/)? I think this would likely solve it.

**Comment by kmarjanovic** [comment]
@meher-ahmed please hide the Course Description and other items below on [this ](https://twu-fhss.github.io/anth101/welcome.html)page.

**Comment by meher-ahmed** [comment]
sure @kmarjanovic

**Comment by meher-ahmed** [comment]
@kmarjanovic I am not sure about the course description page. I usually don't work on these pages could you please let me know on what exactly you would want me to change?

**Comment by meher-ahmed** [comment]
> @meher-ahmed please hide the Course Description and other items below on [this ](https://twu-fhss.github.io/anth101/welcome.html)page.

Issue resolved @cmadland @kmarjanovic
