### ISSUE TITLE
Production-LDRS 300 U5 broken link

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#88]
### Course 
LDRS 300

### URL
https://learn.twu.ca/course/view.php?id=10828&section=5

https://github.com/TWUOnline/ba-lead/blob/master/pages/04.ldrs300/11.U5/02.topic-1/section.md

Unit 5 Topic 1 - last line

### Instructions
This link should be working, but currently opens in Moodle to a 404 page. Temporary glitch?

In GitHub
- Blog: [3 Ways Simon Sinek’s book "Why Leaders Eat Last" Changed my
    Life](https://medium.com/@JohnMashni/3-ways-simon-sineks-why-leaders-eat-last-changed-my-life-3273e90a317)
    by John Mashni

**Comment by mattdennis15** [comment]
The link appears to be working as it should now.
