### ISSUE TITLE
TWU banner for LDRS 620

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#881]
**Which course contains the bug?**  
[LDRS 620- Worldview FDN of Educ Leadership (FAR MASTER)
](https://learn.twu.ca/course/view.php?id=15710&section=0#tabs-tree-start)
 
 
**Describe the error and/or your suggestion**  
Please replace logo on the home page with the new banner
 
 
![bannerblue](https://github.com/TWUOnline/bug-tracking/assets/35148983/74fe85f4-93e0-475c-b936-80c2b45a2b6f)

**Comment by MeeksonHundoo** [comment]
Hello @kmarjanovic this is done
