### ISSUE TITLE
Top course menu bar mission options 

### ISSUE THREAD

**Issue by Sonya1974** [TWUOnline/bug-tracking#883]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 
 PSYC 215 OL 2023 Cameron 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 
 I read that some system-wide Moodle changes were made.  I notice that on my course, PSYC 215 OL SU 2023 Cameron, that the structure or format of the course is different.  

BEFORE - the top bar menu for the course, under the course title, had options of hyperlinking to Week 1, Week 2... It also had a tab for Assignments.  

NOW - the top bar menu doesn't have those options.  Students and I will need to scroll down through all the pages to get to the Week we want, to find a place to read about or submit assignments...  

Is this a system change, a settings change, an error??  If possible, I would like my course to have the full options on the top menu bar again.  I cannot even find the Assignments option.   

**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  
2. Unit #         Topic #         Activity#  
 
https://learn.twu.ca/course/view.php?id=28107 
Location is horizontal menu bar for the course, right under the course title. 

**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @Sonya1974 I've changed this. The tabs are on the top now. Here is the link:
https://learn.twu.ca/course/view.php?id=28107&section=0

**Comment by Sonya1974** [comment]
Thanks so much!!  
Sonya
