### ISSUE TITLE
PSYC 411 edits & google doc help

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#889]
**Which course contains the bug?**  
[PSYC 411 OL - Psychology and Spirituality (SU 2023)](https://learn.twu.ca/course/view.php?id=28115)

[PSYC 411: Psychology and Spirituality (Master)](https://learn.twu.ca/course/view.php?id=22610)
 
 
**Describe the error and/or your suggestion**  
Request from Debra Ivancovich:
1. On the assessment page please delete the Presentation.  Please change the values to:
 
The Values should be:
Disc Forum- 20%
Contemplative retreat:
Proposal 5%
Reflection: 10%
Wiki assignment: 10%
EHS Workbook: 10%
Religious Genogram: 15%
Integrative Reflection: 30%

2. Please make the value changes to the gradebook as well.

3. As well, I need help adding a Google doc for the wiki assignment.  

@barishgolland or @MeeksonHundoo could you please set up a meeting with Debra to help her with this?

**Comment by MeeksonHundoo** [comment]
Hello @kmarjanovic I'll set it up. Sorry for responding late. I had lost access to my twu.ca email account and got it recovered last night.

**Comment by MeeksonHundoo** [comment]
Hello @kmarjanovic got all the changes done as requested by Debra.
