### ISSUE TITLE
PSYC 331 gradebook edit

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#891]
**Which course contains the bug?**  
[PSYC 331 OL - Theories of Counselling (SU 2023)](https://learn.twu.ca/grade/report/grader/index.php?id=28111) 
 
**Describe the error and/or your suggestion**  
In the gradebook, please get rid of the "presentation" section.  See weighting in [home page](https://learn.twu.ca/course/view.php?id=28111&section=0#tabs-tree-start)

**Comment by MeeksonHundoo** [comment]
Hello @kmarjanovic this is done. I also fixed the DQ forums, they were not setup for grading.
Here is the link to the grade book : https://learn.twu.ca/grade/edit/tree/index.php?id=28111
