### ISSUE TITLE
Production - LDRS 400

### ISSUE THREAD

**Issue by Nataliadsanchez** [TWUOnline/bug-tracking#893]
### LDRS 400

**URL:** https://ba-leadership.github.io/ldrs400/
**Moodle:** https://learn.twu.ca/course/view.php?id=30175&section=0#tabs-tree-start

Please create bookdown and upload:
- [x] Unit 1
- [x] Unit 2
- [x] Unit 3
- [x] Unit 4
- [x] Unit 5
- [ ] Assessment

Required files:
[U1_LDRS 400 - v.13.07.23.docx](https://github.com/TWUOnline/bug-tracking/files/12042692/U1_LDRS.400.-.v.13.07.23.docx)
[U2_LDRS 400 - v.13.07.23.docx](https://github.com/TWUOnline/bug-tracking/files/12043717/U2_LDRS.400.-.v.13.07.23.docx)
[U3_LDRS 400 - v.13.07.23.docx](https://github.com/TWUOnline/bug-tracking/files/12099753/U3_LDRS.400.-.v.13.07.23.docx)
[U4_LDRS 400 - v.13.07.23.docx](https://github.com/TWUOnline/bug-tracking/files/12045355/U4_LDRS.400.-.v.13.07.23.docx)
[U5_LDRS 400 - v.18.07.23.docx](https://github.com/TWUOnline/bug-tracking/files/12100046/U5_LDRS.400.-.v.18.07.23.docx)
[LDRS 400_Assessment_v.19.07.23.docx](https://github.com/TWUOnline/bug-tracking/files/12100049/LDRS.400_Assessment_v.19.07.23.docx)

**Comment by Nataliadsanchez** [comment]
**Unit 2:**

- [ ] Figure 1.2: Communication Model. Could you please remake this?
- [ ] Figure 1.1 was taken from https://www.communicationtheory.org/berlos-smcr-model-of-communication/ Please add the...
- [ ] SME did not know how to site this reference: Westman, L. (2017). Understanding people, mental health and trauma. You will find it highlighted in the Word doc. She attached a picture about it. If you have any idea about how to site it, please modify the reference.

**Comment by MeeksonHundoo** [comment]
Hello @Nataliadsanchez I'll work on putting these in bookdown...!

**Comment by Jeff-TWU** [comment]
>  - [ ] Figure 2.2: Communication Model. Could you please remake this?

@Nataliadsanchez Does this work? Let me know if you'd like any changes.

![Communication Model](https://github.com/TWUOnline/bug-tracking/assets/66963480/15f2be89-28a6-4de5-9cc8-eab0abdded95)

**Comment by Nataliadsanchez** [comment]
> > * [ ]  Figure 2.2: Communication Model. Could you please remake this?
> 
> @Nataliadsanchez Does this work? Let me know if you'd like any changes.
> 
> ![Communication Model](https://user-images.githubusercontent.com/66963480/254647265-15f2be89-28a6-4de5-9cc8-eab0abdded95.png)

I really like it! Thanks @Jeff-TWU!!

**Comment by Jeff-TWU** [comment]
Fixing a typo.
![Communication Model](https://github.com/TWUOnline/bug-tracking/assets/66963480/8c242553-d5c6-45da-9945-7ceda17270d4)

**Comment by MeeksonHundoo** [comment]
Hello @Nataliadsanchez all units are up. Here is the link:
https://effective-adventure-ov6lj83.pages.github.io/emotional-and-social-intelligence.html

**Comment by Nataliadsanchez** [comment]
Thanks for it, @MeeksonHundoo! 
I will start listing the edits that LDRS 400 will need. Please send me a message on Slack if you have any question.

**UNIT 1**
- [ ] Delete last 3 resources and add "Other online resources will be provided in the unit"
- [ ] [Activity Checklist: ](https://effective-adventure-ov6lj83.pages.github.io/emotional-and-social-intelligence.html#activity-checklist)**Add the note:** *Note that the learning activities in this course are ungraded, unless specified. They are designed to help you succeed in your assessments in this course, so you are strongly encouraged to complete them.*
- [ ] YouTube videos are still opening in the same window. Could you please modify it? 
- [ ] [Activity: Animated Video Clips Review and Analysis](https://effective-adventure-ov6lj83.pages.github.io/emotional-and-social-intelligence.html#activity-animated-video-clips-review-and-analysis) - **Modify Instruction**: Watch the following short MindTools Video on “Developing Emotional Intelligence”and the animated video clip on “Empathy” by Dr. Brenne Brown. Then, discuss and reflect on what was shared in both videos and what practical ways you can increase your emotional intelligence through empathy.
**Delete** the last paragraph after the Brené Brown on Empathy video
- [ ] [Activity: Article Analisys](https://effective-adventure-ov6lj83.pages.github.io/emotional-and-social-intelligence.html#activity-article-analysis-1) - **Fix the linked article** 
- [ ] [Unit 1 Sumary](https://effective-adventure-ov6lj83.pages.github.io/emotional-and-social-intelligence.html#unit-1-summary): Remove yellow highlight
- [ ] [Assessment: ](https://effective-adventure-ov6lj83.pages.github.io/emotional-and-social-intelligence.html#assessment-1)Please put together the 2 assignments into one blue box only.
- [ ] [Assessment: ](https://effective-adventure-ov6lj83.pages.github.io/emotional-and-social-intelligence.html#assessment-1) **Add the following paragraph before listing the assignments**: Please locale under the “Assessment” tab all information including instructions, rubrics, forums, and dropboxes for the following assignments.
- [ ] [Assignment 1](https://effective-adventure-ov6lj83.pages.github.io/emotional-and-social-intelligence.html#assignment-1-video-introduction): **Change name** "Video Introduction" (remove the word _assignment 1_)
- [ ] [Assignment 2](https://effective-adventure-ov6lj83.pages.github.io/emotional-and-social-intelligence.html#assignment-2-forum-posts-and-responses): **Change name** "Discussion Forum 1" (remove the word _assignment 2_)

**Comment by Nataliadsanchez** [comment]
**UNIT 2**
- [ ] [Topics: ](https://effective-adventure-ov6lj83.pages.github.io/relating-to-others.html#topics-1): Check the formatting. They are not listed. 
- [ ] **Fig 2.1:** Can it be bold (and centred) so students do not get confused? 
- [ ] Figure designed by Rebecca Straforelli (Fig 2.2) is not displaying. Please take a look at it
- [ ] [Activity: Read and watch: ](https://effective-adventure-ov6lj83.pages.github.io/relating-to-others.html#activity-read-and-watch)Remove bullets. It should be just 2 different paragraphs . 
- [ ] [Activity: Read, Review and Reflect](https://effective-adventure-ov6lj83.pages.github.io/relating-to-others.html#activity-read-review-and-reflect): The reading is opening in the same window. Please fix it. 
- [ ] [Activity: Read, Watch, and Reflect](https://effective-adventure-ov6lj83.pages.github.io/relating-to-others.html#activity-read-watch-and-reflect): The readings are opening in the same window. Please fix it. 

As **general** notes:
- [ ] Could you please list the figures?
- [ ] Is it possible to change the way how we are linking YouTube videos? Can we talk about it?

**Comment by Nataliadsanchez** [comment]
**UNIT 4**
- [ ] [Activity Checklist: ](https://effective-adventure-ov6lj83.pages.github.io/working-through-conflicts-crucial-accountability.html#activity-checklist-3)Remove space between learning activities.
- [ ] [Activity: Watch and Reflect ](https://effective-adventure-ov6lj83.pages.github.io/working-through-conflicts-crucial-accountability.html#activity-watch-and-reflect-1)- Modify instruction: Watch the video "Accountability is Relational Responsibility"
- [ ]  [Activity: Watch and Reflect ](https://effective-adventure-ov6lj83.pages.github.io/working-through-conflicts-crucial-accountability.html#activity-watch-and-reflect-1)- **Insert the title:** Questions to consider (after the video and before the questions)
- [ ]  [Activity: Watch and Reflect ](https://effective-adventure-ov6lj83.pages.github.io/working-through-conflicts-crucial-accountability.html#activity-watch-and-reflect-1)- **Index the last paragraph:** The first step is determining the need for the conversation. What is the problem? What happened (situation) that has left you frustrated, disappointed or even angry?
- [ ] [Activity: Anticipation Guide: ](https://effective-adventure-ov6lj83.pages.github.io/working-through-conflicts-crucial-accountability.html#activity-anticipation-guide)The reading is opening in the same window. Please fix it.
- [ ] Topic 4.2 Overview: We are missing a [video ](https://www.youtube.com/watch?v=EFaXx3pgaxM)at the beginning of this topic. Please check the Word document. 
- [ ] [Activity: Read and Compare](https://effective-adventure-ov6lj83.pages.github.io/working-through-conflicts-crucial-accountability.html#activity-read-and-compare): The reading is opening in the same window. Please fix it.
- [ ] [Activity: : Discussion Forum 2](https://effective-adventure-ov6lj83.pages.github.io/working-through-conflicts-crucial-accountability.html#activity-discussion-forum-2-graded): Remove double dots from this title.
- [ ] [Activity: : Discussion Forum 2](https://effective-adventure-ov6lj83.pages.github.io/working-through-conflicts-crucial-accountability.html#activity-discussion-forum-2-graded) - **Italicize the last sentence**: All information, including specific instructions, rubrics, and dropboxes, are located under the "Assessment" tab. ALSO, please remove the word "forums" from it. 
- [ ] [Topic 4.3 Overview](https://effective-adventure-ov6lj83.pages.github.io/working-through-conflicts-crucial-accountability.html#during-the-conversation): Please embed SME video. Here it is the embeded code: <iframe src="https://player.vimeo.com/video/848140063?h=225051884a" width="640" height="360" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe>

Also, please add the following content after the video: 
[U4_LDRS400 - After the Conversation.docx](https://github.com/TWUOnline/bug-tracking/files/12152308/U4_LDRS400.-.After.the.Conversation.docx)
- [ ] [Activity: Case Analysis](https://effective-adventure-ov6lj83.pages.github.io/working-through-conflicts-crucial-accountability.html#activity-case-analysis-graded): **Italicize the last sentence**: _This activity will be graded. Please refer to the Assessment section for more information about how to submit it._
- [ ] [Topic 4.4 Overview ](https://effective-adventure-ov6lj83.pages.github.io/working-through-conflicts-crucial-accountability.html#move-to-action) - Please remove the double dots in the "Structural" accordion, and the dashes (before click here to expand) in all three of them. 
- [ ] [Activity: Read and think about](https://effective-adventure-ov6lj83.pages.github.io/working-through-conflicts-crucial-accountability.html#activity-read-and-think-about): The reading is opening in the same window. Please fix it.
- [ ] [Activity: Read and think about](https://effective-adventure-ov6lj83.pages.github.io/working-through-conflicts-crucial-accountability.html#activity-read-and-think-about): Could you please increase indent where the bullet points are? You can check the Word document for guidance. 
- [ ] [Activity: Conflict Scenario:](https://effective-adventure-ov6lj83.pages.github.io/working-through-conflicts-crucial-accountability.html#activity-conflict-scenario-graded): The reading is opening in the same window. Please fix it. 
- [ ] [Activity: Conflict Scenario:](https://effective-adventure-ov6lj83.pages.github.io/working-through-conflicts-crucial-accountability.html#activity-conflict-scenario-graded): Italicize the last sentence: This activity will be graded. Please refer to the Assessment section for more information about it.

**Comment by MeeksonHundoo** [comment]
Hello @Nataliadsanchez all these edits are have been made. Just to let you know that I spoke to Colin on the slide show, however he has advised me to put it in manner in which we have changed the content to text from Images. That's how we are doing it. If there are any other edits that are needed please let me know. Here is the link:
https://effective-adventure-ov6lj83.pages.github.io/emotional-and-social-intelligence.html

**Comment by Nataliadsanchez** [comment]
Thank you SO MUCH @MeeksonHundoo for working on those edits. Could you please double check the following ones again?

**UNIT 1**

- [ ] [Activity: Animated Video Clips Review and Analysis](https://effective-adventure-ov6lj83.pages.github.io/emotional-and-social-intelligence.html#activity-animated-video-clips-review-and-analysis) -  Delete the last paragraph after the Brené Brown on Empathy video
- [ ] [Activity: Article Analisys](https://effective-adventure-ov6lj83.pages.github.io/emotional-and-social-intelligence.html#activity-article-analysis-1) - Fix the linked article

**UNIT 2**
- [ ] [Topics: ](https://effective-adventure-ov6lj83.pages.github.io/relating-to-others.html#topics-1): Check the formatting. Topic one is not listed.
- [ ] Figure 2.2 is not displaying. 

**UNIT 4**
- [ ] [Activity: Watch and Reflect ](https://effective-adventure-ov6lj83.pages.github.io/working-through-conflicts-crucial-accountability.html#activity-watch-and-reflect-1)- **Modify instruction:** Watch the video "Accountability is Relational Responsibility", and reflect on the questions provided below it.

**UNIT 5**
- [ ] [Assessment: ](https://effective-adventure-ov6lj83.pages.github.io/negotiations---the-culturally-sensitive-servant-leader.html#assessment-8)Remove space between assignments

_Thanks for linking the video like we discussed! Could you please make sure that in Unit 5 they are linked the same way?:_

- [ ] [Activity: Watch and Create](https://effective-adventure-ov6lj83.pages.github.io/negotiations---the-culturally-sensitive-servant-leader.html#activity-watch-and-create) - **Modify instruction:** Watch the video "Negotiation Principles: GETTING TO YES by Roger Fisher and William Ury" that illustrates these concepts related to negotiating. Note the differences between positional and principled bargaining.
**ALSO,** please link the video in the instruction. Thanks!
- [ ] [Activity: Pair and Share](https://effective-adventure-ov6lj83.pages.github.io/negotiations---the-culturally-sensitive-servant-leader.html#activity-pair-and-share): **Modify instructions:**
**BEFORE THE VIDEO:** Watch the video “Cultural Differences in Negotiations and Conflicts”.
**AFTER THE VIDEO:** Next, read the following articles [Insert the two articles]... After the articles, please leave the Questions to consider BUT do not separate them from the articles (remove line)
- [ ] [Activity: Watch and Create](https://effective-adventure-ov6lj83.pages.github.io/negotiations---the-culturally-sensitive-servant-leader.html#activity-watch-and-create) (after the activity) - **The following **_shouldn't_** be indexed:** “each side takes a position, argues for it and makes concessions to reach a compromise” (Fischer & Ury, 2011, p. 3). It SHOULD be a normal text:
Positional bargaining is when “each side takes a position, argues for it and makes concessions to reach a compromise” (Fischer & Ury, 2011, p. 3).

**Comment by Nataliadsanchez** [comment]
Also, Rebecca is working on the Reference part. I will let you know when she is done with it :)

**Comment by MeeksonHundoo** [comment]
U1 : Fix the linked article. 
![image](https://github.com/TWUOnline/bug-tracking/assets/98780625/ff3eee00-f823-4f60-bd6a-c44e6136d0a1)
Article is fine. Opening on a different tab as well. Could you please elucidate what do you want me to fix?

![image](https://github.com/TWUOnline/bug-tracking/assets/98780625/a363c699-89c9-405b-85a6-17d0fcd4eb85)
U2 :  Figure 2.2 is not displaying. Rendering perfectly fine as shown.

Rest all the other changes have been made and implemented.

**Comment by Nataliadsanchez** [comment]
-[ ] [Activity: Article Analysis](https://ba-leadership.github.io/ldrs400/emotional-and-social-intelligence.html#activity-article-analysis-1): This reading is not properly linked, Meekson. Could you please double check it?
<img width="415" alt="Capture LDRS 400" src="https://github.com/TWUOnline/bug-tracking/assets/117681170/ad11c3c6-ec30-48fe-ac63-9f4a7033d947">


The rest of the book looks great! Thank you so much!!

**Comment by MeeksonHundoo** [comment]
Hello @Nataliadsanchez Yeah, I remember not doing this purposely as that's how articles are referenced in APA 7. The Word doc had it mentioned that way, so thought probably the Prof wanted it to be that way. Moreover, the link is not right, it does not lead to the article, it leads to the TWU one search library. Could you please double  check this with her? Uploaded the Course Description..

**Comment by Nataliadsanchez** [comment]
Hi @MeeksonHundoo! Do we reference articles in the learning activities? As far as I know, we just mention the name of the article and then link it. If we need to reference articles in APA 7 in the learning activities, we will have to change all the articles in the course. We need consistency and this is the only one that is different. Could you please clarify this? Thanks!!

About the link, I already asked the librarian but she will be back on Monday.

**Comment by MeeksonHundoo** [comment]
Hello @Nataliadsanchez i meant.. the way it was written..it looked like a reference. That's why I didn't change it. We just need to cite the content in the body and their corresponding references are at the very end according to APA. So all good. No worries about the link, whenever you get it from the Librarian just let me know and i'll have it updated.

**Comment by Nataliadsanchez** [comment]
@MeeksonHundoo I am confused! It is not written like a reference in the Word documents. I thought you changed it. If it does not need to be written as a reference, could you please write the instruction as it is in the Word doc? Thanks!

I'll let you know once I have the link from the librarian.

**Comment by Nataliadsanchez** [comment]
Hi @MeeksonHundoo Could you please update the [Activity: Article Analysis](https://ba-leadership.github.io/ldrs400/emotional-and-social-intelligence.html#activity-article-analysis-1)? This is the [new article link](https://eds-p-ebscohost-com.twu.idm.oclc.org/eds/detail/detail?vid=0&sid=e6702958-c209-4559-823b-733ef63d3e9b%40redis&bdata=JnNpdGU9ZWRzLWxpdmUmc2NvcGU9c2l0ZQ%3d%3d#AN=130794839&db=bth)

**Comment by MeeksonHundoo** [comment]
> Hi @MeeksonHundoo Could you please update the [Activity: Article Analysis](https://ba-leadership.github.io/ldrs400/emotional-and-social-intelligence.html#activity-article-analysis-1)? This is the [new article link](https://eds-p-ebscohost-com.twu.idm.oclc.org/eds/detail/detail?vid=0&sid=e6702958-c209-4559-823b-733ef63d3e9b%40redis&bdata=JnNpdGU9ZWRzLWxpdmUmc2NvcGU9c2l0ZQ%3d%3d#AN=130794839&db=bth)

Hello @Nataliadsanchez edited the links and also changed the YouTube video's to a list format. Here is the link to the course:
https://ba-leadership.github.io/ldrs400/emotional-and-social-intelligence.html

**Comment by Nataliadsanchez** [comment]
Thanks @MeeksonHundoo for all your help to build this course! It is all done now :)
