### ISSUE TITLE
Need changes to Psyc 322-OL course content

### ISSUE THREAD

**Issue by chiquepiece** [TWUOnline/bug-tracking#895]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 
Psyc322-OL  Summer 2023
url: https://learn.twu.ca/course/view.php?id=28109&section=0#tabs-tree-start

**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 
Under the "Research project and presentation" tab -- need to edit Part 1: Defining your research, to say "In the discussion forum below, create a post that describes what your research question will be."

Also add a Part 0 (to go before that Part 1) that says: In the first discussion forum (link below), talk about your areas of interest and ideas for how you might turn this into a suitable research project.  This is where you can interact with each other to help shape your ideas.  And look for feedback from the course instructor(s).  This is a brainstorming process, no marks are assigned for this.  
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28109&section=8
2. Unit #         Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @chiquepiece this has been updated

**Comment by chiquepiece** [comment]
Hi Meekson, thx for work on all my edit requests.  I'm not seeing the changes for this one reflected on the course site.

**Comment by MeeksonHundoo** [comment]
> Hi Meekson, thx for work on all my edit requests. I'm not seeing the changes for this one reflected on the course site.

Hello @chiquepiece my sincere apologies. I just overlooked the edit in **Part 1: Defining Your Research** tab. I thought i did it last night. its done now.

**Comment by chiquepiece** [comment]
Hi Hudson, I"m still not seeing these edits on the course site.  The new addition, Part 0 is not showing.  And Part 1 still has the old text, not the change/edit I submitted.  And since we are still working on this, can the Part 1 edit say:  "In the discussion forum below, create a post that describes what your research question will be. Further instructions/details about how to format this post are explained in the Discussion Forum."
Thanks alot!

**Comment by MeeksonHundoo** [comment]
![image](https://github.com/TWUOnline/bug-tracking/assets/98780625/02b8caf5-0874-4be6-a192-e89b90232b32)
 hello @chiquepiece please see this image. Could you please try refreshing your course page.

**Comment by MeeksonHundoo** [comment]
> Hi Hudson, I"m still not seeing these edits on the course site. The new addition, Part 0 is not showing. And Part 1 still has the old text, not the change/edit I submitted. And since we are still working on this, can the Part 1 edit say: "In the discussion forum below, create a post that describes what your research question will be. Further instructions/details about how to format this post are explained in the Discussion Forum." Thanks alot!

Hello @chiquepiece I've updated Part 1 to the above statment. Here is the link which shows the changes : https://learn.twu.ca/course/view.php?id=28109&section=8#tabs-tree-start and have also attached a screenshot below.

![image](https://github.com/TWUOnline/bug-tracking/assets/98780625/f0bb52fe-6565-46c5-acb6-c13c36dd6bf0)

**Comment by chiquepiece** [comment]
Hi  Meekson (sorry I was calling you Hudson?!?! in last msg, no idea why I did that) --
thank-you so much for your work on this.  I wonder if you can suggest who/how I might get help with something, which is that I logged out of and back to course site but it is not showing the updated content on my system.  I see that you updated it so I don't know why it's not updating on my system.  I also tried to access using a different browser (Safari instead of Firefox).  It says there my password is wrong and when tried to reset it, get msg that it is not an option: "We're sorry. You can’t reset your own password because password writeback, how your password changes in the cloud are copied to your organization’s on-premises system, isn’t turned on for your organization.  You must contact your administrator to both reset your password and to check your organization’s setup. "  Do you know if there is a way to troubleshoot this with TWIT?  And thanks again so much for your great help with the course!

**Comment by MeeksonHundoo** [comment]
Hello @chiquepiece no worries. that's fine. Sorry to hear about your account getting locked, but if you send a helpdesk ticket someone from IT will definitely assist (link for service hub: https://trinitywestern.teamdynamix.com/TDClient/1904/Portal/Requests/ServiceCatalog?CategoryID=18138&SIDs=11261/)
or else you could also send an email to elearning@twu.ca explaining them the issue and someone from IT will get back to you.

**Comment by chiquepiece** [comment]
ah, thank-you so much.  I just did a help request.  REally appreciate your time.  Cheers, Lisa
p.s. going to try attaching a pic here (a meme) thought you might enjoy, esp. since I should have taken care of all this before the course went live.  Not sure this will work.   thank-you again for your help.
![Screen Shot 2023-07-20 at 2 17 37 PM](https://github.com/TWUOnline/bug-tracking/assets/140017682/8359c584-1512-470a-805c-c7d99c85a03b)

**Comment by MeeksonHundoo** [comment]
🤣 😂 you're welcome and no worries at Lisa. If you need any further assistance with the course, please do let us know. Have a good day.
