### ISSUE TITLE
Edit needed on psyc 322OL Summer 2023 course site

### ISSUE THREAD

**Issue by chiquepiece** [TWUOnline/bug-tracking#896]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 Psyc 322OL Summer 2023
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 Under "Assessments" Tab, under Assignment 1: Interview.  It currently says to "summarize your experience in 4-6 sentences"  I'd like that changed to say "summarize your experience in 1-2 pages (double-spaced)".
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/mod/assign/view.php?id=914914
2. Unit #         Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @chiquepiece this has been updated

**Comment by chiquepiece** [comment]
Hi Hudson, I'm not seeing these changes showing up on the course site.

**Comment by chiquepiece** [comment]
Hudson!  I just realized this is not a change that needs to be made.  The original statement of 4-6 sentences can remain as is.  Sorry for confusion.

**Comment by MeeksonHundoo** [comment]
Hello @chiquepiece do you want to have the original statement to be reinstated?

**Comment by chiquepiece** [comment]
It looks like what is there now is correct (4-6 sentences) so no need for further action on this one.  Thanks so much!
