### ISSUE TITLE
Edit needed on Psyc322OL

### ISSUE THREAD

**Issue by chiquepiece** [TWUOnline/bug-tracking#897]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 
 Psyc 322OL Summer 2023

**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 
Under the tab "Research Project and Presentation" there is a discussion forum I have hidden temporarily b/c the dx is contradictory/inaccurate to course req'ts --  Forum is -- "Assignment 4: Part 1 Your Research Question".  The dx says this is an ungraded assignment, but it is actually worth 10%.  So need the dx to be changed from what it currently says to :

For this activity, we want you to take the input provided in the brainstorming session of discussion forum 1 and present what you propose to do for your research project.  

Your post should clearly identify 4 things:
1.	A sentence or two about your area of interest;
2.	Your research question;
3.	Put your research question into the form of a hypothesis (a prediction – what you expect to find or how you expect your IV to impact your DV);
4.	Clearly describe your IV and DV (including the 2 levels of your IV).  At this point you don’t have to be too specific yet about how you will measure things; we’ll go into more detail in another step.  

This assignment will act like a final check, to make sure you are proceeding with an appropriate research design.  

Sample entry:
1.	 As a student athlete I am interested in the role that physical activity and fitness plays in people’s mental health.  
2.	I want to investigate if exercising helps people feel better.
3.	My hypothesis (prediction) is that people who exercise will feel better/have better mood.
4.	IV will be activity level – one group will exercise by walking briskly for an hour and the other group will sit/be sedentary for an hour (maybe watch tv).  The DV is mood which I will measure by creating some kind of survey or questionnaire that participants answer at the end.

 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  
2. Unit #         Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by chiquepiece** [comment]
sorry forgot url:  https://learn.twu.ca/mod/forum/view.php?id=914938

**Comment by MeeksonHundoo** [comment]
hello @chiquepiece this is updated
