### ISSUE TITLE
Edit content on Psyc322OL Summer 2023

### ISSUE THREAD

**Issue by chiquepiece** [TWUOnline/bug-tracking#898]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 Psyc 322OL Summer 2023
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 
In Unit 2 tab/page, there are multiple places where it refers to reviewing 2 articles.  These all need to say 1 article, so it matches content elsewhere on course site.  

on this main page for Unit 2, in the blue Activity boxes, , the last item "Assessment" says Evaluate two articles, change that to 1.

When looking at the menu items in column on left side of this page, that last one is Assessment.  Go to that page, and the  "Assignment 2" heading, says "evaluate 2 articles".  This should say 1 article.  And paragraph 2 within that section also refers to in 2 places to 2 articles; need to change those to 1.  the Instructions #1 and 3, refers to 2 articles, need to change to 1.  
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28109&section=2#tabs-tree-start
2. Unit #         Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @chiquepiece these edits have been implemented.

**Comment by chiquepiece** [comment]
superb!  looks great Meekson.  Thanks so much for getting on that so quickly.   btw, figured out I wasn't seeing the updates b/c my browser cache needed to be cleared.  I can see all the current content properly now.  
Cheers,
Lisa

**Comment by MeeksonHundoo** [comment]
> superb! looks great Meekson. Thanks so much for getting on that so quickly. btw, figured out I wasn't seeing the updates b/c my browser cache needed to be cleared. I can see all the current content properly now. Cheers, Lisa

@chiquepiece Your welcome and glad to hear that you can now view all the updates without any delays. Also, yeah clearing browser cache, deleting unnecessary and temp files, running a disk cleanup, etc. are all good practices to keep your laptop functioning well. Have a good night and a nice weekend.
