### ISSUE TITLE
Edit content on course site 

### ISSUE THREAD

**Issue by chiquepiece** [TWUOnline/bug-tracking#899]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 
 Psyc 322OL Summer 2023

**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 
 under assessment tab, Assignment Case STudy 1, in point 2 it says about the forum that you will not be able to see other posts until create own.  Please remove that sentence.

**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:    https://learn.twu.ca/course/view.php?id=28109&section=7#tabs-tree-start
2. Unit #         Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello Lisa.. @chiquepiece.These edits have been made.
