### ISSUE TITLE
Production - WRSH 101 - U1 pwpt

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#90]
### Course
WRSH 101
### URL
https://learn.twu.ca/course/view.php?id=10744&section=1

Unit 1 Topic 2 Learning Activity1.3
### Instructions
Please upload the pwpt - or make into a Presentations slideshow.
[WRSH_101_U1.3_What-is-Worship.pptx](https://github.com/TWUOnline/bug-tracking/files/3773153/WRSH_101_U1.3_What-is-Worship.pptx)

**Comment by rezakh66** [comment]
Done
