### ISSUE TITLE
LDRS 634 - removing unit #s

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#900]
**Which course contains the bug?**  
[LDRS 634: Accountability & Performance (DEV MASTER)](https://learn.twu.ca/course/view.php?id=18002) 
 
**Describe the error and/or your suggestion**  
LDRS 634 Dev Master on github: Request from Heather:

Could I request that you remove the “unit X” label from the beginning of each topic in the different unit overview pages – and just leave the topic heading such as “A Context for Accountability”.

If you could also remove the “Required Readings” section from each of the unit overview pages as well that would be great.  I have included the required readings in a separate section on Moodle, that way I can pick and choose what the students are reading and not be stuck with the list I created 4 years ago.

So each unit overview page would have: 
•	A topic title
•	An image
•	An overview of the topic
•	Learning Outcomes for the topic

(We can add the Unit #s back in when we move to Moodle books, but for now this shouldn't be an issue.)

**Comment by MeeksonHundoo** [comment]
Hello @kmarjanovic these edits have been implemented.
