### ISSUE TITLE
SOCI 101 units missing

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#901]
**Which course contains the bug?**  
[bookdown](https://twu-fhss.github.io/soci101/introduction-to-sociology.html) 
[FAR version](https://learn.twu.ca/course/view.php?id=10781&section=3#tabs-tree-start) 

**Describe the error and/or your suggestion**  
Unit 3 (Socialization) and 5 (Social Institutions) are missing in bookdown.  Please fix!

**Comment by meher-ahmed** [comment]
<img width="1440" alt="Screenshot 2023-07-24 at 11 17 40 AM" src="https://github.com/TWUOnline/bug-tracking/assets/130523647/93e2f3da-26c3-4a23-ba4a-6361e452e55c"> 
<img width="1440" alt="Screenshot 2023-07-24 at 11 18 03 AM" src="https://github.com/TWUOnline/bug-tracking/assets/130523647/c24b64fb-865e-415d-8d39-e3dc2d181fbf">
I can see it is there. Both the units are present in my bookdown files  @kmarjanovic @cmadland

**Comment by meher-ahmed** [comment]
Strange!! as from my end, all units were built. Even now, without pulling any changes, it is building 
<img width="1440" alt="Screenshot 2023-07-24 at 11 35 46 AM" src="https://github.com/TWUOnline/bug-tracking/assets/130523647/dd32665f-a8ba-48c7-80f3-dc4840a3c4f6">

**Comment by Jeff-TWU** [comment]
All units rendering now. Had some blocks within blocks, and some headings within blocks.
