### ISSUE TITLE
Psych 331 Master: Unit 2 Assessment section

### ISSUE THREAD

**Issue by Mike2625** [TWUOnline/bug-tracking#902]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 _Psych 331 ADC Master copy_
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 _Under Unit 2 Assessment section_

_Change the following:
Where it says "Discussion Form" to "Journal Entry Assignment" (keep the paragraph the same below this section)_

Chan

**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  
2. Unit #  2       Topic #  Assessment section       Activity#  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
hello @Mike2625 this edit has been made
