### ISSUE TITLE
Psych 331 Unit 4 Assessment section

### ISSUE THREAD

**Issue by Mike2625** [TWUOnline/bug-tracking#904]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 Psych 331 master
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 ___In the assessment section of unit 4, please delete what it says under Questions for Reflection and instead note the following:
 
Please pick one of the three theories that most interest you - "Behavior", "CBT" or "Reality" Therapy - regarding the "Case for Stan" and then answer the Questions for Reflection in that chapter. Each of these sections begins on pages 259, 300, and 329.___

 _In the Journal Entry section: please add the following after the words "Feel Stuck".  

These questions stem from the chapter covering Reality Therapy.  It's good practice for therapists to ask themselves these questions as part of their own journey (of countertransference etc)_

_In the final presentation and paper section, in the last sentence please reword it as follows:
"By the end of this week, you have the option to submit via e-mail to your professor an outline of your paper to receive input and suggestions. However, this is not required or graded. Only do this if you feel this will help you as you prepare for your final paper_

**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  
2. Unit #  4       Topic # Assessment section        Activity#  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @Mike2625 these edits have been made
