### ISSUE TITLE
Psyc 322OL Summer 2023 Edits

### ISSUE THREAD

**Issue by chiquepiece** [TWUOnline/bug-tracking#908]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 
 Psyc 322OL Summer 2023

**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 
Under tab "Research Project and Presentation" -- 
Assignment 5 Heading -- text says "7 minutes" for presentation.  Should be 3 - 5 minutes.  Also last sentence, please change from "interesting visual slides" to " helpful visual aids".  
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28109
2. Unit #         Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello Lisa @chiquepiece edits have been made
