### ISSUE TITLE
Psyc 322OL, edit needed asap please :)

### ISSUE THREAD

**Issue by chiquepiece** [TWUOnline/bug-tracking#909]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 
 Psych 322OL Summer 2023

**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 
Under Research Project and Presentation tab,   in the Assignment Link for Assignment 4, Part 3 Your Hypothesis.  Remove the current description that is there [One or two hypotheses that are clear, concise, and testable. One or two sentences per hypothesis. This will be the only part in the PRESENT TENSE.]  and replace it with:  

HYPOTHESIS
Submit your hypothesis statement here.   Remember the hypothesis is a clear, concise and testable description (a prediction) of how you think your IV will affect your DV.   Remember to use your operational definitions for this.  

This will be similar to what you worked on in Assignment 4, Part 1 "Your Research Question", #3 (the hypothesis/prediction).  Note also that since what you are writing here is like a proposal for a research project (not writing up the results of a project after collecting data), this will be written in the future tense.  I.e., a description of what you expect will happen.   And it should be written in 3rd person (not first-person).  

Examples:

It is predicted that participants who walk in nature for ½ hour will report higher mood scores on a questionnaire designed by the researcher, compared to students who sit for ½ in the similar natural setting.  OR

It is expected that students who write for 15 minutes about a positive experience in their life when they felt proud, will score higher on the Rosenberg Self-Esteem Scale than do students who write for 15 minutes about a time in their life when they regretted their actions.   OR

Participants who read a scenario in which a soldier was killed one day before the end of their tour, will award higher compensation to the family compared to participants who read a scenario in which a soldier was killed 6 months before the end of their tour.  

Note that in all these examples, no personal pronouns are used (i.e., don’t say “I predict that…”).  Also note that the predications are expressed in future tense:  ‘will report’ or ‘will score’ or ‘will award’.  This is how you phrase a proposal.  After you collect data and are writing up the report, this changes to past tense (“It was predicted that…”; “It was expected that…”).

You do not need a title page for this submission.  Please do put your name (or all names of members of your group) at top of the page.  

**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28109&section=8
2. Unit #         Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello Lisa @chiquepiece this is done

**Comment by chiquepiece** [comment]
oh my!  you are working today??  wow thank-you for posting these changes.
I didn't expect it to be seen until Tue.  Very good of you, will help
students a lot to see right away.  Thank-you kindly.
