### ISSUE TITLE
LDRS300 Unit 7 Assessment

### ISSUE THREAD

**Issue by cmadland** [TWUOnline/bug-tracking#91]
LDRS 300

- [ ] Assessment section is missing?

http://far.twu.ca/ba-lead/ldrs300/u7/assessment
2. Unit #   7      Topic #   assessment      Activity#

**Comment by kmarjanovic** [comment]
@cmadland it's in the word doc.  Were you able to access it via dropbox?

**Comment by cmadland** [comment]
got it
