### ISSUE TITLE
Psyc322OL Summer 2023 edit request

### ISSUE THREAD

**Issue by chiquepiece** [TWUOnline/bug-tracking#910]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 Psyc 322OL Summer 2023

**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 
 Under Research Project and Presentation tab, in the Assignment Link for Assignment 4, Part 2 “Review your 5 articles”,  Remove the current description* that is there and replace with:

LITERATURE REVIEW
Using the five primary research articles you found, write a 3-5 page Introduction section (aka a literature review) for your proposed research study.  You can of course use additional sources to the five articles (more articles, book chapters, websites, etc.) if you want, but five is sufficient for this activity.  

To make this section of your paper effective, you should relate information from the various sources to each other and to your research. After you discuss past research, you should make it clear how your study is the next logical one, that your study improves upon past studies, that your study fills gaps left by the others.

For more detailed information on writing a Literature Review including grading rubric and sample paper, see documents under “Resources” heading near bottom of “Research Project and Presentation” page.  

Remember – this is written in 3rd person (no personal pronouns).  

**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=28109&section=8
2. Unit #         Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello Lisa @chiquepiece this is done
