### ISSUE TITLE
Psyc 322OL

### ISSUE THREAD

**Issue by chiquepiece** [TWUOnline/bug-tracking#912]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 
 Psyc 322 OL Summer 2023
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 
Under Research Project and Presentation tab, in the **Assignment Link** for Assignment 4, Part 4 Your Research Methods.

Remove the existing 4 paragraphs/headings and replace with:

METHODS SECTION (25%)

This is where you describe what you plan to do to test your hypothesis.  

A note about tense:  What you are writing here for this assignment should be in future tense (as it would be in a proposal you submit to get approval for the project).  If you continued with this project and ran subjects (collected data), you would then revise this section and put it in past tense, as a report of what you did do to collect data.  For now however, you’re going to stick with future tense as writing a proposal is always the first step.

The Methods section contains a set of clear instructions that provides enough detail describing what you plan to do (in the proposal) or did do (in the report) so that someone else could replicate your study.   Most Methods sections are divided into subsections, usually Participants, Materials, and Procedures.  You should present them in that order, using those sub-headings.  You will also include a final section called Design.  This is not a standard section in a research report, but is useful here as part of learning.

Length:  1.5 - 3 pages, not including Appendices.  (It’s possible your methods section could be longer than this if needed to adequately describe your methods.  However, for most of these projects 2-3 pages will likely be sufficient.) 

Participants (5%) 
Include information about who the participants will be in your experiment. How many participants do you intend to recruit?  [Note: a good guideline is 15 people per condition.  So if you have 2 levels of your IV, you need 30 participants.]. Explain if you plan to include male and female, whether you will make an effort to have people from different departments/majors, years of study or even race/ethnicity if that’s relevant.  You can describe here how you plan to recruit participants (e.g., announcement asking for volunteers in Psychology classes, posters around campus, etc.).  Did participants receive compensation (payment, gift card, course credit etc.) for being in your study? 

Example: 
Thirty undergraduate students from TWU will be recruited from first-year psychology classes.  An effort will be made to recruit a relatively equal number of male and female students.  With permission from the professors of Intro Psychology, the researcher will make an announcement in class about the study and collect names/emails of interested students.  Where instructors agree, participants will receive some course credit for their participation in the study.

Materials (7.5%)
Here is where you describe any materials that will be used in your study.  Any common materials do not need to be described in detail (e.g., stopwatch, paper, pens, furniture that is in the room, desktop computer on which participants work or enter answers).  However, any material you design (including your Informed Consent form) should be described and a copy included in an Appendix.  Similarly if something about the room or setting is crucial to your IV, that should be described in sufficient detail (e.g., a room with no plants versus a room filled with plants).  

If you use a published test (e.g., Rosenberg Self-Esteem Scale), say so here in the Materials section and include appropriate reference for the test publisher.  If you have secured a copy of the test, you can include that in the Appendix but that is not required.  

Example
Participants will fill out an Informed Consent form (Appendix A) before beginning the study.  During the study, half of the participants will read version A of a story written by the researcher (Appendix B) and half will read version B of the story (Appendix C).  Participants will then respond by filling out the survey questions that have been designed by the researcher for use in this study, and that are at the bottom of each of the respective handouts participants read (Appendix B and C).

Procedure: 7.5% 
Include here details about what participants will experience in your study. You should include enough detail that someone could replicate your study, using your paper as a guide. The order of this section should be the order of activities that participants will experience. What was the setting of the experiment (where did it take place)? What questionnaires did participants complete? Did you make up your own questionnaire? What instructions did you give participants? 
Example
Participants will be greeted as they arrive to an office on TWU campus, at the day and time previously arranged through email contact.  After the consent form is signed and collected, the researcher will read instructions explaining the activity the participant is being asked to do (Appendix E).  The participant will then have 15 minutes to complete the writing activity, using pen and paper [or whatever method you intend to use].  When time is up, participants will be asked to fill out the questionnaire designed by the researcher (Appendix F).  When they are finished, participants will be debriefed, asked if they have any questions and thanked for their participation in the study.  

Design: 5% 
In this section, include information about your independent variable (what are the two levels  -- or three if that is appropriate for your study) and dependent variable (use your operational definitions).  State whether your study is a within- or a between-subjects design.  You can also mention here if you included an additional subject variable (such as gender or major) in the demographic data you collected to see if this interacts with your main IV, and explain why you were interested in this/thought is worthwhile to include.

Example
The independent variable in this study is order of word presentation.  There are two levels: in one case positive adjectives come first followed by negative adjectives; the other level has negative adjectives come first followed by the positive ones.  The dependent variable is impression formed of the person begin described.  This is measured by average score on a set of questions posed about the person being described.  This will be an independent groups design (different people participating in each of the conditions).  

A note about Appendices – These come at the end of your paper (or in this case at the end your Methods section).  The order is the order in which they are referred to in your paper.  The first time you mention something that is in the Appendix, it is called Appendix A, the next item you refer to that is in the Appendix, gets called B, and so on.  Each Appendix begins on a new page, and has a centered heading with appropriate title: Appendix A, Appendix B and so on.

There is a sample Methods section posted under the banner “Resources” at bottom of Research Project and Presentation tab/page.   

 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/mod/assign/view.php?id=914933
2. Unit #         Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello Lisa @chiquepiece this is done.
