### ISSUE TITLE
Production - MCOM 221GX

### ISSUE THREAD

**Issue by Nataliadsanchez** [TWUOnline/bug-tracking#915]
[MCOM 221_U8.docx](https://github.com/TWUOnline/bug-tracking/files/12434119/MCOM.221_U8.docx)
[Guidelines for Pitching a Film Project.docx](https://github.com/TWUOnline/bug-tracking/files/12434121/Guidelines.for.Pitching.a.Film.Project.docx)
**MCOM 221 GX**
Moodle: https://learn.twu.ca/course/view.php?id=29282
Bookdown:

Please, build a book for MCOM 221GX:
- [x] Unit 1
- [x] Unit 2
- [x] Unit 3
- [x] Unit 4
- [x] Unit 5
- [x] Unit 6
- [x] Unit 7
- [x] Unit 8
- [x] Unit 9
- [x] Unit 10

**Priority**
HIGH

[MCOM 221_U1.docx](https://github.com/TWUOnline/bug-tracking/files/12325642/MCOM.221_U1.docx)
[MCOM 221_U2.docx](https://github.com/TWUOnline/bug-tracking/files/12325643/MCOM.221_U2.docx)
[MCOM.221_U3_v.14.08.23.docx](https://github.com/TWUOnline/bug-tracking/files/12337964/MCOM.221_U3_v.14.08.23.docx)
[MCOM 221_U4.docx](https://github.com/TWUOnline/bug-tracking/files/12325645/MCOM.221_U4.docx)
[MCOM 221_U5.docx](https://github.com/TWUOnline/bug-tracking/files/12325646/MCOM.221_U5.docx)
[MCOM 221_U6.docx](https://github.com/TWUOnline/bug-tracking/files/12325647/MCOM.221_U6.docx)
[MCOM 221_U7.docx](https://github.com/TWUOnline/bug-tracking/files/12325648/MCOM.221_U7.docx)
[MCOM 221_U8.docx](https://github.com/TWUOnline/bug-tracking/files/12434122/MCOM.221_U8.docx)
Please link this document in an activity in Unit 8: [Fairy Tale Template for a Short Film.docx](https://github.com/TWUOnline/bug-tracking/files/12325641/Fairy.Tale.Template.for.a.Short.Film.docx)
[MCOM 221_U9.docx](https://github.com/TWUOnline/bug-tracking/files/12434550/MCOM.221_U9.docx)

**Comment by cmadland** [comment]
[Book is here.](https://github.com/twu-samc/mcom221)

I'll add the werd files and convert them.

**Comment by cmadland** [comment]
@Nataliadsanchez were there updates to these files? The course that is already there looks the same, but it is already produced.

**Comment by Nataliadsanchez** [comment]
Hi @cmadland. Those file are not the same, However, I'll submit the changes made in each unit.

**Comment by Nataliadsanchez** [comment]
**UNIT 1** 
- [ ] **Activity Checklist**
- [ ] **Assessment**
- [ ] **Resources**
* Introduction and Chapter One of the course text: _Digital Filmmaking: A Beginner’s Guide to Mastering the Craft_, by Ned Vankevich (e-text)
* Other online resources will be provided in the unit.
- [ ]  **Activity: The Importance of the Film Journal**
"Unit 1 Film Journal Entry" is also part of the activity. It should be in the blue box
- [ ] Remove **Activity 1.2: Film Terms and Vocabulary Needed for this Course**
- [ ] Remove **Topic 4: Transferable Skills**

**Comment by Nataliadsanchez** [comment]
**UNIT 2**
- [ ]  **Activity Checklist**
- [ ] **Resources**
- [ ] Topics 2, 3 and 4 are now only 1 topic. Also, one video was removed and activities changed. Please refer to the file to find the changes
[MCOM.221_U2_v.14.08.23.docx](https://github.com/TWUOnline/bug-tracking/files/12337516/MCOM.221_U2_v.14.08.23.docx)

**Comment by Nataliadsanchez** [comment]
**UNIT 3**
- [ ] Activity Checklist

* Read and study Chapter 3 of course e-text: Digital Filmmaking: A Beginner’s Guide to Mastering the Craft.
* Read the article “11 Thoughts: An Introduction to Photographic Composition” by Todd Vorenkamp and reflect on the question provided.
* Read the article “20 Composition Techniques That Will Improve Your Photos”, and practice and apply techniques and principles of design.
* Review the suggested websites to enrich your understanding of photographic themes and find images that stand out in intriguing, startling, fascinating, and emotionally moving ways.

- [ ] **Resources**
* Chapter 3 of course text: Digital Filmmaking: A Beginner’s Guide to Mastering the Craft, by Ned Vankevich (e-text)
* Other online resources will be provided in the unit.
- [ ] Topic 1 and 2 are only one topic: Topic 1. Activities were combined. Please refer to Unit 3 document if you want to see the changes.
- [ ] **Assessment: Composition Exercise** - Add the following note at the beginning of the instructions: _This activity is ungraded, but part of journal entry_

**Comment by MeeksonHundoo** [comment]
Hello @kmarjanovic could you please give me access to write in the mcom221 repo...I have made edits to U1 & U2 which I cannot push..

![image](https://github.com/TWUOnline/bug-tracking/assets/98780625/2f4dab29-ef7d-4180-9f9a-96cdc130b546)

**Comment by MeeksonHundoo** [comment]
hello @Nataliadsanchez these edits have been made.
Thanks @kmarjanovic for giving me access to write.

**Comment by Nataliadsanchez** [comment]
**Course Introduction**
- [ ] Insert Banner in Moodle. I tried but it displayed an error

**GENERAL:**
Remove the bold words in the activity checklists. Leave only the descriptions. 
Please check that all the notes in the activity checklists are in plural
- [ ] make sure all the links open in a new tab

**Unit 1:**
- [ ] **Learning Activity:** Unit 1 Film Journal Entry: Fix the link [How to Start a Creative Journal](https://karenbanes.com/how-to-start-a-creative-journal)
- [ ] The article How to Start a Creative Journal and the video How to journal every day... need to be indexed. Please check the word doc.
- [ ] The 3 "Learning Activities" heading need to be in singular. There is only 1 learning Activity in each topic. 
- [ ] The title of the activities should be out of the green box

**Unit 1, 2, 3, 4**
- [ ] Fix instructions for Assignment "Film Journal":

After completing this unit, including the learning activities, you are asked to make sure you are doing journal entries and when appropriate to share your responses with your facilitator and classmates when you meet.

Note that entries are expected for every unit. Your journal reflections are submitted at the end of the course as part of the **Self Assessment Exercise** worth **30**% of your course grade.

See the Assessments section for more details on submitting your journal, as well as the grading criteria.

**UNIT 2**
- [ ] Fix **topics**: 
- The Three Phases of Filmmaking
- Pre-Production, Production, and Post-Production
- [ ] **Learning Outcomes:** Remove space between LO
- [ ] **Activity Checklist:** The note at the end needs to be in plural and italicized 
- [ ] **Activity Checklist:** Unlink the resources 
- [ ] **Topic 2.1 The Three Phases of Filmmaking:** Fix grammar in first paragraph:

In Unit 1 we focused on project excellence and great **storytelling** and why they are important. This unit will help obtain these goals by breaking the filmmaking process down into three phases. Each phase depends upon the other and **if we fail** to understand and execute each one well, the other phases and the film itself will suffer.

- [ ] **Learning Activities:** Needs to be in singular: Learning Activit**y**
- [ ] **Learning Activities: Shooting a Film:** Helpful Hint needs to be bold
- [ ] **Learning Activities: Shooting a Film:** Remove the yellow box and its note. 
- [ ] **Summary:** Change summary

In this unit, you learned about the overall process of making a film as well as the steps involved in the following three phases:
- Pre-Production: this must be done before making a film to save time and help ensure quality, as you write the script, plan the production, and work out the logistics such as casting and finding locations and props. 
- Production: this involves shooting the film and where you use camera angles, camera motions, and the blocking of actors to reveal the meaning of your story and its characters. 
- Post-Production: this involves the editing and completing of your film where you cut the shots and scenes together, and includes adding titling, credits, special effects, music and sound design, and colour grading. 
- [ ]  Please make sure that the title of the activities are out of the green box.
- [ ] Please fix the heading and subheadings for this unit. There is a Learning Activity with a wrong heading level. 

**UNIT 3**
- [ ] Topics: Fix topics:
- Elements and Principles of Composition
- Photographic Themes
- [ ] Please check heading levels for this unit. Click on Topic 3.1 to see what I mean
- [ ] **Topic 1 overview:** Fix link in the Important Tip box: [The Visual Elements: The Building Blocks of Composition in Art](http://www.artyfactory.com/art_appreciation/visual-elements/visual-elements.html). When I click on it, it does not work.
- [ ] **Activity: Read and Study:** Remove the helpful link
- [ ] **Activity: Readings on Techniques and Principles of Composition:** Fix instruction:
Read the article “[20 Composition Techniques That Will Improve Your Photos](https://petapixel.com/2016/09/14/20-composition-techniques-will-improve-photos/)”, and "[Principles of Design](https://www.getty.edu/education/teachers/building_lessons/principles_design.pdf)". Practice and apply techniques and principles of design.
- [ ] **Activity: Read and Explore**: Remove article: [34 Powerful Photos That Tell a Story](https://www.jotform.com/blog/35-powerful-photos-that-each-tells-a-story/) since it does not exist anymore
- [ ] Fix the link for the article: [Walker Evans MoMA Exhibit](https://www.moma.org/artists/1777). Make sure it opens in a new window.
- [ ] Summary: Fix Grammar in the last paragraph: We have emphasized composition here because well composed shots are a foundational building block of a good film. As you will learn, if the head space of your shots is too much or too little, or there is a lack **of**balance of how people are arranged, or if you do not give enough leading entry space in a jogging shot...

**UNIT 4**
- [ ] Add **4.1** to topic 1. 
- [ ] Activity Checklist: Remove bold words. Keep only the description of each activity. 
- [ ] Learning Outcomes: fix it:
- Describe the various types of film motion shots
- Contrast the various types of film motion shots
- Determine when and how to use cinematic motion
- Create effective cinematic motion shots
- [ ] Resources: fix the list:
- Chapter Four of the course text: _Digital Filmmaking: A Beginner’s Guide to Mastering the Craft_, by Ned Vankevich
- Other online resources will be provided in the unit.
- [ ] **Learning Activities:** they need to be in 3 different green boxes, and please keep the titles out of each box. 
- [ ] Topic 4.1 is **4.2**. Please fix it.
- [ ] Please make sure all of the learning Activities titles are out of the green box. 
- [ ] Summary: Add this new one:
In this unit, you learned about cinematic motion and how to motivate it and do it properly. As such, you have gained understanding and practice with another important basic of excellent filmmaking.

1. Types of Cinematic Motion and how to use tracking shots, following shots, dolly shots, amount others to add professionalism and more meaning in your projects.
2. Motivating Camera Movement where you explore the classic cinema technique of discussing your moving shots by having the camera and subject movement in sync. 

**N.B.** These techniques are vital to learning and are the bases for excellent filmmaking.
- [ ] **Checking your Learning:** Align it to the initial Learning Outcomes:
- Describe the various types of film motion shots
- Contrast the various types of film motion shots
- Determine when and how to use cinematic motion
- Create effective cinematic motion shots

**Comment by Nataliadsanchez** [comment]
**UNIT 7**
 - [ ] There were several changes. Here is the Word doc for you to upload it again.
[MCOM 221_U7.docx](https://github.com/TWUOnline/bug-tracking/files/12434020/MCOM.221_U7.docx)

**Comment by Nataliadsanchez** [comment]
@MeeksonHundoo Could you please work on the edits for Unit 1-7 and upload Unit 8 to 9? Please send me a message if you have any question. Thanks!

**Comment by MeeksonHundoo** [comment]
Hello @Nataliadsanchez 
All the edits have been made and all the units which you asked me to upload again, have already been done. Following are some observations that I had in while uploading these units and making edits:
1. In unit 3, I didn’t quite understand this edit, "Please check heading levels for this unit. Click on Topic 3.1 to see what I mean."
2. In unit 8, you’ve mentioned to link the fairy tale template. Is it supposed to be linked in the Activity: Brainstorm and Prepare Your Pitch?
3. The topics overview in Unit 8 lists 4 topics, whereas only 3 are mentioned on the word doc. We’re missing the topic “Script and Story Development”.
4. Also unit 9 topics 1 & 2 have almost similar names. Could you please check which one is correct?
5. What about unit 10? I don’t see the word doc for unit 10. Do we have a unit 10 for this course?

**Comment by Nataliadsanchez** [comment]
Hi @MeeksonHundoo! Could you please work on the following edits?

**UNIT 1**
- [ ] **Assessment:** Please place "Course Journal" the title within the blue box.
- [ ] **Assessment:** Remove "Assignment 1" from Assignment 1: Film Journal

**UNIT 3**
- [ ] Activity Checklist: Remove the assessment part from the green box and add the following note at the end:

_Note that these learning activities are ungraded (unless specified), but they are designed to help you succeed in your assessments in this course._
- [ ] **Topic 3 ->** Principles of Composition is not a subtopic Please fix it.
- [ ] **Topic 3 ->  Important Tip:** The link "[Building Blocks of Composition in Art](https://www.artyfactory.com/art_appreciation/visual-elements/visual-elements.html)" does not work. Please fix it. 
- [ ] **Topic 3 ->** Please fix the "Activity: Read and Study" level
- [ ] **Topic 3: Activity: Readings on Techniques and Principles of Composition:** The name of the first link should be: "**28** Composition Techniques That Will Improve Your Photos". It should also open in a different tab. Please fix it. Also, remove {target=“_blank”} from the green box. Finally, remove the initial quotation mark from the second link. 
- [ ] **Assessment: Composition Exercise:** Italicize the final note: _See the Assessments section for more details on your composition, as well as the grading criteria._

**UNIT 4**
- [ ] **Activity Checklist:** Add the following note at the end: _Note that these learning activities are ungraded, unless specifie, but they are designed to help you succeed in your assessments in this course._

**UNIT 5**
- [ ] **Activity: Watch and Learn:** Please fix the link. It does not open in a new window. Also, please remove what is after it ({target=“_blank”})

**UNIT 7**
- [ ] **Assessment: Montage Project:** Fix the instruction: "This montage project will account for **30 %** of your grade and will be broken down according to the following:"
- [ ] **Summary:** Remove the three dots (...) after "In this unit, you learned about"

**UNIT 8**
- [ ] **Activity: Story Research:** Please add the link "[Watch: How to Write a Short Film](https://youtu.be/wMqIQcTMlA0)" before the video

**UNIT 9**
- [ ] **Activity: Read, Watch and Reflect:** Please add the links "[Watch: How to Shoot a Scene! ](https://youtu.be/IK2IAEO-FUI)" and "[Watch: Film Blocking Tutorial - Filmmaking Techniques for Directors: Ep3](https://youtu.be/9AGaECt9j4g)" before the videos
- [ ] **Topic 4:** Remove heading for **Shot list** 


**GENERAL NOTES:**
- [ ] Please, remove the "Assessment" and "References" that appear after Unit 9
- [ ] Make sure that it follows the[ GX template ](https://learn.twu.ca/course/view.php?id=30133&section=2#tabs-tree-start)

THANK YOU SO MUCH!!

**Comment by Nataliadsanchez** [comment]
**Unit 2**
- [ ] I think that there something going on in the code. Please most of the unit. Please fix the Activity checklist, the assessment in the overview *it should only say See the Assessment section in Moodle for assignment details and due dates). Some learning activities are not in color boxes, 2.2 Pre-Production, Production, and Post-Production need to be in accordion... Please refer to Unit 2 Word doc to make sure all the content is located in the right place. 

**UNIT 3**
- [ ] Remove 3.0.1 from **Assessment** in the overview
- [ ] **3.1.1 Principles of Composition** shouldnt be a heading. Only activities need heading levels

**UNIT 4**
- [ ] Add the assessment in the overview and it should also say: See the Assessment section in Moodle for assignment details and due dates.

**UNIT 8**
- [ ] Film Genres should not have a heading level. Just bold it as you did with Types of Film

**UNIT 9**
- [ ] Activities under Topic 9.4 **read and watch** should be: **Activity:** Read and watch. Add the word activity to it

**Comment by MeeksonHundoo** [comment]
Hello @Nataliadsanchez this is done..

**Comment by Nataliadsanchez** [comment]
Thanks @MeeksonHundoo !!
