### ISSUE TITLE
LDRS 303 - Instructor Videos

### ISSUE THREAD

**Issue by rezakh66** [TWUOnline/bug-tracking#92]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 LDRS 303
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 A video needs to be inserted
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=10748&section=3
2. Unit # 3        Topic #    topic/learning activity     Activity#  3.1
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
@cmadland 
Could you help insert all the videos from Stephen?  Here is the dropbox link: https://www.dropbox.com/sh/ojlr86f1bdetuim/AAD1YPUMtjmdt3cwisWuDRAMa?dl=0

**Comment by kmarjanovic** [comment]
@cmadland I see I can send dropbox files through slack.  Is that easier?
