### ISSUE TITLE
SOCI 101 GX edits

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#922]
**Which course contains the bug?**  
[SOCI 101 GX](https://twu-fhss.github.io/soci101/) 
 
**Describe the error and/or your suggestion**  

Unit 5:
- [x] In [this section](https://twu-fhss.github.io/soci101/social-institutions.html#the-religion-vs.-science-debate), please put the two images here side by side (same as in [Unit 1 here](https://twu-fhss.github.io/soci101/introduction-to-sociology.html#activity-sociological-imagination)) 
 
Unit 6:
- [x] Add missing images. They should be here https://github.com/TWUOnline/arts-master/tree/master/pages/06.soci101/_files/u6-media/media
- [x] For the 3 images in the Social Class and the Environment section, could you put those side by side as well?

**Comment by kmarjanovic** [comment]
More edits/Production requests:
Unit 7
- [ ] For the Collective Behaviours activity (images) - it used to have a slideshow in grav (see [Topic 1](https://learn.twu.ca/course/view.php?id=10781&section=7#tabs-tree-start)) .  Could you insert that here?  Alternatively, we could turn it into an H5P Image Slider https://h5p.org/image-slider#example=128905
- [ ] Please add the Unit 7 assessment page.  ([FAR Master](https://learn.twu.ca/course/view.php?id=10781&section=7#tabs-tree-start))
- [ ] Thank you!

**Comment by MeeksonHundoo** [comment]
Hello @kmarjanovic these edits have been made.

**Comment by kmarjanovic** [comment]
@MeeksonHundoo, could you please add the missing images in Unit 6 - above this section: https://twu-fhss.github.io/soci101/populations-and-the-environment.html#activity-urbanization

**Comment by MeeksonHundoo** [comment]
Hello @kmarjanovic the image is rendering correctly, (shown below) don't know why its not reflecting on github pages. I'll take a look...and get back
![image](https://github.com/TWUOnline/bug-tracking/assets/98780625/c68931e4-6006-423e-9566-d058640fb00f)

**Comment by kmarjanovic** [comment]
I see it now!  Thanks @MeeksonHundoo !

**Comment by MeeksonHundoo** [comment]
> I see it now! Thanks @MeeksonHundoo !

Yes @kmarjanovic all thanks to @cmadland for debugging this befuddling and inexplicable bug. Also, Colin, there's something up with the Unit 6 folder, the figure titled "Figure of growth rate of Congo, United States and Germany" was breaking again. what I did is,, moved that figure to Unit 7 folder and gave it that path. It got fixed instantly. 😲
