### ISSUE TITLE
614 content

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#923]
### Course

- [LDRS 614 (6 Week Master): Mission, Marketing and Quality](https://learn.twu.ca/course/view.php?id=30251&section=0#tabs-tree-start)
- [LDRS 614 in Bookdown](https://ma-lead.github.io/ldrs614/)
- comparing to [LDRS 614 - Mission, Marketing & Quality (FAR MASTER)](https://learn.twu.ca/course/view.php?id=20617&section=0#tabs-tree-start)
- for content mistakenly taken from [631](https://ma-lead.github.io/ldrs631/))

### Instructions
@Jeff-TWU please make the following edits
Unit 1
- [x] https://ma-lead.github.io/ldrs614/a-practices-of-intent.html#learning-activity-discussion-post-1-personal-marketing
    - [x] keep the first half of the activity & move the second half to the Unit 1: Forum 1 Marketing YOU (start at Introductory Post: Marketing YOU)
- [x] Delete topics 1.2, 1.3, 1.4
- [x] the [Birkman Assessment](https://ma-lead.github.io/ldrs614/a-practices-of-intent.html#assessment) is Individual Assignment 1 - due after Unit 2 (in Week 2)
Unit 2
- [x] [Discussion post activity](https://ma-lead.github.io/ldrs614/vision-and-marketing-imperative.html#learning-activity-discussion-post-2-reflections-on-marketing-yourself) should be removed at put in the Forum: Unit 2: Discussion Question 1
- [x] In the FAR master there is a different learning activity.  Please add from here [Unit 2, Topic 1, Learning Activity 2.1](https://learn.twu.ca/mod/page/view.php?id=673339&forceview=1)
- [x] 	Delete Topic 2.2
Unit 3:
- [x] [Topic 1](https://ma-lead.github.io/ldrs614/strategic-marketing-approaches.html#topic-1) - title: Strategic Marketing Approaches
- [x] Topic 2 - Scope of Strategy Definitions
- [x] Topic 3 - Marketing Strategy Layers
- [x] Learning Activity 3.1 is missing.  Please add from [here](https://learn.twu.ca/mod/page/view.php?id=673341&forceview=1)
- [x] [Unit 3 Discussion](https://ma-lead.github.io/ldrs614/strategic-marketing-approaches.html#activity-discussion-posts) is missing content.  see [here](https://learn.twu.ca/mod/forum/view.php?id=574933&forceview=1)

I'll need to do the rest of the units tomorrow.  If you can, compare bookdown and grav and you'll see what's missing.

Here's the assessment info as well:

## Assignments: 
(see [FAR Master Assignment section](https://learn.twu.ca/course/view.php?id=20617&section=1#tabs-tree-start)) 

Discussion Forum Posts (x8)
Individual Assignment (1)
Team Assignments (x2)
Final Assignment

Values:
Unit 1: Forum 1 Marketing YOU	10%
Unit 2: Discussion Question 1	5%
Unit 2: Individual Assignment 1	10%
Unit 3: Discussion Question 2	5%
Unit 4: Discussion Question 3	5%
Unit 4: Team Assignment 1	10%
Unit 6: Discussion Question 4	5%
Unit 6: Team Assignment 2	10%
Unit 7: Discussion Question 5	5%
Unit 8: Discussion Question 6	5%
Unit 9: Discussion Question 7	5%
Unit 10: Final Team Assignment: 90 second Course Trailer	25%
Total	100%

**Comment by Jeff-TWU** [comment]
> ### Course
> * [LDRS 614 (6 Week Master): Mission, Marketing and Quality](https://learn.twu.ca/course/view.php?id=30251&section=0#tabs-tree-start)
> * [LDRS 614 in Bookdown](https://ma-lead.github.io/ldrs614/)
> * comparing to [LDRS 614 - Mission, Marketing & Quality (FAR MASTER)](https://learn.twu.ca/course/view.php?id=20617&section=0#tabs-tree-start)
> * for content mistakenly taken from [631](https://ma-lead.github.io/ldrs631/))
> 
> ### Instructions
> @Jeff-TWU please make the following edits Unit 1
> 
> * [ ]  https://ma-lead.github.io/ldrs614/a-practices-of-intent.html#learning-activity-discussion-post-1-personal-marketing
>   
>   * [ ]  keep the first half of the activity & move the second half to the Unit 1: Forum 1 Marketing YOU (start at Introductory Post: Marketing YOU)
> * [ ]  Delete topics 1.2, 1.3, 1.4
> * [ ]  the [Birkman Assessment](https://ma-lead.github.io/ldrs614/a-practices-of-intent.html#assessment) is Individual Assignment 1 - due after Unit 2 (in Week 2)
>   Unit 2
> * [ ]  [Discussion post activity](https://ma-lead.github.io/ldrs614/vision-and-marketing-imperative.html#learning-activity-discussion-post-2-reflections-on-marketing-yourself) should be removed at put in the Forum: Unit 2: Discussion Question 1
> * [ ]  In the FAR master there is a different learning activity.  Please add from here [Unit 2, Topic 1, Learning Activity 2.1](https://learn.twu.ca/mod/page/view.php?id=673339&forceview=1)
> * [ ]  	Delete Topic 2.1
>   Unit 3:
> * [ ]  [Topic 1](https://ma-lead.github.io/ldrs614/strategic-marketing-approaches.html#topic-1) - title: Strategic Marketing Approaches
> * [ ]  Topic 2 - Scope of Strategy Definitions
> * [ ]  Topic 3 - Marketing Strategy Layers
> * [ ]  Learning Activity 3.1 is missing.  Please add from [here](https://learn.twu.ca/mod/page/view.php?id=673341&forceview=1)
> * [ ]  [Unit 3 Discussion](https://ma-lead.github.io/ldrs614/strategic-marketing-approaches.html#activity-discussion-posts) is missing content.  see [here](https://learn.twu.ca/mod/forum/view.php?id=574933&forceview=1)
> 
> I'll need to do the rest of the units tomorrow. If you can, compare bookdown and grav and you'll see what's missing.
> 
> Here's the assessment info as well:
> 
> ## Assignments:
> (see [FAR Master Assignment section](https://learn.twu.ca/course/view.php?id=20617&section=1#tabs-tree-start))
> 
> Discussion Forum Posts (x8) Individual Assignment (1) Team Assignments (x2) Final Assignment
> 
> Values: Unit 1: Forum 1 Marketing YOU 10% Unit 2: Discussion Question 1 5% Unit 2: Individual Assignment 1 10% Unit 3: Discussion Question 2 5% Unit 4: Discussion Question 3 5% Unit 4: Team Assignment 1 10% Unit 6: Discussion Question 4 5% Unit 6: Team Assignment 2 10% Unit 7: Discussion Question 5 5% Unit 8: Discussion Question 6 5% Unit 9: Discussion Question 7 5% Unit 10: Final Team Assignment: 90 second Course Trailer 25% Total 100%

I'm on it. Thanks @kmarjanovic

**Comment by kmarjanovic** [comment]
Looks like Units 4-10 match.  Phew!  @Jeff-TWU please let me know if you have any questions as you put in Moodle Books.

**Comment by Jeff-TWU** [comment]
> Looks like Units 4-10 match. Phew! @Jeff-TWU please let me know if you have any questions as you put in Moodle Books.

Working my way through it. Updated Bookdown first, now working through assignments, then will adjust units. Much smoother now! Ha ha! Thanks. I'll keep you posted.

**Comment by Jeff-TWU** [comment]
@kmarjanovic Sorted.

I just need to add the assignments to the course evaluation section of the hope page. Will need to rename some assignments. Everything else is set.
