### ISSUE TITLE
Production

### ISSUE THREAD

**Issue by meher-ahmed** [TWUOnline/bug-tracking#925]
625 Course

(https://learn.twu.ca/course/view.php?id=30231&section=1)

- [ ] Unit 1 Check your learning section is missing
- [ ] Unit 2 Summary, Check your learning section is missing
- [ ] Unit 3 Topic 3 (Examine the Strengths and Potential Limitations of Two Servant Leadership Metaphors) is missing
- [ ] Unit 4, 5, 6 Check your learning is missing
- [ ] Unit 7 missing - check your learning, summary, and learning activity missing for each chapter and assessment.
- [ ] unit 8 - Topic 3 learning activity, summary, check your learning missing.
- [ ] unit 9, chapter 4 activity forum post needs to be checked as an activity or assessment. If assessment then we need more information and rubric. If learning an activity, need more information on activity title.
- [ ] Unit 9 and 10 - Summary, check your learning missing
- [ ] Too many creative images which is not coherent with content. Each units each chapter has a creative image, which is not the case for other LDRS courses

@cmadland @kmarjanovic @Jeff-TWU @MeeksonHundoo @MaraChequer

**Comment by cmadland** [comment]
Duplicate issue - see https://github.com/ma-lead/ldrs625/issues/1
