### ISSUE TITLE
Change wording 

### ISSUE THREAD

**Issue by dhanenburg** [TWUOnline/bug-tracking#927]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 SOCI 320 - OL - FALL 2023
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 On the "General" tab, near the bottom, under "Course Evaluation" please delete "Students will be evaluated on a Pass/Fail basis according to the objectives noted above. Students must complete the required contractual hours at their field placement, hand in all required paperwork stated in the syllabus, and complete 75% of the required journal/online discussions and assignments to receive a passing grade." and REPLACE it with "The first human services field placement is a graded course and practicum 2 are Pass/Fail courses."  
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=29984&section=0#tabs-tree-start
2. Unit #         Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by dhanenburg** [comment]
Sorry, I had a typo....Replace with "The first human services field placement is a graded course and practicum 2 and 3 are Pass/Fail courses."

**Comment by MeeksonHundoo** [comment]
Hello @dhanenburg done..
