### ISSUE TITLE
SOCI 101 Quizzes

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#929]
### Course
[SOCI 101 GX](https://learn.twu.ca/course/view.php?id=30133&section=6)

### Instructions
- [x] Could you please check each of the 16 chapter quizzes in the Self-Assessment section to see if there are any questions that need to be reviewed by an instructor (e.g. short/long answer).  Could we hide or delete those for now? 
- [x] Please note that this does not apply to the Chapter Quizzes in the Assessment section (keeping those for GX Live)

**Comment by MeeksonHundoo** [comment]
Hello @kmarjanovic I checked all the 16 chapter quizzes individually on the moodle Self Assessment tab. Each chapter Quiz has 10 questions that are of MCQ type either being True/False or Fill in the blanks...none of those quizzes have any question that is categorized as a long/short answer.

**Comment by kmarjanovic** [comment]
Thank you so much, @MeeksonHundoo !!
