### ISSUE TITLE
LDRS 303 Unit 1 Learning Activities 

### ISSUE THREAD

**Issue by 345-Jay** [TWUOnline/bug-tracking#93]
LDRS 303 

**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
Checklist for learning  activity in Unit 1 has four learning activities but there are 5 learning activities in that unit.

Please confirm that they need 1.5. 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  http://far.twu.ca/ba-lead/ldrs303/u1/overview
2. Unit #  1     Topic #  Overview       Activity#  1.5
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
Yes, there should be 5 activities.  I had previously taken out all references to the key terms activities, but now that they're back in, we'll need to add those instructions.

@cmadland could we change the alerts to just show the basic task (read...watch...) - not the full activity descriptions (see content from original checklist)

**Comment by faitht1023** [comment]
I've added the U1 activity checklist with the basic tasks all in one alert and the full activity descriptions in a separate tab ("Learning Activities")
