### ISSUE TITLE
SOCI 101 discussions 

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#930]
### Course
[SOCI 101 GX Master](https://learn.twu.ca/course/view.php?id=30133&section=6#tabs-tree-start)

### Instructions
- [x] For the Discussions in the Self-Assessment page, could you set it up so students must submit a response first before they can see others' posts?

**Comment by MeeksonHundoo** [comment]
Hello @kmarjanovic this is done. Here is the link: https://learn.twu.ca/course/view.php?id=30133&section=6#tabs-tree-start

**Comment by kmarjanovic** [comment]
Thanks so much, Meekson!
