### ISSUE TITLE
SOCI 101 GX & X1 - import

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#931]
### Course
1. master to import: [SOCI 101 GX MASTER](https://learn.twu.ca/course/view.php?id=30133&section=0#tabs-tree-start)

2. GX Live: [SOCI 101 GX FA 2023](https://learn.twu.ca/course/view.php?id=29974)

3. GX Prime: [SOCI 101 PX FA 2023](https://learn.twu.ca/course/view.php?id=30234)

4. [SOCI 101 X1 FA 2023](https://learn.twu.ca/course/view.php?id=30187)
(@cmadland isn't Live supposed to be X1?)

### Instructions
- [x] Please import the Master into the FA 2023 shells - (2 and 3 above)
- [x] Please make sure the courses are still hidden from students (only GX FA 2023 has students; instructor & facilitator can unhide)
- [x] PX is the Prime version - so should have Assessment (Prime) tab and Self-Assessment tab
- [x] GX Live (should be just X1, but apparently they are using GX FA 2023) should have the Assessment tab (no Assessment Prime or Self-Evaluation)

Please let me know if you have any questions.

**Comment by cmadland** [comment]
First session in a term of Live is GX, second session in a term is X1

**Comment by meher-ahmed** [comment]
Noted

**Comment by meher-ahmed** [comment]
Hi @kmarjanovic can you pls explain - Please make sure the courses are still hidden from students (only GX FA 2023 has students; instructor & facilitator can unhide)
Which tab are you reffering to for **courses are still hidden from students**

**Comment by kmarjanovic** [comment]
Hi @meher-ahmed 
It's in Settings > Course Visibility > Hide.
When instructor's are ready (updated & uploaded the syllabus) then they can Show the course.

**Comment by meher-ahmed** [comment]
Edits complete. Pls review @cmadland @kmarjanovic 

1. GX Live: [SOCI 101 GX FA 2023](https://learn.twu.ca/course/view.php?id=29974)

2. GX Prime: [SOCI 101 PX FA 2023](https://learn.twu.ca/course/view.php?id=30234)

**Comment by kmarjanovic** [comment]
Somehow the Course Book for LDRS 471 was put in all the SOC 101 moodle shells (including master).  I fixed it - but it would be good to figure out how that happened!

**Comment by meher-ahmed** [comment]
That is strange!! I have imported content today from the links shared by @kmarjanovic in the issue tab. And I haven't worked on editing the content on Moodle Socio 101 Master
