### ISSUE TITLE
Edit to UNIV 301

### ISSUE THREAD

**Issue by dhanenburg** [TWUOnline/bug-tracking#933]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
UNIV 301 OL FA2023 
 
**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
Under Assessments tab/Overview tab, please change the column on the chart under "Due Date" and anywhere there is a specific date - replace with "Please see syllabus for Due Date". The first row for "Discussion Forum" can remain as it is with "Weekly (5 Weeks)" 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=30039&section=18#tabs-tree-start
2. URL for Master Course - please make the change here as well - https://learn.twu.ca/course/view.php?id=17766&section=18#tabs-tree-start
3. Unit #         Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by MeeksonHundoo** [comment]
Hello @dhanenburg it's done.
