### ISSUE TITLE
Production - Working Masters for LDRS

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#934]
### Course
all MA Lead courses

### Instructions
@Jeff-TWU Please make a copy all of the ldrs 6 week master courses.  Title should be: LDRS ####: [course Title] (6 week Working Master).

- [x] LDRS 500: Leadership Foundations 
- [x]	LDRS 501: Strategic Leadership
- [x]	LDRS 502: Team Leadership + Conflict Resolution
- [x]	LDRS 503: Results-based Leadership
- [x]	LDRS 504: Leadership Values & Ethics
- [x]	LDRS 591: Scholarly Inquiry
- [x]	LDRS 611: Organizational Behaviour
- [x]	LDRS 612: Leading Change & Innovation
- [x]	LDRS 614: Mission, Marketing & Quality
- [x]	LDRS 617: Employee Engagement & Stewardship
- [x]	LDRS 632: Leadership & Change 
- [x]	LDRS 631: Health Leadership Issues
- [x]	LDRS 634: Accountability & Performance
- [x]	LDRS 620: Worldview Foundation Educ Leadership
- [x]	LDRS 623: Developing Education Programs
- [x]	LDRS 624: School Leadership & Supervision
- [x]	LDRS 625: Educational Leadership & Dynamics
- [x]	LDRS 697: Leadership Integration Project I
- [x]	LDRS 698: Leadership Integration Project II

Please let me know the urls, as I'll need to enrol specific faculty by tomorrow morning.
Thank you!

**Comment by kmarjanovic** [comment]
Shoot!  Should I have made this issue in the MA Lead repo?  Does it make a difference for Production @cmadland ?

**Comment by Jeff-TWU** [comment]
@kmarjanovic Hi Kelly, I've created these.

[LDRS 500: Leadership Foundations (6 week Working Master)](https://learn.twu.ca/course/view.php?id=30331&section=0#tabs-tree-start)
[LDRS 501: Strategic Leadership (6 week Working Master)](https://learn.twu.ca/course/view.php?id=30332&section=0#tabs-tree-start)
[LDRS 502: Team Leadership + Conflict Resolution (6 week Working Master)](https://learn.twu.ca/course/view.php?id=30333&section=0#tabs-tree-start)
[LDRS 503: Results-based Leadership (6 week Working Master)](https://learn.twu.ca/course/view.php?id=30334&section=0#tabs-tree-start)
[LDRS 504: Leadership Values & Ethics (6 week Working Master)](https://learn.twu.ca/course/view.php?id=30335&section=0#tabs-tree-start)
[LDRS 591: Scholarly Inquiry (6 week Working Master)](https://learn.twu.ca/course/view.php?id=30336&section=0#tabs-tree-start)
[LDRS 611: Organizational (6 week Working Master)](https://learn.twu.ca/course/view.php?id=30337&section=0#tabs-tree-start)
[LDRS 612: Leading Change & Innovation (6 week Working Master)](https://learn.twu.ca/course/view.php?id=30338&section=0#tabs-tree-start)
[LDRS 614: Mission, Marketing & Quality (6 week Working Master)](https://learn.twu.ca/course/view.php?id=30339&section=0#tabs-tree-start)
[LDRS 617: Employee Engagement & Stewardship (6 week Working Master)](https://learn.twu.ca/course/view.php?id=30340&section=0#tabs-tree-start)
[LDRS 620: Worldview Foundation Educ Leadership (6 week Working Master)](https://learn.twu.ca/course/view.php?id=30345&section=0#tabs-tree-start)
[LDRS 623: Developing Education Programs (6 week Working Master)](https://learn.twu.ca/course/view.php?id=30346&section=0#tabs-tree-start)
[LDRS 624: School Leadership & Supervision (6 week Working Master)](https://learn.twu.ca/course/view.php?id=30347&section=0#tabs-tree-start)
[LDRS 625: Educational Leadership & Dynamics (6 week Working Master)](https://learn.twu.ca/course/view.php?id=30348&section=0#tabs-tree-start)
[LDRS 631: Health Leadership Issues (6 week Working Master)](https://learn.twu.ca/course/view.php?id=30343&section=0#tabs-tree-start)
[LDRS 632: Leadership & Change (6 week Working Master)](https://learn.twu.ca/course/view.php?id=30341&section=0#tabs-tree-start)
[LDRS 634: Accountability & Performance (6 week Working Master)](https://learn.twu.ca/course/view.php?id=30344&section=0#tabs-tree-start)
[LDRS 697: Leadership Integration Project I (6 week Working Master)](https://learn.twu.ca/course/view.php?id=30349&section=0#tabs-tree-start)
[LDRS 698: Leadership Integration Project II (6 week Working Master)](https://learn.twu.ca/course/view.php?id=30350&section=0#tabs-tree-start)

**Comment by kmarjanovic** [comment]
Thank you so much, Jeff!!

Could I make 1 more request to copy the 624 master content into the working master again?  I didn't realize Mara was still working on restructuring the course, so there are a number of changes to each page.

https://learn.twu.ca/course/view.php?id=30347&section=0#tabs-tree-start
https://learn.twu.ca/course/view.php?id=30308&section=0#tabs-tree-start

Sorry for the mix-up!

**Comment by Jeff-TWU** [comment]
> Thank you so much, Jeff!!
> 
> Could I make 1 more request to copy the 624 master content into the working master again? I didn't realize Mara was still working on restructuring the course, so there are a number of changes to each page.
> 
> https://learn.twu.ca/course/view.php?id=30347&section=0#tabs-tree-start https://learn.twu.ca/course/view.php?id=30308&section=0#tabs-tree-start
> 
> Sorry for the mix-up!

No problem. [Updated.](https://learn.twu.ca/course/view.php?id=30351)
