### ISSUE TITLE
Bookdown homepage edits for GX

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#936]
### Course
GX courses

### Instructions
Please make the following edits to the bookdown template:  (Full edits are also in Notion [here](https://www.notion.so/twuid/Bookdown-Template-e61814ae6c2648ae88f7aed1498065c3))

- [ ] In Welcome section, fix spelling: 1st paragraph opportunities  2nd paragraph, Assessment.

- [ ] Replace 6 in the first sentence with thematic: This book is divided into thematic units of study to help you engage with the materials.

- [ ] 2nd paragraph: indent: Below you will find information about how to navigate this book. Please read the full course syllabus located on the Course Home page in Moodle. It includes key information about the course schedule, assignments, and policies.

- [ ] in Course Notes section, indent: Assessment tasks are managed in other sections of the Moodle course, so be sure to familiarize yourself with those requirements and resources.

- [ ] In Navigation section, could we improve the contrast of the icons?  Doesn't pass the accessibility test.

- [ ] In Course units section, replace 6 with thematic: This course is organized into thematic units. 
- [ ] last note indent: Note that assessments, including assignments and discussion posts will be submitted in Moodle. See the Assessment section(s) in Moodle for full assignment details.

- [ ] End of page, add: If you have any questions, do not hesitate to ask. We are here to help and be your guide on this journey.

@cmadland @Nataliadsanchez @MaraChequer - feel free to suggest other changes!

Once confirmed, please update the homepage of these GX bookdown courses:
- [x] https://symmetrical-dollop-z7jp63l.pages.github.io/ (psyc 105)
- [x] https://twu-fhss.github.io/psyc106/
- [x] https://twu-busi.github.io/busi231/
- [x] https://twu-fhss.github.io/anth101/welcome.html
- [x] https://twu-fhss.github.io/hist107/
- [x] https://twu-samc.github.io/mcom281/
- [x] https://twu-fhss.github.io/phil100/

Let's hold off on these courses, as they are running (or SME is editing).  (to do after November 6th)
- [ ] https://twu-fhss.github.io/soci101/index.html#welcome
- [ ] https://twu-fhss.github.io/phil210-GX/
- [ ] https://twu-samc.github.io/mcom221/
- [ ] https://jubilant-disco-8km2y14.pages.github.io/ (ldrs 220)
- [ ] https://ba-leadership.github.io/pmpp201/
- [ ] https://twu-fhss.github.io/wrtg101/ (to do end of Dec.)

If there are any other GX courses in bookdown, please add the links in Notion: https://www.notion.so/twuid/FAR-GXP-Courses-9efebda59ba34d54aa46803a98fe0373

**Comment by meher-ahmed** [comment]
Noted

**Comment by Jeff-TWU** [comment]
@meher-ahmed making changes to the template now...

**Comment by meher-ahmed** [comment]
@Jeff-TWU ok. Once the template is updated I will work on making the changes to the homepage

**Comment by Jeff-TWU** [comment]
@kmarjanovic I've made updates to the [template](https://twuonline.github.io/bookdown-template/). One thing to note is that in bookdown we are limited to either indenting the first line of a paragraph, or creating line breaks, which is not ideal. [More info on indents](https://bookdown.org/yihui/rmarkdown-cookbook/indent-text.html).

Instead I added the paragraphs using block quotes. I think it works well, please confirm. Thanks!

**Comment by kmarjanovic** [comment]
Thanks Jeff!  I thought the block quote formatting was an indent, so what you've done is great!  :)

**Comment by meher-ahmed** [comment]
Hi @kmarjanovic homepage for the following course has been updated for these GX bookdown courses:

- [ ] https://symmetrical-dollop-z7jp63l.pages.github.io/ (psyc 105)
- [ ]  https://twu-fhss.github.io/psyc106/
- [ ]  https://twu-busi.github.io/busi231/
- [ ]  https://twu-fhss.github.io/anth101/welcome.html
- [ ]  https://twu-fhss.github.io/hist107/
- [ ]  https://twu-samc.github.io/mcom281/
- [ ]  https://twu-fhss.github.io/phil100/

**Comment by kmarjanovic** [comment]
Thank you @meher-ahmed !

**Comment by MaraChequer** [comment]
Thank you so much @meher-ahmed :)
