### ISSUE TITLE
PSYC 354 OL FA23 course changes

### ISSUE THREAD

**Issue by mackenzie111** [TWUOnline/bug-tracking#937]
**Which course contains the bug?**  
- PSYC 354 OL FA23
 
 
**Describe the error and/or your suggestion**  
I am teaching this course starting in November 2023 and I will be removing the article analysis assignment for the course. I was hoping to have all references and information about the article analysis removed from the Moodle course.
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=23420&section=10#tabs-tree-start                                  2. Unit #  course introduction (course evaluation section) and assessments tab (article analysis section). There may be more places where the article analysis is referenced, I am happy to meet over Zoom and help to explain this further if need be. 
 
**Optional: Screenshots**

**Comment by Jeff-TWU** [comment]
@mackenzie111 Hi Mackenzie, I've gone through and hidden all references to the article analysis assignment. Should be good to go.
