### ISSUE TITLE
LDRS 101 podcast link

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#939]
**Which course contains the bug?**  
LDRS 101 
 
**Describe the error and/or your suggestion**  

Could you help format the podcast?  
https://twu-innovation.github.io/inno101/building-a-network-of-people.html#activity-podcast-on-digital-citizenship

Thank you!

**Comment by Jeff-TWU** [comment]
I'm jumping in on this now.

**Comment by Jeff-TWU** [comment]
@kmarjanovic [Updated](https://twu-innovation.github.io/inno101/building-a-network-of-people.html#activity-podcast-on-digital-citizenship). Also I see that Colin already updated it yesterday? I simplified it, removing the image. Let me know if you'd prefer the image.

I also went through and fixed a bunch of formatting issues.
