### ISSUE TITLE
LDRS 300 IF FA19 - Quiz #1 - no questions added

### ISSUE THREAD

**Issue by BLMSasaki** [TWUOnline/bug-tracking#94]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 
 LDRS 300 IF FA2019

**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 
 Please upload the questions to Quiz #1 under the assessment tab, under the quiz tab. Thanks!

**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  
2. Unit #         Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
Hi Brenda,
Sorry, I made the request over a month ago, so checking again.  It'll be done by the end of the day!

**Comment by kmarjanovic** [comment]
Hi Brenda,
Could you email/attach the answers for the T/F section in Quiz #1?
