### ISSUE TITLE
Academic Dishonesty Policy - broken link

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#940]
**Which course contains the bug?**  
All courses 

**Describe the error and/or your suggestion**  
Could you please replace the broken link in the Academic Dishonesty Policy button? (on Course Home page in Moodle)

https://www.twu.ca/about-us/policies-guidelines/university-policies/academic-misconduct-fraud
 
 Let's start with those courses converted to Bookdown.  See Moodle Masters here:
- [ ] [FAR/GX](https://www.notion.so/twuid/FAR-GXP-Courses-9efebda59ba34d54aa46803a98fe0373) 
- [ ] [BA Lead](https://www.notion.so/twuid/BA-Leadership-608f69b2b6b0440db98fd1f319cc53f0) 
- [ ] [MA Lead](https://www.notion.so/MA-Leadership-4b888b1a626941ecbe780ed1d5a930ae)

Thanks @MaraChequer for pointing this out!

**Location of the bug**  
Course Home page in Moodle.

**Comment by Jeff-TWU** [comment]
I'll jump on this.
