### ISSUE TITLE
Broken link - Activity update

### ISSUE THREAD

**Issue by MaraChequer** [TWUOnline/bug-tracking#941]
**Which course contains the bug?**  
- Course LDRS 471 
https://learn.twu.ca/course/view.php?id=28301&section=2#tabs-tree-start
 
 
**Describe the error and/or your suggestion**  
Activity 6.2 (Unit 6), has a broken link. 
 
Replace Activity description with:
For this activity, watch the video below, How Do We ACTUALLY Build Trust In Our Teams? by Simon Sinek. During this talk, you will learn how to form strong bonds with others and succeed in life.
 
New Video link: https://youtu.be/08RU6oiFTdg?si=xv1fqOB6WuhSBaGF

**Comment by Jeff-TWU** [comment]
I'm working on this.

**Comment by Jeff-TWU** [comment]
> I'm working on this.

@MaraChequer [Fixed.](https://ba-leadership.github.io/ldrs471/the-essentials-for-success-collaboration-innovation-civic-mindset-and-humane-global-leadership.html#activity-watch-how-to-build-trust)

**Comment by MaraChequer** [comment]
[celebrate]     Mara Chequer reacted to your message:
________________________________

**Comment by MaraChequer** [comment]
thanks Jeff!
