### ISSUE TITLE
Psych 340 Fall Week 4

### ISSUE THREAD

**Issue by Mike2625** [TWUOnline/bug-tracking#942]
**Which course contains the bug?**  
- Psych 340 OL
 
**Describe the error and/or your suggestion**  
In the overview of week 4, please change the chapter readings to the following:

Readings for this week: Chapters 9,10,11,12(and if time look through chapter 13 on mostly immediacy)
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  
2. Unit # 4         Topic #   Overview      Activity#  Chapter reading
 
**Optional: Screenshots**

**Comment by Jeff-TWU** [comment]
Hi @Mike2625 Could you please provide a little more info?

Is this the course and section you are referring to?: https://learn.twu.ca/course/view.php?id=29865&section=4

Are you wanting to change the Learning activities? 
![Screenshot 2023-11-08 at 10 09 54 AM](https://github.com/TWUOnline/bug-tracking/assets/66963480/73b6442b-9a44-4896-aa72-8114d2b82019)

**Comment by Mike2625** [comment]
Yes, that is the one.  And please take out the portion in 4.1 that states:

First, read Chapter 8 from Hill (2020).

And in the overview in 4.1 noting:
Complete the Chapter 8 reading from our course textbook and view the additional readings/videos provided.


They can easily do 4.1 without reading chapter 8 (as this is noted in other sections of the book)

But yes, please fix the readings for week 4 in the overview section to Chapters 9, 10, 11 and 12

Week 5 in the overview to chapters  14, 15, 16, and 17

Thanks


"Faith is something whole and involves one's whole life. Jesus calls not to a new religion but to life" Dietrich Bonhoeffer

________________________________

**Comment by Jeff-TWU** [comment]
Hi @Mike2625 I've made the requested changes. Have a great day!
