### ISSUE TITLE
Remove Video

### ISSUE THREAD

**Issue by mackenzie111** [TWUOnline/bug-tracking#944]
**Which course contains the bug?**  
- PSYC 354 OL FA2023
 
 
**Describe the error and/or your suggestion**  
I am a new instructor teaching the course and there is an "instructor welcome" from the previous instructor that I was hoping could be removed from my course. I don't want students to be confused!
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL: https://learn.twu.ca/course/view.php?id=29868
2. Unit #  Course Introduction   Topic # Welcome to PSYC 354: Brain and Behaviour! 
 
Thank you!

**Comment by meher-ahmed** [comment]
Hi @mackenzie111 can you please share the master shell location you are working on for me to check on the content?

**Comment by cmadland** [comment]
I've removed the video from your course @mackenzie111 
https://github.com/TWUOnline/arts-master/commit/a2e5e4e5d3f5869d3fb1387629e84bd1d0890204
