### ISSUE TITLE
Moodle Master Shells for GX Courses

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#946]
### Course
GX courses & [GX Master Template](https://learn.twu.ca/course/view.php?id=30130&section=0)

### Instructions

Please add the template to these courses:
- [x] [ANTH 101](https://learn.twu.ca/course/view.php?id=28366&section=0#tabs-tree-start)

Please create a Moodle Master for these courses and apply the template
- [x] [FNDN 101](https://learn.twu.ca/course/view.php?id=28757) (wordPress course)
- [x] [ENGL 101: Introduction to Writing] (GX: https://learn.twu.ca/course/view.php?id=32191) (FAR: https://learn.twu.ca/course/view.php?id=15705)
- [x] [ENGL 102: Introduction to World Literature](https://learn.twu.ca/course/view.php?id=32162) 
- [x] [PSYC 105: Introduction to Psychology](https://learn.twu.ca/course/view.php?id=32192)
- [x] [PMPP 201: Introduction to Project Management](https://learn.twu.ca/course/view.php?id=32207&section=0)
- [x] [FNDN 102: Human Flourishing](https://learn.twu.ca/course/view.php?id=32189) 

Thank you!
tagging IDs @MaraChequer @Nataliadsanchez @dgaudet48 @ktchanx

**Comment by meher-ahmed** [comment]
Template added for [ANTH 101](https://learn.twu.ca/course/view.php?id=28366&section=6)

**Comment by meher-ahmed** [comment]
@kmarjanovic Hi Kelly, I have not created Moodle shell before, but giving it a shot here. Could you please share the course ID for  - FNDN 101
 - ENGL 101
 - ENGL 102
- PSYC 105
 - PMPP 201
 - FNDN 102
<img width="1440" alt="Screenshot 2023-11-14 at 2 47 27 PM" src="https://github.com/TWUOnline/bug-tracking/assets/130523647/0aacada0-a375-4efe-a8d7-1d9e7d808ebb">

**Comment by kmarjanovic** [comment]
Thanks so much, Meher!  For the course category, I usually select Development.  For the course full name e.g. "LDRS 101: Learning with Technology (GX MASTER)" and the short name "LDRS 101 (GX MASTER)".  

All of the course names, links, etc. can be found in Notion on our [FAR GXP page](https://www.notion.so/twuid/FAR-GXP-Courses-9efebda59ba34d54aa46803a98fe0373).  Once you have the urls, could you please add them there?

Thanks again!

**Comment by kmarjanovic** [comment]
Good morning @meher-ahmed !

Just checking [ANTH 101](https://learn.twu.ca/course/view.php?id=28366&section=0#tabs-tree-start).  It's missing the Community tab - and has 2 course notes tab.

Could you also confirm that no ANTH Moodle content was deleted?  Any Assignment info or Course info? Tagging @dgaudet48 in case there are other updates for the course.

**Comment by kmarjanovic** [comment]
Is there a shell created for FNDN 102 yet?  I need to show Jack his course today, so please import the GX template into the new Master shell for 102 and change the default book to https://learning-commons.github.io/fndn102/.
Thank you!

**Comment by chloecwh** [comment]
For sure! Let's hop on a call and create it!

**Comment by dgaudet48** [comment]
> Good morning @meher-ahmed !
> 
> Just checking [ANTH 101](https://learn.twu.ca/course/view.php?id=28366&section=0#tabs-tree-start). It's missing the Community tab - and has 2 course notes tab.
> 
> Could you also confirm that no ANTH Moodle content was deleted? Any Assignment info or Course info? Tagging @dgaudet48 in case there are other updates for the course.

@meher-ahmed @kmarjanovic No content has been added for ANTH101 yet

**Comment by meher-ahmed** [comment]
@dgaudet48 I don't recall deleting any content for ANTH 101. I had copied the template to the course

**Comment by meher-ahmed** [comment]
@dgaudet48 could you specify the location from where the content needs to go to [ANTH 101](https://learn.twu.ca/course/view.php?id=28366&section=3)

**Comment by meher-ahmed** [comment]
@kmarjanovic Can you pls check if this works [FNDN 101](https://learn.twu.ca/course/view.php?id=32190)? Then I will go ahead and create the other Moodle shells.

**Comment by kmarjanovic** [comment]
Hi @meher-ahmed , Yes that looks great!  I've done FNDN 102, so could you check if these next ones are done and add the Moodle links to Notion [here](https://www.notion.so/twuid/FAR-GXP-Courses-9efebda59ba34d54aa46803a98fe0373 )?

1.	PSYC 105: Introduction to Psychology
2.	ENGL 101: Introduction to Writing
3.	ENGL 102: Introduction to World Literature  ( I think Colin did this)
4.	PMPP 201: Introduction to Project Management
5.	LDRS 220: Leading with Numbers 

Thank you!

**Comment by kmarjanovic** [comment]
A couple more steps as I went through the process with Chloe:
1. Create new shell
2. Import content
3. Hide Guides section
4. Delete Forum from Home page
5. Add link to Notion
6. Let lead ID of the course know that the shell is ready
7. Extra step - if the Course info (description, learning outcomes, assessment) is available (see old Grav course or syllabus), please fill in that home page.

**Comment by chloecwh** [comment]
@kmarjanovic @dgaudet48 please check the above Moodle shells. ENGL 101 bookdown is empty so there's no content in the course unit.

**Comment by MaraChequer** [comment]
@chloecwh Engl 101 is mine. Let's chat to learn what you need.

**Comment by kmarjanovic** [comment]
These look great!  Thanks all!
