### ISSUE TITLE
Bookdown home page title & SME

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#947]
Hi all,
I'm just noticing some inconsistencies on the bookdown home page.

- Could we have the main title as LDRS: Full Course Title  
- next line: Course Developed by Phillip G. Laird, Ph.D.  (or appropriate SME)  
- On the left menu - could we have at the top the course number:  Leadership 370  

Please correct in the following...and any others you happen to be working on.

- [x] [LDRS 672](https://ma-lead.github.io/ldrs672/) - also remove tips for instructors
- [x] [LDRS 370](https://ba-leadership.github.io/ldrs370/)
- [x] [LDRS 371](https://ba-leadership.github.io/ldrs371/)
- [x] [LDRS 471](https://ba-leadership.github.io/ldrs471/) - SME Deon Pretorius, Ph.D.
- [x] [LDRS 472](https://ba-leadership.github.io/ldrs472/)
- [x] [LDRS 473](https://ba-leadership.github.io/ldrs473/)
- [x] [LDRS 670](https://ma-lead.github.io/ldrs670/) 
- [x] [LDRS 440](https://ba-leadership.github.io/ldrs440/)
- [x] [LDRS 320](https://ba-leadership.github.io/ldrs320/)

 Thank you!

**Comment by meher-ahmed** [comment]
Sure, letme make the changes @kmarjanovic

**Comment by meher-ahmed** [comment]
@kmarjanovic, where can I access the course developers name for these courses -
[LDRS 672](https://ma-lead.github.io/ldrs672/) - also remove tips for instructors
 [LDRS 370](https://ba-leadership.github.io/ldrs370/)
 [LDRS 371](https://ba-leadership.github.io/ldrs371/)
 [LDRS 471](https://ba-leadership.github.io/ldrs471/) - SME Deon Pretorius, Ph.D.
 [LDRS 472](https://ba-leadership.github.io/ldrs472/)
 [LDRS 473](https://ba-leadership.github.io/ldrs473/)
 [LDRS 670](https://ma-lead.github.io/ldrs670/)
 [LDRS 440](https://ba-leadership.github.io/ldrs440/)
 [LDRS 320](https://ba-leadership.github.io/ldrs320/)

**Comment by kmarjanovic** [comment]
Hi @meher-ahmed!
471 is by Deon Pretorius, 672 by Imbenzi George, 440 by Ben Manickam, 320 by Linda Vandersys.  All other courses are written by Phil Laird.
You can find all SMEs in the [Programs List](https://www.notion.so/twuid/f954953ac5394636b4f21db912cc4358?v=cdf8d7d11a3b4ce898eadd1010480c99) page in Notion, then in the specific program page:
- https://www.notion.so/twuid/Innovation-Certificates-458a9933492f437b8d1eae475932bc65
- https://www.notion.so/BA-Leadership-608f69b2b6b0440db98fd1f319cc53f0
- https://www.notion.so/twuid/MA-Leadership-4b888b1a626941ecbe780ed1d5a930ae

**Comment by meher-ahmed** [comment]
Thank you, @kmarjanovic. Could you let me know the content for the Welcome section for 672? It is currently empty

**Comment by meher-ahmed** [comment]
@kmarjanovic 
Can I use this content for 671 Welcome section -
 This is the course book for LDRS 672 : Global Relationship Development, Negotiation and Diplomacy. This book is divided into thematic units of study to help you engage with the materials. The course resources and learning activities are designed not only to help prepare you for the course assessments, but also to give you opportunities to practice various skills.

Below you will find information about how to navigate this book. Please read the full course syllabus located on the Course Home page in Moodle. It includes key information about the course schedule, assignments, and policies.

**Comment by meher-ahmed** [comment]
@kmarjanovic  would you want the tips for instructors section removed from LDRS 670? 
<img width="1440" alt="Screenshot 2023-11-17 at 5 27 33 PM" src="https://github.com/TWUOnline/bug-tracking/assets/130523647/df685c4a-5ac9-4ad3-9fd9-1ebcc96be454">

**Comment by kmarjanovic** [comment]
Hi @meher-ahmed 

The Tips for Instructors boxes should be deleted from all courses.  That was from an old template showing instructors the parts of a unit. 

And yes, for now please add that 672 snippet for the welcome.

@MaraChequer please let Meher know if there are changes, or whether Imbenzi has his own welcome message or video to include.

Thank you!

**Comment by MaraChequer** [comment]
Hi there! Imbenzi has not mentioned that will work on a welcome message but I will ask again about this. For now there are no changes to this course. Thank you @meher-ahmed , please reach out if you need anything else from me or notice any mistakes.
