### ISSUE TITLE
Bookdown edits

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#951]
- [x] Please remove the Sample Unit section from our bookdown courses:
e.g. https://twu-fhss.github.io/psyc106/sample-unit-format.html & https://symmetrical-dollop-z7jp63l.pages.github.io/sample-unit-format.html  (needs new url?)

- [x] For the Course Credits section, hide the info that is incomplete
https://symmetrical-dollop-z7jp63l.pages.github.io/course-credits.html
- Course Contributors & 11.3.1 Course Development Team (hide numbers?

- [x] Hide References page unless it is complete
https://twu-fhss.github.io/psyc106/references.html

**Comment by meher-ahmed** [comment]
Edits completed

**Comment by kmarjanovic** [comment]
Thanks so much, Meher!
