### ISSUE TITLE
Random bookdown edits

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#952]
**Describe the error and/or your suggestion**  
Please fix the following
- [x] Navigation icons in [bookdown template](https://twuonline.github.io/bookdown-template/index.html#how-to-navigate-this-book) are too big.  In other courses ([LDRS 220](https://cautious-disco-wooo74e.pages.github.io/index.html#how-to-navigate-this-book)) too light.  I like our [LDRS100](https://twu-innovation.github.io/inno101/index.html#how-to-navigate-this-book) example with the description under the image, but the contrast is not great.  Any thoughts? 
- [x] Please take out the [How this course is built](https://cautious-disco-wooo74e.pages.github.io/index.html#how-this-course-is-built) section, as it doesn't apply to many of our courses. (it should though;).  This will be in a study tips section in Moodle - not bookdown.
- [x] Please fix the table [Summary of technologies used on this course](https://twu-innovation.github.io/inno101/index.html#summary-of-technologies-used-on-this-course) - I think I missed a line.
- [ ] In general - hide the [References](https://cautious-disco-wooo74e.pages.github.io/references.html) section unless there is content.

Thank you!

**Comment by kmarjanovic** [comment]
And a couple more as I review course homepages in bookdown...

- [ ] PSYC 106 - the [video on the homepage](https://twu-fhss.github.io/psyc106/index.html#welcome) seems inaccessible.  Could you check what the issue is?
- [ ] Please delete the [LDRS 320 Assessment Page](https://ba-leadership.github.io/ldrs320/assessment-9.html) (for some reason it always defaults to LDRS 664 assignments?).  Also delete the [references ](https://ba-leadership.github.io/ldrs320/references.html)page.
- [ ] SOCI 101 - The [Navigate heading](https://twu-fhss.github.io/soci101/index.html#how-to-navigate-this-book) should be a lower level heading (no line)
- [ ] Also fix nav icons (too big) in SOCI 101
- [ ] [PHIL 210](https://twu-fhss.github.io/phil210-GX/index.html#how-this-course-is-built), [WRTG 101](https://twu-fhss.github.io/wrtg101/) and [MCOM 221](https://twu-samc.github.io/mcom221/index.html#how-this-course-is-built)- delete How this course was built.

**Comment by meher-ahmed** [comment]
@kmarjanovic 
<img width="1440" alt="Screenshot 2023-11-23 at 8 14 46 PM" src="https://github.com/TWUOnline/bug-tracking/assets/130523647/694ea738-fe39-4d86-be22-e160c7b7e4f4">
SOCI 101 - The Navigate heading is already in level H3 would you want it to be H4?

**Comment by kmarjanovic** [comment]
Hi @meher-ahmed !  So strange!  Yes, it's H3 that's needed...but I still see 2 lines here:

![image](https://github.com/TWUOnline/bug-tracking/assets/35148983/b4ff602c-1d01-4193-a960-1c7ce992ba3f)

**Comment by meher-ahmed** [comment]
Yes. I am not sure why this error is happening. Maybe @cmadland and @Jeff-TWU can help us ?

**Comment by Jeff-TWU** [comment]
> Navigation icons in [bookdown template](https://twuonline.github.io/bookdown-template/index.html#how-to-navigate-this-book) are too big. In other courses ([LDRS 220](https://cautious-disco-wooo74e.pages.github.io/index.html#how-to-navigate-this-book)) to light. I like our [LDRS100](https://twu-innovation.github.io/inno101/index.html#how-to-navigate-this-book) example with the description under the image, but the contrast is not great. Any thoughts?

@kmarjanovic Larger icons was in response to [issue 936](https://github.com/TWUOnline/bug-tracking/issues/936) where you wanted more contrast.
![Screenshot 2023-11-27 at 1 55 48 PM](https://github.com/TWUOnline/bug-tracking/assets/66963480/b68a5c38-9ecf-4d6a-966b-81e65fe5b264)

Icons can be remade with darker contrast. I don't have time this week but I can get to it next week.

> Yes. I am not sure why this error is happening. Maybe @cmadland and @Jeff-TWU can help us?

I looked at SOCI 101, There were 2 H2 headings. [Updated](https://twu-fhss.github.io/soci101/index.html#how-to-navigate-this-book). 

Just a friendly reminder that any updates to the reminder will not affect bookdown courses that have already been built. The only exception to this would be CSS styles that are called from [here](https://github.com/TWUOnline/course-materials/blob/master/bookdown_styles.css).

**Comment by kmarjanovic** [comment]
Thank you Jeff!  @meher-ahmed or @chloecwh please let me know when the other issues above have been resolved.
Thanks all!

**Comment by Jeff-TWU** [comment]
These edits have been made with the exception of the large navigation icons in [soci 101](https://twu-fhss.github.io/soci101/index.html#how-to-navigate-this-book). @cmadland I'm running into an issue where the latex is assigning an id with a `:` in it. This breaks the css. I was hoping to just be able to style the images with CSS to the appropriate size., but I might have to just remake the images.

Context: 
![Screenshot 2023-12-21 at 5 13 03 PM](https://github.com/TWUOnline/bug-tracking/assets/66963480/982f4c50-a06f-4485-a0a1-c59f843c62dd)
