### ISSUE TITLE
LDRS 503 formatting edits & copy to working masters

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#953]
### Instructions
[LDRS 503](https://learn.twu.ca/course/view.php?id=28348&section=1#tabs-tree-start) has a lot of formatting issues.  Please see below for Unit 1 and check the other units for similar issues.

Note: This course was scheduled for March, but now needed for January.  Instructors would like to edit in the Working Masters asap.

Please check the Unit Moodle Books (e.g. [Unit 1](https://learn.twu.ca/mod/book/view.php?id=919002)) to align with the formatting from our Moodle Master template (e.g. [Unit 1 in template](https://learn.twu.ca/mod/book/view.php?id=915827))
- [x] Learning Activities - heading level 1 (no numbers)
- [x] Topic &  activities are on different pages (see [Topic 2](https://learn.twu.ca/mod/book/view.php?id=919002&chapterid=8908))
- [x] Activity page: heading for Learning Activities. Activities don't have numbers.
- [x] Units may not have a summary, so please make the Checking For Learning Heading level 1.

- [x] Once all formatting is checked, please copy the revised [LDRS 503 6 week Master](https://learn.twu.ca/course/view.php?id=28348&section=0) content  to the [LDRS 503: Results-based Leadership (6 week Working Master)](https://learn.twu.ca/course/view.php?id=30334&section=0#tabs-tree-start)

**Comment by kmarjanovic** [comment]
Unit edits:
Please note all missing resources should be in original master: https://learn.twu.ca/course/view.php?id=13614 

Unit 1:
- [ ] Topic 2 learning activity resource missing - [The Best Story Wins](https://learn.twu.ca/assets/u1/Luhn_Ch1_Ch5.pdf)
- [ ]Topic 3 learning activity resource missing - [Workplace Communication Assessment Poll](https://learn.twu.ca/assets/u1/U1_Table_assignment.pdf)
- [ ] Topic 4 learning lab - add in the missing slideshows

Unit 2
- [ ] missing resources in [Resources section](https://learn.twu.ca/mod/book/view.php?id=918342&chapterid=8849): https://learn.twu.ca/assets/u2/Managing_Horizontal_Accountability.pdf, https://learn.twu.ca/assets/u2/Orange_Nonprofit.pdf, https://learn.twu.ca/assets/u2/Readiness_for_Organizational_Learning.pdf, https://learn.twu.ca/assets/u2/The_origins_and_practice_of_delivery.pdf, https://learn.twu.ca/assets/u2/Accountability_Example_7.pdf, https://learn.twu.ca/assets/u2/Accountability_Example_9.pdf, https://learn.twu.ca/assets/u2/Accountability_Example_10.pdf

Unit 3 
- [ ] Topic 5 missing resource: https://learn.twu.ca/assets/u3/Campbells_Law.pdf

Unit 4
- [ ] Topic 5 - take list out of accordion

Unit 5
- [ ] Resources section - missing: https://learn.twu.ca/assets/u5/BUILDING_CORPORATE_SOCIAL_RESPONSIBILITY.pdf

Unit 6 
- [ ] missing resources: Topic 3: https://learn.twu.ca/assets/u6/ControllingCascadingFailure.pdf, 

Unit 7
- [ ] missing resource: https://learn.twu.ca/assets/u7/Good_to_Great_by_Jim_Collins.pdf, https://learn.twu.ca/assets/u7/Good_to_Great_and_the_Social_Sectors.pdf

Unit 8
- [ ] missing resource: https://learn.twu.ca/assets/u8/What_is_Emotional_Intelligence.pdf

Unit 9
- [ ] resource missing in learning activity: https://learn.twu.ca/assets/u9/U9_Case_Study_New_Leaf.pdf

**Comment by kmarjanovic** [comment]
Hi @chloecwh @cmadland - can this issue be completed today?  DeAnn requested this last Monday and needs to open the course to the SMEs asap.  Thank you!

**Comment by chloecwh** [comment]
Hi Kelly, for sure! I'm working on it now

**Comment by chloecwh** [comment]
@kmarjanovic Unit 4 resources links expired (https://learn.twu.ca/mod/book/view.php?id=918847&chapterid=8871)
Also, regarding Topic 4.5 I can't seem to find your request - take the list out of accordion https://learn.twu.ca/mod/book/view.php?id=918847&chapterid=8868

Side note - I worked on master instead of working master by mistake.

**Comment by kmarjanovic** [comment]
Okay thanks Chloe!  Let's just leave a note by those links to let the SME know they need to find a new link.

For the accordion - it's this one: https://ma-lead.github.io/LDRS503/performance-based-leadership-in-tsl-budgetary-practice.html#types-of-accounting

**Comment by chloecwh** [comment]
Resources U5 also has a link that's expired: https://learn.twu.ca/mod/book/view.php?id=918852&chapterid=8873
U6 https://learn.twu.ca/mod/book/view.php?id=918853&chapterid=8883

**Comment by chloecwh** [comment]
All tasks done, except duplicating master to working master and importing h5p slides from (https://far.twu.ca/ldrs/503/presentations/u1#/u1-0) @kmarjanovic

**Comment by chloecwh** [comment]
Sounds good! I copied 6 week master to working master @kmarjanovic
