### ISSUE TITLE
PHIL 100 Assessment section

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#959]
**Which course contains the bug?**  
[PHIL 100](https://twu-fhss.github.io/phil100/assessment.html)
 
 
**Describe the error and/or your suggestion**  
Please hide the assessment section and references section.  Only show them if there is content from the ID.  In this case - it's showing a default assessment page from LDRS 664.  I'm not sure why this keeps happening in courses, as the [Template ](https://twuonline.github.io/bookdown-template/) doesn't have that 664 info.

**Comment by meher-ahmed** [comment]
On it @kmarjanovic

**Comment by meher-ahmed** [comment]
@kmarjanovic Assessment and Reference section is hidden. Letme know if you would need any more edits in this course. [PHIL100](https://twu-fhss.github.io/phil100/) Thank you!

**Comment by kmarjanovic** [comment]
Thanks so much, @meher-ahmed !
