### ISSUE TITLE
LDRS 101 video link

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#960]
**Which course contains the bug?**  
LDRS 101 
 
**Describe the error and/or your suggestion**  
Please help add this [vimeo video](https://vimeo.com/493206161) to [this section](https://twu-innovation.github.io/inno101/introduction-to-digital-literacies-for-online-learning.html#learning-online) in Unit 1.

Not sure why the code didn't work...

**Comment by chloecwh** [comment]
I'm on it!

**Comment by chloecwh** [comment]
[Updated](https://twu-innovation.github.io/inno101/introduction-to-digital-literacies-for-online-learning.html#learning-online) @kmarjanovic
