### ISSUE TITLE
PSYC 105

### ISSUE THREAD

**Issue by dgaudet48** [TWUOnline/bug-tracking#962]
### Instructions
Please update the following content into bookdown:
- [x] [Psych105_Unit1.docx](https://github.com/TWUOnline/bug-tracking/files/13697950/Psych105_Unit1.docx)
- [x] [Psych105_Unit2.docx](https://github.com/TWUOnline/bug-tracking/files/13697952/Psych105_Unit2.docx)
- [x] [Psych105_Unit3.docx](https://github.com/TWUOnline/bug-tracking/files/13697953/Psych105_Unit3.docx)
- [x] [Psych105_Unit4.docx](https://github.com/TWUOnline/bug-tracking/files/13697976/Psych105_Unit4.docx)
- [x] [Psych105_Unit5.docx](https://github.com/TWUOnline/bug-tracking/files/13697977/Psych105_Unit5.docx)
- [x] [Psych105_Unit6.docx](https://github.com/TWUOnline/bug-tracking/files/13697978/Psych105_Unit6.docx)
- [x] [Psych105_Unit7.docx](https://github.com/TWUOnline/bug-tracking/files/13697979/Psych105_Unit7.docx)
- [x] [Psych105_Unit8.docx](https://github.com/TWUOnline/bug-tracking/files/13697980/Psych105_Unit8.docx)
- [x] [Psych105_Unit9.docx](https://github.com/TWUOnline/bug-tracking/files/13697981/Psych105_Unit9.docx)
- [x] [Psych105_Unit10.docx](https://github.com/TWUOnline/bug-tracking/files/13697982/Psych105_Unit10.docx)

Please upload required files as attachments.

**Comment by dgaudet48** [comment]
@chloecwh 

Please move the following into the new [GX Master shell LIVE Assessment Page](https://learn.twu.ca/course/view.php?id=32192&section=5#tabs-tree-start)

- [ ] Quiz 1 found [here](https://learn.twu.ca/course/view.php?id=15666&section=4#tabs-tree-start)
- [ ] Quiz 2 found [here](https://learn.twu.ca/course/view.php?id=15666&section=8#tabs-tree-start)
- [ ] Quiz 3 found [here](https://learn.twu.ca/course/view.php?id=15666&section=11#tabs-tree-start)
- [ ] Final Exam found [here](https://learn.twu.ca/course/view.php?id=15666&section=13#tabs-tree-start)

**Comment by chloecwh** [comment]
I've updated the units but are missing the photos. Will work on the quizzes tomorrow!

**Comment by chloecwh** [comment]
Hi @dgaudet48 I've added quizes 1-3 and final exam in the assessment (gx live) tab. https://learn.twu.ca/course/view.php?id=32192&section=5#tabs-tree-start

I've kept the final exam tab from dev to the gx shell. Let me know what you think!

**Comment by dgaudet48** [comment]
@chloecwh Thanks!

Here are some additional updates (along with the missing images)

- [ ] Add this ![Neuron_Image_Psyc105](https://github.com/TWUOnline/bug-tracking/assets/52174877/f048265e-35ee-4709-bd3d-66fa88e860f9) here https://learn.twu.ca/course/view.php?id=32192&section=3#tabs-tree-start
- [ ] highlight "Read and Reflect" Activity in green alert colour https://twu-fhss.github.io/psyc105/processes-of-sensation.html#activity-read-and-reflect-2
- [ ] https://twu-fhss.github.io/psyc105/processes-of-sensation.html#activity-colour-deficiencies-and-colour-blindness - highlight Activity "Colour Deficiencies and Colour Blindness" in green alert
- [ ] https://twu-fhss.github.io/psyc105/processes-of-sensation.html#activity-how-the-ear-works highlight activity "How the Ear Works" in green
- [ ] edit activity "How the Ear Works" so that the first sentence is "We begin this activity"
- [ ] There is a {Target=blank} showing up in this same activity
- [ ] https://twu-fhss.github.io/psyc105/processes-of-sensation.html#activity-all-about-paint - please highlight this activity with the green alert
- [ ] https://twu-fhss.github.io/psyc105/processes-of-sensation.html#checking-your-learning-3 - Bullet points have some weird spacing going on - could you please fix
- [ ] URL: https://twu-fhss.github.io/psyc105/perception.html#activity-ambiguous-figure-illusions - please add this ![Psych105_Topic1_Image](https://github.com/TWUOnline/bug-tracking/assets/52174877/19f0b00c-0969-47e0-a78e-ecf5b7323881)
- [ ] URL: https://twu-fhss.github.io/psyc105/perception.html#visual-perception-depth-distance-and-motion - please add this ![Psych105_Image_U5_depthanddistance](https://github.com/TWUOnline/bug-tracking/assets/52174877/cbf47d64-b549-4f43-a554-a0121f70eb14)
- [ ] URL: https://twu-fhss.github.io/psyc105/perception.html#activity-a-search-for-meaning - please add this ![Psych105_5fs_Image](https://github.com/TWUOnline/bug-tracking/assets/52174877/30b79789-3123-4cd5-8e6c-58a468c689c7) for the "5 F's" section
- [ ] URL: https://twu-fhss.github.io/psyc105/perception.html#activity-a-search-for-meaning - please add this ![PSYCH105_Pieshaped_activity_Image](https://github.com/TWUOnline/bug-tracking/assets/52174877/20ab420b-4302-4b80-b34b-3ab5627217cf) under where it says "...black pie-shaped segments:"
- [ ] URL: https://twu-fhss.github.io/psyc105/perception.html#activity-a-search-for-meaning - please add this ![PSYCH105_Escher_Image](https://github.com/TWUOnline/bug-tracking/assets/52174877/f6da9aa4-3405-44a5-ae60-ddabdf78d1b7) after the statement "...Escher drawing or an “impossible” object such as this:"
- [ ] URL: https://twu-fhss.github.io/psyc105/conciousness.html#activity-drug-information-resources - please highlight this activity using the green alert
- [ ] URL: https://twu-fhss.github.io/psyc105/motivation-and-emotion.html#biology-of-emotion - Under the section titled "Important Role" there is a weird formatting issue and "1943" is standing out all alone...could you please fix
- [ ] URL: https://twu-fhss.github.io/psyc105/the-science-of-psychology.html#principles-of-scientific-research - please highlight the "Note" at the bottom in yellow

**Comment by dgaudet48** [comment]
@chloecwh Unit 1 does not look like it has been updated - attaching the word document below:

- [ ] Update [Psych105_Unit1.docx](https://github.com/TWUOnline/bug-tracking/files/13896755/Psych105_Unit1.docx) to reflect this content

**Comment by meher-ahmed** [comment]
Hi, @dgaudet48  @chloecwh, Unit 1 has been updated as per the new Word doc. content. I have not deleted the older content incase it is needed for reff. I have kept it hidden. Feel free to delete it if you need. Thank you!
!

**Comment by dgaudet48** [comment]
@meher-ahmed @chloecwh Any timeline for the additional edits? Todd is inquiring as he would like to perform a final review ASAP

Thanks again

**Comment by chloecwh** [comment]
Hi @dgaudet48 yes, I will work on it in an hour.

**Comment by chloecwh** [comment]
[Psych105_Topic1_Image](https://github.com/TWUOnline/bug-tracking/assets/52174877/19f0b00c-0969-47e0-a78e-ecf5b7323881)
[Psych105_Image_U5_depthanddistance](https://github.com/TWUOnline/bug-tracking/assets/52174877/cbf47d64-b549-4f43-a554-a0121f70eb14)
[Psych105_5fs_Image](https://github.com/TWUOnline/bug-tracking/assets/52174877/30b79789-3123-4cd5-8e6c-58a468c689c7) 
[PSYCH105_Pieshaped_activity_Image](https://github.com/TWUOnline/bug-tracking/assets/52174877/20ab420b-4302-4b80-b34b-3ab5627217cf) [PSYCH105_Escher_Image](https://github.com/TWUOnline/bug-tracking/assets/52174877/f6da9aa4-3405-44a5-ae60-ddabdf78d1b7)

**Comment by chloecwh** [comment]
[PSYCH105_Escher_Image](https://github.com/TWUOnline/bug-tracking/assets/52174877/f6da9aa4-3405-44a5-ae60-ddabdf78d1b7

**Comment by chloecwh** [comment]
@dgaudet48 it's updated, thanks for being patient.

**Comment by dgaudet48** [comment]
@chloecwh 

- [ ] URL: https://twu-fhss.github.io/psyc105/biological-psychology.html#activity-neurscience
          - Spelling issue - can you update "Activity: Neurscience" - it should read "Activity: Neuroscience"

**Comment by chloecwh** [comment]
@dgaudet48 done!

**Comment by kmarjanovic** [comment]
Added PSYC 105 card in course-logistics for Design Schedule.
This card should be an issue, correct?

**Comment by chloecwh** [comment]
Hi @dgaudet48 While importing U8 Check your learning to X2 FA 2024 course, I have noticed that Check your learning in the last bit doesn't relate to memory at all... Would you mind taking a look? 
![Screenshot 2024-10-30 at 4 04 49 PM](https://github.com/user-attachments/assets/065be770-794d-499b-bfc4-b8749b52490f)

**Comment by dgaudet48** [comment]
@chloecwh These were the learning outcomes that were given to me and approved by Todd...

@kmarjanovic are you ok with me reaching out and re-confirming that these are the learning outcomes he would like for Unit 8?

**Comment by kmarjanovic** [comment]
@dgaudet48 yes please do!  It seems the LOs & Check Your Learning are about a stress unit, not Ch.8's memory unit.
Here's chapter 7 LOs from the textbook:
•	Know the key terminology of memory systems.
•	Understand which structures in the brain are associated with specific memory tasks and how the brain changes as new memories form.
•	Apply your knowledge of the neural basis of memory to predict what types of memory would be affected by damage to different areas of the brain.
•	Analyze the claim that humans have multiple memory systems

**Comment by kmarjanovic** [comment]
@dgaudet48 
Just saw they are the same as PSYC 106 Unit 9 LOs on Stress & Coping

**Comment by dgaudet48** [comment]
@chloecwh @kmarjanovic I spoke with Todd today and we went through Unit 8. He would like the LO's to be updated with the following:


- Define the key terminology of memory systems including forgetting, encoding, retrieval, and how memories are organized and constructed.
- Describe which structures in the brain are associated with specific memory tasks and how the brain changes as new memories form and how the type of cognitive processing employed can affect the chances of remembering what you encounter.
- Apply your knowledge of the neural basis of memory to predict what types of memory would be affected by damage to different areas of the brain and how to improve your ability to memorize information.
- Analyze the claim that humans have multiple memory systems and whether emotional memories are more accurate than non-emotional ones.
- Describe why schemas are important frameworks for encoding and constructing memories and how psychologists can produce false memories in the laboratory.
- Analyze what you have learned to judge the reliability of eyewitness testimony and why that is important in the “recovered memory” debate.

**Comment by kmarjanovic** [comment]
Thanks so much, @dgaudet48 !  Chloe, could you please make those changes to the LO & Check Your Learning sections of [Unit 8](https://learn.twu.ca/course/view.php?id=34577&section=2#tabs-tree-start)?

**Comment by chloecwh** [comment]
@dgaudet48 Sounds good. Any update on other units? 

> @chloecwh @kmarjanovic I spoke with Todd today and we went through Unit 8. He would like the LO's to be updated with the following:
> 
> * Define the key terminology of memory systems including forgetting, encoding, retrieval, and how memories are organized and constructed.
> * Describe which structures in the brain are associated with specific memory tasks and how the brain changes as new memories form and how the type of cognitive processing employed can affect the chances of remembering what you encounter.
> * Apply your knowledge of the neural basis of memory to predict what types of memory would be affected by damage to different areas of the brain and how to improve your ability to memorize information.
> * Analyze the claim that humans have multiple memory systems and whether emotional memories are more accurate than non-emotional ones.
> * Describe why schemas are important frameworks for encoding and constructing memories and how psychologists can produce false memories in the laboratory.
> * Analyze what you have learned to judge the reliability of eyewitness testimony and why that is important in the “recovered memory” debate.

**Comment by Jeff-TWU** [comment]
> Thanks so much, @dgaudet48 ! Chloe, could you please make those changes to the LO & Check Your Learning sections of [Unit 8](https://learn.twu.ca/course/view.php?id=34577&section=2#tabs-tree-start)?

@chloecwh @kmarjanovic I've updated the this request but will hold off on updating Moodle course content until I receive confirmation there are no more changes.  Above changes can be viewed here: [https://twu-fhss.github.io/psyc105/memory.html](https://twu-fhss.github.io/psyc105/memory.html)

**Comment by kmarjanovic** [comment]
Looks right to me!  Feel free to update.
Thanks Jeff!

**Comment by Jeff-TWU** [comment]
> Looks right to me! Feel free to update. Thanks Jeff!

@kmarjanovic Updated the master and the [active course](https://learn.twu.ca/course/view.php?id=34577&section=2#tabs-tree-start).
