### ISSUE TITLE
SOCI 320 OL edits

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#965]
**Which course contains the bug?**  

[SOCI 320 OL - Field Placement (SP 2024)](https://learn.twu.ca/course/view.php?id=32015) 
 
**Describe the error and/or your suggestion**  
From SME:

Here are the edits I want to make to the SOCI 320 OL (SP24) course:

Under the Praxis Preparation tab --> Activity 1.2 - the date needs to be changed to January 22nd at 6 pm

Under the Praxis Preparation tab --> Topic 3 --> the hyperlinked document needs to be changed to the one I have attached to this email. The title can remain the same.

Under the Praxis Preparation tab --> Activities --> change date on Activity 1.2 to be January 22nd at 6 pm. Also edit, "After the orientation there is a monthly zoom "process group" that is not required but highly recommended and the other weeks will consist of a discussion forum." Changing the words to "monthly" and "other."

Under the Praxis Preparation tab --> Praxis Preparation Summary --> remove Debra's email.

Thank you!

MacKenzie 
________________________________________
[Praxis Schedule CURRENT FA23.docx](https://github.com/TWUOnline/bug-tracking/files/13907508/Praxis.Schedule.CURRENT.FA23.docx)

**Comment by chloecwh** [comment]
@kmarjanovic Updated as you request!

**Comment by kmarjanovic** [comment]
Thanks @chloecwh !
