### ISSUE TITLE
PSYC ADC Revisions - SME tracking

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#967]
### Course
PSYC ADC Revisions

https://github.com/TWUOnline/sme-logistics/issues/new/choose

### Instructions
Just wondering if this is something Production can help set up, then tag the assigned ID to fill in the details?

- [x] Please create new git cards for the following courses

1.	PSYC 207: Data Analysis  (ID: KATY) 
2.	PSYC 215: Lifespan Development (ID: KATY) 
3.	PSYC 301: Theories of Personality(ID: KELLY) 
4.	PSYC 305: Abnormal Psychology  (ID: KATY) 
5. 	PSYC 322: Research Methods II  (KATY) 
6.	PSYC 331: Theories of Counselling (ID: MARA) 
7.	PSYC 340: Interpersonal and Helping Skills  (ID: MARA) 
8.	SOCI 201: Introduction to Human Services  (ID: MARA) 
9.	SOCI 221: Sociology of Family – Todd Martin (ID: NATALIA) 
10.	SOCI 400: Critical Issues in Human Services t (ID: KATY)

**Comment by chloecwh** [comment]
@kmarjanovic @cmadland 
Hi Kelly, are these courses new designes (which go into course logistics) or are they revisions that go into course repositories?

**Comment by kmarjanovic** [comment]
@chloecwh  they are revisions.

**Comment by chloecwh** [comment]
Ok I'll create issue under each class repo 
@kmarjanovic @cmadland

**Comment by kmarjanovic** [comment]
Thanks Chloe!
Are you also able to add the SME cards for tracking payments? ([MCOM example](https://github.com/TWUOnline/sme-logistics/issues/84))

**Comment by chloecwh** [comment]
@kmarjanovic Would you mind giving me access to SME payment tracking project and access to ([MCOM example](https://github.com/TWUOnline/sme-logistics/issues/84))? Thank you!

**Comment by kmarjanovic** [comment]
@chloecwh you should have access now: https://github.com/TWUOnline/sme-logistics/issues

**Comment by chloecwh** [comment]
Hi @kmarjanovic , I used PSYC 301 as an example. 

SME card: https://github.com/TWUOnline/sme-logistics/issues/86
Issue card: https://github.com/psyc-adc/psyc301/issues/1

If these cards are correct, I can ask Colin to invite other IDs into these repo.

**Comment by kmarjanovic** [comment]
Thanks so much Chloe!!

For course revisions, the deliverables are different.  I updated the card: https://github.com/TWUOnline/sme-logistics/issues/86

**Comment by kmarjanovic** [comment]
Just wondering too about the WP conversion workflow.  Should we add for Production to create a Word doc to send to IDs.  This will (hopefully) speed up the process for SMEs sending in edits.

**Comment by chloecwh** [comment]
@kmarjanovic From the production standpoint. It's the same one for Bookdown... I can confirm with Jeff (:

**Comment by chloecwh** [comment]
@kmarjanovic done
