### ISSUE TITLE
PSYC 301 master update

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#968]
### Course
[PSYC 301 - Theories of Personality (ADC MASTER)](https://learn.twu.ca/course/view.php?id=18759&section=0#tabs-tree-start)

[PSYC 301 OL - Theories of Personality (FA 2023)](https://learn.twu.ca/course/view.php?id=29855&section=0#tabs-tree-start)

### Instructions
- [x] Please replace the content in the Master with the content from the FA 2023 section.
- [x] I don't need the 2 zoom tabs
- [x] Also - please don't copy over any student info.  (need assignment dropboxes, but no student submissions)

**Comment by kmarjanovic** [comment]
A couple more edits:

- [ ] In the [Projects page](https://learn.twu.ca/course/view.php?id=18759&section=9#tabs-tree-start), please change the 
"four-page paper" reference to "two-page paper" in both Project 1 and Project 2.

(Note that Todd is not a fan of Git, so will likely make edit requests via email)

**Comment by chloecwh** [comment]
I'm on it!

**Comment by chloecwh** [comment]
Done @kmarjanovic

**Comment by kmarjanovic** [comment]
Thanks so much Chloe!
