### ISSUE TITLE
LDRS 504 pwpt

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#972]
### Instructions
Please upload to 
[LDRS 504: Leadership Values & Ethics (6 week Working Master) - Instructor Resources](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.twu.ca%2Fcourse%2Fview.php%3Fid%3D30335%26section%3D8%23tabs-tree-start&data=05%7C02%7CKelly.Marjanovic%40twu.ca%7C1dc1cf091e6f4fe4665a08dc1ba8f860%7C2b4ef155167343efa480230c3d483f16%7C0%7C0%7C638415659727156326%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=fxzfIb3fiw9ETcxavDgj1qZj31Bj0VL2iLIxVkaFAyk%3D&reserved=0)

 [Unit-9 Overview of Ethical Leadership-How to Develop Responsible Leadership Business.PPTX](https://can01.safelinks.protection.outlook.com/ap/p-59584e83/?url=https%3A%2F%2Fmytwu-my.sharepoint.com%2F%3Ap%3A%2Fg%2Fpersonal%2Fimbenzi_george_twu_ca%2FES2IoX_LenRAvvWjKADMkDsBfPNHdZTYHZKsYIYBo9vCaw&data=05%7C02%7CKelly.Marjanovic%40twu.ca%7C1dc1cf091e6f4fe4665a08dc1ba8f860%7C2b4ef155167343efa480230c3d483f16%7C0%7C0%7C638415659727150351%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=AwB34Hwb5J2qYQ482HYakTMH%2BQMQhJ8QCaEpXT8gaLo%3D&reserved=0)
 [Unit-8 Building an Effective Ethical Group-Developing Leadership for Sustainable Business.PPTX](https://can01.safelinks.protection.outlook.com/ap/p-59584e83/?url=https%3A%2F%2Fmytwu-my.sharepoint.com%2F%3Ap%3A%2Fg%2Fpersonal%2Fimbenzi_george_twu_ca%2FEcoY3aeeyjlHutKU1V1B7bEBVxQbQ-QB7hovKCHPP7ctSA&data=05%7C02%7CKelly.Marjanovic%40twu.ca%7C1dc1cf091e6f4fe4665a08dc1ba8f860%7C2b4ef155167343efa480230c3d483f16%7C0%7C0%7C638415659727144286%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ldhdJSQ6cxpwZl10PrvpBqkHqRBc87jnMfiToQVKXeY%3D&reserved=0)
 [Unit-7 Ethical Challenge of Diversity-Leading Responsibly Across Cultures.PPTX](https://can01.safelinks.protection.outlook.com/ap/p-59584e83/?url=https%3A%2F%2Fmytwu-my.sharepoint.com%2F%3Ap%3A%2Fg%2Fpersonal%2Fimbenzi_george_twu_ca%2FEYLqz7wXYrNCqyh72eg8Vl0Bd1pEna3CcxtRB0y0tE2KZQ&data=05%7C02%7CKelly.Marjanovic%40twu.ca%7C1dc1cf091e6f4fe4665a08dc1ba8f860%7C2b4ef155167343efa480230c3d483f16%7C0%7C0%7C638415659727137909%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=5QiaRm8Bb1ApuPylm0SqE5gW2kYf02ndYWUSSiVUBPA%3D&reserved=0)
 [Unit-6 Creating an Ethical Organization Climate.PPTX](https://can01.safelinks.protection.outlook.com/ap/p-59584e83/?url=https%3A%2F%2Fmytwu-my.sharepoint.com%2F%3Ap%3A%2Fg%2Fpersonal%2Fimbenzi_george_twu_ca%2FEZYMMDHZRiBEmqy9PA3UMVQBPPCGeGThdRdhl8828bqcvg&data=05%7C02%7CKelly.Marjanovic%40twu.ca%7C1dc1cf091e6f4fe4665a08dc1ba8f860%7C2b4ef155167343efa480230c3d483f16%7C0%7C0%7C638415659727131103%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=NxW6GM0rDbLPl8L6GdfsNBumZipNxlvKix5Fz1SnRMY%3D&reserved=0)
 [Unit-5 Ethics and Leadership Theories -Normative Leadership Theories.PPTX](https://can01.safelinks.protection.outlook.com/ap/p-59584e83/?url=https%3A%2F%2Fmytwu-my.sharepoint.com%2F%3Ap%3A%2Fg%2Fpersonal%2Fimbenzi_george_twu_ca%2FEbHPVzisix5JhwqP1w2ZTEoBokDeQjNrrQjzHrEAbAV_3g&data=05%7C02%7CKelly.Marjanovic%40twu.ca%7C1dc1cf091e6f4fe4665a08dc1ba8f860%7C2b4ef155167343efa480230c3d483f16%7C0%7C0%7C638415659727124249%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=HRlENmuuoUu6inzLuxezAX%2B97c%2Fsa4mP29nOl91eBac%3D&reserved=0)
 [Unit-4 Ethical Decision Making- A Compass for Decision Making.PPTX](https://can01.safelinks.protection.outlook.com/ap/p-59584e83/?url=https%3A%2F%2Fmytwu-my.sharepoint.com%2F%3Ap%3A%2Fg%2Fpersonal%2Fimbenzi_george_twu_ca%2FEYMNQ8A8QE5CqjW79m_XSQ0BPirHbm-uNqiTLGy-ulivVQ&data=05%7C02%7CKelly.Marjanovic%40twu.ca%7C1dc1cf091e6f4fe4665a08dc1ba8f860%7C2b4ef155167343efa480230c3d483f16%7C0%7C0%7C638415659727117371%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=yIZnGHOjeRciReRcFZK4RjhM4kx9rKS9jP85m86Mi2U%3D&reserved=0)
 [Unit-3 Leadership Character.PPTX](https://can01.safelinks.protection.outlook.com/ap/p-59584e83/?url=https%3A%2F%2Fmytwu-my.sharepoint.com%2F%3Ap%3A%2Fg%2Fpersonal%2Fimbenzi_george_twu_ca%2FERCd-sKrahRLvqEDKqPZfsIBKKzVnzpxgrtOHADi8YkAKQ&data=05%7C02%7CKelly.Marjanovic%40twu.ca%7C1dc1cf091e6f4fe4665a08dc1ba8f860%7C2b4ef155167343efa480230c3d483f16%7C0%7C0%7C638415659727109735%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Ggj2k4WG5p9IAQB7Q3KfLJH0Ft%2B1KtzqELNiFfBwfxQ%3D&reserved=0)
 [Unit-2 Moral Imagination-What is Responsible Leadership.PPTX](https://can01.safelinks.protection.outlook.com/ap/p-59584e83/?url=https%3A%2F%2Fmytwu-my.sharepoint.com%2F%3Ap%3A%2Fg%2Fpersonal%2Fimbenzi_george_twu_ca%2FEQDDrO9H_m9Nmb4z2bTd68EB9OwjiP4RrK_ugJZUPp41Mg&data=05%7C02%7CKelly.Marjanovic%40twu.ca%7C1dc1cf091e6f4fe4665a08dc1ba8f860%7C2b4ef155167343efa480230c3d483f16%7C0%7C0%7C638415659727100322%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=oo9ANPkzMYw2YvhDmJscSADN3E5wlAy2ks%2Fp4784X4c%3D&reserved=0)
[Unit-1 The Leader’s Light or Shadow.PPTX](https://can01.safelinks.protection.outlook.com/ap/p-59584e83/?url=https%3A%2F%2Fmytwu-my.sharepoint.com%2F%3Ap%3A%2Fg%2Fpersonal%2Fimbenzi_george_twu_ca%2FEX-SZBRadJ1NjnCf1aL558gB-Qie23GaAs4SJEtBhmc8WA&data=05%7C02%7CKelly.Marjanovic%40twu.ca%7C1dc1cf091e6f4fe4665a08dc1ba8f860%7C2b4ef155167343efa480230c3d483f16%7C0%7C0%7C638415659727089520%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=iXlU4syWzI3QTMQV0WWCYEiXldiJtsh%2B0XL22vQeJDo%3D&reserved=0)

**Comment by meher-ahmed** [comment]
Hi @kmarjanovic, for the above pptx files, can you please give me access?

**Comment by kmarjanovic** [comment]
Sorry about that Chloe!  Let me know if these work:

[Unit-1 The Leader’s Light or Shadow.PPTX](https://github.com/TWUOnline/bug-tracking/files/14042060/Unit-1.The.Leader.s.Light.or.Shadow.PPTX)

[Unit-2 Moral Imagination-What is Responsible Leadership.PPTX](https://github.com/TWUOnline/bug-tracking/files/14042061/Unit-2.Moral.Imagination-What.is.Responsible.Leadership.PPTX)

[Unit-3 Leadership Character.PPTX](https://github.com/TWUOnline/bug-tracking/files/14042062/Unit-3.Leadership.Character.PPTX)

[Unit-4 Ethical Decision Making- A Compass for Decision Making.PPTX](https://github.com/TWUOnline/bug-tracking/files/14042063/Unit-4.Ethical.Decision.Making-.A.Compass.for.Decision.Making.PPTX)

[Unit-5 Ethics and Leadership Theories -Normative Leadership Theories.PPTX](https://github.com/TWUOnline/bug-tracking/files/14042064/Unit-5.Ethics.and.Leadership.Theories.-Normative.Leadership.Theories.PPTX)

[Unit-6 Creating an Ethical Organization Climate.PPTX](https://github.com/TWUOnline/bug-tracking/files/14042065/Unit-6.Creating.an.Ethical.Organization.Climate.PPTX)

[Unit-7 Ethical Challenge of Diversity-Leading Responsibly Across Cultures.PPTX](https://github.com/TWUOnline/bug-tracking/files/14042057/Unit-7.Ethical.Challenge.of.Diversity-Leading.Responsibly.Across.Cultures.PPTX)

[Unit-8 Building an Effective Ethical Group-Developing Leadership for Sustainable Business.PPTX](https://github.com/TWUOnline/bug-tracking/files/14042058/Unit-8.Building.an.Effective.Ethical.Group-Developing.Leadership.for.Sustainable.Business.PPTX)

[Unit-9 Overview of Ethical Leadership-How to Develop Responsible Leadership Business.PPTX](https://github.com/TWUOnline/bug-tracking/files/14042059/Unit-9.Overview.of.Ethical.Leadership-How.to.Develop.Responsible.Leadership.Business.PPTX)

**Comment by chloecwh** [comment]
@kmarjanovic I uploaded the PPT to a folder inside instructor resources. Please let me know if it works for you! https://learn.twu.ca/course/view.php?id=30335&section=8

**Comment by kmarjanovic** [comment]
Perfect!  Thanks Chloe!
