### ISSUE TITLE
MA Lead Working Masters SME

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#974]
### Course
[MA Lead Working Masters](https://docs.google.com/document/d/1FCi5xnr_9SRsmz6qwpuuxFPG912yv5Jr1E-0d54azdk/edit#heading=h.mt7cf1d69og7)

### Instructions
- [x] Could you please enroll Cathy Penfold Navarro <C.PenfoldNavarro@twu.ca> in all of the Working Masters?  Role: Teacher

Thank you!

**Comment by chloecwh** [comment]
done @kmarjanovic

**Comment by kmarjanovic** [comment]
Thanks so much, Chloe!
