### ISSUE TITLE
LDRS 591 import content

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#976]
### Course
- [LDRS 591: Scholarly Inquiry (6 week Working Master)](https://learn.twu.ca/course/view.php?id=30336&section=7#tabs-tree-start)  
- [LDRS 591 RD - Scholarly Inquiry (SP 2024)](https://learn.twu.ca/course/view.php?id=31055) - (Doug & Simone)  
- [LDRS 591 D - Scholarly Inquiry (SP 2024)](https://learn.twu.ca/course/view.php?id=31051) - (Rob)  

### Instructions
- [x] Please replace the content in 591 RD & D with the content from the Working Masters.

Please let @deannadams know when this is complete so she can add the correct syllabi.

Thank you!

**Comment by chloecwh** [comment]
@deannadams @kmarjanovic This request is completed. Please let me know if there's anything else I can help with.

**Comment by kmarjanovic** [comment]
Thanks Chloe!

**Comment by deannadams** [comment]
Oh great - thanks Chloe (and Kelly)!
Much appreciated.

DeAnn


DeAnn Adams

Senior Director, Faculty and Academic Services
TWU GLOBAL

**Comment by kmarjanovic** [comment]
@deannadams Rob's gradebook is now correct as well.

Colin & Chloe - in the import, does it work to import gradebook settings as well?  I'm not sure if this was just missed, or whether we do this part manually.

Thanks for your help, Chloe!
