### ISSUE TITLE
LDRS 620 rubrics & assignment info

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#979]
### Course
[LDRS 620: Worldview Foundation Educ Leadership (6 week Working Master)](https://learn.twu.ca/course/view.php?id=30345&section=7#tabs-tree-start)  
[LDRS 620- Worldview FDN of Educ Leadership (FAR MASTER)](https://learn.twu.ca/course/view.php?id=15710&section=6#tabs-tree-start) - original course  
[LDRS 620 D - Worldview FDN of Educ Leadershp (SP 2024)](https://learn.twu.ca/course/view.php?id=31082&section=7) - Karen's section  

### Instructions

Some assignment info and rubrics didn't make it from the grav course to Moodle books.  Please add a page with the info & rubrics  to the 6 week working master, and Karen's class. 

- [x] [Units 1, 3, 4 Reflection Papers](https://learn.twu.ca/course/view.php?id=15710&section=8#tabs-tree-start) 
[LDRS_620_unit_reflection_rubric.docx](https://github.com/TWUOnline/bug-tracking/files/4860120/LDRS_620_unit_reflection_rubric.docx)

- [x] [Unit 2 Reflection and Application Project](https://learn.twu.ca/course/view.php?id=15710&section=9#tabs-tree-start) 
[LDRS_620_reflection_and_application_rubric.docx](https://github.com/TWUOnline/bug-tracking/files/4860119/LDRS_620_reflection_and_application_rubric.docx)

- [x] [Summative Academic Paper](https://learn.twu.ca/course/view.php?id=15710&section=10#tabs-tree-start) 
[LDRS_620_summative_academic_paper_rubric.docx](https://github.com/TWUOnline/bug-tracking/files/4860492/LDRS_620_summative_academic_paper_rubric.docx)

- [x] [Forum Discussion and Engagement](https://learn.twu.ca/course/view.php?id=15710&section=7#tabs-tree-start)
[LDRS_620_forum_post_rubric.docx](https://github.com/TWUOnline/bug-tracking/files/4860126/LDRS_620_forum_post_rubric.docx)

**Comment by chloecwh** [comment]
Working on it

**Comment by chloecwh** [comment]
Hi @kmarjanovic embedded the docs to each assignments dropbox, eg See the [rubric](https://learn.twu.ca/draftfile.php/1198801/user/draft/234438553/LDRS_620_forum_post_rubric.docx) for specific grading criteria.

**Comment by kmarjanovic** [comment]
Thanks Chloe!

Just a note I realized the forum docs had a comment remaining so I replaced with [this](https://learn.twu.ca/pluginfile.php/1288205/mod_resource/content/1/LDRS%20620%20Forum%20Discussion%20and%20Engagement%20Rubric.pdf).  All good now!
