### ISSUE TITLE
LDRS 300 IF FA19 Assessments Tab-Portfolio #2 -Formatting challenges of the list of Values

### ISSUE THREAD

**Issue by BLMSasaki** [TWUOnline/bug-tracking#98]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 
**LDRS 300 IF FA19 Assessments Tab - Portfolio - SLP #2 Portfolio**

**In the moodle the list of values in section 2 is very long. Maybe it can be formatted into a table as it would be easier to read and then work with for the students to complete this assignment.** 

**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 
 
**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  **https://learn.twu.ca/course/view.php?id=10796&section=13**
2. Unit #         Topic #         Activity#  
 

**Optional: Screenshots**

**Comment by cmadland** [comment]
https://github.com/TWUOnline/ba-lead/commit/a3aeeaa9697fa3a46079b5850e619a87e7b0a24d

**Comment by kmarjanovic** [comment]
In looking at the table...I thought perhaps of another option.  
I've created a couple of word clouds, and then provided the list as a pdf.  
@BLMSasaki please let me know what you think.

**Comment by cmadland** [comment]
Way better idea!!

We can post them as images.


--
Colin Madland, MEd (Distance Education)
Online Learning and Instructional Technologies
Trinity Western University  | 7600 Glover Road
Langley, BC | V2Y 1Y1
604.513.2121 ext. 3876 |  colin.madland@twu.ca<mailto:colin.madland@twu.ca>
@colinmadland | create.twu.ca<http://create.twu.ca>

Trinity Western University is located on the traditional, ancestral, and unceded territory of the Sto:lo people.

On Oct 30, 2019, at 8:34 AM, Kelly Marjanovic <notifications@github.com<mailto:notifications@github.com>> wrote:


In looking at the table...I thought perhaps of another option.
I've created a couple of word clouds, and then provided the list as a pdf.
@BLMSasaki<https://github.com/BLMSasaki> please let me know what you think.

**Comment by kmarjanovic** [comment]
Thanks! It's posted:
https://learn.twu.ca/course/view.php?id=10796&section=13
