### ISSUE TITLE
LDRS 300 - PPT remake

### ISSUE THREAD

**Issue by Nataliadsanchez** [TWUOnline/bug-tracking#980]
**LDRS 300?**

Edit the PPT and only keep the 6 slides that explain the 10 attributes of a humble leader [create a H5P?] (Also, remove the final slide, "Pause and Reflect"). 

**PPT**
https://far.twu.ca/ba-lead/ldrs300/presentations/ldrs300-u2-3#/ldrs300-u2-3-0
https://learn.twu.ca/course/view.php?id=10828&section=3#tabs-tree-start

**Comment by Jeff-TWU** [comment]
> **LDRS 300?**
> 
> Edit the PPT and only keep the 6 slides that explain the 10 attributes of a humble leader [create a H5P?] (Also, remove the final slide, "Pause and Reflect").
> 
> **PPT** https://far.twu.ca/ba-lead/ldrs300/presentations/ldrs300-u2-3#/ldrs300-u2-3-0 https://learn.twu.ca/course/view.php?id=10828&section=3#tabs-tree-start

@Nataliadsanchez I'm wondering if it would make more sense to just to use the text (no h5p)? The slides are an accessibility issue, and the images aren't contributing anything important.

**Comment by Nataliadsanchez** [comment]
I agree. Could I please get the text from all the PPTs in LDRS 300? To complete the minor revisions, the SME is asking for the PPTs in Word form so she can add comments and decide which slide(s) - or text - to keep. She was also asking if it is possible to extract the text from the PPTs. Please advise me on this @Jeff-TWU and @chloecwh. Thanks.

**Comment by chloecwh** [comment]
@Nataliadsanchez Sure, it's mostly manual work. I can do that for you first.

**Comment by chloecwh** [comment]
[ldrs300-u2-3.pptx](https://github.com/TWUOnline/bug-tracking/files/14378444/ldrs300-u2-3.pptx)
The text is in the notes section. Still figuring out how to simplify the workflow @Nataliadsanchez

**Comment by chloecwh** [comment]
I think it's faster if I copy the text from images and send you a word doc. Do you need a pdf version of the slides? @Nataliadsanchez

**Comment by Nataliadsanchez** [comment]
A Word doc works. Thanks @chloecwh
