### ISSUE TITLE
PSYCH 106 - Bookdown

### ISSUE THREAD

**Issue by dgaudet48** [TWUOnline/bug-tracking#981]
### PSYCH 106 GX

@cmadland @chloecwh 

Psych 106 was developed by Todd Dutka - the Spring OL course is being taught by a different instructor...

She has provided some edits/updates for the content in Bookdown - however, Todd is pretty protective of the content he developed (there are some videos she wants to remove, for example). 

Is there a process to leave the original content in Bookdown (that Todd developed), and create a new shell for the new instructor for her edits/updates?

Thank you in advance!

**Comment by dgaudet48** [comment]
@cmadland @kmarjanovic  Just re-upping this....

Thoughts on how to best handle this one?

**Comment by kmarjanovic** [comment]
@chloecwh & @cmadland - could we possibly get this solved today?  Mackenzie has been waiting for those edits.\

2 bookdown repos?  1 for GX (Todd) and the other for PSYC ADC (Mackenzie)?

**Comment by chloecwh** [comment]
Hi @kmarjanovic , I'm working on Natalia's ldrs 302 word docs, but I'm happy to hop on this first. @cmadland can you confirm we're creating additional repo and the naming convention for it?

**Comment by chloecwh** [comment]
@cmadland I would need help with forking the branch as well. We're probably referencing the fhss one, right? 

fhss: https://github.com/twu-fhss/psyc106
psyc-adc (empty): https://github.com/psyc-adc/psyc106

**Comment by chloecwh** [comment]
@cmadland @kmarjanovic Created new fork
https://github.com/twu-fhss/psyc106-sp24

Please advise next step and the new edits! (:

**Comment by cmadland** [comment]
hmm...before you edit anything, you might want to edit the repo name so that it isn't a date. Maybe psyc106-td?

**Comment by dgaudet48** [comment]
@chloecwh Thanks!

Here is the document with the edits - is it useable or do you need me to reformat?

[PSYC 106 OL SP 2024 Moodle Edits (1).docx](https://github.com/TWUOnline/bug-tracking/files/14425975/PSYC.106.OL.SP.2024.Moodle.Edits.1.docx)

**Comment by chloecwh** [comment]
It's good! I'll edit it now. @dgaudet48

**Comment by chloecwh** [comment]
https://github.com/twu-fhss/psyc106/issues/24

**Comment by chloecwh** [comment]
Closed issue and moved conversation to psyc 106 repo.
