### ISSUE TITLE
ANTH 101 links

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#983]
### Course
[ANTH 101 X2 - Introduction Cultural Anthropology (SP 2024)](https://learn.twu.ca/course/view.php?id=32165&section=0#tabs-tree-start)

### Instructions

The SME has added her own material for this course, as it starts this week.  Once the course is complete in 6 weeks, we can take the Moodle content and update the bookdown version.

- [x] For now, please go through all the links in the Weeks/Units and change them so they open in a new tab.

@dgaudet48 may have other edits as he reviews the course.

Thank you!

**Comment by chloecwh** [comment]
sounds good, I'm on it!

**Comment by chloecwh** [comment]
updated @kmarjanovic

**Comment by kmarjanovic** [comment]
Thanks Chloe!
