### ISSUE TITLE
SOCI 101 - word doc

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#984]
### Course
[SOCI 101 in bookdown](https://twu-fhss.github.io/soci101/)

### Instructions
- [x] Please convert bookdown material into a word doc for SMEs to edit.

**Comment by chloecwh** [comment]
Hi @cmadland or @Jeff-TWU , I was able to narrow down to unit 1 that's having a bug. Can you help find where it is on unit 1 that's not generating the doc? Thanks!

**Comment by Jeff-TWU** [comment]
> Hi @cmadland or @Jeff-TWU , I was able to narrow down to unit 1 that's having a bug. Can you help find where it is on unit 1 that's not generating the doc? Thanks!

@chloecwh I'll take a look now.

**Comment by Jeff-TWU** [comment]
> > Hi @cmadland or @Jeff-TWU , I was able to narrow down to unit 1 that's having a bug. Can you help find where it is on unit 1 that's not generating the doc? Thanks!
> 
> @chloecwh I'll take a look now.

Found the problem. The issue is that this should have been block2 and not block.
![Screenshot 2024-03-05 at 3 20 15 PM](https://github.com/TWUOnline/bug-tracking/assets/66963480/c639ba40-3f43-4fc8-a9b4-399e40e9c12f)

**Comment by chloecwh** [comment]
Thank you!!!

**Comment by chloecwh** [comment]
[soci101.docx](https://github.com/TWUOnline/bug-tracking/files/14513739/soci101.docx)

@kmarjanovic Here you go! Let me know if you would like to split the documents into units.

**Comment by kmarjanovic** [comment]
This is perfect! Thanks @chloecwh !
