### ISSUE TITLE
PSYC 301 word doc

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#986]
### Course
[PSYC 301 - Theories of Personality (ADC MASTER)](https://learn.twu.ca/course/view.php?id=18759&section=0)

### Instructions
- [x] Please create a word doc for the SME to edit course materials
- [x] For any slideshows, there can just be a placeholder (e.g. insert slideshow) as we hope to replace these.
- [x] If there are other elements that take extra production time (e.g. coding mumbo-jumbo ;), let me know and we can see if it's important for the SME to have in the word doc.

Ideally we'd like this by the end of March.
Thank you!

**Comment by chloecwh** [comment]
I'm on it

**Comment by chloecwh** [comment]
https://mytwu.sharepoint.com/:f:/s/LearningDesign/EuvH_tp0IyVNvtupX99LHREBaXEL13S9seHqFNCKNCm2eg?e=05L3mY
[Overview-PSYC301ADC.docx](https://github.com/TWUOnline/bug-tracking/files/14643487/Overview-PSYC301ADC.docx)
[U1-PSYC301ADC.docx](https://github.com/TWUOnline/bug-tracking/files/14643488/U1-PSYC301ADC.docx)
[U2-PSYC301ADC.docx](https://github.com/TWUOnline/bug-tracking/files/14643489/U2-PSYC301ADC.docx)
[U3-PSYC301ADC.docx](https://github.com/TWUOnline/bug-tracking/files/14643490/U3-PSYC301ADC.docx)
[U4-PSYC301ADC.docx](https://github.com/TWUOnline/bug-tracking/files/14643491/U4-PSYC301ADC.docx)
[U5-PSYC301ADC.docx](https://github.com/TWUOnline/bug-tracking/files/14643492/U5-PSYC301ADC.docx)
[U6-PSYC301ADC.docx](https://github.com/TWUOnline/bug-tracking/files/14643493/U6-PSYC301ADC.docx)

**Comment by kmarjanovic** [comment]
Thank you so much for this, Chloe!  
Could you please create 1 word doc with all the assessment info?  https://learn.twu.ca/course/view.php?id=18759&section=7#tabs-tree-start 
This would include the Moodle forums and any other assessment details in Moodle.

Also - I have a couple comments about the formatting, but it might be helpful to have a Production/ID discussion to see what works best for everyone.
e.g.
- For major/minor revisions, I find it helpful for all units to be in one doc; another doc for assessment, and another for Overview.  For design it makes sense for separate docs, but let's check with IDs & SMEs about their preference.
 
- None of these docs should have the ID design comments (e.g. "Here is where we want to hook our students!")

- The Overview doc shouldn't have an Activity Checklist.  This doc likely won't go to the SME in any case.

As we work through this new process, please let me know if you see any other areas so we can be more efficient!

**Comment by chloecwh** [comment]
Here you go! @kmarjanovic 
[assessment-PSYC301ADC.docx](https://github.com/TWUOnline/bug-tracking/files/14841341/assessment-PSYC301ADC.docx)
I wasn't able to export the Test 1 & 2 questions.

**Comment by kmarjanovic** [comment]
Thanks so much, Chloe!!
No worries about the test questions, as they likely won't be used in the revision.
