### ISSUE TITLE
LDRS 502 broken link

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#989]
**Which course contains the bug?**  
[LDRS 502 working master](https://learn.twu.ca/course/view.php?id=30333),
[LDRS 502 B](https://learn.twu.ca/course/view.php?id=31018&section=3)
 
**Describe the error and/or your suggestion**  
It seems an article wasn’t transferred from the [original course](https://learn.twu.ca/course/view.php?id=17713&section=4#tabs-tree-start).  I’ve attached it here.  Please fix in the master & Derrick's course.

@cmadland process question:  should Derrick ask instructors to update the link, or should Production check the [27 courses for 2024](https://learn.twu.ca/course/search.php?areaids=core_course-course&q=ldrs+502+2024)?
 
[U3_Grigsby.pdf](https://github.com/TWUOnline/bug-tracking/files/14831163/U3_Grigsby.pdf)

**Comment by kmarjanovic** [comment]
Derrick has requested the file be uploaded to the 27 sections.  SP sections a priority.  SU section start end of April.

**Comment by chloecwh** [comment]
@kmarjanovic I'm starting on it!

**Comment by chloecwh** [comment]
@kmarjanovic Added to [LDRS 502 working master](https://learn.twu.ca/course/view.php?id=30333) and
[LDRS 502 B](https://learn.twu.ca/course/view.php?id=31018&section=3)
