### ISSUE TITLE
LDRS 302 IF FA19 Unit 4 Topic 3  - link not working for Caldari article

### ISSUE THREAD

**Issue by BLMSasaki** [TWUOnline/bug-tracking#99]
**Which course contains the bug?**  
- Course Code, section, and term (e.g. LDRS 591 OL SP2019)
 
LDRS 302 IF FA19 Unit 4 Topic 3

**Describe the error and/or your suggestion**  
A clear and concise description of what the error or suggestion is.
 
**Link is not working to the article in the TWU library (says 404 error)**

> Learning Activity 4.3: Read and Reflect
> In this learning activity, begin by reading the following article:
> 
> Caldari (2007). Alfred Marshall's Critical Analysis of Scientific Management.

**Location of the bug**  
Please provide a specific link to the page with the error, as well as where the error is on the page:
1. URL:  https://learn.twu.ca/course/view.php?id=10797&section=6 
2. Unit #         Topic #         Activity#  
 
**Optional: Screenshots**

**Comment by kmarjanovic** [comment]
@dgaudet48 do you have this link from Heather?

**Comment by dgaudet48** [comment]
I will connect with her and ask her if she has a different format

**Comment by cmadland** [comment]
I think I've fixed it. Please test. @BLMSasaki

**Comment by kmarjanovic** [comment]
Seems to work now. Thanks Colin!
