### ISSUE TITLE
TOP Project cards - remove SME payments

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#990]
### Course
All TOP course cards need to be reviewed. My guess is half will have SME info.

### URL

https://github.com/orgs/TWUOnline/projects/30/views/6?pane=issue&itemId=55766425

### Instructions
- [ ] Please move the SME tracking info (comments on payments, triggers, contracts) to the [SME tracking project](https://github.com/TWUOnline/sme-logistics/issues).

***Not a priority!***

**Comment by chloecwh** [comment]
https://github.com/TWUOnline/bug-tracking/issues/961#event-11263420861

https://github.com/TWUOnline/bug-tracking/issues/987#issuecomment-2035301116

Organize into 1 issue... After meeting today, we have decided to hide SME information on the done section of Master Design

**Comment by chloecwh** [comment]
Edited until LDRS 502, no.29
Will work on it tomorrow

**Comment by kmarjanovic** [comment]
Thank you Chloe!  Again, not a priority.  If you want to wait until we have student support workers, this could be a project for them.

**Comment by chloecwh** [comment]
edits done until 50

**Comment by chloecwh** [comment]
completed
