### ISSUE TITLE
Scholarly Learning Foundations - new bookdown for LDRS 500

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#991]
### Course
(LDRS 500](https://learn.twu.ca/course/view.php?id=30331&section=1)

### Instructions
- [x] The 3 books: Days 1-3: Scholarly Learning Foundations - Parts I-3 - need to be put into a new bookdown titled: "Scholarly Learning Foundations"
- [x] Kelly will let Production know when to start moving the content in as Cathy is currently editing the content in Moodle.  (for sure by April 11)
- [x] Note it won't be separated by days or in 3 sections, but by the topics:
1.	What is Dialogue Education?
2.	Dialogue and Leadership
3.	What is Scholarly Inquiry
4.	Asking Significant Questions
5.	What is Leadership?
6.	What is an Idea?
7.	What is Critical Thinking
8.	Analyzing and Making Argument
9.	Analyzing and Using Evidence
10.	Communicating Clearly
11.	Writing in APA Style
12.	Citing the Ideas of Others
13.	Academic Integrity

 ***Due date: April 19*** (will be imported to LDRS 500 sections on April 22)

**Comment by chloecwh** [comment]
so we've settled to name the URL ldrs500-slf? is it build on a separate repo? @kmarjanovic @cmadland

**Comment by kmarjanovic** [comment]
@chloecwh the books are ready to be imported into a bookdown format.  Please let me know if you have questions.
Thank you!
ldrs500-slf makes sense to me.

**Comment by kmarjanovic** [comment]
A note too that we'll keep the Overview on Part 1 as an intro to the book - listing all topics - not just the 5 for part 1.  The Overviews for Part 2 and Part 3 can be deleted.

**Comment by chloecwh** [comment]
Hi @kmarjanovic Here you go! https://learn.twu.ca/course/view.php?id=30331&section=1

I've embedded the bookdown to the shell and edited what's above bookdown in Moodle. 
1. For headings, some units I added H2, titles with underline, is that better or just have H1 for each units? 
2. On the welcome page, do you advise to remove the other 3 blocks? (keep green learning activity)

**Comment by kmarjanovic** [comment]
Thank you Chloe!  That was fast!!

A couple edits..
Let's move the Overview (Unit 1) to the welcome page, so it's not a unit.

On that welcome page...

#Scholarly Learning Foundations
Name  - replace with "A Guide book for Graduate Writing at TWU"

## Introduction

As a graduate student, you will be challenged to think deeply about complex ideas and theories. You will be challenged to write with clarity and precision, to integrate scholarly literature into your writing, and to build strong academic arguments.

This guide book is designed to support you in your development as a scholarly thinker and writer and to help you succeed as a graduate student. 

## Topics

[ insert numbered list]

## Course Notes
You should be reading this information in the context of a Trinity Western University course offered via Moodle. If this is not the case, then this may be an unauthorized reproduction of the course. Please contact [elearning@twu.ca](mailto:elearning@twu.ca) if you have concerns.

delete: These notes will be your guide through the learning activities and assessment strategies necessary for you to succeed in the course, so it is important for you to engage to the best of your ability and take advantage of the resources available to you through Trinity Western University.

delete: Assessment tasks are managed in other sections of the Moodle course, so be sure to familiarize yourself with those requirements and resources.

## How To Navigate This Book
[keep content]


Hide Course Units and course Activities for now

Keep last sentence: If you have any questions, do not hesitate to ask. We are here to help and be your guide on this journey.

**Comment by kmarjanovic** [comment]
@chloecwh could you please archive the Moodle Books for Part 1, 2, and 3?  I was to delete them in the master so instructors don't get confused, but want to make sure we don't lose them.

**Comment by chloecwh** [comment]
@kmarjanovic 
I backed up this course with MB, named it ldrs_500_6wkm-20240418-1353-MB-nu.mbz and now deleted the 3MB. 
Updated Index.Rmd with your request!

**Comment by kmarjanovic** [comment]
Awesome!  Thanks @chloecwh !

**Comment by kmarjanovic** [comment]
@chloecwh A couple more edits:
- [ ] Please add back in the title "Scholarly Learning Foundations" 
- [ ] "A Guide book for Graduate Writing at TWU" should replace "Name"
- [ ] Please hide the [credits section](https://ma-lead.github.io/ldrs500-slf/course-credits.html) until we fill out that content (one of those projects for another time)

Thank you!

**Comment by chloecwh** [comment]
@kmarjanovic Updated

**Comment by kmarjanovic** [comment]
Thanks so much, Chloe!

**Comment by chloecwh** [comment]
@kmarjanovic Hi Kelly, I've restored Moodle and looked at the [MB part 1 ](https://learn.twu.ca/mod/book/view.php?id=1078036). Even through What is Leadership? is in the overview, the chapter is missing... Do you have more information on it?

**Comment by kmarjanovic** [comment]
Let's just delete "What is Leadership?" then.

Can you switch LDRS 500 back to the latest version.  I believe DeAnn is importing 500 into shells this morning.

Also on the intro page for the topics list - can you please change the titles for these two"

Leadership and Dialogue
Analyzing and Making Arguments

**Comment by chloecwh** [comment]
@kmarjanovic updated!

**Comment by kmarjanovic** [comment]
Thanks @chloecwh !
