### ISSUE TITLE
Production - LDRS 663 - Create Word Doc

### ISSUE THREAD

**Issue by inoklim-twu** [TWUOnline/bug-tracking#992]
**Course**
LDRS 663

**URL**
[Leadership 663: Coaching for Transformational Blended Learning](https://ma-lead.github.io/ldrs663/)

**Instructions**

- [ ] Create Word Doc

Please upload required files as attachments.

**Comment by chloecwh** [comment]
Hi @inoklim-twu @cmadland, since Colin is the SME, I wonder if you prefer to edit directly on markdown instead of a word doc?

**Comment by inoklim-twu** [comment]
Hi, @chloecwh @cmadland I like the idea. Let me have a meeting with Colin and let you know if I need your help.
Thank you!

**Comment by cmadland** [comment]
Ya, we won't need word docs for this! 🤓
