### ISSUE TITLE
LDRS 500 activity formatting 

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#994]
### Course
[LDRS 500 working master](https://learn.twu.ca/course/view.php?id=30331&section=2#tabs-tree-start)

### Instructions
The activity sections in the 6 Moodle Books has moved around, so now we need it to match the formatting of the [MA Lead Master template](https://learn.twu.ca/mod/book/view.php?id=915827)
- [x] Please move the Learning Activities from the bottom of the topic to a new subchapter - with no number and in a green box (e.g. [from template](https://learn.twu.ca/mod/book/view.php?id=915827&chapterid=8636))
- [x] Please note in Unit 1 there is a topic "Learning Activities" so no need to fix that section.  

If Production has time to complete this tomorrow, please let me know.  DeAnn is importing the master on Monday, so if there is not enough time (which is okay!!!) then we'll wait until after she imports so we won't get mixed formatting in the books.

Please let me know if you have any questions.
Thank you!

**Comment by chloecwh** [comment]
@kmarjanovic Working on it!

**Comment by chloecwh** [comment]
Hi @kmarjanovic I've updated the formating as best as I can! Let me know if there are any other edits!

**Comment by kmarjanovic** [comment]
Thanks @chloecwh !
