### ISSUE TITLE
LDRS 500 Rubric

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#995]
**Which course contains the bug?**  
[LDRS 500 wrk master](https://learn.twu.ca/mod/forum/view.php?id=967463&forceview=1) 

**Describe the error and/or your suggestion**  
For some reason, I can't replace the discussions rubric.  The new one is attached.  The title should be Discussions Rubric, not Community of Inquiry (it keeps going back to the old pdf version).
 
**Location of the bug**  

Please fix in Units 1-5 discussion forum (end of forum page)

[Discussions Rubric_OL - 2024.pdf](https://github.com/TWUOnline/bug-tracking/files/15045536/Discussions.Rubric_OL.-.2024.pdf)

**Comment by kmarjanovic** [comment]
[Discussions Grading Rubric_OL - 2024.pdf](https://github.com/TWUOnline/bug-tracking/files/15046113/Discussions.Grading.Rubric_OL.-.2024.pdf)

updated to be consistent with other 500 rubrics

**Comment by chloecwh** [comment]
@kmarjanovic Done!

**Comment by kmarjanovic** [comment]
Thanks so much!!
