### ISSUE TITLE
LDRS 101 PLE Image Slider

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#996]
**What course/project is this request for?**
[LDRS 101](https://twu-innovation.github.io/inno101/building-your-online-presence.html#activity-what-is-your-ple)
**Describe the request**
I'd like to show [PLE examples](https://www.notion.so/twuid/Personal-Learning-Network-1d485cd0fb6f462082d681d6efdb9e7d) for [this activity](https://twu-innovation.github.io/inno101/building-your-online-presence.html#activity-what-is-your-ple).  Perhaps use H5P image slider?  Let's discuss next week..

**Priority**
Not a priority

**Comment by MaraChequer** [comment]
Hello @kmarjanovic  are you assigning this task to me?

**Comment by kmarjanovic** [comment]
@MaraChequer I realized H5P requests should go through Production rather than media (video/graphics).  I'll close this issue and reopen when it's a priority.
Sorry for the confusion!

**Comment by MaraChequer** [comment]
👍 No problem!
