### ISSUE TITLE
Production - LDRS 591 import to wk master

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#998]
### Course
[LDRS 591: Scholarly Inquiry (6 week Working Master)](https://learn.twu.ca/course/view.php?id=30336&section=0#tabs-tree-start)

[LDRS 591 OL - Scholarly Inquiry (SU 2024)](https://learn.twu.ca/course/view.php?id=32616) - Cathy's SU OL

### Instructions
- [x] Please copy the OL version of 591 to into the 591 working master

**Comment by Jeff-TWU** [comment]
@kmarjanovic Please provide a bit more info. Looks like the summer course is not hidden, is it live now? Are you wanting to outright replace everything? Does a backup need to take place? More info appreciated. Thanks!

**Comment by kmarjanovic** [comment]
@Jeff-TWU the OL course is live and has all the correct info.  We don't want to change that course, but the master.  We need all of the OL content put into the 591 master as it's the most up to date.

**Comment by Jeff-TWU** [comment]
> @Jeff-TWU the OL course is live and has all the correct info. We don't want to change that course, but the master. We need all of the OL content put into the 591 master as it's the most up to date.

@kmarjanovic Oh my, sleepy brain Jeff. In my brain I reversed it. Glad I checked!
