### ISSUE TITLE
Importing test banks - SOCI 101

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#999]
### Course
SOCI 101 for TOP

### URL
- please create based on TOP template (when decided)

### Questions
- [ ] When using a test bank, is it easier to import the whole file into Moodle and then deselect questions we don't want to use?
- [ ] What format does production need from IDs?

#### Questions
- https://help.openstax.org/s/article/Importing-the-Organic-Chemistry-QTI-Test-Bank-into-Canvas
- https://moodlexml.fly.dev/info/help

### Instructions
- [ ] once the above questions are resolved, please import SOCI 101 test bank

[Sociology3e_AssessmentBanks_xKYNTh8.zip](https://github.com/TWUOnline/bug-tracking/files/15267186/Sociology3e_AssessmentBanks_xKYNTh8.zip)

**Comment by chloecwh** [comment]
@kmarjanovic is this task still needed?

**Comment by kmarjanovic** [comment]
@chloecwh I'll defer to @inoklim-twu & @rankang-twu to confirm.

I assume they are still needed for optional knowledge checks for students.  

Please note the [current GX ](https://learn.twu.ca/course/view.php?id=30133&section=4#tabs-tree-start)(& campus) courses are still using the old textbook ([Real-Life Sociology: A Canadian Approach, (Quan-Haase & Tepperman, 2e).](https://www.vitalsource.com/en-ca/products/real-life-sociology-anabel-quan-haase-lorne-v9780190162757) - with the Unit tests and quizzes using the Oxford Test Bank.  They are using bookdown as well.

I'd suggest we create a new SOCI 101 TOP template in Moodle, branch the bookdown & quarto versions, and then import the openstax testbank for the TOP course.

Does that make sense?

Note this course isn't essential for the Pilot, but it should be an option (unless there are SME delays).

Inok & Ran please confirm with Jason how/if you'd like to use the Open Stax testbank.

**Comment by rankang-twu** [comment]
@chloecwh FYI, Inok and I will be meeting with SME on Sep 5 and give an update accordingly.

**Comment by rankang-twu** [comment]
@chloecwh @kmarjanovic @inoklim-twu SME wants to remove the quizzes for TOP (for January launch) due to low engagement.

**Comment by chloecwh** [comment]
Hi @rankang-twu Are you hoping to hide quizzes from students and adjust the gradebook on GX master or is that note for TOP shell?

**Comment by rankang-twu** [comment]
Hi Chloe,

I think it would make more sense to create a new SOCI 101 TOP template in Moodle without importing quizzes as SME agreed to remove quizzes for TOP. Let me know if you have any further questions.

Ran
________________________________

**Comment by chloecwh** [comment]
Update from @rankang-twu: On hold for making TOP shell
